### PR TITLE
[[ Bug 16415 ]] Fix windows event processing for non-stack windows

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 9ebfbb7

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 9ebfbb7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 9ebfbb764bf2cd5eff6f2f0b13b0901549142c85

**Comment by livecode-vulcan** [comment]
😎 test success 9ebfbb764bf2cd5eff6f2f0b13b0901549142c85
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1552)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1571)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1548)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1559)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1571)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1572)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1574)

**Pull request merged**
