### PR TITLE
[[ Tree View ]] Calculate only 1000 keys worth of subarray display data

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 6848b7b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6848b7b36a06f4da95765c0ed33ef9f7ab0ebc25

**Comment by livecode-vulcan** [comment]
😎 test success 6848b7b36a06f4da95765c0ed33ef9f7ab0ebc25
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/586)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/591)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/586)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/590)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/595)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/587)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/587)

**Comment by peter-b** [comment]
@livecode-vulcan review ok a0e1816

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a0e1816455c469fc1d87c1b8d5f92a98c4e54bb6

**Comment by livecode-vulcan** [comment]
😎 test success a0e1816455c469fc1d87c1b8d5f92a98c4e54bb6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/591)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/596)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/591)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/595)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/600)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/592)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/592)

**Pull request merged**
