### PR TITLE
[Docs] open driver|file|process - Syntax and parameters fixes

### PR DESCRIPTION
**Pull request by seaniepie**
- Add curly braces around variants
- `Encoding` parameter changes

### CODE REVIEW

**Comment by livecodeali** [comment]
@seaniepie I think the full information about the `encoding` parameter that was introduced in 7.0 should probably go in a `Changes:` section after the description. 

Ideally the encoding parameter description should just refer to a separate glossary entry, describing the notion of text encoding, but [currently there isn't one](http://quality.livecode.com/show_bug.cgi?id=18679), so I think the descriptions here should be identical to that of the `textEncode` and `textDecode` entries (which I now notice have a superfluous whitespace problem!)

**Comment by seaniepie** [comment]
Fixed the whitespace issue in both textEncode/Decode also (in separate pull request).

**Comment by livecodeali** [comment]
@livecode-vulcan review ok e01ed36

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok e01ed36e97b4c285bea909f29bad912d72d541de

**Comment by livecode-vulcan** [comment]
😎 test success e01ed36e97b4c285bea909f29bad912d72d541de
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/481)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/486)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/481)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/481)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/487)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/481)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/481)

**Pull request merged**
