### PR TITLE
[[ Bug ]] Ensure marker points are initialised

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 7c6a346

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7c6a3468f6afab3f5ae354f865db6cc7af69ae3a

**Comment by livecode-vulcan** [comment]
😎 test success 7c6a3468f6afab3f5ae354f865db6cc7af69ae3a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/109)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/109)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/109)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/109)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/109)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/109)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/109)

**Comment by montegoulding** [comment]
@livecodeali I did this before the branch but it should go in RC2 so I'll change the target and we can see if @livecode-vulcan spots it ;-)

**Pull request merged**
