### PR TITLE
[[ SB Inclusions ]] Feature mobile inclusions search

### PR DESCRIPTION
**Pull request by livecodeali**
Builds on https://github.com/livecode/livecode/pull/3999 to make search for inclusions work for mobile simulator builds

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali This looks good to me -- feel free to mark as reviewed by me once #3999 is merged.

**Comment by livecodeali** [comment]
@livecode-vulcan review by @peter-b ok ca0d6aa

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ca0d6aac1a9854ec34896fed7b4cfebc8394f2ca

**Comment by livecode-vulcan** [comment]
😎 test success ca0d6aac1a9854ec34896fed7b4cfebc8394f2ca
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2498)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2508)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2491)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2509)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2515)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2519)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2531)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 63f73ec

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 63f73ec0f634d93864017709ab7555bbfcf68392

**Comment by livecode-vulcan** [comment]
😎 test success 63f73ec0f634d93864017709ab7555bbfcf68392
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2499)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2509)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2492)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2510)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2516)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2520)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2532)

**Pull request merged**
