### PR TITLE
clock: General rework

### PR DESCRIPTION
**Pull request by peter-b**
- Improved text layout
- Improved fit to bounding box; widget will never be clipped
- Support "local" timezone by setting timeZone to empty/nothing
- Change timeZone to be expressed in seconds

### CODE REVIEW

**Comment by peter-b** [comment]
Must merge with livecode/livecode-ide/pull/990

**Comment by livecodeali** [comment]
@livecode-vulcan review ok c76b05f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok c76b05f8c362340fd6453110ad7f815500b184b9

**Comment by livecode-vulcan** [comment]
😎 test success c76b05f8c362340fd6453110ad7f815500b184b9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2069)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2081)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2063)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2077)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2084)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2091)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2097)

**Pull request merged**
