### PR TITLE
Copy CEF support files to standalone for stacks using browser widget

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian Just to check -- with these patches, does a normal Debug build on Windows set up the `win-x86-bin` directory in such a way that when you run the debug IDE you can use the browser widget? I noticed that you changed where the engine looks for the CEF helper process binary on Windows, but I didn't see any corresponding gyp file changes...?

**Comment by livecodeian** [comment]
I wasn't aware of aliasReference. shelling out works so will replace if I have time after everything else.

**Comment by livecodeian** [comment]
@peter-b RE: the windows path changes - the actual location hasn't changed but has to be specified here relative to the executable rather than (as was the case for revbrowser) a dynamically loaded dll. libbrowser is statically linked to the engine.

**Comment by livecodeian** [comment]
@peter-b do we really need to handle the case of someone overwriting their existing executable? In any case, the configured paths are cached so it'll only be an issue if that happens before a CEF browser is created.

**Comment by peter-b** [comment]
@livecodeian Technically, there's nothing stopping someone from starting their standalone and then deleting it.  The only question is whether you want to help them work out why they're an idiot with a helpful error message or a messy crash.

I'll take your word for it on the Windows stuff. ;-)

**Comment by runrevmark** [comment]
Okay - so - we should file a bug about the 'deleted' aspect. We can fix for dp-9. Apart from that I think this PR looks good to go.

**Comment by peter-b** [comment]
@runrevmark Agreed!

@livecode-vulcan review ok 55cbdef

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 55cbdef1f879ae425e7fd79c3846838312aac1aa

**Comment by runrevmark** [comment]
Bug about deletion filed here - http://quality.runrev.com/show_bug.cgi?id=16316

**Comment by livecode-vulcan** [comment]
😎 test success 55cbdef1f879ae425e7fd79c3846838312aac1aa
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/932)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/940)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/929)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/933)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/942)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/951)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/946)

**Pull request merged**
