### PR TITLE
[[ Bugfix 14763]]

### PR DESCRIPTION
**Pull request by livecodegeorgia**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodegeorgia Please make sure that the first line of your commit message (and the title of your pull request) concisely summarize the change. :sunglasses:

**Comment by livecodeali** [comment]
I think you have committed the segmented control file in this commit too - this may or may not be deliberate depending on whether the bugfix has been applied to that widget too. If it is deliberate then you should base this branch on feature-widget_segmented so that we can see what the actual diff for this fix is, and so that it merges cleanly.

**Comment by livecode-vulcan** [comment]
📝 Hi @livecodegeorgia, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodesebastien** [comment]
[Bug](http://quality.runrev.com/show_bug.cgi?id=14763) changed to NON_FIXABLE, closing the pull request.

**Pull request closed without merging**
