### PR TITLE
[[ LCS ]] Add 'floor' and 'ceil' functions.

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 9a18a04

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 9a18a044d235d4cce944aea250a25d70cc4df069

**Comment by livecode-vulcan** [comment]
😞 test failure 9a18a044d235d4cce944aea250a25d70cc4df069
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/403)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/465)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/349)
- try-android-armv6: [pending](https://vulcan.livecode.com/builders/try-android-armv6/builds/414)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/349)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/340)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 9a18a04

**Comment by livecode-vulcan** [comment]
😎 test success 9a18a044d235d4cce944aea250a25d70cc4df069
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/408)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/470)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/354)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/419)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/354)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/345)

**Pull request merged**
