### PR TITLE
[[Docs]] keyword/selection - Add link to cut

### PR DESCRIPTION
**Pull request by seaniepie**
- Added links to command and cut
- removed links to self

### CODE REVIEW

**Comment by livecodeali** [comment]
@seaniepie You should keep the 'links to self' in the dictionary entry, as the dictionary makes self-references bold. (removing it from the References list is correct though)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 41da180

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 41da1800e9ad2f3595975ce13b32ac9828268227

**Comment by livecode-vulcan** [comment]
😎 test success 41da1800e9ad2f3595975ce13b32ac9828268227
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/381)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/386)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/381)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/381)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/387)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/381)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/381)

**Pull request merged**
