### PR TITLE
[Bug 15561] Tooltip appears for controls out of the visible window

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok f59a654

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f59a654b7ac3766b30cfe43e87f7a0392771aa4b

**Comment by livecode-vulcan** [comment]
😞 test failure f59a654b7ac3766b30cfe43e87f7a0392771aa4b
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/372)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/435)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/317)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/383)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/318)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/309)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 30f5ddd

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry  f59a654

**Comment by livecode-vulcan** [comment]
😞 test failure f59a654b7ac3766b30cfe43e87f7a0392771aa4b
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/380)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/443)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/326)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/391)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/326)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/317)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry f59a654

**Comment by livecode-vulcan** [comment]
😞 test failure f59a654b7ac3766b30cfe43e87f7a0392771aa4b
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/384)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/447)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/330)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/395)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/330)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/321)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry f59a654

**Comment by livecode-vulcan** [comment]
😎 test success f59a654b7ac3766b30cfe43e87f7a0392771aa4b
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/387)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/450)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/333)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/398)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/333)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/324)

**Pull request merged**
