### PR TITLE
[Bug 15619] Fix "revdberr,invalid database type" error on iOS 

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodepanos** [comment]
I tested this patch on both device and simulator, and it seems to fix bug 15619.

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok  2eafb2f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 2eafb2f74034ff70f2829338da9122467335bb59

**Comment by livecode-vulcan** [comment]
😎 test success 2eafb2f74034ff70f2829338da9122467335bb59
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/670)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/731)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/619)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/683)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/615)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/608)

**Pull request merged**
