### PR TITLE
[[ Bugfix 13580 ]] Use g++ as compiler by default

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
Now it builds, but still tries to link with CC. :disappointed:

**Comment by peter-b** [comment]
Works for me! Thanks for sorting this out.

**Comment by peter-b** [comment]
I've merged this into my `feature-stackdir` branch, but it should probably go into the 7.x stable branch too.

**Comment by livecodeali** [comment]
Merged into release-7.0.1

**Pull request closed without merging**
