### PR TITLE
[Bug 13480] Back port fix for nil pointer crash

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok c78b34d

I'm not sure what release this should go into -- normally it would be scheduled for 6.7.11-rc-1.  However, if I remember correctly, we're already going to be putting non-regression fixes into 6.7.10-rc-2 -- so maybe this should go along with them.  @runrevmark: thoughts?

**Comment by peter-b** [comment]
@montegoulding If we decide that this should go into 6.7.10-rc-2 you'll need to close this PR and open a new one against the "release-6.7.10" branch.

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c78b34dfaa8b84eae301cd52ac8d4f2af835159e

**Comment by montegoulding** [comment]
OK, no problem

**Comment by livecode-vulcan** [comment]
😎 test success c78b34dfaa8b84eae301cd52ac8d4f2af835159e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2006)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2019)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2000)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2012)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2022)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2028)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2032)

**Comment by peter-b** [comment]
@montegoulding This is going into 6.7.11-rc-1

**Pull request merged**
