### PR TITLE
[[ Bug 16294 ]] Improve printing on Linux.

### PR DESCRIPTION
**Pull request by runrevmark**
The Linux printing mechanism has always used a custom PostScript output
to perform its function. However, updating the implementation to work
well (in particular with Unicode and transparency) would duplicate the
work that the PDF printing mechanism already does.

Given that the Linux printing stack will happily accept PDF as well as
PostScript, it makes more sense to update the Linux printer to use the
existing PDF printing mechanism (at least until such time comes that
we can update it to use GTK's cairo based printing model).

This patch hooks up MCPSPrinter to a pdf MCCustomPrinter meaning that
PDF gets generated rather than PostScript.

Tweaks have also been made to the GTK print dialog integration to
reflect this.

Note: Print settings and page settings on linux do not work correctly
as it stands, this needs more work. In particular, the orientation of
paper does not 'stick' correctly.

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevmark Looking at previous code that I've written using the GTK printing API, I think it's necessary to use a `GtkPageSetup` to handle orientation and paper size "correctly".

**Comment by runrevmark** [comment]
@peter-b: Indeed, updating that code can be a separate PR - this PR means printing will work much better in linux (but you need to configure the global printing properties yourself, rather than via a dialog).

**Comment by peter-b** [comment]
@livecode-vulcan review ok 13e6b18

**Comment by peter-b** [comment]
@livecode-vulcan review ok 680af48

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 13e6b186af4a7c327637cb684f1219c1bc629470

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 680af487501f8274d46ae02307e174c5be7cc676

**Comment by livecode-vulcan** [comment]
😎 test success 680af487501f8274d46ae02307e174c5be7cc676
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1349)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1360)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1345)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1355)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1366)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1365)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1370)

**Pull request merged**
