### PR TITLE
Update accept.lcdoc

### PR DESCRIPTION
**Pull request by reducetoflow**
Remove <number>, replaced with portNumber, as read in Ali's blog post.

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @reducetoflow, I haven't been able to verify that you've signed our LiveCode Contributor's Agreement.  Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information. Let me know when you're all signed up. Thanks!

**Comment by reducetoflow** [comment]
doh, sorry about that Peter, was all signed up but under a different email address. I've switched it now in livecode accounts so you should be able to see it.

**Comment by peter-b** [comment]
@livecode-vulcan review ok f348c68

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f348c68c35091f9502b19cfb6945cb7bcdf1f1d8

**Comment by livecode-vulcan** [comment]
😎 test success f348c68c35091f9502b19cfb6945cb7bcdf1f1d8
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/88)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/87)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/87)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/87)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/89)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/87)

**Pull request merged**
