### PR TITLE
[[ Build ]] Fix release notes upload

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Branch tested (and approved) by Vulcan: https://vulcan.livecode.com/builders/installers-commercial/builds/170

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 0784a68

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 0784a6838c40018324aa8b2ef3eb46d8f03347b9

**Comment by livecode-vulcan** [comment]
😎 test success 0784a6838c40018324aa8b2ef3eb46d8f03347b9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1219)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1231)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1216)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1224)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1235)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1235)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1239)

**Pull request merged**
