### PR TITLE
[[ Bug 17633 ]] Fix MCEngineRunloopBreakWait() not working as intended

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodeian: Is there a reason it uses MCNotifyPing here, rather than MCPlatformBreakWait?

**Comment by livecodeian** [comment]
@runrevmark The MCPlatform\* functions are not implemented on Windows or Linux.

**Comment by runrevmark** [comment]
Okay - that makes sense. We need to clean this up a bit at some point as there are a number of places using BreakWait / pingwait() and MCNotify to do the same thing. Really all should vector through one place!

@livecode-vulcan review ok f2117e0

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok f2117e002a6d6cd72137c3f31cb3e9fb2539d700

**Comment by livecode-vulcan** [comment]
😎 test success f2117e002a6d6cd72137c3f31cb3e9fb2539d700
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/18)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/18)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/18)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/18)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/18)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/18)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/18)

**Pull request merged**
