### PR TITLE
[[ MergExt ]] Fix docs builder to use build mergext utility functions

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Needs to be merged after https://github.com/livecode/livecode/pull/3884

**Comment by peter-b** [comment]
@livecode-vulcan review ok d966073

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d9660739d0ba26defca0a8fa2bd1881be6956198

**Comment by livecode-vulcan** [comment]
😎 test success d9660739d0ba26defca0a8fa2bd1881be6956198
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2387)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2397)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2380)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2398)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2404)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2408)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2420)

**Pull request merged**
