### PR TITLE
[Bug 20019] Ensure GetPixelHeightOfCanvas returns the height of canvas

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodepanos This could probably be tested - if you make a `_canvas.lcb` library [here](https://github.com/livecode/livecode/tree/develop/tests/lcs/core/engine) and a handler that creates a new canvas with a given size, and create a `canvas.livecodescript` that does a similar thing to the extension test https://github.com/livecode/livecode/blob/develop/tests/lcs/core/engine/extension.livecodescript#L92

**Comment by livecodeali** [comment]
@livecode-vulcan review ok ea0a0db

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok ea0a0db0565b762945129d16af046de4ef5cf956

**Comment by livecode-vulcan** [comment]
😎 test success ea0a0db0565b762945129d16af046de4ef5cf956

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/472)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/483)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/459)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/402)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/405)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/467)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/473)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/470)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/484)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/470)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/479)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/497)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/466)

**Pull request merged**
