### PR TITLE
[TEST] Vulcanbot reporting build success

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 04304ae

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 04304ae997ff0892eb0959a81c33329d37868147

**Comment by peter-b** [comment]
@livecode-vulcan retry 04304ae

**Comment by livecode-vulcan** [comment]
😭 test error 04304ae997ff0892eb0959a81c33329d37868147
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/133)
- try-win-x86: [error](https://vulcan.livecode.com/builders/try-win-x86/builds/198)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/86)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/143)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/79)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/83)

**Comment by peter-b** [comment]
@livecode-vulcan retry 04304ae

**Comment by livecode-vulcan** [comment]
😎 test success 04304ae997ff0892eb0959a81c33329d37868147
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/134)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/199)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/87)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/144)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/80)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/84)

**Pull request closed without merging**
