### PR TITLE
Variable access performance improvements

### PR DESCRIPTION
**Pull request by peter-b**
Cherry-picked from #5100.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok aefe4fd

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok aefe4fd85f283352a8e01e43ac8e4b9856e0288d

**Comment by livecode-vulcan** [comment]
😞 test failure aefe4fd85f283352a8e01e43ac8e4b9856e0288d

* try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1066)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1069)
* try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1061)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1067)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1071)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1083)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1061)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 5d8e0de

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 5d8e0de89a3f7b18d090005401f93ba843b0b2c1

**Comment by livecode-vulcan** [comment]
😎 test success 5d8e0de89a3f7b18d090005401f93ba843b0b2c1

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1072)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1075)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1067)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1073)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1077)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1089)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1068)

**Pull request merged**
