### PR TITLE
[[ Bug 15396 ]] Implement out-of-handler variable checking for the co…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…mmand value (server-specific)

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodesebastien - could you take a look at the other places where there is no handler context - they are listed here:

http://quality.runrev.com/show_bug.cgi?id=11277

I think there are bug reports on server about merge too - it would be good to get them all working in one go.

**Comment by livecodesebastien** [comment]
Do we want to fix 6.7 as well, or only 7.0? variableNames and localNames work as expected in LiveCode 7.0.5, but do not for 6.7.5

**Comment by runrevmark** [comment]
I obviously did some work on this ages ago then!

We should fix against 6.7+.

**Comment by livecodesebastien** [comment]
This branch will be closed, as we want to fix all the server defects listed in the bug report referred by @runrevmark .

**Pull request closed without merging**
