### PR TITLE
[[ Bug 21156 ]] videoClip not deprecated in dictionary

### PR DESCRIPTION
**Pull request by MWCoastMedia**
Second attempt at my first pull request, thanks for your patience.

I watched Brian Milby's "Git on the source train" presentation from LC Global18 and read Ali's comments on my first attempt. I think I may have this done correctly this time...

### CODE REVIEW

**Comment by montegoulding** [comment]
@WMCoastMedia the only problem is the inclusion of the ide submodule pointer. Are you on command line or a git gui?

**Comment by MWCoastMedia** [comment]
GUI on Mac. I was hinted some command line instructions, but wasn’t sure how to apply them via desktop. 

--Andrew Bell
--Sent from my iPhone

**Comment by montegoulding** [comment]
Hmm... ok well to fix this pr on the command line we need to:
```
cd ide
git checkout a64911479f88b19a609c6774b741f8151485b6b2
cd ..
git add ide
git commit --amend --no-edit
git push -f
```
I'm not really sure you would do that in your git gui

**Comment by livecodeali** [comment]
@livecode-vulcan review ok e4fd64e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok e4fd64e9751aa218076f3d06720ee8d11cc8e5b1

**Comment by livecode-vulcan** [comment]
😎 test success e4fd64e9751aa218076f3d06720ee8d11cc8e5b1

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/389)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/381)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/381)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/381)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/381)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1903)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/131)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/130)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1934)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1924)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1923)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1955)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1896)

**Pull request merged**
