### PR TITLE
[[ Dictionary ]] Fix some issues with the formatting in the mode property

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 0a6352d

Maybe we need to have something about the "right way" to format menu paths in the style guide.

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 0a6352de4edc0ce32c80164492f9e24af430806c

**Comment by livecodeali** [comment]
@peter-b yeah that's a good suggestion.

**Comment by livecode-vulcan** [comment]
😎 test success 0a6352de4edc0ce32c80164492f9e24af430806c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1943)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1956)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1937)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1949)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1959)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1964)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1969)

**Pull request merged**
