### PR TITLE
[[ User Guides ]] Build user guide PDF and include in IDE

### PR DESCRIPTION
**Pull request by livecodeali**
Also implement guide ordering.

Builds on https://github.com/livecode/livecode/pull/3620

### CODE REVIEW

**Comment by livecodeali** [comment]
IDE PR: https://github.com/livecode/livecode-ide/pull/928

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4b54c63

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4b54c63bcd171fbd81f99ceb32f26f1cc759a21a

**Comment by livecodeali** [comment]
Oops, totally jumped the gun there, sorry

**Pull request merged**
