### PR TITLE
build: Add rule for running testsuite in CI system

### PR DESCRIPTION
**Pull request by peter-b**
This commit adds a rule to the buildbot support Makefile to be used
for running the LiveCode testsuites.

**Note:** This PR is being proposed against the `release-8.1.1` branch because the `check` rule needs to be present in all CI-eligible branches.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 7ddfefe

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7ddfefe103fe4f63119aeb7ffc23851bd187aa00

**Comment by livecode-vulcan** [comment]
😎 test success 7ddfefe103fe4f63119aeb7ffc23851bd187aa00
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/420)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/425)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/420)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/420)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/426)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/420)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/420)

**Comment by peter-b** [comment]
I need to add some changes to this branch so that the testsuite isn't run apart from on Mac and Linux (for now).

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 41a35c4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 41a35c49a46d9402f647f573a14990a8dfb21fcd

**Comment by livecode-vulcan** [comment]
😎 test success 41a35c49a46d9402f647f573a14990a8dfb21fcd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/423)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/428)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/423)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/423)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/429)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/423)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/423)

**Pull request merged**
