### PR TITLE
[[ Bug 16476 ]] Add Android platform in the Release Notes

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by peter-b** [comment]
Thank you!

@livecode-vulcan review ok fc9c92c

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok fc9c92c771f60382d340b577f30a0fbeecb69e47

**Comment by livecode-vulcan** [comment]
😞 test failure fc9c92c771f60382d340b577f30a0fbeecb69e47
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1289)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1300)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1285)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1295)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1306)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1305)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1310)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry fc9c92c

**Comment by livecode-vulcan** [comment]
😎 test success fc9c92c771f60382d340b577f30a0fbeecb69e47
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1291)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1302)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1287)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1297)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1308)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1307)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1312)

**Pull request merged**
