### PR TITLE
[[ Bug 14481 ]] Cache the native strings searched by regex on matchText

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by runrevmark** [comment]
@runrevsebastien: I'm not sure I quite understand the approach you've taken here. My understanding of MCStringRef's is that if you do MCStringGetCharPtr() - then the string will automagically be unnativized... i.e. You are guaranteed to be given a unichar_t*. Given that replaceText() is a tight internal loop, there's no chance the source string is going to get changed or mutated during it so you can just call MCStringGetCharPtr() once before the loop.

(Note I think the API docs on the string calls in foundation.h are slightly misleading - the original semantics were that you would not be guaranteed to get a unichar_t\* ptr if the string is native. However, the current behavior is actually better for most uses - i.e. GetCharPtr()/GetNativeCharPtr() will do work to ensure you get what you want - in the latter case, you only get nil if the string cannot be nativized).

**Comment by livecodesebastien** [comment]
@runrevmark : I absolutely agree on the fact that MCStringGetCharPtr() does unnativize its string; but this was an issue (bug 12676) and therefore the code was changed to use MCStringGetChars instead; in each iteration of this tigh loop, the whole string must be converted from char_t to unichar_t. With a string of 300.000 chars (like in the bug report), I let you imagine why LiveCode hangs.

**Comment by runrevmark** [comment]
@runrevsebastien: How does the problem relate to 12676?

The conversion of a string (internally) between native and unicode shouldn't affect any numeric value which is present (although obviously it either needs to be preserved at the end of the char block, or discarded with the string marked as not having one).

Why can you not just pass MCStringGetCharPtr() direct to MCR_exec?

**Comment by livecodesebastien** [comment]
@runrevmark: That should be asked to @runrevali, he's the one who fixed it and changed GetCharPtr to GetChars  - regex.cpp, line 381 (see the diff).
That might have been another effect of the bug 14386 though, and is simply not required anymore

**Comment by runrevmark** [comment]
@runrevsebastien: I've asked @livecodeali to take another look at his original changes to see if they were really needed or a side-effect of something else.

**Comment by livecodeali** [comment]
Ok, https://github.com/runrev/livecode/pull/1782 now fixes this bug, reverting part of the changes from the fix for 12676: https://github.com/livecodeali/livecode/commit/a21da54c9d83d1c88931087170ee23ecfddd4938

**Comment by runrevmark** [comment]
@runrevsebastien: Can you double-check this has been superceded by @livecodeali's fix and close if so?

**Comment by livecodesebastien** [comment]
Yes, I can confirm that the bug 14481 is fixed in this branch.

**Pull request closed without merging**
