### PR TITLE
[[ Bug 18403 ]] Add support for hidden paragraph in styled text

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
@trevordevore we are discussing whether `hidden` should be in or out of the paragraph `style` array. @runrevmark thought you might offer some good input on this seeing as you are a heavy user of styledText. Currently it was out as an undocumented third key for the paragraph and not supported when setting the styledText. This PR puts it into the style element but it's easy enough to change that if we have a plan ;-)

**Comment by runrevmark** [comment]
@trevordevore Just to add to what @montegoulding said - the question here is whether 'hidden' is more 'metadata' like or 'padding' like (the metadata key is not in the style array whilst the hidden key is). I must confess I can't remember the rationale for metadata _not_ being in the style array - maybe that was actually an error and everything should be in the style array. If there is a good use-case for metadata not being in the style array, then we can use that to evaluate whether 'hidden' should or should not be either. (It would be perfectly feasibly to move 'metadata' to the style array - one there would simply override the one in the parent array if present).

**Comment by montegoulding** [comment]
@runrevmark Its seems that paragraph `metadata` isn't a documented key either.

**Comment by runrevmark** [comment]
@montegoulding Might not be documented - but is definitely used ;)

**Comment by trevordevore** [comment]
@montegoulding @runrevmark I think hidden goes into the `style` key. CSS has `display: none;` which is part of a style sheet. 

The argument for metadata could go either way. I think I like keeping `metadata` outside of `style`. One point of view would be that any metadata you store for the paragraph will probably be related to displaying the paragraph. I use it for assigning styles defined by my app to paragraphs that I then use to style the paragraph in LiveCode (e.g. code blocks). But what is stored in the metadata isn't explicitly tied to how the paragraph is rendered.

**Comment by montegoulding** [comment]
Thanks @trevordevore. This PR should probably amend the docs to note the metadata element can be at either the run level or paragraph level as with style.

**Comment by peter-b** [comment]
@montegoulding Is this PR complete other than needing merge conflict resolution?  Is there any other info or work that's needed before it's merged?

**Comment by montegoulding** [comment]
@peter-b yes now that @livecodeian 's PR is merged I'll rebase this and sort out the conflicts ASAP

**Comment by peter-b** [comment]
@livecode-vulcan review ok cf405a9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok cf405a952923a33a5784220f1d53ac5ac752b4d7

**Comment by livecode-vulcan** [comment]
😎 test success cf405a952923a33a5784220f1d53ac5ac752b4d7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/305)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/310)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/305)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/305)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/311)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/305)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/305)

**Comment by montegoulding** [comment]
Marking as WIP until we determine if a paragraph hidden property should inherit from the field hidden property as other properties do. I expect it shouldn't but it's worth confirming now before we merge...

**Comment by montegoulding** [comment]
Rebased and removed WIP

**Comment by peter-b** [comment]
@livecode-vulcan review ok ab52ca5

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ab52ca5f962de0293e68445aa781fc3988731ce8

**Comment by livecode-vulcan** [comment]
😎 test success ab52ca5f962de0293e68445aa781fc3988731ce8

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/756)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/761)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/754)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/755)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/761)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/753)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/753)

**Pull request merged**
