### PR TITLE
[[ Documentation ]] Allow deprecated info to percolate through parser

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 9d641cd

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9d641cd1545bdc26a1ee6942935690e9b023e4ab

**Comment by peter-b** [comment]
@livecode-vulcan review ok ffffe94

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ffffe941eddd9fb3f5f67afca22f70c2fd724a66

**Comment by livecode-vulcan** [comment]
😎 test success ffffe941eddd9fb3f5f67afca22f70c2fd724a66
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2702)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2712)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2697)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2713)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2719)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2725)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2737)

**Pull request merged**
