### PR TITLE
[[ iOS Deployment Broken ]] TextEncode does not exist in LC 6.7

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by runrevmark** [comment]
Don't you still need to encode the strings?

**Comment by livecodesebastien** [comment]
Well we never did in 6.7, the call to textEncode was added in the back port of Monte's templateAppMetada pull request (https://github.com/runrev/livecode/pull/2257/files)

**Comment by runrevmark** [comment]
Hmmm - I think we probably should be UTF-8 encoding the various strings (particularly display name). Otherwise you can't include non-ASCII characters (which on 6.7 means the non-ASCII part of MacRoman).

**Comment by livecodesebastien** [comment]
2 things here:
- the bundle ID can only comprise alphanumeric, hyphen and period, so we won't get any problem with it
- the executable name cannot be set to unicode character at the moment, only can the Display Name (which handles the unicode as it should as for now).
  The need for textEncoding the executable name only came from 7.0 where we can use Unicode chars in the executable name.
  That pull request will bring back revsaveasiosstandalone to its 6.7.5 state, which was handling Unicode for the App display name properly.

**Comment by runrevmark** [comment]
Okay cool :)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 5cb0897

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 5cb089763b75d6dbb29098b20f53dcae264b1a74

**Pull request merged**
