### PR TITLE
[[ Bug 15916 ]] Fix crash when effect spread set to value > 1

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok e2453a7

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok e2453a73e4857ef2a618b7c1c92269875a84ce36

**Comment by livecode-vulcan** [comment]
😎 test success e2453a73e4857ef2a618b7c1c92269875a84ce36
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/423)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/423)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/422)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/421)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/427)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/418)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/429)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 51be9b6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 51be9b6153354bc72954155751b015908a9f32c3

**Comment by livecode-vulcan** [comment]
😎 test success 51be9b6153354bc72954155751b015908a9f32c3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/543)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/547)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/542)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/542)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/551)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/545)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/553)

**Pull request merged**
