### PR TITLE
[emscripten] Refactor standalone startup process

### PR DESCRIPTION
**Pull request by peter-b**
- Add consistency checks to standalone startup process (including check for standalone corruption and check for correct engine version)
- Don't include source code for LCB extensions in commercial standalones
- Standalone startup script is now an actual stack

### CODE REVIEW

**Comment by montegoulding** [comment]
This caught my attention... why do community standalones need the extension source?

**Comment by peter-b** [comment]
@montegoulding Community HTML5 standalones are GPL licensed.  This means that they have to come with the corresponding source code in the preferred form for modification.  For LiveCode stacks, the stack _is_ the source code, so that's fine, but LCB modules are compiled and the separate source code file needs to come too.

Since HTML5 standalones are just zip files, devs could remove the extensions' source code and replace it with a written offer to provide the source code... but putting the code in by default is intended to make it easy for people to comply with the license.

**Comment by montegoulding** [comment]
We need to provide a written offer anyway because we need to provide the engine source too so I don't think it complies with the license anyway. Not a huge issue I guess but possibly not necessary to bloat the builds by default...

**Comment by peter-b** [comment]
Failed tests locally.
@livecode-vulcan review not ok 569fece

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 569fece4182d825394e4f2ec62e76f43f334cb7f

**Comment by peter-b** [comment]
I've updated the pull request, resolving the problems found earlier.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 36f6066

Did you remember to check for velociraptors?

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 36f6066d9fa033b44372aceccd78efe971f11323

**Comment by livecode-vulcan** [comment]
😎 test success 36f6066d9fa033b44372aceccd78efe971f11323
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/745)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/759)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/746)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/748)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/759)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/769)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/761)

**Pull request merged**
