### PR TITLE
[Bug 9744] ios video playback starts with black frame

### PR DESCRIPTION
**Pull request by livecodepanos**
Added a new 'readyForDisplay' property to ios player. This maps to to native readyForDisplay property of MPMoviePlayerController:

"...A Boolean that indicates whether the first video frame of the movie is ready to be displayed.."

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevpanos, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay bc658ad

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok bc658ad05b92ca93b9144dbb90a4b0fc5efdd194

**Comment by livecode-vulcan** [comment]
😎 test success bc658ad05b92ca93b9144dbb90a4b0fc5efdd194
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/210)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/209)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/210)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/205)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/212)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/210)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/213)

**Pull request merged**
