### PR TITLE
[ CI 16425 ] [ CI 16782 ] Prevent memory leaks from export snapshot

### PR DESCRIPTION
**Pull request by livecodepanos**
Conflicts:
    engine/src/exec-interface.cpp

### CODE REVIEW

**Comment by livecodesebastien** [comment]
@runrevpanos: if that fixes http://quality.runrev.com/show_bug.cgi?id=15337, could you add the bugfix note?

**Comment by livecodepanos** [comment]
@livecodesebastien unfortunately it does not fix it. The crash mentioned in this bug report does not seem to be directly related to export snapshot, as it happens even if you comment out the 'export snapshot..' line. However, since there is indeed a memory leak in export snapshot, I created this PR

**Comment by livecodestephen** [comment]
@runrevpanos does the example in bug 15337 still leak memory with this fix, or is the crash caused by something else?  I've been investigating a memory leak in our server code, but have been unable to reduce it to a simple example.  This bug could be similar.

**Comment by livecodepanos** [comment]
@livecodestephen Yes, the sample stack in bug 15337 still leaks memory with this fix (and eventually crashes). Moreover, the memory leak (and crash) happens in LC 6.7.x as well.

**Comment by runrevmark** [comment]
@runrevpanos: Is there a leak in 6.7.x with this stack on Linux? If so we can use valgrind to diagnose (the reason to try and fix in 6.7.x is that it cuts down where the leak is - less searching ;)).

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 97c8cb8

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 97c8cb8474fc7771d369ff120935903704740c62

**Pull request merged**
