### PR TITLE
[[Bug 21003]] mobileGetContactData Dictionary entry has been truncated

### PR DESCRIPTION
**Pull request by jameshale**
slight reformat and addition of missing description of the returned array.

### CODE REVIEW

**Comment by livecodeali** [comment]
@jameshale It might be better to put the details about the returned array in the description section and put something in `The result:` section saying "see description for details" - just because the parameter details get put into a table and it isn't ideal for large amounts of markdown

**Comment by jameshale** [comment]
@livecodeali You are right of course. This was where it was located in the original docs. I guess I was fooled by its incomplete positioning within the result block. I have corrected this now.

**Comment by livecodeali** [comment]
@jameshale Yes the conversion tool I wrote sucked up all the information relating to each parameter from the description so it's my fault in the first place!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 562f49f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 562f49f13081115b03b7bea8299b1e4bcbf4952b

**Comment by livecodepanos** [comment]
@jameshale You also have to change the name and the content of the release note, otherwise our release note parser will be unhappy:

Name:
`docs/notes/Bugfix-21003.md` --> `docs/notes/bugfix-21003.md`

Content:
`[[Bug 21003]] mobileGetContactData Dictionary entry has been truncated
` -> `# Fixed malformed Dictionary entry of mobileGetContactData`

**Comment by jameshale** [comment]
@livecodepanos done :-)

**Comment by livecodepanos** [comment]
Thanks @jameshale :)

@livecode-vulcan review ok 53fef3e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 53fef3ea814ab3270149dd7702e890d00e7acb5d

**Comment by livecode-vulcan** [comment]
😞 test failure 53fef3ea814ab3270149dd7702e890d00e7acb5d

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1233)
* try-community-armv6-android-api9: [pending](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1249)
* try-community-js-emscripten-sdk1.35: [pending](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1223)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/176)
* try-community-universal-ios-iphonesimulator11.2: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/175)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1227)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1253)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1233)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1249)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1232)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1242)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1283)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1225)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 53fef3e

**Comment by livecode-vulcan** [comment]
😎 test success 53fef3ea814ab3270149dd7702e890d00e7acb5d

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1234)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1250)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1224)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/177)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/176)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1228)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1254)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1234)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1250)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1233)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1243)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1284)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1226)

**Pull request merged**
