### PR TITLE
[[ libbrowser ]] Update iOS browser implementation to use WKWebView

### PR DESCRIPTION
**Pull request by livecodeian**
This patch adds a new browser implementation for iOS based on the WKWebView class.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok c41cfd9

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok c41cfd99184bba2173350e002e71d41ef28cbdc2

**Comment by livecode-vulcan** [comment]
😞 test failure c41cfd99184bba2173350e002e71d41ef28cbdc2

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/660)
* try-community-armv7-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/69)
* try-community-arm64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/69)
* try-community-x86-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/69)
* try-community-x86_64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/69)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2186)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/20)
* try-community-universal-ios-iphonesimulator13.1: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/20)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2215)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2202)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2201)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2235)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2175)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 86db34a

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 86db34a27f6ac61709f882f7ede364b087e2286d

**Comment by livecode-vulcan** [comment]
😞 test failure 86db34a27f6ac61709f882f7ede364b087e2286d

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/661)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/70)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/70)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/70)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/70)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2187)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/21)
* try-community-universal-ios-iphonesimulator13.1: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/21)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2216)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2203)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2202)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2236)
* try-community-x86_64-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2176)

**Comment by livecodeian** [comment]
@runrevmark The Windows build issues have been fixed now

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 114f494

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 114f494c67468e617c71d0b496c29f610e6aa6b8

**Comment by livecode-vulcan** [comment]
😎 test success 114f494c67468e617c71d0b496c29f610e6aa6b8

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/664)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/73)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/73)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/73)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/73)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2190)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/24)
* try-community-universal-ios-iphonesimulator13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/24)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2219)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2206)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2205)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2239)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2179)

**Pull request merged**
