### PR TITLE
Uninitialised variables

### PR DESCRIPTION
**Pull request by livecodesebastien**
Add `-Werror=uninitialized` for linux, Android, MacOS and iOS compilation.

Then fix the uninitialised variables, since it became compilation errors.

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 18 of 27 files at r1.
Review status: 18 of 27 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

<sup>**[engine/src/combiners.cpp, line 405 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K-y5G3WgNXmT_OIrshg)** ([raw file](https://github.com/livecode/livecode/blob/c6bd3989b0335d4aa9a3e8e10d187d489479c8f4/engine/src/combiners.cpp#L405)):</sup>
Please use `MCUnreachable()` here (and in similar cases!)



---

<sup>**[engine/src/mblandroiddialog.cpp, line 162 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K-y67ipGdkprtnbmLf9)** ([raw file](https://github.com/livecode/livecode/blob/c6bd3989b0335d4aa9a3e8e10d187d489479c8f4/engine/src/mblandroiddialog.cpp#L162)):</sup>
Maybe avoiding the double negatives in this comment could make it clearer, e.g.

> Ensure t_min/t_max are initialised, even though they aren't used unless t_use_min/t_use_max are true
> 
> 

---

<sup>**[engine/src/mblhandlers.cpp, line 3132 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K-y6UkhLDc2WGDUSEJF)** ([raw file](https://github.com/livecode/livecode/blob/c6bd3989b0335d4aa9a3e8e10d187d489479c8f4/engine/src/mblhandlers.cpp#L3132)):</sup>
I suggest checking `t_success` first here (and in other similar cases).



---

<sup>**[engine/src/mbliphonemail.mm, line 474 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K-y6eArEkgE9vIEK4nT)** ([raw file](https://github.com/livecode/livecode/blob/c6bd3989b0335d4aa9a3e8e10d187d489479c8f4/engine/src/mbliphonemail.mm#L474)):</sup>
It might be a good idea to add:

``` c++
MCAssert(nil != ctxt->attachments[i].file)
```



---

<sup>**[engine/src/srvdebug.cpp, line 447 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K-y6yZjGrIOsjcWCdaR)** ([raw file](https://github.com/livecode/livecode/blob/c6bd3989b0335d4aa9a3e8e10d187d489479c8f4/engine/src/srvdebug.cpp#L447)):</sup>
Please add the `else` here rather than replacing the `"files"` case entirely.



---

<sup>**[libcore/src/module.cpp, line 166 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K-y7IxugMXDOKDVFnnM)** ([raw file](https://github.com/livecode/livecode/blob/c6bd3989b0335d4aa9a3e8e10d187d489479c8f4/libcore/src/module.cpp#L166)):</sup>
The rest of this function uses `nil`, so maybe it would be a good idea to be consistent. :wink: 



---

<sup>**[revbrowser/src/revbrowser.cpp, line 1816 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K-y7mXZmWTRm73AwI44)** ([raw file](https://github.com/livecode/livecode/blob/c6bd3989b0335d4aa9a3e8e10d187d489479c8f4/revbrowser/src/revbrowser.cpp#L1816)):</sup>
Please assert the condition!



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3009)

**Comment by peter-b** [comment]
@livecodesebastien I think I'll have to mark this as needing a little bit more work, sorry. Thank you for taking on this massive job!

@livecode-vulcan review not ok c6bd398

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok c6bd3989b0335d4aa9a3e8e10d187d489479c8f4

**Comment by peter-b** [comment]
Review status: 18 of 27 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[engine/src/combiners.cpp, line 405 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K-y5G3WgNXmT_OIrshg)** ([raw file](https://github.com/livecode/livecode/blob/c6bd3989b0335d4aa9a3e8e10d187d489479c8f4/engine/src/combiners.cpp#L405)):</sup>
Thinking about this further: there's an additional problem here. Whether you use `MCAssert()` or `MCUnreachable()`, both will get compiled out in release builds -- which means that release builds will fail with "-Wuninitialised" errors!



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3009)

**Comment by livecodesebastien** [comment]
@peter-b: pull request updated, with all-platforms now compiling in both Debug and Release modes

**Comment by peter-b** [comment]
Reviewed 13 of 16 files at r2.
Review status: 29 of 32 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[engine/src/mblhandlers.cpp, line 6688 [r2]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K01PW3JlT8iSSohkszF)** ([raw file](https://github.com/livecode/livecode/blob/95f58d3a1426531f159d444e0402217524311a12/engine/src/mblhandlers.cpp#L6688)):</sup>
This should be `&&`, not `&`.  Also, please test `t_success` first.



---

<sup>**[engine/src/mbliphonemail.mm, line 473 [r2]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K01PdJw2dzrB0_QsClE)** ([raw file](https://github.com/livecode/livecode/blob/95f58d3a1426531f159d444e0402217524311a12/engine/src/mbliphonemail.mm#L473)):</sup>
Please remove this code rather than commenting it out.



---

<sup>**[revbrowser/src/revbrowser.cpp, line 1815 [r2]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K01Pq6HU_yI7CObp3oN)** ([raw file](https://github.com/livecode/livecode/blob/95f58d3a1426531f159d444e0402217524311a12/revbrowser/src/revbrowser.cpp#L1815)):</sup>
Please remove commented-out code.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3009)

**Comment by peter-b** [comment]
Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3009)

**Comment by peter-b** [comment]
Thanks for working on this!

@livecode-vulcan review ok e745265



---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3009)

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e745265630694ae897e1677c554b99f9b13a8fbc

**Comment by livecode-vulcan** [comment]
😞 test failure e745265630694ae897e1677c554b99f9b13a8fbc
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/674)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/687)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/675)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/677)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/687)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/698)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/689)

**Comment by peter-b** [comment]
@livecodesebastien What's the plan for moving forward with this PR?

**Comment by livecodesebastien** [comment]
Will be updated as soon as 6.7.8 and 7.1.1 are building :)

**Comment by livecodesebastien** [comment]
Pull request updated: the issue with `-Wno-error=maybe-uninitialized` has been fixed, as well as the errors introduced in `develop-7.0` have been addressed.

**Comment by peter-b** [comment]
@livecodesebastien As discussed with @livecodefraser, I suggest:
- Adding an `MCUnreachableReturn()` macro in order to avoid the `MCUnreachable(); return;` pattern.
- Compiling `MCUnreachable()` (etc.) to `__builtin_unreachable()` in Release mode when using GCC or clang.
  

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3009)

**Comment by livecodesebastien** [comment]
Pull request updated with `__builtin_unreachable` and `MCUnreachableReturn`

**Comment by peter-b** [comment]
Reviewed 14 of 15 files at r6.
Review status: 38 of 39 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[engine/src/gradient.cpp, line 1179 [r6]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K0a91OH18nL3PIJZm5X)** ([raw file](https://github.com/livecode/livecode/blob/027e91ce783731e99197dfe9028b63058f158979/engine/src/gradient.cpp#L1179)):</sup>
Should be `NULL`.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3009)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 027e91c



---

Review status: 38 of 39 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[engine/src/gradient.cpp, line 1179 [r6]](https://reviewable.io:443/reviews/livecode/livecode/3009#-K0a91OH18nL3PIJZm5X)** ([raw file](https://github.com/livecode/livecode/blob/027e91ce783731e99197dfe9028b63058f158979/engine/src/gradient.cpp#L1179)):</sup>
Derp, ignore me. Your patch is correct. Sorry!



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3009)

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 027e91ce783731e99197dfe9028b63058f158979

**Comment by livecode-vulcan** [comment]
😞 test failure 027e91ce783731e99197dfe9028b63058f158979
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/740)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/754)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/741)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/743)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/754)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/764)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/756)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 5ee7849

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 5ee7849689c61c9ff6efc606795b954f41885577

**Comment by livecode-vulcan** [comment]
😎 test success 5ee7849689c61c9ff6efc606795b954f41885577
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/741)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/755)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/742)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/744)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/755)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/765)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/757)

**Pull request merged**
