### PR TITLE
Tile Widget for use within the Start Center.

### PR DESCRIPTION
**Pull request by runrevelanor**
Consists of an SVG icon and label.

Properties that can be set are
- icon name
- hover icon name
- background color
- background hover color
- foreground color (svg icon and label)
- foreground hover color (svg icon and label)

### CODE REVIEW

**Comment by runrevelanor** [comment]
@livecode-vulcan Reviewed by @peter-b ok 026f3ad

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 026f3adfb6f56c2a77eabd054ceeaa357f162a19

**Comment by peter-b** [comment]
Oops — just realised that this needs to be hooked into the build system so that it actually gets compiled and included in the installers!

@livecode-vulcan review not OK 026f3ad

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 026f3adfb6f56c2a77eabd054ceeaa357f162a19

**Comment by peter-b** [comment]
@livecode-vulcan review ok 728eadf

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 728eadf88b9c1f222c7cf259946317a570ab68c7

**Comment by livecode-vulcan** [comment]
💥 merge conflict 728eadf88b9c1f222c7cf259946317a570ab68c7 → 4a01ecd4673c93e593c728737f18798c965a9479

**Comment by peter-b** [comment]
@livecode-vulcan review ok 420eba0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 420eba02f4756873d968148fbd1c735e185ba32c

**Comment by livecode-vulcan** [comment]
😎 test success 420eba02f4756873d968148fbd1c735e185ba32c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1967)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1980)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1961)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1973)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1983)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1988)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1993)

**Pull request merged**
