### PR TITLE
[[ docs ]] added tag to behavior

### PR DESCRIPTION
**Pull request by Skipis**

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @Skipis, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok ecd26e7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok ecd26e75574e78ba7210b2186e07b31a7221fe57

**Comment by livecode-vulcan** [comment]
😎 test success ecd26e75574e78ba7210b2186e07b31a7221fe57
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/38)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/38)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/38)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/38)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/38)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/38)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/38)

**Pull request merged**
