### PR TITLE
[Docs] Intersect function. Remove glossary reference from Syntax example

### PR DESCRIPTION
**Pull request by seaniepie**
If this is in the wrong base, please rebase it for me. I could not see a Livecode 9.5 branch.

### CODE REVIEW

**Comment by livecodepanos** [comment]
Hello @seaniepie thanks for the PR.

>>>>_If this is in the wrong base, please rebase it for me_

It is fine for this PR, but for future reference, the base for community PRs that include dictionary updates should be `develop-9.0`. This means the change will appear in LC 9.0.x, and then we will merge `develop-9.0` into `develop`, so as the change appears in LC 9.5.x as well.

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 9c19c59

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 9c19c59520d1ea9330c616706f62af505cf4d7d6

**Comment by livecode-vulcan** [comment]
😎 test success 9c19c59520d1ea9330c616706f62af505cf4d7d6

* try-community-armv6-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-ndk16r15/builds/6)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/6)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/6)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/6)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/6)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2123)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/348)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/344)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2152)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2139)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2138)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2172)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2112)

**Pull request merged**
