### PR TITLE
[[ Mac64 ]] Use the Cocoa API for enabling/disabling screen updates

### PR DESCRIPTION
**Pull request by livecodefraser**
The Carbon API has been removed in 64-bit.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 739ef4e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 739ef4e361642f71ed9c28b668799687a400a92e

**Comment by livecode-vulcan** [comment]
😎 test success 739ef4e361642f71ed9c28b668799687a400a92e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/961)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/969)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/958)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/962)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/971)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/980)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/975)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 99b74c9

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 99b74c967127cb96a8cfef24ae92323fed469897

**Comment by livecode-vulcan** [comment]
😎 test success 99b74c967127cb96a8cfef24ae92323fed469897
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/988)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/996)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/985)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/989)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/998)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1007)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1002)

**Pull request merged**
