### PR TITLE
[[ Warnings ]] Silence unnecessary build noise

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@montegoulding Please modify the commit message and/or add comments to the source code to explain what build noise this silences and how it silences it! 😉

**Comment by montegoulding** [comment]
@peter-b is the commit msg sufficient now?

**Comment by peter-b** [comment]
@montegoulding It is just lovely 💐 

@livecode-vulcan review ok 9e681d0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9e681d0b987cb8361f85e4c4973272f1381ff007

**Comment by livecode-vulcan** [comment]
😎 test success 9e681d0b987cb8361f85e4c4973272f1381ff007
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/222)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/226)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/222)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/222)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/226)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/222)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/222)

**Pull request merged**
