### PR TITLE
[[ Bug 20722 ]] Update launch URL command note for Android

### PR DESCRIPTION
**Pull request by AndyPiddock**
[[ Bug 20722 ]] Update launch URL command note for Android
Create Bugfix-20722.md

### CODE REVIEW

**Comment by livecodepanos** [comment]
@AndyPiddock I think our release notes parser is case sensitive, so `docs/notes/Bugfix-20722.md` should be `docs/notes/bugfix-20722.md`

I am not sure if you can rename a file from GitHub's web interface, so in this case it would be easier to remove this file from the PR and add a new one with the correct filename

**Comment by livecodepanos** [comment]
@AndyPiddock Ah maybe you _can_ rename it from GitHub's web interface :)

If you click on the Edit button for this file you should be able to Edit the filename as well.

**Comment by livecodepanos** [comment]
Thanks @AndyPiddock 

@livecode-vulcan review ok 825aca6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 825aca6a13ff71f7cb084217226483491f07fbbe

**Comment by livecode-vulcan** [comment]
😎 test success 825aca6a13ff71f7cb084217226483491f07fbbe

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/162)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/154)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/154)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/154)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/154)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1676)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/58)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/58)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1706)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1699)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1696)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1732)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1673)

**Pull request merged**
