### PR TITLE
[Bug 16283] PB is not refreshed to show newly created script only stacks

### PR DESCRIPTION
**Pull request by livecodepanos**
Closes livecode/livecode-ide#583.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 2a72ca5

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2a72ca532ec405bd50f27e48f67edc1a64b0a3d3

**Comment by livecode-vulcan** [comment]
😞 test failure 2a72ca532ec405bd50f27e48f67edc1a64b0a3d3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/864)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/878)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/865)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/868)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/878)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/888)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/881)

**Comment by peter-b** [comment]
@livecode-vulcan retry 2a72ca5

**Comment by livecode-vulcan** [comment]
😎 test success 2a72ca532ec405bd50f27e48f67edc1a64b0a3d3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/868)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/882)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/869)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/872)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/882)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/892)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/885)

**Pull request merged**
