### PR TITLE
Revert using libc++ for mac builds

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 54800d7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 54800d74c9f26caa7c38f0e702e72c8d11211efa

**Comment by livecode-vulcan** [comment]
😎 test success 54800d74c9f26caa7c38f0e702e72c8d11211efa

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/872)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/878)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/870)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/871)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/878)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/869)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/869)

**Comment by livecodeali** [comment]
@livecode-vulcan review not ok 54800d7

**Comment by livecodeali** [comment]
Actually @livecodepanos, we should revert https://github.com/livecode/livecode/pull/4997 properly rather than make a new commit with the revert

**Comment by livecode-vulcan** [comment]
💔 review by @livecodeali not ok 54800d74c9f26caa7c38f0e702e72c8d11211efa

**Comment by livecodepanos** [comment]
@livecodeali sure :)

Replaced by https://github.com/livecode/livecode/pull/5122

**Comment by livecodeali** [comment]
@livecodepanos thanks!

**Pull request closed without merging**
