### PR TITLE
libscript: Add MCScriptCreateModuleFromData().

### PR DESCRIPTION
**Pull request by peter-b**
Convenience function.

### CODE REVIEW

**Comment by livecodeali** [comment]
The 'exec context' version of this exists here:
https://github.com/runrev/livecode/blob/develop/engine/src/exec-extension.cpp#L169

Should that one use yours? And should yours have a resource path parameter?

**Comment by peter-b** [comment]
I don't think it should have a resource path parameter -- that's a package thing that should be handled by the `MCScriptPackage` API in libscript when someone gets round to implementing it.

Yes, I should definitely fix up `MCEngineLoadExtensionFromData()` (and the equivalent function in lc-run) to use `MCScriptCreateModuleFromData()`.  Yay removing code duplication.

**Comment by livecode-vulcan** [comment]
📝 Hi @peter-b, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by peter-b** [comment]
@livecodeali Okay -- I've tweaked a couple of those places.  Is this okay to go now?

**Comment by livecodeali** [comment]
Hooray for auto classes!
@livecode-vulcan review ok 824f862

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 824f86231b4adad8a817b2304507a36c8979e2ae

**Comment by livecode-vulcan** [comment]
😎 test success 824f86231b4adad8a817b2304507a36c8979e2ae
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/205)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/204)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/205)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/200)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/207)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/205)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/208)

**Pull request merged**
