### PR TITLE
Merge develop-6.7 into develop-7.0

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by peter-b** [comment]
N.b. failed tests locally.

**Comment by peter-b** [comment]
@livecode-vulcan review by @runrevmark ok 123f355

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 123f355cc95a8847e94426aa2f96b307d4118bff

**Comment by livecode-vulcan** [comment]
😎 test success 123f355cc95a8847e94426aa2f96b307d4118bff
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/759)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/819)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/709)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/773)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/704)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/696)

**Pull request merged**
