### PR TITLE
[[ Docs ]] Build the built api and build guide json at installer build time

### PR DESCRIPTION
**Pull request by livecodeali**
This is a workaround for DP 3 until https://github.com/runrev/livecode-ide/pull/393 works reliably - probably when we have a browser widget.

### CODE REVIEW

**Comment by runrevben** [comment]
I've set this to reviewed but there is one thought. I noticed that in some of the extensions there is dictionary or guide content but it's minimal at best. I notice in the code that if we find content of any kind we parse it.. is there any form of validation we could do to prevent near empty entries or guide data being added. This is hard I realise but might be worth brainstorming around. 

The solution my need to be on the packaging side.. I.e. reject a build that contains very sparse docs. It should be empty of reasonable?

**Comment by runrevben** [comment]
@livecode-vulcan review ok df26cc8

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok df26cc8c43c337506635b8cd52a102ce85944c07

**Comment by livecode-vulcan** [comment]
😎 test success df26cc8c43c337506635b8cd52a102ce85944c07
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/660)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/720)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/609)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/673)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/605)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/598)

**Comment by livecodeali** [comment]
@runrevben Yes, we could do something like require all user visible properties of a widget to be documented, and require a description of the widget too. One thing that would be good would be to somehow declare what messages are being posted by a widget and enforce documentation of those too...

**Pull request merged**
