### PR TITLE
[[ Documentation ]] Fixes to split.lcdoc

### PR DESCRIPTION
**Pull request by asayd**
- Moved change information to Changes element. 
- Added html5 as a platform.
- Changed comments in examples to #, since // seems to be undocumented.
- Added variable declarations to examples.
- Removed The Result element. Combine does not affect the result.
- Restored content from The Result element to Description element.
- Removed properties tag as inappropriate.
- Added references and links.
- Formatting fixes.
- Added arrays Tag.

### CODE REVIEW

**Comment by asayd** [comment]
@livecodeali @montegoulding  I added a new tag, arrays. This is probably a tags that's really needed. I remember use-list discussions in which people express frustration about where to find info about using arrays. I'm compiling a list of tokens that should be so tagged.

**Comment by asayd** [comment]
@livecodeali I am reconsidering the decision to render the Syntax element in the API dict as LiveCode code. It frequently renders parameter names as LiveCode tokens. It also removes italicization from parameter or variable elements of the syntax, making it difficult to distinguish between fixed syntax and variable elements. I wonder if a better solution would be to render Syntax as monospaced, sort of like an html code tag, and render params as italic like you did previously, and as is done in the pre-8.0 dictionary. What do you think?

**Comment by livecodeali** [comment]
@asayd Yes, I agree - should be relatively easy to tweak it.

**Comment by asayd** [comment]
@livecodeali @montegoulding I can go through and add this tag one-by-one like I did for the messages tag, but I wonder how hard it would be to write a job that would do it all at once, like you did for hard wrapping. These tokens should have the arrays tag:
[](keyword)
array (glossary)
array (keyword)
array dimension (glossary)
arrayDecode (function)
arrayEncode (function)
associative array (glossary)
columnDelimiter (property)
x-combine (command)
delete variable (command)
element (glossary)
extents (function)
intersect (command)
is a (operator)
is among the keys of (operator)
is not among the keys of (operator)
key (glossary)
keys (function)
matrixMultiply (function)
rowDelimiter (property)
x-split (command)
transpose (function)
union (command)
using (keyword)
vectorDotProduct (function)
Others?

**Comment by montegoulding** [comment]
@asayd a docs tag tool would be quite handy

**Comment by livecodeali** [comment]
@livecode-vulcan review ok ccab543

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok ccab543cd98350807c8b290be383ca80e1012eb1

**Comment by livecode-vulcan** [comment]
😎 test success ccab543cd98350807c8b290be383ca80e1012eb1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/114)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/114)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/114)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/114)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/114)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/114)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/114)

**Pull request merged**
