### PR TITLE
[[ Bug 15679 ]] Make sure socket resolution threads are attached to the JVM otherwise certain Android devices crash.

### PR DESCRIPTION
**Pull request by livecodemichael**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 75c77cc

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 75c77cc072791b8217028da546e1496ca3acbb4d

**Comment by livecode-vulcan** [comment]
😞 test failure 75c77cc072791b8217028da546e1496ca3acbb4d
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/753)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/813)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/703)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/767)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/698)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/690)

**Comment by livecodemichael** [comment]
@livecode-vulcan retry 75c77cc

**Comment by livecode-vulcan** [comment]
😎 test success 75c77cc072791b8217028da546e1496ca3acbb4d
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/760)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/820)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/710)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/774)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/705)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/697)

**Pull request merged**
