### PR TITLE
bugfix-16032.md

### PR DESCRIPTION
**Pull request by BerndN**
catch OnMouseCancel in gradientrampeditor

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @BerndN, could you please make this change as part of your other pull request?

**Comment by BerndN** [comment]
Hi @peter-b,  I hope I managed to get it right.

**Comment by peter-b** [comment]
@BerndN: You need to add the bugfix file in your `patch-1` branch, so that it appears as part of #2930.

**Comment by livecodeali** [comment]
@BerndN In theory the instructions here should help!
https://github.com/livecode/livecode/blob/community-docs/docs/CONTRIBUTING.md#adding-a-bug-fix-release-note

**Comment by BerndN** [comment]
@livecodeali, I tried to push from patch-1 branch, don't see if it has worked, sorry, gitHub is not where I feel at home. Thanks for the guidance.

**Pull request closed without merging**
