### PR TITLE
Update version for 8.1.2-rc-2

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok dd3ae38

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok dd3ae38a43484e935888dc229e43557a6545df2c

**Comment by livecode-vulcan** [comment]
😞 test failure dd3ae38a43484e935888dc229e43557a6545df2c
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/584)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/589)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/584)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/588)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/593)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/585)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/585)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry dd3ae38

**Comment by livecode-vulcan** [comment]
😎 test success dd3ae38a43484e935888dc229e43557a6545df2c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/590)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/595)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/590)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/594)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/599)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/591)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/591)

**Pull request merged**
