### PR TITLE
[[Docs]] keyword/segments - New description

### PR DESCRIPTION
**Pull request by seaniepie**
- Added a description based on the segment keyword
- Repaired references section
- Put in a few more links
- Replaced out the curved quotes for actual curved quotes

### CODE REVIEW

**Comment by livecodeali** [comment]
@seaniepie Similarly with this one (see [here](https://github.com/livecode/livecode/pull/4665]) - plus it might be useful to add the segment keyword to the references and link to it in the summary.

**Comment by seaniepie** [comment]
I'm pretty sure the one at the beginning of the description needs to stay as the plural tag as it is referring to itself.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 007178d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 007178dd538a386fb654c154d55d6b2e1dec26d7

**Comment by livecode-vulcan** [comment]
😎 test success 007178dd538a386fb654c154d55d6b2e1dec26d7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/444)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/449)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/444)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/444)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/450)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/444)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/444)

**Pull request merged**
