### PR TITLE
[Bug 1751] Allow more flexible parsing: 'flip the selobj ..', 'flip last img..' etc

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok  063acb1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 063acb141864090ccd5fdda61ba5158b3689a7f6

**Comment by livecode-vulcan** [comment]
😎 test success 063acb141864090ccd5fdda61ba5158b3689a7f6
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/6)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/6)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/6)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/6)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/6)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/6)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok  8fb30f9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8fb30f92734aa711adf9fae14935104afebc949a

**Comment by livecode-vulcan** [comment]
😎 test success 8fb30f92734aa711adf9fae14935104afebc949a
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/8)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/8)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/8)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/8)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/8)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/8)

**Pull request merged**
