### PR TITLE
[[ Bug 16405 ]] Fix crash when closing browser widget on Fedora Linux

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian Thank you for looking into this!

**Comment by peter-b** [comment]
@livecode-vulcan review ok f020919

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f020919c01d34936842fb707b416e7a64407749e

**Comment by livecode-vulcan** [comment]
😎 test success f020919c01d34936842fb707b416e7a64407749e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1254)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1266)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1251)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1260)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1271)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1271)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1275)

**Pull request merged**
