### PR TITLE
[[ Bug 15255 ]] Make DirectX the defult for revvideograbber

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @livecodesebastien, since this is a breaking change that will visibly change users' stacks' behaviour, could you please provide a more detailed release note? Thanks!

@livecode-vulcan review not ok 41f85c5

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 41f85c5a3ca803dfa158611db3aa791c6a1e403a

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3e4548d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3e4548dffea725f6753b0438817229405d0a8f07

**Comment by livecode-vulcan** [comment]
😞 test failure 3e4548dffea725f6753b0438817229405d0a8f07
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/520)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/524)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/519)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/519)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/528)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/522)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/530)

**Comment by peter-b** [comment]
@livecodesebastien That was subtle! :no_mouth: 

@livecode-vulcan review ok 2ec051e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2ec051ebf5eceac46f703546a36bb3b4d4540ce1

**Comment by livecode-vulcan** [comment]
😎 test success 2ec051ebf5eceac46f703546a36bb3b4d4540ce1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/524)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/528)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/523)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/523)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/532)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/526)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/534)

**Pull request merged**
