### PR TITLE
[Bug 19105] Check for stack deletion after do frontscripts

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 10a7872

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 10a7872e6356ce7a900e0ce96d2089419057291e

**Comment by livecode-vulcan** [comment]
😎 test success 10a7872e6356ce7a900e0ce96d2089419057291e

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/891)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/897)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/889)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/890)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/897)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/888)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/888)

**Comment by livecodepanos** [comment]
@montegoulding I think this needs to be rebased against `release-8.1.3`

**Comment by peter-b** [comment]
@livecode-vulcan review ok 85cc49f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 85cc49f0fb9b37e70ec31beb56825373f4a53f28

**Comment by livecode-vulcan** [comment]
😎 test success 85cc49f0fb9b37e70ec31beb56825373f4a53f28

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/904)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/910)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/902)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/903)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/910)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/901)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/901)

**Pull request merged**
