### PR TITLE
[[ Extensions ]] Fix warnings in lc-authored extensions

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 19b4b5f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 19b4b5f8cb3c38dea1cfe8fe882c929688e2c282

**Comment by peter-b** [comment]
@livecode-vulcan review ok 5ad431e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 5ad431e851402c06c1974fe6d4f85bee9421b397

**Comment by livecode-vulcan** [comment]
😞 test failure 5ad431e851402c06c1974fe6d4f85bee9421b397
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/578)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/637)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/527)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/591)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/523)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/516)

**Comment by peter-b** [comment]
@livecode-vulcan retry 5ad431e

**Comment by livecode-vulcan** [comment]
😞 test failure 5ad431e851402c06c1974fe6d4f85bee9421b397
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/579)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/638)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/528)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/592)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/524)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/517)

**Comment by peter-b** [comment]
Okay, don't time out this time, Windows build, pleeease.

@livecode-vulcan retry 5ad431e

**Comment by livecode-vulcan** [comment]
😞 test failure 5ad431e851402c06c1974fe6d4f85bee9421b397
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/593)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/653)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/542)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/606)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/538)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/531)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 5ad431e

**Comment by livecode-vulcan** [comment]
😎 test success 5ad431e851402c06c1974fe6d4f85bee9421b397
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/604)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/664)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/553)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/617)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/549)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/542)

**Pull request merged**
