### PR TITLE
[[ Mac Status Menu ]] Implement mac status menu library

### PR DESCRIPTION
**Pull request by montegoulding**
This patch is an initial implementation of a mac status menu library.

Depends on https://github.com/livecode/livecode/pull/6656

### CODE REVIEW

**Comment by trevordevore** [comment]
@montegoulding if `macStatusMenuDelete` is going to throw an error if the named status menu hasn't been created then I think there should be a function that tests is a status menu exists.

**Comment by montegoulding** [comment]
@trevordevore sorry I missed this comment. Probably it's ok to just do nothing for `macStatusMenuDelete` but perhaps we need something for `macStatusMenuSet` ?

**Comment by trevordevore** [comment]
@montegoulding I guess it depends on if behavior should be similar to how controls act in LC. In LC you get an error if you try to delete a non-existent control (or set a property). You can check for the existence of that control first, however.

**Comment by montegoulding** [comment]
@trevordevore how about `macStatusMenuNames()`... it kills two birds by getting a list of names and allowing a method to check if a name exists.

**Comment by montegoulding** [comment]
Version was 0.0.0 so changed to 1.0.0

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a708f62

**Comment by runrevmark** [comment]
@livecode-vulcan review not ok a708f62

**Comment by runrevmark** [comment]
Okay this is fine - but review needs to wait until #6656 is merged :)

**Comment by livecode-vulcan** [comment]
💔 review by @runrevmark not ok a708f62a44dab3e4bd27f67b0a2100120543b1ca

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 5ea5bd3

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 5ea5bd332c763e05bdf7ac3fbe9b9365b35a5e81

**Comment by livecode-vulcan** [comment]
😎 test success 5ea5bd332c763e05bdf7ac3fbe9b9365b35a5e81

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/525)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/517)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/517)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/517)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/517)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2039)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/267)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/266)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2071)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2061)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2059)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2094)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2031)

**Pull request merged**
