### PR TITLE
[[ Scriptify ]] Scriptify environment stack

### PR DESCRIPTION
**Pull request by montegoulding**
This patch moves all scripts in the environment stack longer than 10 words to
script only behavior stacks and replaces the update libURL target with a
descriptify target which adds libURL and the behavior stacks as substacks
of the environment stack.

### CODE REVIEW

**Comment by runrevmark** [comment]
Just a thought here - would it be better to have:
```
environment.livecode
environment/
    <scriptified behaviors>
```
As the structure? It keeps the scripts which are related to environment.rev all together.

**Comment by montegoulding** [comment]
OK

**Comment by montegoulding** [comment]
This is just a straight rebase onto develop-8.1 after checking there was no diffs on the Environment.rev between develop and develop-8.1

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 6ec599b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 6ec599b6653d744d3390abbb382681bfa711569e

**Comment by livecode-vulcan** [comment]
😎 test success 6ec599b6653d744d3390abbb382681bfa711569e

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/405)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/413)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/392)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/335)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/335)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/400)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/405)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/403)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/410)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/403)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/410)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/429)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/399)

**Pull request merged**
