### PR TITLE
[[ LCB Namespaces ]] Interpret '.' as an LCB namespace operator 

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Requires https://github.com/livecode/livecode/pull/4924

**Comment by peter-b** [comment]
@livecode-vulcan review ok b3f2479

**Comment by peter-b** [comment]
@livecodeali You deserve a 🏅!

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b3f24793254ae9db1225684e73bd92636dd81f29

**Comment by livecode-vulcan** [comment]
😞 test failure b3f24793254ae9db1225684e73bd92636dd81f29

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/654)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/659)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/654)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/658)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/663)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/655)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/655)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1643973

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1643973d97ab5649ac3fbeb74e876594ee82644e

**Comment by livecode-vulcan** [comment]
😎 test success 1643973d97ab5649ac3fbeb74e876594ee82644e

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/655)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/660)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/655)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/659)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/664)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/656)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/656)

**Pull request merged**
