### PR TITLE
Ensure lines in fields are at integer locations

### PR DESCRIPTION
**Pull request by livecodefraser**
There is still a lot of field-related code that doesn't like floating-point layout.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 78fde51

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 78fde51c75419f3b113c28886bbfe62a8816437b

**Comment by livecode-vulcan** [comment]
😞 test failure 78fde51c75419f3b113c28886bbfe62a8816437b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1592)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1611)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1588)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1599)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1612)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1613)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1615)

**Comment by peter-b** [comment]
@livecode-vulcan retry 78fde51

**Comment by livecode-vulcan** [comment]
😎 test success 78fde51c75419f3b113c28886bbfe62a8816437b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1620)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1639)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1616)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1627)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1640)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1641)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1643)

**Pull request merged**
