### PR TITLE
[[ Bug 17377 ]] Fix incorrect browser widget rect after show / hide while in browse mode

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok d368f4f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d368f4fa6093e12a6554db49e1e106d40c0dfb81

**Comment by livecode-vulcan** [comment]
😎 test success d368f4fa6093e12a6554db49e1e106d40c0dfb81
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2404)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2414)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2397)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2415)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2421)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2425)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2437)

**Comment by peter-b** [comment]
This PR should be targeted at `release-8.0.0` branch.  Could you please re-submit? Thanks!

@livecode-vulcan review not ok d368f4f

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok d368f4fa6093e12a6554db49e1e106d40c0dfb81

**Pull request closed without merging**
