### PR TITLE
[[ Bug 20917 ]] Update markdown so schemes display

### PR DESCRIPTION
**Pull request by trevordevore**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@trevordevore thanks for the PR. Could you rebase this onto `develop-9.0`?

**Comment by trevordevore** [comment]
@livecodepanos Yes. I suppose that means the community contribution docs need updating to say to base off of 9.0? If you can confirm that I will make the update.

https://github.com/livecode/livecode/blob/d58cfeda735eceaddf34af4ce9857a52c0de89c5/docs/contributing_to_docs.md

**Comment by livecodepanos** [comment]
@trevordevore Thanks for pointing this out. Yes, all community contributions should be branched off and submitted against `develop-9.0`. Sorry about that, I thought the community contribution docs had been updated already. 

BTW I tried to rebase this PR onto `develop-9.0` from the GitHub web interface and there was a conflict in this file, so it might be the case that this bug is already fixed in `develop-9.0`

**Comment by trevordevore** [comment]
@livecodepanos One typo was fixed in `develop-9.0` but the bug report wasn't fixed. I will rebase.

**Comment by trevordevore** [comment]
Creating new PR.

**Comment by livecodepanos** [comment]
thanks :)

**Pull request closed without merging**
