### PR TITLE
[[ Bug ]] Datagrid standalone builder issues

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecodeali there are some actual blockers in this patch. One is that the legacy fiddling around with the mainstack causes the stackfile recursion handler to copy all the behaviors to the standalone as well so we get duplicates of all of them. This in turn causes stack reload with a different name issues. The other is emscripten wasn't including the behaviors. So now that we have https://github.com/livecode/livecode/pull/6224 I will clean this up.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8ab8bd4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8ab8bd4d8d5ec0358c2b6ddeaf44f65c8a2fc321

**Comment by livecode-vulcan** [comment]
😎 test success 8ab8bd4d8d5ec0358c2b6ddeaf44f65c8a2fc321

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1095)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1111)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1085)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/38)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/38)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1090)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1112)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1095)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1111)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1094)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1104)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1127)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1090)

**Pull request merged**
