### PR TITLE
Remove clipboard index check to prevent compile error when UINDEX_MAX < ULONG_MAX

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 7240b59

**Comment by livecodeali** [comment]
@livecodefraser Sorry, tweaked it to keep the check in if necessary

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 2435bba

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 2435bba49a95162aec37d3dc270a95e49e95c1bd

**Comment by livecode-vulcan** [comment]
😎 test success 2435bba49a95162aec37d3dc270a95e49e95c1bd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1648)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1664)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1643)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1654)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1665)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1667)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1672)

**Pull request merged**
