### PR TITLE
[[ Bug 18343 ]] Fix incorrect result from itemOffset when first character of stringToSearch is the delimiter

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian Please could you add a regression test for this problem?

**Comment by peter-b** [comment]
Thanks @livecodeian!
@livecode-vulcan review ok c6db178

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c6db1781fb6dd0318b74a00f54ebb9db67c2ddc4

**Comment by livecode-vulcan** [comment]
😎 test success c6db1781fb6dd0318b74a00f54ebb9db67c2ddc4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/257)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/261)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/257)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/257)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/261)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/257)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/257)

**Comment by peter-b** [comment]
@livecodeian Can you please rebase this on `develop-8.1`?

**Comment by livecodeian** [comment]
Closing to rebase

**Pull request closed without merging**
