### PR TITLE
[[ Tests ]] Extension unzip folder is always lower case

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
I assume this is needed because LCB identifiers (like module names) are case-insensitive, but the platform filesystem isn't necessarily?

@livecode-vulcan review ok 45624c1

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 45624c158e3a68bed769f03a1abcbe1ef9d42712

**Comment by livecodeali** [comment]
@peter-b Yes, and we explicitly lowercase the last item of the extension type ID when creating a directory to unzip to. We'll either always have to do that, or enforce correct casing in (at least) livecodescript test files.

**Comment by livecode-vulcan** [comment]
😎 test success 45624c158e3a68bed769f03a1abcbe1ef9d42712
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1087)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1096)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1084)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1089)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1100)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1105)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1105)

**Pull request merged**
