### PR TITLE
[[ Bug 15029 ]] Ensure repeat labels are popped in all repeat forms.

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by peter-b** [comment]
I can't review this because I don't understand why the fix works. :disappointed:

**Comment by runrevmark** [comment]
When a repeat clause is compiled it pushes two labels onto a stack - the head label and the tail label (the tail label being the one which is after the 'end repeat'). The up to / down to and for each forms of the repeat form were not popping the label stack at the end and so an exit repeat after such a form was using the wrong labels.

**Comment by peter-b** [comment]
Ah, cool! And using a stack means that you can nest repeats properly. Right. Other VM implementations I've looked at have implemented loops using closures, so there wasn't a stack for nested loops.  Thanks for the explanation!

Reviewed-By: @peter-b

**Comment by peter-b** [comment]
Does this need a VM unit test?

**Comment by runrevmark** [comment]
Hmmm - it would probably be a compiler-test as it is a code-gen bug. The VM doesn't have any notion of 'repeat', just jumps.

Actually - maybe a 'language' test - after all it is the combined effect of compiler + VM which needs to be tested, as well as those two components themselves.

**Pull request merged**
