### PR TITLE
Add script to build the widgets on linux

### PR DESCRIPTION
**Pull request by livecodestephen**
This is still rough, but it seems to work.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 9f10cc0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 9f10cc016cb80fd6bdc3bf2708cc22207e94222f

**Comment by livecodestephen** [comment]
I wasn't really expecting this to be merged, just put it here for reference.  I guess the new gyp build system will make this redundant.

**Comment by livecode-vulcan** [comment]
😞 test failure 9f10cc016cb80fd6bdc3bf2708cc22207e94222f
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/185)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/249)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/138)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/196)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/131)
- try-mac: unknown

**Pull request closed without merging**
