### PR TITLE
Enable LTO for release builds

### PR DESCRIPTION
**Pull request by livecodefraser**
Requires https://github.com/livecode/livecode-thirdparty/pull/40 to be merged.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok af1998d

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok af1998d7319fb4f29b7cecb36e43f1d130232f7f

**Comment by livecodefraser** [comment]
Travis is now happy :)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok d4e894b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d4e894b017c04cdd551547dbcb0ca4919a579601

**Comment by livecode-vulcan** [comment]
😞 test failure d4e894b017c04cdd551547dbcb0ca4919a579601
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1612)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1631)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1608)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1619)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1632)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1633)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1635)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry d4e894b

**Comment by livecode-vulcan** [comment]
😎 test success d4e894b017c04cdd551547dbcb0ca4919a579601
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1621)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1640)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1617)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1628)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1641)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1642)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1644)

**Pull request merged**
