### PR TITLE
[[ Community Docs ]] Ask command minor improvements

### PR DESCRIPTION
**Pull request by asayd**
- Fixed misspelled word;
- Added examples;
- Added clarifying text to description on how to format prompt text;
- Changed 'question' to 'prompt' in syntax and parameters, as a more accurate term.

### CODE REVIEW

**Comment by montegoulding** [comment]
@asayd I think you may be branching from develop and then submitting the PR against community-docs.  Quite possibly the issue is the default branch on GitHub is develop. You need to go to https://github.com/livecode/livecode/tree/community-docs and make edits there.

**Comment by asayd** [comment]
@montegoulding I think you may be right, at least in terms of where I'm starting from. With the help of @mwieder I did figure out how to send the actual PR to the right branch. But starting in the right branch to begin with makes the process lots easier. I wonder if there's a way we noobs can figure things like that out without some handholding.

**Comment by montegoulding** [comment]
@asayd It may help if the default branch on here is community-docs but I can't help wondering if people might find using a good git gui client like SourceTree simpler than the web ui

**Comment by mwieder** [comment]
Ah. OK - maybe ignore my previous comments then... I didn't realize that folks might be using a web ui, and I have no experience with the github ui for editing.

**Comment by peter-b** [comment]
@asayd Could you please rebase your changes on the `community-docs` branch? At the moment merging this pull request would pull in a bunch of changes that we don't want in the `community-docs` branch right now.

@livecode-vulcan review not ok a69ccd9

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok a69ccd9796222edde2e0ed41832066e9e6dbd97b

**Comment by asayd** [comment]
Sorry, Peter. There has been some fair amount of confusion on this issue among us noobs (see use-livecode discussion). I think it's clear now. 
Closing pull request to rebase changes on community-docs.

**Comment by peter-b** [comment]
@asayd Don't worry about it. I submit pull requests against the wrong branches on a semi-regular basis -- it happens. Thanks for taking the time to submit changes!

**Pull request closed without merging**
