### PR TITLE
[Bug 18111] Use "DejaVu Sans" instead of "FontAwesome" in guide PDF

### PR DESCRIPTION
**Pull request by jameshale**
Substitute "DejaVu Sans" for "FontAwesome" in PDF of guide.

### CODE REVIEW

**Comment by jameshale** [comment]
How do I associate the bugfix note with this pull request.
It seems to have created a new one "bugfix-18111-2.md #4452"

**Comment by livecodeali** [comment]
@jameshale You can't associate it - the best thing to do would be to just recreate the bugfix note from here: https://github.com/jameshale/livecode/tree/patch-3

Anything you commit to the patch-3 branch will show up in this pull request.

However, I'm not sure a release note is required here - we could potentially change the version of the old release note. Otherwise we might want to report a new bug, I'm not sure!

**Comment by jameshale** [comment]
Yes I wasn't sure it needed one. I have seen other requests where they were a second attempt to fix something and they didn't have a repeat note. I would delete it if I knew how to and wait until I am told it is required.

**Comment by peter-b** [comment]
@jameshale Usually it's preferable to delete code rather than commenting it out, unless it's very likely that the code will be reinstated in the future.  Something to bear in mind for next time!

@livecode-vulcan review ok b718697

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b7186974b7ae0250b9be59d27bda0e0de482cafc

**Comment by livecode-vulcan** [comment]
😎 test success b7186974b7ae0250b9be59d27bda0e0de482cafc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/143)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/147)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/143)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/143)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/143)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/143)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/143)

**Comment by jameshale** [comment]
Thanks @peter-b

**Pull request merged**
