### PR TITLE
[[ Bug 15743 ]] binzip-copy target cannot copy dSYM files in Debug mo…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…de, since the debug symbols are not extracted.

### CODE REVIEW

**Comment by peter-b** [comment]
This looks like one for @livecodefraser  to review!

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay b07d02f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok b07d02fe1f29c0e9a82e4d748199c434c22b8813

**Comment by livecode-vulcan** [comment]
😞 test failure b07d02fe1f29c0e9a82e4d748199c434c22b8813
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/45)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/45)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/45)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/45)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/47)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/45)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry b07d02f

**Comment by livecode-vulcan** [comment]
😎 test success b07d02fe1f29c0e9a82e4d748199c434c22b8813
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/46)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/46)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/46)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/46)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/48)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/46)

**Pull request merged**
