### PR TITLE
Gyp rejig warnings 7.0

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 443796f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 443796f61f9f19df29411481a84d269f170a4824

**Comment by livecode-vulcan** [comment]
😞 test failure 443796f61f9f19df29411481a84d269f170a4824
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/256)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/319)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/207)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/267)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/202)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/199)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3bc2559

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3bc25594811284ea93f5b0e0f76aac15b5bad7d4

**Comment by livecode-vulcan** [comment]
😎 test success 3bc25594811284ea93f5b0e0f76aac15b5bad7d4
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/264)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/327)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/214)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/275)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/210)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/206)

**Pull request merged**
