### PR TITLE
[[ Extensions ]] Make widget and library names more sensible

### PR DESCRIPTION
**Pull request by livecodeali**
[Review on Reviewable](https://reviewable.io/reviews/runrev/livecode/2742)

### CODE REVIEW

**Comment by livecodefraser** [comment]
This patch looks good but I'll need to check it won't break anything when building our installers - there's a dirty hack that assumes the extension names follow a particular pattern.

**Comment by peter-b** [comment]
@livecodefraser What testing still needs to be done on this one?

**Comment by peter-b** [comment]
@livecode-vulcan review ok 5c261a8

Since this passed the installer build check. :+1:

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 5c261a8bfbc4c658141137e5ab2ce18ce37b4718

**Comment by livecode-vulcan** [comment]
😎 test success 5c261a8bfbc4c658141137e5ab2ce18ce37b4718
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/97)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/96)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/96)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/96)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/98)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/96)

**Comment by mwieder** [comment]
I realize this was implemented in dp3, but now that we're almost at dp11, is there a chance of extending this to the directory naming as well? You can address a widget as 'com.livecode.widget.clock', but the directory is still 'com.livecode.extensions.livecode.clock'.

**Pull request merged**
