### PR TITLE
[[ Foundation ]] Add API to convert MCNumberRef to CFNumberRef.

### PR DESCRIPTION
**Pull request by runrevmark**
This patch adds a new API MCNumberConvertToCFNumberRef which
converts an MCNumberRef to the equivalent CFNumberRef.

### CODE REVIEW

**Comment by peter-b** [comment]
I wish we could use

``` C++
#if defined(HAVE_COREFOUNDATION)
```

instead of

``` C++
#if defined(__MAC__) || defined (__IOS__)
```

@livecode-vulcan review ok ee2d9d9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ee2d9d99e02debd3a5fd26ef4ab82cb9b429f3a3

**Comment by runrevmark** [comment]
@peter-b perhaps something to put on a cleanup list :)

**Comment by livecode-vulcan** [comment]
😎 test success ee2d9d99e02debd3a5fd26ef4ab82cb9b429f3a3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1731)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1746)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1726)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1737)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1747)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1750)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1755)

**Pull request merged**
