### PR TITLE
[[ AndroidNFC ]] Enable NFC tag reading on Android

### PR DESCRIPTION
**Pull request by livecodeian**
This PR adds support on Android for reading data from NFC tags.
functions added: mobileIsNFCAvailable, mobileIsNFCEnabled
commands added: mobileEnableNFCDispatch, mobileDisableNFCDispatch
message added: nfcTagReceived

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 71ffc76

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 71ffc76fce83ce2eeaa5d63b17c41987e729cf4c

**Comment by livecode-vulcan** [comment]
😞 test failure 71ffc76fce83ce2eeaa5d63b17c41987e729cf4c

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/982)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/988)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/980)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/981)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/988)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1002)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/979)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 6511df6

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 6511df62e3e45daf791682227c9c80c3b8d65215

**Comment by livecode-vulcan** [comment]
😎 test success 6511df62e3e45daf791682227c9c80c3b8d65215

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/983)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/989)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/981)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/982)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/989)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1003)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/980)

**Pull request merged**
