### PR TITLE
Coverity defects fixes

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by peter-b** [comment]
Which milestone are these planned for?

**Comment by livecodesebastien** [comment]
7.0.4-rc-1 - need a fix for broken iOS compilation...

**Comment by livecodesebastien** [comment]
@peter-b : Can you review #1930 and this one?

**Comment by peter-b** [comment]
Normally I wouldn't add a comment for removing dead code. :wink: 

Reviewed-By: Peter TB Brett peter@livecode.com

**Pull request merged**
