### PR TITLE
[[ LogicTests ]] Rewrite logic tests

### PR DESCRIPTION
**Pull request by livecodesebastien**
Add more tests for comparison operators
Move TestIsA from core/engine/object.livecodescript to core/logic/logic.livecodescript

Fix doc entry for <is a>: hexadecimal strings (like `"0xef"`) are also numbers

Note that https://github.com/livecode/livecode/pull/3348 must be merged in, to allow the test for `empty is a ascii string` to succeed

### CODE REVIEW

**Comment by peter-b** [comment]
Test failed on Travis.

@livecode-vulcan review not ok eb36082

**Comment by peter-b** [comment]
@livecode-vulcan review ok eb36082

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok eb360825d99e160de27589705d0ecf25a0f49841

**Comment by livecode-vulcan** [comment]
😎 test success eb360825d99e160de27589705d0ecf25a0f49841
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1335)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1346)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1331)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1341)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1352)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1351)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1356)

**Pull request merged**
