### PR TITLE
[[ Bug 14015 ]] urldecode and urlencode broken with Unicode characters

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by runrevmark** [comment]
I think this needs more thought - the encoding of URLs has long been encoding-defined-by-server obviously these days UTF-8 does make more sense. This change will break scripts which are passing high-bit set native encoded characters to a server.

A bit of research needs to be done on what best-practice is (RFCs will probably contain this) and we need to implement better url encode/decode conformant to an appropriate RFC, without breaking existing scripts.

**Comment by livecodesebastien** [comment]
I found this issue while fixing the bug 13993, since URLs are used on Linux for the file paths. Encoding/decoding URLs is surely something that should be not broken for the servers, and more important that being able to drag and drop Unicode filenames on Linux; I'll see more in details the RFC rules for it.

**Comment by runrevmark** [comment]
Okay - so if the thing you are interacting with dictates UTF-8 %-encoded url's then that is fine (I believe the ones you get from NSURL / CFURL on Mac are like this and such) - but we need to be careful not to affect the urlDecode() /Encode() functions in script. Thus perhaps just add a parameter which indicates whether to do UTF-8 conversion or not. We can then sort out script-level urlEncode/urlDecode subsequently, whilst fixing the internal issue with drag-drop filenames.

**Comment by livecodesebastien** [comment]
Pull request updated: only decode/encode URLs using the percent-encoding when explicitly asked (for now, only for internal use).

**Comment by livecodesebastien** [comment]
RFCs to be considered for the script level of URL de/encoding: 2396 and 3986

**Pull request merged**
