### PR TITLE
[Bug 3412] Ask and answer commands don't invoke resumeStack message upon close

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@runrevpanos: Are you sure this is an engine problem and not the IDE or script somewhere interfering with the normal flow of messages?

**Comment by livecodepanos** [comment]
@runrevmark: When the ask/answer dialog is closed, the messages are locked. This is the reason why the resumeStack msg is not sent. If I comment out the 'lock/unlock messages' lines, then the resumeStack msg is sent. According to the comment in the relevant IDE script (i.e. stack Answer Dialog, card id 1002, on mouseUp handler), we lock messages "to prevent user stack getting refocusing messages".

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevpanos, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by runrevmark** [comment]
I think the bug here lies elsewhere - it is script in the IDE which is stopping the message, not the engine so the engine does't need to be sending another after answer/ask.

**Comment by trevordevore** [comment]
FWIW the issue is definitely the IDE scripts. The first thing I do when I install a new version of LiveCode is comment out the lock/unlock message calls in the ask and answer dialogs. The locks create all sorts of havoc by failing to send messages when the stack is closed thus creating a scenario where you have unbalanced message. For example, you are notified that focus has left a stack when the answer dialog opens but you don't know that focus returned. If you have code that relies on balanced messages to work then you become rather confused as to why it breaks when the answer dialog pops up :-)

**Comment by peter-b** [comment]
@livecodepanos I'm going to close this pull request for now, since no progress has been made for a few months.  Please re-open it if necessary. Thanks!

**Pull request closed without merging**
