### PR TITLE
[[ Bug ]] Use custom function for string compare in rgb test

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
I have no idea why this wasn't crashing before!

@livecode-vulcan review ok 2501b74

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2501b74cfb7a097c3cac079f5c7c8f9d2b625347

**Comment by livecode-vulcan** [comment]
😞 test failure 2501b74cfb7a097c3cac079f5c7c8f9d2b625347
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/526)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/531)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/526)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/530)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/535)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/527)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/527)

**Comment by peter-b** [comment]
@livecode-vulcan retry 2501b74

**Comment by livecode-vulcan** [comment]
😞 test failure 2501b74cfb7a097c3cac079f5c7c8f9d2b625347
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/528)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/533)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/528)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/532)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/537)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/529)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/529)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 36fd93b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 36fd93b0b6735966daf7af0de266eaca096bf7dd

**Comment by livecode-vulcan** [comment]
😎 test success 36fd93b0b6735966daf7af0de266eaca096bf7dd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/530)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/535)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/530)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/534)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/539)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/531)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/531)

**Pull request merged**
