### PR TITLE
build: Use Xcode 6.4

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 539e491

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 539e4916ede7bff2b68a1377fd0ea79810fcea2d

**Comment by livecode-vulcan** [comment]
😎 test success 539e4916ede7bff2b68a1377fd0ea79810fcea2d
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/348)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/411)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/293)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/359)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/294)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/285)

**Comment by peter-b** [comment]
@livecode-vulcan retry 539e491

**Comment by livecode-vulcan** [comment]
😞 test failure 539e4916ede7bff2b68a1377fd0ea79810fcea2d
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/369)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/432)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/314)
- try-android-armv6: [pending](https://vulcan.livecode.com/builders/try-android-armv6/builds/380)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/315)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/306)

**Comment by peter-b** [comment]
@livecode-vulcan retry 539e491

**Comment by livecode-vulcan** [comment]
😞 test failure 539e4916ede7bff2b68a1377fd0ea79810fcea2d
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/394)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/456)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/340)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/405)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/340)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/331)

**Comment by peter-b** [comment]
@livecode-vulcan retry 539e491

**Comment by peter-b** [comment]
This is going to be dealt with by #2543.

**Pull request closed without merging**
