### PR TITLE
[[ Merge develop 7.0 ]] 06-10-15

### PR DESCRIPTION
**Pull request by livecodesebastien**
All the conflicts in libfoundation were due to the addition of MC_DLLEXPORT and MC_DLLEXPORT_DEF
in LiveCode 8.
Clean merge otherwise

Conflicts:
    libfoundation/include/foundation.h
    libfoundation/src/foundation-data.cpp
    libfoundation/src/foundation-string.cpp

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 2f7d4be

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 2f7d4be360407a20d5a37417c887c2475aa23a50

**Comment by livecode-vulcan** [comment]
😞 test failure 2f7d4be360407a20d5a37417c887c2475aa23a50
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/641)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/653)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/642)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/643)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/652)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/663)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/654)

**Comment by livecodesebastien** [comment]
Pull request updated (fix `MC_DLLEXPORT_DEF` added to static function)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 8ce7aaf

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 8ce7aaf1ea1c5d46331d7cb19e1f1a2d74a7453f

**Comment by livecode-vulcan** [comment]
😎 test success 8ce7aaf1ea1c5d46331d7cb19e1f1a2d74a7453f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/644)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/656)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/645)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/646)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/655)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/666)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/657)

**Pull request merged**
