### PR TITLE
Fix a merge issue that broke Reflex

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 231b53c

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 231b53c2c8396dd20aa0de849b64062c63986186

**Comment by livecode-vulcan** [comment]
😞 test failure 231b53c2c8396dd20aa0de849b64062c63986186
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/225)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/289)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/178)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/236)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/171)
- try-mac: unknown

**Comment by runrevmark** [comment]
Superceeded by #2452

**Pull request closed without merging**
