### PR TITLE
[[ ObjectDeletion ]] Pay more attention not to remove the target stac…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…k from memory at standalone saving, as objects are now deleted more frequently

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 3e8e798

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 3e8e798b8352d3b685ac1643bd186eb6093b7283

**Comment by livecodesebastien** [comment]
Only affects Saving as standalone from the IDE, the CI can be skipped.

**Comment by livecode-vulcan** [comment]
⁉ merge unchanged 3e8e798b8352d3b685ac1643bd186eb6093b7283 → 88a6c14ed218f1fd531e50a5ece6f0b0e64a419d

Pull request is already fully merged!

**Pull request merged**
