### PR TITLE
[[ RemoveCefOSX ]] Remove CEF libs from OSX builds

### PR DESCRIPTION
**Pull request by livecodeian**
This removes support for CEF from revbrowser and libbrowser, and updates the standalone builder script to no longer copy CEF support files during OSX deployment

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian Do you think that removing the `browserType` property from the browser widget should go into this PR too? Or is it better as a separate PR?

**Comment by livecodeian** [comment]
I was going to make it a separate PR

**Comment by livecodeian** [comment]
The reason for removing browserType is that after this PR is merged it will no longer have any purpose, so logically it comes after. I suppose I could make it part of this.

**Comment by peter-b** [comment]
@livecodeian With these changes applied, does setting the `browserType` to CEF make the engine sad? If not, lets make its removal a separate PR!

@livecode-vulcan review ok b147d09

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b147d09bc91a55e787a2ef1ea12f1c0a1697f482

**Comment by livecodeian** [comment]
@peter-b in terms of engine sadness, setting the browserType to CEF should just make the browser not work in a non-crashy way

**Comment by peter-b** [comment]
@livecodeian Something weird is going on with this PR... I don't understand why those svgpath commits are appearing there...

**Comment by livecodeian** [comment]
@peter-b I'm really not sure why those commits are listed - they don't appear to have an impact on the "Files changed" view though

**Comment by livecode-vulcan** [comment]
😎 test success b147d09bc91a55e787a2ef1ea12f1c0a1697f482
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2065)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2077)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2059)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2073)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2080)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2087)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2093)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 2842189

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 28421891c28e4532e93a6c4f50d1c24567256a79

**Comment by livecode-vulcan** [comment]
😎 test success 28421891c28e4532e93a6c4f50d1c24567256a79
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2074)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2085)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2068)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2082)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2088)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2096)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2102)

**Pull request merged**
