### PR TITLE
[Bug 17695] Improve the glossary entry for "highlight"

### PR DESCRIPTION
**Pull request by peter-b**
- Remove the massive list of synonyms, since these are only really
  relevant to the property.
- Make the explanation grammatical
- Provide an example

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 923badb

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 923badb24f5688c2587cb78ffbbb319e191081a6

**Comment by livecode-vulcan** [comment]
😎 test success 923badb24f5688c2587cb78ffbbb319e191081a6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2532)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2542)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2527)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2543)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2549)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2553)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2565)

**Pull request merged**
