### PR TITLE
[[ Bug 15764 ]] Android player class name is VideoControl, not Player…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…Control

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/runrev/livecode/2748)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 512fbd0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 512fbd02b48ba80f1bfd1c2330bb3bfc30ca0660

**Comment by livecode-vulcan** [comment]
😎 test success 512fbd02b48ba80f1bfd1c2330bb3bfc30ca0660
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/98)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/97)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/97)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/97)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/99)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/97)

**Pull request merged**
