### PR TITLE
build: Add -Werror=conversion-null to the build settings

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by peter-b** [comment]
Urgh.  This should be `-Werror=conversion-null`, of course...

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 8cbc68b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 8cbc68b1675a2b2a3131c4b547ad30d688636bac

**Comment by livecode-vulcan** [comment]
😞 test failure 8cbc68b1675a2b2a3131c4b547ad30d688636bac
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2733)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/2743)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2728)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2744)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/2750)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2756)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2768)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay c543ef6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok c543ef69e8298c397514b1ff7ace214d14591468

**Comment by livecode-vulcan** [comment]
😞 test failure c543ef69e8298c397514b1ff7ace214d14591468
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2736)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/2746)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2731)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2747)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/2753)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2759)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2771)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 54b6d26

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 54b6d260ebab7e8196cb3c0f40bfe33d7b3a3726

**Comment by livecode-vulcan** [comment]
😞 test failure 54b6d260ebab7e8196cb3c0f40bfe33d7b3a3726
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2737)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/2747)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2732)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2748)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/2754)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2760)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2772)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay b744b2b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok b744b2b5e87217186c8527a05e0f716f9265f0be

**Comment by livecode-vulcan** [comment]
😞 test failure b744b2b5e87217186c8527a05e0f716f9265f0be
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2738)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/2748)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2733)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2749)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2755)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2761)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2773)

**Comment by peter-b** [comment]
I'll refactor this branch and submit a fresh PR.

**Pull request closed without merging**
