### PR TITLE
[Bug 17330] Correct revliburl's default HTTP 1.1 header.

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by peter-b** [comment]
This probably needs some sort of test but I'm not at all sure how to do that in a sensible way.

**Comment by runrevmark** [comment]
Well I believe the problem the missing space causes is that it means the 'Host:' header is not merged (in the bug's example stack). This means that a request gets sent with two Host: headers which the webserver doesn't seem to like.

**Comment by peter-b** [comment]
@runrevmark I've added a test.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a1a980a

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok a1a980aa5d520d8a5e75f3571f6bba204b9d4b9e

**Comment by livecode-vulcan** [comment]
😎 test success a1a980aa5d520d8a5e75f3571f6bba204b9d4b9e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2542)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2552)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2537)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2553)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2559)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2563)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2575)

**Pull request merged**
