### PR TITLE
[[ WindowsPlayer ]] Implement player "callbacks" property on Windows

### PR DESCRIPTION
**Pull request by livecodeian**
This change is [Reviewable](https://reviewable.io/reviews/livecode/livecode/4140)

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 9 of 9 files at r1, 6 of 7 files at r2.
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

_[engine/src/w32-ds-player.cpp, line 1428 [r1]](https://reviewable.io:443/reviews/livecode/livecode/4140#-KJtzpSibHuyfKoXQ57Q:-KJtzpSibHuyfKoXQ57R:-561956399) ([raw file](https://github.com/livecode/livecode/blob/5d965b17ae9fdde079f12a9e4977017136bcccc6/engine/src/w32-ds-player.cpp#L1428)):_

> ``` cpp
> 
>   case kMCPlatformPlayerPropertyMarkers:
>   case kMCPlatformPlayerPropertyLoadedTime:
> ```

Am I right in thinking that the loaded time property is still unsupported? I think you might have deleted this line by mistake.

---

_[engine/src/w32-ds-player.cpp, line 1083 [r2]](https://reviewable.io:443/reviews/livecode/livecode/4140#-KJtz8XaXNkz-W9J-wNz:-KJtz8XaXNkz-W9J-wO-:2137085889) ([raw file](https://github.com/livecode/livecode/blob/92b147a4755e9d82e35d494fe60473ebe09d99af/engine/src/w32-ds-player.cpp#L1083)):_

> ``` cpp
> bool MCWin32DSPlayer::SetCallbackMarkers(const MCPlatformPlayerDurationArray &p_markers)
> {
>   MCPlatformPlayerDurationArray t_markers = { nil, 0 };
> ```

If `array_t` had a default constructor, you could use implicit construction both here and for `MCWin32DSPlayer::m_callback_markers`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4140)_

**Comment by livecodeian** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

_[engine/src/w32-ds-player.cpp, line 1428 [r1]](https://reviewable.io:443/reviews/livecode/livecode/4140#-KJtzpSibHuyfKoXQ57Q:-KJu2eJhORb8a0h9A31c:13836450) ([raw file](https://github.com/livecode/livecode/blob/5d965b17ae9fdde079f12a9e4977017136bcccc6/engine/src/w32-ds-player.cpp#L1428)):_
<details><summary>

<i>Previously, peter-b (Peter TB Brett) wrote…</i></summary>



> Am I right in thinking that the loaded time property is still unsupported? I think you might have deleted this line by mistake.
> </details>
> This is in the SetProp method - loaded time is read-only so shouldn't have been there in the first place.

---

_[engine/src/w32-ds-player.cpp, line 1083 [r2]](https://reviewable.io:443/reviews/livecode/livecode/4140#-KJtz8XaXNkz-W9J-wNz:-KJu2wi53r4TTo-ekLSr:644244591) ([raw file](https://github.com/livecode/livecode/blob/92b147a4755e9d82e35d494fe60473ebe09d99af/engine/src/w32-ds-player.cpp#L1083)):_
<details><summary>

<i>Previously, peter-b (Peter TB Brett) wrote…</i></summary>



> If `array_t` had a default constructor, you could use implicit construction both here and for `MCWin32DSPlayer::m_callback_markers`.
> </details>
> Thanks, array_t is of limited use at the moment so i'm not too concerned about that.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4140)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok 92b147a

<details><summary>

<i>Previously, livecodeian (Ian Macphail) wrote…</i></summary>



> #### [[ WindowsPlayer ]] Implement player &quot;callbacks&quot; property on Windows
> 
> </details>

---

Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[engine/src/w32-ds-player.cpp, line 1083 [r2]](https://reviewable.io:443/reviews/livecode/livecode/4140#-KJtz8XaXNkz-W9J-wNz:-KK84VhamVwEx42Zaqac:1534846904) ([raw file](https://github.com/livecode/livecode/blob/92b147a4755e9d82e35d494fe60473ebe09d99af/engine/src/w32-ds-player.cpp#L1083)):_
<details><summary>

<i>Previously, livecodeian (Ian Macphail) wrote…</i></summary>



> Thanks, array_t is of limited use at the moment so i'm not too concerned about that.
> </details>
> It doesn't appear to do anything that an `MCAutoArray<T>` wouldn't do.  I will add "Remove `array_t<T>` from engine" to the product backlog.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4140#-:-KK84i75e9OwNn9HVxIl:1478040086)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 92b147a4755e9d82e35d494fe60473ebe09d99af

**Comment by livecode-vulcan** [comment]
😎 test success 92b147a4755e9d82e35d494fe60473ebe09d99af
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2636)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2646)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2631)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2647)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2653)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2659)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2671)

**Pull request merged**
