### PR TITLE
[Docs] read/write sockets - Syntax and parameters fix

### PR DESCRIPTION
**Pull request by seaniepie**
- Modified parameter names and added types.
- Added new tags and formatting.

### CODE REVIEW

**Comment by seaniepie** [comment]
@livecodeali , my pull request say 'This branch has conflicts that must be resolved' for write-to-socket. What do I need to do?

**Comment by montegoulding** [comment]
He's 🛌 😴 

I can help though. Are you still using the github web ui or have you moved to using a local git repo?

**Comment by seaniepie** [comment]
Until I've had the current 4 branches closed I've been using the web ui. I'm going back to source tree once their merged or cancelled.

**Comment by montegoulding** [comment]
OK, well you will need to use source tree or the command line to fix this one. Which would you prefer?

**Comment by seaniepie** [comment]
I can do command line

**Comment by montegoulding** [comment]
ok are you on the public slack channel it might be easier to move there

**Comment by seaniepie** [comment]
Can you remind me of the address

**Comment by montegoulding** [comment]
livecodepublic.slack.com

**Comment by seaniepie** [comment]
Its ok. I got it

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 71eb287

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 71eb2877291c1fca9a29deda7fcca35f97a03712

**Comment by livecode-vulcan** [comment]
😞 test failure 71eb2877291c1fca9a29deda7fcca35f97a03712
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/507)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/512)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/507)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/509)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/514)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/507)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/508)

**Comment by montegoulding** [comment]
@livecode-vulcan try 71eb287

**Comment by livecode-vulcan** [comment]
😎 test success 71eb2877291c1fca9a29deda7fcca35f97a03712
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/545)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/550)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/545)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/549)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/554)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/546)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/546)

**Pull request merged**
