### PR TITLE
build: Use Xcode 6.4 [6.7]

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 7045ba1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 7045ba17e12700fa3cdfc29fb93389c627384cd1

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay e4c07da

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok e4c07dad8b630282a8ab38dca15f97fb3db516c2

**Comment by livecode-vulcan** [comment]
😎 test success e4c07dad8b630282a8ab38dca15f97fb3db516c2
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/350)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/413)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/295)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/361)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/296)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/287)

**Pull request merged**
