### PR TITLE
Revert "Merge pull request #3425 from livecodefraser/feature-lto"

### PR DESCRIPTION
**Pull request by livecodeali**
This reverts commit 0fc3028d32a5759d4164e04c7973055b86dca058, reversing
changes made to 95a11de5551ed46f457b63856722f9d75706651b.

Conflicts:
    config/android-settings.gypi
    config/android.gypi
    config/mac.gypi
    engine/engine.gyp
    engine/src/mode_installer.cpp

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 838c740

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 838c740646f0e7b22f52f8807faf6549d5bc9622

**Comment by livecode-vulcan** [comment]
⁉ merge unchanged 838c740646f0e7b22f52f8807faf6549d5bc9622 → 548241e7b4c649e52ba15242a5ac0b5531ac06ab

Pull request is already fully merged!

**Comment by livecodeali** [comment]
@livecode-vulcan sorry mate!

**Pull request merged**
