### PR TITLE
[[ Player ]] Update iOS mobile player control to use AVKit framework

### PR DESCRIPTION
**Pull request by livecodeian**
This patch updates the iOS mobile player control implementation to use the AVKit framework.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 2563d7a

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 084bcbc

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 084bcbce13c329599b9ba041797bca073759a320

**Comment by livecode-vulcan** [comment]
😎 test success 084bcbce13c329599b9ba041797bca073759a320

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/662)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/71)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/71)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/71)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/71)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2188)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/22)
* try-community-universal-ios-iphonesimulator13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/22)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2217)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2204)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2203)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2237)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2177)

**Pull request merged**
