### PR TITLE
[[Documentation]] subOver - link to transfermodes

### PR DESCRIPTION
**Pull request by seaniepie**
- Explanation of how the values are calculated
- Add a line to link to a list of all other transfer modes on the transferModes glossary page

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok f0072ab

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f0072abbe0a4905be930530128ebe8ba47a4c0a8

**Comment by livecode-vulcan** [comment]
😎 test success f0072abbe0a4905be930530128ebe8ba47a4c0a8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/343)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/348)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/343)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/343)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/349)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/343)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/343)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 41ab99d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 41ab99df3dc7ea6e561f0c8377ca84bb041b119e

**Comment by livecode-vulcan** [comment]
😎 test success 41ab99df3dc7ea6e561f0c8377ca84bb041b119e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/369)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/374)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/369)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/369)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/375)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/369)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/369)

**Pull request merged**
