### PR TITLE
Turn on -Werror=parentheses

### PR DESCRIPTION
**Pull request by montegoulding**
Based on #4479 because both need perfect to be silenced

### CODE REVIEW

**Comment by montegoulding** [comment]
Labelling WIP until #4479 is merged

**Comment by peter-b** [comment]
@livecode-vulcan review ok b606842

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b6068423efeceffb925bb82b6f150d3491254a05

**Comment by livecode-vulcan** [comment]
😎 test success b6068423efeceffb925bb82b6f150d3491254a05
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/316)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/321)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/316)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/316)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/322)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/316)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/316)

**Pull request merged**
