### PR TITLE
Merge develop 9.0 20.06.2019

### PR DESCRIPTION
**Pull request by livecodepanos**
Conflicts:

conflict in `Installer/package.txt`:

Screen Shot 2019-06-20 at 17 03 51

Resolved conflict by removing d3dcompiler_43.dll as done in this PR: https://github.com/livecode/livecode/pull/7091/files

conflict in `prebuilt/scripts/lib_versions.bat` and `prebuilt/scripts/lib_versions.inc`:

Screen Shot 2019-06-20 at 17 09 39

Screen Shot 2019-06-20 at 17 11 01

Resolved conflicts by keeping the `HEAD` version and re-applying the changes in these 2 files as shown here:

https://github.com/livecode/livecode/pull/7019/files

### CODE REVIEW

**Comment by livecodepanos** [comment]
TODO:

Screen Shot 2019-06-20 at 17 05 46

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 4f0c52f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 4f0c52f90e289bc40d8e537fef58163b169f5ed8

**Comment by livecode-vulcan** [comment]
😎 test success 4f0c52f90e289bc40d8e537fef58163b169f5ed8

* try-community-armv6-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-ndk16r15/builds/5)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/5)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/5)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/5)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/5)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2122)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/347)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/343)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2151)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2138)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2137)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2171)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2111)

**Pull request merged**
