### PR TITLE
[Bug 17167] Replace revNet plugin with liveNet plugin.

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by peter-b** [comment]
Needs a corresponding IDE PR when I get the final plugin stack from Richard.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 910fceb

**Comment by livecodeali** [comment]
Just noticed, the file extension should be `.livecode`

**Comment by peter-b** [comment]
@livecodeali Pull request updated.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 949e889

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 949e889080eee44396c06a3ba5055ca0acd91bf2

**Comment by livecode-vulcan** [comment]
😎 test success 949e889080eee44396c06a3ba5055ca0acd91bf2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2186)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2193)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2179)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2195)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2200)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2206)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2217)

**Pull request merged**
