### PR TITLE
[[ Prebuilts ]] prebuild thirdparty libraries for each supported platform

### PR DESCRIPTION
**Pull request by livecodeian**
Build and package thirdparty libraries as prebuilts and use them when compiling LiveCode engines.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 7d3fdb8

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7d3fdb82e24489cf99fdee0ac05e5c6cd9cae679

**Comment by livecode-vulcan** [comment]
😞 test failure 7d3fdb82e24489cf99fdee0ac05e5c6cd9cae679

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/469)
* try-community-armv7-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/461)
* try-community-arm64-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/461)
* try-community-x86-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/461)
* try-community-x86_64-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/461)
* try-community-js-emscripten-sdk1.35: [failure](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1983)
* try-community-universal-ios-iphoneos12.1: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/211)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/210)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2014)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2005)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2003)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2037)
* try-community-x86_64-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1974)

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 0f914c7

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 0f914c78733ce14d181827add9e888d4be19b13a

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 1d45a3b

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 1d45a3b8849acd539380f45505962d57baa0bf2c

**Comment by livecode-vulcan** [comment]
😞 test failure 1d45a3b8849acd539380f45505962d57baa0bf2c

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/475)
* try-community-armv7-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/467)
* try-community-arm64-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/467)
* try-community-x86-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/467)
* try-community-x86_64-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/467)
* try-community-js-emscripten-sdk1.35: [failure](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1989)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/217)
* try-community-universal-ios-iphonesimulator12.1: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/216)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2020)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2011)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2009)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2043)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1980)

**Comment by runrevmark** [comment]
@livecodeian - So this seems to be failing on Android due to not finding fontconfig or freetype? (I think this might be host side). Looking at the windows logs, whilst they succeeded, it seems that Skia (and thus presumably other thirdparty libs) are still being built locally, rather than using the prebuilts.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9ebd822

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9ebd8228a0b79737432617e8288b69c260447cb3

**Comment by livecode-vulcan** [comment]
😞 test failure 9ebd8228a0b79737432617e8288b69c260447cb3

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/498)
* try-community-armv7-android-sdk26_ndk16r15: [pending](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/490)
* try-community-arm64-android-sdk26_ndk16r15: [pending](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/490)
* try-community-x86-android-sdk26_ndk16r15: [pending](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/490)
* try-community-x86_64-android-sdk26_ndk16r15: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/490)
* try-community-js-emscripten-sdk1.35: [failure](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2012)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/240)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/239)
* try-community-universal-mac-macosx10.9: [pending](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2044)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2034)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2032)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2067)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2004)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 9ebd822

**Comment by livecode-vulcan** [comment]
😎 test success 9ebd8228a0b79737432617e8288b69c260447cb3

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/499)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/491)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/491)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/491)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/491)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2013)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/241)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/240)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2045)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2035)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2033)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2068)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2005)

**Pull request merged**
