### PR TITLE
Added support for building with Xcode 11 / iOS 13.0 SDK

### PR DESCRIPTION
**Pull request by livecodepanos**
This patch adds support for building with Xcode 11 / iOS 13.0 SDK

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 70c5ba4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 70c5ba475818b54d7b341eb6ab3515b1ffa86110

**Comment by livecode-vulcan** [comment]
😎 test success 70c5ba475818b54d7b341eb6ab3515b1ffa86110

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/633)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/42)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/42)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/42)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/42)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2159)
* try-community-universal-ios-iphoneos13.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.0/builds/1)
* try-community-universal-ios-iphonesimulator13.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.0/builds/1)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2188)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2175)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2174)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2208)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2148)

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 1f921e0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 1f921e04f77c7fca6c586f7b904900f8e9be4f79

**Comment by livecode-vulcan** [comment]
😎 test success 1f921e04f77c7fca6c586f7b904900f8e9be4f79

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/634)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/43)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/43)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/43)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/43)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2160)
* try-community-universal-ios-iphoneos13.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.0/builds/2)
* try-community-universal-ios-iphonesimulator13.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.0/builds/2)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2189)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2176)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2175)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2209)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2149)

**Pull request merged**
