### PR TITLE
[[ Bug 16096 ]] update gradient on mouseMove

### PR DESCRIPTION
**Pull request by BerndN**
"live" update for editing gradients

### CODE REVIEW

**Comment by livecodefraser** [comment]
Hi Bernd, thanks for your contribution!

Could you add a file to your pull request in docs/notes/bugfix-16096.md containing a line like

``` markdown
# Ensure the gradient ramp editor widget updates on mouseMove
```

This ensures that our release notes contain a useful entry describing what bugs were fixed.

**Comment by BerndN** [comment]
hope it is right this time, have a lot of trouble getting my head around adding the .md file to the correct patch etc. :)

**Comment by livecodefraser** [comment]
That's it :)

@livecode-vulcan review okay 2161b04

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 2161b046a51b020249c1e920110d14510c5986b8

**Comment by livecode-vulcan** [comment]
😎 test success 2161b046a51b020249c1e920110d14510c5986b8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/600)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/612)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/601)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/602)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/611)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/622)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/613)

**Pull request merged**
