### PR TITLE
[[ Build ]] Allow mac engine to build on Snow Leopard (Xcode 4.2)

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan reviewed okay 0dcf6d1

Really sort-of reviewed because we want to see if it breaks the build for other platforms!

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 0dcf6d19f462f6b37c5fc9dc8544f3f86cc27b2b

**Comment by livecode-vulcan** [comment]
😞 test failure 0dcf6d19f462f6b37c5fc9dc8544f3f86cc27b2b
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/227)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/291)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/180)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/238)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/173)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/173)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 0dcf6d1

**Comment by livecode-vulcan** [comment]
😞 test failure 0dcf6d19f462f6b37c5fc9dc8544f3f86cc27b2b
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/390)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/452)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/336)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/401)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/336)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/327)

**Comment by peter-b** [comment]
@livecode-vulcan review not ok 0dcf6d1

This pull request needs some additional work to make it build on iOS.

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 0dcf6d19f462f6b37c5fc9dc8544f3f86cc27b2b

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevmark, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Pull request closed without merging**
