### PR TITLE
Merge develop 9.0 24.07.18

### PR DESCRIPTION
**Pull request by livecodeali**
Conflict in build-android.md (I think some conflict markers were previously left in the file)

```
<<<<<<< HEAD
android-ndk-r14/build/tools/make_standalone_toolchain.py \
    --arch arm --api 19 \
=======
android-ndk-r15/build/tools/make_standalone_toolchain.py \
<<<<<<< HEAD
    --arch arm --api 26 \
>>>>>>> upstream/develop-9.0
=======
    --arch arm --api 16 --deprecated-headers \
>>>>>>> upstream/develop-9.0
    --install-dir ${HOME}/android/toolchain/standalone
```

resolved with 
```
android-ndk-r15/build/tools/make_standalone_toolchain.py \
    --arch arm --api 16 --deprecated-headers \
    --install-dir ${HOME}/android/toolchain/standalone
```

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok addc9d1

**Comment by livecodeali** [comment]
Taking a few liberties with the clean-merge label here.

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok addc9d1a92e2eb2cddcd62ec71ffd6b96bdaf856

**Comment by livecode-vulcan** [comment]
😎 test success addc9d1a92e2eb2cddcd62ec71ffd6b96bdaf856

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/34)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/26)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/26)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/26)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/26)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1548)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/75)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/75)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1578)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1572)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1568)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1605)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1545)

**Pull request merged**
