### PR TITLE
[Bug 9942] Make sure the short system time has no seconds on Linux

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
I think we need to add a documentation comment to this with regards linux.

Strictly speaking there is no 'short' or 'abbr' time format provided by the linux locale functions - you can only ask for a time format, a date format or a date and time format.

Whilst we can remove the :%s format specifier from these system-fetched values, it won't work for all locales - some of which use things like %r or %X which represent HH:MM:SS type formats.

The point is that, if you want the system time format, then (on Linux) there is only one (long) and that is what you have to use.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9176780

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9176780d3bdc7549a1d3ba8e201fa2889d1b1d48

**Comment by livecode-vulcan** [comment]
😎 test success 9176780d3bdc7549a1d3ba8e201fa2889d1b1d48
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/329)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/329)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/328)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/327)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/332)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/324)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/335)

**Pull request merged**
