### PR TITLE
Fix a nullptr deref when checking watched variables

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
Please rebase to `develop-8.1`.

**Comment by peter-b** [comment]
@livecode-vulcan review ok db352d5

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok db352d5a5e5d46b14be275968bb0c2428b61b36f

**Comment by livecode-vulcan** [comment]
😎 test success db352d5a5e5d46b14be275968bb0c2428b61b36f

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/631)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/636)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/631)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/635)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/640)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/632)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/632)

**Pull request merged**
