### PR TITLE
[mergDeploy] Add mechanism to keep external out of SB inclusions

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
Once this is merged I can include mergDeploy in the Ext directory with a support library that inserts itself as a front script.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3373e43

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3373e433b1b25e0a758966675785b6839a0abd89

**Comment by livecode-vulcan** [comment]
😎 test success 3373e433b1b25e0a758966675785b6839a0abd89

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/837)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/843)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/835)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/836)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/843)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/834)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/834)

**Comment by montegoulding** [comment]
Hmm... `clang: error: unknown argument: '-fcheck-new'`

**Pull request merged**
