### PR TITLE
[Bug 18022] lc-compile: Improvements for comments & line continuation

### PR DESCRIPTION
**Pull request by peter-b**
- Add tests for line continuation handling
- Add documentation of comments and line continuation to language reference
- Fix bug where `/* ... /*` comments can act as line continuations

### CODE REVIEW

**Comment by runrevmark** [comment]
Relevant discussion about continuation chars here - http://quality.livecode.com/show_bug.cgi?id=18006

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 5ad38b8

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 5ad38b883f66ff251f7c7664751a6e7eeb91fc88

**Comment by livecode-vulcan** [comment]
😎 test success 5ad38b883f66ff251f7c7664751a6e7eeb91fc88
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2805)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2812)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2798)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2814)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2820)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2828)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2843)

**Pull request merged**
