### PR TITLE
[Bug 19261] Clear treeview selection when deleting selected node

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 6905c8d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 6905c8dab3475257f4c9563f6ce4ab511984d697

**Comment by livecode-vulcan** [comment]
😞 test failure 6905c8dab3475257f4c9563f6ce4ab511984d697

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/953)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/959)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/951)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/952)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/959)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/967)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/950)

**Comment by peter-b** [comment]
@livecode-vulcan retry 6905c8d

**Comment by livecode-vulcan** [comment]
😞 test failure 6905c8dab3475257f4c9563f6ce4ab511984d697

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/954)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/960)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/952)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/953)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/960)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/969)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/951)

**Comment by peter-b** [comment]
@livecode-vulcan retry 6905c8d

**Comment by livecode-vulcan** [comment]
😎 test success 6905c8dab3475257f4c9563f6ce4ab511984d697

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/959)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/965)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/957)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/958)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/965)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/974)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/956)

**Pull request merged**
