### PR TITLE
[[ Bug 8181 ]] Move a File to Trash or Recycle Bin

### PR DESCRIPTION
**Pull request by lan-kc**
If this looks familiar it's because it's my 2nd attempt - the correct way this time I hope.
Added a script example on how to move a flie to Trash or Recycle bin.
Added References to rename and do
The VBScript was extracted from the Use List. I have no way of confirming that it works with the latest version of Windows.

### CODE REVIEW

**Comment by livecodeali** [comment]
Thanks @lan-kc!
- Could you tab-indent the code block you have added please? Otherwise it will come out like this in the entry
  screen shot 2016-01-27 at 12 52 06
- I suggest putting an explicit reference to rename when you introduce the code block, such as 
  `To place a file in the Trash or Recycle Bin, use the <rename> command:`
- Also, could you begin that sentence on the next line so as not to have an extremely long line there?
- As this is an outstanding bug report, can you add a bug fix note too (see https://github.com/livecode/livecode/blob/community-docs/docs/contributing_to_docs.md#adding-a-bug-fix-release-note)?

Sorry there are so many things there, let me know if the guide is adequate in helping you make these changes!

**Comment by lan-kc** [comment]
OK the first 3 done. I note that even after I tab indented the script, when I tested in your Preview stack it still came out displayed as you show above.

Also for your Guide. I see part of my problem when going back and trying to change things was I was clicking here - Arrow 1
firefox

This took me here which looked correct:

firefox

But when I clicked on View I was then presented with a greyed out pencil

firefox

The instruction need to direct you to 'Changed Files' - Arrow 2 in the first screenshot. I thought that was just a statistic, not a link. When I clicked there I then get a pencil that allows me to amend the file.

firefox

Lastly, on my very first attempt I had these option buttons:

firefox

On this more succussful 2nd attempt I did not see these until this subsequent amendment. Not sure what effects why these are or aren't shown but the instructions need to mention them and 'leave them as default' if that is the case.

**Comment by lan-kc** [comment]
I will have a go at the Release Note now.

**Comment by livecodeali** [comment]
@lan-kc Ah, great thanks :-) I will continue to improve the guide!

Looking at your 'formatting changes' commit, it looks like there is a single space before each line of the code rather than a tab character, which I think is why it is still not coming out correctly.

**Comment by lan-kc** [comment]
OK, I'll try to fix. I need the practice

**Comment by lan-kc** [comment]
OK that took a bit to nut out. I didn't notice but along the top is this:
firefox

Which was converting all my tabs to spaces. Once you change it to this:

firefox

Tabs remain as tabs. I'm confident this will work as it looked OK in your Preview stack.

**Comment by livecodeali** [comment]
@lan-kc Yes, that looks great! Thanks :-)

**Comment by lan-kc** [comment]
Reference your instruction for Release Notes. It says:

Click on the link to your livecode repository (under the Popular Repositories heading).

So I click on the LiveCode link on the left here:

firefox

Which takes me here:

firefox

Your instructions then say:

You should see a link to your recently pushed branch (called patch-1 or similar).

If you do, click on the link to the recently pushed branch. If not, select the branch from the branch dropdown list.

As I can see nothing that says 'patch-1' I click on the branch dropdown (arrow 1) and get this:

firefox

Still nothing 'patch-1'. What I needed to do was type Patch into the box and then it found it:

firefox

Which gets me here:

firefox

which leades me here:

firefox

And finally here:

firefox

Your Guide says:

At the top of the page you should see something like

Branch: patch-1 livecode/docs/notes/ +

Click on the +

I don't see any + symbol but I'm sure the New File button will do the same thing.

I'm not sure if these differences are due to Browser (Firefox) or an update to the Github website.

It's very very late so I'll do the Release Note tomorrow.

**Comment by livecodeali** [comment]
@lan-kc Thanks for you perseverance! I think the + -> New File must have been a change to the GitHub website - I did write the instructions last year and a couple of things seem to be different. I will update the instructions.

**Comment by lan-kc** [comment]
Release Note Added

For your Guide I note the following; it says:

> Click the "Commit new file" button.

Again I'm seeing options here so you need a screenshot with the right options selected before Clicking.

firefox

> Check the pull request again in https://github.com/livecode/livecode/pulls You should see the "Add release note" commit added to the pull request.

**I've discovered the quickest way to my pull request is from my profile - Contribution Activity.**

firefox

**So I scroll down and not only do I see my 'Add release note' but also discover a link to 'patch-1'**

firefox

**Comment by lan-kc** [comment]
Link to pull request added to the QCC 8181 Bug report

**Comment by lan-kc** [comment]
OK, hopefully you'll confirm that I've now got the basics right:
1) Amend .lcdoc file and Create Pull Request
2) Create .md file added to above Pull Request
3) Add link to 1) in QCC

If so, I have a confession: I'm not actually happy with the way the entry has turned out - that code chunk is way too big and ugly and distracts if that is not what you are looking for.

The Dictionary is a Catch-22. It needs to be concise, cover all bases, no bloat, but a reoccurring complaint from the LC Community is that there needs to be **more examples - a lot more**. I think where possible code should be colour coded, this becomes more important with larger chunks of code.

When I first thought I'd have a go at amending the community docs I was simply going to add the OS X rename example. Small, it would look fine as plain text in the Description, but then I thought that's a bit myopic - LC is cross platform and the 8181 does ask for a Recycle Bin example. The code quickly bloated.

My suggested solution is to take the rename portion of the script and amend the rename.lcdoc (new pull request) to include it as an example. Do the same for do.lcdoc with the VBScript example. This way the code chunks will be smaller, they'll be colour coded, the rename.lcdoc is light on for examples and do.lcdoc has no VBScript example.

I will cut my amendment to the delete_file.lcdoc and replace it with two simple lines:

See `<rename>` for an example of moving a file to the Trash.
See `<do>` for an example of moving a file to the Recycle Bin.

Tell me what you think

**Comment by livecodeali** [comment]
@lan-kc I think I might agree. I'm sure there are other examples of code within the description element though, so it might be a general problem we need to solve.

I wonder if it would make a difference if we tweaked the styling? I think the fact that it is not colorized is a bug, for example. Maybe code blocks within the description section could be smaller, or foldable. Maybe they should appear by default as

```
local tName, tNameTrash
...
end switch
```

but then expand on click, like (to pluck a randomly googled example) http://jsfiddle.net/sutekh/ku8B9/light/

**Comment by lan-kc** [comment]
I've been having a poke around and there are certainly other examples of code within the Description block, but I couldn't find any that were more than half a dozen lines. HyperCard use to have an excellent solution, you selected either Basic, Intermediate or Advanced (if I recall correctly) and got either 1 liners, some multi-liners or some big chunks of code - basically learned to xTalk from plagiarizing those examples. I like the foldable idea. I think though, if the community eventually comes around to adding copious examples,  you are going to be forced to have a limit of maybe 20 lines of code in the Examples: block (be it 4 x 5 lines, or 3 one liners and 1 x 17 lines) and an alternative location for storing and viewing other examples: be it a 'Further Examples:' block below the current Dictionary format and stored on the same file, or a link that maybe changed to Dictionary layout to just the keyword heading, it's syntax and the rest just an Example: block - the data coming from a seperate but associated file - 'delete_file_examples.lcdoc', 'revDeleteFolder_examples.lcdoc' etc etc.

One further 'style' question. As I've been looking around the Dictionary, someone has been busy. Some of the entries are well linked, but others are completely lacking. revDeleteFolder is a good example of many links. But even so I can see many instance of key words that could be linked - function, rename, some of these appearing multiple times. For revDeleteFolder some words like file and folder have been linked multiple times. Others, like stack, have some linked and the odd one not. I look at this and think, if every possible key word was actually linked, it might turn out more blue than black. Is the style intention to link every possible instance of a key word? My own thoughts are that maybe just linking the first instance of each key word would be a happy medium?

I will move that code chunk out of 'delete_file.lcdoc' as mentioned, but I'm preparing for a big day tomorrow so I'm not sure when I'll get around to it.

**Comment by livecodeali** [comment]
Most of the linking was already present in the previous dictionary - I tried to preserve as much existing information as possible when converting the files. We had a discussion about this in the office yesterday - I believe @peter-b plans to tweak the CSS so that the links are styled the same as plain text with maybe underline on hover.

I largely agree with your thoughts about code examples. So I think splitting that code between the `do` and `rename`, and referencing them in `delete file` and `revDeleteFolder` is a good solution for what we currently have. 

Thank you for all your feedback, the guide has improved immeasurably because of you contributions!

**Comment by peter-b** [comment]
@livecodeali I'll go ahead and make that tweak now.

**Comment by lan-kc** [comment]
Hi Ali,

You may have thought I'd fallen off the planet, but not quite. Just a couple of extremely busy months.

I just want to check that I'm accessing the latest version of the Doc's as I'm seeing something strange.

If I take the 'rename.lcdoc' as an example, and narrow it down to this line:

`Summary: Gives a <file> or <folder> a new name or moves it to a new location or both.`

What I see via LC8dp16 Dictionary is this:

snap1

Which correctly shows the words 'file' and 'folder', but if I place the entire content of the 'rename.lcdoc' file into your Preview stack and run it I see this:

snap2

In this case the words 'file' and 'folder' are missing. I've discovered the nice feature of your Preview stack is that if there are any ambiguous references then they disappear completely. So if I change the Summary line to:

`Summary: Gives a <file(glossary)> or <folder(glossary)> a new name or moves it to a new location or both.
` 

Then your Preview stack displays correctly:

snap3

But this then begs 2 questions:

1) Why does the rename.lcdoc that I can access incorrectly have the ambiguous  <file> in several places when the LC8dp16 Dictionary clearly has disambiguous entries?

2) Why is <folder(glossary)> necessary. As far as I'm aware 'folder' is only a glossary entry, there is no ambiguity? Surely it can't be because 'folder' is an 's' short of 'folders' a function!

Slowly plodding on with this... but I'm easily confused ;-)

**Comment by livecodeali** [comment]
Hi @lan-kc,

Glad to hear you haven't fallen off the planet. 

Part of what you are seeing is the fact that the preview stack does not bother building the whole dictionary into the preview, so _all_ references should fail there. I'm not quite sure why they are disappearing in one case and not another, 

So, in the dictionary proper, `<folder(glossary)>` will not be necessary, and the `<file>`s should be changed to `<file(glossary)>`. I think currently if there is an ambiguous reference, the dictionary will just choose the last one.

**Comment by lan-kc** [comment]
Hi Ali,
Firstly, you wrote something and it came out as this:

the s should be changed to .

I think you may have used some code that has been lost when displayed.
I think it might be related to the fact, upon further investigation I've discovered your Preview stack seems to display OK:

```
<folder|folder's> --plural or possesive format
<file(glossary)> --disambiguous format
<file(keyword)|files> --combination disambiguous + plural/possesive
<rename> --if it's a direct match to the first line Name: tag

```

but does NOT display:

`<plainReference> --simple format`

By coincidence the first lcdoc I worked on had many non-simple formatted links so I didn't notice the few missing. I've now added 'Check for ambiguous references' to my action list and will have to have a think of a way to highlight such instances so they can be formatted correctly.
Moving ahead slowly.

**Comment by lan-kc** [comment]
Ali,
Also I notice the existence within the 'command' folder of a 'lock-updates.lcdoc', which seems to be a copy of 'lock-messages.lcdoc' although lines 22 and 28 are slightly different with lock-messages containing a little more detail. The only 'lock updates' I could find in the Dictionary is the lockUpdates property - which correctly has it's own lockUpdates.lcdoc file. Should the lock-updates.lcdoc file exist? Should I file a Bug report?

**Comment by livecodeali** [comment]
I don't think it should exist no - unless `lock updates` is a valid command (which I don't think it is). So yes, please file a bug report!

(I've edited my previous message to correct the display issues)

**Comment by lan-kc** [comment]
Hi Ali,

Still here, still plodding along when I have spare time. Currently trying to get my head around the relationship between Associated and References. In the Livecode Documentation Format Reference:

https://github.com/livecode/livecode/blob/community-docs/docs/guides/LiveCode%20Documentation%20Format%20Reference.md

it states:

Associated

A comma-delimited list of names of other API or docs entries. Each one must be of type object, glossary, library, or widget. It is used to generate the docs for the entries to which it is associated.

References

A comma-delimited list of other API or docs entries that are referenced. The references element is essential for linking around the documentation viewer.

So if I look at this lcdoc:

https://github.com/livecode/livecode/blob/community-docs/docs/dictionary/property/name.lcdoc

Name: name

Type: property

Associations: stack,card,field,button,graphic,scrollbar,player,image

References: HCAddressing property (property), ..., player (object), object (object), stack (object), control (object), ..., statement (glossary), standalone application (glossary), file path (glossary), property (glossary), folder (glossary), development environment (glossary), object reference (glossary), application bundle (glossary), execution error (glossary), main stack (glossary), OS X (glossary), bundle'sfile path (glossary), pane (glossary), property inspector (glossary), current card (glossary), background (glossary), card control (glossary), object (glossary)

So I'm left scratching my head for a couple of reasons:

1) stack and player are the only Associated that appear in References; why aren't the others?
2) Associated is to include Glossary, yet not a single one of the many References that are glossary are in the Associated list. Why not? *
3) Why isn't the format for Associated the same as for References; or possibly specifically different to the Reference link to avoid ambiguity? **

If I enter 'stack' into the search box of the LC 8 Dictionary I get 3 exact hits; 2 x objects and 1 x keyword. The 1st object entry is the static /object/stack.lcdoc file. The 2nd object entry appears to be dynamically built based on the Associated entries. In this case it groups together all the Message, Property, Command and Function. Very nice, and extremely handy, \* although I'm not sure why you'd want to cram glossary entries into it as well?

Unfortunately if I go to the 'name' entry in the Dictionary: 

set the [{ long | abbr[ev[iated]] | short }] name of object to string

to bring up the /property/name.lcdoc mentioned above, and click on the 'stack' hyperlink in the Associated list it takes me to the same /object/stack.lcdoc static entry that the stack (object) hyperlink in the Reference line takes me. Even the Associated that aren't listed in References takes me to the static lcdoc not the dynamic one? *\* The link format might need to be more specific - stack (associated)?

So I think I understand what the Associated entry is trying to achieve I'm just not sure how to achieve it. Are the files that I've been looking at incorrectly formatted? When do you put a link in only one, and when in both Associated and Reverences?

And finally, the Documentation Format Reference also states:

In particular, every API entry in a library should have that library name in its Associated list.

Would that be: 'common, database, font' or 'common library, database library, font library' ?

Thanks for your time!

**Comment by livecodeali** [comment]
Hello again!

Most of the anomalies you are seeing are due to the fact that all the dictionary information has been parsed directly from the previous XML format docs. Had they all been written from scratch, the associations and references would probably be consistent in the way you expected them to be!

I'm not sure why there are multiple `stack` entries - the dynamic list of associated entries should be being appended to the main `stack` object entry.

In terms of glossary / associated discrepancies, I think it probably makes sense as it currently is - we probably don't want glossary entries to be cluttered up with syntax information. Actually I think some work needs to be done on how the glossary and dictionary are distinguished- I feel like glossary should be a separate dropdown perhaps.

You are right that the associations should have the same format as references - although actually in light of the above observation, I wonder (as it seems like you were wondering) if we should be allowing glossary-type associations at all. I think it's worth removing them for now. That would mean only entries of type object, library or widget can be associations, which I think makes sense.

The main name of the entry should be used for the association, so for your examples they would include the word library (eg "Common library"). I don't think there is currently a font library entry.

Does that make sense?

**Comment by mwieder** [comment]
I just want to say that this process makes for fascinating reading. @peter-b, I think this would be a great inclusion for your This Week in LiveCode posting.

**Comment by lan-kc** [comment]
> Does that make sense?

Basically yes, see notes further below *, but I've just noticed another anomaly which I'd like your insight into.

> Most of the anomalies you are seeing are due to the fact that all the dictionary information has been parsed directly from the previous XML format docs.

There are a few entries whose Type does not match the folder they are stored in:

```
revBrowserAddJavaScriptHandler
revBrowserRemoveJavaScriptHandler
```

plus others are stored in the **'/docs/dictionary/command/'** folder and both look like **commands** to me but the content states:

`Type: function`

So how accurate was that parse and which is correct?
1) The Type: is 99% correct and the file should be moved to the appropriate folder - _do I need to raise a bug report because I don't think I can move files in Github, just modify them._
2) The Folder they are stored in is 99% correct, just change the Type: to match - _I can do that._
3) **Parse questionable, check ALL Types;** amend those that need it and bug report files that need to be moved. 

\* As for Associations: I'll exclude Glossary and just stick with Object, xxxx Library or Widget. As for the format I'm going to leave them as plain - 'button,card,stack' not `button (object), card (object), stack (object)` because, now that my Dictionary seems to have fixed itself: a) the plain format is working, b) without Glossary, there is no ambiguity. I'll check that any References: that are Type Object, xxxxx Library or Widget are repeated in Associations and vice versa.

> I'm not sure why there are multiple stack entries

Me either because today when I started LC 8 dp16 on OS X 10.9.5 I'm getting a different response. Instead of 3 `stack` entries I now only get two, they are the object and glossary entries and in both cases the aggregated Associated table is appended to the bottom. That looks much better, although I note when I click on the stack Glossary entry it reports it's `Type: object`. Investigating further if there is a single Glossary entry then it shows `Type: glossary`, but if there are two entries with the same name, then the Glossary entry reports it's Type as whatever the 'other' entry is.

For Glossary markup I'll leave those in References: as we agree a simple link against Related seems to be the least cluttered presentation. As for distinguishing between Glossary and Dictionary entries my own thoughts are - in probably order of complexity:

1) From the pulldown menu where you can select 'Livecode Script', 'Livecode Builder', ... etc, include 'Glossary' which would bring up a similar table to Associations, just 2 columns, Name - a link, and Description.

2) A negative filter. I imagine most long time users don't need to see the Glossary entries. Currently you can Filter the search but only by a single Type + single Tag + single OS. Searching by all Types except Glossary (or any other Type) would be very handy too. Maybe the Filter label could be used as a trigger; clicking on it would change the label from 'Filter with:" to/from "Filter without"

3) When you type in the Dictionary search box, in the list of hits, if any are Glossary then these are highlighted as such: ie if the search term is stack

`...`
`sort [marked] cards [of stack] [direction] [sortType] by sortKey`
`stack`
`stack - Glossary`
`stack file - Glossary`
`...`

4) When perusing the actual content of a Dictionary entry, if you pass the mouse over any word/phrase/link that has a Glossary entry then a tooltip pops up with just the Description portion of the entry. Probably hard to implement as it would require further refinement of the mark up to something like this:

`<nnnnn(glossary)|nnnnn(type)|nnnnn s ed ing> --tooltip|link|visible text`
`<nnnnn(glossary)|nnnnn s ed ing>  --tooltip & link|visible text`
`<nnnnn(type)> --link & nnnnnn as visible text - no tooltip **`
`** actually this could be extended so that commands and functions could have their Syntax displayed as a tooltip - but I wont get too greedy and just go with Glossary for now ;-)`

Thanks again for sparing the time to answer my questions.

**Comment by livecodeali** [comment]
> There are a few entries whose Type does not match the folder they are stored in:
> 
> revBrowserAddJavaScriptHandler
> revBrowserRemoveJavaScriptHandler
> plus others are stored in the '/docs/dictionary/command/' folder and both look like commands to me but the content states:
> 
> Type: function
> 
> So how accurate was that parse and which is correct?

This looks to be an error from when it was added, rather than a parsing error. Looking at 7.0.5 it is marked as a function, but it is definitely a command. So your option

> 2) The Folder they are stored in is 99% correct, just change the Type: to match - I can do that.

is the correct one. I also notice there is a spurious comma in the example of `revBrowserAddJavaScriptHandler`.

> - As for Associations: I'll exclude Glossary and just stick with Object, xxxx Library or Widget. As for the format I'm going to leave them as plain - 'button,card,stack' not button (object), card (object), stack (object) because, now that my Dictionary seems to have fixed itself: a) the plain format is working, b) without Glossary, there is no ambiguity. I'll check that any References: that are Type Object, xxxxx Library or Widget are repeated in Associations and vice versa.

I have fixed this in the develop branch now so that it will link to the entry with the associations in it.

> Me either because today when I started LC 8 dp16 on OS X 10.9.5 I'm getting a different response. Instead of 3 stack entries I now only get two, they are the object and glossary entries and in both cases the aggregated Associated table is appended to the bottom. That looks much better, although I note when I click on the stack Glossary entry it reports it's Type: object. Investigating further if there is a single Glossary entry then it shows Type: glossary, but if there are two entries with the same name, then the Glossary entry reports it's Type as whatever the 'other' entry is.

I've also now fixed all of the types in the glossary so that they are glossary rather than object.

I think each of your ideas on how to deal with the glossary have merit - I've added a GitHub issue so we remember to think about it when we have time!
https://github.com/livecode/livecode-ide/issues/1105

**Comment by lan-kc** [comment]
OK, No 2 is easy. Glad you like the Glossary ideas. And just another Glossary question. Many other Dictionary entries don't have Synonyms:, but for the Glossary it seems every entry has a synonym even if it's an exact match to it's Name:

https://github.com/livecode/livecode/blob/community-docs/docs/glossary/a/Aqua.lcdoc

Is there a reason for this? Will something break if I remove Synonyms: which are an exact match to Name: ? It seems a waste of Dictionary screen real estate to list a Synonyms: = Name:

**Comment by livecodeali** [comment]
They can be deleted, yes - I can confirm that they perform no useful function. Indeed the docs parser collects all the synonyms and does nothing with them - the javascript resolves link the links at display time, first looking at the name element and then the synonyms element

**Comment by montegoulding** [comment]
@lan-kc I started reading this PR discussion after @mwieder mentioned it on the use list. I'm a little concerned by:

> The VBScript was extracted from the Use List.

Given there's no license on the use list content perhaps it would be prudent to check the original author has signed the contributors agreement and is happy to contribute it?

**Comment by lan-kc** [comment]
Hi Ali,
as I continue to stumble through the lcdocs I notice that a few entries have `Security:   xxxx`
https://github.com/livecode/livecode/blob/community-docs/docs/dictionary/command/open-file.lcdoc
but there is no mention of this in the LiveCode Documentation Format Reference. I gather the format is a **single** item from the 10 listed in the Dictionary's `securityPermissions` entry:
`Security: disk`
`Security: network`
`Security: process`
... etc
I notice this information use to be displayed in the Dictionary (6.6.5) but not in 8dp16. Do you want me to enter a bug report?
I notice one of the categories is:
`doalternate - use of the 'do ... as ...' alternate language execution feature`
so I was expecting the do.lcdoc
https://github.com/livecode/livecode/blob/community-docs/docs/dictionary/command/do.lcdoc
to have
`Security: doalternate`
but it doesn't.
Can I assume that any lcdoc that is **directly related** * to the 10 security categories as listed under the `securityPermissions` entry of the Dictionary, should have the matching `Security: xxxx` line in the lcdoc? My hope is that `Security: xxxx` will be used like the `Associated: aaaa,bbbb` to produce a link to a Table that clearly lists the commands, functions, keywords and properties that will be effected by changing the `securityPermissions`.

\* or even **slightly related** ? What's the point of `specialFolderPath()` or setting `the defaultFolder` if you can't actually read from any file because you've removed `disk` from the `securityPermissions`? In my imagined Table above these would be 'effected'. Although I believe you can still open Stack files for read only - so would these entries warrant a `Security: disk`?

**Comment by livecodeali** [comment]
@lan-kc That is a nice idea for a table in the securityPermissions entry, yes - if you could file an enhancement request for it that would be great. 

To be honest all the security category information was just directly parsed from the old files- we hadn't decided what to do with them yet. 

The security category in a dictionary entry should match the permission checked in the source code before a particular piece of syntax is executed. 

If you search all the files in the engine folder called exec-*.cpp, you will find the implementation of every piece of LiveCode syntax (this was a large chunk of the work done in the refactoring project). At the beginning of some of them, there is 

```
    if (!ctxt . EnsureDiskAccessIsAllowed())
        return;
```

or

```
    if (MCsecuremode & MC_SECUREMODE_DISK)
    {
        ctxt . LegacyThrow(EE_DISK_NOPERM);
        return;
    }
```

or various other `...IsAllowed()` or `MC_SECUREMODE_...` types.

You are correct that `specialFolderPath()` is affected by the disk security permission (it has the above clause in its implementation) - I'm not sure if you were saying it doesn't have `Security: disk` but it does: https://github.com/livecode/livecode/blob/community-docs/docs/dictionary/function/specialFolderPath.lcdoc

So I would say that for the moment the source code should be the ultimate arbiter of the content of the `Security` element of the docs entry (of course another way to check this is to set the securityPermissions and test it!) Now, the trouble with `do ... as ...` is that it's in the same dictionary entry as `do`. Actually I think the best thing for this would be to add the security category to `do` and add a note to the effect that `do .. as ...` throws an error if the securityPermissions don't allow its use.

Of course there is the additional question of what should happen with something like `the alternateLanguages`. Currently this returns `empty` if the `doAlternate` secure mode is on, rather than throwing an error. I _think_ the current precedent is that the security category should be added to the docs if and only if it throws an error, although I could be wrong about that.

**Comment by lan-kc** [comment]
Ali,
Got that. Thanks.

Monte,
my discussion on the Use List I was quite open about the fact that I was seeking help for a Dictionary entry. I  have no idea if the originator has signed a contributors agreement. I'll be happy to ask but I'm just wondering if this is making a mountain out of a mole hill. What happens if they say no? Does this mean that Charles' offer to process other people's amendments will also have to be turned down - because these people are likely to be Gitphobic and just haven't the time for the whole sign-up process?

I understand the concern though so I guess I'll do whatever Ali suggests.

**Comment by livecodeali** [comment]
I'd do whatever Monte suggests - he has a better handle on these sorts of issues than me ;-)

**Comment by montegoulding** [comment]
@livecodeali that's news to me. 
@lan-kc basically the contributors agreement covers us if you contribute something you don't have the right to so its more about covering your but than ours. It really would be helpful if the lists and forums were CC0 because I can't imagine many people post things they don't want public domain.

**Comment by lan-kc** [comment]
Monte,
I immediately emailed the contributor after my previous post here \* as I'm sure the person is a generous sole and it's not going to be an issue; in this case - but your question has wider ramifications.

> It really would be helpful if the lists and forums were CC0 because I can't imagine many people post things they don't want public domain.

I've always thought that anything posted to a LiveCode Use List was public domain, or at least for LiveCode for the benefit of all LiveCode users - I certainly post with that mind set; but I also tried to look up what license/agreement the LiveCode Use List and Forums operates under and surprised I couldn't  find any. If there is an agreement/license/code of conduct it should be more prominent - a link. If there isn't one I agree that Heather should start testing the waters about putting one in place. I think CC0 unless the poster specifically states otherwise.

\* as yet, no response; and then two other scenarios came to mind:
1) they reply, as is so often the case on the Use List, _"oh that isn't my original code, I got that from someone else who I can't remember, or off a VBScript Use List"_,... or some other never ending chain of never actually finding the original author.
2) they don't respond - either no longer active on the Use List, don't care and couldn't be bothered to respond, or are dead.

**Comment by lan-kc** [comment]
> That is a nice idea for a table in the securityPermissions entry, yes - if you could file an enhancement request for it that would be great. 

http://quality.livecode.com/show_bug.cgi?id=17333

**Comment by lan-kc** [comment]
Hi Ali,

some lcdoc files seem to have mysteriously disappeared, I think they were there but now I can't seem to locate them:

`cameraControl - object`

`cameraControlCreate - command`
`cameraControlDelete - command`
`cameraControlDo - command`
`cameraControlSet - command`

`cameraControlGet - function`
`cameraControls - function`
`cameraControlTarget - function`

Are there reasons that lcdocs might be moved out of the Community Branch temporarily, or unavailable for amendment? Is it just a matter of wait and they'll return a day or week later?

**Comment by livecodeali** [comment]
@lan-kc These docs are in the commercial repository as the camera control is only available in LiveCode Indy and Business. They shouldn't ever have been in the community repo.

**Comment by lan-kc** [comment]
OK. Not sure how I stumbled across them then.

**Comment by peter-b** [comment]
@lan-kc @livecodeali Unfortunately, it looks like this PR has got stuck.  I'm going to close it for now. @lan-kc, please go ahead and re-open it (or submit a new PR) if you'd like to pick these changes up again.

**Comment by lan-kc** [comment]
Sorry, life is way to hectic right now. Haven't LiveCoded in..... way too
looonnng :-(

**Comment by macMikey** [comment]
Could we get this reopened?  I spent an hour digging through the mail lists...

**Comment by montegoulding** [comment]
@macMikey would need to be resubmitted against develop-9.0 branch now as the community-docs branch is no longer used.

**Comment by macMikey** [comment]
I fell asleep about 10 messages in, so I'm not even clear why this was not included.

**Pull request closed without merging**
