### PR TITLE
LCB: Add array expressions to language.

### PR DESCRIPTION
**Pull request by peter-b**
Add array expressions to the LiveCode Builder language.  They have the
grammar:

```
array          ::= "{" [key-datum-list] "}"
key-datum-list ::= key-datum ("," key-datum)*
key-datum      ::= expression ":" expression
```

### CODE REVIEW

**Comment by montegoulding** [comment]
Cool... does this support multi-dimensional arrays and lists?
`{ "foo" : { "bar" : true }}` If so we almost have a JSON parser...

I presume that LCB can only do single line syntax but it would be nice to be able to:

```
put {
        "foo" : true,
        "bar" : true
      } into tArray
```

**Comment by peter-b** [comment]
Yes, it supports nested arrays and lists. Automatic line continuation is something for the future, I think.

**Comment by peter-b** [comment]
For now you can use `\` at the end of a line to request line continuation!

**Comment by montegoulding** [comment]
Ah, just like LCS... ok then. I guess automatic line continuation is pretty complicated without `;` but ignoring all whitespace until you find `({[` pairs would cover nicely formatted arrays and lists. Any chance this supports inline comments:

```
put {
        "foo" : true, // foo thing \
        "bar" : true  // bar thing \
      } into tArray
```

**Comment by peter-b** [comment]
This is exactly what I said to @runrevmark when we discussed it yesterday! It would help with wrapping long parameter lists too.

Feel free to have a crack at it — it might be a while before anyone here gets round to it…

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 45d2e24

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 45d2e241dd6cf282e9cc4eb9426ac637cb126a54

**Comment by livecode-vulcan** [comment]
😎 test success 45d2e241dd6cf282e9cc4eb9426ac637cb126a54
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1517)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1536)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1513)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1524)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1536)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1537)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1539)

**Comment by montegoulding** [comment]
Ah... if I ever get a couple of weeks (months) to try and get my head around gentle then I'll put it on the todo list ;-)

**Pull request merged**
