### PR TITLE
[[ MemoryLeak ]] Cleanup Linux MCScreenDC::vendorname on deletion

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by peter-b** [comment]
Out of interest, when should I use `MCNameDelete()` rather than `MCValueRelease()`?

**Comment by runrevmark** [comment]
I think MCNameDelete should probably be deprecated - I believe the semantics are identical to MCValueRelease these days. A form of MCNameRefs existed prior to 7.0, hence the existence of MCNameDelete.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9031835

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9031835e03437d0beeb656dd10fe2424372a2530

**Comment by livecode-vulcan** [comment]
😎 test success 9031835e03437d0beeb656dd10fe2424372a2530
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/468)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/471)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/467)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/467)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/475)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/468)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/477)

**Pull request merged**
