### PR TITLE
[[ Bug 22888 ]] Add support for building apps against iOS 14.1 SDK

### PR DESCRIPTION
**Pull request by livecodepanos**
Supersedes https://github.com/livecode/livecode/pull/7438

Needs https://github.com/livecode/livecode/pull/7450 and https://github.com/livecode/livecode/pull/7456 

The prebuilts for iOS 14.1 are ready.

### CODE REVIEW

**Review by runrevmark — CHANGES_REQUESTED** [review]
@livecodepanos Please file an issue in BZ so this has an issue number to attach it to.

The title of the PR and commit message need to be updated both to reflect the issue number (i.e. ``[[ Bug XXXX ]] at the start of the title`) and also to reflect what the patch does. Specifically, this isn't `adding support for building with Xcode 12.1` but `Add support for building apps against iOS 14.1` I believe?

Finally this should have a release note (obviously attached to the BZ issue to be filed).

**Review by runrevmark — APPROVED** [review]

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a0ace42

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok a0ace424454f27da09915042eb9b9333e2e4a777

**Comment by livecode-vulcan** [comment]
😎 test success a0ace424454f27da09915042eb9b9333e2e4a777

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/907)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/316)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/316)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/316)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/316)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2433)
* try-community-universal-ios-iphoneos14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.1/builds/10)
* try-community-universal-ios-iphoneos13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.5/builds/86)
* try-community-universal-ios-iphonesimulator14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.1/builds/10)
* try-community-universal-ios-iphonesimulator13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.5/builds/82)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2460)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2449)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2448)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2483)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2423)

**Pull request merged**
