### PR TITLE
[[ NO MERGE ]] Livecodeali/bugfix 20550

### PR DESCRIPTION
**Pull request by livecodeali**
Test branch for https://github.com/livecode/livecode/pull/6556 with submodule update

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 4b5b3fe

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4b5b3fecbed76872060320d463bf59115a9ef3bf

**Comment by livecode-vulcan** [comment]
😞 test failure 4b5b3fecbed76872060320d463bf59115a9ef3bf

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1523)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1539)
* try-community-js-emscripten-sdk1.35: [failure](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1513)
* try-community-universal-ios-iphoneos11.4: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/40)
* try-community-universal-ios-iphonesimulator11.4: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/40)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1517)
* try-community-universal-mac-macosx10.9: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1543)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1523)
* try-community-x86-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1537)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1522)
* try-community-x86_64-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1532)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1571)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1511)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8665e9a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8665e9af579a6226a5284f7fe8158ae3dbf775e2

**Comment by livecode-vulcan** [comment]
😞 test failure 8665e9af579a6226a5284f7fe8158ae3dbf775e2

* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1540)
* try-community-armv6-android-api26: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api26/builds/24)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1514)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/41)
* try-community-universal-ios-iphonesimulator11.4: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/41)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1544)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1538)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1533)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1572)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1512)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 8665e9a

**Comment by livecode-vulcan** [comment]
😎 test success 8665e9af579a6226a5284f7fe8158ae3dbf775e2

* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1541)
* try-community-armv6-android-api26: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api26/builds/25)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1515)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/42)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/42)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1545)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1539)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1534)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1573)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1513)

**Pull request closed without merging**
