### PR TITLE
[[ Tree View ]] General rework

### PR DESCRIPTION
**Pull request by livecodeali**
- Fix issues with key / value display
- Rename selectedRowColor to hiliteColor
- Rename showFrameBorder to showBorder
- Allow background, foreground and border colors to be user-defined.
  A combination of background, foreground and hilite colors are used
  to generate the appropriate appearance of the alternate row and
  hover colors
- Use 'list' as the default themeClass for the tree view

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok fc23e5c

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok fc23e5ca4dd215b4436120ba11e86032425c6715

**Comment by livecodeali** [comment]
@peter-b updated

**Comment by peter-b** [comment]
@livecode-vulcan review ok aa1e396

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok aa1e3968af9daeb93a9a363d60d9f301fbef5839

**Comment by livecode-vulcan** [comment]
😎 test success aa1e3968af9daeb93a9a363d60d9f301fbef5839
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2030)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2042)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2024)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2038)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2045)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2051)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2058)

**Comment by livecodeali** [comment]
@peter-b Some further updates... hopefully the last

**Comment by peter-b** [comment]
@livecode-vulcan review ok e36a844

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e36a844ed37e9acb7a0db85bdff3124d9868d0c2

**Comment by livecode-vulcan** [comment]
😎 test success e36a844ed37e9acb7a0db85bdff3124d9868d0c2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2041)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2053)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2035)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2049)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2056)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2062)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2069)

**Pull request merged**
