### PR TITLE
[[ Bug 17731 ]] Work around issues with revert command

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodepanos** [comment]
This fix works for me. I tested it locally on Windows 7 and I no longer get a crash when building an html5 standalone.

BTW (this is not related to this patch), it seems that now setting `grevdevelopment`to true has no result, since if I put a breakpoint in `revSaveAs(_platform_name_)Standalone` it is not respected. Moreover, typing `put grevdevelopment` in the msg box returns "grevdevelopment". So it looks like grevdevelopment is not treated as a global. This is probably caused by PR https://github.com/livecode/livecode-ide/pull/1205, since it did not happen in previous builds. I will add this comment in https://github.com/livecode/livecode-ide/pull/1205

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok dfb35e5

**Comment by montegoulding** [comment]
Hmm...ill take a look at it... Sorry

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok dfb35e522a9794b7a72a4bae855403be875e6058

**Comment by livecode-vulcan** [comment]
😎 test success dfb35e522a9794b7a72a4bae855403be875e6058
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2579)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2589)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2574)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2590)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2596)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2600)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2612)

**Pull request merged**
