### PR TITLE
Bugfix revRuggedID

### PR DESCRIPTION
**Pull request by mwieder**
revRuggedID in the IDE backscript library was throwing errors and getting into a tight loop when creating a new stack (enable gRevDevelopment and turn on the Message Watcher to expose and track the error). I placed the hcaddressing check in a try/catch construct to bypass the error. Note: the error is in the 6.x branch as well, but isn't nearly as destructive there.

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @mwieder, please just make a pull request against runrev/livecode-ide. We'll make sure that the submodule punter gets updated as necessary.

**Comment by peter-b** [comment]
"Submodule pointer", even!

**Comment by peter-b** [comment]
@mwieder Also, I know that submodules can be a monumental pain, so if you run into any problems finding the correct set of git incantations let me know. :+1:

**Comment by mwieder** [comment]
rotfl. I think 'punter' may be more to the point. Yeah, I _am_ having trouble figuring out the proper format here. I made my changes in a branch off develop-7.0, I didn't create a new branch in the ide submodule. I hope that's correct. I see there's also a develop-7 branch. Previously I was told to use the 7.0 branch as my base, but I'm not sure that's correct any more. And I could use some guidance on how to get this issued in github because submodules suck.

**Comment by montegoulding** [comment]
@mwieder you need to fork the ide repo, cd into the ide submodule, branch off one of the develops... (I think they all have the same IDE backscript), commit your changes, add your fork as a remote, and do the pull request on that.

**Comment by mwieder** [comment]
Oh, hell... so it's not enough to have multiple copies of the ide submodule in the different develop repos, I now have to create a separate repo for the ide submodule itself?

**Comment by montegoulding** [comment]
No you don't need a separate repo. Once you cd into the submodule dir then your git commands operate on that. So fork [it](https://github.com/runrev/livecode-ide) on github then add it as a remote.

Eg:

```
cd ~/livecode/ide
git remote add myfork https://github.com/mwieder/livecode-ide.git
git branch bugfix_revruggedid
git commit -m "revRuggedID fix"
git push myfork bugfix_revruggedid
```

Then go to https://github.com/mwieder/liveocde-ide and submit the PR

**Comment by montegoulding** [comment]
@mwieder I edited the last comment to fix a few issues with it so don't look at the email

**Comment by montegoulding** [comment]
@peter-b this isn't the simplest stuff to get your head around so perhaps an explanation [here](https://github.com/runrev/livecode/blob/develop/HACKING.md) would be good?

**Comment by mwieder** [comment]
Monte- thanks.
There appear to be develop and master branches here, not branch-formerly-known-as-master, as in the main trunk. Should I issue pull requests against develop?

**Comment by montegoulding** [comment]
develop is 8. You probably want to branch & PR against the lowest versioned develop branch with the issue... they regularly merge develop-6.7 and develop-7.0 into develop but I think to go the other way then need to cherrypick which they had to do a couple of time for me when I didn't think about that...

**Comment by mwieder** [comment]
Hmmm... I forked the ide submodule, but I've got way fewer branches than the original.

**Comment by montegoulding** [comment]
You probably had a fork sitting there from when lc was originally open sourced. If you were like me you forked all their repos just after they were pushed :-)

Either way I'd doesn't matter how many branches are up on GitHub. Just add as remote locally and push to it.

**Comment by mwieder** [comment]
Yeah, IIRC you got there first, but I think I was the second fork. I'm pushing a baseline develop now, and I'll create my branch off develop and submit that.

**Comment by montegoulding** [comment]
Ah those were the days ;-)

**Comment by peter-b** [comment]
@montegoulding Thank you so much for helping with this! :grinning:

**Comment by montegoulding** [comment]
No problem @peter-b

**Comment by mwieder** [comment]
Monte- my thanks too. This is part of my effort to get 7.1 working properly on linux, but I've seen this affect OSX as well.

**Comment by peter-b** [comment]
> @peter-b this isn't the simplest stuff to get your head around so perhaps an explanation here would be good?

@montegoulding I haven't forgotten about this; it's on my list of jobs to do in September, unless someone else on the team gets there first.  It's not the simplest stuff to _explain_, either!

**Pull request closed without merging**
