### PR TITLE
[[ RunRevReferences ]] Remove references to RunRev in LiveCode 8 file…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…s copyright

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 74d3e20

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 74d3e2087aea12537dc6eb6769716d2dd6bfb603

**Comment by livecodesebastien** [comment]
The files in `ide/Documentation/html_viewer/resources/data/api` (such as `script.js`) need to be regenerated, as they have around 1500 references to `Revolution` and `Revolution custom library`.

**Comment by livecodeali** [comment]
It's ok, they are not part of the repo, they are generated at installer build time.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 96d315d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 96d315d684926497e8610e2e7f322621b0bb127c

**Comment by livecode-vulcan** [comment]
😎 test success 96d315d684926497e8610e2e7f322621b0bb127c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/436)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/436)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/435)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/434)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/440)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/431)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/442)

**Pull request merged**
