### PR TITLE
[Bug 16793] Disable LTO on Android (for now)

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 837b5db

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 837b5db447329d5082da0420997eafa474659c72

**Comment by livecode-vulcan** [comment]
😎 test success 837b5db447329d5082da0420997eafa474659c72
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1730)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1745)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1725)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1736)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1746)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1749)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1754)

**Comment by livecodefraser** [comment]
My suggestion would be to just force 'supports_lto' to 0 rather than revert all of the Android LTO changes (just to minimise the code churn). Assuming that is sufficient for the problems to go away...

**Comment by livecodeali** [comment]
@livecodefraser Yeah I suggested that, but apparently it wasn't sufficient for some reason! (I say I suggested it, I think @livecodepanos had already tried it)

**Comment by livecodepanos** [comment]
Unfortunately I was getting some other errors when just forcing 'supports_lto' to 0, which disappeared only after gradually reverting all the Android LTO changes. This patch is temporary, until @livecodefraser returns to fix it properly :)

**Comment by livecodeali** [comment]
Closing as we've reverted the whole LTO patch for DP 14.

**Pull request closed without merging**
