### PR TITLE
Gyp rejig warnings

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 6da19fc

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6da19fca50ee7abc36feb26db2ce9b0979845821

**Comment by livecode-vulcan** [comment]
😎 test success 6da19fca50ee7abc36feb26db2ce9b0979845821
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/247)
- try-win-x86: unknown
- try-ios: unknown
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/258)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/193)
- try-mac: unknown

**Comment by peter-b** [comment]
Argh @livecode-vulcan why are you so buggy.

@livecode-vulcan retry 6da19fc

**Comment by livecode-vulcan** [comment]
😎 test success 6da19fca50ee7abc36feb26db2ce9b0979845821
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/250)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/313)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/201)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/261)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/196)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/193)

**Pull request merged**
