### PR TITLE
[[ ScriptOnly ]] Added RW scriptOnly property of stack

### PR DESCRIPTION
**Pull request by montegoulding**
This is currently undocumented mainly because create script only stack is undocumented and I'm not sure if that means it's meant to be undocumented...

### CODE REVIEW

**Comment by montegoulding** [comment]
@peter-b yay my GitHub linking in my LC account worked. I didn't think it worked because when I returned to livecode.com I got a page that just said Array and there was no indication of the link when I went back to my account.

**Comment by peter-b** [comment]
@montegoulding Yes, it's a bug in the website! I think the web team is aware of the problem.  We're gradually getting there on automating all of our processes... :smiley:

**Comment by peter-b** [comment]
@montegoulding I only added the CLA checking function today and I think you're the first non-staff guinea pig.

**Comment by montegoulding** [comment]
Good plan. Any thoughts on the docs for this. Should I wait for create script only to be documented?

**Comment by peter-b** [comment]
@montegoulding Did you discuss with @runrevmark or was there just the mailing list traffic?  I'm personally not quite convinced yet that this should be a RW property, but I'm willing to be persuaded...

**Comment by montegoulding** [comment]
I just went ahead and did it @peter-b because I had a couple of minutes after I put the kids to bed. I mainly want it personally for read use cases but if I were maintaining the standalone builder or transitioning a project to use script only stacks I'd definitely want it to be a writable property.

**Comment by peter-b** [comment]
@montegoulding  Cool - and thank you very much! :+1:  The only reason I'm worried is because of the possibility of data loss. It would be nice to make the prop to `true` throw an error if the stack contains anything other than a script, for example.

**Comment by montegoulding** [comment]
Hmm... that might defeat the purpose though as it's impossible to have a stack in the IDE without it getting a million custom properties set. I guess you could just mean objects although someone could have transitioned a stack with a UI to object creation in code and setting the scriptOnly is the last step in the transition??? I'm more in the give us enough rope and if we hang ourselves it's our own fault for not reading the warning in the docs camp. I definitely wouldn't represent the property in the IDE anywhere and I don't think it would it be useful in the properties property.

**Comment by peter-b** [comment]
@montegoulding Yeah, I know what you mean. I'm sure someone will give us a 3rd opinion on this tomorrow. :-) Thanks for the patch, it's always easier when you have the actual code!

**Comment by runrevmark** [comment]
I've been pondering this and ultimately, I don't really see a problem with it.

Whilst one would imagine it would be 'better' if script only stacks were restricted in some way, in practice you can't really do that as they are still stacks and so things expect them to work as stacks do. The IDE should probably prevent non-script only things happening to script only stacks rather than the engine.

Therefore, having a property controlling the type of stack seems useful in specific contexts. i.e. the IDE, the S/B and VCS related stuff.

Notionally 'script only stacks' are a stepping stone towards the idea of 'script objects' in a 'project' so we'd gain the safety / protection etc. at the point of getting the latter. With this in mind it seems a bit silly to spend too long on script-only stacks themselves engine-wise.

In regards to documentation - create script only stack needs documentation, and scriptOnly property (this PR) needs an lcdoc. I suggest making it very clear in the docs that the 'scriptOnly' property is only intended to be used for specific purposes (i.e. meta processing of stacks) and fiddling with it might cause data-loss and other such things. That should be enough to warn off all but the most intrepid LiveCoders.

**Comment by runrevmark** [comment]
@montegoulding: Thanks for the docs - and updating the 'create stack' entry... I had intended to that on a separate PR, but you've saved me some time by doing it here :)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok fdedad6

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok fdedad6e2106e2385faeb5f365798b6e85cb90ea

**Comment by runrevmark** [comment]
Thanks again for the submission @montegoulding - this should make it into 8-dp-5.

**Comment by montegoulding** [comment]
no problem

**Comment by livecode-vulcan** [comment]
😎 test success fdedad6e2106e2385faeb5f365798b6e85cb90ea
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/302)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/302)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/301)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/300)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/305)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/297)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/308)

**Pull request merged**
