### PR TITLE
[Dictionary] reset paint to revDatabaseColumnTypes

### PR DESCRIPTION
**Pull request by livecodealice**
command/reset-paint.lcdoc - Removed extraneous HTML.
keyword/resfile.lcdoc - Fixed broken link.
command/revBrowserAddJavaScriptHandler.lcdoc - Reformatted code examples.
function/revBrowserOpen.lcdoc - Fixed broken link and changed associated reference.
command/revBrowserSet.lcdoc - Reformatted code examples.
dictionary/command/revCacheGeometry.lcdoc - Removed all reference to `control (object)` because it doesn’t exist.
command/revCloseCursor.lcdoc - Fixed broken link and changed associated reference.
command/revCloseDatabase.lcdoc - Fixed broken link and changed associated reference.
command/revCloseVideoGrabber.lcdoc - Fixed broken link.
command/revCopyFile.lcdoc - Changed type of result reference.
command/revCopyFolder.lcdoc - Changed type of result reference. Fixed broken link and change one’s associated reference.
function/revCurrentRecord.lcdoc - Fixed broken link and changed associated reference.
function/revCurrentRecordIsFirst.lcdoc - Fixed broken link and changed associated reference.
function/revCurrentRecordIsLast.lcdoc - Fixed broken link and changed associated reference.
function/revDatabaseColumnCount.lcdoc - Fixed broken link and changed associated reference.
function/revDatabaseColumnLengths.lcdoc - Fixed broken link and changed associated reference.
function/revDatabaseColumnNamed.lcdoc - Fixed broken link and changed associated reference.
function/revDatabaseColumnNames.lcdoc - Fixed broken links and changed one’s associated reference.
function/revDatabaseColumnNumbered.lcdoc - Fixed broken link and changed associated reference.
function/revDatabaseColumnTypes.lcdoc - Fixed broken link and changed associated reference.

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 9ff2799

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 9ff2799c050f879313591233cb666013e4ba4481

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 6ee53e3

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 6ee53e35d686da53dac46303eeec027808d311c9

**Comment by livecode-vulcan** [comment]
😎 test success 6ee53e35d686da53dac46303eeec027808d311c9

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/184)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/176)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/176)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/176)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/176)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1698)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/80)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/80)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1728)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1721)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1718)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1754)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1695)

**Pull request merged**
