### PR TITLE
[[ Git ]] Makesure .sh files always have LF engines

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
Engines? :steam_locomotive: 

@livecode-vulcan review ok e823392

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e823392b6b24f0196ea81d2a33eece2c1275b5ce

**Comment by livecodefraser** [comment]
Note who authored the commit... _cough_ @runrevmark _cough_ ;)

**Comment by runrevmark** [comment]
engines = endings, obviously ;)

**Comment by livecode-vulcan** [comment]
😎 test success e823392b6b24f0196ea81d2a33eece2c1275b5ce
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/261)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/324)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/211)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/272)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/207)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/203)

**Pull request merged**
