### PR TITLE
Turn on -Werror=constant-logical-operand

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok ce7294a

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ce7294a9a66b7ba7b309eadedcd7601304a86ca5

**Comment by livecode-vulcan** [comment]
😎 test success ce7294a9a66b7ba7b309eadedcd7601304a86ca5
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/187)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/191)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/187)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/187)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/191)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/187)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/187)

**Comment by montegoulding** [comment]
@livecode-vulcan review by @peter-b ok 0cadb45

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 0cadb456dda066d751862e98b65ed8db8e5bbc46

**Comment by livecode-vulcan** [comment]
😎 test success 0cadb456dda066d751862e98b65ed8db8e5bbc46
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/193)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/197)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/193)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/193)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/197)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/193)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/193)

**Pull request merged**
