### PR TITLE
libfoundation: Re-use iconv file descriptors

### PR DESCRIPTION
**Pull request by peter-b**
Creating a new `iconv_t` file descriptor is an expensive operation.
For UTF-16 encoding/decoding, `iconv_open()` requires at least one
`open()` system call (and additional work) to load its UTF-16 support
shared library.

`iconv_t` file descriptors can be reused safely if they're reset to
their original state by calling `iconv()` with null input and output
pointers.

This patch eliminates about two thirds of the `open()` syscalls that
occur during IDE startup on Linux.

### CODE REVIEW

**Comment by livecodeali** [comment]
@peter-b I'm assuming you didn't mean to include `libfoundation/include/foundation-dynarray.h`? Otherwise, looks good to me!

**Comment by peter-b** [comment]
@livecodeali Fixed that, good spot.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok cc02b04

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok cc02b04412748bc74caeadd3be7292db173b5e78

**Comment by livecode-vulcan** [comment]
😎 test success cc02b04412748bc74caeadd3be7292db173b5e78

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1040)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1043)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1035)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1041)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1045)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1057)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1035)

**Pull request merged**
