### PR TITLE
Merge develop-8.1 into develop

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review by @peter-b ok 6e81061

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6e810613b7d0edb95f22e4ce9de3f2245bdb056f

**Comment by livecode-vulcan** [comment]
😎 test success 6e810613b7d0edb95f22e4ce9de3f2245bdb056f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/205)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/209)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/205)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/205)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/209)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/205)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/205)

**Comment by peter-b** [comment]
I screwed up by updating the submodule pointer in this branch before completing the merge. 😫

**Pull request closed without merging**
