### PR TITLE
[[ Installer ]] Fix command line args parsing

### PR DESCRIPTION
**Pull request by livecodeali**
-ui is not included in the $N arguments, so the index of 'proper' 
arguments to the installer starts at 2 after $0 (the executable) 
and $1 (install)

### CODE REVIEW

**Comment by livecodeali** [comment]
https://gist.github.com/livecodeali/e80cac82f2fa104fed499ddf57498703

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok f5ef5aa

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok f5ef5aa17fa8112ac183bdf3318de012523790ba

**Comment by livecode-vulcan** [comment]
😎 test success f5ef5aa17fa8112ac183bdf3318de012523790ba

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/871)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/877)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/869)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/870)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/877)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/868)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/868)

**Pull request merged**
