### PR TITLE
[12315] Ensure files open for driver have stdio buffering turned off

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodepanos Looking through the uses of `MCS_sync` then it currently seems to be disabled on win/macOS (although its not clean why its necessary on other platforms either). As this is pertinent to serial connections - I wonder if it should only be done if 'open driver' was used?

**Comment by runrevmark** [comment]
So looking at this again - I wonder if MCS_flush is *actually* more appropriate here (when writing to a driver). The implementation of MCS_sync is strange - I can see it would work, but I suspect is a hack dating back to inconsistent UNIX systems a very long time ago.

Indeed, I'm inclined to think the underlying issue is really that (on macOS and Linux - the issue doesn't affect Windows) is that the FILE* (C stdio stream) backing the IO in this case is line-buffered. Therefore we could probably fix it much more neatly by ensuring that files open for driver on macOS/Linux have their stdio buffering turned off.

Instead of adding the MCS_sync() call, in the OpenDevice() implementations on macOS and Linux can we try adding:
```
setbuf(fptr, nullptr);
```
After checking that we have a valid fptr? This call sets the stream to non-buffering.

This should eliminate the need to add sync or flush after writes - as any data written to the stream will be immediately written to the underlying file descriptor.

[ This isn't needed on Win32 as we do direct file I/O there ]

**Comment by livecodepanos** [comment]
@runrevmark I have done the changes you suggested and tested again with the sample stack and the serial device - I confirm the problem is fixed :)

**Comment by runrevmark** [comment]
@livecodepanos Great! It's a much neater fix then putting in sync calls and such - especially as the change only affects open driver now :)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 086d790

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 086d790aa525b9d7b9964206a740c7f7afc43422

**Comment by livecode-vulcan** [comment]
😎 test success 086d790aa525b9d7b9964206a740c7f7afc43422

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/551)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/543)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/543)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/544)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/543)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2065)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/292)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/292)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2096)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2087)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2085)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2120)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2057)

**Pull request merged**
