### PR TITLE
[[ Bug 22042 ]] Update SQLite to v3.28.0

### PR DESCRIPTION
**Pull request by runrevmark**
This patch adds a release note for the update of SQLite in the
thirdparty submodule.

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 74d80c1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 74d80c14b69468acf23867c18308c56863bb133e

**Comment by livecodepanos** [comment]
No need to wait for the checks to finish - this is just a release note PR. Merging it now so as to kick off a new build asap

**Comment by livecode-vulcan** [comment]
⁉ merge unchanged 74d80c14b69468acf23867c18308c56863bb133e → f62154257e04da0712bad0be8d30b9c6c7b539c1

Pull request is already fully merged!

**Pull request merged**
