### PR TITLE
[[ Bug 18343 ]] Fix incorrect result from itemOffset when first character of stringToSearch is the delimiter

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1af0a1c

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1af0a1c1e0aea00e04026558f507d97e35d3d97c

**Comment by livecode-vulcan** [comment]
😞 test failure 1af0a1c1e0aea00e04026558f507d97e35d3d97c
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/260)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/264)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/260)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/260)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/264)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/260)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/260)

**Comment by peter-b** [comment]
@livecode-vulcan retry 1af0a1c

**Comment by livecode-vulcan** [comment]
😎 test success 1af0a1c1e0aea00e04026558f507d97e35d3d97c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/262)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/266)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/262)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/262)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/266)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/262)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/262)

**Comment by peter-b** [comment]
@livecode-vulcan review ok e18cc0f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e18cc0f2b807afb5d7b2a0aec463f48552dd5907

**Comment by livecode-vulcan** [comment]
😎 test success e18cc0f2b807afb5d7b2a0aec463f48552dd5907
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/264)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/268)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/264)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/264)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/268)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/264)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/264)

**Pull request merged**
