### PR TITLE
[Bugfix 19609] Fix unicode not show in browser's htmlText

### PR DESCRIPTION
**Pull request by HedgeHao**
Not sure if this patch cause side effects but it does fix the bug.

### CODE REVIEW

**Comment by runrevmark** [comment]
@HedgeHao Thanks for your PR :)

Looking into this, your fix isn't quite correct as you are changing the meaning of MCJavaStringFromNative. 

Looking at the libbrowser android source, the issue comes about because the htmlText accessor:
```
	bool SetHTMLText(const char *p_utf8_string)
	{
		MCAndroidObjectRemoteCall(m_view, "loadHtml", "vss", nil, LIBBROWSER_DUMMY_URL, p_utf8_string);
		return true;
	}
```
Is specifying that p_utf8_string should be passed to android as format 's' which corresponds to 'native c-string'. It really needs to be 'utf8 c-string' which we currently don't have a format for in MCAndroidObjectRemoteCall - with that in place, it would be a simple change to the format string to make this work.

If you want to have a go at adding a utf8 c-string format type then the code can be found in MCJavaConvertParameters. I'd recommend using 't' to indicate a utf-8 c-string.

**Comment by HedgeHao** [comment]
@runrevmark thanks for your comment 👍

**Comment by HedgeHao** [comment]
This PR lies here for couple months.. Can someone review it?

**Comment by montegoulding** [comment]
@HedgeHao sorry about that. This seems fine to me.

@livecode-vulcan review ok f13a3c9

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok f13a3c96d347d90ccaa949a7217e5d29a0542a0d

**Comment by livecode-vulcan** [comment]
😎 test success f13a3c96d347d90ccaa949a7217e5d29a0542a0d

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/542)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/557)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/531)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/474)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/477)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/537)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/545)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/540)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/557)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/540)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/550)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/572)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/536)

**Comment by montegoulding** [comment]
@HedgeHao I'm sorry there is apparently some internal chatter about this PR I missed and @runrevmark wanted to respond and must have been side-tracked. I'll review not ok just so it doesn't get merged until he has a chance to look at it again. Again, sorry about the wait!

@livecode-vulcan review not ok f13a3c9

**Comment by livecode-vulcan** [comment]
💔 review by @montegoulding not ok f13a3c96d347d90ccaa949a7217e5d29a0542a0d

**Comment by HedgeHao** [comment]
@runrevmark Can you review this one? The milestones keep pushing back. It's been four months since my last commit... Thanks!

**Comment by runrevmark** [comment]
@HedgeHao Sorry for the delay! I hope you don't mind but I made a small change to the code to ensure that Supplementary Plane characters will work. The JNI uses a 'Modified UTF-8' encoding, whereas the engine uses normal UTF-8, so I've change it to create a JString using UTF-16 chars instead.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 4a18435

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4a184354f073ed4fcfd2ebba52eaa5cafe2162fd

**Comment by livecode-vulcan** [comment]
😎 test success 4a184354f073ed4fcfd2ebba52eaa5cafe2162fd

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/752)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/768)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/742)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/685)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/687)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/746)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/766)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/751)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/768)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/750)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/761)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/782)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/746)

**Pull request merged**
