### PR TITLE
Do not build 32bit MacOS prebuilts

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 8ec530a

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 8ec530a02a7a42910999abbeedbb267b6d08e155

**Comment by livecode-vulcan** [comment]
😞 test failure 8ec530a02a7a42910999abbeedbb267b6d08e155

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/940)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/348)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/347)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/346)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/347)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2465)
* try-community-universal-ios-iphoneos14.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.3/builds/0)
* try-community-universal-ios-iphoneos14.1: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.1/builds/43)
* try-community-universal-ios-iphonesimulator14.3: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.3/builds/0)
* try-community-universal-ios-iphonesimulator14.1: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.1/builds/41)
* try-community-universal-mac-macosx10.9: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2492)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2481)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2479)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2516)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2452)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 8ec530a

**Comment by livecode-vulcan** [comment]
😎 test success 8ec530a02a7a42910999abbeedbb267b6d08e155

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/941)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/349)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/348)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/347)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/348)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2466)
* try-community-universal-ios-iphoneos14.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.3/builds/1)
* try-community-universal-ios-iphoneos14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.1/builds/44)
* try-community-universal-ios-iphonesimulator14.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.3/builds/1)
* try-community-universal-ios-iphonesimulator14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.1/builds/42)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2493)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2482)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2480)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2517)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2453)

**Pull request merged**
