### PR TITLE
[Bug 16859] Make sure we use chmod on Linux only

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok c098ec1

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c098ec1dc2e7b062a4aa6bdb162d610a72919002

**Comment by livecode-vulcan** [comment]
😎 test success c098ec1dc2e7b062a4aa6bdb162d610a72919002
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1748)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1763)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1743)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1754)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1764)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1767)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1772)

**Comment by livecodeali** [comment]
Argh, sorry. My fault for targeting at develop https://github.com/livecode/livecode/pull/3392

**Comment by livecodepanos** [comment]
Added bugfix note, self-review:

@livecode-vulcan review ok 86f2a43

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 86f2a433c8593e4e1f3e636d88d5754a5da91903

**Comment by livecodepanos** [comment]
Added more descriptive bugfix note, self-review:

@livecode-vulcan review ok 787cca0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 787cca01a482e728d9067a1d8eec428b7bf5565b

**Comment by livecode-vulcan** [comment]
😎 test success 787cca01a482e728d9067a1d8eec428b7bf5565b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1750)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1765)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1745)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1756)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1766)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1769)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1774)

**Pull request merged**
