### PR TITLE
[emscripten] LCB extensions in HTML5 standalones

### PR DESCRIPTION
**Pull request by peter-b**
When building HTML5 standalones, include any requested extensions in the `/boot/extensions` directory.  Provide a `/boot/extensions/extensions.txt` directory that describes the dependency load order.  Add rules to the HTML5 startup script to load all included extensions.

### CODE REVIEW

**Comment by peter-b** [comment]
This will now compile extensions into standalone archives and load them in the pre-startup script in the correct order.  However, no extensions are usable; they will all fail verification due to inability to access global variables using `dlsym(3)`.  This will be fixed in a future PR.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 7e346de

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 7e346de7a712f63b8d85f91d3eb22e4c5d6a7f75

**Comment by livecode-vulcan** [comment]
😎 test success 7e346de7a712f63b8d85f91d3eb22e4c5d6a7f75
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/372)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/372)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/371)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/370)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/375)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/367)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/378)

**Pull request merged**
