### PR TITLE
[[ Header Bar ]] Fix regression when setting actionStyle to names

### PR DESCRIPTION
**Pull request by livecodeali**
Added some basic property tests to try and prevent similar regressions in the future.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3f04fb2

**Comment by peter-b** [comment]
This seems to be something that the LCB compiler should be able to help with -- the bug here is indistinguishable from a null pointer dereference due to a codepath that doesn't initialise a variable properly.  Maybe there's a language bug here?

/cc @runrevmark

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3f04fb2428c7874443b4033c81e7d64ccb31974e

**Comment by livecode-vulcan** [comment]
😎 test success 3f04fb2428c7874443b4033c81e7d64ccb31974e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1752)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1767)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1747)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1758)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1768)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1771)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1776)

**Pull request merged**
