### PR TITLE
[[ Bug 15305 ]] Ensure that nowhere is s_pending_key_down dereferenced if nil

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
As @runrevpanos noticed, that does not fix properly the output in the Script Editor, only in a field / Message Box.
More work needed.

**Comment by livecodesebastien** [comment]
Pull request updated, and the wrong behaviour has been fixed.
Note that the fix for the IME insertion also fixes the resurgence of the bug 14162.

**Comment by runrevmark** [comment]
Reviewed-by: @runrevmark.

**Comment by peter-b** [comment]
@livecode-vulcan review by @runrevmark ok 1878a12

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 1878a128197875ad2e8332a23364fb520725b8d5

**Pull request merged**
