### PR TITLE
[Bug 14447] [Docs] Updated QT-related dictionary entries

### PR DESCRIPTION
**Pull request by livecodepanos**
to make clear that dontuseqt should be false to allow interaction with QT

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevpanos, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 741cc57

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 741cc57c46e21c313eb951313357424b8aa8a900

**Comment by livecode-vulcan** [comment]
😎 test success 741cc57c46e21c313eb951313357424b8aa8a900
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/207)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/206)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/207)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/202)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/209)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/207)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/210)

**Pull request merged**
