### PR TITLE
Add -Werror=conversion-null to build settings

### PR DESCRIPTION
**Pull request by peter-b**
Enabling this error causes the build to fail when converting a null pointer to an integer.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok f276131

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f276131d8ce7b7ae33efe91f6676da2bf8a53738

**Comment by livecode-vulcan** [comment]
😞 test failure f276131d8ce7b7ae33efe91f6676da2bf8a53738
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/138)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/138)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/138)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/138)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/138)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/138)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/138)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok d1edef6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok d1edef685655e1c08c1d8c238ccf1dc7891ae087

**Comment by livecode-vulcan** [comment]
😞 test failure d1edef685655e1c08c1d8c238ccf1dc7891ae087
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/139)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/139)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/139)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/139)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/139)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/139)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/139)

**Comment by peter-b** [comment]
@livecodeali Some of the fixes in the original version of this branch apparently got lost when I rebased it.  This should now be complete (and I've tested that the commercial build isn't saddened by the changes either).

**Comment by peter-b** [comment]
I've moved this to `develop-8.1` because it fixes Linux build failure (on some configurations) caused by commit f86365ec

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 0f6fdc9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 0f6fdc97c678f2a39987ade9bf4711efb4e61c2d

**Comment by livecode-vulcan** [comment]
😞 test failure 0f6fdc97c678f2a39987ade9bf4711efb4e61c2d
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/152)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/156)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/152)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/152)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/153)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/152)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/152)

**Comment by peter-b** [comment]
@livecode-vulcan retry 0f6fdc9

**Comment by livecode-vulcan** [comment]
😎 test success 0f6fdc97c678f2a39987ade9bf4711efb4e61c2d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/161)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/165)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/161)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/161)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/165)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/161)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/161)

**Pull request merged**
