### PR TITLE
[[ Bug 18969 ]] Add 'Select All' as builtin field action

### PR DESCRIPTION
**Pull request by runrevmark**
This patch adds support for Ctrl+A/Cmd+A in the field control,
causing the field's whole text to be selected when triggered.

### CODE REVIEW

**Comment by runrevmark** [comment]
This needs updating after #4962 is fixed.

**Comment by peter-b** [comment]
@livecode-vulcan review ok f1a0681

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f1a0681ac3f18210bd2c43a468eb31981272b9fd

**Comment by livecode-vulcan** [comment]
😎 test success f1a0681ac3f18210bd2c43a468eb31981272b9fd

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/723)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/724)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/721)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/722)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/728)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/719)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/720)

**Pull request merged**
