### PR TITLE
[[ Bugfix 18135 ]] Clear extended file attributes from iOS app bundle

### PR DESCRIPTION
**Pull request by montegoulding**
This needs testing on 10.12 as that's what the original report was made against. I have only tested on 10.11 so far.

### CODE REVIEW

**Comment by livecodepanos** [comment]
I applied part of this patch locally (just added the line `get shell("xattr -cr" && quote & pAppBundle & quote)` in `revsaveasiosstandalone.livecodescript` ) and:
- it fixes the error message on macOS 10.12 (tested with beta 7 version)
- it does not break anything in OSX 10.10

So I am marking this as reviewed, and I'll do further testing when we have an installer build.

@livecode-vulcan review ok 45f398f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 45f398f08851438cdc1e1906593f5e63c6e999d8

**Comment by livecodepanos** [comment]
Hmm maybe we should retarget this PR against `develop-8.1` now?

**Comment by livecode-vulcan** [comment]
😎 test success 45f398f08851438cdc1e1906593f5e63c6e999d8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/112)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/112)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/112)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/112)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/112)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/112)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/112)

**Pull request merged**
