### PR TITLE
[[ Community Docs ]] Format, examples, and tag

### PR DESCRIPTION
**Pull request by asayd**
- Fixed some format problems with the description (list of schemes are not showing on separate lines)
- One example used a very old, classic Mac OS style file path
- Added examples using URL as destination rather than source, including need to textEncode and textDecode when reading and writing to external files.
- Added file system tag, since URL can be used to read/write from local file system

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @asayd, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by livecodeali** [comment]
HI @asayd, thanks for this.

I think the schema would be better changed into a markdown list, eg:

```
* http: a page from a web server
* ftp: a directory or file on an FTP server
...
```

And then they don't need to be on double-spaced lines.

Otherwise this looks great, thanks very much!

**Comment by livecodeali** [comment]
Oh and the file scheme probably shouldn't be a link to the file keyword, so could you remove the &lt; and &gt; from it please?

**Comment by asayd** [comment]
Hi @livecodeali,
Yeah, I wondered about whether the schemes should be a list, but couldn't find how to do it in the documenation. I know now. I'll also remove the link around the file scheme. (It was there before my PR, 
BTW.)
I'm keen to help some more with the docs, as a way of becoming familiar with github, so please be patient if I have some basic questions.

**Comment by livecodeali** [comment]
@asayd Great, thanks! Didn't mean to imply that the file link was your fault, just a sort of 'while you are in there' kind of thing.
Anyway, no worries about basic questions, happy to answer them!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 72154e9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 72154e99a885da05276c9b3859da2959c9d820d5

**Comment by livecode-vulcan** [comment]
😎 test success 72154e99a885da05276c9b3859da2959c9d820d5
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2366)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2376)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2359)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2377)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2383)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2387)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2399)

**Pull request merged**
