### PR TITLE
[Bug 21491] Ensure pageRanges and pageHeights return correct results

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodepanos This looks correct - I take it things are now returning the same as they did in 6.x? (someone referenced that on the use-list I think...). If so, then this can get a review ok :)

**Comment by runrevmark** [comment]
@livecodepanos Might be good to add a test for this :)

**Comment by livecodepanos** [comment]
@runrevmark Yes with this patch the function is now returning similar results as in 6.6.5 (things were first broken in 6.7.0)

RE the test, I'll try to convert the sample stack into a test, as this bug is seen only with specific field content.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok d13b2cf

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d13b2cfc39dd8dc06997b668d2e4000352fd3dfe

**Comment by livecode-vulcan** [comment]
😎 test success d13b2cfc39dd8dc06997b668d2e4000352fd3dfe

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/72)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/64)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/64)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/64)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/64)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1586)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/113)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/113)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1616)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1610)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1606)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1643)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1583)

**Pull request merged**
