### PR TITLE
[[ GradientRampEditor ]] Initial implementation of a gradient ramp ed…

### PR DESCRIPTION
**Pull request by livecodemichael**
…itor to be used by the property inspector.

### CODE REVIEW

**Comment by runrevben** [comment]
@livecode-vulcan review ok faff151

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok faff15115f59b87d3a4fd22ae174ad28544bee14

**Comment by livecode-vulcan** [comment]
😞 test failure faff15115f59b87d3a4fd22ae174ad28544bee14
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/554)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/613)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/503)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/567)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/499)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/492)

**Comment by livecodemichael** [comment]
@livecode-vulcan retry faff151

**Comment by livecode-vulcan** [comment]
😎 test success faff15115f59b87d3a4fd22ae174ad28544bee14
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/555)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/614)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/504)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/568)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/500)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/493)

**Pull request merged**
