### PR TITLE
[[ Bug fix 9030 ]] Clarify how pageRect works

### PR DESCRIPTION
**Pull request by trevordevore**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@trevordevore Could you please rename `Bugfix-9030.md` to `bugfix-9030.md`?

I think our release notes parser is case-sensitive.

**Comment by livecodepanos** [comment]
Thank you @trevordevore 👍 

@livecode-vulcan review ok 2ed3216

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 2ed3216c2db43cb9a0af358fadb9b481ebd4b202

**Comment by livecodepanos** [comment]
@seaniepie This residual is no longer present, as it has been removed in one of the next commits (it is preferable to see the diffs in total and not per commit).

**Comment by livecodepanos** [comment]
Hehe sorry @seaniepie, I missed your previous comment

**Comment by seaniepie** [comment]
Yep, I saw it eventually. 😣

**Comment by trevordevore** [comment]
@seaniepie I'm going to punt on changing instances of `you` in the doc. There are a number of them so I will just leave it at "this falls outside the scope of this bug fix" ;-)

**Comment by seaniepie** [comment]
I’ll save it for later once yours is merged. 😌

**Comment by livecode-vulcan** [comment]
😎 test success 2ed3216c2db43cb9a0af358fadb9b481ebd4b202

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/161)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/153)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/153)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/153)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/153)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1675)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/57)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/57)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1705)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1698)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1695)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1731)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1672)

**Comment by seaniepie** [comment]
I was mistaken in my understanding. The guide says:

> **Addressing the user**
> 
> Address the user as 'you' where possible. Documentation often makes a direct appeal to LiveCode users to take action, eg 'Deploy your stack to your phone' or 'Store your content in a database'.

I think I'd confused it with the guides for submitting pull requests or something entirely different. Carry on! As you were! 😞

**Comment by trevordevore** [comment]
Hey, less work for you :-)

**Pull request merged**
