### PR TITLE
Merge release 8.0.0 29.04.16

### PR DESCRIPTION
**Pull request by livecodeali**
Aside from the usual IDE and version conflicts, there were conflicts in the following dictionary files, due to having changed `object (object)` to `object (glossary)` in develop-8.0 and `(control_st)` to `(control structure)` in release-8.0.0

```
both modified:   docs/dictionary/command/call.lcdoc
both modified:   docs/dictionary/command/libURLftpUpload.lcdoc
both modified:   docs/dictionary/command/load.lcdoc
both modified:   docs/dictionary/command/read-from-socket.lcdoc
both modified:   docs/dictionary/command/send.lcdoc
both modified:   docs/dictionary/command/start-using.lcdoc
both modified:   docs/dictionary/control_st/exit-to-top.lcdoc
both modified:   docs/dictionary/control_st/exit.lcdoc
both modified:   docs/dictionary/control_st/getProp.lcdoc
both modified:   docs/dictionary/control_st/on.lcdoc
both modified:   docs/dictionary/control_st/pass.lcdoc
both modified:   docs/dictionary/control_st/return.lcdoc
both modified:   docs/dictionary/control_st/setProp.lcdoc
both modified:   docs/dictionary/control_st/throw.lcdoc
both modified:   docs/dictionary/function/clipboard.lcdoc
both modified:   docs/dictionary/function/dragDestination.lcdoc
both modified:   docs/dictionary/function/dragSource.lcdoc
both modified:   docs/dictionary/function/errorObject.lcdoc
both modified:   docs/dictionary/function/exists.lcdoc
both modified:   docs/dictionary/function/flushEvents.lcdoc
both modified:   docs/dictionary/function/focusedObject.lcdoc
both modified:   docs/dictionary/function/frontScripts.lcdoc
both modified:   docs/dictionary/function/intersect.lcdoc
both modified:   docs/dictionary/function/mouseColor.lcdoc
both modified:   docs/dictionary/function/number.lcdoc
both modified:   docs/dictionary/function/pendingMessages.lcdoc
both modified:   docs/dictionary/function/selectedField.lcdoc
both modified:   docs/dictionary/function/selectedObject.lcdoc
both modified:   docs/dictionary/function/target.lcdoc
both modified:   docs/dictionary/function/textHeightSum.lcdoc
both modified:   docs/dictionary/function/uniDecode.lcdoc
both modified:   docs/dictionary/function/uniEncode.lcdoc
both modified:   docs/dictionary/function/value.lcdoc
both modified:   docs/dictionary/function/within.lcdoc
both modified:   docs/dictionary/keyword/long.lcdoc
both modified:   docs/dictionary/keyword/me.lcdoc
both modified:   docs/dictionary/keyword/of.lcdoc
both modified:   docs/dictionary/keyword/target.lcdoc
both modified:   docs/dictionary/keyword/templateAudioClip.lcdoc
both modified:   docs/dictionary/keyword/templateButton.lcdoc
both modified:   docs/dictionary/keyword/templateCard.lcdoc
both modified:   docs/dictionary/keyword/templateEPS.lcdoc
both modified:   docs/dictionary/keyword/templateField.lcdoc
both modified:   docs/dictionary/keyword/templateGraphic.lcdoc
both modified:   docs/dictionary/keyword/templateGroup.lcdoc
both modified:   docs/dictionary/keyword/templateImage.lcdoc
both modified:   docs/dictionary/keyword/templatePlayer.lcdoc
both modified:   docs/dictionary/keyword/templateScrollbar.lcdoc
both modified:   docs/dictionary/keyword/templateStack.lcdoc
both modified:   docs/dictionary/keyword/templateVideoClip.lcdoc
both modified:   docs/dictionary/message/IDChanged.lcdoc
both modified:   docs/dictionary/message/arrowKey.lcdoc
both modified:   docs/dictionary/message/closeStackRequest.lcdoc
both modified:   docs/dictionary/message/deleteEPS.lcdoc
both modified:   docs/dictionary/message/dragDrop.lcdoc
both modified:   docs/dictionary/message/dragEnd.lcdoc
both modified:   docs/dictionary/message/dragEnter.lcdoc
both modified:   docs/dictionary/message/enterInField.lcdoc
both modified:   docs/dictionary/message/nameChanged.lcdoc
both modified:   docs/dictionary/message/newBackground.lcdoc
both modified:   docs/dictionary/message/newButton.lcdoc
both modified:   docs/dictionary/message/newCard.lcdoc
both modified:   docs/dictionary/message/newEPS.lcdoc
both modified:   docs/dictionary/message/newField.lcdoc
both modified:   docs/dictionary/message/newGraphic.lcdoc
both modified:   docs/dictionary/message/newGroup.lcdoc
both modified:   docs/dictionary/message/newImage.lcdoc
both modified:   docs/dictionary/message/newPlayer.lcdoc
both modified:   docs/dictionary/message/newScrollbar.lcdoc
both modified:   docs/dictionary/message/newStack.lcdoc
both modified:   docs/dictionary/message/newWidget.lcdoc
both modified:   docs/dictionary/message/openCard.lcdoc
both modified:   docs/dictionary/message/openStack.lcdoc
both modified:   docs/dictionary/message/preOpenCard.lcdoc
both modified:   docs/dictionary/message/preOpenStack.lcdoc
both modified:   docs/dictionary/message/rawKeyDown.lcdoc
both modified:   docs/dictionary/message/resizeControl.lcdoc
both modified:   docs/dictionary/message/returnInField.lcdoc
both modified:   docs/dictionary/message/shutdownRequest.lcdoc
both modified:   docs/dictionary/operator/there-is-a.lcdoc
both modified:   docs/dictionary/operator/there-is-no.lcdoc
both modified:   docs/dictionary/property/customProperties.lcdoc
both modified:   docs/dictionary/property/customPropertySets.lcdoc
both modified:   docs/dictionary/property/imageData.lcdoc
both modified:   docs/dictionary/property/properties.lcdoc
```

### CODE REVIEW

**Comment by livecodeali** [comment]
Conflict resolution diff:
https://gist.github.com/livecodeali/0b5e028ee3298c02fe45e74d93d7b7e0

I rewrapped a few dictionary files whilst merging.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 7d62fda

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 7d62fdaa6641b5c877c06dc7ce108687e924fa1b

**Comment by livecode-vulcan** [comment]
😎 test success 7d62fdaa6641b5c877c06dc7ce108687e924fa1b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2469)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2479)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2462)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2480)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2486)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2490)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2502)

**Pull request merged**
