### PR TITLE
[[ tsNet ]] Update tsNet pointer to version 1.2.3

### PR DESCRIPTION
**Pull request by techstrategies**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok fa2c265

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok fa2c2658ba33fb0adbe552d71d3eecf9108ed3ff

**Comment by livecode-vulcan** [comment]
😞 test failure fa2c2658ba33fb0adbe552d71d3eecf9108ed3ff
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/198)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/202)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/198)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/198)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/202)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/198)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/198)

**Comment by peter-b** [comment]
Merged as #4508.

**Pull request closed without merging**
