### PR TITLE
[[ Community Docs ]] Working with Databases

### PR DESCRIPTION
**Pull request by asayd**
- Fixed malformed table.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3d4555e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3d4555ea158b1069d98dfa7eb79f87af8b858167

**Comment by livecode-vulcan** [comment]
😎 test success 3d4555ea158b1069d98dfa7eb79f87af8b858167
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2485)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2495)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2478)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2496)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2502)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2506)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2518)

**Comment by peter-b** [comment]
Thanks @asayd!

**Pull request merged**
