### PR TITLE
[Bug 13586] Tweak X11 class for commercial editions.

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok e660a83

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok e660a8369d219d8208113c3659452d1ccd3be74c

**Comment by livecode-vulcan** [comment]
😎 test success e660a8369d219d8208113c3659452d1ccd3be74c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1252)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1264)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1249)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1258)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1269)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1269)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1273)

**Comment by livecodeali** [comment]
Wow, I really dropped the ball on that review. Sorry @peter-b.

**Pull request merged**
