### PR TITLE
[[ Bug 18870 ]] Add release note

### PR DESCRIPTION
**Pull request by techstrategies**

### CODE REVIEW

**Comment by livecodeali** [comment]
Fixed in this update: https://github.com/livecode/livecode/pull/5017

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 6c54c92

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 6c54c929489f1d62440de0b89d34e1ce667911fd

**Comment by livecode-vulcan** [comment]
😞 test failure 6c54c929489f1d62440de0b89d34e1ce667911fd

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/775)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/780)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/773)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/774)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/780)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/772)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/772)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 6c54c92

**Comment by livecode-vulcan** [comment]
😎 test success 6c54c929489f1d62440de0b89d34e1ce667911fd

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/797)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/802)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/795)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/796)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/802)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/794)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/794)

**Pull request merged**
