### PR TITLE
[Bug 17790] Make sure the mouseAction is updated correctly

### PR DESCRIPTION
**Pull request by livecodepanos**
when clicking on the headerBar widget

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3616165

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3616165cff2cae114f5d9c5c3457331e24b8f3be

**Comment by peter-b** [comment]
@livecode-vulcan review ok 918be6f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 918be6f15ec9ff7daf941086350aacd824feea2f

**Comment by livecode-vulcan** [comment]
😎 test success 918be6f15ec9ff7daf941086350aacd824feea2f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2591)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2601)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2586)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2602)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2608)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2612)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2626)

**Pull request merged**
