### PR TITLE
Merge release 8.1.6 31.07.17

### PR DESCRIPTION
**Pull request by livecodeali**
Trivial conflicts in version and ide

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 031c0c7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 031c0c78e911578e95a343c4fd4ba0f7b6d140ae

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 031c0c78e911578e95a343c4fd4ba0f7b6d140ae

**Comment by livecode-vulcan** [comment]
😎 test success 031c0c78e911578e95a343c4fd4ba0f7b6d140ae

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/545)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/560)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/534)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/477)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/480)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/540)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/548)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/543)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/560)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/543)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/553)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/575)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/539)

**Pull request merged**
