### PR TITLE
[[ CommandArguments ]] Feature commandline arguments

### PR DESCRIPTION
**Pull request by livecodesebastien**
This pull request adds the functions
- commandName (return $0)
- commandArguments (returns all the other command line parameters)

Only valid for desktop standalones and server scripts. These functions return empty from the IDE and on mobile platforms.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodesebastien: Thank you for implementing this! I know that our users will be very pleased.  Unfortunately there is a small problem: `the commandArguments` cannot return a list, because each argument could contain any character, including `,`, `\n`, etc.  It should probably return an numerical array of strings in order to cope with this

**Comment by runrevmark** [comment]
I must confess I was wondering whether a command argument could contain '\n' :)

What we could do here is make the zero argument form of 'the commandArguments' return a numerically indexed array of strings. Then make the one argument form of 'the commandArguments' return the argument with the given index. (The latter has precedent as it is how the 'param()' function works - which returns the parameter to the current handler for a given index).

**Comment by livecodesebastien** [comment]
@runrevmark that sounds like a good idea, since it follows `param()` behaviour

**Comment by livecodesebastien** [comment]
Closed as it won't get implemented in 6.7

**Pull request closed without merging**
