### PR TITLE
[Bug 14223] Add messageDigest() function with SHA2 and SHA3 support

### PR DESCRIPTION
**Pull request by peter-b**
Add a new `messageDigest(<type>, <message>)` function that allows
access to a large variety of cryptographic message digest hash
functions, including SHA2 and SHA3.

### CODE REVIEW

**Comment by montegoulding** [comment]
@peter-b the params feel like they are in the wrong order to me. I think most engine functions would be thing to do something to, options rather than the other way around.

**Comment by peter-b** [comment]
@montegoulding I've swapped the parameters over so they're the same order as e.g. `textEncode()`.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a303de8

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok a303de8ccbd501d328fe1d7ca866a7dd000d7a91

**Comment by livecode-vulcan** [comment]
😞 test failure a303de8ccbd501d328fe1d7ca866a7dd000d7a91

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1046)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1049)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1041)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1047)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1051)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1063)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1041)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok f5bbd6b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f5bbd6b38ae1c97ae36dc2603ad3d816c83f188a

**Comment by livecode-vulcan** [comment]
😞 test failure f5bbd6b38ae1c97ae36dc2603ad3d816c83f188a

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1060)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1063)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1055)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1061)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1065)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1077)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1055)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 507744e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 507744e82e787c3e614292cc99f668a18fd89f0b

**Comment by livecode-vulcan** [comment]
😎 test success 507744e82e787c3e614292cc99f668a18fd89f0b

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1061)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1064)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1056)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1062)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1066)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1078)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1056)

**Pull request merged**
