### PR TITLE
[[ Community Docs ]] Merge into develop-8.0

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Reviewed elsewhere - just need to check they pass the example code tests.
@livecode-vulcan review ok f09325c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f09325c7f2791eb6672de016c29274d2798f4452

**Comment by livecode-vulcan** [comment]
😎 test success f09325c7f2791eb6672de016c29274d2798f4452
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2668)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2678)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2663)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2679)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2685)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2691)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2703)

**Comment by montegoulding** [comment]
@livecodeali did you want this merged. I think the example tests are on develop though.

**Comment by livecodeali** [comment]
@montegoulding Might as well - we'll catch any example test failures in the merge.

**Pull request merged**
