### PR TITLE
[[ Bug 16700 ]] Add support for URLs hosted on SNI aware servers.

### PR DESCRIPTION
**Pull request by livecodemichael**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9cee9a0

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9cee0a0

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9cee0a0eee5b980d693688ed1101403ca5bb1524

**Comment by livecode-vulcan** [comment]
😞 test failure 9cee0a0eee5b980d693688ed1101403ca5bb1524
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1601)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1620)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1597)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1608)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1621)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1622)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1624)

**Comment by livecodemichael** [comment]
@livecode-vulcan retry 9cee0a0

**Comment by livecode-vulcan** [comment]
😎 test success 9cee0a0eee5b980d693688ed1101403ca5bb1524
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1603)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1622)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1599)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1610)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1623)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1624)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1626)

**Pull request merged**
