### PR TITLE
[[ Merge develop 7.0 ]] 10-11-15

### PR DESCRIPTION
**Pull request by livecodesebastien**
Clean merge, apart from the files listed in 'Conflicts'.

Conflicts:
    engine/src/stackview.cpp: fixed by applying the same changes as in 7

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 5222840

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 5222840649942c239d704feb12b50f637b122141

**Comment by livecode-vulcan** [comment]
😞 test failure 5222840649942c239d704feb12b50f637b122141
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1096)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1105)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1093)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1098)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1109)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1114)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1114)

**Comment by peter-b** [comment]
@livecode-vulcan retry 5222840

**Comment by livecode-vulcan** [comment]
😎 test success 5222840649942c239d704feb12b50f637b122141
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1102)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1111)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1099)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1104)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1115)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1120)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1120)

**Pull request merged**
