### PR TITLE
[[ Bug 16642 ]] Ensure all dictionary files are included in the installer

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 011dcea

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 011dcea85a571282eba21631fe762c3e6daebac9

**Comment by livecode-vulcan** [comment]
😞 test failure 011dcea85a571282eba21631fe762c3e6daebac9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1526)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1545)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1522)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1533)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1545)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1546)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1548)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 011dcea

**Comment by livecode-vulcan** [comment]
😎 test success 011dcea85a571282eba21631fe762c3e6daebac9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1528)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1547)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1524)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1535)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1547)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1548)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1550)

**Pull request merged**
