### PR TITLE
LCS: Script Only Stack Specification

### PR DESCRIPTION
**Pull request by runrevmark**
This is a place-holder for the spec which is to be written for script-only-stacks.

The remit of script-only-stacks is to be able to create a stack in a special mode where its content can be entirely serialized as a text-file. The use-case is for (mostly?) pure script bearing stacks. The textfile format must be readable by a human and easily editable in a text editor. It should be resilient as far as possible to merge conflicts when used correctly by the developer.

We have an initial implementation which exists in 6.7 onwards for script only stacks and it shown to be really quite useful for a number of projects so far.

However, it has a number of deficiencies which need some thought to resolve - hence a new spec.

Things to consider:
- you can't use script-onlys in server (as they conflict with PHP-style interpolated scripts)
- they only store the stack script
- all non-script data is lost even though some things (like simple string-like custom properties) could be preserved

Please comment below if there is anything else you think should be taken into consideration in an updated version of 'script only stacks', or if you have any ideas about them that might be useful.

### CODE REVIEW

**Comment by peter-b** [comment]
[Bug 14133 - Running server with a script-only stack echoes the program](http://quality.runrev.com/show_bug.cgi?id=14133)

**Comment by livecodestephen** [comment]
Can I point out the problem with line numbers in [Bug 14637](http://quality.runrev.com/show_bug.cgi?id=14637).  This is primarily an IDE problem but might also impact the engine.

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevmark, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by peter-b** [comment]
@runrevmark We're unlikely to iterate on this in the foreseeable future, so I'll close this PR for now.

**Pull request closed without merging**
