### PR TITLE
[[ Bug 13213 ]] Take in consideration the case in the name of the Androi...

### PR DESCRIPTION
**Pull request by livecodesebastien**
...d libs

### CODE REVIEW

**Comment by runrevmark** [comment]
Another option here is to actually interrogate the target path for the list of files within it... Then use caseless lineOffset to get the true name.

If there is an ambiguity it would be fine to throw an error in this case since that would have been caused by us - i.e. a programmatic issue with building / naming (indeed, since we build everything on caseless filesystems it shouldn't be possible to have an ambiguity).

**Comment by peter-b** [comment]
I like @runrevmark's solution best. :+1:

**Comment by livecodesebastien** [comment]
Just updated to follow your idea Mark

**Comment by runrevmark** [comment]
Looks good @runrevsebastien - thanks!

**Comment by peter-b** [comment]
Yes, that's very neat @runrevsebastien, thanks. :+1:

**Pull request merged**
