### PR TITLE
[[ Bug 17131 ]] Don't draw selection handles of invisible objects

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali Do you think there should be a method on objects that returns true iff the object is actually able to be drawn?  Something like `IsReallyVisible()` or something...?

@livecode-vulcan review ok 84287d0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 84287d01c1f43def68c9cbf74488fbeb5418dd51

**Comment by livecodeali** [comment]
@peter-b Yeah, makes sense.

**Comment by livecodeali** [comment]
@peter-b In fact I wonder if the `showinvisible()` stuff should really be in `MCObject::isvisible`.

**Comment by peter-b** [comment]
@livecodeali That would be pretty neat if it's feasible without breaking other stuff that depends on the current interpretation of `isvisible() == true`.

**Comment by livecodeali** [comment]
@peter-b What I meant was it might be a bug that it isn't currently in there

**Comment by livecodeali** [comment]
Ok, looking at it, I think there should be a separate `isreallyvisible` but some of the uses of `isvisible` should be changed.

**Comment by livecode-vulcan** [comment]
😎 test success 84287d01c1f43def68c9cbf74488fbeb5418dd51
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2212)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2219)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2205)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2221)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2226)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2232)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2243)

**Pull request merged**
