### PR TITLE
[[ Bug ]] Make sure errno is reset before using strto* functions in M…

### PR DESCRIPTION
**Pull request by runrevmark**
…CNumberParse and friends.

### CODE REVIEW

**Comment by runrevmark** [comment]
This is the 7.0 version of #2380 - it will cause merge conflicts when merged forward as the number functions have changed.

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok 274f596

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 274f5960b3d71861badb9647667a9455ff3b2eda

**Comment by livecode-vulcan** [comment]
😞 test failure 274f5960b3d71861badb9647667a9455ff3b2eda
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/156)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/220)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/109)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/166)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/102)
- try-mac: unknown

**Pull request merged**
