### PR TITLE
[emscripten] Standardise on "the platform" as "HTML5"

### PR DESCRIPTION
**Pull request by peter-b**
Having `the platform` evaluate to "HTML" was just confusing and violated the rule of least surprise for people developing for HTML5 deployment.

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay af09b28

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok af09b28378c15d374f66a666344d41dcb9b385f9

**Comment by livecode-vulcan** [comment]
💥 merge conflict af09b28378c15d374f66a666344d41dcb9b385f9 → 959e99b48ab5583cb9d9c7b02e9a62a01619d161

**Comment by peter-b** [comment]
@livecodefraser Pull request updated, fixing a minor documentation oversight and merge conflicts.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay aa9ce00

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok aa9ce006ac9fd24255182f0cf65f86e61d20d435

**Comment by livecode-vulcan** [comment]
😎 test success aa9ce006ac9fd24255182f0cf65f86e61d20d435
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1471)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1491)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1467)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1478)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1490)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1491)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1493)

**Pull request merged**
