### PR TITLE
[[ Standalone Builder ]] Refactor save as standalone script

### PR DESCRIPTION
**Pull request by livecodeali**
This patch goes some way towards having a single handler which encapsulates building for a given platform. It should be possible to wrap these with a script-only stack which can function as a command line tool for standalone building.

This builds on https://github.com/livecode/livecode/pull/4079, but is a separate pull request to avoid having a scary quantity of code changes to review in a single PR.

---

This change is [Reviewable](https://reviewable.io/reviews/livecode/livecode/4101)

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali This looks fine, although it would be nice to avoid adding any more static state variables if possible.

@livecode-vulcan review ok 9daec18

<details><summary>

<i>Previously, livecodeali (Ali Lloyd) wrote…</i></summary>



> #### [[ Standalone Builder ]] Refactor save as standalone script
> 
> This patch goes some way towards having a single handler which encapsulates building for a given platform. It should be possible to wrap these with a script-only stack which can function as a command line tool for standalone building.
> 
> This builds on https://github.com/livecode/livecode/pull/4079, but is a separate pull request to avoid having a scary quantity of code changes to review in a single PR.
> 
> </details>

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[ide-support/revsaveasstandalone.livecodescript, line 458 [r2]](https://reviewable.io:443/reviews/livecode/livecode/4101#-KJjO5ZFh7yly1D8tx1c:-KJjMuNT-QWwAjHvBagP:985684843) ([raw file](https://github.com/livecode/livecode/blob/9daec182585653eae33e8c41433b527ced13bf56/ide-support/revsaveasstandalone.livecodescript#L458)):_

> ```
>       put true into sSearchedForInclusions
>    end if
> end revSearchForInclusions
> ```

As discussed, is there any reasonable alternative to using this static variable?

---

_[ide-support/revsaveasstandalone.livecodescript, line 481 [r2]](https://reviewable.io:443/reviews/livecode/livecode/4101#-KJjOM3_M4CFjrgHIglN:-KJjOM3_M4CFjrgHIglO:2127791372) ([raw file](https://github.com/livecode/livecode/blob/9daec182585653eae33e8c41433b527ced13bf56/ide-support/revsaveasstandalone.livecodescript#L481)):_

> ```
>    set the itemdelimiter to slash
>    put item -1 of the effective filename of stack tStackFileName into tStackName
>    if not (tStackName ends with ".livecode" or tStackName ends with ".rev") then 
> ```

Is there a "does this filename have a 'normal' stack filename suffix?" function in the IDE library somewhere?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4101#-:-KJjQB4yH4yKaGukZ021:666832708)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9daec182585653eae33e8c41433b527ced13bf56

**Comment by livecode-vulcan** [comment]
😎 test success 9daec182585653eae33e8c41433b527ced13bf56
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2610)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2620)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2605)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2621)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2627)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2633)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2645)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1dd2d5a

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1dd2d5a80ba1ee8fcc3cd9f1c6ba41f7adb9cd9b

**Comment by livecode-vulcan** [comment]
😎 test success 1dd2d5a80ba1ee8fcc3cd9f1c6ba41f7adb9cd9b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2612)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2622)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2607)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2623)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2629)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2635)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2647)

**Pull request merged**
