### PR TITLE
[[ Docs ]] Put all docs of a particular type together in API

### PR DESCRIPTION
**Pull request by livecodeali**
Put all lcs syntax into an lcs folder for inclusion in an LCS
API, and similarly for LCB and IDE docs.

### CODE REVIEW

**Comment by livecodeali** [comment]
'Need-tests' in the sense that this needs to be tested in a full release build before merging.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok fa1360a

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok fa1360a287b504b7a0c4b87c11f914ff07416b5d

**Comment by livecode-vulcan** [comment]
😎 test success fa1360a287b504b7a0c4b87c11f914ff07416b5d

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/886)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/902)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/876)
* try-community-universal-ios-iphoneos11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.0/builds/51)
* try-community-universal-ios-iphonesimulator11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.0/builds/52)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/880)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/902)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/886)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/902)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/885)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/895)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/917)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/881)

**Pull request merged**
