### PR TITLE
[[ Bug 16094 ]] Remove opacity setting from drop shadow props array

### PR DESCRIPTION
**Pull request by techstrategies**
It is specified by the alpha component of the color.

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 53d1cea

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 53d1cea1ceae0eb06cfd00143ef86e660ce11b6c

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 0b24ce4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 0b24ce4d7b6c81bd52047175768f930883852a9b

**Comment by livecode-vulcan** [comment]
😎 test success 0b24ce4d7b6c81bd52047175768f930883852a9b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/597)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/609)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/598)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/599)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/608)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/619)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/610)

**Pull request merged**
