### PR TITLE
[[ Bugfix ]] Fix a crash in server when an assertion fails outside a …

### PR DESCRIPTION
**Pull request by livecodestephen**
…handler

### CODE REVIEW

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok 286b94b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 286b94b1ecad5be3ce3762543bb191520a57d37b

**Comment by livecode-vulcan** [comment]
😞 test failure 286b94b1ecad5be3ce3762543bb191520a57d37b
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/127)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/192)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/80)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/137)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/73)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/78)

**Comment by peter-b** [comment]
@livecode-vulcan try 286b94b

**Comment by livecode-vulcan** [comment]
😞 test failure 286b94b1ecad5be3ce3762543bb191520a57d37b
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/130)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/195)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/83)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/140)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/76)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/80)

**Pull request merged**
