### PR TITLE
[[ Bug 19197 ]] Allow script-only stacks in deploy params

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Tests: https://github.com/livecode/livecode-ide/pull/1546

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 516d698

@livecodeali it would be nice to add a way to add a stack to auxiliary stacks in standalone settings [one day](http://quality.livecode.com/show_bug.cgi?id=19255)

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 516d698f4ea339ae019240e46d336e979ec5bfde

**Comment by livecode-vulcan** [comment]
😞 test failure 516d698f4ea339ae019240e46d336e979ec5bfde

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/944)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/950)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/942)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/943)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/950)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/945)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/941)

**Comment by peter-b** [comment]
@livecode-vulcan retry 516d698

**Comment by livecode-vulcan** [comment]
😞 test failure 516d698f4ea339ae019240e46d336e979ec5bfde

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/956)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/962)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/954)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/955)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/962)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/971)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/953)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 516d698

**Comment by livecode-vulcan** [comment]
😎 test success 516d698f4ea339ae019240e46d336e979ec5bfde

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/963)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/969)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/961)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/962)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/969)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/978)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/960)

**Pull request merged**
