### PR TITLE
[[libsystem]] Add new "system foundation" library

### PR DESCRIPTION
**Pull request by peter-b**
As the LCB standard library grows, there's an increasing amount of library code that's been introduced (mostly by me) to provide a consistent wrapper for low-level platform APIs (for example, reading and writing files).

This has mostly been stuffed into `libfoundation`. However, `libfoundation` really was supposed to be a type library rather than a system services library.  @runrevmark and I discussed this recently and determined that it would be better to separate out the system services code into a separate library eventually, but that for the time being we should introduce a "sublibrary" of `libfoundation`.

This changeset introduces a new `<foundation-system.h>` header, which defines a large number of C API functions using the `MCS` prefix.  So far, these include:
- `MCSFile`: file and filesystem operations
- `MCSStream`: C stdio-compatible streams based on `MCStream`
- `MCSRandom`: Random number generation
- `MCSCommandLine`: Command-line argument handling

This pull request includes & supersedes #1687 and #1679.
## Notes
1. Rather than having separate "public" and "private" headers, each of the public `system-foo.h` headers includes private definitions guarded by an `#ifdef __MCS_INTERNAL_API__` macro. The `system-private.h` header just defines `__MCS_INTERNAL_API__` and then `#include`s the public headers.
2. Instead of putting header guards in each of the `system-foo.h` headers, there's only a header guard on the main `libfoundation-system.h` header.  The `system-foo.h` headers cause a preprocessing error if they're not being included via the main header.
3. All of the system foundation library public API is exported with C linkage.

### CODE REVIEW

**Comment by runrevmark** [comment]
One way to avoid the potential ambiguity with syntax is to choose different syntax :)

How about 'the command line' returns the actual command-line that was used to invoke the application (with suitable platform-uniformisation munging) [ as a string ].

Then 'the command arguments' are a list of the arguments, and perhaps 'the command executable' for the absolute path to the executable.

**Comment by livecodestephen** [comment]
Do your lists start at index 0 or 1?  If your indices start at 1 then there is no equivalent of `argv[0]` so you'd need different syntax anyway.

**Comment by peter-b** [comment]
Thanks for the feedback. :-)

@runrevmark: The main reason I'm keen to have "C-like" command line arguments available is for proofing against future "LiveCode as general-purpose programming language" applications. I do agree that there is scope for splitting out the `argv[0]` and `argv[n]` elements!

I think `the command arguments` could work well. In fact, what about just using `the arguments`?

One of the reasons that `argv[0]` is so difficult to pin down is that its interpretation as the filename of the running executable is only by convention.
- Some language implementations, e.g. Python and Guile Scheme, pass the script filename as argv[0], whereas others pass the name that the interpreter was invoked as
- If you look at the POSIX system call `execve(2)`, you can actually specify _whatever you like_ as `argv[0]` when creating a subprocess -- no relationship whatsoever with the `filename` argument is required!

So clearly `argv[0]` and (notionally) `the executable file` are distinct things, and I have no idea what to call the former (although I think it's useful to be able to get at it).

Worse: what exactly should `the executable file` return? Should it be the same as `$0` in current script (which does slightly different things depending on which platform you're on)?

@runrevstephen: Most people read `argv[0]` as "the first element of the argument list". With 1-based indices, then `element 1 of the command line` is still the same. I don't think we can wriggle out of the problem that easily. ;-)

**Comment by peter-b** [comment]
Further discussions with @runrevmark:
1. `the command name` will be `argv[0]`, or equivalent.
2. `the command arguments` will be the remaining arguments after the runtime wrapper has consumed any that it doesn't want to pass to LCB.
3. `the command filename` is the canonical filename of the executable.

Examples:

| Description | Command Line | Name | Arguments | Executable |
| --- | --- | --- | --- | --- |
| Running LCB file with `lc-run` tool. | `lc-run foo.lcm bar baz` | `"foo.lcm"` | `["bar", "baz"]` | `/path/to/foo.lcm`. |
| Natively-compiled LCB file | `foo.lcm.native bar baz` | `"foo.lcm.native"` | `["bar", "baz"]` | `/path/to/foo.lcm.native`. |
| The IDE | `LiveCode-Community bar baz` | `"LiveCode-Community"` | `[]` | `/path/to/LiveCode-Community` |
| Standalone | `MyStandalone bar baz` | `"MyStandalone"` | `["bar", "baz"]` | `/path/to/MyStandalone` |

**Comment by peter-b** [comment]
I've updated the patches based on your feedback. At the moment only "the command name" and "the command arguments" are implemented; "the command filename" should follow at some point but it wasn't as high a priority as "the command arguments".

I've hooked up both "the command name" and "the command arguments" for engine-based programs.

**Comment by livecodefraser** [comment]
Will need some post-merge cleanup for Visual Studio and Xcode project files and the Android makefiles.

**Pull request merged**
