### PR TITLE
[[ Bug 20953 ]] Fix specialfolderpath of engine on windows

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
I did it like this because `MCcmd` is computed at startup using exactly the method that was being used here (i.e. getting native path to library) - so this way round removes duplication of effort.

**Comment by livecodeali** [comment]
However, I have just realised that this was getting the eventual delimiter wrong - it seems GetStandardFolder *is* native on return, and then in gets generally denativized by `MCS_specialfolderpath`

**Comment by montegoulding** [comment]
@livecode-vulcan review ok af240ce

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok af240ce2e0258d4d72c6c2f0cb7d4eb30326101b

**Comment by livecode-vulcan** [comment]
😎 test success af240ce2e0258d4d72c6c2f0cb7d4eb30326101b

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1206)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1222)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1196)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/149)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/149)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1201)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1227)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1206)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1222)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1205)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1215)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1255)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1200)

**Pull request merged**
