### PR TITLE
[[ Builder ]] Adjust the builder stack width, to see the OSX checkbox

### PR DESCRIPTION
**Pull request by livecodesebastien**
[[ AndroidBuild ]] Update tools/build-android.osx to allow the use of the Android Tool after Revision 20

### CODE REVIEW

**Comment by runrevmark** [comment]
This contains changes to the android build script too - was that intended?

**Comment by livecodesebastien** [comment]
Yes - the commit message is two-line long, I should certainly have made two commits instead

**Comment by livecodesebastien** [comment]
Change to the Android build script reverted.

**Comment by livecodesebastien** [comment]
Superseded by livecode/builder_fixes branch.

**Pull request closed without merging**
