### PR TITLE
[[ Cleanup ]] Remove non-gyp build related files.

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 8cf6f54

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 8cf6f54f0b09b0ac68417fb0a943674cb830dace

**Comment by livecode-vulcan** [comment]
😎 test success 8cf6f54f0b09b0ac68417fb0a943674cb830dace
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/695)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/755)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/645)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/709)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/640)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/632)

**Comment by peter-b** [comment]
@livecode-vulcan retry 8cf6f54

**Comment by peter-b** [comment]
@livecode-vulcan retry 8cf6f54

**Comment by peter-b** [comment]
@livecode-vulcan retry 8cf6f54

**Comment by livecode-vulcan** [comment]
😎 test success 8cf6f54f0b09b0ac68417fb0a943674cb830dace
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1)

**Pull request merged**
