### PR TITLE
[[ Bug 19478 ]] Add 'filemaker' as valid deploy target

### PR DESCRIPTION
**Pull request by runrevmark**
This patch adds 'filemaker' as a valid deploy target present in
a LiveCode license.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok eaa7fad

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok eaa7fad5b07d23d508485541efa4ea36a2848201

**Comment by runrevmark** [comment]
Re-reviewing as I accidentally overwrote the original commit with force push!

@livecode-vulcan review ok 9cc2593

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9cc2593cf05a9640838beff22c8a1a2ec6d87a30

**Comment by livecode-vulcan** [comment]
😎 test success 9cc2593cf05a9640838beff22c8a1a2ec6d87a30

* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/9)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/9)
* try-community-js-emscripten: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten/builds/16)
* try-community-universal-ios-iphoneos10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.2/builds/14)
* try-community-universal-ios-iphonesimulator10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.2/builds/14)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/8)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/10)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/12)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/14)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/12)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/14)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/14)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/13)

**Pull request merged**
