### PR TITLE
Feature treeview resizable view

### PR DESCRIPTION
**Pull request by livecodeali**
Based on https://github.com/livecode/livecode/pull/2843

This adds an optional movable separator to the tree view with the keys one side and the values the other.
There are new properties `showSeparator` and `separatorRatio` to control the visibility and position of the separator.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 946a6d3

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 946a6d325c6d71a4d4b16d5c66347d6022624ce1

**Comment by livecodeali** [comment]
Haha, yes - this went through several small increments of doing things a bit more properly than before

**Comment by livecode-vulcan** [comment]
😎 test success 946a6d325c6d71a4d4b16d5c66347d6022624ce1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/473)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/476)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/472)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/472)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/480)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/473)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/482)

**Pull request merged**
