### PR TITLE
[[ Bug 16308 ]] Ensure that RTF styles with fldinst are always in sync

### PR DESCRIPTION
**Pull request by livecodesebastien**
(cherry picked from commit 087c04d0af428ae08b200127e6c00b04bb20dee5)

Add tests for checking that RTF export works as it should

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodesebastien Should there be a release note in this PR?

**Comment by livecodesebastien** [comment]
Yes, there should be. And there now is!

**Comment by peter-b** [comment]
@livecode-vulcan review ok 9f05b15

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9f05b15edd66dc83a220e3d74dc97ac5f8a77315

**Comment by livecode-vulcan** [comment]
😎 test success 9f05b15edd66dc83a220e3d74dc97ac5f8a77315
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1207)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1219)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1204)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1212)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1223)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1224)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1227)

**Pull request merged**
