### PR TITLE
[Bug 16076][emscripten] Generate Emterpreter whitelist more cleverly

### PR DESCRIPTION
**Pull request by peter-b**
Apply two sets of regular expressions to the symbols in the engine:
- Only symbols that match a whitelist expression are compiled with
  Emterpreter
- No symbol that matches a blacklist expression is compiled with
  Emterpreter

The set of regular expressions provided in this patch seems to cover
most possible ways that the engine could end up waiting, but it's not
guaranteed to be exhaustive.  Just compiling everything in the core
engine to Emtepreter bytecode made the engine very large and very
slow, so a more selective approach was required.

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 7e57b9b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 7e57b9be6ca98ea14bbd46bc3748a93f321ec48f

**Comment by livecode-vulcan** [comment]
😞 test failure 7e57b9be6ca98ea14bbd46bc3748a93f321ec48f
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1418)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1438)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1414)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1424)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1435)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1434)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1439)

**Comment by peter-b** [comment]
@livecode-vulcan retry 7e57b9b

**Comment by livecode-vulcan** [comment]
😎 test success 7e57b9be6ca98ea14bbd46bc3748a93f321ec48f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1420)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1440)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1416)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1426)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1437)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1436)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1441)

**Pull request merged**
