### PR TITLE
[[Community Docs]] Clarify difference between opaque vs transparent o…

### PR DESCRIPTION
**Pull request by Brahmanathaswami**
…bjects

Add two lines to the description to note the difference of how the shadow is applied when an object is opaque versus how it is applied if the object is transparent.

### CODE REVIEW

**Comment by seaniepie** [comment]
There are some other quite heavy changes that need doing to the Syntax and Parameters of this entry. I will leave its till after @Brahmanathaswami changes have been merged.

**Comment by montegoulding** [comment]
@seaniepie you should be fine unless you need to change the line above or below @Brahmanathaswami 's addition.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 460cb22

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 460cb223c931978891de51c84651a259bb34f82b

**Comment by livecode-vulcan** [comment]
😎 test success 460cb223c931978891de51c84651a259bb34f82b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/450)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/455)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/450)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/450)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/456)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/450)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/450)

**Pull request merged**
