### PR TITLE
[[ Array Set Ops ]] Fix semantics of intersect and union

### PR DESCRIPTION
**Pull request by livecodeali**
This patch amends the array set operations so that they match those in 6.7 exactly.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodeali: How do the current 7.0 semantics compare with 6.7? If this is a change from 6.7 then we should probably put it into 8.0 only.

**Comment by livecodeali** [comment]
@runrevmark The changes to the 6.7 behavior are in the comment - it affects

```
intersect tLeftString with tRightString
intersect tLeftString with tRightArray
```

I guess what I should do then is tweak this PR so to make the behavior identical to 6.7 in 7.1, and re-target this back at develop.

**Comment by runrevmark** [comment]
@livecodeali: That would be ideal :)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok f07bbd0

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok f07bbd00b392f9ee6eda918af5ac62a3fb0c092e

**Comment by livecode-vulcan** [comment]
😎 test success f07bbd00b392f9ee6eda918af5ac62a3fb0c092e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1199)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1210)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1196)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1203)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1214)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1216)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1218)

**Pull request merged**
