### PR TITLE
[[ SOSBehavior ]] Do deferred behavior resolution in installer mode startup

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 432f5bd

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 432f5bd8e6d4bf6a794c6b0b63709d714d431312

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 432f5bd

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 432f5bd

**Comment by livecodeali** [comment]
@livecode-vulcan retry 432f5bd

**Pull request merged**
