### PR TITLE
[Bug 15549] MCParagraph::fmovefocus(): Allow any field translation.

### PR DESCRIPTION
**Pull request by peter-b**
Regression introduced in commit 0280749eb6bb.

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 0a1a2bc

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 0a1a2bc27d1e800954c811ede77a44ad3b58b058

**Comment by livecode-vulcan** [comment]
😎 test success 0a1a2bc27d1e800954c811ede77a44ad3b58b058
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/298)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/360)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/242)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/309)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/244)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/234)

**Comment by livecodeali** [comment]
I think this needs to be
    default:
        break;

because all the other field translations should just continue to the next switch.

**Comment by runrevmark** [comment]
Yes - Ali is right - that initial switch is just twiddling the operation based on writing direction.

**Comment by peter-b** [comment]
Sure, will fix ASAP. :+1:

**Comment by livecodeali** [comment]
I should note for the record that I was the original reviewer :hand:

**Comment by peter-b** [comment]
@livecodeali @runrevmark Is that more like it?

**Comment by runrevmark** [comment]
@livecodeali: I looked at the code too and didn't notice any problems - you just got to reviewing it first. Hindsight is a wonderful thing ;)

@peter-b: Difficult to tell - there seem to be a lot of whitespace changes ;)

**Comment by peter-b** [comment]
Argh, editor being overly enthusiastically helpful!

**Comment by peter-b** [comment]
@runrevmark Okay, that's cleaned up.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok b2afe8c

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok b2afe8cdd6e86a9b349433db0d0ef1ee859bc9ae

**Comment by livecode-vulcan** [comment]
😎 test success b2afe8cdd6e86a9b349433db0d0ef1ee859bc9ae
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/299)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/361)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/243)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/310)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/245)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/235)

**Pull request merged**
