### PR TITLE
[[ Bug 18484 ]] Prevent overrelease of object handle

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 4be1037

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 4be1037963fa637bb774f915827604b9192a1459

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 5167ce6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 5167ce64ffbe7d8c23490e51c7463af739d9070e

**Comment by livecode-vulcan** [comment]
😎 test success 5167ce64ffbe7d8c23490e51c7463af739d9070e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/601)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/606)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/601)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/605)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/610)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/602)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/602)

**Pull request merged**
