### PR TITLE
Update all of our pre-built libraries

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by livecodefraser** [comment]
New versions of libICU will need to be built for iOS 8.3 and 8.4 too

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok  505b0fc

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 505b0fc4f49697292761ddf34da8067ded7cf8ce

**Comment by livecode-vulcan** [comment]
😞 test failure 505b0fc4f49697292761ddf34da8067ded7cf8ce
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/352)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/415)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/297)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/363)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/298)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/289)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 505b0fc

Re-trying with re-build Android libraries

**Comment by livecode-vulcan** [comment]
😞 test failure 505b0fc4f49697292761ddf34da8067ded7cf8ce
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/353)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/416)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/298)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/364)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/299)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/290)

**Comment by livecodefraser** [comment]
ICU -> 55.1
Curl -> 7.43.0
OpenSSL -> 1.0.1o

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok  23b1302

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 23b1302a240266957aef77d0bfea6ba0e7023c96

**Comment by livecode-vulcan** [comment]
😞 test failure 23b1302a240266957aef77d0bfea6ba0e7023c96
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/371)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/434)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/316)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/382)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/317)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/308)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 23b1302

**Comment by livecode-vulcan** [comment]
😞 test failure 23b1302a240266957aef77d0bfea6ba0e7023c96
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/373)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/436)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/319)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/384)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/319)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/310)

**Comment by peter-b** [comment]
I think this may be failing because @livecode-vulcan is trying to compile with the iOS 8.4 SDK but the branch doesn't know how...

**Comment by livecodesebastien** [comment]
yes - if Windows builds properly, I'll simply merge it in anyway.

**Comment by peter-b** [comment]
I think you might be able to merge this branch and the corresponding Xcode 6.4 branch together into a new branch, then test that?

**Comment by livecodesebastien** [comment]
That's very right - and very safe.

**Comment by livecodesebastien** [comment]
That commit was present in the PR https://github.com/runrev/livecode/pull/2532, so we still need to merge this one.
@livecode-vulcan review ok  4c69991

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 4c699914d1bdbb16174b5cb0268abcefa044de72

**Comment by livecode-vulcan** [comment]
😎 test success 4c699914d1bdbb16174b5cb0268abcefa044de72
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/406)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/468)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/352)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/417)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/352)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/343)

**Pull request merged**
