### PR TITLE
[[ Bug 17891 ]] Reset the m_was_licensed instance variable to true before calls to an external's handler

### PR DESCRIPTION
**Pull request by techstrategies**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 6c3848a

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 6c3848a6ea65dc133caa202791214d77fa8c2c9f

**Comment by livecode-vulcan** [comment]
😞 test failure 6c3848a6ea65dc133caa202791214d77fa8c2c9f
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2673)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2683)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2668)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2684)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2690)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2696)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2708)

**Comment by montegoulding** [comment]
@livecode-vulcan retry 6c3848a

**Comment by livecode-vulcan** [comment]
😎 test success 6c3848a6ea65dc133caa202791214d77fa8c2c9f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2674)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2684)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2669)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2685)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2691)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2697)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2709)

**Pull request merged**
