### PR TITLE
[[ AndroidAAR ]] Add support for AAR files as extension dependencies

### PR DESCRIPTION
**Pull request by livecodeali**
This PR enables extensions to include android AARs on which they depend. The aars must be included in the extension's code/jvm-android folder. Currently, the supported AAR contents are:
  - Jar files
  - Resources
  - Manifests

In particular, native code contained in AARs is not yet supported.

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecodeali this looks good to me. Where's a good place to document this? Also I think you might want to be explicit that it supports classes.jar but no other jars that may be in the aar (I'm pretty sure there can be a folder of them).

**Comment by livecodeali** [comment]
@montegoulding I think our 'Extending LiveCode' guide is probably the best place - it needs a good update anyway. A lesson would also probably be a good idea.

**Comment by montegoulding** [comment]
@livecodeali given the changes for code resources perhaps we should do a separate PR for docs?

**Comment by livecodeali** [comment]
@montegoulding I think that makes sense

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 6b787c0

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 6b787c0c9d7aefa618d391ec8bc6c7c53deb155f

**Comment by livecode-vulcan** [comment]
😎 test success 6b787c0c9d7aefa618d391ec8bc6c7c53deb155f

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1024)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1040)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1014)
* try-community-universal-ios-iphoneos11.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.1/builds/87)
* try-community-universal-ios-iphonesimulator11.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.1/builds/87)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1019)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1041)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1024)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1040)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1023)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1033)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1056)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1019)

**Pull request merged**
