### PR TITLE
[[ Bug 15648 ]] Fix the brace direction when starting a new paragraph…

### PR DESCRIPTION
**Pull request by livecodesebastien**
… with a specific bacgroundcolor on RTF export

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 3b80b56

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 3b80b5647ee427ca5f6be6409aef40c259b264f6

**Comment by livecode-vulcan** [comment]
😞 test failure 3b80b5647ee427ca5f6be6409aef40c259b264f6
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/710)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/770)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/660)
- try-android-armv6: [pending](https://vulcan.livecode.com/builders/try-android-armv6/builds/724)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/655)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/647)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 3b80b56

**Comment by livecode-vulcan** [comment]
😎 test success 3b80b5647ee427ca5f6be6409aef40c259b264f6
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/713)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/773)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/663)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/727)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/658)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/650)

**Pull request merged**
