### PR TITLE
Fix typo in dictionary entry for codepoint

### PR DESCRIPTION
**Pull request by livecodestephen**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 7c8d0f8

**Comment by peter-b** [comment]
@livecode-vulcan review ok 5063697

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 5063697710baf481ebe73d6bf6568c67d4307470

**Comment by livecode-vulcan** [comment]
😎 test success 5063697710baf481ebe73d6bf6568c67d4307470
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/284)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/347)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/230)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/295)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/230)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/222)

**Pull request merged**
