### PR TITLE
[[ Bug 11803 ]] Implement MCAndroidSystem::TextEncodeToUnicode, which…

### PR DESCRIPTION
**Pull request by livecodesebastien**
… is used by RTFReader

WIP now as it needs to be tested on Windows and Linux, and with different charsets.

### CODE REVIEW

**Comment by peter-b** [comment]
Please set an error or at least emit a debug message when `MCTextEncodingEnumToAndroidSystemEncodingEnum()` fails!

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay af6e46a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok af6e46a3249e985fed2bb07d9046b02416f710ae

**Comment by livecode-vulcan** [comment]
😞 test failure af6e46a3249e985fed2bb07d9046b02416f710ae
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/381)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/444)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/327)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/392)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/327)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/318)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry af6e46a

**Comment by livecode-vulcan** [comment]
😎 test success af6e46a3249e985fed2bb07d9046b02416f710ae
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/385)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/448)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/331)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/396)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/331)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/322)

**Pull request merged**
