### PR TITLE
Avoid an infinite loop with trace exceptions

### PR DESCRIPTION
**Pull request by ricochet1k**
I hit this infinite loop while trying to debug GLX2.

### CODE REVIEW

**Comment by ricochet1k** [comment]
There are apparently a few more places where that while(...) MCB_error(); concept is used, and they all need to be modified in the same way. I'll look for all the others at some point.

**Comment by runrevmark** [comment]
Hi Matt,

Sorry for the delay in getting to this - the conference kind of got in the way of our usual processes!

Anyway, this looks like a reasonable fix to the problem so I'll pull it into 'develop' in due course so we can see whether it has any unintended consequences.

By the way, I must confess I forgot to check whether you had signed the contributers agreement before I pulled in your last submissions. I couldn't find record of this in our system against your ricochet1k email address. I'd be grateful if you could visit our signup page for this and 'sign' the agreement for our records:

http://livecode.com/store/account/contributor-agreement-signup/

Note signing is tied to your livecode.com customer (store) account - if this uses a different email address to the one you use for github, let me know so I can verify.

Thanks in advance,

Warmest Regards,

Mark.

**Comment by ricochet1k** [comment]
Sorry, I kinda forgot about this. I have signed the contributor agreement now.

**Comment by ricochet1k** [comment]
This should fix all the places where MCB_error was used in a loop that could hang.

**Comment by runrevmark** [comment]
Hi, thanks for this - I've merged it into 'develop' for 6.6.

Warmest Regards,

Mark.

**Pull request closed without merging**
