### PR TITLE
Bugfix player colors

### PR DESCRIPTION
**Pull request by livecodepanos**
This pull request replaces https://github.com/runrev/livecode/pull/1175

### CODE REVIEW

**Comment by livecodepanos** [comment]
This pull request comes together with https://github.com/runrev/livecode-ide/pull/214

**Comment by livecodeali** [comment]
I think if you revert the IDE submodule pointer commit here, this is fine to merge. You'll have to just update it manually after merging https://github.com/runrev/livecode-ide/pull/214

**Comment by livecodeali** [comment]
@livecode-vulcan review ok c289cce

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok c289ccea88e344f9c316ee4a5d2e18f945c5c02b

**Comment by livecode-vulcan** [comment]
😞 test failure c289ccea88e344f9c316ee4a5d2e18f945c5c02b
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/155)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/219)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/108)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/165)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/101)
- try-mac: unknown

**Pull request merged**
