### PR TITLE
[[ Tests ]] Output not ok results to stdout

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
@peter-b thoughts on this? It's handy to see exactly what failed in the travis log

**Comment by peter-b** [comment]
@montegoulding It's been on my list for a while.  My main thought was that maybe there should be a helper function in the [TesterLib](https://github.com/livecode/livecode/blob/develop/tests/_testerlib.livecodescript) stack for getting the "failures log".  This is for two reasons:
1. Other test runners (e.g. the compiler test runner) should probably also output this info and it would be good to avoid code duplication.
2. Listing the failures is more complicated than listing `not ok` lines.  For example, if you have `1..3` at the start of your TAP output but you only emit two `ok` lines, the TAP log analysis should show the test as **failed** (because the tests didn't run to completion) and output listing failures should reflect this.  Actually I think that, to my shame, `TesterTapAnalyse()` doesn't actually check this properly -- but if in the future we fix that, we could fix a "failures log" function at the same time.

**Comment by montegoulding** [comment]
@peter-b OK I will look at moving it into TesterLib. For now I'm using it to work out which grapheme test I've broken because it's passing locally.

**Comment by montegoulding** [comment]
@peter-b thinking about the lack of an `ok` line probably meaning there was an unexpected execution error or something. Perhaps we need some way to register a test with a description then do stuff involved in the test then assert the value so that in the event of a failure or another test being registered we know there's an issue and we know which test caused it:

```
TestRegister <hopefully useful description>
... do stuff that could break
TestAssert <bool>
```

That would allow the tester to always pump out a `not ok` line

**Comment by peter-b** [comment]
@montegoulding (1) Use `TestPlan` to state how many test you expect to do before the next `TestPlan`, (2) upgrade `TesterTapAnalyse` to process `1..n` lines. Simple!

**Comment by montegoulding** [comment]
@peter-b that wouldn't give us a description of the failed test though would it

**Comment by montegoulding** [comment]
@peter-b I'm looking at just adding a "failures" element to the array returned by `TesterTapAnalyse` then having `logSummaryLine` output the current summary line followed by the failures if any.

**Comment by montegoulding** [comment]
Like that ^

**Comment by peter-b** [comment]
@montegoulding Please resolve conflicts in this PR.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok da9f1f3

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok da9f1f31bb869001ae0f00fe792543071a3b3105

**Comment by livecode-vulcan** [comment]
😎 test success da9f1f31bb869001ae0f00fe792543071a3b3105
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/488)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/493)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/488)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/488)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/494)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/488)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/488)

**Comment by montegoulding** [comment]
just a slight little tweak so we don't get unnecessary newlines in our test output

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 202d19a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 202d19a7925ca4508365a8a5d3f368d9435af9f1

**Comment by livecode-vulcan** [comment]
😎 test success 202d19a7925ca4508365a8a5d3f368d9435af9f1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/490)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/495)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/490)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/490)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/496)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/490)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/490)

**Pull request merged**
