### PR TITLE
The zip package is required to build on linux

### PR DESCRIPTION
**Pull request by livecodestephen**
Just doing a build on a fresh Debian Wheezy VM and I had to install the zip package.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4711625

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4711625ddcb48d04528a3768c2f67dec173d94c1

**Comment by livecode-vulcan** [comment]
😞 test failure 4711625ddcb48d04528a3768c2f67dec173d94c1
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/396)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/396)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/395)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/394)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/400)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/391)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/402)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 4711625

**Comment by livecode-vulcan** [comment]
😎 test success 4711625ddcb48d04528a3768c2f67dec173d94c1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/399)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/399)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/398)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/397)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/403)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/394)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/405)

**Pull request merged**
