### PR TITLE
Update tan.lcdoc

### PR DESCRIPTION
**Pull request by LiveCodeSteven**
As per bug report - http://quality.runrev.com/show_bug.cgi?id=14837 I have resolved the function error on line 40

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @LiveCodeSteven, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecode-vulcan** [comment]
📝 Hi @LiveCodeSteven, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecode-vulcan** [comment]
📝 Hi @LiveCodeSteven, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 0c19286

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 0c19286af2f8e8dadc4919deda88c86b39083b40

**Comment by livecode-vulcan** [comment]
😎 test success 0c19286af2f8e8dadc4919deda88c86b39083b40
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/320)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/320)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/319)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/318)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/323)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/315)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/326)

**Pull request merged**
