### PR TITLE
[[ CleanupMCColor ]] Remove obsolete fields and revise color <-> pixel transform

### PR DESCRIPTION
**Pull request by livecodeian**
This removes the following fields from MCColor:
1: pad - unused.
2: flags - only relevant to Windows color picker dialog, and easily replaced
3: pixel - only used for translation between red, green, blue fields and native pixel value. Now replaced with MCColorGetPixel, MCColorSetPixel functions. This prevents further errors due to neglecting to initialize pixel field when setting up color.

Resolves:
[ CID 15987 ] [ CID 16025 ] [ CID 16418 ] [ CID 16427 ] [ CID 16440 ] [ CID 16463 ] [ CID 16492 ] [ CID 16498 ] [ CID 16514 ] [ CID 16571 ] [ CID 16618 ] [ CID 16870 ] [ CID 16967 ]

### CODE REVIEW

**Comment by livecodeali** [comment]
Awesome!

**Comment by livecodeali** [comment]
@livecodeian Does this make it impossible to set black as one of the `colorDialogColors`?

Also I've just noticed that the Mac MCA_getcolordialogcolors doesn't set the count to 0, so 

```
get the colorDialogColors
```

probably crashes on Mac!

**Comment by livecodeali** [comment]
Indeed it does. Do you want to fix that in this PR, or shall I report a separate bug?

**Comment by livecodeian** [comment]
@livecodeali separate bug please. I imagine it's been crashing for a while now, so we should do the full BZ

**Comment by livecodeali** [comment]
@livecode-vulcan review ok cd9210c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok cd9210c819ea58d35e1867bcd6cba3acf5324de1

**Comment by livecode-vulcan** [comment]
😎 test success cd9210c819ea58d35e1867bcd6cba3acf5324de1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2430)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2440)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2423)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2441)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2447)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2451)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2463)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok e177f8b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok e177f8b1d2472270c3cf4f15f1df635a3ab9e8c6

**Comment by livecode-vulcan** [comment]
😎 test success e177f8b1d2472270c3cf4f15f1df635a3ab9e8c6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2464)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2474)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2457)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2475)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2481)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2485)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2497)

**Pull request merged**
