### PR TITLE
[[ Trial ]] Add general support for trial mode.

### PR DESCRIPTION
**Pull request by runrevmark**
This patch adds the core engine part of trial mode.

Note: There is an ide repo PR and a private repo PR to go along with this PR.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/livecode/livecode/3712)

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 19 of 20 files at r1, 5 of 5 files at r2, 6 of 6 files at r3, 1 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: 33 of 36 files reviewed at latest revision, 4 unresolved discussions.

---

_[engine/src/dispatch.h, line 244 [r4]](https://reviewable.io:443/reviews/livecode/livecode/3712#-KCV8u-UjXFR4gjpyU4K:-KCV8u-UjXFR4gjpyU4L:-825853089) ([raw file](https://github.com/livecode/livecode/blob/944f682198c03b442186f67e45ea96ce200cd99a/engine/src/dispatch.h#L244)):_
`isolatedsend()` isn't defined or used in the community engine as far as I can tell; should it be in the community headers?

---

_[engine/src/em-system.cpp, line 1145 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3712#-KCV-qzLfQaxDKB4kCgn:-KCV-qzMc2h8kFhat35z:1812414043) ([raw file](https://github.com/livecode/livecode/blob/92ab03f9859476f6862d8ccc67294dcc350fc11c/engine/src/em-system.cpp#L1145)):_
I think you can call `MCEmscriptenDialogShowAlert()` to implement this.

---

_[engine/src/mode_standalone.cpp, line 568 [r4]](https://reviewable.io:443/reviews/livecode/livecode/3712#-KCV86_5WHfZ8ozpIQ8Y:-KCV86_5WHfZ8ozpIQ8Z:33129259) ([raw file](https://github.com/livecode/livecode/blob/944f682198c03b442186f67e45ea96ce200cd99a/engine/src/mode_standalone.cpp#L568)):_
I can't figure out how the splash screen gets shown on iPhoneOS. It looks like on iOS the engine will just freeze for the appropriate number of seconds rather than actually showing the banner.  Am I missing something?

---

_[engine/src/mode_standalone.cpp, line 838 [r4]](https://reviewable.io:443/reviews/livecode/livecode/3712#-KCV7P2dhNi354lcL49p:-KCV7P2dhNi354lcL49q:-1760473273) ([raw file](https://github.com/livecode/livecode/blob/944f682198c03b442186f67e45ea96ce200cd99a/engine/src/mode_standalone.cpp#L838)):_
Please check these!

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3712)_

**Comment by runrevmark** [comment]
Review status: 33 of 36 files reviewed at latest revision, 4 unresolved discussions.

---

_[engine/src/dispatch.h, line 244 [r4]](https://reviewable.io:443/reviews/livecode/livecode/3712#-KCV8u-UjXFR4gjpyU4K:-KCVDJ9loIHA0gtoLdv7:-255060349) ([raw file](https://github.com/livecode/livecode/blob/944f682198c03b442186f67e45ea96ce200cd99a/engine/src/dispatch.h#L244)):_
Well it needs to be a member of MCDispatch, unless we derive a new class for MCDispatch in commercial, then I'm not sure the best way to resolve that. I can put a dummy implementation in community?

---

_[engine/src/mode_standalone.cpp, line 568 [r4]](https://reviewable.io:443/reviews/livecode/livecode/3712#-KCV86_5WHfZ8ozpIQ8Y:-KCVDY_hzJjgXqElO0Es:-567737191) ([raw file](https://github.com/livecode/livecode/blob/944f682198c03b442186f67e45ea96ce200cd99a/engine/src/mode_standalone.cpp#L568)):_
The banner on iOS is an image which is loaded by the StartupViewController. This is displayed between the startup of the app and the initialization of the LiveCode part finishing.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3712)_

**Comment by runrevmark** [comment]
Review status: 33 of 36 files reviewed at latest revision, 4 unresolved discussions.

---

_[engine/src/mode_standalone.cpp, line 838 [r4]](https://reviewable.io:443/reviews/livecode/livecode/3712#-KCV7P2dhNi354lcL49p:-KCVEvl4PJC_doIfZGY5:-499146009) ([raw file](https://github.com/livecode/livecode/blob/944f682198c03b442186f67e45ea96ce200cd99a/engine/src/mode_standalone.cpp#L838)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3712)_

**Comment by runrevmark** [comment]
Review status: 33 of 36 files reviewed at latest revision, 4 unresolved discussions.

---

_[engine/src/em-system.cpp, line 1145 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3712#-KCV-qzLfQaxDKB4kCgn:-KCVFZwvicJbzKvbkPmx:-499146009) ([raw file](https://github.com/livecode/livecode/blob/92ab03f9859476f6862d8ccc67294dcc350fc11c/engine/src/em-system.cpp#L1145)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3712)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok 8600477

---

Reviewed 1 of 3 files at r4, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[engine/src/dispatch.h, line 244 [r4]](https://reviewable.io:443/reviews/livecode/livecode/3712#-KCV8u-UjXFR4gjpyU4K:-KCVHBoI5MMD8iXHHwi-:1404240153) ([raw file](https://github.com/livecode/livecode/blob/944f682198c03b442186f67e45ea96ce200cd99a/engine/src/dispatch.h#L244)):_
I think it's probably okay. It's probably my "proprietary stuff should be disjoint from community stuff to the maximum extent possible" knee-jerk happening again.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3712#-:-KCVHjAdETmGSmdMjACC:658847126)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 8600477027630c174c41867c4340acc83646dcb6

**Comment by livecode-vulcan** [comment]
😞 test failure 8600477027630c174c41867c4340acc83646dcb6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2045)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/2057)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2039)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2053)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2060)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2066)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2073)

**Comment by peter-b** [comment]
@livecode-vulcan review ok f6b834f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f6b834f57cdf00b4502f59ce5c83074819b17883

**Comment by livecode-vulcan** [comment]
😎 test success f6b834f57cdf00b4502f59ce5c83074819b17883
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2047)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2059)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2041)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2055)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2062)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2068)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2075)

**Pull request merged**
