### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by JohnWoodman**
I've discovered a potentially high severity vulnerability in Livecode and would like to properly disclose it. After trying to reach out to Livecode support team with no response, I decided to make this pull request in hopes one of the developers may see it so I can notify them and so they can implement a proper policy for disclosing future vulnerabilities. Thanks!

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @JohnWoodman, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by mwieder** [comment]
@JohnWoodman how have you tried reaching out to the team? An email to support@livecode.com should get someone's attention.

**Comment by JohnWoodman** [comment]
I've sent a support ticket at livecode.com, which says it gets sent to support@livecode.com, but I'll try emailing them directly. Thanks!

**Comment by mwieder** [comment]
Cool. Ping me if you don't get a response post-haste.

**Comment by JohnWoodman** [comment]
Will do.

**Pull request closed without merging**
