### PR TITLE
apk_list_folder_entries(): Clean up error handling.

### PR DESCRIPTION
**Pull request by peter-b**
Ensure that all operations that can fail get their results checked.

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok fee160d

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok fee160d246d9a374b4916245c0cbcfd3a0464305

**Comment by livecode-vulcan** [comment]
😞 test failure fee160d246d9a374b4916245c0cbcfd3a0464305
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2801)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/2808)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2794)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2810)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2816)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2820)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2839)

**Comment by peter-b** [comment]
@montegoulding I've now refactored this function's error handling much more thoroughly, as recommended by @livecodeali.

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 4e1bcb7

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 4e1bcb70cae45ac8b04911c523e11e7b7dba0c94

**Comment by livecode-vulcan** [comment]
😎 test success 4e1bcb70cae45ac8b04911c523e11e7b7dba0c94
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2813)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2820)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2806)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2822)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2828)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2837)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2852)

**Pull request merged**
