### PR TITLE
[[ Widgets ]] Add themeClass to reserved properties

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevmark** [comment]
What's the rationale behind this? The only reason (I believe) we added it to engine controls was because they are mixed components (I.e. have more than one function). Widgets won't be - they should decide their 'theme class'.

**Comment by livecodefraser** [comment]
It is an engine-level property common to all objects so, like the other properties in that group, should probably be reserved until we decide what to do with it (even if that is make it read-only for widgets).

**Comment by runrevmark** [comment]
@livecodefraser: Makes sense!

@livecode-vulcan review ok b9b42a4

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok b9b42a4da4f8e2a040ca9c303f083962f0c7b417

**Comment by livecode-vulcan** [comment]
😎 test success b9b42a4da4f8e2a040ca9c303f083962f0c7b417
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1993)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2006)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1987)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1999)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2009)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2015)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2019)

**Pull request merged**
