### PR TITLE
[CID 16896] Fix memory leak when compacting paragraphs.

### PR DESCRIPTION
**Pull request by peter-b**
Coverity-ID: 16986

### CODE REVIEW

**Comment by runrevmark** [comment]
@peter-b: I wonder if we could actually consider removing this code. The engine has not emitted stackfiles with the 'COMPACT_PARAGRAPHS' flag since at least version 2 (14 years ago) - perhaps even further back. What do you think?

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 84aea8e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 84aea8ed7152f86bd9e0adea9972375e15364cea

**Comment by peter-b** [comment]
@runrevmark I've decided not to remove `COMPACT_PARAGRAPHS` support for now, because it would make it impossible to load some older stacks into the current engine.  I suppose there's a question about whether we want to drop backwards compatibility with them, but that seems like a separate issue to this fix.

**Comment by livecode-vulcan** [comment]
😎 test success 84aea8ed7152f86bd9e0adea9972375e15364cea

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/848)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/854)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/846)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/847)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/854)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/845)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/845)

**Pull request merged**
