### PR TITLE
Rename HACKING.md to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by livecodestephen**
CONTRIBUTING.md is clearer and hopefully less intimidating.  This also seems to be a more usual file name; it's used by rust, coffeescript, go, ruby, php, julia, scala, ....

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok caa6272

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok caa627245ff7c65275265925186ec0e93442028f

**Comment by livecodeali** [comment]
Does this need to be merged first, or will git be ok?
https://github.com/livecode/livecode/pull/2861

**Comment by livecodestephen** [comment]
I think git is supposed to be ok with renames, but I've never tried it.

**Comment by livecode-vulcan** [comment]
😎 test success caa627245ff7c65275265925186ec0e93442028f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/357)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/357)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/356)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/355)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/360)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/352)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/363)

**Comment by livecodeali** [comment]
Argh, just realised this should have been targeted at develop-6.7

**Comment by livecodestephen** [comment]
Should I put in a separate pull request for 6.7?

**Comment by livecodestephen** [comment]
develop is set as the default branch on GitHub so this is the version people will see.

**Comment by livecodeali** [comment]
True, it's not a big issue

**Pull request merged**
