### PR TITLE
[[ Bug 17776 ]] Parse deprecated LCB syntax properly

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 6981374

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 69813747d16200057f7458d7eeec7416df58e0d0

**Comment by peter-b** [comment]
@livecode-vulcan review ok 6981374

**Comment by livecode-vulcan** [comment]
😎 test success 69813747d16200057f7458d7eeec7416df58e0d0
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2708)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2718)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2703)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2719)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2725)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2731)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2743)

**Pull request merged**
