### PR TITLE
[[Documentation]] pointer - Links

### PR DESCRIPTION
**Pull request by seaniepie**
- Added links to control (glossary) and cantModify (property)

### CODE REVIEW

**Comment by livecodeali** [comment]
@seaniepie For the links to work you also need to add `control (glossary)` and `cantModify (property)` to the references

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 5c8f721

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 5c8f72151e68879c579e17c2d34bb82306546a6d

**Comment by livecode-vulcan** [comment]
😎 test success 5c8f72151e68879c579e17c2d34bb82306546a6d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/382)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/387)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/382)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/382)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/388)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/382)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/382)

**Pull request merged**
