### PR TITLE
Bugfix/iss8884

### PR DESCRIPTION
**Pull request by montegoulding**
Found another couple of tweaks to make while working on lcVCS... still to think about it what we should do about the fact that returning the abbrev id if name's not set. Round tripping that will cause problems.

### CODE REVIEW

**Comment by runrevmark** [comment]
Hi Monte,

I've pulled your modifications in with a couple of changes - hope you don't mind too much...

I decided a conservative approach to changing the behavior of the image prop setting for filename/text would be sensible. Rather than change this at this functionality at this late stage of the dev cycle, I've put work-arounds in for these properties into MCVariableValue::setprops - i.e. to make it so that setting the filename/text of an image there has no effect if the value is empty. I've filed a bug (10977) about the actual behavior of text/filename and commented out the changes to fix it in the code - we can reintroduce the fix for the next major release, and remove the workarounds in 'the properties' then.

I also noticed that the 'preprocess' check wasn't actually working since 'continue' was acting on the containing 'for', rather than 'while'.

You can see the final changes at 'feature-revised_properties_prop' in the runrev/livecode repo.

Thanks for all your work!

Mark.

**Comment by montegoulding** [comment]
Weird that Github says it's closed with unmerged commits... I guess it's because it's not merged into master?? Anyway, don't know how I missed the pre-process logic... sorry about that. Regarding bug 10977 I think that's a good way to go although I had general support on the use list for that change... there is a little quirk now though that if both are empty or one is empty and the other isn't there and the target object has the corresponding property then it won't be cleared.

**Comment by runrevmark** [comment]
Yeah - it means closed with unmerged commits against master - it's annoying you can't change the target of a pull-request in GitHub to stop that. The warning will vanish when the release-6.1.0 branch merges into master.

In regards to the 'continue' thing, easy mistake to make - I missed it from looking at it and only noticed when I was checking roundtripping the properties on an image object. I guess c compilers just aren't clairvoyant enough to know which loop you want to continue ;)

Yes - I think we'll be absolutely fine in making the change, I just wanted to do it at the beginning of a dev cycle so people have time to potentially adjust code. It's a much cleaner semantic than the current one which fits with the rule, setting a property to its existing value should have no effect.

I'm going to file a bug about the changes to 'name' too - I can't see any stacks _correctly_ relying on the name returning '... id ...' if the name is empty as (since we've already established) such references don't work anyway when used with a control chunk.

I'll take a look at the quirk you describe and see if I can fix for release.

**Comment by runrevmark** [comment]
Okay took a look at the quirk... Based on the rule 'setting an empty property to empty should have no effect', then the only case that's erroneous with the work-around is if both filename/text are present and empty. If you have an array with just one of 'filename' or 'text' and it is empty, then it should only have an effect if the object already has a filename or text respectively - this is the same with the color/pattern properties. i.e. If your object has a pattern, and you try to set the properties with just an empty color key it will have no effect (since the existing color property is empty).

**Pull request closed without merging**
