### PR TITLE
[21690] Fix crash when clicking on magnify palette with Browse tool

### PR DESCRIPTION
**Pull request by livecodepanos**
Previously the image was converted to mutable only an editing tool was selected, and clicking (i.e. `image_mdown`) on the magnify palette with Browser or Pointer tool selected was causing a crash.

This patch ensures that `MCImage::magmdown` sends `image_mdown` only if an editing tool is selected.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodepanos This has a version update in it too!

**Comment by livecodepanos** [comment]
@livecodeali Oops :)

**Comment by montegoulding** [comment]
@livecode-vulcan review ok e026ab9

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok e026ab9d9c702bf8c8c51c420b35c00fc86875ae

**Comment by livecode-vulcan** [comment]
😎 test success e026ab9d9c702bf8c8c51c420b35c00fc86875ae

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/245)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/237)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/237)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/237)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/237)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1759)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/141)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/141)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1790)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1780)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1779)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1814)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1754)

**Pull request merged**
