### PR TITLE
Runrev references removal 7.0

### PR DESCRIPTION
**Pull request by livecodesebastien**
Merge of runrev_references_removal into develop-7.0:
- no conflict apart from line ending issues
- the changes made for 7.0-only files are in the commits a399f55 and 6e103bc

### CODE REVIEW

**Comment by livecodesebastien** [comment]
https://github.com/runrev/livecode-ide/pull/462 must be merged in.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 6e103bc

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 6e103bc0e9a4f20f27c22d0a0bc9bb95da6d04e9

**Comment by livecodeali** [comment]
The dictionary seems to build ok with these changes merged in.

**Comment by livecode-vulcan** [comment]
😎 test success 6e103bc0e9a4f20f27c22d0a0bc9bb95da6d04e9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/254)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/252)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/254)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/249)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/256)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/252)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/257)

**Pull request merged**
