### PR TITLE
[Bug 16785] Fix up release note.

### PR DESCRIPTION
**Pull request by peter-b**
Release note was in the wrong place and in the wrong format (which
broke the build).

### CODE REVIEW

**Comment by peter-b** [comment]
Fixes breakage introduced by #3539.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 06b2d97

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 06b2d97992d24093ea1b385164060d0107ce9047

**Comment by livecode-vulcan** [comment]
😎 test success 06b2d97992d24093ea1b385164060d0107ce9047
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1786)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1799)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1780)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1792)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1801)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1805)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1811)

**Pull request merged**
