### PR TITLE
[Bug 17373] clock: Make local timezone default & fix setting local tz

### PR DESCRIPTION
**Pull request by peter-b**
- Ensure that the clock treats an empty timezone as the local
  timezone
- Change the default clock timezone to local
- Add some basic tests for setting the local timezone

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 8e663a5

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 8e663a5049929694d73a27ae178ed65126258b32

**Comment by peter-b** [comment]
I've made no code changes from @BerndN's original PR; I've just cleaned up the commit log and rebased to `develop-8.0`.

**Comment by BerndN** [comment]
@peter-b thank you for cleaning that up.
I noticed that the test is not in a subfolder tests, if I understand this correctly.
the path for the file is:
extensions/widgets/clock/properties.livecodescript

**Comment by peter-b** [comment]
@BerndN Good spot! Thanks for checking and pointing it out so promptly. I'll correct that right now.

@livecode-vulcan review not ok 8e663a5

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 8e663a5049929694d73a27ae178ed65126258b32

**Comment by peter-b** [comment]
@livecodefraser Could you please re-review? Only change is moving the test into the `tests` subdirectory.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay d9f7582

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok d9f758292a8585a3036004f5299df11707f8d37c

**Comment by livecode-vulcan** [comment]
😎 test success d9f758292a8585a3036004f5299df11707f8d37c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2662)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2672)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2657)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2673)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2679)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2685)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2697)

**Pull request merged**
