### PR TITLE
Merge develop-8.0 into develop

### PR DESCRIPTION
**Pull request by peter-b**
Only conflict was in ide submodule pointer, which has been left unchanged.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 76dd2fd

**Comment by livecodefraser** [comment]
Hmm, Vulcan seems to be ignoring you Ali...

@livecode-vulcan reviewed by @livecodeali okay 76dd2fd

**Comment by peter-b** [comment]
@livecode-vulcan reviewed by @livecodeali ok 467182e

Curse you GitHub, Y U no show commits in DAG order?!

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 467182e2b9f4909460a88141a4cd51bb5ec86089

**Comment by livecode-vulcan** [comment]
😎 test success 467182e2b9f4909460a88141a4cd51bb5ec86089
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2682)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2692)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2677)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2693)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2699)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2705)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2717)

**Pull request merged**
