### PR TITLE
Archive and stage documentation data

### PR DESCRIPTION
**Pull request by peter-b**
Ensure that all pre-built documentation included with the installer is separately archived and uploaded to the staging area.

This will be used for automated deployment of the online documentation.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali I'm not sure this is quite the ideal approach but it seems to work well enough for now.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 9f6e21a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 9f6e21a0ba170799451fe4930b988f853360a45d

**Comment by livecode-vulcan** [comment]
😎 test success 9f6e21a0ba170799451fe4930b988f853360a45d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1808)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1821)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1802)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1814)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1824)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1827)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1833)

**Pull request merged**
