### PR TITLE
[[ Bug 22511 ]] Fix multi-codepoint character parsing in JSONImport()

### PR DESCRIPTION
**Pull request by trevordevore**
Closes https://quality.livecode.com/show_bug.cgi?id=22511

### CODE REVIEW

**Review by peter-b — CHANGES_REQUESTED** [review]
Hi @trevordevore, this is a great bug! Good find!

The 'French flag' emoji (🇫🇷) is a grapheme composed from 3 codepoints:

1. U+1F1EB REGIONAL INDICATOR SYMBOL LETTER F
2. U+200D ZERO WIDTH JOINER
3. U+1F1F7 REGIONAL INDICATOR SYMBOL LETTER R

In LCB, each 'char' of a string is actually a grapheme. The JSON library incorrectly loops over the chars of each string when parsing or formatting, rather than looping over their codepoints.  `FormatChar` thinks its processing a single codepoint, but incorrectly gets passed whole graphemes. The same  problem affects the `JSONImport()` scanner; it should operate over the codepoints of its input string rather than its graphemes.

So, unfortunately, I'm not sure that this patch is correct in the general case.  Please could you try to fix this by changing the various loops from 'char' loops to codepoint loops?

Best regards,

Peter

**Comment by runrevmark** [comment]
@peter-b This patch is fine.

In the FormatChar case, it is checking to see if the char is a control char (i.e. <= 0x1f codepoint) - and otherwise just returning the char string (which is only then concatenated into another string) for the purposes of error generation.

In the parsing case it is (again), just fixing the test for a control char to ensure an appropriate error is generated - as unescaped control chars are not allowed.

The fact that pChar might be a multi-codepoint grapheme in these cases is irrelevant - as it is the first codepoint of the cluster which is important, and if said codepoint is a control char then the JSON is malformed anyway.

**Review by runrevmark — APPROVED** [review]

**Comment by runrevmark** [comment]
@livecode-vulcan review ok daafb50

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok daafb50c81c33bb1f2f69a3be8d7b0bd0241ab70

**Comment by livecode-vulcan** [comment]
😎 test success daafb50c81c33bb1f2f69a3be8d7b0bd0241ab70

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/737)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/146)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/146)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/146)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/146)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2263)
* try-community-universal-ios-iphoneos13.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.2/builds/38)
* try-community-universal-ios-iphonesimulator13.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.2/builds/38)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2292)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2279)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2278)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2312)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2252)

**Pull request merged**
