### PR TITLE
Make RevBrowser compatible with 64-bit OSX

### PR DESCRIPTION
**Pull request by livecodefraser**
The CEF component of RevBrowser does not yet work in 64-bit builds as we don't currently have a 64-bit libCEF prebuilt.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 67de8e7

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 67de8e784fe5381fe43be98539182f728508fbe8

**Comment by livecode-vulcan** [comment]
😞 test failure 67de8e784fe5381fe43be98539182f728508fbe8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/962)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/970)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/959)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/963)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/972)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/981)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/976)

**Comment by livecodefraser** [comment]
Oops, I broke it...

**Comment by peter-b** [comment]
@livecodefraser Please fix the Windows build issue!

**Comment by peter-b** [comment]
@livecode-vulcan review not ok 67de8e7

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 67de8e784fe5381fe43be98539182f728508fbe8

**Comment by peter-b** [comment]
@livecode-vulcan review ok d3f8581

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d3f85810d48bf859741aa9ee481612e33a12a1e2

**Comment by livecode-vulcan** [comment]
😞 test failure d3f85810d48bf859741aa9ee481612e33a12a1e2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1370)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1381)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1366)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1376)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1387)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1386)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1391)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 376ad95

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 376ad95d2557ae514b20966c443d883e0ad1edf2

**Comment by livecode-vulcan** [comment]
😎 test success 376ad95d2557ae514b20966c443d883e0ad1edf2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1372)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1383)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1368)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1378)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1389)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1388)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1393)

**Pull request merged**
