### PR TITLE
[[ Bugfix 15187 ]] Update the valid iOS SDK, to include iOS SDK 8.3

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by runrevmark** [comment]
We need to provide both 8.2 and 8.3 builds for now - Xcode 6.3 only runs on Yosemite, so until Apple require iOS 8.3 for submission to the AppStore we need to continue to support Xcode 6.2.

**Comment by livecodesebastien** [comment]
This pull request needs both https://github.com/runrev/livecode-ide/pull/176 and https://github.com/runrev/livecode-prebuilt/pull/3 to be merged in (and the IDE submodule pointer to be updated).

**Comment by runrevmark** [comment]
Reviewed-by: @runrevmark.

**Comment by livecodesebastien** [comment]
Also requires pull requests https://github.com/runrev/livecode-private/pull/8 and https://github.com/runrev/livecode-prebuilt/pull/3 to be merged in.

**Pull request merged**
