### PR TITLE
[[Cleanup]] Mac-oriented build cleanups

### PR DESCRIPTION
**Pull request by peter-b**
Various fixes to make CI builds on Mac less noisy, by targeting warnings from header files.

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay b4eb12f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok b4eb12fc36b5e7138067e07bf95c0dde6e2575c6

**Comment by livecodeali** [comment]
@livecode-vulcan review ok afc7ac1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok afc7ac1c0598447ae6b5aa27c7148fe9a89e9fe9

**Comment by livecode-vulcan** [comment]
😎 test success afc7ac1c0598447ae6b5aa27c7148fe9a89e9fe9
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/547)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/606)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/496)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/560)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/492)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/485)

**Pull request merged**
