### PR TITLE
Merge develop 7.0 08 07 15

### PR DESCRIPTION
**Pull request by livecodeali**
Only one conflict here, a trivial one in dsklnx.cpp

### CODE REVIEW

**Comment by peter-b** [comment]
Looks okay :+1: 

@livecode-vulcan review okay 700372d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 700372d9d08b5f99ae3dd551722a42ef43776dc9

**Comment by livecode-vulcan** [comment]
😞 test failure 700372d9d08b5f99ae3dd551722a42ef43776dc9
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/451)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/511)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/397)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/462)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/397)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/388)

**Comment by livecodeali** [comment]
@livecode-vulcan review by @peter-b ok e12465b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e12465bb9968a8eeb7f910b382d27e0df1ddfcc8

**Comment by livecode-vulcan** [comment]
😞 test failure e12465bb9968a8eeb7f910b382d27e0df1ddfcc8
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/458)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/517)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/404)
- try-android-armv6: [pending](https://vulcan.livecode.com/builders/try-android-armv6/builds/469)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/404)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/395)

**Comment by livecodeali** [comment]
@livecode-vulcan retry e12465b

**Comment by livecode-vulcan** [comment]
😞 test failure e12465bb9968a8eeb7f910b382d27e0df1ddfcc8
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/461)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/520)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/407)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/472)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/407)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/398)

**Comment by livecodeali** [comment]
@livecode-vulcan  review by @peter-b ok 914a98b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 914a98bf0b14cea7e5d94dad783252a99ae6cfa9

**Comment by peter-b** [comment]
@livecode-vulcan review ok 914a98b

**Comment by livecode-vulcan** [comment]
😎 test success 914a98bf0b14cea7e5d94dad783252a99ae6cfa9
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/465)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/524)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/411)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/476)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/411)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/402)

**Pull request merged**
