### PR TITLE
Standalone builder leaves stackfiles stacks in memory

### PR DESCRIPTION
**Pull request by trevordevore**
http://quality.livecode.com/show_bug.cgi?id=19248

### CODE REVIEW

**Comment by montegoulding** [comment]
@trevordevore This seems OK but for some reason the mac build or tests are timing out. Logs seem beyond the limit of what Travis supports. I've just restarted the builds again and we will see what happens. Could you please add a release note to this PR.

**Comment by trevordevore** [comment]
@montegoulding Done.

**Comment by montegoulding** [comment]
Thanks @trevordevore hopefully that might fix the build issue too. I notice that @livecodepanos changed the PR target and I think that can confuse Travis until there's a new commit... maybe...

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 1d0c557

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 1d0c55728ec6c72fd01d358b1faeefda000ffd43

**Comment by livecode-vulcan** [comment]
😞 test failure 1d0c55728ec6c72fd01d358b1faeefda000ffd43

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/952)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/958)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/950)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/951)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/958)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/965)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/949)

**Comment by peter-b** [comment]
@livecode-vulcan retry 1d0c557

**Comment by livecode-vulcan** [comment]
😎 test success 1d0c55728ec6c72fd01d358b1faeefda000ffd43

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/961)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/967)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/959)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/960)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/967)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/976)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/958)

**Pull request merged**
