### PR TITLE
[[ Graph Widget ]] Enhancements to the graph widget

### PR DESCRIPTION
**Pull request by livecodeali**
- Don't recalculate when widget is moved but not resized
- Actually draw x-axis label text
- Don't draw new lines in transparent color
- Add hilitedCoordinates property
- Use editorList with color subeditor rather than (to be removed) colorList editor

### CODE REVIEW

**Comment by livecodeali** [comment]
Requires https://github.com/livecode/livecode-ide/pull/911

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4d0e8dd

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4d0e8dd4de9149b437bb569e6bdef56abdfb7369

**Comment by livecode-vulcan** [comment]
😞 test failure 4d0e8dd4de9149b437bb569e6bdef56abdfb7369
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1835)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1848)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1829)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1841)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1851)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1854)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1860)

**Comment by peter-b** [comment]
@livecode-vulcan retry 4d0e8dd

**Comment by peter-b** [comment]
@livecode-vulcan review ok 03968ed

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 03968ed428eeb79fb39bf4edc8f2561d85a6cd22

**Comment by livecode-vulcan** [comment]
😞 test failure 03968ed428eeb79fb39bf4edc8f2561d85a6cd22
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1843)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1856)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1837)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1849)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1859)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1862)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1868)

**Comment by livecodeali** [comment]
@livecode-vulcan retry  03968ed

**Comment by livecode-vulcan** [comment]
😎 test success 03968ed428eeb79fb39bf4edc8f2561d85a6cd22
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1848)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1861)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1842)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1854)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1864)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1867)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1873)

**Pull request merged**
