### PR TITLE
[[ CEF ]] Fix locale copying on win32 for development

### PR DESCRIPTION
**Pull request by runrevmark**
This patch ensures that the locale files for CEF on Win32 are
copied from the right place when doing a development build.

This has no effect on distribution builds, just when building
from Visual Studio - ensuring that the locale files are present
in the appropriate place.

### CODE REVIEW

**Review by peter-b — APPROVED** [review]

**Comment by peter-b** [comment]
@livecode-vulcan review ok 741d5de

**Comment by runrevmark** [comment]
@livecode-vulcan review by @peter-b ok 741d5de

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 741d5deb0bc96ada26b100e14c8d61fafe851309

**Comment by livecode-vulcan** [comment]
😎 test success 741d5deb0bc96ada26b100e14c8d61fafe851309

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/127)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/127)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/113)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/59)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/59)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/125)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/127)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/129)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/131)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/129)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/131)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/150)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/126)

**Pull request merged**
