### PR TITLE
[[ Bug 15426 ]] Check that foreign handler definitions are fully typed.

### PR DESCRIPTION
**Pull request by runrevmark**
The compiler now distinguishes between a type annotation being present, and not being present (unspecified). This is used to ensure foreign handler definitions have explicity typed parameters and return type.

### CODE REVIEW

**Comment by peter-b** [comment]
Why comment out chunks of code rather than deleting it?

**Comment by peter-b** [comment]
Does this change require a release note?

**Comment by runrevmark** [comment]
Because it is not yet implemented - but might well be at some point soon.

**Comment by livecodeali** [comment]
Is this going into DP 3?

**Comment by runrevmark** [comment]
@livecodeali: Release note added - just needs a review :)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 10e52b9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 10e52b9b7f87aacd0c745681a4a1c92365e08e42

**Comment by livecode-vulcan** [comment]
😎 test success 10e52b9b7f87aacd0c745681a4a1c92365e08e42
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/708)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/768)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/658)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/722)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/653)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/645)

**Pull request merged**
