### PR TITLE
[Bug 16953] Remove dependency on libX11

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay d220cea

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok d220cea80abccadb253cca87741efce15030d8e4

**Comment by livecode-vulcan** [comment]
😞 test failure d220cea80abccadb253cca87741efce15030d8e4
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1916)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1929)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1910)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1922)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1932)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1937)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1942)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay c3eefd1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok c3eefd1b0d0fe5c25ea332c8276013f6383cebf8

**Comment by livecode-vulcan** [comment]
😎 test success c3eefd1b0d0fe5c25ea332c8276013f6383cebf8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1917)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1930)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1911)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1923)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1933)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1938)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1943)

**Pull request merged**
