### PR TITLE
Allow global handlers to be overridden by scripted handlers

### PR DESCRIPTION
**Pull request by montegoulding**
Previously global handlers took priority
over handlers scripted in LCS. This patch
enables a LCS handler the handle the global
handler instead. This is necessary for
for overriding the libURL commands on mobile.

### CODE REVIEW

**Comment by peter-b** [comment]
@montegoulding Please update the commit message & PR description to more clearly describe the problems that this patch solves!

**Comment by montegoulding** [comment]
Does that cover it @peter-b ?

**Comment by peter-b** [comment]
Indubitably, my dear @montegoulding 

@livecode-vulcan review ok a8b3b79

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a8b3b7949fed78be33242ded38fdb2b40ee639bc

**Comment by livecode-vulcan** [comment]
😎 test success a8b3b7949fed78be33242ded38fdb2b40ee639bc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2782)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2791)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2777)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2793)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2799)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2803)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2821)

**Pull request merged**
