### PR TITLE
[[ Bug 18032 ]] Implement do in object

### PR DESCRIPTION
**Pull request by montegoulding**
An alternative to #4374 that doesn't break things and adds a feature ;-)

### CODE REVIEW

**Comment by runrevmark** [comment]
@montegoulding: Unfortunately this doesn't work - there is an ambiguity between 'do in widget which happens to be browser' and 'do in any object' - if you have a browser object you might either want to execute javascript in it, or in some cases you might want to execute a script in it.

**Comment by montegoulding** [comment]
Hmm... I documented that it was up to the widget author how they wanted to implement `do in object` which I think is reasonable.

**Comment by montegoulding** [comment]
But I guess we could add some more explicit syntax if you have some suggestions. FWIW the use case we need in the IDE is covered by just `do in stack`...

**Comment by runrevmark** [comment]
But then there's no way to get the do LiveCode script in object for widgets which choose to do something different - you'd get unexpected behavior looping over a collection of different objects some of which that happen to be widgets. This perhaps does suggest that 'do in widget' should have more specific syntax.

**Comment by peter-b** [comment]
I'm marking this WIP pending agreeing on how this should work with @runrevmark

**Comment by montegoulding** [comment]
Yes I'm not sure if we will be able to use this without changing the do in widget syntax.

**Comment by runrevmark** [comment]
This is a bit of a quandry. It is clear that in this instance there is a distinction between 'doing a script in the context of a (script) object' and 'doing a script _inside_ an object'. The former is entirely a host environment concern; the latter would be a widget concern. I'm sure this isn't going to be the only case of this - where a similar verb seems to make sense for an action which could be interpreted as either something universal (to the environment) or internal to the target.

Looking forward to a world where syntax is more mutable, the current situation would be described as this:

The host environment defines a universal (not restricted to a specific type) piece of syntax:

```
    do x in <object>
```

The browser widget exports a specific (restricted to the browser type) piece of syntax:

```
   do x in <object> -- where <object> must be of browser widget type
```

In the future, this would mean that trying to do 'do x in y' where y is not a browser would be fine; but if you did try to do 'do x in browser y' then you would get an ambiguity error - as a browser is also an object. This would mean you would have to explicitly tag the 'do' (e.g. livecode.do x in y) to indicate which one you wanted to select in that case.

For third-party extension interactions this situation is fine - as most of those would be target type based and thus ambiguity would rarely arise. However, for a verb (do) which has very well known and well defined meaning in the host environment it is not really fine at all. Thus I think we might need to seriously consider doing something terminal to 'do in browser'.

The problem is I'm not sure what the syntax should be. Using 'in' and 'inside' doesn't work as they are synonyms (and the distinction is too subtle).

```
   do X in <object>
   do X inside <object>
```

Another (just as bad?) suggestion would be to use 'do X on <object>' for the universal (host) case. However, we 'send' messages 'to' objects which suggests they are handled 'in' the object (well the script) so 'on' is the wrong sense.

Another option would be to use a trailing adverb to distinguish. Given 'do in browser' is more akin to 'do script internally in browser widget' perhaps:

```
   do X in <object>
   do X in <object> internally
```

The 'internal' idea potentially is inline with the idea of the distinction between the host script object, and the 'internal' widget which is wrapped by it.

However, perhaps we just need a different verb to describe the 'doing something language like in the way a widget wants to'.

**Comment by jameshale** [comment]
I thought you might be doing something WITH a widget but you are actually using the widget to do something so...
do X using <widget>

Perhaps?
Sorry, discussion looked interesting and began heading toward two syntactic forms rather than a single omnibus one.

**Comment by montegoulding** [comment]
@jameshale Hmm... `using` seems to be just a different token that doesn't really convey the difference in function. I'm currently on a different project so this may remain WIP for a while but hopefully be resolved before 9. Probably a solution would be:

```
do in object [ as {script | alternateLanguage} ]
```

Where:
- no explicit language is a legacy form _only_ supported on widgets and throws an error on other objects
- where the `script` form is handled by the engine in all cases
- where the `alternateLanguage` form is handled by the widget in all cases and the widget can throw an error if either it doesn't support the alternateLanguage being specified or the engine throws an error if there's no `OnDo` handler.

This works as long as we don't want the engine to handle scripts in alternate languages in an object context ever... which probably needs input from @runrevmark as it may not be the case

An alternative form might be:

```
do [script] in object
```

Where if `script` isn't specified then the `object` must be a widget but I think I like the `as alternateLanguage` form because it means that a widget could support multiple languages.

**Comment by jameshale** [comment]
@montegoulding ok. Seems the scope of a widget is much larger than I had envisaged if it is capable of running other languages. I am assuming here you are not talking about wrapping some library.

**Comment by montegoulding** [comment]
@jameshale why would you assume that? It is up to the widget to implement whatever it wants to with do. The browser widget passes JavaScript to the browser. Other widgets could pass it to other libraries.

**Comment by jameshale** [comment]
@montegoulding ok, I understand I think.
So it is..
do X [in object][as alternatelanguage/script]

**Comment by montegoulding** [comment]
@jameshale yes:

```
do <whatever> [in object][ as {script | alternateLanguage} ]
```

Indeed it also opens up an explicit form for do which is probably not a bad idea:

```
do <whatever> as script
```

**Comment by montegoulding** [comment]
Actually being completely explicit you could:

```
do <whatever> in me as script
```

**Pull request closed without merging**
