### PR TITLE
Fix misnamed bugfix release note.

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 4d16d3c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4d16d3c45d774a3c537f6e6c66ce69c164f57ce4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4d16d3c45d774a3c537f6e6c66ce69c164f57ce4

**Comment by livecode-vulcan** [comment]
😎 test success 4d16d3c45d774a3c537f6e6c66ce69c164f57ce4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2334)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2343)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2327)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2344)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2350)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2355)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2366)

**Pull request merged**
