### PR TITLE
Bugfix 15417 - update launch data when app is resumed

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodeian: Is it worth having this as a separate PR? Or would it be better just rolled into the 'notification' idea PR?

**Comment by livecodeian** [comment]
It's already a separate PR, and it fixes a bug so why not?

**Comment by runrevmark** [comment]
@livecode-vulcan review ok da284f2

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok da284f24291e9eb206555dee5d6a07e40bf3b7d5

**Comment by livecode-vulcan** [comment]
😎 test success da284f24291e9eb206555dee5d6a07e40bf3b7d5
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/704)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/717)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/705)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/707)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/717)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/728)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/719)

**Pull request merged**
