### PR TITLE
[[ Android API 28 ]] Update to use android API 28

### PR DESCRIPTION
**Pull request by livecodeali**
This patch changes our build scripts to use or default to android
api 28. It also removes the builders' dependence on the sdk API
version so we can use the same build containers for any sdk API and
only have to update (and rebuild prebuilts) when the ndk changes.

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok a6a4b6c

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok a6a4b6c26c3bc7c14c988e28687a342f2ba16b95

**Comment by livecodeali** [comment]
@livecode-vulcan retry a6a4b6c

**Comment by montegoulding** [comment]
@livecode-vulcan review ok be57014

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok be57014d0fba2e92090d6a9ad47728ba23b3be45

**Comment by livecodeali** [comment]
This succeeded on all builders but something went wrong with buildbot communication that prevented vulcanbot reporting that success.

**Pull request merged**
