### PR TITLE
[[ Bug 15808 ]] Document SVG icon widget

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/runrev/livecode/2783)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 215232e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 215232ee7032d59cc6e0a222515801b8d12331ab

**Comment by livecode-vulcan** [comment]
😎 test success 215232ee7032d59cc6e0a222515801b8d12331ab
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/179)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/178)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/179)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/174)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/181)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/178)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/182)

**Pull request merged**
