### PR TITLE
Merge develop 7.0 01.04.16

### PR DESCRIPTION
**Pull request by livecodeali**
Clean merge (modulo version file)

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok cfd049c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok cfd049ca25c4311b62c1f380cc525f37853e40aa

**Comment by livecode-vulcan** [comment]
😞 test failure cfd049ca25c4311b62c1f380cc525f37853e40aa
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2286)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/2295)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2279)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2296)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2302)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2307)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2318)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 1c2aae5

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 1c2aae573690e162a4366b22678e555e9a0edfcd

**Comment by livecode-vulcan** [comment]
😞 test failure 1c2aae573690e162a4366b22678e555e9a0edfcd
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2288)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/2297)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2281)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2298)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2304)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2309)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2320)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok e603f29

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok e603f29550aef130473c80809458e42c3fc340e7

**Comment by livecode-vulcan** [comment]
😎 test success e603f29550aef130473c80809458e42c3fc340e7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2289)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2298)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2282)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2299)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2305)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2310)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2321)

**Pull request merged**
