### PR TITLE
Merge develop-8.1 into develop and update supported target triples

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodeali** [comment]
@peter-b You need to add a `(nothrow)` to the updated `new Ustruct` section :-)
(https://github.com/livecode/livecode/pull/5305)

**Comment by peter-b** [comment]
@livecodeali Whoops, sorry -- I missed that you already had a merge PR open.

I've added a commit that adds the missing `std::nothrow`.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 1610f0a
No worries!

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 1610f0a7737731d83220326e60dd442757b8d083

**Comment by livecode-vulcan** [comment]
😎 test success 1610f0a7737731d83220326e60dd442757b8d083

* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/7)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/9)
* try-community-universal-ios-iphoneos10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.2/builds/9)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/9)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/4)
* try-community-universal-ios-iphonesimulator10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.2/builds/9)
* try-community-js-emscripten: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten/builds/11)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/9)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/8)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/3)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/5)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/7)

**Pull request merged**
