### PR TITLE
[[ Bug 19010 ]] Add release note

### PR DESCRIPTION
**Pull request by techstrategies**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 6818d58

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 6818d58b50acd3a60ae03e219e1cc260bc064e87

**Comment by livecode-vulcan** [comment]
😞 test failure 6818d58b50acd3a60ae03e219e1cc260bc064e87

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/776)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/781)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/774)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/775)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/781)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/773)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/773)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 6818d58

**Comment by livecode-vulcan** [comment]
😎 test success 6818d58b50acd3a60ae03e219e1cc260bc064e87

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/796)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/801)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/794)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/795)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/801)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/793)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/793)

**Pull request merged**
