### PR TITLE
docs: Refine LiveCode 8 release notes

### PR DESCRIPTION
**Pull request by peter-b**
[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode/3410)

### CODE REVIEW

**Comment by livecodeali** [comment]
_[docs/lcb/notes/15426.md, line 12 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3410#-K5e70m_SFo3WPzcifgm:-K5e70m_SFo3WPzcifgn:1985436329) ([raw file](https://github.com/livecode/livecode/blob/feb6dcc07d2b1cd0b689d70ef67ced5f46d417d5/docs/lcb/notes/15426.md#L12)):_
'foriegn' ( I know it was there before, but might as well fix typos)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3410)_

**Comment by livecodeali** [comment]
_[docs/notes/feature-image_metadata.md, line 21 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3410#-K5e9VpXFE3ejwbGl3j8:-K5e9VpXFE3ejwbGl3j9:-1364348384) ([raw file](https://github.com/livecode/livecode/blob/feb6dcc07d2b1cd0b689d70ef67ced5f46d417d5/docs/notes/feature-image_metadata.md#L21)):_
I guess this should be in a ``` block

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3410)_

**Comment by livecodeali** [comment]
_[docs/notes/feature-image_metadata.md, line 21 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3410#-K5e9VpXFE3ejwbGl3j8:-K5e9nGXFK-CaTkLE-k4:-504530952) ([raw file](https://github.com/livecode/livecode/blob/feb6dcc07d2b1cd0b689d70ef67ced5f46d417d5/docs/notes/feature-image_metadata.md#L21)):_
Didn't realise it was tabbed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3410)_

**Comment by livecodeali** [comment]
Reviewed 97 of 98 files at r1.
Review status: 95 of 97 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3410)_

**Comment by livecodeali** [comment]
Reviewed 1 of 98 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3410)_

**Comment by livecodeali** [comment]
Thanks for doing this!
@livecode-vulcan review ok 3c72ad0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3c72ad02b0aff05fcef2d51ffd7c062ac8dd47b8

**Comment by livecode-vulcan** [comment]
😎 test success 3c72ad02b0aff05fcef2d51ffd7c062ac8dd47b8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1467)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1487)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1463)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1474)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1486)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1487)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1489)

**Comment by peter-b** [comment]
@livecodeali I've added a couple of extra minor changes.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 331aa40

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 331aa40c7bab870a5f00f25fb293a5554bf7cc47

**Comment by livecode-vulcan** [comment]
😎 test success 331aa40c7bab870a5f00f25fb293a5554bf7cc47
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1469)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1489)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1465)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1476)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1488)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1489)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1491)

**Pull request merged**
