### PR TITLE
[[ UpdateCEF2526 ]] combined PR for Travis-CI

### PR DESCRIPTION
**Pull request by livecodeian**
DO NOT MERGE THIS PR
The individual PRs for livecode & livecode-thirdparty should be merged instead:
https://github.com/livecode/livecode/pull/3828
https://github.com/livecode/livecode-thirdparty/pull/57

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8578db2

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8578db2d18636b67df344c051a0780484457c48b

**Comment by livecode-vulcan** [comment]
😎 test success 8578db2d18636b67df344c051a0780484457c48b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2302)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2311)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2295)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2312)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2318)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2323)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2334)

**Comment by runrevmark** [comment]
Closing - merge https://github.com/livecode/livecode/pull/3828 and https://github.com/livecode/livecode-thirdparty/pull/57 instead.

**Pull request closed without merging**
