### PR TITLE
Merge release 6.7.8 07.12.15

### PR DESCRIPTION
**Pull request by livecodeali**
Merge release branch into develop 6.7

### CODE REVIEW

**Comment by livecodeali** [comment]
Self-review clean merge.
@livecode-vulcan review ok 5781d61

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 5781d61a4d2544b5d08f8e83baac44598c6b0336

**Comment by livecode-vulcan** [comment]
😞 test failure 5781d61a4d2544b5d08f8e83baac44598c6b0336
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1397)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1417)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1393)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1403)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1414)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1413)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1418)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 5781d61

**Comment by livecode-vulcan** [comment]
😞 test failure 5781d61a4d2544b5d08f8e83baac44598c6b0336
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1398)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1418)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1394)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1404)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1415)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1414)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1419)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 5781d61

**Comment by livecode-vulcan** [comment]
😎 test success 5781d61a4d2544b5d08f8e83baac44598c6b0336
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1399)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1419)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1395)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1405)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1416)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1415)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1420)

**Pull request merged**
