### PR TITLE
Color swatch widget for property inspector

### PR DESCRIPTION
**Pull request by runrevben**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 93c483f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 93c483f9dd35cc247dd5c8b1cd9ca41732be8860

**Comment by livecode-vulcan** [comment]
😞 test failure 93c483f9dd35cc247dd5c8b1cd9ca41732be8860
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/404)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/466)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/350)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/415)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/350)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/341)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 93c483f

**Comment by livecode-vulcan** [comment]
😎 test success 93c483f9dd35cc247dd5c8b1cd9ca41732be8860
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/462)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/521)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/408)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/473)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/408)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/399)

**Pull request merged**
