### PR TITLE
[[ RevPDFPrinter ]] Add Android support to revpdfprinter library

### PR DESCRIPTION
**Pull request by livecodeian**
This patch adds support for the Android platform to the revpdfprinter library, allowing the `open printing to pdf ...` command to be used to redirect printing output to a PDF file on Android devices.

*Note*: This PR depends on https://github.com/livecode/livecode-thirdparty/pull/139

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 682672c

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 682672c457e3b3bdbb1c81584f53301d47846846

**Comment by livecode-vulcan** [comment]
😞 test failure 682672c457e3b3bdbb1c81584f53301d47846846

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/673)
* try-community-armv7-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/82)
* try-community-arm64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/82)
* try-community-x86-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/82)
* try-community-x86_64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/82)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2199)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/33)
* try-community-universal-ios-iphonesimulator13.1: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/33)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2228)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2215)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2214)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2248)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2188)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 682672c

**Comment by livecode-vulcan** [comment]
😞 test failure 682672c457e3b3bdbb1c81584f53301d47846846

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/675)
* try-community-armv7-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/84)
* try-community-arm64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/84)
* try-community-x86-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/84)
* try-community-x86_64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/84)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2201)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/35)
* try-community-universal-ios-iphonesimulator13.1: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/35)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2230)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2217)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2216)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2250)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2190)

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 769025b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 769025b9b7b4aaaf8fe563f00ac6f216ee579d51

**Comment by livecode-vulcan** [comment]
😞 test failure 769025b9b7b4aaaf8fe563f00ac6f216ee579d51

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/676)
* try-community-armv7-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/85)
* try-community-arm64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/85)
* try-community-x86-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/85)
* try-community-x86_64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/85)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2202)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/36)
* try-community-universal-ios-iphonesimulator13.1: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/36)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2231)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2218)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2217)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2251)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2191)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 769025b

**Comment by livecode-vulcan** [comment]
😎 test success 769025b9b7b4aaaf8fe563f00ac6f216ee579d51

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/677)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/86)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/86)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/86)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/86)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2203)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/37)
* try-community-universal-ios-iphonesimulator13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/37)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2232)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2219)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2218)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2252)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2192)

**Pull request merged**
