### PR TITLE
added borderWidth as a synonym for lineSize, penHeight and penWidth for ...

### PR DESCRIPTION
**Pull request by montegoulding**
...graphics as it is for all other objects

### CODE REVIEW

**Comment by runrevmark** [comment]
Playing devil's advocate here - is there any particular reason this is useful? After all, isn't 'lineSize' the best description of the property from the point of view of a graphic?

**Comment by montegoulding** [comment]
On 30/04/2013, at 12:56 AM, runrevmark notifications@github.com wrote:

> Playing devil's advocate here - is there any particular reason this is useful? After all, isn't 'lineSize' the best description of the property from the point of view of a graphic?

I like consistency and I don't like the current behavior of there being no error thrown for borderWidth but it not actually doing anything. It just makes sense that these properties are all synonyms everywhere.

**Comment by runrevmark** [comment]
Actually, setting the borderWidth of a graphic does have an effect (now that I've drilled into the code more) - it's just that the 'showBorder' property of graphics is (by default) false. Graphic objects can have borders just like all other objects and this is distinct from the presentation properties of the graphic.

The borderWidth is stored in 'borderwidth' in MCObject, the lineSize is stored in 'linewidth' in MCGraphic.

**Comment by montegoulding** [comment]
Ah... ok then, close this one

**Comment by runrevmark** [comment]
Sure - closed as requested.

**Pull request closed without merging**
