### PR TITLE
[[ Bug 17754 ]] Actually copy mergExt externals into standalones

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok e9d4be7

**Comment by livecodeali** [comment]
I'm hoping @montegoulding meant
@livecode-vulcan review by @montegoulding ok 7696cfb

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 7696cfbd2911dd7f8b4f6c3605c22cb9fc438e84

**Comment by livecode-vulcan** [comment]
😎 test success 7696cfbd2911dd7f8b4f6c3605c22cb9fc438e84
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2578)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2588)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2573)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2589)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2595)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2599)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2611)

**Comment by montegoulding** [comment]
Whoops... Sorry

**Pull request merged**
