### PR TITLE
Get revbrowser building on Linux again

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 258d42d

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 258d42d513548f8b01df4d1c7c117822f6e8f968

**Comment by livecode-vulcan** [comment]
😞 test failure 258d42d513548f8b01df4d1c7c117822f6e8f968
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/306)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/368)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/250)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/317)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/252)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/242)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 258d42d

Windows build failure was caused by a missing prebuilt library file on our download server.

**Comment by livecode-vulcan** [comment]
😎 test success 258d42d513548f8b01df4d1c7c117822f6e8f968
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/309)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/372)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/254)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/320)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/255)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/245)

**Pull request merged**
