### PR TITLE
Hard wrap lcdoc files

### PR DESCRIPTION
**Pull request by montegoulding**
This patch wraps lcdoc files at 72 columns where
appropriate and orders lcdoc elements consistently
in all files. It also fixes some file naming
anomalies where `_` or ` `was used instead of`-`
for space or the filename did not include the entire
name.

Additionally this patch removes web as a platform due
to the confusion between the legacy browser plugin
and html5 which is listed as an OS.

---

This change is [Reviewable](https://reviewable.io/reviews/livecode/livecode/4271)

### CODE REVIEW

**Comment by peter-b** [comment]
@montegoulding: A couple of months ago, @livecodeali and I discussed a surprising behaviour in .lcdoc files whereby any line that just so happened to start with `word:` would be treated as the start of a key.  For example:

``` markdown
Description:
This is an example of some code which uses this command in a
feature:

    blah blah code goes here 
```

In this situation, the documentation builder detected the start of an .lcdoc key named `feature`, and truncated the description.

@livecodeali suggested that this problem could (mostly) be avoided if the documentation builder only treated `foo:` at the start of a line as a key iff preceded by an empty line.

Would this patch be a good opportunity to change the layout of the .lcdoc files in such a way that all "real" keys are preceded by a blank line?

**Comment by montegoulding** [comment]
@peter-b yes I can very easily add extra newlines between parameters. Would you like an additional newline after `Parameters:`?

**Comment by montegoulding** [comment]
@techstrategies was surprised by this just a few days ago BTW so it would be great to sort it out!

**Comment by montegoulding** [comment]
@peter-b it looks like I already have a newline between each parameter

**Comment by montegoulding** [comment]
I have amended the patch to apply quote markers to hard wrapped quotes `>`

**Comment by montegoulding** [comment]
My script hard wrapping needs some work 😞

**Comment by montegoulding** [comment]
@peter-b @livecodeali how would you feel about all elements being required to have a newline before and a newline after ":"

For example:

```
Name:
mobileStoreVerifyPurchase

Type:
command

Synonyms:
mobilePurchaseVerify

Syntax:
mobileStoreVerifyPurchase <purchaseID>, <verified>

Summary:
Confirm or reject a purchase in the unverified state.
...
```

**Comment by montegoulding** [comment]
The latest iteration should do slightly improved script wrapping. It is less strict about wrapping scripts and looks instead for better places to wrap. It also doesn't worry about wrapping single line examples because in many cases the example compilation test needs to fiddle with those as they are often function calls without get or put etc.

**Comment by montegoulding** [comment]
When we are ready to review this I will resolve conflicts at the last minute by resetting and running the script on the latest version of the docs. Ideally it will be merged in before the conference if we can.

**Comment by montegoulding** [comment]
@livecode-vulcan review by @livecodeali ok b4ba7d7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b4ba7d7fc56b436e7cf13187c532baa9ff507d94

**Comment by livecode-vulcan** [comment]
😎 test success b4ba7d7fc56b436e7cf13187c532baa9ff507d94
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/14)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/14)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/14)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/14)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/14)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/14)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/14)

**Pull request merged**
