### PR TITLE
[Bug 19212] Make sure calling [mobileComposeMail tSubject] does not crash

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok e53add2

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok e53add2a786731c0b991ba2c8402806a8d043466

**Comment by livecode-vulcan** [comment]
😎 test success e53add2a786731c0b991ba2c8402806a8d043466

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/898)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/904)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/896)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/897)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/904)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/895)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/895)

**Comment by livecodeali** [comment]
`MCStringIsEmpty` actually checks if the string is nil so there are lots of unnecessary checks in this code!

**Comment by runrevmark** [comment]
Hmmm - that might be true, however, I think that the current code is okay - there is a difference (as this code actually demonstrates) between nullptr and kMCEmptyString. It is probably best to make such explicit in the code.

**Comment by livecodeali** [comment]
Perhaps we should have an `MCStringIsEmpty` and an `MCOptionalStringIsEmpty` or something :-)

**Pull request merged**
