### PR TITLE
[Bug 11866] iphoneHeadingCalibrationTimeout returns empty

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
There looks to be something wrong here... This is a PR against 6.7, but the code is 7.0 architecture (use of MCExecContext etc.)...

**Comment by livecodepanos** [comment]
@runrevmark Indeed, but there is also a MCExecPoint. I double-checked and this code is in develop-6-7 branch. (The refactored code in develop-7.0 branch is in mblhandlers.cpp)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 92e8bff

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 92e8bff76f4d52a1072bfa1ffc6df4bd81e0b00c

**Comment by livecode-vulcan** [comment]
😎 test success 92e8bff76f4d52a1072bfa1ffc6df4bd81e0b00c
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/449)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/509)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/395)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/460)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/395)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/386)

**Comment by livecodesebastien** [comment]
I just tagged 6.7.7-rc-1 and started the dist build - but in case that first build is successful, this pull request can potentially be merged in, and the engines rebuilt.

**Pull request merged**
