### PR TITLE
[[ Documentation ]] Changes to mouseDoubleDown.lcdoc

### PR DESCRIPTION
**Pull request by asayd**
- Updated description of mouse button numbers.
- Added html5 as an OS.
- Corrected some references and added missing ones.
- Standardize on _Note:_ for block quoted notes.

### CODE REVIEW

**Comment by livecodeali** [comment]
@asayd Regarding the change from `Important` to `Note` - was there a particular reason to do this? I'm open to persuasion that this is merely a note rather than an important one. I think we have several different types of blockquote section floating around: Important, Note, Warning and Tip.

**Comment by asayd** [comment]
@livecodeali I guess I couldn't see how it differed from any other note. How does one make that determination? In the absence of a clear guideline, maybe the thing to do is leave them as is. Are there notes that aren't important? Warning and Tip seem a little easier to differentiate.

**Comment by livecodeali** [comment]
@asayd Yeah, I've just kept them as they were from before, but who knows how they were determined then...

**Comment by asayd** [comment]
@livecodeali  OK I think I'll leave the changes in the PR as they are if that's okay, and then going forward leave the note designations as they were before. FYI I had changed from Important: to Note: on a couple others as well, mouseDown and mouseUp I believe, before you noticed. :)

**Comment by ali** [comment]
> @ali OK I think I'll leave the changes in the PR as they are if that's okay, and then going forward leave the note designations as they were before. FYI I had changed from Important: to Note: on a couple others as well, mouseDown and mouseUp I believe, before you noticed. :)

@asayd it's probably better to mention @livecodeali here instead of me

**Comment by asayd** [comment]
Sorry, @ali. Typing too fast with my eyes closed. :-P

**Comment by livecodeali** [comment]
@asayd Hehe, OK, sounds good to me!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 7749ea5

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7749ea512f25680ec75f1a9dc3404d566d8d6006

**Comment by livecode-vulcan** [comment]
😎 test success 7749ea512f25680ec75f1a9dc3404d566d8d6006
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/406)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/411)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/406)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/406)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/412)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/406)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/406)

**Pull request merged**
