### PR TITLE
[[ Bug 15366 ]] Correctly update stack rectangle when moved

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 63dae5a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 63dae5a46b0cdcad494f3d71c3910ffb251ef076

**Comment by livecode-vulcan** [comment]
😎 test success 63dae5a46b0cdcad494f3d71c3910ffb251ef076
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2627)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2637)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2622)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2638)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2644)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2650)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2662)

**Comment by livecodepanos** [comment]
I am changing the milestone to 8.0.3 rc1, since 8.0.2 rc2 should contain only fixes for regressions introduced in 8.0.2 rc1

**Pull request merged**
