### PR TITLE
Ensure Windows debug symbols are preserved

### PR DESCRIPTION
**Pull request by livecodefraser**
WIP pending further testing locally.

### CODE REVIEW

**Comment by livecodefraser** [comment]
Seems to work in various build configurations on Windows. Will need a full installer build on Vulcan to verify though.

**Comment by peter-b** [comment]
@livecode-vulcan review ok ffee30b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ffee30b73a7faf81bfa74f5d6cde2e58103f287c

**Comment by livecode-vulcan** [comment]
😞 test failure ffee30b73a7faf81bfa74f5d6cde2e58103f287c
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2538)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/2548)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2533)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2549)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2555)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2559)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2571)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 6b69dd2

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6b69dd2058de24152e657d4dd9a0c5b24a2ee5bc

**Comment by livecode-vulcan** [comment]
😞 test failure 6b69dd2058de24152e657d4dd9a0c5b24a2ee5bc
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2544)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/2554)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2539)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2555)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2561)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2565)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2577)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 1ea812d

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 1ea812d10b67979d508994a6fb46d4411582acbb

**Comment by livecode-vulcan** [comment]
😞 test failure 1ea812d10b67979d508994a6fb46d4411582acbb
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2547)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/2557)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2542)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2558)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2564)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2568)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2580)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 2b4f12a

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 2b4f12a0131afeec8332f1dd57e31cab398d8b09

**Comment by livecode-vulcan** [comment]
😎 test success 2b4f12a0131afeec8332f1dd57e31cab398d8b09
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2550)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2560)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2545)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2561)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2567)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2571)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2583)

**Pull request merged**
