### PR TITLE
[[ Bug 10267 ]] Add HardwareAccelerated option in Android S/B

### PR DESCRIPTION
**Pull request by livecodesebastien**
Feature note added
revsaveasandroidstandalone.livecodescript update to take into account the new S/B setting
android-manifest.xml updated
ide submodule updated to point on the ide with the new S/B option

### CODE REVIEW

**Comment by livecodesebastien** [comment]
https://github.com/livecode/livecode-ide/pull/529 must be reviewed, and merged in.

**Comment by peter-b** [comment]
@livecode-vulcan review ok c015e6f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c015e6f8f63e54e7b054a49e683a3bacb415eb8d

**Comment by livecode-vulcan** [comment]
😎 test success c015e6f8f63e54e7b054a49e683a3bacb415eb8d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/553)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/559)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/554)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/553)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/561)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/559)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/563)

**Pull request merged**
