### PR TITLE
[[ Bug 15888 ]] UTF-8 encode the filename stored in the clipboard

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodesebastien: Have you checked this doesn't break windows/linux? I think MCLocalPasteboard is used on all platforms...

**Comment by livecodesebastien** [comment]
So, currently in `develop-7.0`, neither Windows or Linux work when following Trevor's recipe from the bug report.
This branch fixes Windows as long as the path is non-Unicode - there is more to be fixed anyway.

**Comment by runrevmark** [comment]
I'd check that the problem isn't in the clipboard <-> OS interconnect rather than in the LocalPasteboard.

Actually - you should probably get @livecodefraser to take a look - he's currently deep in the clipboard code implementing 'the rawClipboardData'.

**Comment by livecodesebastien** [comment]
I'll leave this on standby until @livecodefraser has finished his rework on the clipboard then.

**Comment by peter-b** [comment]
See also #2856.

**Comment by peter-b** [comment]
@livecodesebastien Since @livecodefraser's clipboard is now targeted only for LiveCode 8, am I right in thinking that this pull request is definitely needed? What is left to do with it?

**Comment by livecodefraser** [comment]
Yes, the new clipboard features are going into 8.

File paths for the OSX clipboard are URL-encoded UTF-8. Presumably, because the clipboard is 8-bit clean, most apps accept non-urlencoded paths without bother though.

For Windows, passing file paths is a bit more complicated, but the correct encoding is UTF-16.

On Linux, as with everything X11-related, the encoding is not specified. But the consensus amongst other programs and toolkits is the same as OSX: urlencoded UTF-8.

If Windows and Linux are already broken for non-ASCII paths and this patch doesn't break them any further, I'm happy to go with it. Working on one platform is better than no platforms!

**Comment by trevordevore** [comment]
I filed this original bug report on this. I'm actually moving my project to LC 8 (and skipping LC 7) so I would be happy to just get a fix in LC 8 for the time being.

**Comment by runrevmark** [comment]
@livecodefraser: Is this problem fixed in LC8?

**Comment by livecodesebastien** [comment]
Closing this PR as this is most likely fixed in 8, where the clipboard have been rewritten, and the fix is not right

**Pull request closed without merging**
