### PR TITLE
[[ Runrev references removal ]]

### PR DESCRIPTION
**Pull request by livecodesebastien**
Remove all references to RunRev, Runtime Revolution and Revolution in the text files.

https://github.com/runrev/livecode-ide/pull/439 must be reviewed as well, and merged it.

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 844 of 861 files at r1.
Review status: 844 of 861 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

<sup>**[builder/installer_utilities.livecodescript, line 1441 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-JxfiIHZ6962vDQA_TrS)** ([raw file](https://github.com/runrev/livecode/blob/1fa3d47b833297f260fa6abe32ca56698fc53489/builder/installer_utilities.livecodescript#L1441)):</sup>
I thought the plan was to back out the changes to the use of the `$HOME` directory in 6.7?

---

<sup>**[engine/rsrc/server.rc, line 24 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-JxfkHSFipmH6ayrigqo)** ([raw file](https://github.com/runrev/livecode/blob/1fa3d47b833297f260fa6abe32ca56698fc53489/engine/rsrc/server.rc#L24)):</sup>
Missing "L".

---

<sup>**[engine/src/dispatch.cpp, line 2066 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-JxfmkPOXjMuO7JSugnF)** ([raw file](https://github.com/runrev/livecode/blob/1fa3d47b833297f260fa6abe32ca56698fc53489/engine/src/dispatch.cpp#L2066)):</sup>
You shouldn't really edit bugfix comments! Don't worry about restoring the ones you've already modified.

---

<sup>**[engine/src/execpt.cpp, line 1175 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-JxfnFhopyI12cUk2d6c)** ([raw file](https://github.com/runrev/livecode/blob/1fa3d47b833297f260fa6abe32ca56698fc53489/engine/src/execpt.cpp#L1175)):</sup>
Random added whitespace. :wink: 

---

<sup>**[engine/src/graphicscontext.cpp, line 1 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-JxfolBXKfrJEqyoZjAq)** ([raw file](https://github.com/runrev/livecode/blob/1fa3d47b833297f260fa6abe32ca56698fc53489/engine/src/graphicscontext.cpp#L1)):</sup>
Is this file missing a copyright header entirely?

---

<sup>**[engine/src/graphicscontext.h, line 1 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-Jxfp8MV6BsAXkpQE0Zc)** ([raw file](https://github.com/runrev/livecode/blob/58b68be76363e48874c5ca13063b2a7d2dd67c07/engine/src/graphicscontext.h#L1)):</sup>
Might as well add the missing copyright header here.

---

<sup>**[libcore/include/sserialize.h, line 1 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-Jxg7eCjTBq240LwadaA)** ([raw file](https://github.com/runrev/livecode/blob/58b68be76363e48874c5ca13063b2a7d2dd67c07/libcore/include/sserialize.h#L1)):</sup>
This file needs a copyright header.

---

<sup>**[libcore/include/sserialize_w32.h, line 1 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-Jxg7xrCoU1vMpXtVjjO)** ([raw file](https://github.com/runrev/livecode/blob/58b68be76363e48874c5ca13063b2a7d2dd67c07/libcore/include/sserialize_w32.h#L1)):</sup>
This file needs a copyright header.

---

<sup>**[libcore/src/filesystem.cpp, line 1 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-Jxg82Gmf8iHT0Wt8FVi)** ([raw file](https://github.com/runrev/livecode/blob/58b68be76363e48874c5ca13063b2a7d2dd67c07/libcore/src/filesystem.cpp#L1)):</sup>
Copyright header etc.

---

<sup>**[libexternal/src/osxsupport.cpp, line 1 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-Jxg87eK2iTb9DfK4xzT)** ([raw file](https://github.com/runrev/livecode/blob/58b68be76363e48874c5ca13063b2a7d2dd67c07/libexternal/src/osxsupport.cpp#L1)):</sup>
No copyright header.

---

<sup>**[libexternal/src/w32support.cpp, line 1 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-Jxg8CtoXsqAFR55NatD)** ([raw file](https://github.com/runrev/livecode/blob/58b68be76363e48874c5ca13063b2a7d2dd67c07/libexternal/src/w32support.cpp#L1)):</sup>
No copyright header.

---

<sup>**[revvideograbber/src/qedit.h, line 1 [r1]](https://reviewable.io:443/reviews/runrev/livecode/2768#-JxgDztwmWLsbvqNKVvE)** ([raw file](https://github.com/runrev/livecode/blob/58b68be76363e48874c5ca13063b2a7d2dd67c07/revvideograbber/src/qedit.h#L1)):</sup>
Copyright header needed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/runrev/livecode/2768)

**Comment by peter-b** [comment]
Reviewed 844 of 861 files at r1.
Review status: 844 of 861 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/runrev/livecode/2768)

**Comment by livecodesebastien** [comment]
Pull request updated.

**Comment by peter-b** [comment]
Reviewed 6 of 861 files at r1, 30 of 30 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/runrev/livecode/2768)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 01ddb69

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 01ddb69189cb2f636b17b5be33f4dd08426878df

**Comment by livecode-vulcan** [comment]
😎 test success 01ddb69189cb2f636b17b5be33f4dd08426878df
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/153)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/151)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/151)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/151)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/154)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/151)

**Comment by livecodeali** [comment]
@livecodesebastien I've just noticed a couple of references to Revolution in the glossary that need changing

**Comment by livecodesebastien** [comment]
@livecodeali @runrevmark They are present in the glossary entries for `Revolution` and `Revolution custom library`, and they respectively have `LiveCode` and `LiveCode custom library` as synonyms; should we keep them for legacy, or remove them totally?

**Comment by livecodesebastien** [comment]
@livecodeali: I've updated the pull request, and removed the references to Revolution in the dictionary.

**Comment by mwieder** [comment]
Not sure it belongs as part of this pull request, but I just noticed that the 7.x message box has a checkbox in the pendingMessages card with the label "Show Revolution UI Messages'.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 69c440e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 69c440e524ffbe5be5c1f6b252918c93a588d660

**Comment by livecodesebastien** [comment]
@mwieder thank you for your input, we are not currently planning to update the binary stacks, but in case we come to doing it, we'll think about this one.

**Comment by livecode-vulcan** [comment]
😎 test success 69c440e524ffbe5be5c1f6b252918c93a588d660
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/260)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/258)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/260)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/256)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/263)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/258)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/264)

**Pull request merged**
