### PR TITLE
 [[ ExtensionUtils ]] Move code to validate package to extension utils

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 01b67d8

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 01b67d8a3f255fbb7217448281d7a8272825aba5

**Comment by livecode-vulcan** [comment]
😎 test success 01b67d8a3f255fbb7217448281d7a8272825aba5

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1333)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1349)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1323)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/276)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/274)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1327)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1353)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1333)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1347)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1332)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1342)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1383)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1323)

**Comment by montegoulding** [comment]
@livecodeali just merged this then noticed it's against develop but the ide PR is against release-9.0.0. Which did you want?

**Comment by livecodeali** [comment]
oops, meant to be release-9.0.0

**Pull request merged**
