### PR TITLE
[[ Bugfix 11133 ]] Implement faceless uninstaller

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Binary diff: https://gist.github.com/livecodesebastien/05666a9243719b28cf01

**Comment by peter-b** [comment]
@livecode-vulcan review ok 20e73d8

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 20e73d8d05718fdc7def16ce19717c0cd12bd2f2

**Comment by livecode-vulcan** [comment]
😎 test success 20e73d8d05718fdc7def16ce19717c0cd12bd2f2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/486)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/489)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/485)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/485)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/494)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/486)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/496)

**Pull request merged**
