### PR TITLE
[[ Bug 19973 ]] Allow binding to interface callbacks with non-void return

### PR DESCRIPTION
**Pull request by livecodeali**
- Allow interface callbacks to return a value
- Fix some incorrect bindings in android field widget
- Reinstate returnKey message in android field widget
- Add `passReturnKey` property to android field widget to control passing of return key event
- Ensure LCB handlers bound to void interface callback methods return nothing

### CODE REVIEW

**Comment by livecodeian** [comment]
@livecode-vulcan review ok 4819cfa

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeian ok 4819cfa00bd7b22f59bc9713cbe9408b93b8a455

**Comment by livecode-vulcan** [comment]
💥 merge conflict 4819cfa00bd7b22f59bc9713cbe9408b93b8a455 → bae7034c32a0fba6a324ff19b010a917f4ba880b

**Comment by livecodeian** [comment]
@livecode-vulcan review ok c0709a4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeian ok c0709a4c624829920b176770bb1ca0d763af40eb

**Comment by livecode-vulcan** [comment]
😎 test success c0709a4c624829920b176770bb1ca0d763af40eb

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/588)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/602)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/576)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/519)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/522)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/582)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/600)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/587)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/602)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/586)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/595)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/617)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/581)

**Pull request merged**
