### PR TITLE
[[ Prebuilt ]] Build Linux prebuilt libraries with position-independant code

### PR DESCRIPTION
**Pull request by livecodeian**
This patch enables the `-fPIC` option when compiling Linux prebuilt libraries, allowing those libraries to be used to create position-independent executables, which is now the default in the version of GCC provided with Ubuntu 18.04.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 17637ac

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 17637ace9b042ce34f825ead90c0ddf3d0dbe356

**Comment by livecode-vulcan** [comment]
😞 test failure 17637ace9b042ce34f825ead90c0ddf3d0dbe356

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/384)
* try-community-armv7-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/376)
* try-community-arm64-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/376)
* try-community-x86-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/376)
* try-community-x86_64-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/376)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1898)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/126)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/125)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1929)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1919)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1918)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1950)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1891)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 17637ac

**Comment by livecode-vulcan** [comment]
😞 test failure 17637ace9b042ce34f825ead90c0ddf3d0dbe356

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/386)
* try-community-armv7-android-sdk26_ndk16r15: [pending](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/378)
* try-community-arm64-android-sdk26_ndk16r15: [pending](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/378)
* try-community-x86-android-sdk26_ndk16r15: [pending](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/378)
* try-community-x86_64-android-sdk26_ndk16r15: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/378)
* try-community-js-emscripten-sdk1.35: [pending](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1900)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/128)
* try-community-universal-ios-iphonesimulator12.1: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/127)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1931)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1921)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1920)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1952)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1893)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 17637ac

**Comment by livecode-vulcan** [comment]
😎 test success 17637ace9b042ce34f825ead90c0ddf3d0dbe356

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/387)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/379)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/379)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/379)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/379)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1901)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/129)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/128)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1932)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1922)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1921)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1953)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1894)

**Comment by mwieder** [comment]
I can no longer build from source, as I'm getting linker errors on all the prebuilt libraries of the form

/usr/bin/ld: ../../prebuilt/lib/linux/x86_64/libpcre.a(pcre16_compile.o):
relocation R_X86_64_32S against `.rodata' can not be used when making a PIE
object; recompile with -fPIC

**Comment by mwieder** [comment]
Was this actually tested?
By adding my patches from https://github.com/livecode/livecode/pull/6897 after this. I'm able to compile the source again.

**Comment by montegoulding** [comment]
@mwieder you could feasibly have some stale thirdparty prebuilts. Try trashing them and rebuilding.

**Comment by mwieder** [comment]
Hmmm... "make clean-linux" trashes prebuilt/fetched, prebuilt/include, prebuilt/include, and prebuilt/lib. Is there maybe more work it should be doing?

**Comment by mwieder** [comment]
I got rid of everything in prebuilt/packed with the same results.

**Comment by montegoulding** [comment]
OK @livecodeian any thoughts on this?

**Comment by livecodeian** [comment]
@mwieder @montegoulding I did a test build at the weekend and got the same results as Mark. Investigating I realised the configuration for building thirdparty prebuilt libs didn't include the `-fPIC` flag so I've put together a PR that should fix the issue - #7032

**Pull request merged**
