### PR TITLE
[Bug 19584] Allow deletion of a message's target object in a frontscript

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 90b6d65

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 90b6d65363b5402e0331fb3a849d785254d549a6

**Comment by livecode-vulcan** [comment]
😞 test failure 90b6d65363b5402e0331fb3a849d785254d549a6

* try-community-armv6-android-api8: [failure](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/172)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/174)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/160)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/104)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/104)
* try-community-universal-mac-macosx10.6: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/170)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/174)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/174)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/178)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/174)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/178)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/198)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/171)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 78446c3

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 78446c397ecc933e1b8e2cd4683cbecbe6fb3af2

**Comment by runrevmark** [comment]
@livecode-vulcan review ok f95076f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok f95076fe6846613c00f4b3e0e07c6c2bbcd99fa7

**Comment by livecode-vulcan** [comment]
😞 test failure f95076fe6846613c00f4b3e0e07c6c2bbcd99fa7

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/175)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/177)
* try-community-js-emscripten-sdk1.35: [failure](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/163)
* try-community-universal-ios-iphoneos10.3: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/107)
* try-community-universal-ios-iphonesimulator10.3: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/107)
* try-community-universal-mac-macosx10.6: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/173)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/177)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/177)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/181)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/177)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/181)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/201)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/173)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok e85f355

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok e85f35513dcf60e76b6ba90c778ab6c49fbcc2fc

**Comment by runrevmark** [comment]
@livecode-vulcan review ok d22b7e9

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d22b7e9bad9d47e0b83f56c253b086a5c3bb063b

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 580b779

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 580b7794b0b8f33175ce82189df1b737ead0a856

**Comment by livecode-vulcan** [comment]
😞 test failure 580b7794b0b8f33175ce82189df1b737ead0a856

* try-community-armv6-android-api8: [pending](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/183)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/185)
* try-community-js-emscripten-sdk1.35: [failure](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/171)
* try-community-universal-ios-iphoneos10.3: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/115)
* try-community-universal-ios-iphonesimulator10.3: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/115)
* try-community-universal-mac-macosx10.6: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/181)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/185)
* try-community-x86-linux-debian7: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/185)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/189)
* try-community-x86_64-linux-debian7: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/185)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/189)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/209)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/180)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 5d5cc28

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 5d5cc28d1607a3afa24fa81ec55a5941070a49ab

**Comment by runrevmark** [comment]
@livecode-vulcan review ok c58c5b3

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok c58c5b36a7b7a57583e881db117426588d8fc003

**Comment by livecode-vulcan** [comment]
😞 test failure c58c5b36a7b7a57583e881db117426588d8fc003

* try-community-armv6-android-api8: [failure](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/185)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/187)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/173)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/117)
* try-community-universal-ios-iphonesimulator10.3: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/117)
* try-community-universal-mac-macosx10.6: [pending](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/183)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/187)
* try-community-x86-linux-debian7: [failure](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/187)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/191)
* try-community-x86_64-linux-debian7: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/187)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/191)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/211)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/181)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok f68efb5

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok f68efb54b0f08af5fb464efb063a7b3d3b4d3bce

**Comment by livecode-vulcan** [comment]
😎 test success f68efb54b0f08af5fb464efb063a7b3d3b4d3bce

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/186)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/188)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/174)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/118)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/118)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/184)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/188)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/188)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/192)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/188)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/192)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/212)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/182)

**Pull request merged**
