### PR TITLE
[[ Bug 18217 ]] Allow newer JDKs to be used for android builds

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 788f1a4

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 788f1a44a328491d0d8a9eed4d86b9229e32fa0a

**Comment by livecode-vulcan** [comment]
😎 test success 788f1a44a328491d0d8a9eed4d86b9229e32fa0a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/174)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/178)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/174)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/174)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/178)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/174)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/174)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 788f1a4

**Pull request merged**
