### PR TITLE
[[ iOS9.1 ]] Update for iOS 9.1

### PR DESCRIPTION
**Pull request by livecodesebastien**
Update the minimum iOS versions
Update the valid Xcode versions
Update tools/setup_xcode_sdk.sh
Update Makefile to build iOS9.1 instead of 9.0

### CODE REVIEW

**Comment by livecodesebastien** [comment]
https://github.com/livecode/livecode-ide/pull/585 needs to be reviewed and merged in as well (for the installers, on 6.7 only)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 6b2199d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6b2199dc5ccdc4266365f6c7d3883d7d5828f3ab

**Comment by peter-b** [comment]
@livecodesebastien Let's make sure the basic build works, then try the installer update.

Once this is merged, please immediately merge through to develop... because all auto builds will fail until then...!

**Comment by livecodesebastien** [comment]
No worries, that will be merged up as swiftly as I can!

**Comment by livecode-vulcan** [comment]
😎 test success 6b2199dc5ccdc4266365f6c7d3883d7d5828f3ab
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/832)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/846)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/833)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/836)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/846)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/856)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/849)

**Pull request merged**
