### PR TITLE
graph: Improve documentation.

### PR DESCRIPTION
**Pull request by peter-b**
Make sure properties are documented using consistent language and
terminology.  Add cross-references where appropriate.  Flesh out
the module-level description of the widget.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali I'm not sure this is quite right yet due to being unable to get "Related" or "References" keys to work in the module-level doc comment.

**Comment by peter-b** [comment]
Updated now that #3975 has been merged.  This should be ready to go.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 5adc394

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 5adc39467396e5510a6701d34b8a12dab48b2276

**Comment by livecode-vulcan** [comment]
😎 test success 5adc39467396e5510a6701d34b8a12dab48b2276
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2452)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2462)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2445)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2463)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2469)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2473)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2485)

**Pull request merged**
