### PR TITLE
[[ Community Docs ]] Specified that time is in epoch seconds

### PR DESCRIPTION
**Pull request by angerangel**
for the pendingMessages function. Moreover I switched from unordered list to numbered list, regarding the items of each line of the pendingMessages list.

### CODE REVIEW

**Comment by livecodeali** [comment]
@angerangel Thanks for this. There is one minor change needed - the return value type is not an enum, so this can just be removed. Otherwise the entry will not be formatted correctly. (It won't be formatted correctly anyway at the moment, until https://github.com/livecode/livecode-ide/pull/842 is merged)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 003d4ad

**Comment by peter-b** [comment]
@angerangel Thanks for making that tweak. Looks good to me. :+1:

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 003d4adf38a371af845586af796e9f5b3b7052ac

**Pull request merged**
