### PR TITLE
decrypt command enhancements

### PR DESCRIPTION
**Pull request by marksmithhfx**
- add encryption example 
- provide descriptions for parameters
- add < > brackets to most parameters in the description and to encrypt, decrypt and cipherNames... so they link
- fix miscellaneous typos
- wrapped long paragraph lines to 72 characters

### CODE REVIEW

**Comment by livecodeali** [comment]
Great, thanks @marksmithhfx!
@livecode-vulcan review ok 0a7ea15

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 0a7ea1548e7baa03678671a1a8365ccc13a4dbf8

**Comment by livecode-vulcan** [comment]
😎 test success 0a7ea1548e7baa03678671a1a8365ccc13a4dbf8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2492)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2502)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2485)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2503)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2509)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2513)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2525)

**Comment by peter-b** [comment]
@marksmithhfx Thanks for the patch!

**Comment by marksmithhfx** [comment]
Hi Peter, when I get the message

You’re all set—the marksmithhfx:patch-7 branch can be safely deleted.

Should I go ahead and delete it or just leave it there?

M

On May 12, 2016, at 7:24 AM, Peter TB Brett <notifications@github.com<mailto:notifications@github.com>> wrote:

Merged #4011https://github.com/livecode/livecode/pull/4011.

**Comment by peter-b** [comment]
@marksmithhfx That branch only exists in your copy of the livecode repository, so it's up to you!

When branches I've made in my own repository get merged into the official livecode repository, I usually go ahead and delete them, unless I expect to need to do some more work on that particular branch.  It saves cluttering up my copy of the livecode repository with branches that aren't needed any more.

**Comment by marksmithhfx** [comment]
Great, thanks.

On May 12, 2016, at 7:51 AM, Peter TB Brett <notifications@github.com<mailto:notifications@github.com>> wrote:

@marksmithhfxhttps://github.com/marksmithhfx That branch only exists in your copy of the livecode repository, so it's up to you!

When branches I've made in my own repository get merged into the official livecode repository, I usually go ahead and delete them, unless I expect to need to do some more work on that particular branch. It saves cluttering up my copy of the livecode repository with branches that aren't needed any more.

**Pull request merged**
