### PR TITLE
[[Docs]] keyword/segment - Link updates

### PR DESCRIPTION
**Pull request by seaniepie**
- Updated some of the links
- Modified the quotes and curved quotes

### CODE REVIEW

**Comment by livecodeali** [comment]
@seaniepie For additional linkage/markup could you put all the occurrences of `segment` in angle brackets, and make the occurrences of items, characters and lines links too please (i.e. `<item|items>` etc)?

**Comment by livecodeali** [comment]
@seaniepie I think the plural chunk types should mostly link to the singular chunk type entries, i.e. `<item|items>`, `<character|characters>` and `<line|lines>` since the plural form relates to the chunk types being used in conjunction with the `number of ...` construction.

**Comment by livecodeali** [comment]
@seaniepie Actually I've just noticed one other one, which is the occurrence of `<Segments>`. These are case-sensitive anyway, so it'll have to be changed - but I also think this should be `<segment|Segments>`

**Comment by livecodeali** [comment]
@seaniepie These comments also apply to https://github.com/livecode/livecode/pull/4668

**Comment by livecodeali** [comment]
@livecode-vulcan review ok fe2b8c0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok fe2b8c06102b8bac5af72f9fb5787ea4d0f18ccd

**Comment by livecode-vulcan** [comment]
😎 test success fe2b8c06102b8bac5af72f9fb5787ea4d0f18ccd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/445)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/450)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/445)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/445)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/451)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/445)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/445)

**Pull request merged**
