### PR TITLE
[[ Community Docs ]] Cancel command fixes

### PR DESCRIPTION
**Pull request by asayd**
- Corrected formatting of example embedded in Description element.
- Reviewed and updated links and references.
- Added a more complete example.
- Changed Tags element from objects to messages.

### CODE REVIEW

**Comment by livecodeali** [comment]
Thanks!
@livecode-vulcan review ok d25ffa0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok d25ffa0cb24366d4422ebbb6b15bcf3a6a7d9fb0

**Comment by asayd** [comment]
@livecodeali - I changed the Tags element to 'messages' as you suggested. That seems to be a new tag now. To make it more helpful I am thinking the following entries should also be tagged with 'messages':
- send _message_ in _time_
- pass command
- dispatch command
- call command
- pendingMessages function
- GLOSSARY:
  - message (?)
  - handler (?)

Thoughts? I don't want to willy-nilly start adding this new tag to other entries unless others think it's a good idea.

**Comment by livecode-vulcan** [comment]
😎 test success d25ffa0cb24366d4422ebbb6b15bcf3a6a7d9fb0
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2449)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2459)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2442)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2460)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2466)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2470)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2482)

**Comment by livecodeali** [comment]
Yeah, they all seem to be sensible suggestions to me.
Probably also
- lock and unlock messages commands
- message path glossary
- message order glossary

and maybe frontScripts/backScripts?

**Comment by asayd** [comment]
And possibly behavior? 
I'll works these in over the next few days.
Question: Is one big commit that fixes lots of things preferable to lots of little commits that each fix one thing? I tend to want to fix everything I can once I get into a .lcdoc.

**Comment by livecodeali** [comment]
Yes, behavior is a good idea. 

I think fixing everything in one lcdoc file in one commit is fine, as is fixing the same thing in multiple lcdoc files.

**Pull request merged**
