### PR TITLE
[[ Bug 19003 ]] Ensure stack file paths are relativized appropriately

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Tests are here: https://github.com/livecode/livecode-ide/pull/1496

**Comment by peter-b** [comment]
@livecode-vulcan review ok ccd5b03

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ccd5b03893a61114a691a6f2e73327eb216dfc44

**Comment by livecode-vulcan** [comment]
😎 test success ccd5b03893a61114a691a6f2e73327eb216dfc44

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/749)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/754)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/747)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/748)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/754)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/746)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/746)

**Pull request merged**
