### PR TITLE
iOS 10.2 / Xcode 8.2 support

### PR DESCRIPTION
**Pull request by livecodepanos**
This should be merged after being retested with Xcode 8.2 GM Seed (once this is available).

Currently I have tested with Xcode 8.2-beta

### CODE REVIEW

**Comment by livecodepanos** [comment]
I have now rebuilt and uploaded the openssl and icu prebuilts for iOS 10.2 using Xcode 8.2, so this PR can now be reviewed and merged.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay d9d2907

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok d9d29071702d94c2d1dde90feb6a46d6eca1ba2c

**Comment by livecodepanos** [comment]
Note: Do not merge this until we release 8.1.2 GM

**Comment by livecode-vulcan** [comment]
😞 test failure d9d29071702d94c2d1dde90feb6a46d6eca1ba2c

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/725)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/726)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/723)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/724)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/730)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/721)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/722)

**Comment by livecodeali** [comment]
@livecode-vulcan retry d9d2907

**Comment by livecode-vulcan** [comment]
😞 test failure d9d29071702d94c2d1dde90feb6a46d6eca1ba2c

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/780)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/785)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/778)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/779)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/785)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/777)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/777)

**Comment by livecodeali** [comment]
@livecode-vulcan retry d9d2907

**Comment by livecode-vulcan** [comment]
😎 test success d9d29071702d94c2d1dde90feb6a46d6eca1ba2c

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/785)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/790)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/783)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/784)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/790)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/782)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/782)

**Pull request merged**
