### PR TITLE
[Bug 13992] Fixed bug causing crash on mouseEnter

### PR DESCRIPTION
**Pull request by abrisan**
One step closer to a * free world

### CODE REVIEW

**Comment by livecodepanos** [comment]
Added [NO MERGE] to the title until we find out why vulcan did not check this PR

**Comment by montegoulding** [comment]
Seems to be not responding on this PR too https://github.com/livecode/livecode/pull/5973

**Comment by livecodepanos** [comment]
Yay! Removing [NO MERGE] now

**Comment by livecodeali** [comment]
This looks right to me. Two minor things: 
1) Could you change the occurrences of `static_cast<MCGroup *>(tptr.Get())` to `tptr.GetAs<MCGroup>()`
2) Please add a release note!
I'm not going to ask you about adding a test as it doesn't seem like it's remotely possible here ;-)

**Comment by abrisan** [comment]
@livecodeali I think I addressed all the comments

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 831585a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 831585a014d2b491e6942abc0e015672764908a1

**Comment by livecode-vulcan** [comment]
😎 test success 831585a014d2b491e6942abc0e015672764908a1

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/876)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/892)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/866)
* try-community-universal-ios-iphoneos11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.0/builds/41)
* try-community-universal-ios-iphonesimulator11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.0/builds/42)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/870)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/892)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/876)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/892)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/875)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/885)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/907)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/871)

**Pull request merged**
