### PR TITLE
[[ Bug 17802 ]] Document how to escape special chars in filter patterns

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by runrevmark** [comment]
@montegoulding: I wonder if this would  be clearer if we listed 'how to match' special chars, just like we list how to use special chars. At the moment the new paragraph is a little difficult to read and work out what you should do if you want to match '[' or ']', for example:

```
You can match instances of special chars as follows:
   - [ - [[]
   - ] - ]
```

etc.

**Comment by montegoulding** [comment]
OK @runrevmark I will lit it like that. I agree it is clearer and I struggled to come up with a coherent paragraph on this...

**Comment by peter-b** [comment]
@livecode-vulcan review ok ade7966

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ade796644e1f48aa75fe02914bd5d8550bc27daa

**Comment by livecode-vulcan** [comment]
😎 test success ade796644e1f48aa75fe02914bd5d8550bc27daa
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2699)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2709)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2694)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2710)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2716)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2722)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2734)

**Pull request merged**
