### PR TITLE
Docs contributing

### PR DESCRIPTION
**Pull request by alextweedly**

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @alextweedly, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 5180bda

**Comment by peter-b** [comment]
@alextweedly Thank you for the patch!

**Comment by peter-b** [comment]
@alextweedly In future, could you please ensure that your pull requests have an informative title/description, e.g. "Tweak community docs command line instructions"?

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 5180bdae4502e14d3860174bd8fbd60f800ef46a

**Comment by livecode-vulcan** [comment]
😎 test success 5180bdae4502e14d3860174bd8fbd60f800ef46a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2303)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2312)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2296)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2313)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2319)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2324)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2335)

**Pull request merged**
