### PR TITLE
Add thirdparty lib support to android externals

### PR DESCRIPTION
**Pull request by montegoulding**
This PR is just a request for comment at this stage. It's untested but looks like it will work fine to me. The main thing I want comment on is the future proofing I've done to support multiple architectures. See my use of the kArchs constant which is intended to be a list of words. I'm wondering if perhaps this would be a user selection like on iOS and therefore the list would be better passed as a parameter to addExternalFromFile?

### CODE REVIEW

**Comment by peter-b** [comment]
@montegoulding Thanks for this -- definitely something that's needed!  To make things more consistent, could you please apply the same rules to writing pull requests as to writing commit messages (i.e. descriptive one-line title, with a longer descriptive body explaining what the pull request aims to achieve)?  It makes it much easier to review...!

**Comment by montegoulding** [comment]
Were there any thoughts on this? I'd like to complete this, document and test soonish

**Comment by peter-b** [comment]
@montegoulding: I don't have any particular thoughts about it -- I was hoping that @runrevmark or @livecodefraser would chime in.

**Comment by runrevmark** [comment]
@montegoulding: I would have some thoughts - but I must confess I'm not entirely clear what the patch is intended to do... If you could explain the problem it is trying to solve and an example use-case I can probably develop some comments quite quickly ;)

**Comment by peter-b** [comment]
This is an example of how more detailed/explanatory commit messages and pull request description would help a lot. :wink:

**Comment by montegoulding** [comment]
;-) Basically it adds any libraries native or jar included in the external to the appropriate directory.

**Comment by runrevmark** [comment]
@montegoulding: Well, if you are happy it works (I presume you've tested it with an example) then it looks like a perfectly plausible patch :)

**Comment by runrevmark** [comment]
It looks like it should work - but I want to hold off merging it in until after dp-8 - just in case it does break something ;)

@livecode-vulcan review ok ca14b5f

**Comment by montegoulding** [comment]
I still need to do some more testing on it. Actually if you notice I have a question on the engine forum about getting setup for android... it's changed with the gypification it seems. The main thing I needed feedback on was on the future proofing.

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok ca14b5f2bb641d1bbbfa75332e725208cda2cc86

**Comment by livecode-vulcan** [comment]
😎 test success ca14b5f2bb641d1bbbfa75332e725208cda2cc86
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/862)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/876)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/863)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/866)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/876)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/886)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/879)

**Comment by peter-b** [comment]
It's now "after dp-8".

**Comment by livecodeali** [comment]
This causes android building to fail in DP 9 due to the 'conatant' typo.

**Comment by montegoulding** [comment]
Yeah, still working on the external to test it. Sorry about that. Was it merged? Must have missed the email.

**Comment by peter-b** [comment]
Yes, it was merged for DP9. If you submit a pull request we'll usually merge it if it's not obviously broken and doesn't have "WIP" or "needs" labels.

**Comment by montegoulding** [comment]
Aha, well I didn't know about the WIP thing but the PR said it was just a request for comment at this stage.

**Pull request merged**
