### PR TITLE
[[ Bugfix 15646 ]] Fix memory leaks...

### PR DESCRIPTION
**Pull request by livecodesebastien**
...when putting text into a variable's chunk of text.

### CODE REVIEW

**Comment by livecodeali** [comment]
The ImageRep memory leak is already fixed in develop-6.7:
https://github.com/runrev/livecode/pull/2572/files

**Comment by livecodesebastien** [comment]
Nice - I'll revert c72be8a in this branch, and maybe merge #2572 (as it is a safe bug fix).

**Comment by livecodeali** [comment]
Do you want to maybe reset the branch and re-commit and force push so that this is just the one commit?

**Comment by livecodesebastien** [comment]
You're right, that would be a nicer pull request :)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b380490

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b380490dd6f47112c7445b3cb4ac2b61c5680306

**Comment by livecode-vulcan** [comment]
😎 test success b380490dd6f47112c7445b3cb4ac2b61c5680306
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/658)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/718)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/607)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/671)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/603)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/596)

**Pull request merged**
