### PR TITLE
[Bug 13820] Extended dontUseQT player property for OSX

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevpanos, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 9e32d2a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 9e32d2a731c6fa8ef3df3e5a84f60b1a98c6bfb7

**Comment by livecode-vulcan** [comment]
😎 test success 9e32d2a731c6fa8ef3df3e5a84f60b1a98c6bfb7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/213)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/212)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/213)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/208)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/215)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/213)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/216)

**Pull request merged**
