### PR TITLE
[[ Bugfix 16363 ]] Close menus when a click occurs outside

### PR DESCRIPTION
**Pull request by livecodefraser**
Basically, I was checking the wrong mouse coordinates...

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 5b01322

**Comment by livecodefraser** [comment]
@livecode-vulcan review by @runrevmark okay 5b10322

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 5b103222a5a8df94b9e8601b3b012f99528c851a

**Comment by livecode-vulcan** [comment]
😎 test success 5b103222a5a8df94b9e8601b3b012f99528c851a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1437)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1457)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1433)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1443)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1455)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1455)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1459)

**Pull request merged**
