### PR TITLE
[Bug 7769] Allow relative img references with rotate command (i.e. last image/ first image)

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@runrevpanos: I wonder if it would be better here to allow the rotate command to parse an arbitrary chunk, and then make it a runtime error if that chunk does not resolve as an image. i.e. Don't check for 'image' before parsing chunk, just parse a chunk and add validation to exec.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok f776187

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok f77618728d2e8a349b7564d2880e5a28c8edca99

**Comment by livecode-vulcan** [comment]
😎 test success f77618728d2e8a349b7564d2880e5a28c8edca99
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/5)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/5)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/5)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/5)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/5)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/5)

**Comment by livecodepanos** [comment]
Hi @runrevmark, I added another one commit that handles the case where no image is specified (i.e. 'rotate [by] 90'. Could you please re-review?

**Comment by runrevmark** [comment]
This is a bit tricky - the update doesn't actually cover the current syntax which is 'rotate [by] EXPR' where EXPR can be any valid expression (which problematically look exactly like chunks!). I'm not sure the best way to resolve this at present - I suspect flip / crop suffer the same problem... Any of the image editing commands which can target both the image currently being edited or a given image will suffer the same problem (and this is probably why the target syntax was restricted to chunks beginning with 'image' to begin with!).

**Comment by livecodeali** [comment]
Flip is ok I think because it doesn't have any additional expressions - it just expects either "vertical" or "horizontal"

**Comment by livecodepanos** [comment]
Yes I agree Flip should be ok

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevpanos, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodefraser** [comment]
Closing as this fix causes parsing ambiguities.

**Pull request closed without merging**
