### PR TITLE
[[ Bug 15642 ]] Add bugfix note - fix is in the thirdparty submodule

### PR DESCRIPTION
**Pull request by livecodesebastien**
Pull request https://github.com/runrev/livecode-thirdparty/pull/26 needs to be merged in.

### CODE REVIEW

**Comment by runrevmark** [comment]
Did you update the submodule pointer here? (Only the release note is in the commit history)

**Comment by livecodesebastien** [comment]
No, I was planning to do it manually after the merge in thrirdparty (so that the submodule points to the commit of the merge, not the last commit of the branch merged in)

**Comment by livecodesebastien** [comment]
Auto-reviewing, as this only adds the bugfix note (the bug fix has been reviewed and merged in, see first comment).
@livecode-vulcan review ok 4be0e59

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 4be0e591e98f9fdac3454da47bf0836aa53fcedb

**Comment by livecode-vulcan** [comment]
⁉ merge unchanged 4be0e591e98f9fdac3454da47bf0836aa53fcedb → 90e5129137b125508cb665e36ed1ed4c5a685d8b

Pull request is already fully merged!

**Pull request merged**
