### PR TITLE
Update version file for 8.0.2-rc-1

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok f6a8dcc

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok f6a8dccde54167802cead88d74e90c2355d37ea8

**Comment by livecode-vulcan** [comment]
😞 test failure f6a8dccde54167802cead88d74e90c2355d37ea8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2521)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2531)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2516)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2532)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2538)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2542)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2554)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry f6a8dcc

**Comment by livecode-vulcan** [comment]
😎 test success f6a8dccde54167802cead88d74e90c2355d37ea8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2523)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2533)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2518)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2534)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2540)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2544)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2556)

**Pull request merged**
