### PR TITLE
[[ Guides ]] Move guides from ide repo and from monolithic Extending LiveCode guide to engine repo

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
Awesome :sparkles: 

@livecode-vulcan review ok 3268a27

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3268a27fcebe4720b5f352bbddf715f7db11282f

**Comment by livecode-vulcan** [comment]
😎 test success 3268a27fcebe4720b5f352bbddf715f7db11282f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1466)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1486)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1462)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1473)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1485)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1486)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1488)

**Comment by livecodeali** [comment]
Corresponding removal PR: https://github.com/livecode/livecode-ide/pull/731

**Comment by peter-b** [comment]
@livecode-vulcan review ok 742fc03

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 742fc03e16e85e9db81bfc8e6b992bc1c9910124

**Comment by livecode-vulcan** [comment]
😎 test success 742fc03e16e85e9db81bfc8e6b992bc1c9910124
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1487)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1506)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1483)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1494)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1506)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1507)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1509)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 273fce6

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 273fce62980f4d34bc86747ee408b224fab51d13

**Comment by livecode-vulcan** [comment]
😎 test success 273fce62980f4d34bc86747ee408b224fab51d13
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1491)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1510)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1487)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1498)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1510)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1511)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1513)

**Pull request merged**
