### PR TITLE
[[ Bug 20293 ]] Fixed bug that causes crash with bad range chunk

### PR DESCRIPTION
**Pull request by abrisan**

### CODE REVIEW

**Comment by abrisan** [comment]
This is a duplicate of https://github.com/livecode/livecode/pull/6308. Rebasing was too much of a pain, so I cherry-picked the commit into develop-8.1.

@runrevmark I'll close the other PR, please review this one.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 384012b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 384012ba9cc2b08f7bc429cd4daa58ecefd17762

**Comment by livecode-vulcan** [comment]
😎 test success 384012ba9cc2b08f7bc429cd4daa58ecefd17762

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1177)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1193)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1167)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/120)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/120)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1172)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1197)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1177)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1193)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1176)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1186)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1215)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1171)

**Pull request merged**
