### PR TITLE
Update OpenSSL to 1.1.0c and libcurl to 7.51.0

### PR DESCRIPTION
**Pull request by livecodefraser**
Requires some changes in the thirdparty repo: https://github.com/livecode/livecode-thirdparty/pull/81

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4d6573a

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4d6573a77cecb41e15a9d792d629a9125fbed92b

**Comment by livecode-vulcan** [comment]
😞 test failure 4d6573a77cecb41e15a9d792d629a9125fbed92b
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/579)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/584)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/579)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/583)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/588)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/580)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/580)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 4d6573a

**Comment by livecode-vulcan** [comment]
😞 test failure 4d6573a77cecb41e15a9d792d629a9125fbed92b
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/580)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/585)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/580)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/584)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/589)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/581)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/581)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 4d6573a

**Comment by livecode-vulcan** [comment]
😞 test failure 4d6573a77cecb41e15a9d792d629a9125fbed92b
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/581)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/586)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/581)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/585)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/590)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/582)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/582)

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok d472b8c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok d472b8c9f66774e79a70e50103d9022d3ab7e79e

**Comment by livecode-vulcan** [comment]
😞 test failure d472b8c9f66774e79a70e50103d9022d3ab7e79e
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/582)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/587)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/582)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/586)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/591)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/583)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/583)

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 524f222

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 524f222ebb2715bfacf3102104d586fa69eb0f76

**Comment by livecode-vulcan** [comment]
😞 test failure 524f222ebb2715bfacf3102104d586fa69eb0f76
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/583)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/588)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/583)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/587)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/592)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/584)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/584)

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 23e217a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 23e217ab3f72c44c15057f3637150886827aa0ea

**Comment by livecode-vulcan** [comment]
😞 test failure 23e217ab3f72c44c15057f3637150886827aa0ea
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/587)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/592)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/587)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/591)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/596)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/588)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/588)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 23e217a

**Comment by livecode-vulcan** [comment]
😎 test success 23e217ab3f72c44c15057f3637150886827aa0ea
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/588)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/593)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/588)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/592)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/597)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/589)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/589)

**Pull request merged**
