### PR TITLE
[Bug 14929] com.livecode.engine: Make "send" return "optional any"

### PR DESCRIPTION
**Pull request by peter-b**
It's possible for a command not to return anything.

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevmark I'm not sure if this covers exactly what was described by the bug report -- is this pretty much what you intended?

**Comment by runrevmark** [comment]
@peter-b: I'm not sure I quite remember _exactly_ what I intended... However, I suspect it was the fact that send should return nothing if the message was unhandled / passed.

**Comment by runrevmark** [comment]
@peter-b: It should probably also explicitly clear the result before the dispatch... And then use the logic you have as well (so that 'nothing' is returned if the handler executed didn't use 'return')

**Comment by peter-b** [comment]
@runrevmark Updated the pull request.  Does this need a release note?

**Comment by runrevmark** [comment]
@livecode-vulcan review ok e1237a5

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok e1237a50b19966131a72869ae67bd3d1bf859fd1

**Comment by livecode-vulcan** [comment]
😎 test success e1237a50b19966131a72869ae67bd3d1bf859fd1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1114)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1124)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1111)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1117)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1128)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1132)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1133)

**Pull request merged**
