### PR TITLE
Bump version to 8.0.1-rc-1.

### PR DESCRIPTION
**Pull request by peter-b**
- Don't merge until _after_ forking the `release-8.0.0` branch.
- The build number is a placeholder and will need to be tweaked once we find out how many 8.0.0 RC releases are needed.

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 4864204

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 48642042a6cfa6fa4efc74ba78a1866f7be9c45b

**Comment by livecode-vulcan** [comment]
😞 test failure 48642042a6cfa6fa4efc74ba78a1866f7be9c45b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2393)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2403)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2386)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2404)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2410)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2414)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2426)

**Comment by peter-b** [comment]
@livecode-vulcan retry 4864204

**Comment by livecode-vulcan** [comment]
😎 test success 48642042a6cfa6fa4efc74ba78a1866f7be9c45b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2394)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2404)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2387)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2405)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2411)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2415)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2427)

**Pull request merged**
