### PR TITLE
Make possible to 'put "x" before msg', without replacing the contents of msg with x

### PR DESCRIPTION
**Pull request by livecodepanos**
i.e. it is similar with 'put "x" into msg.

### CODE REVIEW

**Comment by runrevmark** [comment]
I suggest refactoring prepend_string and append_string so that they use an operation:

```
bool insert_string(const MCString& string_to_insert, int insert_at);
```

Then:

prepend_string == insert_string(string, 0)
append_string == insert_string(string, length(targetstring))

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevpanos, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 8aa95d0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 8aa95d033acd2a8ec1b2f3822b7fefa853354c17

**Comment by livecode-vulcan** [comment]
😎 test success 8aa95d033acd2a8ec1b2f3822b7fefa853354c17
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/214)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/213)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/214)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/209)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/216)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/214)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/217)

**Pull request merged**
