### PR TITLE
[Bug 16260] Document the "deleteWidget" message.

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by runrevelanor** [comment]
@livecode-vulcan review ok 6ff014f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevelanor ok 6ff014f72f19d494fa7a25d86e3087d165494e0c

**Comment by runrevelanor** [comment]
@livecode-vulcan review ok 0020842

**Comment by livecode-vulcan** [comment]
💙 review by @runrevelanor ok 00208427fec1d39dea369f864dacc5de5960d0f8

**Comment by livecode-vulcan** [comment]
😎 test success 00208427fec1d39dea369f864dacc5de5960d0f8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2133)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2141)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2126)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2141)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2148)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2154)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2164)

**Pull request merged**
