### PR TITLE
Update mergExt pointer

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok a78f895

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a78f8957cd67add3d752ce5e7229f9f696e211ba

**Comment by livecode-vulcan** [comment]
😎 test success a78f8957cd67add3d752ce5e7229f9f696e211ba
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2528)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2538)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2523)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2539)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2545)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2549)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2561)

**Comment by peter-b** [comment]
@livecode-vulcan retry a78f895

**Comment by livecode-vulcan** [comment]
😎 test success a78f8957cd67add3d752ce5e7229f9f696e211ba
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2535)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2545)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2530)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2546)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2552)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2556)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2568)

**Pull request merged**
