### PR TITLE
[[ LegacyExec ]] Remove LEGACY_EXEC and OLD_EXEC blocks

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
I've reviewed about as much of this as is probably worth reviewing - I haven't seen anything that's gone wrong so I'm happy to mark reviewed.
@livecode-vulcan review ok 8426332

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 84263321236e42cefd6007091a99db93295f581c

**Comment by montegoulding** [comment]
Thanks @livecodeali

**Comment by livecode-vulcan** [comment]
😎 test success 84263321236e42cefd6007091a99db93295f581c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2592)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2602)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2587)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2603)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2609)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2615)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2627)

**Pull request merged**
