### PR TITLE
 [[ Bug 20570 ]] Fix MySQL errors after calling stored procedures

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 597054b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 597054bd8d5e6c9922465d16a3489a3f44d0f221

**Comment by livecode-vulcan** [comment]
😎 test success 597054bd8d5e6c9922465d16a3489a3f44d0f221

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1443)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1459)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1433)
* try-community-universal-ios-iphoneos11.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.3/builds/36)
* try-community-universal-ios-iphonesimulator11.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.3/builds/36)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1437)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1463)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1443)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1457)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1442)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1452)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1492)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1432)

**Comment by livecodepanos** [comment]
This PR is replaced by https://github.com/livecode/livecode/pull/6517

**Pull request closed without merging**
