### PR TITLE
[Bug 20183] Ensure import paint into group respects the (parent) group

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
As `import paint` is in the Interface module, I would create a new test script `import.livecodescript` in `core/interface` for this.

Also, instead of using `the last group` etc (which is contingent on layer order), just to be clear I would use `it`, eg
```
local tTargetGroup
create group
put it into tTargetGroup
...
```
Ok, I've just checked and `import paint` doesn't set `it` to the long id of the newly created image! So, if you have time, it would probably be good to fix that and then use 
```
local tImportedImage
import paint from file tImageFilenameFullPath in tTargetGroup
put it into tImportedImage
...
```

**Comment by livecodepanos** [comment]
Thanks @livecodeali, ok I'll add this, so I am setting this to WIP for now

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 6feddd4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 6feddd42fa2166ae56f54a6c67d6d4140d69e1de

**Comment by livecode-vulcan** [comment]
😎 test success 6feddd42fa2166ae56f54a6c67d6d4140d69e1de

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/562)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/577)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/551)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/494)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/497)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/557)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/575)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/561)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/577)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/560)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/570)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/592)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/556)

**Pull request merged**
