### PR TITLE
[Bug 6506] Fix regression to global watched variables

### PR DESCRIPTION
**Pull request by montegoulding**
Not sure about milestone for this as it should probably be 8.2 given the new version numbering scheme.

### CODE REVIEW

**Comment by peter-b** [comment]
@montegoulding: Since this is a bug fix could you please rebase onto the `develop-8.1` branch?  Thanks!

**Comment by montegoulding** [comment]
yes, sure thing

**Comment by peter-b** [comment]
@montegoulding For future reference, when cherry-picking please use `git cherry-pick -x`.  This includes the SHA-1 of the original commit into the newly created copy, and ensures that we can always trace back a change to find the set of changes that it started from.

**Comment by peter-b** [comment]
@livecode-vulcan review ok dbc65d0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok dbc65d074c6693a52c5495334956f3b3d03cbd79

**Comment by livecode-vulcan** [comment]
😎 test success dbc65d074c6693a52c5495334956f3b3d03cbd79
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/384)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/389)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/384)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/384)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/390)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/384)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/384)

**Comment by montegoulding** [comment]
Will try and remember @peter-b... you would think that could have just been the default behaviour

**Pull request merged**
