### PR TITLE
Turn on -Werror=missing-declarations

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 0ad5cd9

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 0ad5cd911a6bc4c5e226f1626d514abd45abf335

**Comment by livecode-vulcan** [comment]
😞 test failure 0ad5cd911a6bc4c5e226f1626d514abd45abf335
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/171)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/175)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/171)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/171)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/175)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/171)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/171)

**Comment by montegoulding** [comment]
Ah... I'll test all these PRs against iOS as obviously the iOS config is based on Mac

**Comment by montegoulding** [comment]
No it's a signing issue. I think develop-8.0 needs to be merged over so I can rebase on it

**Comment by peter-b** [comment]
@montegoulding I'll get the branches merged up ASAP.

**Comment by peter-b** [comment]
@livecode-vulcan retry 0ad5cd9

**Comment by livecode-vulcan** [comment]
💥 merge conflict 0ad5cd911a6bc4c5e226f1626d514abd45abf335 → b877d3d8e0daf4b65ad56f03a61eba66b43f1f33

**Comment by montegoulding** [comment]
@livecode-vulcan review by @runrevmark ok df5d68c

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok df5d68ce188e8d06c2cba217b1d425d818a83179

**Comment by livecode-vulcan** [comment]
😎 test success df5d68ce188e8d06c2cba217b1d425d818a83179
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/182)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/186)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/182)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/182)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/186)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/182)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/182)

**Pull request merged**
