### PR TITLE
[[ Bug 19050 ]] Use SCRIPT_FILENAME to get CGI script path

### PR DESCRIPTION
**Pull request by livecodesebastien**
The engine was altering PATH_TRANSLATED to find the script path, assuming that
PATH_TRANSLATED was built on <script path>/<path info>, where it actually should
be <server document root>/<path info>

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay e2fe550

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok e2fe550b293a44f51a5206ac864106ae4a842f86

**Comment by livecode-vulcan** [comment]
😞 test failure e2fe550b293a44f51a5206ac864106ae4a842f86

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/782)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/787)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/780)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/781)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/787)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/779)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/779)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 66756ef

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 66756ef4912283388b9ffd40d1105e1b143d947b

**Comment by livecode-vulcan** [comment]
😎 test success 66756ef4912283388b9ffd40d1105e1b143d947b

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/795)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/800)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/793)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/794)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/800)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/792)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/792)

**Pull request merged**
