### PR TITLE
[Bug 18385] lc-run: Load multi-module assemblies.

### PR DESCRIPTION
**Pull request by peter-b**
For large multi-module pure-LCB programs like vulcanbot, it can be
pretty tedious to construct a suitable `lc-run` command line with many
`-l dependency.lcm` arguments.

Since LCB module files are self-delimiting, multiple modules can be
aggregated by concatenation (using `cat`, for example), without losing
the ability to load them.

This patch modifies `lc-run` to be able to load multiple modules from
a single .lcm file, allowing multi-module code libraries to be loaded
using a single `-l` argument to `lc-run`.

### CODE REVIEW

**Comment by peter-b** [comment]
Some outstanding issues with this PR which I would like feedback on:
- This is a bit of a hack; should it remain undocumented for now, or should I update the `lc-run` documentation and add a release note?  It's worth noting that `load extension from file` can't cope with these aggregated module files (and maybe it _shouldn't_)!
- What's the best way to test this?  Should I restore a set of `lc-run`-specific tests to the testsuite?

**Comment by runrevmark** [comment]
I think it is worth mentioning in the lc-run docs as an experimental ability - describing how to build the multi-module assemblies.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 3acbfbe

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 3acbfbe72d5db543010c179357d053e859caeb1e

**Comment by livecode-vulcan** [comment]
😞 test failure 3acbfbe72d5db543010c179357d053e859caeb1e
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/199)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/203)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/199)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/199)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/203)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/199)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/199)

**Comment by peter-b** [comment]
@runrevmark I've resolved the (extremely minor) conflicts with the current `develop` branch -- do you mind re-reviewing, please?

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 2e3f532

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 2e3f532e651c00b93ab5aa5d0795573ba396f5b3

**Comment by livecode-vulcan** [comment]
😎 test success 2e3f532e651c00b93ab5aa5d0795573ba396f5b3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/232)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/236)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/232)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/232)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/236)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/232)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/232)

**Pull request merged**
