### PR TITLE
[Bug 19214] Foreign type info creation ultra-moomin

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 3d40133

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 3d40133b54a10aa93d12a0ff7d78b8a116d9d10e

**Comment by livecode-vulcan** [comment]
😞 test failure 3d40133b54a10aa93d12a0ff7d78b8a116d9d10e

* try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1115)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1117)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1110)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1115)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1119)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1130)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1111)

**Comment by runrevmark** [comment]
This approach relies on the underlying C types of the LCB foreign types to all be distinct - however, this isn't the case in general (e.g. size_t and long or size_t and int maybe the same size). A slightly different approach is used in #5290 to achieve the same effect.

**Pull request closed without merging**
