### PR TITLE
[[ Bug 15750 ]] Document URL behaviour with Unicode files

### PR DESCRIPTION
**Pull request by livecodesebastien**
GitHub diff does not let us see the change. Simply, the change history has now 
7.0.0 Added support for Unicode files

and the following paragraph has been added in the comment section:

**Changes:** From LiveCode 7.0.0, **URL** keyword has been upgraded to understand Unicode files when using _URL("file:<path>")_. If the file located at the path has a Byte Order Mark at its beginning, then **URL** will decode the file according to that Byte Order Mark (UTF-8, UTF-16BE, UTF-16LE, UTF-32BE and UTF-32LE are compatible). If no Byte Order Mark is found, then the file will be decoded as if it were using Native encoding (_MacRoman_ on Mac OS X, _ISO-8859-1_ on Linux, _CP-1252_ on Windows).

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4dbee37

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4dbee37c7a85a004ca05f7ac021d507d5b77f412

**Comment by livecode-vulcan** [comment]
😞 test failure 4dbee37c7a85a004ca05f7ac021d507d5b77f412
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/181)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/180)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/181)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/176)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/183)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/180)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/184)

**Comment by livecodesebastien** [comment]
The build was broken on develop-7.0 (missing the update necessary for empscripten build), now fixed by merging https://github.com/runrev/livecode/pull/2791
@livecode-vulcan retry 4dbee37

**Comment by livecode-vulcan** [comment]
😎 test success 4dbee37c7a85a004ca05f7ac021d507d5b77f412
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/187)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/186)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/187)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/182)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/189)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/186)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/190)

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4dbee37c7a85a004ca05f7ac021d507d5b77f412

**Pull request merged**
