### PR TITLE
libbrowser: Remove uninformative "break wait" logging message

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a69c650

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok a69c6506b7757f35a5812285dd4961876dfa1928

**Comment by livecode-vulcan** [comment]
😞 test failure a69c6506b7757f35a5812285dd4961876dfa1928
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/172)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/176)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/172)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/172)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/176)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/172)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/172)

**Comment by peter-b** [comment]
@livecode-vulcan retry a69c650

**Comment by livecode-vulcan** [comment]
😎 test success a69c6506b7757f35a5812285dd4961876dfa1928
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/177)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/181)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/177)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/177)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/181)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/177)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/177)

**Pull request merged**
