### PR TITLE
[[ BrowserWidget ]] Fix crash when saving stack with a browser widget

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
I suggest clarifying the behavior of url and htmlText in the docs.

e.g. The url property always reflects the current url being displayed in the browser, and is updated if the user navigates to other pages by clicking on hyperlinks. If the url property is empty then it means the browser has had its htmlText property set.

A similar advisement (but the other way round) should go into the htmlText property.

**Comment by peter-b** [comment]
Is this something that can be tested?

**Comment by runrevmark** [comment]
@peter-b: How much does the unittest stack like widgets?

**Comment by peter-b** [comment]
@runrevmark :confused: It doesn't have any awareness of widgets at all.  I assume it would be necessary to move a widget handling library out of the IDE into e.g. `/ide-support/` in order to provide a way for tests to understand widgets. So — there is the opportunity to improve the test infrastructure...? :no_mouth:

**Comment by runrevmark** [comment]
@peter-b: Hmmmmmm - well using widgets only requires loading the appropriate extensions so as long as the tests can find the built extension lcm blobs then all is well.

**Comment by livecodeali** [comment]
If we added a suitable 'binaries path' function to the test lib, then loading could be added in the TestSetup handler provided the widget has no dependencies

**Comment by livecodeali** [comment]
For proper integration we would need to move some of the extension library into ide-support as @peter-b  says. This may not be a bad idea anyway, as I feel like in theory things in ide-support shouldn't depend on anything in the IDE (currently revIDEExtensionsOrderByDependency is in the standalone saving stacks).

We would need to do something with revZip to enable manifest parsing in TestSetup anyway, wouldn't we?

**Comment by runrevmark** [comment]
@livecodeali: In the first instance, can't we get away with something 'simpler'?

i.e. a handler in the TestLibrary - LoadExtension

LoadExtension "com.livecode.extensions.livecode.browser"
=> Resolve path to lcm file in folder inside build folder and load extension on it

**Comment by livecodeali** [comment]
@runrevmark Yeah, that sounds reasonable.

**Comment by runrevmark** [comment]
Is it possible to organise some tests for this today? This needs to go into dp-9 ideally, and so if we are to have tests before merging let's add them sooner rather than later :)

**Comment by livecodeali** [comment]
Additions to the framework are now working and ready to review.

https://github.com/livecode/livecode/pull/3218

**Comment by peter-b** [comment]
@livecode-vulcan review ok c21680b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c21680bf28e2840f253bed470cd660c47ea0d861

**Comment by livecode-vulcan** [comment]
😞 test failure c21680bf28e2840f253bed470cd660c47ea0d861
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1097)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1106)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1094)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1099)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1110)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1115)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1115)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 71305e9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 71305e9586950f98cebd7f406fd01580391c805e

**Comment by livecodeali** [comment]
@livecode-vulcan review ok cd40e75

**Comment by peter-b** [comment]
@livecode-vulcan review ok cd40e75

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok cd40e752bbc7e1a2a633c4cbe3abcdffa324d873

**Comment by livecodeali** [comment]
These commits were merged in https://github.com/livecode/livecode/pull/3237

**Pull request closed without merging**
