### PR TITLE
[[ Bug 16983 ]] GradienRampEditor put upper handle higher

### PR DESCRIPTION
**Pull request by BerndN**
add an accidentally deleted Y-value to draw upper selected handle at the top

### CODE REVIEW

**Comment by peter-b** [comment]
Third time lucky! Thank you for the fix, @BerndN 

@livecode-vulcan review ok a39176d

**Comment by BerndN** [comment]
@peter-b 
unfortunately I copied the typo (gradienRampEditor) in again. I hope this does not break anything.

Sorry for my thickheadedness, this is supposed to help, but at the current state of affairs I am not so sure.

**Comment by peter-b** [comment]
@BerndN I think it's okay -- it is clear what it means, which is the important part, and it is not in any UI text or in source code where it can make a big difference.

Thank you very much for contributing -- it's very much appreciated!

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a39176d27ebf06e2c701b06ccef16f3bf9d2adcc

**Comment by livecode-vulcan** [comment]
😎 test success a39176d27ebf06e2c701b06ccef16f3bf9d2adcc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1881)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1894)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1875)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1887)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1897)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1900)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1906)

**Pull request merged**
