### PR TITLE
[[ Bug 11727 ]] Fix arrow key not work in Android field

### PR DESCRIPTION
**Pull request by HedgeHao**

### CODE REVIEW

**Comment by livecodepanos** [comment]
Thank you @HedgeHao :)

@livecode-vulcan review ok 0953d36

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 0953d367f722fbe644665d074a0fac39f30c1eb8

**Comment by livecode-vulcan** [comment]
😞 test failure 0953d367f722fbe644665d074a0fac39f30c1eb8

* try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/924)
* try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/930)
* try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/922)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/923)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/930)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/922)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/921)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 0953d36

**Comment by livecode-vulcan** [comment]
😞 test failure 0953d367f722fbe644665d074a0fac39f30c1eb8

* try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/927)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/933)
* try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/925)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/926)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/933)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/925)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/924)

**Comment by montegoulding** [comment]
@livecode-vulcan retry 0953d36

**Comment by livecode-vulcan** [comment]
😎 test success 0953d367f722fbe644665d074a0fac39f30c1eb8

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/936)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/942)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/934)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/935)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/942)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/934)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/933)

**Pull request merged**
