### PR TITLE
[[ Bug 14377 ]] Throw an error if the For loop is not valid

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by runrevmark** [comment]
I'm not sure I understand this fix - the original report was about not flagging 'repeat with i = 1 to x' as a syntax error... This seems to be a runtime error that is now being generated.

**Comment by livecodesebastien** [comment]
I simply reapplied the way it was checked in 6.7 - an execution error is generated as well, not a syntax error.

**Comment by runrevmark** [comment]
We've looked closer at this - the current fix does catch the syntax errors, albeit at runtime. It is the best way to fix the problem at the moment without causing backwards-compatbility problems (making it a parser-level fix would break any scripts which have the incorrect form, even if that code is never run).

**Comment by runrevmark** [comment]
Reviewed-by: Mark Waddingham (@runrevmark)

**Pull request merged**
