### PR TITLE
[[ BrowserWidget ]] Add placeholder image to browser widget

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok c8424b4

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok c8424b44fc5cf8521110804186c15111e056261c

**Comment by livecode-vulcan** [comment]
😞 test failure c8424b44fc5cf8521110804186c15111e056261c
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/816)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/830)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/817)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/820)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/830)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/840)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/833)

**Comment by peter-b** [comment]
Hi @livecodeian, could you please merge from **develop** and resolve conflicts? Thanks!

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 12032fc

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 12032fce657e10b5bfe4ebfc2eb4dbfd0baf0e7d

**Comment by livecode-vulcan** [comment]
😞 test failure 12032fce657e10b5bfe4ebfc2eb4dbfd0baf0e7d
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/843)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/857)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/844)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/847)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/857)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/867)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/860)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 12032fc

**Comment by livecode-vulcan** [comment]
😎 test success 12032fce657e10b5bfe4ebfc2eb4dbfd0baf0e7d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/851)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/865)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/852)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/855)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/865)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/875)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/868)

**Pull request merged**
