### PR TITLE
[Bug 18536] Add support for Xcode 8.1 / iOS 10.1

### PR DESCRIPTION
**Pull request by livecodepanos**
WIP until we build and upload the prebuilt libs (libcustomcrypto, libcustomssl, libicu) for iOS 10.1

### CODE REVIEW

**Comment by livecodepanos** [comment]
Prebuilt libs are now successfully built and uploaded. So this PR is ready for review.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok c5a7315

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok c5a7315fa3f050d318e53068acc0b976e9b02220

**Comment by livecode-vulcan** [comment]
😞 test failure c5a7315fa3f050d318e53068acc0b976e9b02220
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/504)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/509)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/504)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/505)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/510)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/504)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/505)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry c34a239

**Comment by livecodepanos** [comment]
@livecode-vulcan retry c5a7315

**Comment by livecode-vulcan** [comment]
😞 test failure c5a7315fa3f050d318e53068acc0b976e9b02220
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/514)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/519)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/514)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/518)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/521)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/514)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/515)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry c34a239

**Comment by livecodepanos** [comment]
@livecode-vulcan retry c5a7315

**Comment by livecode-vulcan** [comment]
😞 test failure c5a7315fa3f050d318e53068acc0b976e9b02220
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/515)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/520)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/515)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/519)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/522)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/515)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/516)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry c5a7315

**Comment by peter-b** [comment]
@livecode-vulcan retry c5a7315

**Comment by livecode-vulcan** [comment]
😎 test success c5a7315fa3f050d318e53068acc0b976e9b02220
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/517)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/522)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/517)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/521)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/526)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/518)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/518)

**Pull request merged**
