### PR TITLE
Release notes fixes

### PR DESCRIPTION
**Pull request by peter-b**
Some minor fixes to release notes generation to make sure the 8.0.1 release notes are correct.

### CODE REVIEW

**Comment by livecodeali** [comment]
Nice.
@livecode-vulcan review ok 9317fc5

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 9317fc57381bc61700c269e9f06e985465d66769

**Comment by livecode-vulcan** [comment]
😎 test success 9317fc57381bc61700c269e9f06e985465d66769
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2490)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2500)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2483)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2501)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2507)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2511)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2523)

**Comment by peter-b** [comment]
Please don't merge this yet -- I need to make a small tweak.

**Comment by peter-b** [comment]
@livecodeali Could you please re-review the third commit in this series? I think it fixes the problem more elegantly.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay f8671fe

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok f8671fe88f76467066191a92c62ccae8b5c16763

**Comment by livecode-vulcan** [comment]
😎 test success f8671fe88f76467066191a92c62ccae8b5c16763
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2495)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2505)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2488)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2506)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2512)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2516)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2528)

**Pull request merged**
