### PR TITLE
[[ Bug 18254 ]] Convert data to real directly

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by runrevmark** [comment]
I'm not sure using a length check here is correct - the string rep of a number could be arbitrarily long. The performance problem is caused by the explicit convert to a string to try to parse as a number... This could be improved by having converttonumber act directly on the bytes (native encoded text) rather than converting to string first.

**Comment by montegoulding** [comment]
Hmm... there is actually that same check in `MCU_strtor8` so I was just thinking to to it before wasting any time trying to parse the string but I can try it that way.

**Comment by montegoulding** [comment]
@runrevmark I just ran a quick test by virtually duplicating `MCTypeConvertStringToReal` to `MCTypeConvertDataToReal` and yes this has the same performance increase as what I did. I'm wondering about the other `MCTypeConvertString*` functions here now? Perhaps they all should have Data versions?

**Comment by montegoulding** [comment]
`StringToBool` & `StringToLongInteger` don't appear to be used all that much

**Comment by montegoulding** [comment]
Labelling as WIP for the time being as I don't like the code duplication

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 0bcb7e4

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 0bcb7e467c80b9401dd586485ce4c3d58da6f10c

**Comment by livecode-vulcan** [comment]
😞 test failure 0bcb7e467c80b9401dd586485ce4c3d58da6f10c
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/173)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/177)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/173)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/173)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/177)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/173)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/173)

**Comment by montegoulding** [comment]
@livecode-vulcan review ok f6f5995 by @runrevmark

**Comment by peter-b** [comment]
@livecode-vulcan review by @runrevmark ok f6f5995

**Comment by montegoulding** [comment]
Ah... backwards.. silly me

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok f6f5995b9e987612a26cad5a8aff4b60c87ec509

**Comment by livecode-vulcan** [comment]
😎 test success f6f5995b9e987612a26cad5a8aff4b60c87ec509
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/179)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/183)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/179)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/179)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/183)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/179)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/179)

**Pull request merged**
