### PR TITLE
Speed up the "&" and "&&" operators

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by montegoulding** [comment]
What about comma?

**Comment by peter-b** [comment]
<bikeshed> What about `MCStringConcatenate()` and `MCDataConcatenate()`? </bikeshed>

**Comment by runrevmark** [comment]
@montegoulding: The &, && and ',' operators were all based on the same underlying functions... @livecodefraser just updated those underlying functions - there was no need to modify the actual top-level operator code. (So the PR is better than advertised - it speeds up more operations than is listed in the title).

**Comment by montegoulding** [comment]
Good stuff @livecodefraser

**Comment by runrevmark** [comment]
@livecode-vulcan review ok e99f0a6

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok e99f0a657dde6693787376be09fdf66791373ad3

**Comment by livecode-vulcan** [comment]
😞 test failure e99f0a657dde6693787376be09fdf66791373ad3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/621)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/633)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/622)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/623)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/632)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/643)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/634)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry e99f0a6

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry e99f0a6

**Comment by livecode-vulcan** [comment]
😎 test success e99f0a657dde6693787376be09fdf66791373ad3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/625)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/637)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/626)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/627)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/636)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/647)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/638)

**Comment by mwieder** [comment]
+1. Thanks.

**Pull request merged**
