### PR TITLE
[[Docs]] true - Example formatting

### PR DESCRIPTION
**Pull request by seaniepie**
- Placed the sub-example into a script format
- Added then to both scripts to complete the line

### CODE REVIEW

**Comment by peter-b** [comment]
@seaniepie Don't forget that you can do inline code samples using `...`!  Also, consider something like:

> The following two `if` statements are equivalent:
> 
> ```
> if the lockText of field 1 is true then ...
> if the lockText of field 1 then ...
> ```

**Comment by seaniepie** [comment]
@peter-b , @livecodeali , does this look better now?

**Comment by livecodeali** [comment]
@seaniepie I think it needs to say `the following two if statements are equivalent` rather than `...are true` since the field may not have lockText set to true!

**Comment by seaniepie** [comment]
Agreed, that's much better. I didn't notice it in Peter's original post

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 72101cb

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 72101cb064fcee89b410d0c0f4ca50ab67d79c50

**Comment by livecode-vulcan** [comment]
😎 test success 72101cb064fcee89b410d0c0f4ca50ab67d79c50
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/432)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/437)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/432)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/432)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/438)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/432)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/432)

**Pull request merged**
