### PR TITLE
[Bug 16193] Make sure the label stays always within the combobox when resizing

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
The rect of the entry box is being changed in the draw method here... Couldn't it be changed in the setrect() method or similar?

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay c90b5d6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok c90b5d6acadf17b3da186261aaaa2e796ad27e4b

**Comment by livecode-vulcan** [comment]
😎 test success c90b5d6acadf17b3da186261aaaa2e796ad27e4b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/733)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/747)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/734)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/736)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/747)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/757)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/749)

**Pull request merged**
