### PR TITLE
[[ Dictionary ]] Tweak guide structure and update installer manifest

### PR DESCRIPTION
**Pull request by livecodeali**
Requires https://github.com/livecode/livecode-ide/pull/759

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 02a3b67

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 02a3b678ed548fb9a2a8585658a7d4570edbee61

**Comment by livecode-vulcan** [comment]
😎 test success 02a3b678ed548fb9a2a8585658a7d4570edbee61
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1525)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1544)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1521)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1532)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1544)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1545)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1547)

**Comment by livecodeali** [comment]
Fixed a merge conflict - the PR fixing the installer package for the DP 12 dictionary added viewer_external.html, which is no longer needed after this PR.

**Comment by peter-b** [comment]
Is it still possible to open the dictionary viewer HTML page directly from the filesystem rather than via the IDE without viewer_external.html?

**Comment by livecodeali** [comment]
Provided it has been generated, yes

**Comment by peter-b** [comment]
@livecode-vulcan review ok 120cfc5

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 120cfc5750d1f8274ff83a4ad49b6f97dbdc3639

**Comment by livecode-vulcan** [comment]
😎 test success 120cfc5750d1f8274ff83a4ad49b6f97dbdc3639
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1535)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1554)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1531)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1542)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1554)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1555)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1557)

**Pull request merged**
