### PR TITLE
Make sure we don't use the system Gyp for building

### PR DESCRIPTION
**Pull request by livecodefraser**
Our version has some customisations and bugfixes that aren't (yet...)
suitable for upstreaming.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 589da86

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 589da8639050ab1bdab613f9f8fa0dc133b8af39

**Comment by livecode-vulcan** [comment]
😎 test success 589da8639050ab1bdab613f9f8fa0dc133b8af39
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1660)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1676)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1655)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1666)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1677)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1679)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1684)

**Comment by mwieder** [comment]
can this please get merged into the develop branch? thanks.

**Comment by mwieder** [comment]
Peter - that merged into develop-6.7: it's not in develop yet.

**Comment by peter-b** [comment]
Sadly, I can't do (and check) merges from my phone while waiting in an airport passport control queue.

**Comment by mwieder** [comment]
Ha! I'm happy you can't. No rush, but please put it on the to-do list.

**Comment by mwieder** [comment]
Is now a good time to merge this into the 7.x / 8.x develop branches?

**Comment by mwieder** [comment]
Or would it be better if I just submitted a matching PR against the develop branch?

**Comment by runrevmark** [comment]
@mwieder: This will appear in those branches shortly... I believe the initial merge from 6.7 to 7.0 went through today.

**Comment by mwieder** [comment]
Merging this into the develop branch would be nice.
I currently have to patch this in after every pull and then delete it if I'm going to push changes.

**Comment by peter-b** [comment]
I'm pretty sure it is merged now...?

**Comment by mwieder** [comment]
Nope. I just pulled the latest before posting that and I still have to patch the develop branch in order to build 8.0.

**Comment by livecodeali** [comment]
@mwieder Now merged into develop.
https://github.com/livecode/livecode/pull/3629

**Comment by mwieder** [comment]
@livecodeali ty - it's working fine now.

**Pull request merged**
