### PR TITLE
[Tests] Add livecodescript test infrastructure.

### PR DESCRIPTION
**Pull request by peter-b**
Add a test suite infrastructure for `.livecodescript` files.

### CODE REVIEW

**Comment by runrevmark** [comment]
Looking good :)

`<bikeshed>`Can I suggest that the folder under 'tests' be tests/lcs?`</bikeshed>`

**Comment by peter-b** [comment]
@runrevmark Pull request updated!

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9dbb33b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9dbb33b5b91f11587a4e468ba15ca7ffecfa5339

**Comment by livecode-vulcan** [comment]
😎 test success 9dbb33b5b91f11587a4e468ba15ca7ffecfa5339
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/448)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/448)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/447)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/446)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/452)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/443)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/454)

**Pull request merged**
