### PR TITLE
Bump tsNet version number for inclusion

### PR DESCRIPTION
**Pull request by techstrategies**

### CODE REVIEW

**Comment by montegoulding** [comment]
@techstrategies it's probably better to wait until your server syncs up to submit a PR as when travis runs the tests it does a HEAD request to check the files are there.

@livecode-vulcan review ok 5822622

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 5822622f842bc96927cd0967a4e1dca2cd388021

**Comment by livecode-vulcan** [comment]
😎 test success 5822622f842bc96927cd0967a4e1dca2cd388021
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/58)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/58)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/58)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/58)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/58)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/58)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/58)

**Comment by techstrategies** [comment]
Thanks @montegoulding ... I'll remember that for next time!

**Pull request merged**
