### PR TITLE
[[ Bug 17310 ]] Implement userAgent property for Mac browser.

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevmark I think that the release note should probably be in the browser widget's notes...

**Comment by peter-b** [comment]
@livecode-vulcan review ok b0ce2f3

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b0ce2f318b2605357be4936ea5556723f73693ad

**Comment by livecode-vulcan** [comment]
😎 test success b0ce2f318b2605357be4936ea5556723f73693ad
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2338)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2347)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2331)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2348)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2354)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2359)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2370)

**Pull request merged**
