### PR TITLE
[[ Community Docs ]] Fix some broken links and missing image in guide

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali Do we want these changes to go into the 8.0 GM release?

**Comment by livecodeali** [comment]
@peter-b This is repo-only documentation so yes / it doesn't matter

**Comment by peter-b** [comment]
@livecode-vulcan review ok 90e9c00

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 90e9c00996dc669bab211605131da7127447cbfd

**Comment by livecode-vulcan** [comment]
😎 test success 90e9c00996dc669bab211605131da7127447cbfd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2347)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2357)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2340)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2358)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2364)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2368)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2380)

**Pull request merged**
