### PR TITLE
[Bug 15763] Can't select the last control of a group

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevpanos, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by mwieder** [comment]
wait. wat?

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 73c8385

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 73c8385ee2e04025b0479f1d7597d8ac3afb23f9

**Comment by livecode-vulcan** [comment]
😎 test success 73c8385ee2e04025b0479f1d7597d8ac3afb23f9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/203)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/202)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/203)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/198)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/205)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/203)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/206)

**Pull request merged**
