### PR TITLE
[Bug 16543][emscripten] Make specialFolderPath() function work

### PR DESCRIPTION
**Pull request by peter-b**
Also rewrite the documentation for `specialFolderPath()` because why not.

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 39e312e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 39e312e3c70d566fc90a702f593f3b61c7702b77

**Comment by livecode-vulcan** [comment]
💥 merge conflict 39e312e3c70d566fc90a702f593f3b61c7702b77 → 959e99b48ab5583cb9d9c7b02e9a62a01619d161

**Comment by peter-b** [comment]
@livecodefraser review ok 39e312e

**Comment by peter-b** [comment]
@livecodefraser Pull request updated

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay dba66e5

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok dba66e530c554f86b8d15f7a5e501f9b87d6d0e4

**Comment by livecode-vulcan** [comment]
😞 test failure dba66e530c554f86b8d15f7a5e501f9b87d6d0e4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1423)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1443)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1419)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1429)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1440)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1439)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1444)

**Comment by peter-b** [comment]
@livecode-vulcan retry dba66e5

**Comment by livecode-vulcan** [comment]
😞 test failure dba66e530c554f86b8d15f7a5e501f9b87d6d0e4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1424)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1444)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1420)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1430)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1441)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1440)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1445)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry dba66e5

**Comment by livecode-vulcan** [comment]
😞 test failure dba66e530c554f86b8d15f7a5e501f9b87d6d0e4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1425)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1445)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1421)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1431)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1442)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1441)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1446)

**Comment by peter-b** [comment]
@livecode-vulcan retry dba66e5

**Comment by livecode-vulcan** [comment]
😎 test success dba66e530c554f86b8d15f7a5e501f9b87d6d0e4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1440)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1460)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1436)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1446)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1458)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1459)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1462)

**Pull request merged**
