### PR TITLE
Tweaks to Installer/package.txt

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay ecb2c3a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok ecb2c3a6d4ddd58c52af8ea8e5d4d9f393cc9053

**Comment by livecodepanos** [comment]
Note: Do not merge this PR yet, since at this point we don't want to add _more_ changes in the installer. Once we have a successful `8.1.1-rc-1` build, we can then merge this PR (or rebase it)

**Comment by livecode-vulcan** [comment]
😎 test success ecb2c3a6d4ddd58c52af8ea8e5d4d9f393cc9053
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/263)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/267)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/263)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/263)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/267)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/263)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/263)

**Pull request merged**
