### PR TITLE
[[ Bug 16244 ]] Override setting of showInvisibles for IDE stacks

### PR DESCRIPTION
**Pull request by livecodeian**
This ensures hidden objects on IDE stacks remain hidden when "Show Invisible Objects" is enabled from the "View" menu.

ide submodule changes: added initialisation code to Home stack to set 'showInvisibles' property of IDE stacks to false.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian What are the changes in the IDE submodule?

**Comment by livecodeian** [comment]
@peter-b : I've edited the PR comment, the ide changes are additions to the init code to set the 'showInvisibles' of IDE stacks, which overrides the global property.

**Comment by peter-b** [comment]
@livecode-vulcan review ok f9cbd11

**Comment by runrevmark** [comment]
Sorry to be a pain - but could we add an effective form of the stack-level show invisibles property too?

It's normal for every property which can inherit from parent to have an effective form too :)

@livecode-vulcan review not ok f9cbd11

**Comment by livecode-vulcan** [comment]
💔 review by @runrevmark not ok f9cbd1114e66a85d151f8dfaf9b0fe099cdae801

**Comment by livecodeian** [comment]
@runrevmark : 'effective showInvisibles' added now

**Comment by peter-b** [comment]
@livecode-vulcan review ok 82e5c33

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 82e5c33cd2c20ca0c7e32f145b264f4704bce7dc

**Comment by livecode-vulcan** [comment]
😎 test success 82e5c33cd2c20ca0c7e32f145b264f4704bce7dc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1956)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1969)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1950)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1962)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1972)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1977)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1982)

**Pull request merged**
