### PR TITLE
[[ Bug 16345 ]] Clear browser when url set to the empty string

### PR DESCRIPTION
**Pull request by livecodeian**
Depends upon PR #3181

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian It looks like the test is failing on the (headless) builder.  Is it expected to work in `-ui` mode?

**Comment by livecodeian** [comment]
Ah, the failing test file was an old version with some errors in it. It shouldn't have been commited in the first place.

**Comment by peter-b** [comment]
@livecode-vulcan review ok a12375d



---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3237)

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a12375d4010f80d875cb9192007bf123adf29b79

**Comment by livecode-vulcan** [comment]
😎 test success a12375d4010f80d875cb9192007bf123adf29b79
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1106)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1115)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1103)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1108)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1119)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1124)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1124)

**Pull request merged**
