### PR TITLE
Feature android launch intent access

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecodeian** [comment]
Note: this will need to be modified once https://github.com/runrev/livecode/pull/2511 has been merged as the MCJavaMapToArray call will be obsolete.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok f16d383

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok f16d38327621fbd3009a9ff6dcadc2bc173bae86

**Comment by livecode-vulcan** [comment]
😎 test success f16d38327621fbd3009a9ff6dcadc2bc173bae86
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/447)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/507)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/393)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/458)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/393)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/384)

**Pull request merged**
