### PR TITLE
Dictionary updates

### PR DESCRIPTION
**Pull request by madpink**
Just a few corrections to the dictionary (LCB)

### CODE REVIEW

**Comment by montegoulding** [comment]
@madpink do you happen to know how to rebase? These would both be good against the `develop-9.0` branch rather than `develop`. I can provide instructions if you need.

**Comment by madpink** [comment]
instructions would be great

**Comment by montegoulding** [comment]
OK are you on command line or using a gui?

**Comment by madpink** [comment]
for this, I just edited online on github, I could switch to github's desktop app

**Comment by montegoulding** [comment]
Hmm... usually github will create a patch branch for you. I'm thinking we should just merge this in on develop and one of us can cherry-pick it back to develop-9.0 when we get a chance.

@livecode-vulcan review ok 948ea08

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 948ea084933e7172dd242ae646dca411ee6703f1

**Comment by madpink** [comment]
I could also just delete my local and try again off of "develop-9.0"?

**Comment by livecode-vulcan** [comment]
😎 test success 948ea084933e7172dd242ae646dca411ee6703f1

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/67)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/59)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/59)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/59)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/59)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1581)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/108)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/108)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1611)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1605)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1601)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1638)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1578)

**Pull request merged**
