### PR TITLE
Community Docs: replaced misspelled command revDatabaseQuery with cor…

### PR DESCRIPTION
**Pull request by marksmithhfx**
…rect version; revQueryDatabase on line 40

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @marksmithhfx, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by peter-b** [comment]
Thank you @marksmithhfx!

@livecode-vulcan review ok 287428e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 287428e5b8405429e9b270806f97e441c0f4f0c4

**Comment by livecode-vulcan** [comment]
😎 test success 287428e5b8405429e9b270806f97e441c0f4f0c4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1668)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1684)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1663)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1674)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1685)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1687)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1692)

**Pull request merged**
