### PR TITLE
[[ Profiling ]] A simple approach to low-level profiling.

### PR DESCRIPTION
**Pull request by runrevmark**
This patch allows the server engine to be be built with 'FEATURE_PROFILE'.

This augments the core exec methods for statements so that they measure
the amount of 'time' spent executing each one.

It instruments the root server script, and outputs a list of (line, count) pairs at
the end which can easily be processed by a simple script.

Note 'time' here is the low-level CPU cycle counter.

### CODE REVIEW

**Comment by mwieder** [comment]
Note that the copyright string is still Copyright (C) 2015 Runtime Revolution Ltd.

**Comment by mwieder** [comment]
Is there any reason to limit this to the server and not the desktop?

**Comment by runrevmark** [comment]
@mwieder: This isn't really designed for use in an IDE type context. It is designed for a 'low-level' benchmarking suite to be run from the command line to enable fast iteration on optimizations for basic operations. It's design is quite restricted in scope - for example the engine has to be built differently and server type running makes it easy to output and map what lines of the script took how long. Certainly something could be done for dynamic use in the ide but that would probably be about 3 weeks of work rather than an afternoon.

**Comment by runrevmark** [comment]
Closing this as the simpler benchmark runner (in benchmarks/) which was developed after this and subsequently merged is much more appropriate for doing performance testing of the engine.

**Pull request closed without merging**
