### PR TITLE
[[ Bug 17838 ]] Update mergExt pointer

### PR DESCRIPTION
**Pull request by montegoulding**
This update includes new versions of:
- mergAccessory - Business Services
- XPDF - Fix for Bug 17838

### CODE REVIEW

**Comment by peter-b** [comment]
@montegoulding Do you want to update the version of mergExt in 8.0.2 GM? Or is 8.0.4 RC 1 okay?

**Comment by montegoulding** [comment]
I think the two main people impacted by these changes already have the new versions so no real need to introduce them into a GM release unless you really want to.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 9fa0105

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9fa01057cff493c3f34385fed9deb9705015c789

**Pull request merged**
