### PR TITLE
[[ Bug 18445 ]] Don't send revLoadLibrary to data grid library stack

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali What changes would need to be made to the datagrid library to make it work correctly with `revLoadLibrary`?

@livecode-vulcan review ok 42e3ec0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 42e3ec0d0cf185d6b30897c8e630dbd7168fca2c

**Comment by livecodeali** [comment]
@peter-b Probably just adding a `revLoadLibrary` handler to the stack to do the appropriate initialisation. Really the `revDataGridLibrary` stack should be script-only and a dependency of the data grid custom control - I suspect it would make sense to work out how custom control packages are going to work and restructure the data grid accordingly

**Comment by livecode-vulcan** [comment]
😎 test success 42e3ec0d0cf185d6b30897c8e630dbd7168fca2c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/250)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/254)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/250)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/250)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/254)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/250)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/250)

**Pull request merged**
