### PR TITLE
[Bug 15811][emscripten] Enable multi-font support

### PR DESCRIPTION
**Pull request by peter-b**
This pull request enables support for multiple fonts in HTML5 standalones.  By default, the standalone will contain the "Droid Sans Fallback" font, but additional fonts can be included via the "Copy Files" page of the standalone builder.

Fonts are now located in the `/boot/standalone` directory of the initial filesystem image.

### CODE REVIEW

**Comment by peter-b** [comment]
Depends on livecode/livecode-thirdparty#45.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 4c48316

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 4c483162ea9343a24eaf847159c15b7267837ffd

**Comment by livecode-vulcan** [comment]
😎 test success 4c483162ea9343a24eaf847159c15b7267837ffd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1679)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1695)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1674)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1685)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1696)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1698)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1703)

**Comment by peter-b** [comment]
@runrevmark Do you mind looking at  livecode/livecode-thirdparty#45 as well, so that I can go ahead and merge this?

**Pull request merged**
