### PR TITLE
Implement API for forcing inclusion in deploy builds

### PR DESCRIPTION
**Pull request by montegoulding**
Note that I think it would be good if the standalone settings dialog used the `revSBGetSettings` and `revSBSetSettings` APIs at some point but it probably isn't necessary right now.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 652da8b

**Comment by livecodeali** [comment]
You'll need to tweak the standalone builder test support stack to get this working. https://github.com/livecode/livecode-ide/blob/develop/tests/standalonebuilder/_support.livecodescript#L70

**Comment by montegoulding** [comment]
Fixed the PR that has related IDE repo changes https://github.com/livecode/livecode-ide/pull/1442

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 652da8b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 652da8b460afbd786e17fbb458f00a092faaec0f

**Comment by livecode-vulcan** [comment]
😎 test success 652da8b460afbd786e17fbb458f00a092faaec0f

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/941)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/947)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/939)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/940)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/947)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/939)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/938)

**Pull request merged**
