### PR TITLE
docs: Add release notes for Mac 64-bit.

### PR DESCRIPTION
**Pull request by peter-b**
Update overview and known issues, and add feature release note.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 92bbd06

**Comment by livecodeali** [comment]
Actually, do line-broken bullet points work? I'm not sure they do...

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 92bbd060a51475363509b37dcd0570ac83923cdc

**Comment by peter-b** [comment]
Um. They work fine with marked.js. Let's see what the release notes look like in the installers…

**Comment by peter-b** [comment]
@livecode-vulcan retry 92bbd06

**Comment by livecode-vulcan** [comment]
😎 test success 92bbd060a51475363509b37dcd0570ac83923cdc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1790)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1803)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1784)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1796)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1805)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1809)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1815)

**Pull request merged**
