### PR TITLE
[Bug 15621] Make LC "purple" to match the actual X11 purple

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @runrevpanos, the named colours in LiveCode are supposed to be X11 colour names, not HTML colour names. So I don't think this patch is quite right (in addition to breaking backwards compatibility).

**Comment by runrevmark** [comment]
@runrevpanos: Yes, @peter-b is correct - we can't just change the color mappings. Purple just means something different in the X11 colors from web colors.

**Comment by livecodepanos** [comment]
Ok. However, LC "purple" (i.e 142, 53, 239) seems to be a bit different than the actual x11 purple (160,32,240), as found here:

https://en.wikipedia.org/wiki/X11_color_names

So, should I just update LC purple to match the actual x11 purple?

**Comment by runrevmark** [comment]
@runrevpanos: Yes - @livecodefraser just pointed that out.  I have no idea why that would be different - do any of the other colors have different definitions from the X11 color table?

(I wonder if the original color table was taken from a server dump for a specific X server which was not 100% compliant)

**Comment by runrevmark** [comment]
Okay is seems that a lot of the colors in our definitions are different from the latest X11 defs in rgb.txt (from an X11 distro). Why this is the case I don't know... It could be that the color tables were generated by a script from a specific X server which tailored the colors for the specific attached display - which would explain the subtle differences across what appear to be random sets of the colors.

**Comment by livecodepanos** [comment]
Yes, I confirm that some LC colors are different. So, since in this PR we will address only the "purple" case, I will create a new bug report in BZ to address all the other cases.

**Comment by peter-b** [comment]
@livecode-vulcan review ok cf53175

**Comment by livecodestephen** [comment]
Is it a good idea to change the definition of a colour in a maintenance release?

**Comment by peter-b** [comment]
@livecodestephen Yes, I wondered about this too.  At the moment the `purple` colour isn't really very purple at all -- it's nowhere near either the X11 or W3C definitions.  The other option is, of course, to just mark this bug **NOT_FIXABLE** and, later, add new syntax for accessing the X11 and W3C palettes.

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok cf53175253511b66caedfe549022878f00570d5b

**Comment by livecodestephen** [comment]
I think it would be reasonable to change the definitions across a major release. In that case the user would expect some changes and would notice if their app looked different, so could make the necessary changes.  But if you upgrade from 6.7.7 to 6.7.8 it would be a bit of a shock if all you're colours came out different.

**Comment by runrevmark** [comment]
This falls into the same class as bugs like the one reported against the tag mapping for htmlText (Bug 15599) - the current mappings have been defined for an age so we definitely can't change them in a maintenance release and I'd suggest even doing it across a major release boundary is the wrong way to do things.

Really the color mappings and htmlText tag mappings should be configurable at runtime (they are just lookups after all)... Of course, then you get the problem of global interactions with the IDE, and multiple 'applications' being edited in one IDE trouncing each others settings rather arbitrarily.

As it stands the X11 colors in the engine are obviously derived from somewhere so they are valid mappings if not up to modern user expectations (just the same as the htmlText mappings are).

**Comment by runrevmark** [comment]
Closing PR as it isn't the correct way to fix the reported issue.

**Pull request closed without merging**
