### PR TITLE
[[ Gradient Ramp Editor ]] Don't send changed message when stop offset doesn't change

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 8e309ae

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 8e309ae28849e4a9904cc09df5c51044b7155de2

**Comment by livecode-vulcan** [comment]
😞 test failure 8e309ae28849e4a9904cc09df5c51044b7155de2
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2313)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2322)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2306)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2323)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2329)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2334)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2345)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 8e309ae

**Comment by livecode-vulcan** [comment]
😎 test success 8e309ae28849e4a9904cc09df5c51044b7155de2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2316)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2325)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2309)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2326)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2332)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2337)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2348)

**Pull request merged**
