### PR TITLE
[[ Bug 17804 ]] Correctly check ProxyEnable setting

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan try 0fc7372

**Comment by peter-b** [comment]
@livecode-vulcan review ok 8e03755

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 8e03755a91c579d5e41f7fe990ffa220ba6cc34c

**Comment by livecode-vulcan** [comment]
😞 test failure 8e03755a91c579d5e41f7fe990ffa220ba6cc34c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/124)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/124)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/124)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/124)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/124)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/124)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/124)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok cc1d6af

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok cc1d6af7befa4cb5c0a6340e5fe02788d3402306

**Comment by livecode-vulcan** [comment]
😎 test success cc1d6af7befa4cb5c0a6340e5fe02788d3402306
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/132)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/132)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/132)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/132)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/132)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/132)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/132)

**Pull request merged**
