### PR TITLE
[[ Bug 20290 ]] Support PKCS#1 format public keys in encrypt

### PR DESCRIPTION
**Pull request by montegoulding**
This patch adds support for using RSA public keys in PKCS#1
format. If reading traditional format fails an attempt is made
to read in PKCS#1 format.

Depends on: https://github.com/livecode/livecode-thirdparty/pull/109

### CODE REVIEW

**Comment by livecodeali** [comment]
I did a bit of experimenting- this seems to work
```
lcs-check: $(LCS_ENGINE) lcm_compile
ifeq ($(guess_platform),mac)
	@cp -f $(bin_dir)/revsecurity.dylib $(bin_dir)/Standalone-Community.app/Contents/MacOS
	@cp -rf $(bin_dir)/revpdfprinter.bundle $(bin_dir)/Standalone-Community.app/Contents/MacOS
endif
	@rm -f $(LCS_LOG)
	@export TEST_SUITE_LOG_FILE="$(LCS_LOG)"; \
	cmd="$(LCS_CMD)"; \
	echo "$$cmd" $(_PRINT_RULE); \
	$$cmd
```

Apparently ifeq needs to have no indent to work in a makefile

**Comment by montegoulding** [comment]
¯\_(ツ)_/¯

**Comment by montegoulding** [comment]
@livecodeali @runrevmark should I rebase this entire patch on `develop-8.2` or should I open up a new PR with just the cherry-picked commit that copies the libraries to the standalone for testing?

**Comment by runrevmark** [comment]
@montegoulding Is there a reason we need that commit on 8.2?

**Comment by montegoulding** [comment]
Only if we want to test revsecurity stuff on that branch

**Comment by livecodeali** [comment]
We don't run Travis on Mac in 8.2 so there's no point. At some point we could backport the revsecurity copy and the travis-on-mac stuff, but my quick attempt at the latter did not work for some reason

**Comment by montegoulding** [comment]
Ok cool it's ready for review then :-)

**Comment by montegoulding** [comment]
@runrevmark  @livecodeali just rebased this to resolve the merge conflict

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 32f12eb

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 32f12eb4f656ba5c39647053fdd17f417564de1d

**Comment by livecode-vulcan** [comment]
😎 test success 32f12eb4f656ba5c39647053fdd17f417564de1d

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/746)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/762)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/736)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/679)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/681)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/740)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/760)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/745)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/762)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/744)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/755)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/776)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/740)

**Pull request merged**
