### PR TITLE
Highlighted

### PR DESCRIPTION
**Pull request by mwieder**
This finishes making "highlight" a synonym for "hilite" everywhere it's used.
And when integrated it fulfils the promise of http://quality.runrev.com/show_bug.cgi?id=8211, which I filed six years ago. Figured I might as well do the work myself.

### CODE REVIEW

**Comment by peter-b** [comment]
@mwieder The automated tests have failed because your patch doesn't preserve strict alphabetical ordering in the lexer tables.  Could you please fix that? Thanks. :smiley:

It would also be very helpful if you could update any corresponding tests and dictionary entries, and also add a release note. :+1:

**Comment by mwieder** [comment]
Doh! alpha order fixed.
Looking for tests now.
I didn't even realize dehilite was a word in the dictionary.

**Comment by mwieder** [comment]
Added a bunch of tests. Had to comment out two failing tests because they actually caught problems. Filed two bug reports on these issues.

**Comment by peter-b** [comment]
@mwieder Check your e-mail! There are some remaining issues here, but I reckon we can sort them out pretty easily. :+1:

**Comment by peter-b** [comment]
Re-assigning to @runrevmark for review (per [this e-mail](http://lists.runrev.com/pipermail/use-livecode/2015-October/220463.html)).

**Comment by peter-b** [comment]
Since #3148 is merged, I'm closing this for the time being pending further discussion of whether it's actually desirable to add synonyms to the language at this point...

**Comment by mwieder** [comment]
Sounds good. If I do resubmit this I'll have to rework the tests anyway.

**Pull request closed without merging**
