### PR TITLE
Remove an unbalanced ' from a preprocessor directive in foundation.h

### PR DESCRIPTION
**Pull request by livecodefraser**
It makes compilers unhappy.

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok d80a48a

**Comment by peter-b** [comment]
This why you should always use formal English in your code comments and m

@livecode-vulcan review ok d80a48a

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok d80a48acda3a9c1d7578100bb44aa30af4dde48e

**Comment by livecode-vulcan** [comment]
😎 test success d80a48acda3a9c1d7578100bb44aa30af4dde48e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/454)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/459)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/454)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/454)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/460)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/454)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/454)

**Pull request merged**
