### PR TITLE
[[ Gyp ]] Add silence_warnings support for Windows builds

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
Nice.

@livecode-vulcan review ok f449311

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f449311dd5aeab5144f0c67555ca498685b40eff

**Comment by livecode-vulcan** [comment]
😎 test success f449311dd5aeab5144f0c67555ca498685b40eff
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/586)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/646)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/535)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/599)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/531)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/524)

**Comment by livecodefraser** [comment]
This didn't affect the toolchain warnings because they use a different mechanism for disabling warnings - I'm updating the pull request to sort that.

**Comment by peter-b** [comment]
@livecodefraser  As discussed offline, please make a follow-up pull request that re-enables warnings for the non-generated parts of lc-compile!

@livecode-vulcan review ok eb3acb8

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok eb3acb8130b6009667afa2c426919d02de6cda6e

**Comment by livecode-vulcan** [comment]
😞 test failure eb3acb8130b6009667afa2c426919d02de6cda6e
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/590)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/650)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/539)
- try-android-armv6: [pending](https://vulcan.livecode.com/builders/try-android-armv6/builds/603)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/535)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/528)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay a6fb1c2

Reviewing myself to check that I've fixed the build failures!

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok a6fb1c2cc54a1e56d0255c3fcb3994e337e64a14

**Comment by livecode-vulcan** [comment]
😞 test failure a6fb1c2cc54a1e56d0255c3fcb3994e337e64a14
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/598)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/658)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/547)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/611)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/543)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/536)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 058fc04

Umpteenth time lucky?

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 058fc04e3b47fcb8bc37251714a22ef2b50a5563

**Comment by livecode-vulcan** [comment]
😞 test failure 058fc04e3b47fcb8bc37251714a22ef2b50a5563
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/603)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/663)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/552)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/616)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/548)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/541)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay ad52d45

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok ad52d456cf18381cfcd5ddedc8f4acd7018281b7

**Comment by livecode-vulcan** [comment]
😎 test success ad52d456cf18381cfcd5ddedc8f4acd7018281b7
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/613)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/673)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/562)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/626)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/558)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/551)

**Pull request merged**
