### PR TITLE
Fix a memory leak when appending data to variables

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok ffce1e6

**Comment by peter-b** [comment]
@livecodefraser Please make sure that this gets merged up ASAP!

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ffce1e625935d86e1cef96384b7fd51fbb971c08

**Comment by livecode-vulcan** [comment]
😎 test success ffce1e625935d86e1cef96384b7fd51fbb971c08
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2136)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2144)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2129)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2145)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2151)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2157)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2167)

**Pull request merged**
