### PR TITLE
Update SQLite to 3.8.10.2

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok dd42694

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok dd42694b35c1e62f8ed60363704e57943c309f46

**Comment by runrevmark** [comment]
@livecode-vulcan review ok b236644

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok b23664492f0e312702ba96dd6817bbbe76099ff3

**Comment by livecode-vulcan** [comment]
😎 test success b23664492f0e312702ba96dd6817bbbe76099ff3
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/362)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/425)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/307)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/373)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/308)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/299)

**Pull request merged**
