### PR TITLE
[[Docs]] crlf - EOL delimiters made clear

### PR DESCRIPTION
**Pull request by seaniepie**
- Have separated the system End-Of-Line types out into bullets and made clearer and more consistent.

### CODE REVIEW

**Comment by peter-b** [comment]
@seaniepie You're doing again work here! Often when you need to make a bunch of very similar, small fixes it's most efficient  for us and for you to create a branch with several commits and submit it as a single PR rather than making one PR per one-word change. If you check out my blog about Hacktoberfest there's a link at the bottom to a neat interactive training course from GitHub that will help you learn how to do more with git.

**Comment by seaniepie** [comment]
You are right Peter. I did manage it with some of them you will notice, particularly the TransferModes. But some things were getting so messed up before that it made me very overly careful. But I'm sorry this is making more work for you than it should be - I fully understand. I will watch the video but they tend to work command-line and I am even more uncomfortable working that way than using the Web GUI and the desktop app - and then rarely show how to work between them and choose to only show CL workflow. When I learn I will make a video for others so they can benefit from it specific to LC.

**Comment by peter-b** [comment]
@seaniepie I think it's possible to get a lot done with the desktop app and the web interface -- but I'm an Old School Hacker and live in a terminal!  Would love to see a video when you get the chance to put one together. I'll almost certainly learn something from it.

**Comment by montegoulding** [comment]
@seaniepie this may help if you are interested in a reasonable git gui (sourcetree) https://www.youtube.com/watch?v=W14_fiRA6Wo

Also @livecodeian did a talk on using the GitHub app at the conference.

With regard to command line I watched a video the other day where someone was using a command line tool but the audience clearly wasn't comfortable in that space and he described it as text messaging your OS. Puts it in a different perspective I guess ;-)

**Comment by seaniepie** [comment]
Indeed. Terminal always reminds me of the 80s. I'm by far and away more comfortable in there than my colleagues in the tv and vfx industry. 
CL means you have to remember before you do - i.e. too many commands to remember. With a good GUI you can just 'do' and not have to remember how to 'do'. Bad GUI's you end up looking around trying to remember how to add an object or change it's appearance, etc. 
If you're not living the code every day like @peter-b and @livecodeali then you're going to forget all those commands. Even as a coder I'm far more a visual person. Good GUI's turn me on.

That link, @peter-b , on your blog is great for people creating their own repo but doesn't tell you how to link into the LC repo, best ways of working, doing what was suggested above about compiling work into branches before pushing, etc. It is a very poor tutorial as it basically 'tells' you to do a bunch of stuff rather than teach you. There's no explanation of why do it that way. It throws commands at you in a way that you won't remember. It even has a button to type the code in for you. All bad ways of teaching. I learnt very little that helps with our set up here. 
The course that it leads into looks marginally better but again is aimed at command line. 👎

**Comment by seaniepie** [comment]
@montegoulding , your video is really helpful. Thanks. It could probably do with more references to 'why' certain buttons were being clicked. A nube would find it hard to work out I could imagine. I'm sold on sourcetree linked with Atom though. It's frustrating there though that you still need to go into the Git website to actually send your PullRequest to the LC repo first time. I can see why but it's still frustrating. I did all of these recent repairs in the Web GUI itself (which is why in the end so many ended up in separate pulls).

**Comment by montegoulding** [comment]
@seaniepie glad you found it helpful. I did that unscripted (which is probably blatantly obvious!) so I probably didn't cover everything that needs to be covered. BTW I did this before we dropped the `comminuty-docs` branch so where I've used `community-docs` replace that with `develop`.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 5fd9bc0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 5fd9bc0ea71661659e3140fbd4e95400e5e1423a

**Comment by livecode-vulcan** [comment]
😎 test success 5fd9bc0ea71661659e3140fbd4e95400e5e1423a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/396)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/401)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/396)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/396)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/402)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/396)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/396)

**Pull request merged**
