### PR TITLE
[[ OpenSSL ]] Update prebuilt OpenSSL library to version 1.1.1g

### PR DESCRIPTION
**Pull request by livecodeian**
This patch updates the prebuilt OpenSSL library version to 1.1.1g.
Some updates to the Android portion of the build scripts are required due to changes in the
OpenSSL configuration process for Android.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok dbc148e

**Review by runrevmark — APPROVED** [review]

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok dbc148e2f7d73f0ace38cccb30894a1f790ed0df

**Comment by livecode-vulcan** [comment]
😞 test failure dbc148e2f7d73f0ace38cccb30894a1f790ed0df

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/786)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/195)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/195)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/195)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/195)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2312)
* try-community-universal-ios-iphoneos13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.4/builds/45)
* try-community-universal-ios-iphonesimulator13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.4/builds/46)
* try-community-universal-mac-macosx10.9: [pending](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2340)
* try-community-x86-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2328)
* try-community-x86_64-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2327)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2362)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2302)

**Comment by runrevmark** [comment]
@livecode-vulcan review not ok dbc148e

**Comment by livecode-vulcan** [comment]
💔 review by @runrevmark not ok dbc148e2f7d73f0ace38cccb30894a1f790ed0df

**Comment by livecodepanos** [comment]
This has failed in the linux builders, with error:
```
../../prebuilt/lib/linux/x86/libcustomcrypto.a(threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x22): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
```

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok fd28a88

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok fd28a88882824f3cb8d4655bf385764c9c278217

**Comment by livecode-vulcan** [comment]
😎 test success fd28a88882824f3cb8d4655bf385764c9c278217

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/792)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/201)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/201)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/201)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/201)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2318)
* try-community-universal-ios-iphoneos13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.4/builds/51)
* try-community-universal-ios-iphonesimulator13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.4/builds/52)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2346)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2334)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2333)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2368)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2308)

**Comment by livecodepanos** [comment]
Note: Do not merge this yet.

**Pull request merged**
