### PR TITLE
[[ Bug 15379 ]] Data input given to MCR_exec should remain data, to a…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…void a native-char to Unicode char conversion of its bytes

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 7e93917

**Comment by livecodesebastien** [comment]
We still have few issues with `ConvertToString`, probably everywhere it is called with a `DataRef` as input.
If data (like `numToByte(0xff)` output) is concatenated to a string, then we no longer have `0xff`, but `0x02C7`, its Unicode equivalent.
This is invisible at a display level, but when comparisons come, obviously things are going wrong.

Should `ConvertToString` be updated to use `MCStringCreateUnicodeStringFromData`?

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7e9391772f7a28bc930e35cf86efcbf0fcdb8551

**Comment by livecodesebastien** [comment]
Off-GitHub discussion: concatenating data to a string promotes the data as string (which make each byte a native char), and that's the expected behaviour.
The pull request needs no further work.

**Comment by livecode-vulcan** [comment]
😎 test success 7e9391772f7a28bc930e35cf86efcbf0fcdb8551
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/665)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/726)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/614)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/678)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/610)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/603)

**Pull request merged**
