### PR TITLE
[[ Bug 18041 ]] codeunit offset results should be 1 indexed

### PR DESCRIPTION
**Pull request by montegoulding**
This patch fixes codeunitOffset in all cases
and codepointOffset in cases where it is simplified
to codeunitOffset.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 7663b52

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7663b52cd394a2dbf895bc79073e961f0910e4ea

**Comment by peter-b** [comment]
@livecode-vulcan retry 7663b52

**Comment by livecode-vulcan** [comment]
😎 test success 7663b52cd394a2dbf895bc79073e961f0910e4ea
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2)

**Pull request merged**
