### PR TITLE
[[ Develop ]] Corrections to include command

### PR DESCRIPTION
**Pull request by asayd**
- Path parameter in syntax had a typo
- Deleted redundant use of absolute and relative in param description.
- Fixed minor typos.
- Added references.
- Hard wrapped.

### CODE REVIEW

**Comment by asayd** [comment]
@livecodeali Are we okay to start basing changes off the develop branch?

**Comment by montegoulding** [comment]
@asayd the only issue will be merge conflicts against the hard wrapping PR #4271. I can run the script again though so it isn't a huge issue but we do need to slot review and merge of that in between docs changes if we can.

**Comment by asayd** [comment]
@montegoulding Re wrapping. Oh, right! It's just become automatic for me when I submit a change to do the hard wrapping. Would it be easier if I were to delete this PR and resubmit without the hard wrapping?

**Comment by montegoulding** [comment]
@asayd no it won't make any difference as the hard wrapping script won't need to wrap docs that are already wrapped

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 4ad0e25

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4ad0e25dc841bce21974f4811f1148772a46b0f6

**Comment by livecode-vulcan** [comment]
😎 test success 4ad0e25dc841bce21974f4811f1148772a46b0f6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/10)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/10)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/10)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/10)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/10)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/10)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/10)

**Pull request merged**
