### PR TITLE
Fix issues with Mac localisation and icons

### PR DESCRIPTION
**Pull request by livecodesebastien**
And fixes bug 15572 as well

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 62cd77c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 62cd77c30f4c60c033527c80aa8d2ee9a78df752

**Comment by livecode-vulcan** [comment]
😞 test failure 62cd77c30f4c60c033527c80aa8d2ee9a78df752
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/537)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/596)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/486)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/550)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/482)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/475)

**Comment by livecodesebastien** [comment]
The CI failed from the random Windows failure - but since the Mac GYP configuration is the only thing that changed in this PR - and the Mac build succeeded - then the PR can be merged in.

**Pull request merged**
