### PR TITLE
[[ Bug 15056 ]] Fix read for x | x chars | x bytes

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodeali: How come this isn't a 7.0 bug also? I looked at the 7.0 code, and it seems to be slightly different... Did we fix something on develop which we should have back-ported to develop-7.0 previously?

**Comment by livecodeali** [comment]
It was a fix for a resource leak found by coverity:
https://github.com/runrevmark/livecode/commit/2620943c5417bd3ea83895d4d794e6fefdb3338e

I'm not sure any of these have been back-ported have they?

**Comment by runrevmark** [comment]
Ooops - so it was my fault ;)

That's fair enough - I was just checking - I'd forgotten I'd poked around in that code (should have had a look at git blame!).

Reviewed-by: @runrevmark.

**Comment by livecodeali** [comment]
Heh, well it was in quite a long list of coverity fixes, easy to forget!

**Pull request merged**
