### PR TITLE
[Bug 16154] Allow background audio on iOS

### PR DESCRIPTION
**Pull request by livecodepanos**
This PR comes together with its counterpart in the IDE:
https://github.com/livecode/livecode-ide/pull/561

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodepanos: I'd suggest that this be marked as 'experimental' on the check-box.

**Comment by runrevmark** [comment]
@livecodepanos: Could you add to the release note details of how to get this to work and its experimental status?

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9c4355c

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9c4355c20714e9f44ec8a31a24f23abee033bf0b

**Comment by livecode-vulcan** [comment]
😎 test success 9c4355c20714e9f44ec8a31a24f23abee033bf0b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/721)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/734)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/722)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/724)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/734)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/745)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/736)

**Pull request merged**
