### PR TITLE
Remove old font metrics

### PR DESCRIPTION
**Pull request by livecodefraser**
This PR removes all uses of the old font metrics from the engine. In doing so, problems with the pageRanges and other field measurement functions have been resolved.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 989fe6e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 989fe6e4355feb6f8d537cef79f82406d4c0a755

**Comment by livecode-vulcan** [comment]
😎 test success 989fe6e4355feb6f8d537cef79f82406d4c0a755
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1415)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1435)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1411)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1421)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1432)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1431)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1436)

**Comment by livecodefraser** [comment]
@peter-b merge conflict resolved (both of my font-related patches changed em-fonlist.cpp so I should have seen this coming!).

**Comment by peter-b** [comment]
@livecode-vulcan review ok adb0d43

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok adb0d438e43d5650046df731a0885b416a900cdd

**Comment by livecode-vulcan** [comment]
😎 test success adb0d438e43d5650046df731a0885b416a900cdd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1442)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1462)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1438)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1448)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1460)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1461)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1464)

**Pull request merged**
