### PR TITLE
[[ Bug 3537 ]] Make Unicode char typing sending the keyDown/Up messag…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…es on MacOS

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodesebastien - from the original bug report the key feature seemed to be whether the field is locked... How does the fix relate to that case?

**Comment by livecodesebastien** [comment]
If the text is locked, then com_runrev_livecode_MCWindowView::keyDown does not use inputContext, but handleKeyPress - which was doing the job properly.
The fix consists of avoiding to use finsertnew if the char > 127 - because all Unicode chars are > 127, but not all are IME.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok da18be1

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok da18be1d173dfd3416fe854ad136be1df1ebc45f

**Comment by runrevmark** [comment]
@livecode-vulcam review ok e05c1ef

**Comment by livecodesebastien** [comment]
@livecode-vulcan reviewed by @runrevmark ok e05c1ef

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok e05c1ef28ca63615f72a8a20a8af438cb869650f

**Pull request merged**
