### PR TITLE
[Bug 14659] LCB: Default variable values

### PR DESCRIPTION
**Pull request by runrevmark**
This branch adds the idea of 'default value' to types and default initialization to typed slots.

If a slot has a type, and the type has a default value then it will be initialized with that value on creation of its scope.

### CODE REVIEW

**Comment by peter-b** [comment]
Unit tests please. :smiley:

**Comment by peter-b** [comment]
To clarify: all the existing unit tests explicitly initialise the variables that they use.

**Comment by runrevmark** [comment]
Does that mean I should remove the explicit initialization from all the current unit-tests?

**Comment by peter-b** [comment]
@runrevmark No, I think it's okay to just add some unit tests to the `tests/lcb/vm/` directory that checks that types that are expected to receive default initialization actually get it.

Maybe `tests/lcb/stdlib/foreign.lcb` too, if you feel like it!

**Comment by peter-b** [comment]
I suspect that this needs a release note too, if only so that people know they don't need to do explicit initialization any more!

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevmark, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodeali** [comment]
This pull request still needs docs and release notes.

**Comment by peter-b** [comment]
Replaced by #4025.

**Pull request closed without merging**
