### PR TITLE
[[ Bug 13694 ]] Allow a maximum of 1024 form fields in POST request.

### PR DESCRIPTION
**Pull request by peter-b**
This is a partial fix for bug 13694 that prevents the most harmful
effects of the bug.

### CODE REVIEW

**Comment by livecodefraser** [comment]
Was the underlying issue solved or is this still relevant?

**Comment by peter-b** [comment]
@livecodefraser No, the underlying has not been addressed. Best practice is still to limit the number of form fields in a POST request.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 20a05e1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 20a05e17aadeecf1248e8ca9b4a80da2f2b02600

**Comment by livecode-vulcan** [comment]
😎 test success 20a05e17aadeecf1248e8ca9b4a80da2f2b02600
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/217)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/216)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/217)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/212)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/219)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/216)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/220)

**Pull request merged**
