### PR TITLE
[[ Bugfix 18282 ]] Prevent a crash after deleting a shared background group

### PR DESCRIPTION
**Pull request by livecodefraser**
The save code walks the object tree to check which version to use. Deleting a shared background group left a dangling pointer to the group in the list of card objects, causing a crash when saving.

---

This change is [Reviewable](https://reviewable.io/reviews/livecode/livecode/4437)

### CODE REVIEW

**Comment by peter-b** [comment]
Nice cleanup!

@livecode-vulcan review ok a2427d6

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[engine/src/mccontrol.h, line 377 [r1]](https://reviewable.io:443/reviews/livecode/livecode/4437#-KQ_nfB5rk1gPilNknLJ:-KQ_nfB5rk1gPilNknLK:bbv4lht) ([raw file](https://github.com/livecode/livecode/blob/a2427d604e4767828bdbf7218353b888677c86d6/engine/src/mccontrol.h#L377)):_

> ``` objc
> {
>     Chunk_term t_type = p_object->gettype();
>     MCAssert(t_type != CT_UNDEFINED && t_type != CT_STACK && t_type != CT_CARD && t_type != CT_AUDIO_CLIP && t_type != CT_VIDEO_CLIP);
> ```

BTW it would be great to wrap long lines like this in future for diff-viewing pleasure :wink: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4437#-:-KQ_p3EJKhsypXZ36oqW:bewm5ow)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a2427d604e4767828bdbf7218353b888677c86d6

**Comment by livecode-vulcan** [comment]
😞 test failure a2427d604e4767828bdbf7218353b888677c86d6
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/127)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/127)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/127)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/127)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/127)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/127)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/127)

**Comment by livecodeali** [comment]
_[engine/src/mccontrol.h, line 377 [r1]](https://reviewable.io:443/reviews/livecode/livecode/4437#-KQ_nfB5rk1gPilNknLJ:-KQ_wBU-GNRwSYoZo0_Q:b-ks1jee) ([raw file](https://github.com/livecode/livecode/blob/a2427d604e4767828bdbf7218353b888677c86d6/engine/src/mccontrol.h#L377)):_
<details><summary>

<i>Previously, peter-b (Peter TB Brett) wrote…</i></summary>



> BTW it would be great to wrap long lines like this in future for diff-viewing pleasure :wink: 
> </details>
> Should it be t_type >= CT_FIRST_CONTROL && t_type <= CT_LAST_CONTROL anyway? Perhaps there should be a utility function for that.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4437)_

**Comment by peter-b** [comment]
Review status: 27 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

_[engine/src/mccontrol.h, line 377 [r1]](https://reviewable.io:443/reviews/livecode/livecode/4437#-KQ_nfB5rk1gPilNknLJ:-KQ_x5Y58jWrgbMl9Sc2:b-6ws5b5) ([raw file](https://github.com/livecode/livecode/blob/a2427d604e4767828bdbf7218353b888677c86d6/engine/src/mccontrol.h#L377)):_
<details><summary>

<i>Previously, livecodeali (Ali Lloyd) wrote…</i></summary>



> Should it be t_type >= CT_FIRST_CONTROL && t_type <= CT_LAST_CONTROL anyway? Perhaps there should be a utility function for that.
> </details>
> @livecodeali Excellent spot!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4437)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok bdb860c

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4437#-:-KQa0WaigzSDpfo9qgEr:bammac1)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok bdb860cb0c1d60850ff1d3b8c21ad586ac930798

**Comment by livecode-vulcan** [comment]
😞 test failure bdb860cb0c1d60850ff1d3b8c21ad586ac930798
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/129)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/129)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/129)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/129)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/129)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/129)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/129)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 465f9c2

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 465f9c2788a963a69f85dcaa1c23dfff75f4f22f

**Comment by livecode-vulcan** [comment]
😎 test success 465f9c2788a963a69f85dcaa1c23dfff75f4f22f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/130)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/130)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/130)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/130)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/130)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/130)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/130)

**Pull request merged**
