### PR TITLE
[[ Bug 15432 ]] Make sure that the path is always canonical.

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
That re-instate the old way of solving the current folder-relative path, and simply adds a path resolution before doing this (that's the only way to avoid breaking anything).

**Comment by runrevmark** [comment]
I'm not sure I understand... MCS_get_canonical_path() _should_ return an absolute path. On Linux it calls MCS_resolvepath() - what case is this _not_ returning an absolute path?

**Comment by livecodesebastien** [comment]
No, if the stack is in the current directory, then `lstat64(tildepath, &buf)` (in MCS_resolvepath, in lnxspec.cpp) returns true, and the function returns the relative path.
To this point, I wonder if we want to fix it as it may break other things (and it works as expected on 7.0)

**Comment by livecodesebastien** [comment]
As decided offline, MCS_resolvepath should return an absolute path. Pull request closed, since it is not the proper fix.

**Pull request closed without merging**
