### PR TITLE
[[Dictionary]] Abbreviated.lcdoc - missing 'set'

### PR DESCRIPTION
**Pull request by seaniepie**
Description missing the 'set' command

### CODE REVIEW

**Comment by peter-b** [comment]
@seaniepie It would be great to turn "set" into a reference to the `set` command's dictionary entry!

**Comment by livecodeali** [comment]
@seaniepie Also this has `set command (command)` in the references which needs to be removed (or changed to `set (command)` if you go with Peter's suggestion)

**Comment by seaniepie** [comment]
I can't reopen it to edit. I'm out of my depth with GitHub

**Comment by peter-b** [comment]
Oh dear... it looks like you've deleted something and now it's showing this PR as coming from an `unknown repository`.  GitHub is broken. 😭   On the bright side, it looks like this PR is replaced by #4634, so I'm going to go ahead and close it.

**Pull request closed without merging**
