### PR TITLE
Gyp windows config tweaks

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
For consistency with other env variables used by `config.sh`, could you use `WIN_PERL` instead of `WIN32_PERL` please?

**Comment by peter-b** [comment]
@livecode-vulcan review ok af9f07e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok af9f07ea6599d781b884bf05e42bcf9f818f80b0

**Comment by livecode-vulcan** [comment]
😎 test success af9f07ea6599d781b884bf05e42bcf9f818f80b0
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/268)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/331)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/217)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/279)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/214)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/209)

**Pull request merged**
