### PR TITLE
[Bug 17666] Fix crash when getting the effective leftIndent/rightIndent/firstIndent

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodepanos Could you please add a regression test?

**Comment by livecodepanos** [comment]
I discovered a different (but related) bug while writing the tests. I will submit a fix asap. Setting this to WIP

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1f99fda

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1f99fdaa8ef222c35167f2b0188c36bcab2a3ac6

**Comment by livecode-vulcan** [comment]
😎 test success 1f99fdaa8ef222c35167f2b0188c36bcab2a3ac6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2502)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2512)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2495)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2513)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2519)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2523)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2535)

**Pull request merged**
