### PR TITLE
[[ Community Docs ]] Merge community docs

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 7612e66

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7612e662202875d4953ea9dabe3522955b95d79b

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 4639581

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4639581c589e7d506b4712a7cc07ca7eca2f979c

**Pull request merged**
