### PR TITLE
[[ BrowserWidget ]] OSX WebView browser implementation

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 9e96bf4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 9e96bf402962de2e728c733b5711f94cf95485b7

**Comment by livecode-vulcan** [comment]
😞 test failure 9e96bf402962de2e728c733b5711f94cf95485b7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1422)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1442)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1418)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1428)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1439)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1438)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1443)

**Comment by livecodeali** [comment]
I presume this just needs a kick.
@livecode-vulcan retry 9e96bf4

**Comment by livecode-vulcan** [comment]
😎 test success 9e96bf402962de2e728c733b5711f94cf95485b7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1436)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1456)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1432)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1442)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1454)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1454)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1458)

**Pull request merged**
