### PR TITLE
[[Docs]] ContributeToDocs update link references

### PR DESCRIPTION
**Pull request by seaniepie**

### CODE REVIEW

**Comment by livecodepanos** [comment]
Thanks @seaniepie :)

@livecode-vulcan review ok 5c6bc44

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 5c6bc448c51e90c3476c2675908999115f831d93

**Comment by seaniepie** [comment]
Wasn't there at some time also a doc on the markup for formatting? I've been looking for it and can't seem to find it now. The one that shows the characters to use to display notes, code and bullets, etc.

**Comment by livecode-vulcan** [comment]
😎 test success 5c6bc448c51e90c3476c2675908999115f831d93

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/143)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/135)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/135)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/135)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/135)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1657)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/39)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/39)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1687)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1680)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1677)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1713)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1654)

**Comment by livecodepanos** [comment]
@seaniepie do you mean this one? https://github.com/livecode/livecode/blob/develop/docs/development/docs_style_guide.md

**Comment by seaniepie** [comment]
No, this is of course very important. But I was thinking of a link perhaps to the GitHub markdown guide which shows _how_ to use the various characters like the chevron or underscore, etc, to format the doc.

**Pull request merged**
