### PR TITLE
[[ Community Docs ]] Processing Text and Data - minor fixes

### PR DESCRIPTION
**Pull request by asayd**
- Several formatting problems corrected.
- Added example for new replace ... preserving styles command.
- Pipe characters needed to be escaped in Regex table; they were throwing off the table formatting.
- Tables under "The Sort Container Command" section were malformed.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3294ebe

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3294ebece0b7f862515265bd3937f1482930c05d

**Comment by livecode-vulcan** [comment]
😞 test failure 3294ebece0b7f862515265bd3937f1482930c05d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2486)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2496)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2479)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2497)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2503)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2507)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2519)

**Comment by peter-b** [comment]
@livecode-vulcan retry 3294ebe

**Comment by livecode-vulcan** [comment]
😞 test failure 3294ebece0b7f862515265bd3937f1482930c05d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2487)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2497)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2480)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2498)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2504)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2508)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2520)

**Comment by peter-b** [comment]
Ugh Windows builder is getting stuck again...

@livecode-vulcan retry 3294ebe

**Comment by livecode-vulcan** [comment]
😎 test success 3294ebece0b7f862515265bd3937f1482930c05d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2488)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2498)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2481)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2499)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2505)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2509)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2521)

**Comment by peter-b** [comment]
@asayd Thanks for all these great documentation improvements!

**Pull request merged**
