### PR TITLE
Merge develop 9.0 24.07.18

### PR DESCRIPTION
**Pull request by livecodeali**
@livecode-vulcan review ok c8210a2

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok c8210a2c066e8ed5e26eb8763675277cd77d334d

**Comment by livecode-vulcan** [comment]
😞 test failure c8210a2c066e8ed5e26eb8763675277cd77d334d

* try-community-armv6-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/36)
* try-community-armv7-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/28)
* try-community-arm64-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/28)
* try-community-x86-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/28)
* try-community-x86_64-android-sdk26_ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/28)
* try-community-js-emscripten-sdk1.35: [failure](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1550)
* try-community-universal-ios-iphoneos11.4: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/77)
* try-community-universal-ios-iphonesimulator11.4: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/77)
* try-community-universal-mac-macosx10.9: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1580)
* try-community-x86-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1574)
* try-community-x86_64-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1570)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1607)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1547)

**Comment by livecodeali** [comment]
This needs submodules updated first.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3b37abc

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3b37abcc3dc0bddeac6f97988960dbd5646bac85

**Comment by livecode-vulcan** [comment]
😎 test success 3b37abcc3dc0bddeac6f97988960dbd5646bac85

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/48)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/40)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/40)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/40)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/40)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1562)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/89)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/89)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1592)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1586)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1582)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1619)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1559)

**Pull request merged**
