### PR TITLE
[Bug 13277] scalefactor doesn't change player size in browse mode

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodepanos - I wonder whether this is more to do with the fact we aren't mapping the size of the native layer correctly with scaleFactor != 1.0? Although this will certainly work if there isn't the infrastructure there yet to make it work in that way...

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a5343a7

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok a5343a7a22c0120da9401c4226a53773a536cfc1

**Comment by livecode-vulcan** [comment]
😞 test failure a5343a7a22c0120da9401c4226a53773a536cfc1
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1348)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1359)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1344)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1354)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1365)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1364)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1369)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9f0345c

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9f0345c967477f55fb4bd113d83adfa4650420c1

**Comment by livecode-vulcan** [comment]
😎 test success 9f0345c967477f55fb4bd113d83adfa4650420c1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1451)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1471)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1447)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1458)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1470)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1471)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1473)

**Pull request merged**
