### PR TITLE
Fix various issues with building the Android engine on OSX

### PR DESCRIPTION
**Pull request by livecodefraser**
These issues are specific to 8.0 as the addition of the LCB toolchain has complicated the build system and revealed some corner-cases.

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @livecodefraser, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 20bda6c

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 20bda6c52994ce6b4df39f15c57a82b3f5d95780

**Comment by livecode-vulcan** [comment]
😞 test failure 20bda6c52994ce6b4df39f15c57a82b3f5d95780
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/285)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/283)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/284)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/283)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/288)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/280)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/291)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 954235e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 954235e1816a7b5d4149499ace4a9f72540d3067

**Comment by livecode-vulcan** [comment]
😞 test failure 954235e1816a7b5d4149499ace4a9f72540d3067
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/287)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/285)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/286)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/285)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/290)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/282)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/293)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok af9304a

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok af9304a8b9213829d4f2935eee3f20271bdf0941

**Comment by livecode-vulcan** [comment]
😎 test success af9304a8b9213829d4f2935eee3f20271bdf0941
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/294)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/292)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/293)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/292)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/297)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/289)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/300)

**Pull request merged**
