### PR TITLE
[[ Bug 15723 ]] Add bugfix note

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
The fix is in the private repo.

**Comment by peter-b** [comment]
@livecodesebastien Please open a bug report! We should make sure that commercial-only release notes are stored in the commercial repository and release separate release notes documents... :tired_face:

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3c1dbbd

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3c1dbbd9b188918ee6d9b4b4f8bf6868294c65db

**Comment by livecodesebastien** [comment]
That PR is not necessary - the fix is commercial-only.

**Comment by livecode-vulcan** [comment]
😎 test success 3c1dbbd9b188918ee6d9b4b4f8bf6868294c65db
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/42)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/42)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/42)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/42)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/44)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/42)

**Pull request merged**
