### PR TITLE
[[Documentation]] Fixes to audioClip.lcdoc

### PR DESCRIPTION
**Pull request by asayd**
- Clarified types of audio data that an audioClip object may contain.
- Clarified that audio data may be imported or referenced in an external file.
- Added missing references and links to references.
- Added and enhanced examples.

### CODE REVIEW

**Comment by asayd** [comment]
@livecodeali @peter-b @montegoulding It seems to me that the audioClip entry is incomplete, since it doesn't mention that it can be used with external audio files. But the real question is, I suppose, is an external audio file really an audioClip? IOW, when `play audioClip` refers to an external rather than an imported clip, what is going on? Is a temporary audioClip object created to play the clip, or is the (optional) `audioClip` term simply ignored when playing an external file. 
This distinction may not mean much to the end user, but I'd like to not tell fibs in the dictionary.
- Devin

**Comment by livecodeali** [comment]
@asayd Yes a new temporary (or in the language of the engine, disposable) audioClip object is created which does not belong to a stack, it's just a global audio clip pointer - however this is also what happens with `play <filename>` (i.e. the `audioClip` is redundant when using that form of the play command)

**Comment by asayd** [comment]
@livecodeali Thanks for the clarification. That's what I was assuming as I revised the documentation, so I'll leave the changes as is.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok fb14790

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok fb147902fde67ca46bb41ccdba161471b0440f24

**Comment by livecode-vulcan** [comment]
😎 test success fb147902fde67ca46bb41ccdba161471b0440f24
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/270)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/274)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/270)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/270)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/274)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/270)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/270)

**Pull request merged**
