### PR TITLE
[[ bugfix 14295 ]] specialFolderPath("resources") added for 

### PR DESCRIPTION
**Pull request by livecodesebastien**
...de if needed (Mac standalone for instance).

This adds a new specialFolderPath("resources") for desktop platforms, returning the correct path where the resources are stored.
More info: see the feature-specialFolderPath-resources.md file.

There is another branch (runrevsebastien/bugfix-14295) in which specialFolderPath("resources") is only supported on Mac, in case we don't want to provide this for all platforms.

### CODE REVIEW

**Comment by runrevmark** [comment]
The internal redirect was only added as a temporary solution to help people get their apps working with the new rules for code inclusion until we could sort out the S/B and provide a better mechanism.

I've no problem with a specialFolderPath("resources") idea - this should return the folder into which the S/B has copied the resource files the user specified. (Some consideration needs to be done for the IDE however). However it is important that if this is to be useful it is uniform on all platforms (in terms of you shouldn't have to do any per-platform fiddling to access S/B included files).

Obviously code and non-code resources might be in different places, so we perhaps need a separate SFP for code resources.

I suggest chatting to Ali about the S/B changes he is currently making and making this part of that work.

The goal should be that after Ali's changes to the S/B that users can update their applications to use 'specialFolderPath(??)' to resolve paths to things included by the S/B and we can deprecate and then remove the Mac-only Code -> Resources/_MacOS redirection.

**Comment by livecodesebastien** [comment]
That is the idea of what I've pushed here - no need anymore, for the LiveCoder, to do the redirection by themselves.
I'll see with Ali once he's done, and update the location returned (and probably add it for the mobile) - that's pretty unfinished for now.

**Comment by livecodesebastien** [comment]
Hi Mark, any executable file is copied alongside the engine - do we actually need a 'code resource' SFP?

**Comment by runrevmark** [comment]
Hi Seb - yes, I think an 'executables' folder path might be a good idea as the analog to 'resources'

**Comment by runrevmark** [comment]
Add the 'executables' SFP as a separate pull request.

This one looks good (I suggest filing an enhancement request about integrating this with the S/Bs notion of 'resource path' which Ali worked on; and then we can remove the auto-redirection on Mac eventually).

Reviewed-by: @runrevmark.

**Pull request merged**
