### PR TITLE
Use lc-compile's --deps option to handle extension dependencies

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok bd52e1a

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1efe208

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1efe2087f0b9924caf6bd4b8e8441f227ca8aafd

**Comment by peter-b** [comment]
:sob:

@livecode-vulcan review ok 690794b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 690794b52cb98beeaa4fdbc3dc238e60a4e73bee

**Comment by livecode-vulcan** [comment]
😎 test success 690794b52cb98beeaa4fdbc3dc238e60a4e73bee
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/291)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/354)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/237)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/302)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/237)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/229)

**Pull request merged**
