### PR TITLE
srvmain compiles with no warnings

### PR DESCRIPTION
**Pull request by mwieder**
Since I was looking into srvmain.cpp anyway, I fixed the compiler warnings.

### CODE REVIEW

**Comment by peter-b** [comment]
@mwieder Next time you make a pull request, could you please try and make sure that your commit messages and your pull request title and description follow [these guidelines](http://chris.beams.io/posts/git-commit/)?  Thanks. :smile: 

@livecode-vulcan review ok f41af5c

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f41af5cba505c93b5bd0c4e25b734d20e806451b

**Comment by mwieder** [comment]
LOL

**Comment by peter-b** [comment]
What's funny?

**Comment by livecode-vulcan** [comment]
😎 test success f41af5cba505c93b5bd0c4e25b734d20e806451b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2199)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2206)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2192)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2208)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2213)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2219)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2230)

**Comment by mwieder** [comment]
Well, first of all, I see myself in the xkcd cartoon. But what would you rather have as a commit message for this PR? "I fixed the code so that the compiler doesn't issue warnings any more" doesn't seem any more descriptive to me. The title, btw, was created by github and I didn't see a reason to change it.

**Comment by peter-b** [comment]
- Ideally the commit message would be something that can be added onto the end of, "When this commit is merged, it will...".  So, for example a good commit summary would have been, "Fix warnings in server startup and main loop."
- If you look at the other pull requests and commits, it's usual practice to give the summary line a prefix that describes the subsystem or area of code that's affected.  In this case, "server" would be a decent description
- You say that your changes fix compile warnings, but you haven't specified on which platform the compile warnings occurred or what the warnings that you've fixed were.  We use a lot of different compilers -- and compiler settings -- and what might be a warning on one platform might be completely fine on another.

So, putting that all together, I would have probably written a commit message that looked something like:

``` markdown
server: Fix some Linux build warnings in startup & main loop.

* Don't try to run main script handler unless it was parsed successfully.
* Use correct type to avoid signed-unsigned comparison
```

I hope that helps!

**Comment by mwieder** [comment]
@peter-b OK - that makes sense. I should point out, though, that the last time I submitted a PR to quash compiler warnings and had those kind of details you had me pull them out.

**Comment by peter-b** [comment]
@mwieder I asked you to remove them from the in-line comments _in the code_! The right place for that information is in the git commit log message.

**Comment by mwieder** [comment]
@peter-b OK. I get it. Does make more sense to me, though, to have the comments next to the code they apply to, rather than making a reviewer have to piece it together. But in any event, that's why I left out comments here like "I changed an int to a uint to avoid compiler warnings".

**Comment by peter-b** [comment]
@mwieder The general principle I apply is that there are two sorts of comment:
1. if I'm describing the _current state_ of the code, then I add in-line comments
2. if I'm describing how the code _arrived at_ it's current state, that info goes in commit messages

There are obviously exceptions -- for example, if the current state of the code _cannot_ be understood without some historical details then I make sure the comments in the code the info required.

Another way to think about it is to think of the code as a textbook. Occasionally, you release a new edition of the textbook (you make a git commit). Now, you wouldn't annotate every amended paragraph in the new edition (the source code) with exact details of how and why you changed it's content; you'd put that info in the front matter (the commit message).

**Comment by mwieder** [comment]
Thanks! I'll try to keep these in mind going forward.

**Pull request merged**
