### PR TITLE
[[ Bug 16006 ]] Output a type field to a module manifest

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3a0f20f

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 3a0f20f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 3a0f20f9ac0d8c566da4ac8a53d9d97535d65eda

**Comment by livecodeali** [comment]
Needs a bugfix note :-)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok bae4f04

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok bae4f04b0561e0c57201e9f59506d8b39c1167a3

**Comment by livecode-vulcan** [comment]
😎 test success bae4f04b0561e0c57201e9f59506d8b39c1167a3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/454)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/454)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/453)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/452)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/458)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/449)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/460)

**Pull request merged**
