### PR TITLE
Resolves regression on android third party lib inclusion

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok ed4a06d

**Comment by peter-b** [comment]
@montegoulding Is there an associated bug report for this?

**Comment by montegoulding** [comment]
Only in my mergExt ticket which aren't public

**Comment by peter-b** [comment]
@montegoulding Well, the change looks probably correct.

@livecode-vulcan review ok ed4a06d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ed4a06df8b73165cc0f0566ab534951f64e36aa2

**Comment by livecode-vulcan** [comment]
😎 test success ed4a06df8b73165cc0f0566ab534951f64e36aa2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1664)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1680)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1659)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1670)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1681)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1683)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1688)

**Pull request merged**
