### PR TITLE
[[ Bug 12876 ]] make the installer calls the right LiveCode exec name

### PR DESCRIPTION
**Pull request by livecodesebastien**
The executable name still had its spaces removed, and was lowercased - which does
not comply with the new naming.

This pull request is targeted against develop-6.7, even though it will only affect LiveCode >= 7: we want to keep the binary stacks synchronised between 6.7 and 7

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Diff for `installer.rev`:
https://gist.github.com/livecodesebastien/16c3804f83bf5906494e

**Comment by livecodesebastien** [comment]
New diff: https://gist.github.com/livecodesebastien/c2c4aae2445e07bea399

**Comment by peter-b** [comment]
@livecode-vulcan review ok e59ada0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e59ada044d8f8efa5e8459ed52fccf9678198bfe

**Comment by livecode-vulcan** [comment]
😎 test success e59ada044d8f8efa5e8459ed52fccf9678198bfe
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/535)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/539)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/534)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/534)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/543)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/537)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/545)

**Pull request merged**
