### PR TITLE
[[ Xcode 7.0 ]] Make compilation possible with Xcode 7.0

### PR DESCRIPTION
**Pull request by livecodesebastien**
Fix few issues with iOS deployment with Xcode 7.0
Take into account the new build option ENABLE_BITCODE
Add iOS 9.0 and Xcode 7.0 amongst the usable SDKs / Xcode version for MacOSX 10.11
Add iphoneos9.0 and iphonesimulator9.0 targets in Makefile
Ensure that iOS 9.0 targets are only added if Xcode 7.0 is installed

### CODE REVIEW

**Comment by livecodefraser** [comment]
Looks like Xcode 7.0 runs on OSX 10.10.4, now that it has gone GM. This PR will need to be updated to allow building iOS9 standalones on Mavericks too.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1c423a9

Thank you for dealing with all my niggly comments, @livecodesebastien! :+1:

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1c423a90d688c9c999949047795640a8ff90607f

**Comment by livecode-vulcan** [comment]
😞 test failure 1c423a90d688c9c999949047795640a8ff90607f
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/390)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/390)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/389)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/388)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/393)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/385)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/396)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry  1c423a9

**Comment by livecode-vulcan** [comment]
😎 test success 1c423a90d688c9c999949047795640a8ff90607f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/391)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/391)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/390)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/389)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/395)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/386)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/397)

**Pull request merged**
