### PR TITLE
[[ Bug 18610 ]] Add release note

### PR DESCRIPTION
**Pull request by techstrategies**

### CODE REVIEW

**Comment by livecodeali** [comment]
@techstrategies Was that also in this update? https://github.com/livecode/livecode/pull/5017

**Comment by techstrategies** [comment]
@livecodeali Yes, that was also part of the version 1.2.6 update.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 86364a6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 86364a6f978b77430fcc5822a329862789cb5d77

**Comment by livecode-vulcan** [comment]
😎 test success 86364a6f978b77430fcc5822a329862789cb5d77

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/789)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/794)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/787)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/788)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/794)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/786)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/786)

**Pull request merged**
