### PR TITLE
Merge develop 8.1 07.07.2017

### PR DESCRIPTION
**Pull request by livecodepanos**
Conflicts in `ide` (trivial) and `Installer/package.txt`:
```
//////////

component Externals.CEF.Linux
	into [[TargetFolder]]/Externals/CEF place
<<<<<<< HEAD
		executable linux-[[TargetArchitecture]]:Externals/CEF/libcef.so
		executable linux-[[TargetArchitecture]]:Externals/CEF/libffmpegsumo.so
		executable linux-[[TargetArchitecture]]:Externals/CEF/libpdf.so
		rfolder linux-[[TargetArchitecture]]:Externals/CEF/locales
		file linux-[[TargetArchitecture]]:Externals/CEF/cef.pak
		file linux-[[TargetArchitecture]]:Externals/CEF/cef_100_percent.pak
		file linux-[[TargetArchitecture]]:Externals/CEF/cef_200_percent.pak
		file linux-[[TargetArchitecture]]:Externals/CEF/cef_extensions.pak
=======
		executable linux-[[TargetArchitecture]]:revbrowser-cefprocess
		executable linux-[[TargetArchitecture]]:libbrowser-cefprocess
		executable linux-[[TargetArchitecture]]:CEF/libcef.so
		rfolder linux-[[TargetArchitecture]]:CEF/locales
		file linux-[[TargetArchitecture]]:CEF/cef.pak
		file linux-[[TargetArchitecture]]:CEF/cef_100_percent.pak
		file linux-[[TargetArchitecture]]:CEF/cef_200_percent.pak
		file linux-[[TargetArchitecture]]:CEF/cef_extensions.pak
		file linux-[[TargetArchitecture]]:CEF/icudtl.dat
		file linux-[[TargetArchitecture]]:CEF/natives_blob.bin
		file linux-[[TargetArchitecture]]:CEF/snapshot_blob.bin
>>>>>>> upstream/develop-8.1
	// Horrible workaround for a libCEF bug
	into [[TargetFolder]] place
		file linux-[[TargetArchitecture]]:icudtl.dat
		file linux-[[TargetArchitecture]]:natives_blob.bin
		file linux-[[TargetArchitecture]]:snapshot_blob.bin
		executable linux-[[TargetArchitecture]]:revbrowser-cefprocess
		executable linux-[[TargetArchitecture]]:libbrowser-cefprocess

```

Resolved this by keeping the `develop` version of this file and removing the `libpdf.so` and `libffmpegsumo.so` references from `Installer/package.txt`

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 9128ad8

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 9128ad8884d5cc27604226293c09c223c5c37d99

**Comment by livecode-vulcan** [comment]
😞 test failure 9128ad8884d5cc27604226293c09c223c5c37d99

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/461)
* try-community-armv6-android-api9: [pending](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/469)
* try-community-js-emscripten-sdk1.35: [pending](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/448)
* try-community-universal-ios-iphoneos10.3: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/391)
* try-community-universal-ios-iphonesimulator10.3: [pending](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/393)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/456)
* try-community-universal-mac-macosx10.9: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/461)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/459)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/473)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/459)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/468)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/486)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/455)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b42605e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b42605e3dd863f2d20fb7d73847e488297c000c7

**Comment by livecode-vulcan** [comment]
😎 test success b42605e3dd863f2d20fb7d73847e488297c000c7

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/462)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/470)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/449)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/392)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/394)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/457)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/462)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/460)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/474)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/460)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/469)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/487)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/456)

**Pull request merged**
