### PR TITLE
[[ Bug 15966 ]] Remove unused effect "opacity" property

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 577c934

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 577c934aeae87a37e6a79babfd5494a9dbd3ae26

**Comment by livecode-vulcan** [comment]
😎 test success 577c934aeae87a37e6a79babfd5494a9dbd3ae26
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/418)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/418)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/417)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/416)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/422)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/413)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/424)

**Comment by livecodeali** [comment]
@livecodeian can you fix the merge conflict here please?

**Comment by livecodeian** [comment]
@livecodeali done!

**Comment by livecodeali** [comment]
Thanks!
@livecode-vulcan review ok 7644ec9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7644ec9b32fea01f04e45dac9d0a446c212bfb75

**Comment by livecode-vulcan** [comment]
😎 test success 7644ec9b32fea01f04e45dac9d0a446c212bfb75
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/505)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/509)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/504)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/504)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/513)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/506)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/515)

**Pull request merged**
