### PR TITLE
[[ Bug 16294 ]] Change linux printing to use the pdf printer

### PR DESCRIPTION
**Pull request by runrevmark**
The Linux printing mechanism has always used a custom PostScript output
to perform its function. However, updating the implementation to work
well (in particular with Unicode and transparency) would duplicate the
work that the PDF printing mechanism already does.

Given that the Linux printing stack will happily accept PDF as well as
PostScript, it makes more sense to update the Linux printer to use the
existing PDF printing mechanism (at least until such time comes that
we can update it to use GTK's cairo based printing model).

This patch hooks up MCPSPrinter to a pdf MCCustomPrinter meaning that
PDF gets generated rather than PostScript.

Tweaks have also been made to the GTK print dialog integration to
reflect this.

Note: Print settings and page settings on linux do not work correctly
as it stands, this needs more work. In particular, the orientation of
paper does not 'stick' correctly.

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevmark And the award for "most informatively-named PR" goes to... :laughing:

**Comment by livecodefraser** [comment]
Well, I understood it perfectly :stuck_out_tongue:

**Comment by mwieder** [comment]
LOL

**Comment by runrevmark** [comment]
@peter-b: The title is perhaps a little more descriptive now ;)

**Comment by peter-b** [comment]
@runrevmark And you've even erased the evidence! :100:

**Comment by runrevmark** [comment]
@peter-b: I don't know what you mean... No history re-writing here... No sir ;)

**Pull request closed without merging**
