### PR TITLE
[[ Bugfix 15685 ]] Fix the casing of the OSX standalone engine path

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok c548e08

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok c548e089671cb46fb0bd25ddecdb1fd7cb8043e6

**Comment by livecode-vulcan** [comment]
😎 test success c548e089671cb46fb0bd25ddecdb1fd7cb8043e6
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2)

**Comment by peter-b** [comment]
@livecodefraser Should this be targeted to release-6.7.7 for the 6.7.7-rc-3 milestone?

**Pull request closed without merging**
