### PR TITLE
[ CID 15041 ] Fix Incorrect Expression Coverity issue

### PR DESCRIPTION
**Pull request by livecodeian**
Invalid comparison in VectorFieldPropType::equal() could lead to false positive when first argument list is empty.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian I think you've added engine/src/stack.cpp.orig by mistake!

@livecode-vulcan review not ok e8c91a3

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok e8c91a30235123b95d1bb5ee3f0115e2fe31f96c

**Comment by livecodeian** [comment]
@peter-b I've sorted that now.

**Comment by peter-b** [comment]
@livecodeian Thanks!

@livecode-vulcan review ok 371a885

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 371a885a961fefbff3e0df48517f5f0b45e23b17

**Comment by livecode-vulcan** [comment]
😎 test success 371a885a961fefbff3e0df48517f5f0b45e23b17
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2363)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2373)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2356)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2374)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2380)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2384)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2396)

**Pull request merged**
