### PR TITLE
Merge develop 7.0 29.07.15

### PR DESCRIPTION
**Pull request by livecodeali**
Conflicts:
- docs/dictionary/keyword/dollar.xml

Regenerated .lcdoc dictionary files from .xml
- engine/src/executionerrors.h

Use develop-7.0 error numbers and shift 8.0 specific ones up 
- engine/src/image_rep.cpp

Variable naming difference in develop vs 7.0 m_bitmap_frames was m_locked_frames
- engine/src/lnxdc.cpp

Some class members added in develop, kept both changes
- prebuilt/fetch-libraries.sh
- prebuilt/package-libs.sh

Refactoring of prebuilt lib scripts, accepted the 7.0 changes and adjusted the CEF library version in prebuilt/versions/cef

### CODE REVIEW

**Comment by livecodefraser** [comment]
Looks like we don't have any .lcdoc files for the floor and ceil functions, but otherwise seems fine

**Comment by livecodeali** [comment]
I already did them, I can't quite remember when though. I forgot to remove the xml at the time, so confusingly did it in this merge, sorry.

(proof: :smile: https://github.com/livecodeali/livecode/blob/merge-develop_7.0_29.07.15/docs/dictionary/function/ceil.lcdoc https://github.com/livecodeali/livecode/blob/merge-develop_7.0_29.07.15/docs/dictionary/function/floor.lcdoc)

**Comment by livecodefraser** [comment]
If you're sure ;)

@livecode-vulcan review okay f590956

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok f59095646f0842b5281f0b5be6bf088f3fefbddd

**Comment by livecode-vulcan** [comment]
😎 test success f59095646f0842b5281f0b5be6bf088f3fefbddd
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/722)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/782)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/672)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/736)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/667)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/659)

**Pull request merged**
