### PR TITLE
[[ Bug 22084 ]] Fix extension release note edition section

### PR DESCRIPTION
**Pull request by montegoulding**
This patch changes the release builder to interrogate the extension's built API file
to determine the documented edition the extension will be available in.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok e4c3790

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok e4c37909d41421e66c38e5eb075ba3a4a3ebe90f

**Comment by livecode-vulcan** [comment]
😭 test error e4c37909d41421e66c38e5eb075ba3a4a3ebe90f

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/546)
* try-community-armv7-android-sdk26_ndk16r15: [error](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/538)
* try-community-arm64-android-sdk26_ndk16r15: [error](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/538)
* try-community-x86-android-sdk26_ndk16r15: [error](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/538)
* try-community-x86_64-android-sdk26_ndk16r15: [error](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/538)
* try-community-js-emscripten-sdk1.35: [error](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2060)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/288)
* try-community-universal-ios-iphonesimulator12.1: [error](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/287)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2092)
* try-community-x86-linux-debian8: [error](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2082)
* try-community-x86_64-linux-debian8: [error](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2080)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2115)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2052)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry e4c3790

**Comment by livecode-vulcan** [comment]
😎 test success e4c37909d41421e66c38e5eb075ba3a4a3ebe90f

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/552)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/544)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/544)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/545)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/544)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2066)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/293)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/293)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2097)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2088)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2086)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2121)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2058)

**Pull request merged**
