### PR TITLE
[[ Bug 19476 ]] Add MCProperListCreateWithForeignValues

### PR DESCRIPTION
**Pull request by runrevmark**
This patch adds a constructor for proper lists which takes a
sequence of foreign value contents (e.g. uint8_t[]) and converts
them into a proper list. If the values are bridgeable then it does
bridging, otherwise it just stores boxes.

Note: No release note because it is an internal API addition.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3312270

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3312270c645d21bedad5f271ba5bed202e0f6390

**Comment by livecode-vulcan** [comment]
😞 test failure 3312270c645d21bedad5f271ba5bed202e0f6390

* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/6)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/6)
* try-community-js-emscripten: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten/builds/13)
* try-community-universal-ios-iphoneos10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.2/builds/11)
* try-community-universal-ios-iphonesimulator10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.2/builds/11)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/5)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/7)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/9)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/11)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/9)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/11)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/11)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/10)

**Comment by peter-b** [comment]
@livecode-vulcan retry 3312270

**Comment by livecode-vulcan** [comment]
💥 merge conflict 3312270c645d21bedad5f271ba5bed202e0f6390 → 14f9273000cd4f8fa6aee0e6a64bbf4eabd0db06

**Comment by runrevmark** [comment]
@livecode-vulcan retry 3312270

**Comment by livecode-vulcan** [comment]
💥 merge conflict 3312270c645d21bedad5f271ba5bed202e0f6390 → 14f9273000cd4f8fa6aee0e6a64bbf4eabd0db06

**Comment by runrevmark** [comment]
@livecode-vulcan retry dfaf5dc

**Comment by runrevmark** [comment]
@livecode-vulcan review ok dfaf5dc

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok dfaf5dc236f46014cbcdccbe3245a67afb5688c8

**Comment by livecode-vulcan** [comment]
😎 test success dfaf5dc236f46014cbcdccbe3245a67afb5688c8

* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/10)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/10)
* try-community-js-emscripten: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten/builds/17)
* try-community-universal-ios-iphoneos10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.2/builds/15)
* try-community-universal-ios-iphonesimulator10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.2/builds/15)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/9)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/11)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/13)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/15)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/13)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/15)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/15)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/14)

**Pull request merged**
