### PR TITLE
Use more native-looking themes on desktop platforms by default

### PR DESCRIPTION
**Pull request by livecodefraser**
Our current "native" themes can differ quite substantially from the look of actual native applications. This PR disables the "backwards compatible" flag added to the new 8.0 theming code and further tweaks the "native" theme to be more accurate to modern HIGs for our desktop platforms.

[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode/3447)

### CODE REVIEW

**Comment by peter-b** [comment]
Does any of the new theme-related syntax work with HTML5?  If so, please do add it to the "OS" field in the dictionary. :wink: 

---

Reviewed 43 of 47 files at r1.
Review status: 42 of 46 files reviewed at latest revision, 5 unresolved discussions.

---

_[docs/notes/feature-native_appearance.md, line 3 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3447#-K8439NvL0N4tua_rxm8:-K8439NvL0N4tua_rxm9:-63474189) ([raw file](https://github.com/livecode/livecode/blob/b95faf78edd4dc16f3e11ad8fcd6a78d1b059929/docs/notes/feature-native_appearance.md#L3)):_
Please only add `version` overrides in release notes when you need to (e.g. when fixing up release note fragments that were added in a previous release).

---

_[engine/src/object.h, line 113 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3447#-K847r4VCpthyhUvaA3h:-K847r4VCpthyhUvaA3i:-452955621) ([raw file](https://github.com/livecode/livecode/blob/b95faf78edd4dc16f3e11ad8fcd6a78d1b059929/engine/src/object.h#L113)):_
I think it would might be helpful to add a comment here explaining the interpretation of "empty", "native" and "legacy".

---

_[engine/src/object.h, line 173 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3447#-K847mQ-xBHZq7ix81p8:-K847mQ0zC7ZiXkAUKXL:-219615225) ([raw file](https://github.com/livecode/livecode/blob/b95faf78edd4dc16f3e11ad8fcd6a78d1b059929/engine/src/object.h#L173)):_
Please add an explanatory comment for this flag!

---

_[engine/src/object.h, line 419 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3447#-K8484ShxAHuOSRzpbEM:-K8484ShxAHuOSRzpbEN:-1945250519) ([raw file](https://github.com/livecode/livecode/blob/b95faf78edd4dc16f3e11ad8fcd6a78d1b059929/engine/src/object.h#L419)):_
Please document the `force` flag -- what's the difference in behaviour if `force` is true?

---

_[engine/src/object.h, line 1245 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3447#-K848aPBFJLlz7iFpMHL:-K848aPBFJLlz7iFpMHM:1374066440) ([raw file](https://github.com/livecode/livecode/blob/b95faf78edd4dc16f3e11ad8fcd6a78d1b059929/engine/src/object.h#L1245)):_
It would probably be a good idea to mention that this returns the _computed_ theme (i.e. taking into account parent controls / defaults / etc. )

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3447#-:-K842zjSq7WuYeCo5Ebx:284231449)_

**Comment by livecodefraser** [comment]
Before and after. Still not perfect, but (I think) better than it was.

fraser jan 2016

**Comment by peter-b** [comment]
@livecode-vulcan review ok 2515191

---

Reviewed 2 of 47 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3447#-:-K8KiH88bygU7XNcN7X_:-398767166)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2515191304c4de09640a48653f387bafd1bd8269

**Comment by livecode-vulcan** [comment]
😞 test failure 2515191304c4de09640a48653f387bafd1bd8269
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1594)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1613)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1590)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1601)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1614)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1615)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1617)

**Comment by livecodefraser** [comment]
Oops, had a few more changes that I'd forgotten to commit. These have been added now.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 107b6f4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 107b6f403b37158e34d78dc50440a9836d439494

**Comment by livecode-vulcan** [comment]
😞 test failure 107b6f403b37158e34d78dc50440a9836d439494
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1634)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1650)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1629)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1640)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1651)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1653)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1658)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 107b6f4

**Comment by livecode-vulcan** [comment]
😞 test failure 107b6f403b37158e34d78dc50440a9836d439494
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1647)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1663)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1642)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1653)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1664)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1666)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1671)

**Comment by livecodefraser** [comment]
@livecodeali updated to (hopefully) fix the Windows compilation issue.

**Comment by livecodeali** [comment]
I suspect this one is up to mr vulcanbot to 'review'
@livecode-vulcan review ok fd75fd7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok fd75fd760064aea55dda6deb4d2e4f4bd8cc8272

**Comment by livecode-vulcan** [comment]
😎 test success fd75fd760064aea55dda6deb4d2e4f4bd8cc8272
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1650)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1666)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1645)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1656)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1667)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1669)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1674)

**Pull request merged**
