### PR TITLE
Clean up old release notes

### PR DESCRIPTION
**Pull request by peter-b**
- Add a new tool for deleting old release notes (i.e. for changes released in major versions other than the current one)
- Delete 1755 old release notes from LiveCode < 8.0.0.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 88e5dd2

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 88e5dd2b74699a729f04e18752cfb7c2b59237f1

**Comment by peter-b** [comment]
@livecode-vulcan reviewed by @runrevmark ok 4065aa6
...without screwing with the ide submodule pointer this time.

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 4065aa6e77da92dbc954843d7a2db067e7c98e5f

**Comment by livecodeali** [comment]
@livecode-vulcan review ok ddae887

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok ddae887e9bf7b776ef3b1c03e610a3ccd6d2a9a0

**Comment by livecode-vulcan** [comment]
😎 test success ddae887e9bf7b776ef3b1c03e610a3ccd6d2a9a0
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2756)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2765)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2751)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2767)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2773)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2777)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2795)

**Pull request merged**
