### PR TITLE
[Bug 18743] Fix references in "keys" docs (and slightly reorganise)

### PR DESCRIPTION
**Pull request by peter-b**
- Fix a broken cross-reference
- Move notes/tips into the description section

### CODE REVIEW

**Comment by livecodeali** [comment]
The sort command reference is also fixed in develop [here](https://github.com/livecode/livecode/commit/53004c5ada7d4cffe382cbdc2ce64f64a18622bc)...

**Comment by peter-b** [comment]
@livecodeali I've rebased this PR on `develop` and resolved the conflicts.

**Comment by livecodeali** [comment]
@peter-b ta!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3b8a7a7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3b8a7a7c1c4bc0d0d762c990f83a242c931abf59

**Comment by livecode-vulcan** [comment]
😎 test success 3b8a7a7c1c4bc0d0d762c990f83a242c931abf59
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/614)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/619)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/614)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/618)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/623)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/615)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/615)

**Pull request merged**
