### PR TITLE
[[ Bug 17828 ]] Clamp player slider to track bounds

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok d0929c0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d0929c087720634325a0a9c0d9d37f9fd3f6c42f

**Comment by livecode-vulcan** [comment]
😞 test failure d0929c087720634325a0a9c0d9d37f9fd3f6c42f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2646)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2656)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2641)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2657)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2663)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2669)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2681)

**Comment by livecodeian** [comment]
The vulcan build timed out:
command timed out: 600 seconds without output running ['/bin/sh', '-c', "wine cmd /K '..\make.cmd'; r=$?; wineserver -k -w; exit $r"], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=1166.012100

**Comment by livecodefraser** [comment]
@livecode-vulcan retry d0929c0

**Comment by livecode-vulcan** [comment]
😎 test success d0929c087720634325a0a9c0d9d37f9fd3f6c42f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2649)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2659)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2644)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2660)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2666)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2672)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2684)

**Pull request merged**
