### PR TITLE
[[ Bug 18306 ]] Allow android externals without java classes to load

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
@peter-b should this be retargeted at 8.2?

**Comment by peter-b** [comment]
@montegoulding No, this is fine

@livecode-vulcan review ok 724615c

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 724615c79fb998c5dea4c9c6e18e684943be782b

**Comment by livecode-vulcan** [comment]
😎 test success 724615c79fb998c5dea4c9c6e18e684943be782b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/146)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/150)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/146)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/146)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/146)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/146)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/146)

**Pull request merged**
