### PR TITLE
[[ Bug 22683 ]] Fix incorrectly placed and sized characters in HTML5 standalones

### PR DESCRIPTION
**Pull request by livecodeian**
This patch fixes bug 22683, where faulty text metrics in the embedded font file were causing characters to appear incorrectly scaled or positioned.

Closes https://quality.livecode.com/show_bug.cgi?id=22683

### CODE REVIEW

**Review by runrevmark — COMMENTED** [review]
@livecodeian I take it the change in filename of the font doesn't matter - the S/B just treats all .ttf files as built in fonts?

**Comment by livecodeian** [comment]
@runrevmark Yes, the engine is not looking for a specific hardcoded font file so the name change doesn't matter.

**Review by runrevmark — APPROVED** [review]

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 6ab733f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 6ab733f68ac929eb16ecaba6bd7435144bc0c0a7

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 6ab733f

**Comment by livecodepanos** [comment]
1. The vulcan tests have all passed, BUT 
2. vulcan has not reported back to GitHub.

I am merging it now, and will investigate (2)

**Pull request merged**
