### PR TITLE
Merge develop 8.1 22.02.2017

### PR DESCRIPTION
**Pull request by livecodepanos**
Conflicts in:
`engine/src/dispatch.cpp` and `libscript/src/script-instance.cpp`

Resolution:
In `engine/src/dispatch.cpp` kept the `develop-8.1` version, which includes the changes described in this commit: https://github.com/livecode/livecode/commit/a1eb36fdb4465e969bf11c8b9b39b0d493af041b

In `libscript/src/script-instance.cpp`, kept the `develop` version. Actually `script-instance.cpp` should be unchanged in `develop` after merging that commit, since there is a new VM implementation in `develop`.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodepanos The conflict in dispatch.cpp was caused by https://github.com/livecode/livecode/commit/c92fa3447bc8a0a0ff8dee728424a5228a05a14c and https://github.com/livecode/livecode/commit/bfd72eafc69d23c0ff04b1a2bf9897b77a425661,
so I think you'll have to apply these changes again in the merge.

**Comment by livecodepanos** [comment]
Thanks @livecodeali. I have updated the PR.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 2b97c86

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 2b97c8611141958d6ab8fcafe7c799b2ba5ca394

**Comment by livecode-vulcan** [comment]
😎 test success 2b97c8611141958d6ab8fcafe7c799b2ba5ca394

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/995)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1001)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/993)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/994)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1001)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1015)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/992)

**Pull request merged**
