### PR TITLE
Merge release 6.7.7

### PR DESCRIPTION
**Pull request by livecodesebastien**
Merge of the regressions fixed for LiveCode 6.7.7 RC 3 into develop-6.7

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 99594a9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 99594a990d13426d7582ffab02bdb053d380676b

**Comment by peter-b** [comment]
@livecode-vulcan retry 99594a9

**Comment by peter-b** [comment]
@livecode-vulcan review ok ea23fdd

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ea23fddf1b6aaedc702956c1afb8de88942e40f1

**Comment by livecode-vulcan** [comment]
😞 test failure ea23fddf1b6aaedc702956c1afb8de88942e40f1
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/125)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/123)
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/123)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/123)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/126)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/123)

**Comment by peter-b** [comment]
@livecode-vulcan retry ea23fdd

**Comment by livecode-vulcan** [comment]
😞 test failure ea23fddf1b6aaedc702956c1afb8de88942e40f1
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/131)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/129)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/129)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/129)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/132)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/129)

**Comment by peter-b** [comment]
@livecodesebastien It looks like this is still failing due to the bug in zlib.  I think you need to backport the patch from the develop branch in the livecode-thirdparty repository.

**Comment by livecodesebastien** [comment]
Pull request updated.

**Comment by peter-b** [comment]
@livecode-vulcan review ok d3681f1

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d3681f1b456630f6983af19b05d702443aa3dde1

**Comment by livecode-vulcan** [comment]
😎 test success d3681f1b456630f6983af19b05d702443aa3dde1
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/158)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/156)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/156)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/156)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/159)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/156)

**Pull request merged**
