### PR TITLE
[Bug 16027] Set permanent visibility of Android audio/video controller

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
This is certainly a nice simple fix... However, what about people who want the controller's default behavior of hiding?

What is iOS's default behavior?

**Comment by livecodepanos** [comment]
You can hide the controller using `mobileControlSet "showController", false`. Regarding iOS, the default behaviour is to show the controller.

**Comment by runrevmark** [comment]
Ah! Okay so we have parity in this between iOS and Android :)

@livecode-vulcan review ok d917d24

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d917d2414c23bfaed6b0ba9bc1f6a38e7f89626d

**Comment by livecode-vulcan** [comment]
😎 test success d917d2414c23bfaed6b0ba9bc1f6a38e7f89626d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/716)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/729)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/717)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/719)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/729)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/740)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/731)

**Pull request merged**
