### PR TITLE
[Bug 14349] Can't use mouse events on QTKit player

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a5a6bdc

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok a5a6bdcc77779b1b420f9779fa3e0d7457835ecc

**Comment by livecodesebastien** [comment]
@livecode-vulcan review not ok a5a6bdc

**Comment by livecodesebastien** [comment]
This branch breaks the compilation for installer and standalone engine, as the QTKit framework has not been added in the linking process it is has for the IDE engine.

**Comment by runrevmark** [comment]
Oops - my bad - I should have noticed that... We can't link to QTKit directly in any engine version as this would prevent the App from being submittable to the appstore.

We'll need to revert this fix.

**Pull request merged**
