### PR TITLE
[[ Tests ]] Fold compile on travis log

### PR DESCRIPTION
**Pull request by montegoulding**
just testing to see if this works

### CODE REVIEW

**Comment by montegoulding** [comment]
This seems to work nicely @livecodeali @runrevmark seems like it would be handy to save scrolling to find the thing at the end that failed. What do you think?

**Comment by montegoulding** [comment]
Ideally it would fold the c++ tests too

**Comment by livecodeali** [comment]
Great idea, I'm on board.

**Comment by runrevmark** [comment]
Neat - should make grokking the error logs much easier!

**Comment by montegoulding** [comment]
Cool... will poke it again when I have some more time... It would probably be nice if there were a pretty header for each fold and the compile was broken up into target folds if possible... have no idea if you can nest them but that would be nice.

**Comment by montegoulding** [comment]
Closing will open a PR on develop for both mac and linux

**Pull request closed without merging**
