### PR TITLE
[[ Bug 14813 ]] Keep script library names as display names until deploy time

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
There is one issue here: the externals are no longer listed in the Script Libraries.
Also, the following entries have been added after the IDE update:
- Backscript
- Common
- Database
- Debugger
- Deploy
- Frontscript
- Ide
- Metadata
- Profiles
- Shortcuts
  (for Database, there is a second item Database in the list)

**Comment by livecodeali** [comment]
Ah ok, yes - I'm not sure it's too much of an issue that there are extra libraries, it just means that they can be included if people want them (although dependencies need to be sorted I suppose) - unless you can think of an issue?

I'll try and work out what's going on with externals, and get rid of the duplicate "Database"

**Comment by runrevmark** [comment]
Is there some way we can separate 'Libraries which are for User Apps' from 'Libraries which the user should not see'?

**Comment by runrevmark** [comment]
Offline discussion - it should be a static list in 6.7 / 7.0 - we can generalize for 8.0 where Users will have modules to choose and such.

**Comment by livecodesebastien** [comment]
Reviewed-By: Sébastien Nouat sebastien.nouat@livecode.com

**Pull request merged**
