### PR TITLE
[[ Documentation ]] Fix tag - mouseUp.lcdoc

### PR DESCRIPTION
**Pull request by asayd**
- Tag is 'message', not 'message'.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok a8c7f10

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a8c7f1048f00fe1f05df11f224d9492cba38aebe

**Comment by livecode-vulcan** [comment]
😎 test success a8c7f1048f00fe1f05df11f224d9492cba38aebe
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/272)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/276)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/272)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/272)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/276)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/272)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/272)

**Comment by asayd** [comment]
@livecodeali @peter-b @montegoulding On further thought, is it appropriate to add a "messages" tag to this (and other) messages, given that there is already a "message" type filter? Other entries that are tagged with "messages" are tokens that pertain to message passing and the message path, things like pass, dispatch and pendingMessages.

**Comment by livecodeali** [comment]
@asayd Yes I think you're right - we should probably remove it.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok d1bfbf9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok d1bfbf964236ec7f46b7b3a8a5857a68a09237be

**Comment by livecode-vulcan** [comment]
😎 test success d1bfbf964236ec7f46b7b3a8a5857a68a09237be
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/278)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/282)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/278)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/278)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/282)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/278)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/278)

**Pull request merged**
