### PR TITLE
Some optimisations for standalone inclusion searches  

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
I guess we can remove `revSBUpdateSettingsForWidgets` after this

**Comment by montegoulding** [comment]
Yes, there were some other functions that I thought might be useful but aren't currently being used but that one could be removed

**Comment by livecodeali** [comment]
I wonder if we should remove the default behaviour of searching for widgets present on the stack (i.e. only do that at standalone build time if 'search for inclusions' is true) but use `revSBListWidgetsInUse` to pre-check the appropriate boxes in the Inclusions pane

**Comment by montegoulding** [comment]
That seems sensible

**Comment by montegoulding** [comment]
@livecodeali I think the pre-check needs some thought... in a way it would be nice to have a search for inclusions and remember them option... perhaps that would be a better thing to do than having two distinct choices? The user can occasionally click the search for inclusions button but otherwise manage inclusions manually

**Comment by montegoulding** [comment]
@livecodeali I suggest we look at changing the behavior in a future

**Comment by livecodeali** [comment]
@montegoulding Yes, that's a good idea. Björnke suggested a similar thing [here](https://livecode.com/cross-platform-app-deployment-with-livecode-is-now-even-easier/#comment-30737)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 0171cc5

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 0171cc58b84f1e2bf749a1ebc66d6c19b1037b38

**Comment by livecode-vulcan** [comment]
😎 test success 0171cc58b84f1e2bf749a1ebc66d6c19b1037b38
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/115)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/115)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/115)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/115)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/115)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/115)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/115)

**Pull request merged**
