### PR TITLE
[Bug 16742] Default listDepth should be 1

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 0139e3e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 0139e3e37d1a86602be657e33555bdea99d8b9f8

**Comment by livecode-vulcan** [comment]
😞 test failure 0139e3e37d1a86602be657e33555bdea99d8b9f8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1598)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1617)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1594)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1605)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1618)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1619)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1621)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 0139e3e

**Comment by livecode-vulcan** [comment]
😎 test success 0139e3e37d1a86602be657e33555bdea99d8b9f8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1614)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1633)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1610)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1621)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1634)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1635)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1637)

**Pull request merged**
