### PR TITLE
[[ Bug 18946 ]] Fix unreliable doc vs frame test in url request callbacks

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodeian As this is a bug fix, would it be better targetted against develop-8.1 for the next maintenance release?

**Comment by peter-b** [comment]
@livecodeian Please rebase your branch onto `develop-8.1`

@livecode-vulcan review not ok 341c98d

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 341c98d4b5dad65e495c32596f6e407e1f6f3ab3

**Comment by livecodepanos** [comment]
Replaced by https://github.com/livecode/livecode/pull/5136

**Pull request closed without merging**
