### PR TITLE
Further documentation tests and fixes for existing tests

### PR DESCRIPTION
**Pull request by montegoulding**
~~This PR is not intended to be merged. It's just a placeholder to run more comprehensive documentation tests. I will occasionally rebase this patch onto develop to see how close we are getting to passing the tests. When we pass these I'll add more!~~

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecodeali @asayd I just rebased this onto the current develop branch so we should see how many tests still fail. I really need to look at adding the not ok output to stderr on travis so we can see which ones in detail.

**Comment by montegoulding** [comment]
@asayd I have merged in a patch here so that the `not ok` lines from the tests are output. If you click on the `Details` link for the travis then you will see a long log with the docs failures towards the bottom. Hope that helps!

**Comment by asayd** [comment]
@montegoulding Starting at line 8002, is that the section you mean?
not ok - param graphic in param section markerFilled property

**Comment by montegoulding** [comment]
@asayd yes that's it. I'll occasionally rebase this PR on the latest develop branch so you can see how the tests are going

**Comment by montegoulding** [comment]
@seaniepie Seeing as you are now a _very_ active docs contributor (which is awesome BTW) you might be interested to see this travis log from this branch. Just click on the details link next to the travis failure and scroll down until you see a big section of `not ok` results which describe test failures on docs. This branch as some extra docs tests enabled that we can't merge in until they are resolved so every now and then I rebase this on the latest docs to see where we are with it. Once merged in it will mean that any changes to docs that break the tests will be picked up before they are merged.

**Comment by seaniepie** [comment]
Lines 8002 to 9026 - Only 1000. I'm on it :) I have quite a bit of down time at the moment. Nice and quiet. Let me know if anything I do causes problems or looks like it might. First thing I'll do is branch off the latest Develop and see what I see.

**Comment by asayd** [comment]
@seaniepie Welcome aboard! I put together a stack a few weeks ago that loads and parses the log file and lets me filter specific token types. If you think that would be useful I'll figure out how to get you a copy.

**Comment by seaniepie** [comment]
Thanks @asayd . I just created a little text handler that sorted by the last two words of each line that starts 'not ok'. LC rocks for those sort of things. The first one listed in the raw which I looked at first says `not ok - param graphic in param section markerFilled property`. Checking in the markerFilled doc I see refs to graphic (object) and (keyword) but a couple of the entries in the description are labeled simply `<graphic>`. Would replacing with something like `<graphic(object)>` make Travis happy?

**Comment by seaniepie** [comment]
Likewise, for the margins property we have a fail for `object`. In the refs there is only object(glossary) but in the defs there are both `<object(glossary)>` and `<object|objects>` along with one use of `<object>` by itself. Do they all need the (glossary) qualifier for Travis benefit?

**Comment by seaniepie** [comment]
Actually, the one place they all meet is at the top of the margins doc.
`Syntax: set the margins of <object> to {<pixels> | <left>, <top>, <right>, <bottom>}`
Left, top, right and bottom are not defined in the refs so that explains those. However, object and pixels both are. Object does not have (glossary) added. But **`pixels`** only has one definition and is linked correctly in the refs so I wonder more what is causing a fail for that one above all others. :/

**Comment by seaniepie** [comment]
I think I've got it. `Param` = Syntax | Parameters
In the case of Syntax, nothing should be in angle brackets. Easy fix. Large majority of `NotOk`'s.

In the case of Parameters, Travis sees the colon at the end of a first word and assumes that means its the start of a new heading. But it's used to format the columns of the parameter table. So to fix this either Travis needs to accept this or (I think the better idea is) the table formatting needs and alternative delimiter than the colon.

Weird thing tho. e.g., in `revXMLRPC_GetSocket function` we have fails on `documentID in syntax` and `XML-RPC document in param`. The thing is though, `documentID:` is referred to in the parameters section and `<XML-RPC document>` in the syntax section!!!

### So Travis seems to have them swapped around.

Is that maybe what is causing the fails overall?

Exactly the same in Commands. **Swap them** and I bet that sorts it out (or causes a newer but equally solvable issue).

**Comment by montegoulding** [comment]
@seaniepie Just to clarify what the tests are doing we have two tests. One tests to ensure that all parameters `<thing>` in syntax are listed as parameters. The other tests that all things listed as parameters are in the syntax. Actually the first test there allows things to be documented in the glossary which I think is planned as an enhancement at some point...

**Comment by montegoulding** [comment]
Regarding the XMLRPC function these are the droids you are looking for:

```
Syntax: revXMLRPC_GetSocket(<documentID>)
```

**Comment by seaniepie** [comment]
But if Trav _thinks_ he is looking at syntax but is actually looking in  the parameters section and then _thinks_ he is looking in the parameters section and is actually looking in the syntax section then would that fail?

**Comment by seaniepie** [comment]
these are the two fails for revXMLRPC_GetSocket:
not ok - param documentID in **syntax section** revXMLRPC_GetSocket function
not ok - param XML-RPC document in **param section** revXMLRPC_GetSocket function

In the lcdoc:
`Syntax: revXMLRPC_GetSocket(<XML-RPC document>)`
...
`Parameters:`
`documentID:`
`The number returned by ...`
...
`Returns:`
...

But the reason Returns doesn't throw a fail is perhaps because in the refs we get:
`return (glossary)`

It just seems to me that it's looking at the opposite areas to where it thinks. Perhaps. :/

**Comment by montegoulding** [comment]
Returns is not a parameter it's a description of what the function returns. Se the documentation format reference which you can find in LC or in GitHub. @asayd also has a great stack explaining everything. The two errors can be fixed with the syntax patch I posted before.

**Comment by montegoulding** [comment]
Ah... I just realised why you are perhaps getting confused. The string after `not ok -` should be true if things are right. So when it says `param XML-RPC document in param section revXMLRPC_GetSocket function` it means it couldn't find `XML-RPC document` in the `param section`

**Comment by seaniepie** [comment]
Let me give you another example:
not ok - param chunk **in param section** backgroundColor property
not ok - param field **in param section** backgroundColor property
not ok - param object **in param section** backgroundColor property
not ok - param line **in param section** backgroundColor property

Look in the backgroundColor property lcdoc and see what you find. How would you fix?
Do the same for:
not ok - param amount **in syntax section** binaryEncode function
not ok - param orderi **in syntax section** binaryEncode function -- THIS ONE IMPORTANT
not ok - param letters **in syntax section** binaryEncode function

**Comment by seaniepie** [comment]
3am - Bed time - I'll leave that with you 😃

**Comment by montegoulding** [comment]
For `backgroundColor` none of those parameters are listed in the params section but they are in the syntax.

`binaryEncode` is a bit more complicated because a couple of those (letters & orderi) are actually false positives because of a bug in our docs parser that things any line beginning with a word followed by a colon is the start of a new parameter. This is one potential solution we are considering http://quality.livecode.com/show_bug.cgi?id=18000

`amount` however is not actually an enum and should be part of the `formatsList` docs. This does appear to be one of our more messed up docs!

**Comment by seaniepie** [comment]
I'm surprised you haven't seen it yet :D
The messages I posted are not from me but from Travis. He thinks that those params are in the Parameters section and not the syntax section. I put the bold there so you might get what I mean. He's looking for parameters in the syntax section and vice versa. He's applying the wrong rules to each section. He's confused the two. After checking several docs I'm super sure of it however rediculous it sounds.

**Comment by montegoulding** [comment]
@seaniepie have a big sleep and re-read ;-) :

> Ah... I just realised why you are perhaps getting confused. The string after not ok - should be true if things are right. So when it says param XML-RPC document in param section revXMLRPC_GetSocket function it means it couldn't find XML-RPC document in the param section

**Comment by seaniepie** [comment]
But why is it looking in the parameter section? What has triggered it to look there? What is it expecting to find? I'm not seeing what would need to be fixed in these 1000+ references to put it 'right'.

**Comment by montegoulding** [comment]
It is looking in the parameter section for things listed in the syntax as parameters and visa versa. If they aren't there then it is an error against the section they are missing from. Seriously mate, a good sleep, a few double shots in the morning and you will see what I mean.

**Comment by seaniepie** [comment]
So what you mean is that syntax and parameters have to match. But not all instances have parameter sections so these I guess will have to be written. Hmm, ok. On that I _will_ sleep

**Comment by asayd** [comment]
@seaniepie @montegoulding In August we gave a workshop for folks who wanted to start contributing to Livecode documentation. Here's a link to the workshop materials. They sort of 
distill (and link to) the guidance given earlier by @livecodeali on contributing to documentation. 
https://www.dropbox.com/sh/21965qeydad83t5/AACXUqS86XFU7IVUmJpOs2dHa?dl=0
There's a fair amount of detail, but you'll want to become familiar with it so that we can provide a high-quality, consistent experience in the docs. 
Thanks for your contributions!

**Comment by asayd** [comment]
@seaniepie RE &lt;object&gt; links in docs. A link embedded in one of the elements of the .lcdoc must have a corresponding entry in the References element. In cases where there is more than one reference of the same name; e.g. string (glossary) and string (keyword), when you link to it you must disambiguate by including the entry type: E.g. "The && operator concatenates a &lt;string(glossary)&gt; to another &lt;string(glossary)&gt;." In the case of &lt;object&gt; you have to _always_ disambiguate because there is an html tag by the same name.
Finally, links must match the reference entry exactly (including case), so you have to give the exact entry followed by the term as it appears in context:
"Use the && operator to concatenate two &lt;string(glossary)|strings&gt;."
Include the disambiguation if needed. 
Tell me if I'm being too basic, because I don't know what experience level you have with .lcdocs.
- Devin

**Comment by seaniepie** [comment]
Thanks Devin @asayd 
Can you give me more info about how to use the && to concatenate as I don't fully understand what you mean. All the rest makes a lot of sense and I appreciate your assistance a great deal.

**Comment by seaniepie** [comment]
The preview stack is very useful.

**Comment by asayd** [comment]
@seaniepie I was just using that sentence as a hypothetical sample sentence in a Description element. (That came to mind because I had just made some changes to the .lcdoc for the LiveCode && concatenation operator.)
I was just showing how you sometimes have to disambiguate links in the text of a .lcdoc. Hope that answers your question.

Also, the preview stack is courtesy of @livecodeali . It's a great help for checking revisions to .lcdocs before submitting  pull request.

**Comment by seaniepie** [comment]
You can [download](https://www.dropbox.com/s/lt8hj8g4pj7b1ku/Travis_Doc_Fails.rtf?dl=0) my modified and **formatted** list of docs that don't meet Travis standards.
I've highlighted in green those which are done so far, the keywords for now as that is what I was mainly working on before. I'll sort out all the operators next.

**Comment by montegoulding** [comment]
@seaniepie @asayd I have just rebased this branch onto the`develop` head so it will include all your recent merged changes

**Comment by montegoulding** [comment]
@asayd @seaniepie @livecodeali I have tweaked the test to not demand a parameter doc for properties because it is common to describe the property in the `Value` element yet use a descriptive name and refer to it. This removed a huge number of test failures so I fixed the remaining issues so that we can get this merged.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok f5a4e10

@montegoulding Nice!

**Comment by peter-b** [comment]
@livecode-vulcan review by @livecodeali ok f5a4e10

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f5a4e1075f371b94f54fe8f54dfe5f7948eb8a6a

**Comment by livecode-vulcan** [comment]
😎 test success f5a4e1075f371b94f54fe8f54dfe5f7948eb8a6a

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/773)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/778)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/771)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/772)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/778)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/770)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/770)

**Pull request merged**
