### PR TITLE
[[ Warnings ]] Fix unsigned int warnings for BIO api

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok e55b27b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e55b27b4732d01fecfad5ed73e5efcc042f51d68

**Comment by montegoulding** [comment]
@livecode-vulcan review by @peter-b ok 7681c5f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 7681c5fe2c7e38b3147f54b12337d1d2186ebd8b

**Comment by livecode-vulcan** [comment]
😎 test success 7681c5fe2c7e38b3147f54b12337d1d2186ebd8b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/185)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/189)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/185)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/185)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/189)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/185)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/185)

**Pull request merged**
