### PR TITLE
[[ AndroidService ]] Add a background service to Android and example

### PR DESCRIPTION
**Pull request by runrevmark**
This patch adds the infrastructure to allow LCB modules to start
and stop a background service on Android. This allows operations to
be performed whilst the engine is in the background.

A long with the basic infrastructure, a simple example which uses
a MediaPlayer to play audio in the background is also included.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 82ec71a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 82ec71a32defdc33be6d6b3747ae0ef8aba98fb4

**Comment by livecode-vulcan** [comment]
😎 test success 82ec71a32defdc33be6d6b3747ae0ef8aba98fb4

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/374)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/380)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/360)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/303)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/303)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/369)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/374)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/372)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/378)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/372)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/378)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/397)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/368)

**Comment by runrevmark** [comment]
Of course I realized last night that the only reason to have 'Service' subclasses in LiveCode is to allow publically named services. Services on Android run on the main (UI) thread - they aren't really logically distinct... If a process has one or more services running then it just will try its best not to discard the app in tight situations (but it still will if absolutely necessary). There is no difference in coding in a service, to coding in the main app really - the only difference is that the engine will automatically pause/resume things on suspension. The example extension works because it uses its own media players which it does not suspend/resume (hence they work whilst the engine is 'suspended' from the user's point of view, at least).

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 36f5761

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 36f57618fb433c6633d692ba6bb04814926b18d2

**Pull request merged**
