### PR TITLE
fix for hostnameToAddress on linux

### PR DESCRIPTION
**Pull request by mwieder**
On linux systems, gethostbyname() will first check the /etc/hosts file to see if the host is declared. If so, it will return the local declaration. By default on linux distros this is 127.0.0.1 for localhost. In order to get the actual network address for localhost we have to go the long way around. Here I'm creating a socket connection to google's open dns server and extracting the address from the local end of the connection. Obviously this will not work if there is no network connection, but hostnameToAddress is probably not very useful in that case anyway.

### CODE REVIEW

**Comment by bwmilby** [comment]
I just checked Mac and Windows - both return 127.0.0.1 when asked for for `hostnameToAddress("localhost")` and none of the systems return `localhost` for `the hostname` on my test.  I didn't try to pull this down and compile, but the code looks like it specifically looks for `localhost` instead of the local computer's name.  Does this change `put hostnameToAddress(the hostname)` so that it doesn't return 127.0.0.1?

EDIT:
Just compiled and don't think this is working as intended.
`put hostnameToAddress(the hostname)` --> 127.0.1.1
`put hostnameToAddress("localhost")` --> 10.0.1.77

**Comment by montegoulding** [comment]
Hmm... so is the issue `the hostname` returns the wrong thing or `hostnameToAddress` does the wrong thing with the hostname?

**Comment by montegoulding** [comment]
BTW getting local IP via `put hostnameToAddress(the hostname)` should probably deprecated for using `the networkInterfaces` these days I would have thought...

**Comment by montegoulding** [comment]
Hmm... I'm leaning towards this actually not being a bug but the design on linux and suggesting people use `the networkInterfaces` to determine an appropriate IP for the system. I will ask internally for other team members to weigh in.

**Comment by bwmilby** [comment]
To me it seems that on Linux it is properly resolving the hostname to the IP in the /etc/hosts file instead of providing the external IP.  The “bug” is that it is not consistent with the other desktop platforms.  One possible solution is to figure out the external IP when ‘the hostname’ resolves to a loopback address `(127.*.*.*)`

**Comment by mwieder** [comment]
Brian- that's essentially what this code does. Or rather determines that the user is trying to resolve "localhost" and then takes it from there. But Monte- I didn't realize that the networkinterfaces was actually implemented yet. Lemme take a look. That might solve this neatly.

**Comment by montegoulding** [comment]
@mwieder `the networkInterfaces` has been around since LC 4.6.3 according to the docs

In my opinion `hostnameToAddress("localhost")` should always resolve to `127.0.0.1`. As for other host names listed in `/etc/hosts` I'm not sure. It may be reasonable to do what we are doing here if we are not resolving `localhost` but the resolved address is `127.0.0.1`. On the other hand you can list hosts names in there that are only accessible locally so... perhaps this function is already doing what it's meant to do...

**Comment by mwieder** [comment]
"localhost" does resolve to 127.0.0.1, but only on the lo interface. It's defined that way in /etc/hosts on linux distros and is a pretty useless result for resolving the address. For resolving other addresses, I think an entry in /etc/hosts should override any further action to resolve the address.

The networkinterfaces is interesting in its own right, but still:
a: is ipv4 only
b: doesn't differentiate between the different network interfaces, i.e., I see it returning both "lo" and "eth0" with no way to tell which is which without knowing beforehand. So another workaround for gethostbyname at the LCS level for ipv4 could be

function gethostbyname pName
  local tAddresses
  put the networkinterfaces into tAddresses
  filter tAddresses without "127.0.0.1"
  return tAddresses
end gethostbyname

Maybe it would be better do deprecate gethostbyname() and beef up networkinterfaces() to permit parameters  as in networkinterfaces("eth0")?

Also... I'm using a kludge to see if the user wants to resolve localhost because I couldn't find an MCCompareStrings function. Is there a better way to do this?

**Comment by montegoulding** [comment]
@mwieder IPv6 is a general issue not something specific to this. Just filtering out localhost is probably sufficient...

BTW I have a bug open about windows returning 0.0.0.0 for inactive interfaces rather than not adding them to the list so you may want to filter out that also ;-)

**Comment by bwmilby** [comment]
@mwieder Your actual bug report starts with indicating that this isn't consistent between platforms:
`put hostnametoaddress(the hostname) && the hostname`
Result on a Mac: `10.0.1.112 Milby-Retina-iMac.local`
Result on Linux:  `127.0.1.1 brian-VirtualBox`

When examining the hosts files, I can see that when I installed Linux it added the loopback address for the host name (using 1.1 instead of 0.1).  That's why I stated that the solution would be to look for attempts to resolve the local computer (via a match to `the hostname`) that return a result that begins with 127 (instead of the full default loopback of 127.0.0.1).

Is there an entry in your hosts file that matches the result of `the hostname`?  Is the IP being returned different than the hosts file?

The bug report is not that `localhost` resolves to `127.0.0.1` because that is correct.  All 3 desktop platforms resolve that way.  I agree with @montegoulding that this is the correct behavior.

**Comment by mwieder** [comment]
Brian- heh - I had to go back and look at the original bug report again. Boy - that's been a while. OK - a couple of things are being conflated here, and that's not good. So let me back off a bit and try this again. Yes, resolving localhost to 127.0.0.1 is technically correct, but not very useful.

So platform parity would indicate that hostnameToAddress() should return the local area address when requested for the hostname. That would require a bit more parsing on the frontend to resolve the hostname, but the end result should be the same.

But now that I look at this again, I'm seeing that hostnameToAddress on osx isn't returning the correct information either. When I request hostnameToAddress(the hostname) on osx I get duplicate copies of the lan addresses for en0 and en1.

**Comment by runrevmark** [comment]
All platforms have their own configuration of hostname and such. On Windows, there is clearly default mappings from the name of the 'host name' to presumably the 'primary network interface'; Mac has long automatically setup local hostname type addresses (i.e. .local ones), and that is what the 'hostname' returns; Linux you can set it up however you want - the only default mapping as far as I can see is the local loopback.

I don't think it is wise to talk about 'platform parity' in this case - as the engine cannot 'make up' for configuration which hasn't been done on any given system - as it can't tell whether that is an omission, or how it is meant to be.

The reality is that 'the address of this machine' doesn't really make much sense beyond using the system configuration which the machine has (which gethostbyname does, by definition) - especially as most machines have multiple network interfaces.

So - the question is - what do people actually want when they are doing 'hostnameToAddress(the hostname)'? It seems to me that operation is not well-defined, and the problem is that people are assuming there exists 'a default external network interface for the machine' - which I'm not sure is ever necessarily true...

**Comment by mwieder** [comment]
Mark- these are valid points all, and admittedly gethostbyname is pedantically returning what it should. But I think the important thing here is your last point, and that's what I meant by 'platform parity'. On Windows and osx asking for hostnameToAddress(the hostname) returns the local area network address in use, and I do think that's the desired result of asking that question. Returning a loopback address from the hosts file is a rather useless result - I already know what the loopback address is without having to call the functions.

You're correct about the operation not being clearly defined. I'm (after the above discussion) tending toward deprecating hostnameToAddress in favor of an improved networkInterfaces facility.

**Comment by runrevmark** [comment]
All we are talking about here is recommending strongly that people don't do 'hostnameToAddress(the hostname)' to try and get the external IP address as what you will get will largely depend on your system setup (regardless of platform, actually - you can fettle with the socket related config files on windows - they are buried in the System32 folder somewhere; similarly on Mac).

The main issue here is that the question 'give me the local IP address of this computer' doesn't make sense - as it might have more than one, and data might come in on any one of the computers network adapters. So a better question to ask is 'why do people need what hostnameToAddress(the hostname)'? i.e. what are they doing with that / expecting to do with that?

The hostnameToAddress function is the cornerstone of doing DNS resolution - so it isn't going anywhere!

**Comment by mwieder** [comment]
hostnameToAddress works properly on linux (and the other platforms) as long as you don't try to resolve the local address, so dns resolution isn't really going to be affected. But point taken. I don't think there is currently an alternative to 'get my local area network address' other than getting the networkInterfaces and filtering that. And given that Windows and osx both return the LAN address when hostnameToAddress is called with the hostname, I think it's reasonable for linux to do the same.

**Comment by montegoulding** [comment]
I'm a little bit confused now. Are we all in agreement that we are currently doing the right thing, this PR should be closed and the original report should be changed to a docs enhancement to steer people to `the networkInterfaces` for getting a list of IPs for the machine?

**Comment by mwieder** [comment]
You and me both. I'm inclined to just close this and forget it.

**Pull request closed without merging**
