### PR TITLE
[[ Bug 18959 ]] Fix memory corruption when getting regular polygon points

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodeian Do you think the stack from the bug report can be used to create a test for this?

**Comment by livecodeian** [comment]
@livecodeali possibly, though given the nature of this bug I'm not sure it can be tested for reliably. I wonder if there's scope for running the engine through valgrind for some tests.

**Comment by livecodeali** [comment]
@livecodeian Yeah that would be so cool... I think we're probably a bit away from that point at the moment unfortunately :-(

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8dd2c5d
Hooray for bugfix with net code deletion!

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8dd2c5d22c3ffbdfb37d576991b673537683874a

**Comment by livecode-vulcan** [comment]
😎 test success 8dd2c5d22c3ffbdfb37d576991b673537683874a

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/832)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/838)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/830)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/831)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/838)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/829)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/829)

**Pull request merged**
