### PR TITLE
App-based DMGs for OSX, 7.x edition

### PR DESCRIPTION
**Pull request by livecodefraser**
https://github.com/livecode/livecode/pull/3616 but pre-merged into 7.0

### CODE REVIEW

**Comment by livecodefraser** [comment]
IDE changes for this PR: https://github.com/livecode/livecode-ide/pull/952

**Comment by peter-b** [comment]
@livecodefraser What needs to be done to this PR before it's mergeable?

**Comment by livecodefraser** [comment]
Nothing, I think. It is just the 6.7 version merged into develop-7.0 with the merge conflicts sorted out (because installer generation in 7.1 builds 3 editions instead of two).

**Comment by peter-b** [comment]
Okay then.

@livecode-vulcan review ok 808e1b0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 808e1b05dca090833d8c50c2cffa525204e296b1

**Comment by livecode-vulcan** [comment]
😎 test success 808e1b05dca090833d8c50c2cffa525204e296b1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1958)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1971)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1952)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1964)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1974)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1979)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1984)

**Pull request merged**
