### PR TITLE
[[Community Docs]] Updated the setMargin() definition

### PR DESCRIPTION
**Pull request by davekilroy**
- Deleted the trailing "as undefined" part of the setMargin() definition - "as undefined" no long seems to be in use and with it included the .lcb file does not work (see http://forums.livecode.com/viewtopic.php?f=93&t=23969)

### CODE REVIEW

**Comment by livecodeali** [comment]
Thanks Dave!
@livecode-vulcan review ok 48d3487

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 48d348761e7d79964fd73aa227f79981af8a66c1

**Comment by livecode-vulcan** [comment]
😎 test success 48d348761e7d79964fd73aa227f79981af8a66c1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2489)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2499)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2482)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2500)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2506)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2510)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2522)

**Comment by davekilroy** [comment]
@livecodeali a pleasure - BTW can you give any hints on where in github I can find the rest of the 'Extending LiveCode' section (there are quite a few niggly little typos in there...)

**Comment by peter-b** [comment]
@DaveKilroy Thanks for this patch!

The "Extending LiveCode" guide [lives in the IDE repository](https://github.com/livecode/livecode-ide/blob/develop/Documentation/guides/Extending%20LiveCode.md).

**Pull request merged**
