### PR TITLE
[[ Installer ]] Make sure all included modules are in the installer manifest

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok  04be46d

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok  90bb9ea

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 90bb9eae77f882db0adfc14693ec5df90f34ebdc

**Comment by livecode-vulcan** [comment]
😎 test success 90bb9eae77f882db0adfc14693ec5df90f34ebdc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/559)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/566)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/560)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/559)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/568)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/566)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/570)

**Pull request merged**
