### PR TITLE
[[Cleanup]] Fixes for graphics rectangle conversions

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 9b3f421

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 9b3f421344ae43351f1499b4d056f3f071aa7f54

**Comment by peter-b** [comment]
@livecode-vulcan review not ok 9b3f421

Failed tests locally.

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 9b3f421344ae43351f1499b4d056f3f071aa7f54

**Comment by peter-b** [comment]
Apparently this only got rid of 6000 warnings form the Windows build... :interrobang:

**Comment by runrevmark** [comment]
@peter-b: 'only'? isn't that 20%?

**Comment by peter-b** [comment]
@runrevmark Yes, and Fraser's build system patches should get rid of a lot more spurious ones.

@livecodefraser This version of the patch doesn't horribly break the engine, so could I please get a proper review when you have time?

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 242025d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 242025d29266d2f26227d06d93e505ec0c6bfd6a

**Comment by livecode-vulcan** [comment]
😎 test success 242025d29266d2f26227d06d93e505ec0c6bfd6a
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/592)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/652)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/541)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/605)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/537)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/530)

**Pull request merged**
