### PR TITLE
widgets: Prune widgets to those that can be stabilised for 8.0.0 release

### PR DESCRIPTION
**Pull request by peter-b**
It's important that we're totally happy with the widgets we ship with LiveCode 8.0.0, and are prepared to fully support them indefinitely.  This pull request disables or hides a number of extensions in order to facilitate this.

The following widgets do not compile at all and have been removed entirely:
- button-popup
- segmented-pup

The following widgets are intended only for internal use for the IDE and have been hidden from the tools palette:
- colorswatch
- gradientrampeditor

The following widgets cannot be stabilised in time for LiveCode 8.0.0 release (for various reasons, particularly theming and integration with other controls) and have been disabled from build:
- checkbox
- progressbar
- radiobutton
- selector

### CODE REVIEW

**Comment by livecodeali** [comment]
@peter-b You should probably remove selector from the installer manifest too (although I don't think it's a fatal error if it's missing is it?)

**Comment by peter-b** [comment]
@livecodeali Pull request updated.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 82253fe

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 82253fefc549aba8788e86933654bc5f9832a407

**Comment by livecode-vulcan** [comment]
😎 test success 82253fefc549aba8788e86933654bc5f9832a407
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1520)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1539)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1516)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1527)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1539)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1540)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1542)

**Comment by peter-b** [comment]
@livecodeali Could you please review the merge?

I've added release notes in livecode/livecode-ide#886.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 72182b0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 72182b09fcafa4d15a24ee09f2494910fc0aa861

**Comment by livecode-vulcan** [comment]
😎 test success 72182b09fcafa4d15a24ee09f2494910fc0aa861
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1785)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1798)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1779)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1791)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1800)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1804)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1810)

**Pull request merged**
