### PR TITLE
[[ ByteOffset ]] Fixed bug causing incorrect results

### PR DESCRIPTION
**Pull request by abrisan**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodealex Could you add tests for byteOffset - covering the erroneous cases discussed, and any other which are pertinent? There are ones which check for empty things in lcs/core/strings/byteoffset.livecodescript - but they could do with extending to cover the extra fast path exits you've added, and also to make sure the 'bytesToSkip' parameter works correctly, and returns the appropriate (relative?) offset.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a225404

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 7b63f69

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 7b63f69953cf1f283555d2cb7fc09c18fa15a0c8

**Comment by livecode-vulcan** [comment]
😎 test success 7b63f69953cf1f283555d2cb7fc09c18fa15a0c8

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/320)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/312)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/312)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/312)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/312)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1834)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/62)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/62)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1865)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1855)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1854)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1888)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1829)

**Pull request merged**
