### PR TITLE
Update RevFont for 64-bit OSX

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 13bd6da

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 13bd6dab0aa0dd1bf99b4379a0d84503d5c1dea6

**Comment by livecode-vulcan** [comment]
😎 test success 13bd6dab0aa0dd1bf99b4379a0d84503d5c1dea6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/965)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/973)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/962)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/966)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/975)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/984)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/979)

**Comment by montegoulding** [comment]
Hmm... why hasn't revFont been dropped from the repo now we have start using font file.

**Comment by livecodefraser** [comment]
Compatibility, mostly. We'd be quite happy if everyone stopped using it!

**Comment by montegoulding** [comment]
Hmm... couldn't you just add commands to the library the IDE includes in standalones?

**Pull request merged**
