### PR TITLE
Fixes encountered while working on HTML5 wait support

### PR DESCRIPTION
**Pull request by peter-b**
Several HTML5-related fixes, including:
- Improved handling of the "input library" used with LCS tests
- Correct some tests that were crashing when run in-browser
- Fix unexpected errors in "the machine" and "the processor"
- Fix "repeat _ times" on emscripten

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodefraser Pull request updated!

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay efe5ea9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok efe5ea928a61bb227e290f1abd678f59a8ded6a5

**Comment by livecode-vulcan** [comment]
😎 test success efe5ea928a61bb227e290f1abd678f59a8ded6a5
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1419)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1439)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1415)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1425)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1436)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1435)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1440)

**Pull request merged**
