### PR TITLE
[[ Bug 19488 ]] Separate engine path and code path 

### PR DESCRIPTION
**Pull request by runrevmark**
This patch makes a distinction between the engine path (MCcmd)
and the path to use to load shared libraries from (MCappcodepath).

These are the same on most platforms, but differ on emscripten
and android.

The app codepath is initialized after MCcmd on initialization of
the engine in a platform-specific manner. On desktop it can be
overriden by setting the MCappcodepath global *before* calling
X_init.

### CODE REVIEW

**Comment by peter-b** [comment]
Looking good. Thanks for fixing the Emscripten stuff -- I have no idea why I failed to include an `MCSInitialize()` call!

@livecode-vulcan review ok 2d34913

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2d34913c2cc8db60d27def887962680c42e85d0b

**Comment by peter-b** [comment]
@livecode-vulcan review ok fa1a150

I can't remember why `MCcmd` was marked as `/* FRAGILE */`

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok fa1a1500a1385c9c5e79ede32d83c4b18a2658e1

**Comment by peter-b** [comment]
@livecode-vulcan review ok 29e9e3c

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 29e9e3cb430bfcf30fd62b71383928f885b1badb

**Comment by livecode-vulcan** [comment]
😞 test failure 29e9e3cb430bfcf30fd62b71383928f885b1badb

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/103)
* try-community-armv6-android-api9: [failure](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/103)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/89)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/35)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/35)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/101)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/103)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/105)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/107)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/105)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/107)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/123)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/103)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok d93d3a1

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d93d3a1489edad740329af5c0d0935338b555c80

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 8f9c5fd

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 8f9c5fd2fd917c20f8bf11ee867d185f54910eab

**Comment by livecode-vulcan** [comment]
😞 test failure 8f9c5fd2fd917c20f8bf11ee867d185f54910eab

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/105)
* try-community-armv6-android-api9: [failure](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/105)
* try-community-js-emscripten-sdk1.35: [pending](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/91)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/37)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/37)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/103)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/105)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/107)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/109)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/107)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/109)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/125)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/104)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9eacecb

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9eacecb73fe2dba2552bd1237c35ad037a39dfcc

**Comment by livecode-vulcan** [comment]
😎 test success 9eacecb73fe2dba2552bd1237c35ad037a39dfcc

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/106)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/106)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/92)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/38)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/38)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/104)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/106)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/108)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/110)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/108)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/110)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/126)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/105)

**Pull request merged**
