### PR TITLE
[Bug 18691] Added bugfix note

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 9b0ac65

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9b0ac6538842a3701ae87f643b11a765bb766fb0

**Comment by livecode-vulcan** [comment]
😎 test success 9b0ac6538842a3701ae87f643b11a765bb766fb0
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/551)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/556)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/551)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/555)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/560)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/552)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/552)

**Comment by montegoulding** [comment]
@peter-b so we are doing individual notes for engine, mergExt and tsNet 10.1 builds? Sorry I had advised @techstrategies that we would just have a single note covering the distribution. I'll submit a mergExt one ASAP.

**Comment by peter-b** [comment]
@montegoulding I think @livecodepanos decided it would be a good idea and I couldn't think of a particularly strong argument against it.  We can revert this PR if you think it's better to have 1 release note to cover all three tracking bugs.

**Comment by montegoulding** [comment]
@peter-b it's no huge issue although it seems a little redundant. I'm happy either way I just had given Charles the wrong advice.

**Comment by livecodepanos** [comment]
@montegoulding @peter-b I added the bugfix note so as it appears in the release notes as well, and let people know that tsnet uses the latest iOS SDK

**Comment by montegoulding** [comment]
OK, cool @livecodepanos I'll get the one for mergExt done

**Comment by montegoulding** [comment]
https://github.com/livecode/livecode/pull/4833

**Pull request merged**
