### PR TITLE
[[ SvgViewWidget ]] Add a simple 'SVG View' widget

### PR DESCRIPTION
**Pull request by runrevmark**
This PR adds both an 'SVG' abstraction at the Canvas level, and a simple 'SVG View' widget.

The SVG abstraction is based on https://github.com/memononen/nanosvg which is a very small SVG subset parser. The subset it understands includes shapes, paths, transforms, color fills as well as linear and radial gradients.

The SVG View widget wraps an SVG document specified by an 'svgText' property, and scales and fills the widgets bounds with a specified rectangle of the SVG document (visibleBox).

Note: The widget does not yet load / save its state, and gradient transforms are not currently mapping correctly.

### CODE REVIEW

**Comment by peter-b** [comment]
As mentioned in private discussion, _ideally_ nanosvg.h should live somewhere in livecode-thirdparty. :wink:

**Comment by runrevmark** [comment]
@peter-b: Indeed, I also need to separate it into two PRs - one for the SVG abstraction in canvas and below, and one for the widget itself :)

I just thought I'd push it in case any interested observers wanted to try it out.

**Comment by peter-b** [comment]
@runrevmark: Well, I don't think that would be _entirely_ necessary but hey, it's your feature. :grinning:

**Comment by runrevmark** [comment]
svg widget screenshot

**Pull request closed without merging**
