### PR TITLE
Reflex tweaks due to mis-merge

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok f2fbccbf

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f2fbccbfc2bd2d89360852dca9d32fa1762b2c63

**Comment by livecode-vulcan** [comment]
😎 test success f2fbccbfc2bd2d89360852dca9d32fa1762b2c63
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/229)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/293)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/182)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/240)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/175)
- try-mac: unknown

**Comment by peter-b** [comment]
Yay bugs. It looks like @livecode-vulcan reported the test as successful before the mac build had even started... I think I've fixed it now though.

**Pull request merged**
