### PR TITLE
[[ Bug 15931 ]] Fix Linux crash on exit after using browser widget

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 9ec54f4

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9ec54f44000fc505f331876df0c60d6536f2a845

**Comment by livecode-vulcan** [comment]
😎 test success 9ec54f44000fc505f331876df0c60d6536f2a845
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1864)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1877)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1858)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1870)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1880)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1883)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1889)

**Comment by mwieder** [comment]
OMG - thank you, Ian! Good catch.

**Pull request merged**
