### PR TITLE
[[ Coverity ]] Update organisation name in travis yml file

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 51cfeee

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 51cfeee37d638e87b21ebe4e3b39ba813ccd88a5

**Comment by livecodeali** [comment]
I'm now a bit unsure of whether we need to merge this.

On here, the "Project Name" is still runrev/livecode
https://scan.coverity.com/projects/runrev-livecode?tab=project_settings

**Comment by livecode-vulcan** [comment]
😎 test success 51cfeee37d638e87b21ebe4e3b39ba813ccd88a5
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/343)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/343)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/342)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/341)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/346)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/338)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/349)

**Comment by peter-b** [comment]
@livecodeali I'm afraid this needs to match the GitHub repository name or it will break the Coverity Scan integration.

(@livecodefraser please don't kill me)

@livecode-vulcan review not ok 51cfeee

**Comment by peter-b** [comment]
... And I've just realised that you've changed the repository name. I'm an idiot and clearly haven't been passing attention while on holiday.

Um.

I'll look into this when I get back!

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 51cfeee37d638e87b21ebe4e3b39ba813ccd88a5

**Comment by runrevmark** [comment]
@peter-b: Indeed - should probably have not done it when anyone was away. It seems you cannot change the coverity project name for some reason... Unless I'm missing something. I managed to change the repo url.

**Comment by livecodeali** [comment]
@peter-b Think we also might need to change the travis CI links here https://travis-ci.org/profile/runrev but it seems only you have admin rights :smile:

**Comment by peter-b** [comment]
@livecodeali @runrevmark For Travis, I think @runrevmark should have full admin access since he's an owner of the corresponding GitHub organisation. For Coverity, we'll probably have to get one of their administrators to manually fix things up — I recommend filling a support request.

**Comment by peter-b** [comment]
Okay -- I've looked into Coverity and the admin interface specifically says:

> GitHub projects cannot be renamed.

So that's that, then. :weary: It's probably not the end of the world if the Coverity project isn't named correctly...

**Pull request closed without merging**
