### PR TITLE
[[ Per-Edition Docs ]] Build per-edition dictionary and guides

### PR DESCRIPTION
**Pull request by livecodeali**
Required: https://github.com/livecode/livecode-private/pull/69

### CODE REVIEW

**Comment by peter-b** [comment]
See [bug 16556](http://quality.livecode.com/show_bug.cgi?id=16556).

**Comment by peter-b** [comment]
@livecode-vulcan review ok 913307d

**Comment by peter-b** [comment]
@livecodeali Are there any changes needed to the installer manifest to make sure that the correct docs go into each edition's installers?

**Comment by livecodeali** [comment]
@peter-b I don't think so - as far as I can see each edition's installers just use the current 'output' ide. So I've just made it overwrite the relevant data each time.

**Comment by livecodeali** [comment]
Superseded by https://github.com/livecode/livecode/pull/3631

**Pull request closed without merging**
