### PR TITLE
Fix redefinition of min & max types

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 333b54b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 333b54b528c627244d63da6622f9f65ebb2ea84c

**Comment by montegoulding** [comment]
@livecode-vulcan review by @peter-b ok d08747a

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d08747a74f7679e52c56fe13ab09ba22bdff8861

**Comment by livecode-vulcan** [comment]
😎 test success d08747a74f7679e52c56fe13ab09ba22bdff8861
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/183)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/187)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/183)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/183)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/187)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/183)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/183)

**Pull request merged**
