### PR TITLE
[[ IsReally ]] New operators 'is [not] really'.

### PR DESCRIPTION
**Pull request by runrevmark**
The following operators have been added:

  x is really nothing
  x is not really nothing
  x is really a boolean
  x is not really a boolean
  x is really an integer
  x is not really an integer
  x is really a real
  x is not really a real
  x is really a string
  x is not really a string
  x is really a binary string
  x is not really a binary string
  x is really an array
  x is not really an array

These test the actual type of the value of x to see if it exactly matches the specified type.

Note that this is mainly added to help work out what types are used in values coming from widgets (in particular, widget object arrays) and due to the way the engine currently works there might be some surprising things - they are not intended for general purpose use.

### CODE REVIEW

**Comment by peter-b** [comment]
GitHub needs a "Like" button :+1:

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevmark, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by mwieder** [comment]
Vulcan is getting a bit over-exuberant about things.

But... I agree about the need for a "Like" button. This is a great addition.
About the '[not] really nothing' operator... what counts as nothing? null? empty strings? the string 'empty'?

**Comment by peter-b** [comment]
The special "nothing" value is `really nothing` — nothing else is! It normally translates to `empty` in LiveCode scripts.

**Comment by mwieder** [comment]
Now cut that out! Nothing is 'really nothing' and nothing else is? My head hurts.
So 'x is really nothing' is 'x is "really nothing"'? Or is there a 'really nothing' object that's normally 'empty'? Gack! It's hard to write this stuff in English syntax.

**Comment by peter-b** [comment]
There's a nothing object that represents the void, the lack of value, the uninitialised state. It's the only value for which `x is really nothing` evaluates to true.

You **really don't** need to care about it if you're not working on LiveCode Builder to LiveCode script bridge code.

**Comment by mwieder** [comment]
Thanks. Yeah, I got that from the 'not intended for general purpose use' thing. Just caught my eye as one of the more interesting pull requests I've come across.

**Comment by livecodefraser** [comment]
Does this need further work other than docs and notes?

**Comment by runrevmark** [comment]
@mwieder: The 'is really' operators allow you to see what the current type of a value in a variable is. The 'is a' operators in LCS don't allow you to do this because of automatic type coercions (e.g. a Number could, at any given point, actually be a String in LCS).

**Comment by runrevmark** [comment]
@livecodefraser: I think this is done for now - it just needs release notes and docs (oh, and updating from develop!)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay b1f44bd

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevmark, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok b1f44bd146590236bba5d6d5efd6d01eb383f83b

**Comment by livecode-vulcan** [comment]
😎 test success b1f44bd146590236bba5d6d5efd6d01eb383f83b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/225)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/224)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/225)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/220)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/227)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/223)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/228)

**Pull request merged**
