### PR TITLE
[[ Emscripten ]] Show the LiveCode logo on the output HTML page

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodefraser Are you sure that `engine/rsrc` is the right place for the LiveCode logo SVG?

**Comment by peter-b** [comment]
I suppose we can move it later if it turns out to be a problem.

@livecode-vulcan review ok 14c545b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 14c545b3a2e9641935bc397ae80d3515203daee6

**Comment by livecode-vulcan** [comment]
😎 test success 14c545b3a2e9641935bc397ae80d3515203daee6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/361)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/361)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/360)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/359)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/364)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/356)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/367)

**Pull request merged**
