### PR TITLE
[[ LCB ]] Add IntSize foreign type (mapping to ssize_t).

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 5094e97

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 5094e9766cc95b9516337197742d48910a662869

**Comment by peter-b** [comment]
Ah -- actually, this requires a release note.

@livecode-vulcan review not ok 5094e97

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 5094e9766cc95b9516337197742d48910a662869

**Comment by livecodeali** [comment]
If this is going into dp 3 it needs rebasing and a release note fairly soon.

**Comment by runrevmark** [comment]
@livecodeali: Rebased and released noted - just needs a review :)

**Comment by peter-b** [comment]
Having a look at this at the moment. :-)

**Comment by peter-b** [comment]
A couple of "style" questions.

```
r_hash = MCHashSize(*(size_t *)value);
```

Would this be better written as follows?

```
r_hash = MCHashSize(*reinterpret_cast<size_t *>(value));
```

Also, I notice that you're using the `SIZE_MAX`.  Should there exist `SSIZE_MAX` & `SSIZE_MIN`?

I don't think these comments really _need_ to be addressed before merging this PR, so:

@livecode-vulcan review ok 943f6f1

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 943f6f180ec0b42fb5d77a8e933242a4a415f0c8

**Comment by livecode-vulcan** [comment]
😞 test failure 943f6f180ec0b42fb5d77a8e933242a4a415f0c8
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/707)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/767)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/657)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/721)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/652)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/644)

**Comment by runrevmark** [comment]
Heh - well - it appears that windows doesn't like ssize_t... So @peter-b I'll tweak things as suggested by your style suggestions above whilst fixing that.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 7111de6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 7111de6f4314bd9241ce9592b6cba40167d4b9a8

**Comment by livecode-vulcan** [comment]
😞 test failure 7111de6f4314bd9241ce9592b6cba40167d4b9a8
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/715)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/775)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/665)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/729)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/660)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/652)

**Comment by peter-b** [comment]
I think you need `limits.h` for the definition of `SSIZE_MAX`.

**Comment by runrevmark** [comment]
@peter-b: Thanks - I'll patch it - Mac must have it implicitly included I guess... Or there's an include hiding somewhere!

**Comment by peter-b** [comment]
@runrevmark Fourth time lucky, I hope!

@livecode-vulcan review ok 66891a6

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 66891a61ccccc59c7d82b2a0874363cfba996e70

**Comment by livecode-vulcan** [comment]
😞 test failure 66891a61ccccc59c7d82b2a0874363cfba996e70
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/731)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/791)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/681)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/745)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/676)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/668)

**Comment by peter-b** [comment]
Fingers crossed....

@livecode-vulcan review ok 0c882df

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 0c882df810566b91e6b475863f03ca59d828e3db

**Comment by livecode-vulcan** [comment]
😞 test failure 0c882df810566b91e6b475863f03ca59d828e3db
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/742)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/802)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/692)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/756)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/687)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/679)

**Comment by peter-b** [comment]
@livecode-vulcan review by @runrevmark ok dd976fb

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok dd976fb0d0485355672f7fc14eb0c92ca54cf7b6

**Comment by livecode-vulcan** [comment]
😎 test success dd976fb0d0485355672f7fc14eb0c92ca54cf7b6
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/745)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/805)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/695)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/759)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/690)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/682)

**Pull request merged**
