### PR TITLE
Fix the grouping of LiveCode windows on Linux

### PR DESCRIPTION
**Pull request by livecodefraser**
Linux taskbars that group windows belonging to the same application (for example, the Ubuntu taskbar) did not consider the LiveCode IDE windows to belong to the same application, causing clutter and general annoyance.

In line with other Linux applications, the WM_CLASS hint on windows is now set to have the application and class name fields equal. For the IDE, this is a string along the lines of "livecodecommunity_8_0_0_dp16" while for standalones, it is the name of the home stack (meaning that unrelated standalones shouldn't group together).

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodefraser It would be really nice if you would be kind enough to get rid of the `/* UNCHECKED */` stuff as part of this PR...

**Comment by livecodefraser** [comment]
@peter-b Uncheckeds expunged.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 44ab7c1

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 44ab7c1eb0f323bfaa55019909ead402dd621fd9

**Comment by livecode-vulcan** [comment]
😞 test failure 44ab7c1eb0f323bfaa55019909ead402dd621fd9
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2216)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2224)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2209)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2225)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/2231)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2236)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2247)

**Comment by peter-b** [comment]
@livecode-vulcan retry 44ab7c1

**Comment by livecode-vulcan** [comment]
😎 test success 44ab7c1eb0f323bfaa55019909ead402dd621fd9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2249)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2258)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2242)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2259)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2265)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2270)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2281)

**Pull request merged**
