### PR TITLE
[[ Tests ]] Add ability to load all extensions in test lib

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali This looks fine, but I guess you'll want to revise it if you implement [bug 15835](http://quality.livecode.com/show_bug.cgi?id=15835)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a221c94

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok a221c94392733b75bf057cf1d476f79b62102c1a

**Comment by livecode-vulcan** [comment]
😎 test success a221c94392733b75bf057cf1d476f79b62102c1a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1797)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1810)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1791)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1803)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1812)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1816)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1822)

**Pull request merged**
