### PR TITLE
[[ Feature ]] Toast notification library

### PR DESCRIPTION
**Pull request by runrevmark**
This patch adds commands to use Android toast notifications.

### CODE REVIEW

**Comment by livecodeali** [comment]
My only question here is whether we should change the call to `androidToast` or whether we're likely to implement / use a third-party library for a toast equivalent on iOS.

**Comment by montegoulding** [comment]
I'm not really sure why we use platform or mobile prefixes when users still need to check the platform before calling it. We also only ever seem to do this for mobile platforms which is a bit odd. It's not like we don't have single platform desktop stuff. When reading the code it's redundant to have:
```
if the environment is "mobile" then
   mobileWhathaveyou
end if
```
So my vote... just call it `toast`

**Comment by mwieder** [comment]
My two cents worth is: I'd prefer "mobileToast" to "androidToast" and "toast" to "mobileToast". Then "toast" by itself could be an umbrella for "mobileToast" and "whateverToast" if we ever have a desktop version, and "mobileToast" could be an umbrella for iOS and Android toast implementations. The user could just call the "toast" command, and the underlying code would figure out what platform it's running on. If I'm reading this right, I think I'm mostly agreeing with Monte.

**Comment by runrevmark** [comment]
The question to ask here (before we consume 'toast' as a verb) is what the equivalent on other platforms is.

On mobile its obvious - its a notification which appears overlaid on the screen at a reasonable place. Mobile devices tend to only have one window at a time, so that makes perfect sense (iOS example here - https://stackoverflow.com/questions/31540375/how-to-toast-message-in-swift).

What is the equivalent on desktop?

Is it notifications? (i.e the things which appear on the top-right on Mac, and also have an analog on Windows?)

Or would it be a floating layer on the current topstack?

If there is dubiety and since there is a clear analog which is easily implementable on iOS then it should be mobileToast until the desktop variant comes around (should it be reasonable to do so) - at which point we can deprecate mobileToast and replace with toast.

(I guess my current feeling is that things which appear at the top-right of the screen on desktop are probably notifications and *not* toasts - notifications linger and are a list, toasts are transient and focused on the UI element/window which is doing the toasting I suppose...)

**Comment by runrevmark** [comment]
Okay - so having briefly chatted to @livecodeali offline, I think we are of the opinion that 'toasts' are transient overlays on the current thing the user is focused on (i.e. window). In contrast, the things which appear on Desktop in top-right are notifications - they are a list of things you can click on to take you to the app - which are distinct on mobile too (pull down from top on iOS).

Now, I'm sure people have mentioned using 'toast like' overlays on desktop apps in LiveCode (maybe @trevordevore ?) - so there if we are happy to reserve the 'toast' verb for that UI thing, then we can use 'toast' in the future. However, I'd suggest a small amount of caution - for now it is probably safest to go with mobileToast - then implement 'toast' for all plats when the details of how it should look/work on Desktop are pinned down.

Android's toast functionality is hard-wired - you just use a message, everything else is done by the OS (styling / placement etc.) - so there's lots of variables which come into play on platforms which don't have a native 'toast' function which will require some design and thought.

**Comment by runrevmark** [comment]
Heh - having re-read the Toast class on Android - you can use formatted text as the message, and there are placement/gravity options. Therefore, let's go with mobileToast for now, we can add an iOS variant subsequently which mimics the basic Android one (which makes it mobile x-platform); then improve later by adding more options and doing a variant for desktop. At which point we can use 'toast' as the command.

**Comment by trevordevore** [comment]
Yes, I use a toast ui element in my desktop apps. I will notify someone about what was copied to the clipboard when clicking a certain button. It pops up, lingers for a moment, and then disapppears.

**Comment by runrevmark** [comment]
@trevordevore Are your toasts on the screen, or current window the notification is from?

**Comment by mwieder** [comment]
Just want to say that Adobe Flex/Actionscript has had toasts on the desktop for many years now. That's where I learned the term.

**Comment by runrevmark** [comment]
@mwieder Cool - do you have a reference for their command/implementation we can look at?

(I thought it was an Android thing)

There's a choice here as to whether a toast is a system-level type window on Desktop which appears on the current screen in a suitable spot (i.e. above all windows), or just in the 'current window' (a bit like on Android - although its the screen there, not window). If there's already other platforms providing Android-like toasts on Desktop then we should probably copy that paradigm.

**Comment by mwieder** [comment]
http://blog.immanuelnoel.com/2011/01/03/toast-on-air-for-android/

**Comment by mwieder** [comment]
There's also https://code.msdn.microsoft.com/windowsdesktop/Sending-toast-notifications-71e230a2/view/SourceCode#content but that looks like a rabbit hole.

**Comment by runrevmark** [comment]
So the ActionScript one is an emulation of the Android idea of 'toast' which is a transient layer above all others on a window (screen on mobile) which disappears after a fixed timeout and has no interaction. The windows one looks more like what other platforms call 'notifications' (e.g. NSUserNotification on Mac) - which appear in top-right of the screen and are clickable.

I'd suggest (since it came from Android) using 'toast' to describe the Android case - the question is what is the best way to implement it on Desktop. Ideally it would be entirely separate from everything else on a stack - not visible to script, as it isn't meant to be interacted with. I suspect @trevordevore does it with a group above all other controls?

We could do it by adding something to the engine to allow LCB libraries to add a widget to a stack which isn't part of the normal control hierarchy (that could be useful for other things too - although none which spring to mind off the top of my head). There's also the question of whether it should be a card level thing (i.e. vanish if the card changes), or a stack level thing... I suspect the latter is probably sufficient.

**Comment by trevordevore** [comment]
I use a disabled group the appears in the same window. That way it ignores all mouse clicks.

**Comment by runrevmark** [comment]
@trevordevore : Heh - sometimes the simplest approaches are the best, hey? ;)

Thinking on this more - we can do that from LCB in the interim - as libraries aren't in anyway restricted from using execute script. However, looking forward, and thinking along the lines of encapsulation - it isn't ideal as the toast changes the control hierarchy of the stack - which means any app using toasts would have to be aware that it might do that. (For example, if you have a loop which repeats over groups - for the time the toast is displayed your code would do something different on Android from the other platforms).

I'm wondering if there is some sort of 'decoration' notion here - a decoration would be a widget which sits above all controls on a card and only manipulatable by the thing which created them (in this case the LCB library). This is essentially what selection handles and graphic tool handles are - currently those things are hard-coded in C++, but they could be moved to something more adaptable with such a notion.

**Comment by mwieder** [comment]
I rather like the idea of toasts being members of a decoration class. I haven't ever come across a toast that consumed events other than the specified timeout. Of course, Microsoft has to repurpose the 'toast' label and create a notification class for it, but I don't think anyone would be disturbed if we ignored that.

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 040f66b

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 040f66b1b565058c9bd5b3f497e9b54c32dd3b4c

**Comment by livecode-vulcan** [comment]
😞 test failure 040f66b1b565058c9bd5b3f497e9b54c32dd3b4c

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1087)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1103)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1077)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/30)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/30)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1082)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1104)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1087)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1103)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1086)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1096)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1119)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1082)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 040f66b

**Comment by livecode-vulcan** [comment]
😎 test success 040f66b1b565058c9bd5b3f497e9b54c32dd3b4c

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1088)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1104)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1078)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/31)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/31)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1083)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1105)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1088)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1104)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1087)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1097)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1120)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1083)

**Pull request merged**
