### PR TITLE
[Bug 16666] Get flaggedRanges with the correct offset

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodepanos review ok 34d3cac

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 34d3cac

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 34d3cacfb98ea816f4eb8426b53a34d2b084d50e

**Comment by livecode-vulcan** [comment]
😎 test success 34d3cacfb98ea816f4eb8426b53a34d2b084d50e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1546)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1565)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1542)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1553)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1565)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1566)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1568)

**Pull request merged**
