### PR TITLE
Coverity scan fixes

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok ae5bf89

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ae5bf898ed00b1d272da437acd85acd058ecb5ee

**Comment by peter-b** [comment]
@livecode-vulcan review okay 7706d76

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 7706d76500451e19af902bb83b9cef628f71e407

**Comment by livecode-vulcan** [comment]
😎 test success 7706d76500451e19af902bb83b9cef628f71e407
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/237)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/300)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/189)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/248)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/183)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/182)

**Pull request merged**
