### PR TITLE
Check that containers are a CT_GROUP before casting to MCGroup*

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 7eab7de

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 7eab7de874d8873eafd8040e9005c55c639b1d37

**Comment by livecode-vulcan** [comment]
😞 test failure 7eab7de874d8873eafd8040e9005c55c639b1d37
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/211)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/275)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/164)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/222)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/157)
- try-mac: unknown

**Comment by peter-b** [comment]
@livecode-vulcan try 7eab7de

**Comment by livecode-vulcan** [comment]
😞 test failure 7eab7de874d8873eafd8040e9005c55c639b1d37
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/223)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/287)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/176)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/234)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/169)
- try-mac: unknown

**Comment by peter-b** [comment]
@livecode-vulcan try 7eab7de

**Comment by livecode-vulcan** [comment]
😎 test success 7eab7de874d8873eafd8040e9005c55c639b1d37
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/235)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/298)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/187)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/246)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/181)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/180)

**Pull request merged**
