### PR TITLE
[[ Bug 20886 ]] Fix crash when class omitted in objc binding

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Question - should this be allowed, or should we throw an error if the "." is missing (even if dynamic binding is intended)?

**Comment by montegoulding** [comment]
@livecodeali at the moment dynamic binding doesn't appear to be documented. We probably need to document it and work out whether the string should be:
```
"objc:[class.](+|-)method[?thread]"
```
or
```
"objc:[class].(+|-)method[?thread]"
```
And throw an error in the event of the incorrect form.

BTW to my mind the `.` is redundant

**Comment by runrevmark** [comment]
I think the '.' can be optional in this case - the fact the bit after the : is a method instead of a class is unambiguously determinable as methods must start with + or - :)

**Comment by montegoulding** [comment]
hmm... I guess the `.` is optional even if there is a class name

**Comment by montegoulding** [comment]
@livecode-vulcan review ok c01b0fc

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok c01b0fc8db8f19cf7ec9a42041dcea781f196949

**Comment by livecode-vulcan** [comment]
😞 test failure c01b0fc8db8f19cf7ec9a42041dcea781f196949

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1185)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1201)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1175)
* try-community-universal-ios-iphoneos11.2: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/128)
* try-community-universal-ios-iphonesimulator11.2: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/128)
* try-community-universal-mac-macosx10.6: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1180)
* try-community-universal-mac-macosx10.9: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1206)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1185)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1201)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1184)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1194)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1224)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1179)

**Comment by montegoulding** [comment]
@livecode-vulcan retry c01b0fc

**Comment by livecode-vulcan** [comment]
😎 test success c01b0fc8db8f19cf7ec9a42041dcea781f196949

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1186)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1202)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1176)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/129)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/129)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1181)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1207)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1186)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1202)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1185)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1195)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1226)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1180)

**Pull request merged**
