### PR TITLE
[[ config ]] Update version of source code expected by javac

### PR DESCRIPTION
**Pull request by livecodemichael**
This patch updates the java config to change the source version to
1.7, needed by classes using java 7 features.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 577204b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 577204bca5129d070dbdb646b8c7ea07f8ad16bc

**Comment by livecode-vulcan** [comment]
😞 test failure 577204bca5129d070dbdb646b8c7ea07f8ad16bc

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/741)
* try-community-armv7-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/150)
* try-community-arm64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/150)
* try-community-x86-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/150)
* try-community-x86_64-android-ndk16r15: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/150)
* try-community-js-emscripten-sdk1.35: [pending](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2267)
* try-community-universal-ios-iphoneos13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.4/builds/1)
* try-community-universal-ios-iphonesimulator13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.4/builds/1)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2296)
* try-community-x86-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2283)
* try-community-x86_64-linux-debian8: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2282)
* try-community-x86-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2317)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2257)

**Comment by livecodeali** [comment]
@livecodemichael Looks like a warning has been turned into an error and we need to remove the Korean comments from that SamsungIapHelper.java file (if we still need to compile it)

**Comment by livecodemichael** [comment]
> @livecodemichael Looks like a warning has been turned into an error and we need to remove the Korean comments from that SamsungIapHelper.java file (if we still need to compile it)

@livecodeali I've been able to recreate the compile error locally by setting the terminal text encoding to ascii. Setting the javac encoding flag appears to resolve the issue.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 9e8e161

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 9e8e161e9290f37dbd6a1b3357f82804156d02a3

**Comment by livecode-vulcan** [comment]
😎 test success 9e8e161e9290f37dbd6a1b3357f82804156d02a3

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/743)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/152)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/152)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/152)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/152)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2269)
* try-community-universal-ios-iphoneos13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.4/builds/3)
* try-community-universal-ios-iphonesimulator13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.4/builds/3)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2298)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2285)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2284)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2319)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2259)

**Pull request merged**
