### PR TITLE
Merge 6.7.7 rc 3

### PR DESCRIPTION
**Pull request by livecodesebastien**
`thirdparty` submodule has been updated appropriately to the branch release-7.1.0

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok eb77e6b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok eb77e6b2abfe8b0b3495a8e9c0c473aa8fbbd983

**Comment by livecode-vulcan** [comment]
😞 test failure eb77e6b2abfe8b0b3495a8e9c0c473aa8fbbd983
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/124)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/122)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/122)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/122)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/125)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/122)

**Comment by peter-b** [comment]
@livecode-vulcan retry eb77e6b

**Comment by livecode-vulcan** [comment]
😎 test success eb77e6b2abfe8b0b3495a8e9c0c473aa8fbbd983
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/130)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/128)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/128)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/128)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/131)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/128)

**Pull request merged**
