### PR TITLE
Fix the Apple Events interface for 64-bit OSX compatibility

### PR DESCRIPTION
**Pull request by livecodefraser**
This PR replaces various obsolete types and function calls with their more modern equivalents.

Tests are needed to ensure that Apple Events integration still works.

I'd recommend reviewing this PR commit-at-a-time as almost all of the changes are going on in a single (massive!) source file, which makes the diff look like a total mess.

[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode/3048)

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodefraser Is it possible to add tests for Apple Events integration by judicious use of livecodescript tests and `shell()`?

**Comment by livecodefraser** [comment]
That's the idea, but it will need a bit of research as to the best way to test it (as whatever other process we're communicating with will need to cooperate with the testing).

**Comment by livecodefraser** [comment]
I've looked at writing tests for the Apple Events interface but it doesn't look feasible in the current test system. To test sending, we need a cooperating application to report that it has received them. To test receiving, the 'on appleEvent' handler needs to be in the current card.

**Comment by runrevmark** [comment]
Tests are run as script-only-stacks arent' they?

In which case, they can be made the current stack when the test is running, and the script will receive the appleEvent message.

**Comment by livecodefraser** [comment]
I'm removing the 'needs-tests' label for now because they're currently impractical in the automated testing system. The current card problem is easy to solve (thanks for the reminder @runrevmark) but, because there are multiple applications responding to the address "LiveCode", strange things seem to happen.(Which instance receives the event seems to be a little unpredictable - I think it may depend on which application has focus at the time...)

**Comment by peter-b** [comment]
Is it feasible to tweak some of these changes to avoid adding new `/* UNCHECKED */` calls?

---

Reviewed 1 of 1 files at r3, 3 of 4 files at r4.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3048#-:-K3PInzy2lUldTySyZVs:636609740)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok d00bc32

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d00bc32f48de88562a1ac0ad1344fe237b314bae

**Comment by livecode-vulcan** [comment]
😎 test success d00bc32f48de88562a1ac0ad1344fe237b314bae
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1338)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1349)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1334)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1344)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1355)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1354)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1359)

**Pull request merged**
