### PR TITLE
[ BUG 17245 ] Fix matchChunk err with optional captured group

### PR DESCRIPTION
**Pull request by thierrydouez**
I'm updating the QCC with a sample stack...

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @thierrydouez, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by peter-b** [comment]
@thierrydouez Could you please add a bugfix note? Please add a one-line file named `docs/notes/bugfix-17245` with the following contents:

``` markdown
# Fix matchChunk error with optional captured group
```

Thanks!

Edit: it should be `bugfix-17245.md`, rather than `bugfix17245`, sorry!

**Comment by peter-b** [comment]
@thierrydouez When I was fixing another regular expression-related bug this morning (#3814) this morning I added a regression test to make sure that the bug doesn't happen again without us catching it.

Do you mind adding a test for this bug, so that we can make sure that it stays fixed?

We've got some documentation on [how to write and run tests](https://github.com/livecode/livecode/blob/develop/docs/testing.md), and you can look at #3814 as an example.

Sorry for not remembering about this earlier!  Luckily this is quite a simple issue to reproduce, so writing a test should be reasonably straightforward, I hope...

Edit: I fixed the link to the testing documentation.

**Comment by peter-b** [comment]
Thanks @thierrydouez, this looks great.  Nice tests.

@livecode-vulcan review ok 6afc296

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6afc296402dc9e0596fcbd648ee9fa2d218422f2

**Comment by livecode-vulcan** [comment]
😞 test failure 6afc296402dc9e0596fcbd648ee9fa2d218422f2
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2314)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2323)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2307)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2324)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2330)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2335)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2346)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 6afc296

**Comment by livecode-vulcan** [comment]
😞 test failure 6afc296402dc9e0596fcbd648ee9fa2d218422f2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2325)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2334)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2318)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2335)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2341)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2346)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2357)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 6afc296

**Comment by livecode-vulcan** [comment]
😎 test success 6afc296402dc9e0596fcbd648ee9fa2d218422f2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2328)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2337)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2321)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2338)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2344)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2349)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2360)

**Pull request merged**
