### PR TITLE
[[Docs]] semi-colon - Pros and cons

### PR DESCRIPTION
**Pull request by seaniepie**
- Added the advantages and disadvantages.
  This is a bit of a punt. It's use is often an oxymoron as for some it make's it easier to read and for others much harder. It is probably inadvisable to use it much with LiveCode although it can be useful at times. It is good though for users to know it's there and can be used, especially for those coming from other coding languages that rely on it. If it is used accidentally it will serve the same purpose, which is good.

### CODE REVIEW

**Comment by livecodeali** [comment]
@seaniepie Since there is only one of each, I suggest saying `The advantage is` and `The disadvantage is`. I'd also remove the `for some` at the end, as you've already qualified it with `can be hard to read`. I think this is a reasonable addition though, thanks!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok fee9ad1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok fee9ad1be1566a159ad73fe466cb796d27840bb7

**Comment by livecode-vulcan** [comment]
😎 test success fee9ad1be1566a159ad73fe466cb796d27840bb7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/429)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/434)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/429)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/429)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/435)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/429)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/429)

**Pull request merged**
