### PR TITLE
[[ Bug 15514 ]] Make sockets work in Linux server.

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by peter-b** [comment]
I like patches that remove code. :ok_hand: 

@livecode-vulcan review ok f983f8c

**Comment by peter-b** [comment]
Obviously this does require release notes etc. before it can be merged...

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f983f8c99671aced49e3fb10976eb8bbbbe78e7b

**Comment by livecode-vulcan** [comment]
😞 test failure f983f8c99671aced49e3fb10976eb8bbbbe78e7b
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/611)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/671)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/560)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/624)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/556)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/549)

**Comment by mwieder** [comment]
Yes, please.

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok 8223be7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 8223be7bffba8d984d74a065ab88c29a8561628c

**Comment by livecode-vulcan** [comment]
😞 test failure 8223be7bffba8d984d74a065ab88c29a8561628c
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/679)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/739)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/628)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/692)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/624)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/616)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 8223be7

**Comment by livecode-vulcan** [comment]
😞 test failure 8223be7bffba8d984d74a065ab88c29a8561628c
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/683)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/742)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/632)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/696)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/628)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/620)

**Comment by livecodesebastien** [comment]
Windows compilation fails, due to the following error:
`..\..\..\engine\src\notify.cpp(63): fatal error C1189: #error :  Threading API not specified`
@livecode-vulcan review not ok 8223be7

**Comment by livecode-vulcan** [comment]
💔 review by @livecodesebastien not ok 8223be7bffba8d984d74a065ab88c29a8561628c

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok 4664763

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 4664763cc874a979b1e116e9fef741a1da3b9bb2

**Comment by livecode-vulcan** [comment]
😎 test success 4664763cc874a979b1e116e9fef741a1da3b9bb2
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/684)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/743)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/633)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/697)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/629)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/621)

**Pull request merged**
