### PR TITLE
Merge develop 6.7 29.01.2016

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodepanos** [comment]
No file updates, just updates in the commit history, thus self-review

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 822cae0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 822cae06ca27ca6d1075f8300f502ff26a7219d1

**Comment by livecode-vulcan** [comment]
😎 test success 822cae06ca27ca6d1075f8300f502ff26a7219d1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1708)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1724)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1703)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1714)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1725)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1727)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1732)

**Pull request merged**
