### PR TITLE
Fixes for some of the minor issues blocking 64-bit Mac support

### PR DESCRIPTION
**Pull request by livecodefraser**
Each of the commits in this PR addresses a different issue so are best reviewed individually. The general theme of this PR is changing some Carbon-specific APIs to their Cocoa replacements.

There are a number of large chunks of code that aren't 64-bit compatible yet; this PR just cleans up some of the low-hanging fruit.

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[engine/src/osxprefix.h, line 26 [r3]](https://reviewable.io:443/reviews/livecode/livecode/3036#-K0B6GwC_RI2B7DTvIkL)** ([raw file](https://github.com/livecode/livecode/blob/dd0d3075c2fb9e8e5e292c28c79ca282f3d497f9/engine/src/osxprefix.h#L26)):</sup>
Is `foundation.h` included at this point? Should this use `MCMemoryMove()`?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3036)

**Comment by peter-b** [comment]
Per off-line conversation with @livecodefraser, `osxprefix.h` is supposed to be included before anything else, so `MCMemoryMove()` isn't guaranteed to be available.

@livecode-vulcan review ok 4224c5e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4224c5ef7322ddf37c3dd95b4e1d98a02a3833b5

**Comment by livecode-vulcan** [comment]
😎 test success 4224c5ef7322ddf37c3dd95b4e1d98a02a3833b5
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/708)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/721)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/709)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/711)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/721)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/732)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/723)

**Pull request merged**
