### PR TITLE
Merge 7.1 into 8.0, including the Business Edition changes

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodefraser It would possibly be useful to have a checklist in the pull request showing what's blocking the merge. I'm quite keen to get this done -- is there any way I can help?

**Comment by livecodefraser** [comment]
Just tested a full installer build and this now builds cleanly.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 8d6aa15

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 8d6aa15c322df0f363af885de893573114ea8dcc

**Comment by livecode-vulcan** [comment]
😎 test success 8d6aa15c322df0f363af885de893573114ea8dcc
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/63)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/63)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/63)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/63)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/65)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/63)

**Pull request merged**
