### PR TITLE
[[ CleanupPathCombiner ]] Remove unused legacy rendering code

### PR DESCRIPTION
**Pull request by livecodeian**
Fixes the following Coverity defects:
[ CID 15679 ] [ CID 15967 ] [ CID 16922 ] [ CID 15484 ] [ CID 16564 ] [ CID 16061 ] [ CID 16062 ] [ CID 16196 ] [ CID 16271 ] [ CID 16466 ] [ CID 16703 ] [ CID 16729 ] [ CID 16857 ]

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian Could you please fix the conflicts in this PR?

**Comment by livecodeian** [comment]
@peter-b OK Done! Is there any way to get notifications from github when pull requests become conflicted?

**Comment by peter-b** [comment]
@livecodeian That would be nice, but sadly not at the moment.  I could probably add a feature to vulcanbot to add a comment once a conflict is detected or something.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4b8ad94

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4b8ad94ded67e88b50c70ba230783a87e5746537

**Comment by livecode-vulcan** [comment]
😞 test failure 4b8ad94ded67e88b50c70ba230783a87e5746537
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2438)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2448)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2431)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2449)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2455)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2459)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2471)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay eccc6df

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok eccc6dfff61939be1127507035e179cded9581c1

**Comment by livecode-vulcan** [comment]
😎 test success eccc6dfff61939be1127507035e179cded9581c1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2463)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2473)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2456)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2474)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2480)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2484)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2496)

**Pull request merged**
