### PR TITLE
[[ Bug 13314 Reopen ]] Fix delimiter issue introduced in 79b29000c9e320f...

### PR DESCRIPTION
**Pull request by livecodesebastien**
...58dc043ef5821125b538fdd0a

### CODE REVIEW

**Comment by runrevmark** [comment]
Reviewed-by: @runrevmark.

**Comment by peter-b** [comment]
@livecode-vulcan reviewed by @runrevmark ok c39ef1e4a4de5e4165abb9f6ed98784b60fc5b91

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok c39ef1e4a4de5e4165abb9f6ed98784b60fc5b91

**Comment by livecodesebastien** [comment]
The pull request was wrongly titled: that's a resurgence of the bug 13314, not 13313.

**Pull request merged**
