### PR TITLE
libfoundation: Make MCClamp() into a template.

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay c29e61a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok c29e61ac63cd95850c487a874feec06c1e405728

**Comment by livecode-vulcan** [comment]
😞 test failure c29e61ac63cd95850c487a874feec06c1e405728
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/602)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/662)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/551)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/615)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/547)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/540)

**Comment by peter-b** [comment]
This needs to be reviewed for the Windows build, which seems to be struggling with it...

@livecode-vulcan review not ok c29e61a

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok c29e61ac63cd95850c487a874feec06c1e405728

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 8909281

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 8909281c83ad801fa8ef03aaa9a6553403847cf7

**Comment by livecode-vulcan** [comment]
😎 test success 8909281c83ad801fa8ef03aaa9a6553403847cf7
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/615)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/675)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/564)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/628)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/560)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/553)

**Pull request merged**
