### PR TITLE
[[ Bug 14056 ]] Setting the cursor to none should have an effect - an…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…d hide the cursor

### CODE REVIEW

**Comment by runrevmark** [comment]
I see how this works, however, the intent of the MCPlatform cursor API was that you should be able to show/hide the cursor independently of the cursor shape.

So if the engine sets the cursor to None, then it should HideCursor, then ShowCursor when it is set to something other than None.

**Comment by livecodesebastien** [comment]
I am not sure that setting the cursor to None is the same as hiding the cursor whilst keeping its shape. If we had a `hide cursor` command, then that would certainly make sense, but here we do ask to set the cursor to nothing.

With the current mechanism, setting `MCcursors[PI_NONE]` to `nil` makes the LiveCode script `set the cursor to none` behave like `unlock cursor`, since no cursor is given. Should I update the way we change cursors?

**Comment by runrevmark** [comment]
Okay - given how the engine is treating a 'NULL' MCCursorRef _and_ that the engine doesn't actually use MCPlatformHideCursor() (it seems). Let's revert to your original approach, with a couple of changes.

Get rid of MCPlatformHideCursor(), and change the name of MCPlatformShowCursor() to MCPlatformSetCursor().

Don't unhide universally in SetCursor since I believe NSCursor keeps a hide count. Instead, setting to None should hide, and setting to non-none should unhide. Hopefully that will keep things happily working with Mac-specific things such as 'hide cursor until mouse moves' (used by the field).

**Comment by livecodesebastien** [comment]
Unhiding the cursor each time SetCursor is called appears to be necessary, because as you stated, it is counted - and

```
lock cursor
set the cursor to none
set the cursor to none
unlock cursor
```

leaves the cursor hidden until the mouse moves

**Comment by runrevmark** [comment]
Well, we shouldn't be hiding the cursor more than once at any one time - so the second set the cursor line shouldn't have any effect (as the cursor is the same). I wonder if the problem is that 'unlock cursor' isn't forcing a cursor update?

**Comment by livecodesebastien** [comment]
The issue is that the number of [NSCursor hide] calls must match the number of [NSCursor unhide] calls (https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSCursor_Class/index.html) - which is now ensured to happen.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok e759cec

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok e759cecf6dce3471cfc6670f75b0fed17a3d57cb

**Comment by livecode-vulcan** [comment]
😎 test success e759cecf6dce3471cfc6670f75b0fed17a3d57cb
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/444)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/504)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/390)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/455)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/390)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/381)

**Pull request merged**
