### PR TITLE
[[ Bug 18871 ]] Add upper and lower case mac field shortcuts

### PR DESCRIPTION
**Pull request by runrevmark**
This patch adds both upper and lower case field shortcut mappings
meaning that, for example, Cmd-C and Cmd-c trigger the copy
action.

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevmark I did a little bit of testing and found that, in most Mac apps, <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd> does not actually do a copy. The copy key combination is <kbd>Cmd</kbd>+<kbd>C</kbd>, but ignores the state of the caps lock.

I'm not clear whether this PR either makes the field ignore the state of the <kbd>Shift</kbd> key, or merely makes it ignore the state of the caps lock.

**Comment by runrevmark** [comment]
@peter-b: I'll take another look - the current patch adds both c and C as valid shortcut chars for copy. However, it sounds like the behavior should be slightly more subtle.

**Comment by runrevmark** [comment]
Okay - I've looked into this and there are actually two places which handle the copy/paste/cut shortcuts. One is in the field where it uses a lookup table, the other is hard-coded in the stack object. On Cmd-V (in particular), the stack object will do a general 'dopaste()' call, which will paste into the active field (if present) - thus overriding the ignoring of the shift key present in the field lookup. I'm not sure of the best approach here - we need to double check the behavior of 'shift' with standard (letter) shortcut keys on other platforms.

**Comment by runrevmark** [comment]
For now, as the patched behavior is better than the current behavior we should merge this. To do it properly will require a fair bit of reworking of the in-engine handling of key combinations.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 111daa6

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 111daa6645aafae580702a1cf69d90fcf7ef7ef8

**Comment by livecode-vulcan** [comment]
😎 test success 111daa6645aafae580702a1cf69d90fcf7ef7ef8

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/720)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/721)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/718)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/719)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/725)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/716)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/717)

**Pull request merged**
