### PR TITLE
[[Bug 19206]] Clipboard always converts plain text to styled text

### PR DESCRIPTION
**Pull request by bwmilby**
Whenever `text` was placed on the clipboard, it was first converted to LiveCode styled text and then put on the clipboard as styled text, RTF, HTML, and plain text.  This introduced errors when pasting to other applications since they would prefer the HTML version which made the text appear double spaced.

Updated `MCClipboard::AddText` such that is will clear the clipboard and only place the plain text representations on the clipboard.  The clipboard needed to be cleared to avoid the HTML/RTF from a previous copy being left on the clipboard which would cause issues when attempting to paste.

Updated related documentation to clarify that placing styled text on the clipboard will convert to the other representations, but plain text will not.  Using the copy text menu command will take styled text as will the copy command (chunk of field syntax).

### CODE REVIEW

**Comment by livecodeali** [comment]
@bwmilby Thanks for this! Sorry I've only just got round to looking at it. The code looks fine, but
I think this should probably have some tests - rather annoyingly they won't run on Travis I don't think but it's worth adding them anyway if they pass locally. 

There are already some clipboard tests here:
https://github.com/livecode/livecode/blob/develop-8.1/tests/lcs/core/engine/clipboard.livecodescript

You can run them locally once you've built the standalone engine by doing
```
<path_to_standalone_engine> <path_to_repo>/tests/_testrunner.livecodescript run <path_to_repo>/tests/lcs/core/engine/clipboard.livecodescript
```

**Comment by bwmilby** [comment]
@livecodeali  Here are the results from my modification and addition:

```
Milby-Retina-iMac:livecode.8 milby$ ./_build/mac/Debug/Standalone-Community.app/Contents/MacOS/Standalone-Community ./tests/_testrunner.livecodescript run ./tests/lcs/core/engine/clipboard.livecodescript
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardLocking [3/3]
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardClearing [2/2]
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardFullClipboardDataAutogeneration [14/14]
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardFullClipboardCoordination [4/4]
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardTypeSelection [13/13]
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardMultipleTypes [5/5]
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardImageTypes [7/7]
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardPrivateKey [4/4]
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardTextToStyled [2/2]
PASS:  ./tests/lcs/core/engine/clipboard: TestCanSetClipboardImageToEmpty [2/2]
PASS:  ./tests/lcs/core/engine/clipboard: TestClipboardTextOnlyOnRawClipboard [2/2]
```
I added explicit tests for HTML not being present when adding text to the clipboard.

**Comment by livecodeali** [comment]
@bwmilby Great stuff as ever, thanks very much!
@livecode-vulcan review ok 5109229

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 5109229ad3ceca0b6ca56607cba56bcf321aebf3

**Comment by livecode-vulcan** [comment]
😎 test success 5109229ad3ceca0b6ca56607cba56bcf321aebf3

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1190)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1206)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1180)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/133)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/133)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1185)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1211)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1190)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1206)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1189)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1199)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1230)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1184)

**Pull request merged**
