### PR TITLE
Merge develop 8.1 16.11.2016

### PR DESCRIPTION
**Pull request by livecodepanos**
Trivial conflict in `version` file

### CODE REVIEW

**Comment by livecodepanos** [comment]
conflict in `engine/src/card.cpp`

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay b6d7795

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok b6d77957f8a836f1c7134cda0d59955d633c17fd

**Comment by livecode-vulcan** [comment]
😞 test failure b6d77957f8a836f1c7134cda0d59955d633c17fd
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/610)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/615)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/610)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/614)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/619)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/611)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/611)

**Comment by livecodepanos** [comment]
Updated the `thirdparty` submodule pointer on `develop` branch

@livecode-vulcan retry b6d7795

**Comment by livecode-vulcan** [comment]
😎 test success b6d77957f8a836f1c7134cda0d59955d633c17fd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/611)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/616)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/611)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/615)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/620)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/612)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/612)

**Pull request merged**
