### PR TITLE
[[ LCB ]] Remove arbitrary widget event message logging.

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok ccc0f62

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ccc0f62200ca70da9b6740312d51172e25057bb5

**Comment by livecode-vulcan** [comment]
😞 test failure ccc0f62200ca70da9b6740312d51172e25057bb5
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/200)
- try-win-x86: unknown\* try-ios: unknown\* try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/211)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/146)
- try-mac: unknown

**Comment by peter-b** [comment]
@livecode-vulcan try ccc0f62

**Comment by livecode-vulcan** [comment]
😞 test failure ccc0f62200ca70da9b6740312d51172e25057bb5
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/224)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/288)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/177)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/235)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/170)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/170)

**Comment by peter-b** [comment]
@livecode-vulcan try ccc0f62

**Comment by livecode-vulcan** [comment]
😎 test success ccc0f62200ca70da9b6740312d51172e25057bb5
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/234)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/297)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/186)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/245)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/180)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/179)

**Comment by peter-b** [comment]
@livecode-vulcan retry ccc0f62

**Comment by livecode-vulcan** [comment]
😎 test success ccc0f62200ca70da9b6740312d51172e25057bb5
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/280)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/343)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/226)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/291)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/226)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/218)

**Pull request merged**
