### PR TITLE
[emscripten] Enable running the LiveCode Builder virtual machine

### PR DESCRIPTION
**Pull request by peter-b**
These changes permit LiveCode Builder widgets to be used in HTML5 apps.
- Enable runtime dynamic binding to C functions by name. This increases the size of the engine somewhat.
- Run the startup script in a temporary stack, in order to allow widgets to be initialised before instantiating the main stack.
- Add a moderately-terrifying implementation of key parts of libffi. This allows LCB code to call C functions that have been compiled to JavaScript.

### CODE REVIEW

**Comment by livecodefraser** [comment]
JavaScript in the middle of a .cpp file... what's not to love?

@livecode-vulcan review okay d6bda30

**Comment by peter-b** [comment]
@livecode-vulcan review by @livecodefraser okay a3a69fe

I think you read the wrong line of this page...

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok a3a69feecb3d987123a79bcdede1c1d500af08b0

**Comment by livecode-vulcan** [comment]
😎 test success a3a69feecb3d987123a79bcdede1c1d500af08b0
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/415)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/415)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/414)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/413)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/419)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/410)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/421)

**Pull request merged**
