### PR TITLE
[[ Bug 14080 ]] Fix find command object resolution failing due to previous error

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodeian Is it possible to write a test for this?

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3c924ed

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3c924ed4751342459f78ebb4f672b8f82f002c10

**Comment by livecode-vulcan** [comment]
😎 test success 3c924ed4751342459f78ebb4f672b8f82f002c10
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/612)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/617)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/612)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/616)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/621)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/613)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/613)

**Pull request merged**
