### PR TITLE
[[ Bug 14696 ]] Fix for opening a file on Windows, if it is too large to...

### PR DESCRIPTION
**Pull request by livecodesebastien**
... get mapped.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodesebastien: You need to check that the stdio handle has been created successfully.

**Comment by runrevmark** [comment]
I wonder if this way of doing things is actually a wise approach. 32-bit apps have a limited address space and as such mapping very large files will fill this up.

You could imagine a situation where a program might map 2 or 3 512-1Gb files and fail because it doesn't have the address space to allocate the memory to process things.

GIven that you can shift the view of a mapped file on Windows - would it make sense to limit the window size to say, 256K and then slide the view as the pointer within the file changes?

(This should perhaps be considered a separate bug - but seems wise as something to consider).

**Comment by runrevmark** [comment]
Reviewed-by: @runrevmark.

**Comment by livecodesebastien** [comment]
Needs to be re-reviewed, after the last commit fixing a potential memory leak, that I pushed.

**Comment by runrevmark** [comment]
Reviewed-by: @runrevmark.

**Pull request merged**
