### PR TITLE
[[ Community Docs ]] capStyle - documentation update

### PR DESCRIPTION
**Pull request by asayd**
- Added note about relationship between roundEnds and capStyle, reported as lacking in bug #8710.
- Added a complete, self-contained example.
- Added relevant references and links.
- Added information about effect of lineSize property on capStyle.
- Added tag.

### CODE REVIEW

**Comment by livecodeali** [comment]
@asayd All properties are filterable through the 'type' filter anyway, so I don't think properties in general should be tagged with 'properties'.

I think the 'properties' tag is actually properties from a more general perspective (the `set` command and custom property manipulation) - indeed it used to be called `Values & Properties` which may be a better name.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok a2bb635

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a2bb6359d5d9dccc44ab5b4d35c8446ddbb685ba

**Comment by livecode-vulcan** [comment]
😎 test success a2bb6359d5d9dccc44ab5b4d35c8446ddbb685ba
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2442)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2452)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2435)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2453)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2459)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2463)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2475)

**Comment by livecodefraser** [comment]
@asayd Quick note for future: the bugfix note needs to have a '#' before the title on the first line (so '# Relation between roundends and capStyle is not documented'; this indicates that the line should be treated as a title in Markdown.

Thanks for the PR!

**Comment by asayd** [comment]
@livecodefraser Is this in the title field of the bug fix note, or in the body? 
Also, is there a comprehensive list of formatting tags for Markdown? I'm just sort of compiling a list as I encounter them. It seems to be similar to Github markdown in some ways.

**Comment by livecodeali** [comment]
Oops, my bad - should have caught that when reviewing.  

@asayd that's in the body of the bug fix note (see [here](https://github.com/livecode/livecode/commit/447d778c2ab0aeb1da28e06b25b691d7e137636b) for example).

It is indeed GitHub flavor markdown.

**Comment by asayd** [comment]
@livecodeali @livecodefraser Yeah, overlooked that in this one; have included it in previous bug fix notes I think. I'll add that note to my checklist.
Should I redo the note and add the #?

**Comment by livecodefraser** [comment]
@asayd No, that's okay - we caught it during a build and I submitted a separate PR that fixed the issue.

**Comment by asayd** [comment]
@livecodeali @livecodefraser I'm considering building a validator stack to check all of these little issues before submitting a PR on a dictionary entry. I'll let you have a look if/when I get to it. Thanks for all your help. Really excited to be getting these dict fixes submitted.

**Comment by peter-b** [comment]
Hi @asayd, I will also be creating a tool that runs as part of the auto test process to catch these issues. We should collaborate maybe!

**Comment by asayd** [comment]
@peter-b Gladly! I've got the skeleton of a checklist that I'll fill out and send you.

**Pull request merged**
