### PR TITLE
[[ Bug 15753 ]] Check that environ variable is not NULL before iterat…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…ing its elements

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 0b5f2f3

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 0b5f2f32fbc2f570bfc905cd0492b54a90d605fd

**Comment by livecode-vulcan** [comment]
😞 test failure 0b5f2f32fbc2f570bfc905cd0492b54a90d605fd
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/429)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/429)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/428)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/427)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/433)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/424)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/435)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 0b5f2f3

**Comment by livecode-vulcan** [comment]
😎 test success 0b5f2f32fbc2f570bfc905cd0492b54a90d605fd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/438)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/438)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/437)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/436)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/442)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/433)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/444)

**Pull request merged**
