### PR TITLE
Include MergExt into the installed IDE application

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3b056fe

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3b056fe7cdd99914e1ee51d12d011e776398e7ef

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b53ec6c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b53ec6cc1cf501a5c9838a703fbc81c1e1e125eb

**Comment by livecode-vulcan** [comment]
😎 test success b53ec6cc1cf501a5c9838a703fbc81c1e1e125eb
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2380)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2390)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2373)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2391)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2397)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2401)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2413)

**Pull request merged**
