### PR TITLE
[Tests] Unify LCB and LCS test trees & make LCB tests use colour

### PR DESCRIPTION
**Pull request by peter-b**
This pull request removes the "lc-run" tests (since everything they check is already tested by the LCB test suite), adds colour status line output to the LCB test suite, and moves all test runners to the top of the `tests` directory.

Tests can now be run by using `make check` (instead of having to run the LCB & LCS tests separately).

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay c90a480

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok c90a48047a12537cc0fe377b947080f144371925

**Comment by livecode-vulcan** [comment]
💥 merge conflict c90a48047a12537cc0fe377b947080f144371925 → 49ef5276286e113c44fac82e7b9d0b9bee6196b6

**Comment by peter-b** [comment]
@livecodefraser I've updated the pull request by merging from develop.

**Comment by livecodestephen** [comment]
I think you've mis-merged the root `Makefile`.

**Comment by peter-b** [comment]
@livecodestephen I didn't add the changes that corrected the merge... _facepalm_

**Comment by livecodestephen** [comment]
@peter-b I had noticed that this PR would conflict with the changes I made, so was on the look out for problems.

**Comment by peter-b** [comment]
@livecode-vulcan review by @livecodestephen not ok f919cb3

**Comment by peter-b** [comment]
@livecodefraser @livecodestephen Okay, I think this is okay now... :grimacing:

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay bdcd4fe

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok bdcd4fe42b9f275084b69504ec19bd279ac69469

**Comment by livecode-vulcan** [comment]
😎 test success bdcd4fe42b9f275084b69504ec19bd279ac69469
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/856)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/870)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/857)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/860)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/870)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/880)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/873)

**Pull request merged**
