### PR TITLE
[[ MobileSockets ]] Port of socket support to iOS and Android.

### PR DESCRIPTION
**Pull request by livecodemichael**
Note, this pull request relies on https://github.com/runrev/livecode-thirdparty/pull/24

### CODE REVIEW

**Comment by runrevmark** [comment]
On discussion with @runrevmichael this PR is almost ready to go - we just have to sort out waking up the event loop when a socket needs servicing on Android.

**Comment by runrevmark** [comment]
@livecode-vulcan review-ok ff0a0ed

**Comment by runrevmark** [comment]
@livecode-vulcan review ok ff0a0ed

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok ff0a0ed68a2a17b2f67c8bf62d0525f2aedeaede

**Comment by livecode-vulcan** [comment]
😞 test failure ff0a0ed68a2a17b2f67c8bf62d0525f2aedeaede
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/398)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/460)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/344)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/409)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/344)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/335)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9c0cb6e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9c0cb6ec0b6638666a044eee79024df4630ea944

**Comment by livecode-vulcan** [comment]
😞 test failure 9c0cb6ec0b6638666a044eee79024df4630ea944
- try-linux-x86: [pending](https://vulcan.livecode.com/builders/try-linux-x86/builds/400)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/462)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/346)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/411)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/346)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/337)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 2716e5d

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 2716e5da52c57d639348a2fe94080bc41e12c719

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 716e5d

**Comment by runrevmark** [comment]
@livecode-vulcan retry 2716e5d

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 2716e5d

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok  88c6462

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 88c6462ba55ad7057d2e0572246e8dcc470466d6

**Comment by livecode-vulcan** [comment]
😞 test failure 88c6462ba55ad7057d2e0572246e8dcc470466d6
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/432)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/492)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/378)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/443)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/378)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/369)

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok  62fd977

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 62fd9779cb0947e271570caf0d08f54c2506e143

**Comment by livecode-vulcan** [comment]
😞 test failure 62fd9779cb0947e271570caf0d08f54c2506e143
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/433)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/493)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/379)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/444)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/379)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/370)

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok 6b9a3e9

**Comment by livecodesebastien** [comment]
@livecode-vulcan try 6b9a3e9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 6b9a3e95f6d2be35e01cbe0ed0b35f6a46f53450

**Comment by livecode-vulcan** [comment]
😞 test failure 6b9a3e95f6d2be35e01cbe0ed0b35f6a46f53450
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/437)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/497)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/383)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/448)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/383)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/374)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 6b9a3e9

**Comment by livecode-vulcan** [comment]
😎 test success 6b9a3e95f6d2be35e01cbe0ed0b35f6a46f53450
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/441)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/501)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/387)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/452)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/387)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/378)

**Comment by livecodesebastien** [comment]
PR https://github.com/runrev/livecode/pull/2296 merged in.

**Pull request merged**
