### PR TITLE
Encrypt command enhancements

### PR DESCRIPTION
**Pull request by marksmithhfx**
- add encryption example 
- provide descriptions for parameters
- add < > brackets to most parameters in the description and to encrypt, decrypt and cipherNames... so they link
- fix miscellaneous typos

### CODE REVIEW

**Comment by livecodeali** [comment]
@marksmithhfx Great stuff, thanks very much for this!
@livecode-vulcan review ok ea03a76

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok ea03a76f3cf3a6be65a8ed7737792ff6d006cf7e

**Comment by livecode-vulcan** [comment]
😎 test success ea03a76f3cf3a6be65a8ed7737792ff6d006cf7e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2466)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2476)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2459)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2477)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2483)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2487)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2499)

**Comment by marksmithhfx** [comment]
And thank you for your patience and assistance. I’ll go take a look at decrypt to see if any similar fix-ups are needed.

Mark

On May 3, 2016, at 5:47 AM, Ali Lloyd <notifications@github.com<mailto:notifications@github.com>> wrote:

@marksmithhfxhttps://github.com/marksmithhfx Great stuff, thanks very much for this!
@livecode-vulcanhttps://github.com/livecode-vulcan review ok ea03a76https://github.com/livecode/livecode/commit/ea03a76f3cf3a6be65a8ed7737792ff6d006cf7e

**Pull request merged**
