### PR TITLE
build: Replace config.sh script with Python script

### PR DESCRIPTION
**Pull request by peter-b**
In order to facilitate builds on Windows where a Bourne shell is
not easily available, this patch replaces the toplevel `config.sh`
script with an equivalent `config.py` Python script.  All the rest
of the build infrastructure is kept the same and all the same
commands will continue to work unchanged.

### CODE REVIEW

**Comment by runrevmark** [comment]
@peter-b: Remember to compare the 'validate' step for windows with Configure.bat - there are some checks in that file (for Speech and QuickTime libraries) which aren't part of the config.sh original.

**Comment by livecodefraser** [comment]
My Python-fu is a bit rusty, but that looks reasonable.

@livecode-vulcan review okay d6aed76

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok d6aed76400840ecddeb33fabfbf78860f03e8494

**Comment by livecode-vulcan** [comment]
😞 test failure d6aed76400840ecddeb33fabfbf78860f03e8494

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/900)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/906)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/898)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/899)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/906)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/897)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/897)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok b93a750

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok b93a750801e40a0e280b60d619c4efc32d128dad

**Comment by livecode-vulcan** [comment]
😞 test failure b93a750801e40a0e280b60d619c4efc32d128dad

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/902)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/908)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/900)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/901)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/908)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/899)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/899)

**Comment by runrevmark** [comment]
@livecode-vulcan review okay 1326963

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 13269632906a8cd9a60d6da1ac95f66b773681d9

**Comment by livecode-vulcan** [comment]
😎 test success 13269632906a8cd9a60d6da1ac95f66b773681d9

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/903)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/909)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/901)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/902)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/909)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/900)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/900)

**Pull request merged**
