### PR TITLE
Refactor MCObjectHandle, 8.0 Edition

### PR DESCRIPTION
**Pull request by livecodefraser**
See https://github.com/livecode/livecode/pull/4173 for details.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok d78ee1c

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d78ee1ca7886585cad3e57b3d2867ec29137d50f

**Comment by livecode-vulcan** [comment]
😎 test success d78ee1ca7886585cad3e57b3d2867ec29137d50f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2677)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2687)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2672)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2688)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2694)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2700)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2712)

**Comment by livecodefraser** [comment]
I'm not sure why tests are failing in the Travis build...

**Comment by livecodefraser** [comment]
Missing commit re-added; Travis is happier now!

**Comment by peter-b** [comment]
@livecode-vulcan review ok 330e6d5

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 330e6d5aaf2976da776f7b52f6318570b15ede59

**Comment by livecode-vulcan** [comment]
😎 test success 330e6d5aaf2976da776f7b52f6318570b15ede59
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2686)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2696)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2681)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2697)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2703)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2709)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2721)

**Pull request merged**
