### PR TITLE
[[ Bug 15129 ]] implement "popup widget ..." as LCS syntax.

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
http://quality.runrev.com/show_bug.cgi?id=15241 :)

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevian, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodefraser** [comment]
Looks good - what still needs to be done?

**Comment by livecodeali** [comment]
Hi Ian, can you add just a brief summary of the popup widget command and how to use it to the bugfix note please? Otherwise it will just end up hiding in the bullet-point list in the release notes :smile:

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 4ea8e54

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4ea8e548c2c06b5a790e6cdaa5e206b6f3abd881

**Comment by livecode-vulcan** [comment]
😎 test success 4ea8e548c2c06b5a790e6cdaa5e206b6f3abd881
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/335)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/335)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/334)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/333)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/338)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/330)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/341)

**Pull request merged**
