### PR TITLE
[[ GImageRep ]] Implement MCImageRep using MCGImageRef

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevian, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay d59435b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok d59435b161bbd653bcd9b062652634839570b9a7

**Comment by livecode-vulcan** [comment]
😎 test success d59435b161bbd653bcd9b062652634839570b9a7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/222)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/221)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/222)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/217)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/224)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/220)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/225)

**Pull request merged**
