### PR TITLE
[Bug 16177] Do not "bind" stack's rect if resizable==false

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
I'm unsure about this - boundrect I believe ensures stacks open on screen - this is unrelated to 'resizable'. (Imagine I save a stack on a huge monitor and put it in the bottom right, then open on a small monitor - I won't see the stack!).

Certainly, boundrect should probably not adjust the size of the stack if resizable is false...

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 771c324

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 771c324dd6d7dd1814951cb34406155f44fd3043

**Comment by livecode-vulcan** [comment]
😎 test success 771c324dd6d7dd1814951cb34406155f44fd3043
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/899)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/908)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/897)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/900)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/909)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/919)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/913)

**Pull request merged**
