### PR TITLE
[[Documentation]] subPin - link to transfermodes

### PR DESCRIPTION
**Pull request by seaniepie**
- Explanation of how the values are calculated.
- Add a line to link to a list of all other transfer modes on the transferModes glossary page

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 53494a9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 53494a9518c2a241030f0fbdd2969cb405056047

**Comment by livecode-vulcan** [comment]
😎 test success 53494a9518c2a241030f0fbdd2969cb405056047
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/342)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/347)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/342)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/342)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/348)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/342)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/342)

**Comment by seaniepie** [comment]
Updated to move the Result section contents as suggested in another pull request.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok de2b7ed

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok de2b7ed6a866cdadc59dde7d167bd65bf89d9ea7

**Comment by livecode-vulcan** [comment]
😎 test success de2b7ed6a866cdadc59dde7d167bd65bf89d9ea7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/368)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/373)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/368)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/368)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/374)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/368)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/368)

**Pull request merged**
