### PR TITLE
[[Dictionary]] Fix 2 links in the "on" control structure entry

### PR DESCRIPTION
**Pull request by bwmilby**
There are 2 links to "<private keyword>" that disappear in the final dictionary.  This update corrects them to "<private> keyword" so they show up and link properly.

### CODE REVIEW

**Comment by livecodeali** [comment]
@bwmilby Thanks! `private keyword (glossary)` should also be removed from the references. (PS these sorts of things always go hand in hand because when the docs were translated from xml to lcdoc, the references lists were auto generated from the referenced items in the text)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 7303fca

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7303fca5f34c6a427ac3f2edcc1bb76e2d4faa5f

**Comment by livecode-vulcan** [comment]
😎 test success 7303fca5f34c6a427ac3f2edcc1bb76e2d4faa5f

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/875)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/891)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/865)
* try-community-universal-ios-iphoneos11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.0/builds/40)
* try-community-universal-ios-iphonesimulator11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.0/builds/41)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/869)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/891)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/875)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/891)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/874)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/884)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/906)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/870)

**Pull request merged**
