### PR TITLE
[[ Bug 17708 ]] Fix overflow of large player position values

### PR DESCRIPTION
**Pull request by livecodeian**
This PR expands the internal position values to 64 bits and changes the LCS property type to double in order to hold larger values.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian It looks like this is causing some build issues on Linux!

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay dbacd6b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok dbacd6b70aefa09e142c49212c50550489c39015

**Comment by livecode-vulcan** [comment]
😎 test success dbacd6b70aefa09e142c49212c50550489c39015
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2554)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2564)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2549)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2565)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2571)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2575)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2587)

**Comment by peter-b** [comment]
@livecode-vulcan review ok c643ab6

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c643ab61e05546a4f27c7ab66a46f44caf02de0c

**Comment by livecode-vulcan** [comment]
😞 test failure c643ab61e05546a4f27c7ab66a46f44caf02de0c
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2556)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/2566)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2551)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2567)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2573)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2577)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2589)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 4d65259

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 4d65259686e0d9dcdad674d96a1316648e52a0ee

**Comment by livecode-vulcan** [comment]
😎 test success 4d65259686e0d9dcdad674d96a1316648e52a0ee
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2605)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2615)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2600)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2616)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2622)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2628)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2640)

**Pull request merged**
