### PR TITLE
[[ Merge 6.7.8 rc 5 ]] 03-12-15

### PR DESCRIPTION
**Pull request by livecodesebastien**
Clean merge.
`version` updated

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 94165c6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 94165c63dbfa627c5898d20affce76e9c86ac602

**Comment by livecode-vulcan** [comment]
😞 test failure 94165c63dbfa627c5898d20affce76e9c86ac602
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1389)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1409)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1385)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1395)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1406)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1405)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1410)

**Comment by livecodepanos** [comment]
Replaced by https://github.com/livecode/livecode/pull/3405

**Pull request closed without merging**
