### PR TITLE
App-based DMGs for OSX (i.e no installer)

### PR DESCRIPTION
**Pull request by livecodefraser**
This allows us to distribute the IDE with a valid signature on it, possibly solving some Gatekeeper-related problems on OSX.

[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode/3616)

### CODE REVIEW

**Comment by livecodefraser** [comment]
The DMGs that this generates have slightly different names to the installer-based ones, so some infrastructure changes will be required (these DMGs omit 'Installer' from the name, as that would just be misleading!).

**Comment by mwieder** [comment]
@livecodefraser Thank you for this. Now how about .deb and/or .rpm files for linux builds? Or even .gz files so that the executable bit is preserved.

**Comment by runrevmark** [comment]
@livecodefraser: I notice 'Setup' is removed from the app bundle... Won't this disable the auto-updater which the IDE launches from within itself on startup?

**Comment by livecodefraser** [comment]
Hence the "WIP" tag ;)

I decided to do a little testing before doing the complicated bit of sorting out the auto-updater (looks like it involves some changes to binary stacks, unhappily).

**Comment by livecodefraser** [comment]
Corresponding IDE change: https://github.com/livecode/livecode-ide/pull/945

**Comment by peter-b** [comment]
Just a couple of minor comments.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 9 of 11 files at r3, 3 of 4 files at r4.
Review status: 14 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

_[builder/tools_builder.livecodescript, line 457 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3616#-KBlrBRRlUHaBDUXySnc:-KBlrBRSPVmLzwDgmYiB:-770101236) ([raw file](https://github.com/livecode/livecode/blob/173c624f08bb31851dc9af9e7822ec67030e0420/builder/tools_builder.livecodescript#L457)):_
I think that this will still allow some shell expansions if `pArg` contains `$` -- is that intentional?

What about this alternative implementation which will prevent all shell expansions?

```
replace "'" with "\'" in pArg
put "'" before pArg
put "'" after pArg
```

---

_[builder/tools_builder.livecodescript, line 463 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3616#-KBlqiqK0NmfwweKmZ8Y:-KBlqiqK0NmfwweKmZ8Z:768546024) ([raw file](https://github.com/livecode/livecode/blob/173c624f08bb31851dc9af9e7822ec67030e0420/builder/tools_builder.livecodescript#L463)):_
Is it necessary to check `the result` after the `shell` invocation?

---

_[engine/rsrc/dmg/fake-installer.sh, line 12 [r3]](https://reviewable.io:443/reviews/livecode/livecode/3616#-KBlt09rlGV0MEES3j0X:-KBlt09rlGV0MEES3j0Y:24182030) ([raw file](https://github.com/livecode/livecode/blob/8778584962dc1313e00156982e2db5e2d2f938d1/engine/rsrc/dmg/fake-installer.sh#L12)):_
This is pretty sweet -- I need to remember this trick!

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3616#-:-KBlwOUnON-8Xj0Zvsr4:2109807384)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4714aa5

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4714aa5c10f1593889e20f49932652363839443c

**Comment by livecode-vulcan** [comment]
😎 test success 4714aa5c10f1593889e20f49932652363839443c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1954)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1967)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1948)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1960)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1970)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1975)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1980)

**Pull request merged**
