### PR TITLE
contrib: Add basic Emacs mode for LiveCode builder.

### PR DESCRIPTION
**Pull request by peter-b**
Currently support some basic syntax highlighting.

### CODE REVIEW

**Comment by livecodestephen** [comment]
Perhaps it would be better to call this livecode-builder-mode, as you'd want a different mode for livecode scripts.

**Comment by peter-b** [comment]
I was going to add logic to the mode to automatically go into the correct submode depending on the file type, like Emacs `cc-mode` does.

**Comment by peter-b** [comment]
Anyway, aren't we expecting people to use the IDE for editing scripts?

**Comment by livecodestephen** [comment]
Doesn't the same go for LCB scripts!

You can't currently edit CGI scripts in the IDE (at least I don't know how to) and anyway on the server you don't have access to the IDE.

**Comment by peter-b** [comment]
At the moment I don't really have time to fiddle around with highlighting for LC Script; if you'd like to do a bit more work on this and propose an alternative implementation that would be great. :smiley:

**Comment by peter-b** [comment]
Just merging this because I doubt many other people are likely to be using Emacs! @livecodestephen, please send patches. :wink:

**Pull request merged**
