### PR TITLE
[[ Bug 16400 ]] Implement canvas clipping bounds property

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @livecodeian, please place the release note fragment in `docs/lcb/notes` so that it ends up in the correct part of the release notes!

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 1cea12a

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 1cea12a2ca231acd5bfd00be6a0dcd29e8ba03a3

**Comment by livecode-vulcan** [comment]
😎 test success 1cea12a2ca231acd5bfd00be6a0dcd29e8ba03a3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1363)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1374)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1359)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1369)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1380)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1379)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1384)

**Comment by peter-b** [comment]
Hi @livecodeian, the LCB release notes have several sections and a slightly different format.  I'm really sorry for neglecting to mention this last night.

```
# LiveCode Builder Host Library

# [16400] Add access to the current clipping bounds in OnPaint
```

**Comment by livecodeian** [comment]
@peter-b Ok, done.

**Comment by peter-b** [comment]
@livecodeian Thank you :+1: 

@livecode-vulcan review by @runrevmark ok f92a57f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok f92a57ff47a6e1720ae0c374bf41c2b26fc71de1

**Comment by livecode-vulcan** [comment]
😎 test success f92a57ff47a6e1720ae0c374bf41c2b26fc71de1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1368)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1379)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1364)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1374)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1385)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1384)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1389)

**Pull request merged**
