### PR TITLE
[[ Bug 16983 ]] GradienRampEditor put upper handle higher

### PR DESCRIPTION
**Pull request by BerndN**

### CODE REVIEW

**Comment by peter-b** [comment]
@BerndN Thank you very much for this bug fix!  Please could you make a few changes to enable us to merge it?
1. It's very helpful for the git commit message to explain what the cause of the bug was, and how the change in the commit fixes the bug.  The commit message you have written does explain what the change is, but it doesn't explain the _why_ of the change.  I encourage you to change the commit message so that it has a little more detail (and to fix the typo)
2. It looks like, in your second commit, you have accidentally created a weirdly named file.  I think you meant to create a file called:
   
   ```
   extensions/widgets/gradientrampeditor/notes/16983.md
   ```
   
   with the contents:
   
   ``` markdown
   # [16983] Put upper handle higher
   ```

I encourage you to either fix up this pull request, or to close it and resubmit a new, corrected one.  If you're not sure how to make the changes I've asked for, please just let me know and we can organise to talk through it (here, or in a Slack chat, or maybe in a Skype call).

Peter

@livecode-vulcan review not ok cde7d3d

**Comment by BerndN** [comment]
I am afraid I goofed up on the file ending .md for the note. Can't figure out how to change this. :(

**Comment by peter-b** [comment]
@BerndN Do you have Xcode installed? Probably we can go through the steps for using the `git` command-line tool to change the problem.
1. You need to get a copy of your GitHub repository onto your computer.  You can do this with:
   
   ``` sh
   git clone https://github.com/BerndN/livecode.git
   cd livecode
   ```
2. Then, you need to check out this branch:
   
   ``` sh
   git checkout patch-1
   ```
3. Next, you move the incorrect file into the correct place
   
   ``` sh
   git mv 'extensions/widgets/gradientrampeditor/notes/[[ Bug 16983 ]] fix location of upper handle' extensions/widgets/gradientrampeditor/notes/16983.md
   ```
4. Now edit the new notes file
5. Update the commit with the corrections
   
   ``` sh
   git add -u
   git commit --amend
   ```
6. Finally you can "force" push your changes into this branch on GitHub, overwriting the current version:
   
   ``` sh
   git push --force origin patch-1
   ```

Hope that helps. :smiley: 

Peter

**Comment by BerndN** [comment]
@peter-b 
thank you for your offer, I deleted the pull request and created a new on 
https://github.com/livecode/livecode/pull/3623
hopefully this fixes the problems.

Well it did not as I can tell from you comment.

My problem is that I feel uneasy in GitHub using the browser, even worse using command line and the combination of Xcode and Github is probably not much help for me either.

I will retry yet another time and hope I get it right.
Thank you for your patience

**Pull request closed without merging**
