### PR TITLE
[[ LiveCode ]] We are called LiveCode

### PR DESCRIPTION
**Pull request by livecodeali**
Squash some remaining pre-LiveCode company names that may well have spread through the test system.

### CODE REVIEW

**Comment by peter-b** [comment]
:grinning: 

@livecode-vulcan review ok 5a4fbd5

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 5a4fbd522df410833c1a17fb44836efbdfbc6755

**Comment by livecodeali** [comment]
I missed one!

**Comment by peter-b** [comment]
That was my fault, too! :frowning:

**Comment by peter-b** [comment]
@livecode-vulcan review ok 6e616ba

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6e616ba556fc3bf2abc10eadcf8b1d331c2c7059

**Comment by livecode-vulcan** [comment]
😎 test success 6e616ba556fc3bf2abc10eadcf8b1d331c2c7059
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/943)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/951)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/940)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/944)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/953)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/962)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/957)

**Pull request merged**
