### PR TITLE
Update clock.lcb

### PR DESCRIPTION
**Pull request by macMikey**
Added fractional hours so the hour hand more closely resembles an analog clock.

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @macMikey, thank you for your contribution! Unfortunately, we won't be able to merge it until you've completed our Contributor License Agreement (CLA). Also unfortunately, the new website update this week means that our CLA webpage isn't currently available, but we'll be fixing it as soon as possible -- and when it's back up, either @runrevmark or I will get in touch and let you know. Thanks again!

**Comment by peter-b** [comment]
Hi @macMikey, you should now be able to sign the LiveCode Contributor's LiveCode agreement on the LiveCode website.  Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.  Let me know when you're all signed up.  Thanks!

**Comment by macMikey** [comment]
Done.  NOW GET MY CODE IN THE CLOCK!!!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok a5c73dd

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a5c73dd0ea37b70bb8870ad2ea4ccd52003493ed

**Comment by livecode-vulcan** [comment]
😎 test success a5c73dd0ea37b70bb8870ad2ea4ccd52003493ed
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/741)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/801)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/691)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/755)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/686)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/678)

**Comment by livecodefraser** [comment]
Done!

**Comment by macMikey** [comment]
Wow.  I actually contributed something, lol.

**Comment by peter-b** [comment]
Please contribute something again soon! :+1:

**Comment by mwieder** [comment]
Mikey - congrats on getting the pull request accepted.

**Pull request merged**
