### PR TITLE
[ Bug 18911 ]] Fix graphical artefacts when reshaping polygon graphics while selected

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok b9e48a0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b9e48a097b825ce33d80f279dbe05fdd090c7efc

**Comment by livecode-vulcan** [comment]
😞 test failure b9e48a097b825ce33d80f279dbe05fdd090c7efc

* try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/676)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/676)
* try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/674)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/675)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/680)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/672)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/672)

**Comment by livecodepanos** [comment]
@livecodeian Since this bug was introduced in 8.1.2 RC-1, could you please rebase this PR against `release-8.1.2` branch? Thanks :)

**Comment by livecodeian** [comment]
Here you go: https://github.com/livecode/livecode/pull/4940

**Comment by livecodepanos** [comment]
I am closing this PR, since it is replaced by https://github.com/livecode/livecode/pull/4940

**Pull request closed without merging**
