### PR TITLE
[Bug 20715] Don't setJAVA_HOME in startup script when deploying to HTML5

### PR DESCRIPTION
**Pull request by livecodepanos**
See http://quality.livecode.com/show_bug.cgi?id=20715

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodepanos I'm _reasonably_ sure [this PR](https://github.com/livecode/livecode/pull/6158) fixes this issue... it might be worth testing

**Comment by livecodepanos** [comment]
@livecodeali I have tested with the latest DP-11, which does include the PR you mentioned. I used the first attachment of the bug report. When clicking on the Test button to deploy to Default Browser, the standalone opens in the browser and then the tab closes (I assume the standalone crashes on startup). The msg box is populated with:
```
buttonTest9dp11
buttonTest9dp11
buttonTest9dp11 - err #2
startup failed: 573,113,1,revInternal_SetJAVA_HOME
buttonTest9dp11 - exit
99
```

**Comment by livecodeali** [comment]
OK, fair enough!
@livecode-vulcan review ok cbba34f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok cbba34f9969d6044428071f267a85041beed1b99

**Comment by livecode-vulcan** [comment]
😎 test success cbba34f9969d6044428071f267a85041beed1b99

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1016)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1032)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1006)
* try-community-universal-ios-iphoneos11.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.1/builds/79)
* try-community-universal-ios-iphonesimulator11.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.1/builds/79)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1011)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1033)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1016)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1032)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1015)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1025)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1048)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1011)

**Pull request merged**
