### PR TITLE
[11919] Add support for URI filenames in SQLITE databases

### PR DESCRIPTION
**Pull request by livecodepanos**
Requires https://github.com/livecode/livecode-thirdparty/pull/125

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodepanos There seems to be a submodule change in one of the commits.

**Comment by livecodepanos** [comment]
> @livecodepanos There seems to be a submodule change in one of the commits.

@runrevmark This was intended, since the changes in the thirdparty submodule branch are required for the tests to pass. I was planning to drop the submodule change once the tests pass. But I see you have already reviewed the other required PR (livecode/livecode-thirdparty#125), so I can safely drop the submodule change now.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 7070d55

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 7070d553b90810a5cab2b23f9f26df53889e2803

**Comment by livecode-vulcan** [comment]
😎 test success 7070d553b90810a5cab2b23f9f26df53889e2803

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/266)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/258)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/258)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/258)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/258)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1780)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/8)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/8)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1811)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1801)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1800)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1835)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1775)

**Pull request merged**
