### PR TITLE
Ios 9.2 support

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodepanos** [comment]
IDE-part of this PR:

https://github.com/livecode/livecode-ide/pull/738

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 8417461

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 84174619b4893150a8a9622f9e614286f1c2c2f0

**Comment by livecode-vulcan** [comment]
😞 test failure 84174619b4893150a8a9622f9e614286f1c2c2f0
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1549)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1568)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1545)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1556)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1568)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1569)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1571)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 8417461

**Comment by livecode-vulcan** [comment]
😞 test failure 84174619b4893150a8a9622f9e614286f1c2c2f0
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1560)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1579)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1556)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1567)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1579)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1580)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1582)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 8417461

**Comment by livecode-vulcan** [comment]
😎 test success 84174619b4893150a8a9622f9e614286f1c2c2f0
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1562)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1581)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1558)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1569)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1581)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1582)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1584)

**Pull request merged**
