### PR TITLE
Merge develop 8.1 09.01.17

### PR DESCRIPTION
**Pull request by livecodeali**
Conflicts:
- engine/src/regex.cpp
`new (nothrow)` had been added in both branches. Keep the develop-8.1 version of all changes.

- engine/src/uidc.cpp
An implicit boolean operator precedence was fixed in develop. Keep the additional parentheses, otherwise keep develop-8.1 changes.

- ide
Will be merged up in a separate PR

- tools/setup_xcode_sdks.py
Updated to 10.2 iOS version as per develop-8.1.

### CODE REVIEW

**Comment by livecodeali** [comment]
Here is a gist of the merge conflict resolution
https://gist.github.com/livecodeali/ba78258ac204465f4f33f7d5f12fae9f

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok ec2cded

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok ec2cded770c0a7d15699e636ddddac31102eda10

**Comment by livecode-vulcan** [comment]
😎 test success ec2cded770c0a7d15699e636ddddac31102eda10

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/799)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/804)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/797)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/798)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/804)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/796)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/796)

**Pull request merged**
