### PR TITLE
navbar: General refactor.

### PR DESCRIPTION
**Pull request by peter-b**
- Remove separate iOS and Android themes
- Rename properties and signals to be consistent with other
  widgets.
- Use standard LiveCode properties and property names wherever
  possible.

### CODE REVIEW

**Comment by peter-b** [comment]
Must merge livecode/livecode-ide#982 with this PR.

**Comment by livecodeali** [comment]
- The labels of the `hilited` properties maybe need to be changed from "Selected ..." to "Highlighted ..."
- Not a huge deal but there are a bunch of `my height`s that can be `mHeight`s

**Comment by peter-b** [comment]
@livecodeali Should I implement the **opaque** property?

**Comment by livecodeali** [comment]
@peter-b  Hmmm... maybe? I'm not sure how important it is given you can just change the background color

**Comment by peter-b** [comment]
@livecodeali Well, it's a bit of a hassle to set the background colour to a transparent paint (you have to use a pattern).  I deleted the previously-existing `backgroundOpacity` property, but you renamed it to `opaque` in the header bar widget and seemed to do something sensible with it.

**Comment by livecodeali** [comment]
@peter-b I'm not sure - the other option is to delete the opaque property from the header bar of course.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 40bc6c5

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 40bc6c5179392ace59097850081bcde605fd130e

**Comment by livecode-vulcan** [comment]
😎 test success 40bc6c5179392ace59097850081bcde605fd130e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2075)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2086)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2069)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2083)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2089)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2097)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2103)

**Pull request merged**
