### PR TITLE
[[ Bug 20283 ]] Replace dead openssl.org links

### PR DESCRIPTION
**Pull request by AndyPiddock**

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @AndyPiddock, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by livecodepanos** [comment]
@AndyPiddock Could you add a bugfix note as well?

You should create a file `docs/notes/bugfix-20283.md` which will only contain a short description of the bug fixed, starting with `#` followed by one space. In this case something like:

```
# Updated broken links in `encrypt using rsa` dictionary entry
```

Thanks :)

**Comment by AndyPiddock** [comment]
Ok done.
Q. Should this be done for all doc pull requests or only after all reviews passed or when closed?
Also as in this case there are 2 files touched against the same bug id, would 2 entries go in the one file?

**Comment by livecodepanos** [comment]
Thanks @AndyPiddock .

Sorry I was not clear. I meant you should add a bugfix note in the same PR. Don't worry about it now, I will review them as separate PRs, but in the future all the changes (code and/or docs updates + bugfix note) for a specific bug should be included in the same PR.

The bugfix note is required only if there is a corresponding report in BugZilla.

**Comment by AndyPiddock** [comment]
OK, thanks...still learning.

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok acfb234

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok acfb23461037b1793ba0fcd614293f0242af795c

**Comment by livecode-vulcan** [comment]
😎 test success acfb23461037b1793ba0fcd614293f0242af795c

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/154)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/146)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/146)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/146)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/146)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1668)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/50)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/50)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1698)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1691)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1688)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1724)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1665)

**Pull request merged**
