### PR TITLE
[[ Bug 15630 ]] Ensure script object property getter matches syntax

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok ff9dfd9

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok ff9dfd95392ec1f3a199e968b440d5e550eecb65

**Comment by livecode-vulcan** [comment]
😎 test success ff9dfd95392ec1f3a199e968b440d5e550eecb65
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/694)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/754)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/644)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/708)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/639)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/631)

**Comment by trevordevore** [comment]
@livecodeali I'm still having problems with <get property>. I'm getting a runtime error when trying to execute:

get property "top" of my script object

**Comment by livecodeali** [comment]
@trevordevore Have you done a clean rebuild of lc-compile? Also are you testing using the extension builder? You might need to make a trivial change in the file just to jog it into recompiling.

**Comment by trevordevore** [comment]
I have been making trivial changes to recompile using the extension builder. I just tried cleaning and building the lc-compile project in XCode prior to building the development project. Still no love. I added break points and the new code in module-engine.cpp is getting called. I'll try cleaning out some more things and see if I can get it to work.

**Comment by livecodeali** [comment]
Hmm, this is what I am trying (in an OnGeometryChanged handler)

```
    get property "top" of my script object
    log the result
```

Are you subsequently using the result in any expression? I had an error for a while in my test code because property "topleft" returns a String while property "top" returns a Number.

**Comment by trevordevore** [comment]
Ah, the result was the issue. I was treating the result as a String in all cases. Not sure when that changed as the code was working previously.

**Comment by trevordevore** [comment]
Silly me, my original code never used "top". I actually changed it while trying to track down the original problem. I have always been using a property which returned a string.

**Comment by livecodeali** [comment]
Heh, easily done. Anyway, thanks for spotting the bug in the first place :+1:

**Pull request merged**
