### PR TITLE
tools: Add a helper script for setting up Xcode for LiveCode builds

### PR DESCRIPTION
**Pull request by peter-b**
Add a script that installs all of the SDK symlinks needed for building LiveCode into a Xcode app bundle (and checks whether they're all available, of course!)

Originally written for checking vulcan buildslave setup, but I think it might be more generally useful.

@livecode-vulcan assign reviewer @livecodefraser

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review not ok 6bfe8a7

**Comment by livecode-vulcan** [comment]
:broken_heart: review by @livecodefraser not ok 6bfe8a71f254aaf97f87746c2bb98dad737e26f6

**Comment by livecodefraser** [comment]
@livecode-vulcan review ok 6bfe8a7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 6bfe8a71f254aaf97f87746c2bb98dad737e26f6

**Comment by peter-b** [comment]
Resubmitting for develop-6.7.

**Pull request closed without merging**
