### PR TITLE
[[ DisableATS ]] Add mobile-disable-ats.plist in the installer package

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Already reviewed in https://github.com/livecode/livecode-ide/pull/631
@livecode-vulcan review ok 770929a by @runrevmark

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok 770929a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 770929ae88788ea3c3ba690baa2b7305dc45d569

**Comment by livecode-vulcan** [comment]
😞 test failure 770929ae88788ea3c3ba690baa2b7305dc45d569
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1011)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1019)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1008)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1011)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1022)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1029)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1026)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 770929a

**Comment by livecode-vulcan** [comment]
😎 test success 770929ae88788ea3c3ba690baa2b7305dc45d569
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1012)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1020)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1009)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1012)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1023)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1030)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1027)

**Pull request merged**
