### PR TITLE
Oval points

### PR DESCRIPTION
**Pull request by mwieder**
Hot on the heels of allowing effective points for rects, roundrects, and regular polygons, I figured out how to allow points for ovals by treating them as roundrects with a radius equal to the greater of the the rect width or height. Since the previous pull request hasn't been merged into master yet, it looks like I'm actually adding more lines than are in this pull request - there are actually very few, since the heavy lifting was already done for roundrects. I created this branch off the rect_points branch, since it leverages that work.

### CODE REVIEW

**Comment by livecodefraser** [comment]
Thanks for the contribution.

Does it obey the startAngle and arcAngle properties of oval graphics? If not, how problematic would the change be?

Regards,
Fraser

**Comment by mwieder** [comment]
Ah - good point. No, this doesn't take startAngle and arcAngle into consideration. I've been leveraging the roundedRect functions, treating an oval as a roundRect with a big radius. I'm now looking into cloning MCU_roundrect so that I can factor in the additional two variables, and hoping the math won't be too much for my head.

**Comment by mwieder** [comment]
Whew! I spent way more time than I'd like to admit struggling with this function. Finally gave up and rewrote it pretty much from the ground up, and it turned out much cleaner that way. A little faster, too, I think, since I'm precomputing some of the variables. This also gives a side-effect of smoother roundrect corners, since they now use 90 points instead of 10.

**Comment by mwieder** [comment]
Any chance of getting this merged into 6.7? Ovals are the only graphic object now that don't have effective points. I was hoping this could get into dp5 or dp6. Now I hope for a dp7.

**Comment by runrevmark** [comment]
Hi Mark - thanks for this.

It got to the top my list today so it will be in the next build of 6.7-dp-7 which should appear at the end of the week. The only tweak I made was changing a && to an || - the latter was why it was appearing jaggy when removing duplicate points (with the previous code not commented out, only points that differed in both x and y were being added thus eliminating any horizontal or vertical segments).

Warmest Regards,

Mark.

**Comment by mwieder** [comment]
Doh! Must have been a long night here... I stared at that && statement for quite a while and didn't catch that. Thanks for sorting it out.

**Pull request closed without merging**
