### PR TITLE
[[ Gyp ]] Fix exports from iOS engines

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3860f77

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3860f77304a510051a912989d240a0c935c853bf

**Comment by livecode-vulcan** [comment]
😞 test failure 3860f77304a510051a912989d240a0c935c853bf
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/652)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/712)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/601)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/665)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/597)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/590)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 2b5252b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 2b5252bfe6f10231e074e2e647de1d382df82078

**Comment by livecode-vulcan** [comment]
😎 test success 2b5252bfe6f10231e074e2e647de1d382df82078
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/654)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/714)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/603)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/667)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/599)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/592)

**Pull request merged**
