### PR TITLE
Unbreak OSX builds on Travis

### PR DESCRIPTION
**Pull request by livecodefraser**
A number of problems happened on Travis, which have now all been resolved:
- [X] Travis auto-updated to an Xcode 7.3 VM (we now explicitly choose a VM)
- [X] LiveCode wouldn't compile against 10.10 or newer OSX SDKs (fixed up to 10.11 SDK)
- [X] The version of Ruby in the Xcode 7.3 VM was very crashy (we now request a particular version)

### CODE REVIEW

**Comment by peter-b** [comment]
This PR fixes bug 16211, correct? (It doesn't need a release note)

**Comment by livecodefraser** [comment]
I added one anyway 😛

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4be93ea

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4be93ea24086043d200c04828d9b5f87b8c2f210

**Comment by livecode-vulcan** [comment]
😎 test success 4be93ea24086043d200c04828d9b5f87b8c2f210
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/362)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/367)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/362)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/362)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/368)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/362)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/362)

**Pull request merged**
