### PR TITLE
[[ Bug ]] Ensure extensions and dependencies are added and loaded in correct order in standalones

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Requires https://github.com/runrev/livecode-ide/pull/385

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1e4a001

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1e4a001ea45bfe8b8905d243352d547da38e6c6e

**Comment by livecode-vulcan** [comment]
😎 test success 1e4a001ea45bfe8b8905d243352d547da38e6c6e
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/595)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/655)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/544)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/608)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/540)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/533)

**Pull request merged**
