### PR TITLE
[Bugs 8774 & 19008] Modal placement issues

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodefraser** [comment]
My last comment disappeared into the ether, apparently... it basically said "looks good to me, hopefully the behaviour change is uncontroversial; @runrevmark may want to chime in".

@livecode-vulcan review okay 20572ce

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 20572ce945af68c2e72f68bb9204954f94eecb8b

**Comment by livecode-vulcan** [comment]
😞 test failure 20572ce945af68c2e72f68bb9204954f94eecb8b

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/783)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/788)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/781)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/782)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/788)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/780)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/780)

**Comment by montegoulding** [comment]
@livecode-vulcan try 20572ce

**Comment by livecode-vulcan** [comment]
😎 test success 20572ce945af68c2e72f68bb9204954f94eecb8b

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/787)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/792)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/785)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/786)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/792)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/784)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/784)

**Pull request merged**
