### PR TITLE
[[ Navbar ]] Various updates to make the navBar more user-friendly

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @runrevben,

When you've reviewed a pull request, please leave a comment like this: `@livecode-vulcan review ok <sha-1>`.  This will tell the continuous integration system that the review has been passed, and will automatically trigger testing the branch.

I'll do that for you now. :smiley: 

@livecode-vulcan review by @runrevben ok c85d5ed

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok c85d5eddc1cbd32a22bd82ffe9bc16243c5b0a44

**Comment by livecode-vulcan** [comment]
😞 test failure c85d5eddc1cbd32a22bd82ffe9bc16243c5b0a44
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/197)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/261)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/150)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/208)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/143)
- try-mac: unknown

**Comment by runrevben** [comment]
@livecode-vulcan review ok b42382b

**Comment by runrevben** [comment]
@livecode-vulcan review ok b42382b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok b42382b5933614c57eb697203e85a3436165d490

**Comment by livecode-vulcan** [comment]
😞 test failure b42382b5933614c57eb697203e85a3436165d490
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/208)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/272)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/161)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/219)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/154)
- try-mac: unknown

**Pull request merged**
