### PR TITLE
[[ Bug 14642 ]] Cleanup the Undo list when reverting a stack to its s…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…aved state

### CODE REVIEW

**Comment by runrevmark** [comment]
If the problem here is related to the listener stuff - then that is probably where the problem is.

It _sounds_ like a deleted object (which is not quite the same as delete t_object_ptr) might not be being removed the listeners at the point it is delete control'd?

**Comment by livecodesebastien** [comment]
Well the objects are removed from the listener list when they are deleted - but in the case that a control is deleted with the backspace key, it is not properly deleted, but moved onto the Undo stack.
I don't think that popping an action from the Undo stack adds again the object in the listener list - but that might be something we want the engine to do.

**Comment by runrevmark** [comment]
It requires a script action (for example in the project browser) to listen to an object - so there's no problem in re-establishing the listen (the Project Browser will do so when the object is undeleted, if it is).

If you look at the code then the BackSpace action in MCStack causes MCSellst::del() to be executed. This results in MCObject<virtual>::del() being invoked - the latter removes the object from the script world and is the correct point for listens to be flushed. (Think of deleting an object as a two step process - it's first unhooked from the script world, and _then_ it is either put on the undo list _or_ put on the todelete list). When a delete action is undone, all the script world hooking is redone - including sending the various messages (such as new<controltype>) which you'd expect.

Of course - having just looked at the code to see what needs to be done to 'unlisten' an object - I realize that it isn't the listening mechanism which is at fault at all. The listening mechanism runs entirely on 'weak handles' (MCObjectHandle), such weak handles should lose their ptr to the object they represent when the object is being deleted. Thus - if the crash is indeed down to a dangling pointer in the listening subsystem, then it will be because an object's weak handle is not being unhooked when ::del() is invoked.

At the moment, two actions are performed in MCObject::scheduledelete() (which is invoked after ::del() when the object is not to be undone) which _should_ be done in MCObject::del():

```
    if (m_weak_handle != nil)
    {
        m_weak_handle -> Clear();
        m_weak_handle = nil;
    }

    // MW-2012-10-10: [[ IdCache ]] Remove the object from the stack's id cache
    //   (if it is in it!).
    if (m_in_id_cache)
        getstack() -> uncacheobjectbyid(this);
```

These two clauses should be moved to MCObject::del() I think.

**Comment by livecodesebastien** [comment]
That indeed makes a perfect sense to move these actions in `MCObject::del`.

**Comment by livecodesebastien** [comment]
Superseded by https://github.com/runrev/livecode/pull/2355 as cleaning the Undo list is not the correct fix.

**Pull request closed without merging**
