### PR TITLE
[Bug 18875] Release notes & other final tweaks for 9.0.0-dp-2

### PR DESCRIPTION
**Pull request by peter-b**
- Include getopt library in release
- Ensure script-only library release notes are scanned and included
- Other minor release note tweaks

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 54231a3

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 54231a331d32cf65b24ffc3c7f4a628b25b1681c

**Comment by livecode-vulcan** [comment]
😎 test success 54231a331d32cf65b24ffc3c7f4a628b25b1681c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/618)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/623)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/618)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/622)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/627)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/619)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/619)

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 506d227

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 506d2274419275904baad72dd7ad15f19a0a4cb4

**Comment by livecode-vulcan** [comment]
😎 test success 506d2274419275904baad72dd7ad15f19a0a4cb4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/623)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/628)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/623)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/627)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/632)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/624)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/624)

**Pull request merged**
