### PR TITLE
[[ Bug 15386 ]] Do not over-release the stack filename as ~MCStack ta…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…kes care of it

### CODE REVIEW

**Comment by livecodesebastien** [comment]
This simple line of code was causing over release of kMCEmptyString, and memory corruption which was causing a crash on closing (whence the server hang).

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 4262e5f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 4262e5f82f0241e53d5168b130399d6aba339bfa

**Comment by livecode-vulcan** [comment]
😞 test failure 4262e5f82f0241e53d5168b130399d6aba339bfa
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/164)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/228)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/117)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/175)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/110)
- try-mac: unknown

**Comment by livecodesebastien** [comment]
Merged in for LiveCode 7.0.6 RC 1, as the crash is pretty critical, and the fix is required as soon as possible

**Pull request merged**
