### PR TITLE
[Bug 16163] 'is a number' should return false for infinity

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-panos: This certainly fixes that particular issue but it fixes it in the wrong place.

The issue is more general - 'infinity' shouldn't be considered to be a number at all in any context I don't think... It has implications for comparisons which try numbers first. I think the problem is actually in numeric conversion - rather than in specific syntax. This and the other related bug reports all stem from that.

It needs a bit more discussion to work out how 'infinity' should be expressed and returned in LiveCode to ensure it doesn't have these problems.

**Comment by peter-b** [comment]
@runrevmark There's no obvious solution.  For example, when trying to find the minimum of a set of floating-point numbers, the normal algorithm is to start off with the "current minimum" set to infinity, e.g.:

```
function FindMin tValues
    local tVal, tMinVal
    put Infinity into tMinVal
    repeat for each element tVal in tValues
        if tVal < tMinVal then
             put tVal into tMinVal
        end if
    end repeat
    return tMinVal
end function
```

For that to work, there needs to be **some** way of obtaining a floating-point infinity as a number in LiveCode.  I'm not convinced that "Ban Infinity!" is an appropriate response here.

**Comment by peter-b** [comment]
@runrevmark Or, more accurately, there needs to be some way of obtaining a floating-point infinity _and using math operations on it_.

**Comment by runrevmark** [comment]
@peter-b: Yes - we need to figure out how to express infinity as a token which means that it doesn't disrupt string comparisons! The problem at the moment is that "infinity" can be converted to a number - this breaks the typeless comparison operation which does:

if left and right are numbers, then compare as numbers

Now, float(inf) == float(inf) based on the IEEE754 standard... However, if 'infinity' is considered to be a numeric token - then so is INFinity. Thus you still have this problem:

set the caseSensitive to true
answer "Infinity" is "INFINITY"

Now, to be fair this is true for strings like "1e10" and "1E10" - however, at least they are clearly numbers... Whereas the token "infinity" isn't necessarily, for anyone just writing code which processes strings.

**Comment by livecodefraser** [comment]
Add a function that returns infinity? 

Or we can just accept the infinity symbol, now that scripts are Unicode ;)

**Comment by runrevmark** [comment]
Having looked at this in more depth - "infinity" is a number has been true for a long time... Thus this isn't a bug. The problem is actually http://quality.runrev.com/show_bug.cgi?id=16162 where it appears to be data coming from a field is not behaving correctly.

**Pull request closed without merging**
