### PR TITLE
[Bug 16754] Make sure fld line spacing is correct when displaying images via imageSource

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan 3692f48

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 3692f48

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 3692f48c5beb8182256b2e3ec695e85b4f16899d

**Comment by livecode-vulcan** [comment]
😞 test failure 3692f48c5beb8182256b2e3ec695e85b4f16899d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1824)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1837)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1818)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1830)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1840)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1843)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1849)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 3692f48

**Comment by livecode-vulcan** [comment]
😎 test success 3692f48c5beb8182256b2e3ec695e85b4f16899d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1825)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1838)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1819)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1831)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1841)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1844)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1850)

**Pull request merged**
