### PR TITLE
[[ Bug 11277 ]] Refactored fix for the bug 11277

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Supersedes https://github.com/runrev/livecode/pull/2329

**Comment by runrevmark** [comment]
Looks good - much neater :)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 5678faf

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 5678faff2c9336ea3b941e132094a68f5cd789b6

**Pull request merged**
