### PR TITLE
[[ Bug 15302 ]] Fix misspellings of occurred in dictionary

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 783ae26

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 783ae2672d6de046bd9fdc4947f2498be18f3d4b

**Comment by livecode-vulcan** [comment]
😞 test failure 783ae2672d6de046bd9fdc4947f2498be18f3d4b
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/153)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/217)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/106)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/163)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/99)
- try-mac: unknown

**Comment by peter-b** [comment]
@livecode-vulcan try 783ae26

**Comment by livecode-vulcan** [comment]
😎 test success 783ae2672d6de046bd9fdc4947f2498be18f3d4b
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/228)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/292)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/181)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/239)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/174)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/174)

**Pull request merged**
