### PR TITLE
[[ Tests ]] Add old script tests to be run during CI

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok aa2ed21

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok aa2ed2141cde82b1112f888dc5a83b458479640e

**Comment by livecode-vulcan** [comment]
😎 test success aa2ed2141cde82b1112f888dc5a83b458479640e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/692)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/705)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/693)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/695)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/705)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/716)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/707)

**Comment by peter-b** [comment]
@livecodeali Woo! It works! I think there's a bit to do to reorganise the tests, give them proper names, etc. but this is a massive step forward. :100: 

@livecode-vulcan review ok b48d576

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b48d576b01ff1d48042eeed42833c3dc76797513

**Comment by livecode-vulcan** [comment]
😎 test success b48d576b01ff1d48042eeed42833c3dc76797513
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/694)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/707)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/695)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/697)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/707)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/718)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/709)

**Comment by livecodeali** [comment]
Wahey!

**Pull request merged**
