### PR TITLE
[[docs]] markerFilled - graphic param define

### PR DESCRIPTION
**Pull request by seaniepie**
- Added the correct reference of graphic (object or keyword)

### CODE REVIEW

**Comment by livecodeali** [comment]
@seaniepie The `graphic` keyword specifically refers to the use of it as a tool, as in `choose graphic tool`, so I think these should all be references to `graphic (object)` .

Arguably the reference to `graphic (keyword)` is not needed in this entry so it could be removed and the references wouldn't have to be disambiguated.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 1508030

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 15080308f7c8a1c3f9842312ed807251a7a4dcbc

**Comment by livecode-vulcan** [comment]
😞 test failure 15080308f7c8a1c3f9842312ed807251a7a4dcbc
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/523)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/528)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/523)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/527)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/532)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/524)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/524)

**Comment by peter-b** [comment]
@livecode-vulcan retry 1508030

**Comment by livecode-vulcan** [comment]
😎 test success 15080308f7c8a1c3f9842312ed807251a7a4dcbc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/535)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/540)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/535)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/539)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/544)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/536)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/536)

**Pull request merged**
