### PR TITLE
Merge develop 8.1 06.03.17

### PR DESCRIPTION
**Pull request by livecodeali**
Conflicts:
      engine/src/object.cpp
      engine/src/opensslsocket.cpp

Conflict in object.cpp just because the call to `exec` [here](https://github.com/livecode/livecode/pull/5235/files#diff-d5f23e9865ddcd6d2c03e6bdb5b0a9a3R2904) passes params in develop.

In opensslsocket.cpp some code had been slightly restructured, so just a case of adding the `MCObjectHandle` logic from [here](https://github.com/livecode/livecode/pull/5189/files) to the develop version.

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 6eec941

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 6eec94190315ce1788983abfc3ff85b6e8068c9d

**Comment by livecode-vulcan** [comment]
😞 test failure 6eec94190315ce1788983abfc3ff85b6e8068c9d

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1093)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1096)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1088)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1094)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1098)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1110)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1089)

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 1e897c8

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 1e897c8e9aa6b2da69ea0dfc65ff568d36dea9df

**Comment by livecode-vulcan** [comment]
😞 test failure 1e897c8e9aa6b2da69ea0dfc65ff568d36dea9df

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1095)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1098)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1090)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1096)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1100)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1112)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1091)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 1e897c8

**Pull request merged**
