### PR TITLE
Replace various filesystem-related APIs that are gone in 64-bit mode

### PR DESCRIPTION
**Pull request by livecodefraser**
The affected code deals primarily with resource files and forks.

[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode/3174)

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[engine/src/dskmac.cpp, line 2440 [r4]](https://reviewable.io:443/reviews/livecode/livecode/3174#-K3PRnGbrOF2ltW9i7K8:-K3PRnGbrOF2ltW9i7K9:1361978772) ([raw file](https://github.com/livecode/livecode/blob/1e82a4384363d0a83599aa2cfcbea589de687f4a/engine/src/dskmac.cpp#L2440)):_
Is it feasible to return false rather than leaving these `/* UNCHECKED */`?

---

_[engine/src/dskmac.cpp, line 2485 [r4]](https://reviewable.io:443/reviews/livecode/livecode/3174#-K3PS5NKl1UDsp5GaGYY:-K3PS5NKl1UDsp5GaGYZ:-221068985) ([raw file](https://github.com/livecode/livecode/blob/1e82a4384363d0a83599aa2cfcbea589de687f4a/engine/src/dskmac.cpp#L2485)):_
Currently `MCStringGetNativeChars()` will forcibly nativize `p_value`.  I think you should use a `MCAutoStringRefAsNativeChars` here.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3174)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok 007a9e1

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 007a9e190aa04c225475bdaf7beed109bca787ab

**Comment by livecode-vulcan** [comment]
😞 test failure 007a9e190aa04c225475bdaf7beed109bca787ab
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1336)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1347)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1332)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1342)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1353)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1352)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1357)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 007a9e1

**Comment by livecode-vulcan** [comment]
😞 test failure 007a9e190aa04c225475bdaf7beed109bca787ab
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1340)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1351)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1336)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1346)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1357)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1356)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1361)

**Comment by peter-b** [comment]
@livecode-vulcan review ok e771b94

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e771b9417a94cd59ffe778546f7eaad58c1a1b92

**Comment by livecode-vulcan** [comment]
😎 test success e771b9417a94cd59ffe778546f7eaad58c1a1b92
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1366)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1377)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1362)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1372)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1383)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1382)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1387)

**Pull request merged**
