### PR TITLE
Refactor HyperCard import to use ValueRefs

### PR DESCRIPTION
**Pull request by livecodefraser**
[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode/3168)

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review not ok 03e429f

Build failures on Linux.

**Comment by livecodefraser** [comment]
Quite unbeknownst to me, the HyperCard import code is actually on all platforms and not just OSX. I'll have to remove the OSX conditional from the MCString...PascalString functions in libFoundation.

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 03e429f24c06d9af90591e053caa6529b7e5fd57

**Comment by peter-b** [comment]
Reviewed 2 of 6 files at r1, 3 of 5 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

_[engine/src/osxmisc.mm, line 209 [r2]](https://reviewable.io:443/reviews/livecode/livecode/3168#-K3PLXQvWsnEVqWY9CZt:-K3PLXQvWsnEVqWY9CZu:-1182950049) ([raw file](https://github.com/livecode/livecode/blob/f5139837eadffc6b82ac4105c8b01ce68fa86d81/engine/src/osxmisc.mm#L209)):_
Is it possible to check these and produce `IO_ERROR` on failure?

---

_[libfoundation/include/foundation-auto.h, line 606 [r2]](https://reviewable.io:443/reviews/livecode/livecode/3168#-K3PMGe_iXJdWBT0SVM_:-K3PMGe_iXJdWBT0SVMa:-803307548) ([raw file](https://github.com/livecode/livecode/blob/f5139837eadffc6b82ac4105c8b01ce68fa86d81/libfoundation/include/foundation-auto.h#L606)):_
It slightly bothers me that, on non-Apple platforms, this might result in the a Pascal string that doesn't technically-speaking have the correct encoding.  :wink: 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3168)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok 2fcc644

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3168#-:-K3pIZ9Tk-HfwZ0HCYl6:1051612322)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2fcc644c9251c4a66b70b7f6726e5fedf7e87600

**Comment by livecode-vulcan** [comment]
😎 test success 2fcc644c9251c4a66b70b7f6726e5fedf7e87600
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1265)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1277)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1262)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1271)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1282)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1282)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1286)

**Pull request merged**
