### PR TITLE
[21453] Fix crash when calling 'open process'

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecodepanos could you tell me where there crash is? Is it in a debug build at `__MCAssertIsString` in `MCStringGetLength`? If so I think perhaps the least risky fix is in `MCS_startprocess_launch`:

```
if (docname != nullptr && MCStringGetLength(docname))
```

The problem I see with the patch as is there's different code paths if `p_doc` is `nil` in the various `StartProcess` implementations.

**Comment by montegoulding** [comment]
Actually replacing `MCStringGetLength` with `MCStringIsEmpty` which handles `nil` will cover it

**Comment by livecodepanos** [comment]
@montegoulding Yes it crashes  at `__MCAssertIsString` in `MCStringGetLength`. Yes you are right, I'll update the PR shortly. Thanks :)

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 9266147

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 9266147a82c0d8d7f144098c88d01e3f7c82512d

**Comment by livecode-vulcan** [comment]
😎 test success 9266147a82c0d8d7f144098c88d01e3f7c82512d

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/97)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/89)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/89)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/89)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/89)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1611)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/138)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/138)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1641)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1634)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1631)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1667)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1608)

**Pull request merged**
