### PR TITLE
[Bug 17191] graph: Ensure that properties are persisted over save

### PR DESCRIPTION
**Pull request by peter-b**
Implement the missing `OnSave` and `OnLoad` handlers.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 29a4827

**Comment by livecodeali** [comment]
@peter-b sorry about that, clicked the wrong button.

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 29a4827541ac81e40fb6346fcb4f6119767cbc81

**Comment by livecode-vulcan** [comment]
😎 test success 29a4827541ac81e40fb6346fcb4f6119767cbc81
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2178)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2186)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2171)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2187)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2193)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2198)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2209)

**Pull request merged**
