### PR TITLE
[[Documentation]] minimize - title and zoombox

### PR DESCRIPTION
**Pull request by seaniepie**
There doesn't seem to be a title property. However, the zoomBox property does exist.

### CODE REVIEW

**Comment by livecodeali** [comment]
Comment [here](https://github.com/livecode/livecode/pull/4652) also applies

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 1790014

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 1790014f0d72a23c40811e723c927eb022c23d75

**Comment by livecode-vulcan** [comment]
😎 test success 1790014f0d72a23c40811e723c927eb022c23d75
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/426)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/431)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/426)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/426)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/432)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/426)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/426)

**Pull request merged**
