### PR TITLE
Don't use ATSUI fontname mapping in 64-bit mode

### PR DESCRIPTION
**Pull request by livecodefraser**
We may need a CoreText replacement for this - @runrevmark?

### CODE REVIEW

**Comment by peter-b** [comment]
This doesn't solve the problem of ATSUI fontname mapping being unavailable even in 32-bit mode with the MacOSX10.11 SDK.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1ed8eb7

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1ed8eb745b27414aeefe817a699f3b7c9f108940

**Comment by livecode-vulcan** [comment]
😎 test success 1ed8eb745b27414aeefe817a699f3b7c9f108940
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1367)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1378)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1363)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1373)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1384)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1383)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1388)

**Pull request merged**
