### PR TITLE
[Bug 19009 & 18982] New mergExt builds

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 4fb5710

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4fb571062baaa86edf3d6c3b7bf38abb052d75d0

**Comment by livecode-vulcan** [comment]
😎 test success 4fb571062baaa86edf3d6c3b7bf38abb052d75d0

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/753)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/758)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/751)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/752)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/758)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/750)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/750)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8c0ece3

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8c0ece35ddacc93e6bdcd23f4856e7980895bf79

**Comment by livecode-vulcan** [comment]
😎 test success 8c0ece35ddacc93e6bdcd23f4856e7980895bf79

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/759)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/764)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/757)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/758)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/764)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/756)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/756)

**Pull request merged**
