### PR TITLE
Fix object relayering

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodepanos** [comment]
I am closing this PR. We should probably fix temporarily the relayer issue by reverting the two original PRs and then revisit this issue in the future.

The PRs that have to be reverted are https://github.com/livecode/livecode/pull/5283 and https://github.com/livecode/livecode/pull/5026

**Comment by livecodepanos** [comment]
Thanks @livecodeali for helping on this

**Comment by livecodeali** [comment]
@livecode-vulcan review ok a7c780c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a7c780c772ca12aa6653d2fb012b43abd1f431fb

**Comment by livecode-vulcan** [comment]
😎 test success a7c780c772ca12aa6653d2fb012b43abd1f431fb

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1134)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1136)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1129)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1135)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1139)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1149)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1130)

**Pull request merged**
