### PR TITLE
Added support for building with Xcode11.3 / iOS13.2 SDK

### PR DESCRIPTION
**Pull request by livecodepanos**
WIP until the prebuilts for iOS 13.2 are ready

### CODE REVIEW

**Comment by livecodepanos** [comment]
Prebuilts are ready, removing WIP

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 05c6721

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 05c672106b7fe99391f4917a8afb9f8bb830fe6e

**Comment by livecode-vulcan** [comment]
😎 test success 05c672106b7fe99391f4917a8afb9f8bb830fe6e

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/699)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/108)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/108)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/108)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/108)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2225)
* try-community-universal-ios-iphoneos13.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.2/builds/0)
* try-community-universal-ios-iphonesimulator13.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.2/builds/0)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2254)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2241)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2240)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2274)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2214)

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 4d71e7e

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 4d71e7e1f26e104c22f329f6a1a9cca67622fa2c

**Comment by livecode-vulcan** [comment]
😎 test success 4d71e7e1f26e104c22f329f6a1a9cca67622fa2c

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/702)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/111)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/111)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/111)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/111)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2228)
* try-community-universal-ios-iphoneos13.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.2/builds/3)
* try-community-universal-ios-iphonesimulator13.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.2/builds/3)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2257)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2244)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2243)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2277)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2217)

**Pull request merged**
