### PR TITLE
[[ Bug 16009 ]] Menu arrays come from script, so default values must be strings

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 6587bf3

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6587bf3bae828b93980642e57a624247a45858ab

**Comment by livecode-vulcan** [comment]
😞 test failure 6587bf3bae828b93980642e57a624247a45858ab
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/470)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/473)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/469)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/469)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/477)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/470)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/479)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 6587bf3

**Comment by livecode-vulcan** [comment]
😎 test success 6587bf3bae828b93980642e57a624247a45858ab
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/477)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/480)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/476)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/476)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/484)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/477)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/486)

**Pull request merged**
