### PR TITLE
[[ Bug ]] Fix error numbers

### PR DESCRIPTION
**Pull request by montegoulding**
(cherry picked from commit 3d0c21c196dd728b87e35dd97c86dabef14b97de)

### CODE REVIEW

**Comment by runrevmark** [comment]
This looks fine, so reviewing - I'm assuming the travis failure is due to something other than this...

@livecode-vulcan review ok d6bb0b6

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d6bb0b6d95e83459da1b07702ad6be0c3d201fc0

**Comment by livecode-vulcan** [comment]
😎 test success d6bb0b6d95e83459da1b07702ad6be0c3d201fc0

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/432)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/440)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/419)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/362)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/362)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/427)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/432)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/430)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/437)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/430)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/437)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/456)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/426)

**Comment by montegoulding** [comment]
Actually it was this because there is a test against `EE_SNAPSHOT_FAILED`

**Comment by montegoulding** [comment]
oh, sorry you mean the travis error on this... restarting travis but the parser test runner does use the build error map function so I'll investigate if I broke that.

**Comment by montegoulding** [comment]
@runrevmark that should sort the parser test runner issue

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 99dd77b

**Comment by montegoulding** [comment]
The parserrors issue will need to be fixed on develop-8.1 too. Will do that in a sec.

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 99dd77b0140b2a2b64dc5d0b62099dc6462413c4

**Comment by livecode-vulcan** [comment]
😎 test success 99dd77b0140b2a2b64dc5d0b62099dc6462413c4

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/439)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/447)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/426)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/369)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/369)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/434)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/439)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/437)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/446)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/437)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/446)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/464)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/433)

**Pull request merged**
