### PR TITLE
Merge develop-7.0 into develop

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 2e05278

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 2e052784c7608e487e29791028367abe7cea9816

**Comment by peter-b** [comment]
@livecodeali I've tweaked the merge commit to catch the missed rename of `control.h` -> `mccontrol.h`

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 62b9f32b892864e8dd23a6250301ac83e8046c24

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 62b9f32b892864e8dd23a6250301ac83e8046c24

**Comment by livecode-vulcan** [comment]
😎 test success 62b9f32b892864e8dd23a6250301ac83e8046c24
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/764)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/824)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/714)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/778)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/709)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/701)

**Pull request merged**
