### PR TITLE
Gyp android toolchain tweaks

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review okay b0aac6b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b0aac6b7113200a58b917109ed42f025ea836e36

**Comment by livecode-vulcan** [comment]
😞 test failure b0aac6b7113200a58b917109ed42f025ea836e36
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/273)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/336)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/219)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/284)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/219)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/211)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 59d40ec

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 59d40ec05a774f96b639fd2ceb35b17f400c0fbb

**Comment by livecode-vulcan** [comment]
😎 test success 59d40ec05a774f96b639fd2ceb35b17f400c0fbb
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/277)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/340)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/223)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/288)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/223)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/215)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 601b301

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 601b301ecddd1befa67b0c862eeda88cd1052909

**Comment by livecode-vulcan** [comment]
😞 test failure 601b301ecddd1befa67b0c862eeda88cd1052909
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/283)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/346)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/229)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/294)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/229)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/221)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 601b301

**Comment by livecode-vulcan** [comment]
😞 test failure 601b301ecddd1befa67b0c862eeda88cd1052909
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/288)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/351)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/234)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/299)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/234)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/226)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay a09f5e3

I wonder if Vulcan will let me review my own PR... just doing this to trigger a re-try after fixing a couple of silly typos!

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok a09f5e390b6a3645ea54f4aa4515e24cfad3fc9c

**Comment by peter-b** [comment]
@livecode-vulcan review okay a09f5e3

Just to make it official. ;-)

**Comment by livecode-vulcan** [comment]
😎 test success a09f5e390b6a3645ea54f4aa4515e24cfad3fc9c
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/296)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/358)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/240)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/307)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/242)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/232)

**Pull request merged**
