### PR TITLE
[[ Mac64 ]] Enable 64-bit building in 'Debug' and 'Fast' configurations

### PR DESCRIPTION
**Pull request by livecodefraser**
This, obviously, won't build until all of the other 64-bit building PRs have been merged in.

'Release' mode is not included yet as there is still a lot of work to do with installers, the standalone-builder, etc and we don't want to ship a semi-working binary!

### CODE REVIEW

**Comment by peter-b** [comment]
I'm aware that at this point the Vulcan build will fail because the other PRs haven't been merged in, but this patch is super obviously correct. :wink: 

@livecode-vulcan review ok 851f0bf

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 851f0bfe0c16e08536bc2960858917a29e5d72a5

**Comment by livecode-vulcan** [comment]
😞 test failure 851f0bfe0c16e08536bc2960858917a29e5d72a5
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1006)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1014)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1003)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1006)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1017)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1024)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1021)

**Comment by peter-b** [comment]
@livecode-vulcan retry 851f0bf

**Comment by livecode-vulcan** [comment]
😞 test failure 851f0bfe0c16e08536bc2960858917a29e5d72a5
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1376)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1387)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1372)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1382)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1393)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1392)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1397)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 869670e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 869670ec4bc08f4f20fbea2329882393668e3b5a

**Comment by livecode-vulcan** [comment]
😞 test failure 869670ec4bc08f4f20fbea2329882393668e3b5a
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1378)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1389)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1374)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1384)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1395)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1394)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1399)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 6af6034

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 6af6034622dcb378c295d8269c4dc29ec9ec4c7e

**Comment by livecode-vulcan** [comment]
😞 test failure 6af6034622dcb378c295d8269c4dc29ec9ec4c7e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1384)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1404)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1380)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1390)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1401)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1400)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1405)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 6af6034

After spending all day getting this building under Xcode 7.1, this was just cruel and unusual.

**Comment by livecode-vulcan** [comment]
😎 test success 6af6034622dcb378c295d8269c4dc29ec9ec4c7e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1386)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1406)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1382)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1392)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1403)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1402)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1407)

**Pull request merged**
