### PR TITLE
Coverity defects fixes

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok b0868e5

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b0868e536a7f5f447846597c4424a483e3835ee3

**Comment by livecode-vulcan** [comment]
😝 test failure b0868e536a7f5f447846597c4424a483e3835ee3

* try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/125)
* try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/190)
* try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/78)
* try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/135)
* try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/71)
* try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/76)

**Comment by livecode-vulcan** [comment]
😝 test failure b0868e536a7f5f447846597c4424a483e3835ee3
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/125)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/190)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/78)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/135)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/71)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/76)

**Pull request merged**
