### PR TITLE
Conditionally remove -Werror=uninitialised for android builds on mac

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@montegoulding Is it not feasible to fix the errors?

**Comment by runrevmark** [comment]
@peter-b: I'm sure it is - perhaps put it on the backlog as one of the 'cleaning up' tasks - just make it higher priority than others to remove the corner-case.

**Comment by montegoulding** [comment]
it seems the errors are in the code generated by gentle:

```
       = NULL
../../toolchain/gentle/gentle/cyfront.c:9564:11: error: variable 'yyb' is uninitialized when used here [-Werror,-Wuninitialized]
yy yysb = yyb;
          ^~~
../../toolchain/gentle/gentle/cyfront.c:9468:7: note: initialize the variable 'yyb' to silence this warning
yy yyb;
      ^
       = NULL
../../toolchain/gentle/gentle/cyfront.c:10483:11: error: variable 'yyb' is uninitialized when used here [-Werror,-Wuninitialized]
yy yysb = yyb;
          ^~~
../../toolchain/gentle/gentle/cyfront.c:10408:7: note: initialize the variable 'yyb' to silence this warning
yy yyb;
      ^
       = NULL
fatal error: too many errors emitted, stopping now [-ferror-limit=]

```

**Comment by montegoulding** [comment]
Would gentle be generating different code on mac than linux?

**Comment by runrevmark** [comment]
Ah! That's right - I'd forgotten it was gentle causing the friction - so the patch should only really be applied to files that gentle generates.

The reason it happens on Mac and not on other platforms is that the tools containing gentle generated files are host tools, so use the host compiler toolchain; but with the settings from the target platform (or something - I remember chatting to @livecodefraser about it some time ago).

So, the patch is required, but should be limited to the C source files which gentle generates (which I'm sure should be possible, but my gyp-fu is not sufficient to suggest how!).

**Comment by peter-b** [comment]
@montegoulding What version of bison do you have on your Mac?

**Comment by runrevmark** [comment]
Okay - so this is a bit more complicated - there are conditionals for whether the toolchain is host or not (which changes which gyp settings get used it seems) _and_ mac only enables the -Werror stuff in Debug mode (although I'm not clear the mac settings are used on mac when building the host tools for android, which are obviously compiled for mac).

**Comment by runrevmark** [comment]
@peter-b: The errors there are in cyfront.c which is the main gentle source file - it isn't generated using bison, it is 'as it is'.

**Comment by montegoulding** [comment]
I tried moving it to toolchain.gyp and that doesn't work. I have bison 2.3 if that helps.

**Comment by runrevmark** [comment]
Basically gentle generated source files (of which cyfront.c is one) are not generated to a C standard where these warnings can be actioned. Remember that such warning analyses are conservative in many compilers and produce false-positives. Thus, we just need to ensure the -Werror=uinitialized flag is turned off when compiling _those_ C source files.

This might be a job for gyp-master @livecodefraser when he returns ;)

**Comment by montegoulding** [comment]
OK, is it unreasonable to suggest that we include this patch then put it on the backlog to fix it in a better way?

**Comment by peter-b** [comment]
@runrevmark I know that GCC tries very hard to make sure that `-Wuninitialized` detection has as few false positives as possible (that's why there's a separate `-Wmaybe-uninitialized` category).  It looks suspiciously like this warning is valid: a `yysb` _is_ initialised with an uninitialised value of `yyb`.  However, the only thing that happens with `yysb` is to assign it back to `yyb`, so I would describe this as a false false negative.

@montegoulding I'll have a brief look into this and see if I can figure out what's going wrong.

**Comment by peter-b** [comment]
@montegoulding Something screwy is going on, because warnings are supposed to be turned off entirely when compiling gentle (see line 19 of `toolchain/gentle/gentle/gentle.gyp`)

**Comment by montegoulding** [comment]
@peter-b it isn't conditionally included on silence warnings it is in the debug and fast config of Linux settings.. Perhaps the solution is to move it to the target conditions and then conditionally remove from release if necessary?

**Comment by peter-b** [comment]
@montegoulding Good spot.  It should be an error in release mode and I'm not sure why it's not.  give me a sec and I'll submit a PR to move it.

**Comment by peter-b** [comment]
@montegoulding I've looked into this a bit more.  It looks like GCC is _correctly_ picking up a lot of uninitialised variable errors in release mode -- the higher levels of optimisation help with this.  One of the main problems is that GCC is detecting that failure to allocate memory is leaving pointers uninitialised, which is obviously a **very bad thing**, but in a lot of cases these are in places where we can't actually do anything about it without a massive refactor.  I'll try to fix and/or workaround as much as possible.

**Comment by peter-b** [comment]
@montegoulding I think #4282 might fix your issue.

**Comment by montegoulding** [comment]
@peter-b closing and we can pursue the right incantation in your PR

**Pull request closed without merging**
