### PR TITLE
[Bug 15934] Make sure pressing Backspace key works as expected, even if Shift key is down

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
@livecodepanos I think that the right approach here is to add a new entry in `s_mac_keybindings` for `XK_BackSpace` and `MK_SHIFT`

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok  538ed45

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 538ed45bfb93aba62e9813e534f47821559c62cd

**Comment by livecode-vulcan** [comment]
😎 test success 538ed45bfb93aba62e9813e534f47821559c62cd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/384)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/384)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/383)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/382)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/387)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/379)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/390)

**Pull request merged**
