### PR TITLE
[[ Bug ]] Use target rather than action and correct button name

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 1a047c7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 1a047c75abccb807a2b5b4a71192697751d15a85

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay e440b4e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok e440b4ec7e3cd28361afae00426fff21950a8af5

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 71b2d13

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 71b2d1376a633d858046dae3e1bf8a6c78c65907

**Comment by livecode-vulcan** [comment]
😎 test success 71b2d1376a633d858046dae3e1bf8a6c78c65907
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2693)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2703)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2688)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2704)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2710)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2716)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2728)

**Pull request merged**
