### PR TITLE
[[ Bug ]] Fixes for issues found via valgrind (8.0)

### PR DESCRIPTION
**Pull request by runrevmark**
Various memory leak fixes found as a result of valgrinding.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok a52bd28

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a52bd2802a4051efddbe2eba205b193b33f9c055

**Comment by runrevmark** [comment]
I think this PR can be closed when the 'merge-7.0.6-rc-1' branch is merged as that should contain all these changes already.

**Comment by peter-b** [comment]
@runrevmark Since that branch has now been merged (#2334) I'm closing this pull request.

**Pull request closed without merging**
