### PR TITLE
[Dictionary] "implicit focus" to "is in"

### PR DESCRIPTION
**Pull request by livecodealice**
glossary/i/implicit-focus.lcdoc - Fixed broken link
keyword/in.lcdoc - Fixed broken link
property/ink.lcdoc - Spelling error
property/innershadow.lcdoc - Reformatted property list
keyword/int1.lcdoc - Fixed broken links
keyword/int2.lcdoc - Fixed broken links
keyword/int4.lcdoc - Fixed broken links
function/interrupt.lcdoc - Fixed broken link
function/intersect.lcdoc - Removed double double quotes, changed reference to control (object) to control (glossary)
command/iphoneClearTouches.lcdoc - Made code example display correctly.
operator/is-among-the-keys-of.lcdoc - Changed capitalisation of name in description to display correctly.
operator/is-in.lcdoc - Edited formatting of explanation that “a is in b” and “b contains a” are equivalent.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodesam I changed this to be targeted at develop-9.0 and it has acquired a conflict!

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 0a5b7f5

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 0a5b7f582ed3980b9b68b4511612fae02a257b9a

**Comment by livecode-vulcan** [comment]
😎 test success 0a5b7f582ed3980b9b68b4511612fae02a257b9a

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1434)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1450)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1424)
* try-community-universal-ios-iphoneos11.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.3/builds/27)
* try-community-universal-ios-iphonesimulator11.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.3/builds/27)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1428)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1454)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1434)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1448)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1433)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1443)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1483)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1423)

**Pull request merged**
