### PR TITLE
Enable 64-bit OSX builds in Release mode

### PR DESCRIPTION
**Pull request by livecodefraser**
Does what it says on the tin... without it https://github.com/livecode/livecode-ide/pull/810 just gives false hope.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok dce6da0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok dce6da04d932ac3947d10d1cb2a8515df67a2fcb

**Comment by livecode-vulcan** [comment]
😎 test success dce6da04d932ac3947d10d1cb2a8515df67a2fcb
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1745)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1760)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1740)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1751)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1761)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1764)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1769)

**Comment by peter-b** [comment]
@livecodefraser I'm removing <kbd>need-docs</kbd> - but I've given you [bug 16809](http://quality.livecode.com/show_bug.cgi?id=16809) in return, you lucky thing.  I'm also removing <kbd>need-release-notes</kbd> and I'll put together some suitable release notes in a separate PR.

**Comment by peter-b** [comment]
I've added the release notes in #3576.

**Pull request merged**
