### PR TITLE
[[ Bug 18778 ]] Send standalone messages at correct time

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 2e32142

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2e321428087a337fe874dfe8a2710f8ce8bd21ab

**Comment by livecode-vulcan** [comment]
😎 test success 2e321428087a337fe874dfe8a2710f8ce8bd21ab
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/596)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/601)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/596)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/600)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/605)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/597)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/597)

**Comment by livecodeali** [comment]
We probably need to hold off on merging this until the conflict with http://quality.livecode.com/show_bug.cgi?id=18364 is resolved.

**Comment by livecodeali** [comment]
@peter-b I have reworked this to restore the original `savingStandalone` and `standaloneSaved` behavior.

**Comment by peter-b** [comment]
@livecodeali I don't suppose there's any practicable way to add tests for this, is there?

@livecode-vulcan review ok 1ae387b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1ae387ba198ab4594b4ddd15dd0e3ac1d77a8ce7

**Comment by livecode-vulcan** [comment]
😎 test success 1ae387ba198ab4594b4ddd15dd0e3ac1d77a8ce7

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/758)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/763)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/756)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/757)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/763)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/755)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/755)

**Comment by livecodeali** [comment]
@peter-b Yes! https://github.com/livecode/livecode-ide/pull/1476

**Comment by peter-b** [comment]
@livecodeali I keep forgetting that the tests are currently in a different repository to the code!

**Pull request merged**
