### PR TITLE
[[ Bug 20478 ]] Fix crash on exit after using the commandName

### PR DESCRIPTION
**Pull request by livecodeali**
- Fix the missing retain when fetching the commandName
- Fix a memory leak in the MCCommandArguments class
- Refactor the MCCommandArguments and MCCommandName classes so that
  their functionality is implemented in the engine module
- Add test for crash

### CODE REVIEW

**Comment by livecodeali** [comment]
I just realised this makes a negative command argument index an error... hmm

**Comment by livecodeali** [comment]
OK given the docs say that the index is a positive integer I think it makes sense to throw that error - I'd be very surprised if anyone is relying on `commandArguments(-1)` returning empty - but can revert that part if necessary

**Comment by runrevmark** [comment]
@livecodeali Does commandArguments(0) return something sensible? Is it the argv[0] entry (i.e. the executable name/path rather than an argument)? Given that is available as commandName (I believe) we should probably make 0 an error too (athough I think it will currently always return empty, so not a big thing).

This then gives us:
```
   commandArguments(n) <=> element n of the commandArguments
```
Which validates -1 as being an error at the moment as it would (in the above equivalent) give the last element of the arguments list.

**Comment by livecodeali** [comment]
@runrevmark Yes, `commandArguments(0)` is `empty` - I will make it an error and add a test

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 28b08a6

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 28b08a695ca6fd709b24b57602da81b0c648d9e5

**Comment by livecode-vulcan** [comment]
😎 test success 28b08a695ca6fd709b24b57602da81b0c648d9e5

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/919)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/935)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/909)
* try-community-universal-ios-iphoneos11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.0/builds/84)
* try-community-universal-ios-iphonesimulator11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.0/builds/85)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/913)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/935)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/919)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/935)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/918)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/928)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/950)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/914)

**Pull request merged**
