### PR TITLE
Remove unused variable MCpattern

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok f85bc89

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f85bc892b0b31dbea5a8cb61ea35aecba220ad7d

**Comment by livecode-vulcan** [comment]
😞 test failure f85bc892b0b31dbea5a8cb61ea35aecba220ad7d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2543)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2553)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2538)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2554)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2560)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2564)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2576)

**Comment by montegoulding** [comment]
Cannot open include file: 'unicode/uloc.h'

**Comment by livecodeali** [comment]
@livecode-vulcan retry f85bc89

**Comment by livecode-vulcan** [comment]
😎 test success f85bc892b0b31dbea5a8cb61ea35aecba220ad7d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2546)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2556)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2541)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2557)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2563)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2567)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2579)

**Pull request merged**
