### PR TITLE
[[ Bug 13636 ]] Implement screen snapshot on Android

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian Looks nice!

@livecode-vulcan review ok 6a2b30c

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6a2b30cd9d341683f0c6577e25c138d528eb4818

**Comment by peter-b** [comment]
Oh -- it looks like maybe you meant to submit this as a PR against develop-7.0, not against develop?

@livecode-vulcan review not ok 6a2b30c

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 6a2b30cd9d341683f0c6577e25c138d528eb4818

**Comment by livecodeian** [comment]
Oops!

**Pull request closed without merging**
