### PR TITLE
[[ Bug 15245 ]] Make sure we convert text to native before emitting i…

### PR DESCRIPTION
**Pull request by runrevmark**
…nto PostScript.

### CODE REVIEW

**Comment by peter-b** [comment]
If we used Cairo for generating PostScript on Linux, then this wouldn't be necessary; Cairo handles Unicode text properly.

**Comment by runrevmark** [comment]
Indeed - and if we had ...list arbitrary things that would take significant work... then lots of other things would also be true ;)

For now this at least gives an element of text printing back to Linux especially for apps which currently do not need unicode, but do need to run on 7 :)

**Comment by runrevmark** [comment]
I should point out that revpdfprinter _does_ use cairo. So the next step is to require that to be included for Linux printing and use that instead of MCPSPrinter. We can't use stock cairo for PDF printing as it @livecodeian patched it to support various things its PDF output doesn't (or didn't at the time). There's other options here as well.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 9278da2

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 9278da206c9492e6185a38bf4b2a7f687a5128a9

**Comment by livecode-vulcan** [comment]
😎 test success 9278da206c9492e6185a38bf4b2a7f687a5128a9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/443)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/443)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/442)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/441)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/447)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/438)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/449)

**Pull request merged**
