### PR TITLE
Emscripten standalone builder

### PR DESCRIPTION
**Pull request by livecodefraser**
Corresponding IDE PR: https://github.com/runrev/livecode-ide/pull/432

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review not ok df1bd6a

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok df1bd6ad33f84c016b27c6ff2ea948bbf94690d0

**Comment by peter-b** [comment]
@livecode-vulcan review ok fa7d9b0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok fa7d9b0c872c00efec1ef722c2c662d06f92ed5c

**Comment by livecode-vulcan** [comment]
😎 test success fa7d9b0c872c00efec1ef722c2c662d06f92ed5c
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/137)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/135)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/135)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/135)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/138)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/135)

**Pull request merged**
