### PR TITLE
[[ Bug 15628 ]] Fix typo in lcb repeat syntax docs

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok daf87d9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok daf87d9019498f82df33c0c830bf1cf81d2d928f

**Comment by livecode-vulcan** [comment]
😞 test failure daf87d9019498f82df33c0c830bf1cf81d2d928f
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/594)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/654)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/543)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/607)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/539)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/532)

**Comment by livecodeali** [comment]
@livecode-vulcan retry daf87d9

**Comment by livecode-vulcan** [comment]
😎 test success daf87d9019498f82df33c0c830bf1cf81d2d928f
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/600)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/660)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/549)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/613)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/545)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/538)

**Pull request merged**
