### PR TITLE
[[ Community Docs ]] URL Keyword enhancements

### PR DESCRIPTION
**Pull request by asayd**
- Added references;
- Added links;
- Fixed typos.

### CODE REVIEW

**Comment by asayd** [comment]
@livecodeali Here is the comment that I had put in the wrong place on the previous PR:
Corrected the things you pointed out. Concur with your suggestion re file(glossary) vs file(keyword).  Sorted References alphabetically for better sorting in LC dictionary. Tell me if this is a bad idea.

**Comment by livecodeali** [comment]
@asayd Grand, thanks for that!
@livecode-vulcan review ok e7069cc

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok e7069cc2d867c0e1f3277605f63af63d37dff5b3

**Comment by livecode-vulcan** [comment]
😎 test success e7069cc2d867c0e1f3277605f63af63d37dff5b3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2413)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2423)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2406)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2424)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2430)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2434)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2446)

**Pull request merged**
