### PR TITLE
[[ Bug 16284 ]] Fix warning filtering when linking with Xcode for iOS

### PR DESCRIPTION
**Pull request by livecodesebastien**
(cherry picked from commit cda73ec0c1debdfd166774c2ef866b1d1bffab5f)

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Self-review as the commit has been cherry-picked from develop-6.7 (and was already reviewed in https://github.com/livecode/livecode/pull/3134)
@livecode-vulcan review ok      2e55f3e

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok 2e55f3e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 2e55f3ea2a039e1c2b93953d5a09b51b80688744

**Comment by livecode-vulcan** [comment]
😎 test success 2e55f3ea2a039e1c2b93953d5a09b51b80688744
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1044)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1053)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1041)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1046)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1056)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1062)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1061)

**Pull request merged**
