### PR TITLE
[Bug 18774] Fix syntax errors in "write to file" docs

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodeali** [comment]
Some of these were fixed in develop [here](https://github.com/livecode/livecode/commit/53004c5ada7d4cffe382cbdc2ce64f64a18622bc)...

**Comment by peter-b** [comment]
@livecodeali I've rebased this on `develop` and fixed the merge conflicts.

**Comment by livecodeali** [comment]
@peter-b ta!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 33cd298

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 33cd298876d5d58feb64b5c401bec2c8ca57d173

**Comment by livecode-vulcan** [comment]
😎 test success 33cd298876d5d58feb64b5c401bec2c8ca57d173
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/615)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/620)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/615)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/619)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/624)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/616)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/616)

**Pull request merged**
