### PR TITLE
[[ SB Testing ]] Enable standalone building in IDE tests

### PR DESCRIPTION
**Pull request by livecodeali**
This change is [Reviewable](https://reviewable.io/reviews/livecode/livecode/4079)

### CODE REVIEW

**Comment by peter-b** [comment]
This looks okay to me, with a single minor suggestion.

@livecode-vulcan review ok 79f3cc4

<details><summary>

<i>Previously, livecodeali (Ali Lloyd) wrote…</i></summary>



> #### [[ SB Testing ]] Enable standalone building in IDE tests
> 
> </details>

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 2 of 2 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[ide-support/revsaveasstandalone.livecodescript, line 274 [r3]](https://reviewable.io:443/reviews/livecode/livecode/4079#-KJjH8lnu3CfBTIQG2pt:-KJjH8loOejtv7HkbO-J:-794728368) ([raw file](https://github.com/livecode/livecode/blob/6415dd58651649f96c1d784ab6988c5973c4bc11/ide-support/revsaveasstandalone.livecodescript#L274)):_

> ```
>          return tError
>       else
>          answer error tMessage
> ```

The `if revSBSuppressDialogs() then return else answer` pattern is quite common.  Would it help to add a handler to reduce that to `return revSBMagicDialogHandler(message)`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4079#-:-KJjLpI-fDmH0XsmZZnQ:-612498702)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 79f3cc4f36c13cd7cae6911617d71b55c81b2d3e

**Comment by livecode-vulcan** [comment]
😎 test success 79f3cc4f36c13cd7cae6911617d71b55c81b2d3e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2609)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2619)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2604)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2620)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2626)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2632)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2644)

**Comment by livecodeali** [comment]
_[ide-support/revsaveasstandalone.livecodescript, line 274 [r3]](https://reviewable.io:443/reviews/livecode/livecode/4079#-KJjH8lnu3CfBTIQG2pt:-KJjXvQk8G2_mrHrW_33:1386605406) ([raw file](https://github.com/livecode/livecode/blob/6415dd58651649f96c1d784ab6988c5973c4bc11/ide-support/revsaveasstandalone.livecodescript#L274)):_
<details><summary>

<i>Previously, peter-b (Peter TB Brett) wrote…</i></summary>



> The `if revSBSuppressDialogs() then return else answer` pattern is quite common.  Would it help to add a handler to reduce that to `return revSBMagicDialogHandler(message)`?
> </details>
> I'm not sure because the later one does `exit to top` afterwards instead of `return`...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode/4079)_

**Pull request merged**
