### PR TITLE
[[Documentation]] Changes to unlock-screen.lcdoc

### PR DESCRIPTION
**Pull request by asayd**
* Corrected formatting errors in syntax.
* Adding references.
* Improved examples.
* Clarified Descriptions of params.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 9cc65ca

**Comment by peter-b** [comment]
@asayd Thank you very much for all your hard work on the documentation updates!

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9cc65ca77e03ff883637aed4f6bf2a73d283f363

**Comment by livecode-vulcan** [comment]
😎 test success 9cc65ca77e03ff883637aed4f6bf2a73d283f363

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/645)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/650)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/645)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/649)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/654)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/646)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/646)

**Pull request merged**
