### PR TITLE
[[ Tests ]] Add new tests in the test module

### PR DESCRIPTION
**Pull request by livecodesebastien**
This is part of the process to import in the test module the tests from ARTS.

Import of the input files and library used by ARTS (`_inputlib.livecodescript` and files in `tests/lcs/inputFiles`)

Rename and improve tests for:
- `tests/lcs/core/engine.livecodescript`
- `tests/lcs/core/files/files.livecodescript`
- `tests/lcs/core/interface/interface.livecodescript`

Adds tests for:
- `specialFolderPath`
- `intersect`
- `union`
- `combine`

Update doc for:
- `specialFolderPath`: remove Mac special folders that are no longer supported.
- `processor`: remove `Motorola` and add `x86_64` (see https://gist.github.com/livecodesebastien/eee223c9e54ce164f25b for diff)

### CODE REVIEW

**Comment by livecodeali** [comment]
_[engine/src/uidc.cpp, line 1557 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3342#-K43Rwfb_qOlDJcAWbEi:-K43Rwfb_qOlDJcAWbEj:-314303227) ([raw file](https://github.com/livecode/livecode/blob/086ca7fd0abaeeb8dc9449de1cfba7b2428675e8/engine/src/uidc.cpp#L1557)):_
You still need to MCU_lower this otherwise the char checks below will fail for uppercase chars

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3342)_

**Comment by livecodeali** [comment]
_[tests/lcs/core/array/arrayop.livecodescript, line 170 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3342#-K43U0M2-lwa26l47mdX:-K43U0M2-lwa26l47mdY:-2002434899) ([raw file](https://github.com/livecode/livecode/blob/086ca7fd0abaeeb8dc9449de1cfba7b2428675e8/tests/lcs/core/array/arrayop.livecodescript#L170)):_
Recursive

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3342)_

**Comment by livecodeali** [comment]
_[tests/lcs/core/array/arrayop.livecodescript, line 285 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3342#-K43UGwDDpxfDhCgnfAE:-K43UGwDDpxfDhCgnfAF:-303401193) ([raw file](https://github.com/livecode/livecode/blob/086ca7fd0abaeeb8dc9449de1cfba7b2428675e8/tests/lcs/core/array/arrayop.livecodescript#L285)):_
recursive here too

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3342)_

**Comment by livecodeali** [comment]
_[tests/lcs/core/array/arrayop.livecodescript, line 1 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3342#-K43UQQz66mq64Ka143C:-K43UQQz66mq64Ka143D:-1200785630) ([raw file](https://github.com/livecode/livecode/blob/086ca7fd0abaeeb8dc9449de1cfba7b2428675e8/tests/lcs/core/array/arrayop.livecodescript#L1)):_
I've already added some tests for array union and intersect, although this one does it with data defined from files, so I guess it's slightly different. Anyway, I wonder if they are both necessary - maybe they could be combined.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3342)_

**Comment by livecodeali** [comment]
_[tests/lcs/core/engine/engine.livecodescript, line 82 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3342#-K43V0P58QrjZzA0VCvY:-K43V0P58QrjZzA0VCvZ:75340699) ([raw file](https://github.com/livecode/livecode/blob/086ca7fd0abaeeb8dc9449de1cfba7b2428675e8/tests/lcs/core/engine/engine.livecodescript#L82)):_
The functionName here should be plural

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3342)_

**Comment by livecodeali** [comment]
_[tests/lcs/core/engine/object.livecodescript, line 19 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3342#-K43VJ-mbw-WKy5LTWrc:-K43VJ-mbw-WKy5LTWrd:46541421) ([raw file](https://github.com/livecode/livecode/blob/086ca7fd0abaeeb8dc9449de1cfba7b2428675e8/tests/lcs/core/engine/object.livecodescript#L19)):_
I guess these must parse correctly without the space between the object type and "test", but probably best to add the space!

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3342)_

**Comment by livecodeali** [comment]
Reviewed 23 of 24 files at r1.
Review status: 23 of 24 files reviewed at latest revision, 7 unresolved discussions.

---

_[tests/lcs/core/array/arrayop.livecodescript, line 301 [r1]](https://reviewable.io:443/reviews/livecode/livecode/3342#-K43ULgFQuF6vmWYbOo7:-K43ULgFQuF6vmWYbOo8:-414951019) ([raw file](https://github.com/livecode/livecode/blob/086ca7fd0abaeeb8dc9449de1cfba7b2428675e8/tests/lcs/core/array/arrayop.livecodescript#L301)):_
I've alrea

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3342)_

**Comment by livecodeali** [comment]
Reviewed 1 of 24 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3342)_

**Comment by runrevmark** [comment]
The two engine fixes here should really be submitted as separate PRs I think...

**Comment by livecodesebastien** [comment]
I'll make the pull requests (they will need to be merged in first to let some of this PR new tests pass).

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 988f799

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 988f799666ddf024d09d64bd613888efc3c0ad4b

**Comment by livecode-vulcan** [comment]
😎 test success 988f799666ddf024d09d64bd613888efc3c0ad4b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1316)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1327)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1312)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1322)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1333)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1332)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1337)

**Comment by peter-b** [comment]
Review status: 15 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

_[tests/lcs/core/files/files.livecodescript, line 193 [r3]](https://reviewable.io:443/reviews/livecode/livecode/3342#-K47Q5oxBA1zHXfpfMuQ:-K47Q5oxBA1zHXfpfMuR:1748350986) ([raw file](https://github.com/livecode/livecode/blob/ed046c5eaeede7c57061d1260c95a721566c0cc1/tests/lcs/core/files/files.livecodescript#L193)):_
This should be:

```
TestSkip "specialFolderPath(desktop) is not empty"
```

so that it's clear from the logs which test is being skipped.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3342)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok c1ffb48

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c1ffb48334d86fde665545ea02808f50b2eba9a5

**Comment by livecode-vulcan** [comment]
😎 test success c1ffb48334d86fde665545ea02808f50b2eba9a5
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1319)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1330)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1315)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1325)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1336)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1335)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1340)

**Pull request merged**
