### PR TITLE
[Bug 17122] Allow setting textDirection of a fld to empty

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodepanos Please fix this by updating the documentation to say that the possible values are "auto", "rtl" and "ltr", rather than empty, "rtl" and "ltr".  We need to keep empty as meaning that the value should be inherited.

@livecode-vulcan review not ok c812fc7

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok c812fc7212482ba089da772f834940cc69567a7d

**Comment by peter-b** [comment]
@livecode-vulcan review ok 55a9bc8

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 55a9bc8d68a1c8cbbabcdc7f5ae21a89559a55b1

**Comment by livecode-vulcan** [comment]
😎 test success 55a9bc8d68a1c8cbbabcdc7f5ae21a89559a55b1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2111)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2120)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2104)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2119)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2126)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2132)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2140)

**Pull request merged**
