### PR TITLE
[Bug 13129] Remove revFont in favour of the commands added in 6.5

### PR DESCRIPTION
**Pull request by livecodefraser**
The replacement in-engine commands do everything revFont does and more.

### CODE REVIEW

**Comment by livecodefraser** [comment]
Marking this WIP as the S/B will need to be changed to reflect the removal.

**Comment by peter-b** [comment]
@livecodefraser We probably ought to include a compatibility script-only library that provides the removed commands as wrappers around the engine capabilities.

**Comment by runrevmark** [comment]
We could just add revFontLoad/Unload to revcommon (I think that's the library included in all standalones).

**Comment by peter-b** [comment]
@runrevmark Putting it in a separate inclusion allows people who don't need it (i.e. almost everyone) to leave it out.

**Comment by montegoulding** [comment]
@peter-b if we put it in a separate inclusion the user won't know they need to include it unless they know about revFont disappearing. If they do then they can update their code...

I'd vote for just removing the external. The release note covers the situation as far as I can see.

**Comment by peter-b** [comment]
@montegoulding I agree.

@livecode-vulcan review ok ff83489

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ff834894b459b943e3e2d1284830899e1c2c1a4f

**Comment by livecode-vulcan** [comment]
😎 test success ff834894b459b943e3e2d1284830899e1c2c1a4f

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/942)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/948)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/940)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/941)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/948)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/940)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/939)

**Pull request merged**
