### PR TITLE
Canvas effect updates

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @runrevian, could you please add a release note for these improvements?

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevian, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodeian** [comment]
@peter-b Is there anything else other than the simplified effect command that you think needs written up for a release note?

**Comment by livecodeali** [comment]
Just a sentence or two to go under the LiveCode Builder Language section in the release notes I think (eg the one here https://github.com/runrev/livecode/commit/943f6f180ec0b42fb5d77a8e933242a4a415f0c8)

**Comment by livecodeali** [comment]
Actually maybe that should be LiveCode Builder Host Library

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 9c3fe68

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 9c3fe68704d14cdfa6d0a5317158d5679bd4e978

**Comment by livecode-vulcan** [comment]
😎 test success 9c3fe68704d14cdfa6d0a5317158d5679bd4e978
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/321)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/321)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/320)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/319)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/324)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/316)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/327)

**Pull request merged**
