### PR TITLE
[[ NO MERGE ]] Bugfix 19213 check

### PR DESCRIPTION
**Pull request by runrevmark**
Check to see how far this builds on current windows builders.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 49bc20d

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 49bc20df913768983d3893968209622c72fcf008

**Comment by livecode-vulcan** [comment]
😞 test failure 49bc20df913768983d3893968209622c72fcf008

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/984)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/990)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/982)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/983)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/990)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1004)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/981)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 3346644

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 334664469d8adc71ce0a7cfe55d2e9aba5589ee1

**Comment by livecode-vulcan** [comment]
😞 test failure 334664469d8adc71ce0a7cfe55d2e9aba5589ee1

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/985)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/991)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/983)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/984)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/991)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1005)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/982)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 87fdc8d

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 87fdc8dff8827421d5c6b651e2ce702d027068b3

**Comment by livecode-vulcan** [comment]
😞 test failure 87fdc8dff8827421d5c6b651e2ce702d027068b3

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/986)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/992)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/984)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/985)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/992)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1006)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/983)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 59bd838

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 59bd8388f3afbd57c171c16532da8964ce5b3a12

**Comment by livecode-vulcan** [comment]
😞 test failure 59bd8388f3afbd57c171c16532da8964ce5b3a12

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/987)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/993)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/985)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/986)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/993)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1007)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/984)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 592e3a0

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 592e3a0e16aac662ed77823e105e3f47cbb1fcf1

**Comment by livecode-vulcan** [comment]
😞 test failure 592e3a0e16aac662ed77823e105e3f47cbb1fcf1

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/988)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/994)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/986)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/987)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/994)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1008)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/985)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 81ef91f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 81ef91fc4efd22171dfcdd01148f13895e0e2da8

**Comment by livecode-vulcan** [comment]
😎 test success 81ef91fc4efd22171dfcdd01148f13895e0e2da8

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/989)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/995)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/987)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/988)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/995)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1009)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/986)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 6d87d70

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 6d87d702e7ce3c27ea92396a3cc70a934258d8f6

**Comment by livecode-vulcan** [comment]
😞 test failure 6d87d702e7ce3c27ea92396a3cc70a934258d8f6

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/990)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/996)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/988)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/989)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/996)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1010)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/987)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok b345ecb

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok b345ecb52fa281348715ee24ec2019158b9e30d1

**Comment by livecode-vulcan** [comment]
😞 test failure b345ecb52fa281348715ee24ec2019158b9e30d1

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/991)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/997)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/989)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/990)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/997)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1011)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/988)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 513d359

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 513d3596934c3181b5606d76b53e6d936297810c

**Comment by livecode-vulcan** [comment]
😎 test success 513d3596934c3181b5606d76b53e6d936297810c

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/992)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/998)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/990)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/991)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/998)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1012)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/989)

**Pull request closed without merging**
