### PR TITLE
[[ Bug 22605 ]] Load startup screen storyboard

### PR DESCRIPTION
**Pull request by montegoulding**
This patch applies changes to which loads the startup screen storyboard which replaces the previous image for each device and orientation.

### CODE REVIEW

**Comment by montegoulding** [comment]
Requires IDE patch to standalone settings

**Comment by montegoulding** [comment]
IDE patch https://github.com/livecode/livecode-ide/pull/2124

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 753826b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 753826be3cd318dcc8373b765265936d6ff7ee72

**Comment by livecode-vulcan** [comment]
😎 test success 753826be3cd318dcc8373b765265936d6ff7ee72

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/783)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/192)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/192)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/192)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/192)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2309)
* try-community-universal-ios-iphoneos13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.4/builds/42)
* try-community-universal-ios-iphonesimulator13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.4/builds/43)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2337)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2325)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2324)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2359)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2299)

**Pull request merged**
