### PR TITLE
[[ Feature ]] Added Build Number to iOS S/B

### PR DESCRIPTION
**Pull request by abrisan**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 5acf761

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 5acf761a2407715f0ac1f5edc85d6bd1fd057179

**Comment by livecode-vulcan** [comment]
😭 test error 5acf761a2407715f0ac1f5edc85d6bd1fd057179

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/282)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/292)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/271)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/214)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/215)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/281)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/285)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/284)
* try-community-x86-linux-debian8: [error](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/290)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/284)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/290)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/309)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/280)

**Comment by livecodeali** [comment]
The debian build failure is irrelevant here, so this can be merged.

**Pull request merged**
