### PR TITLE
[[ Merge 6.7.7 rc 1 ]] Merge develop-6.7 into develop-7.0

### PR DESCRIPTION
**Pull request by livecodesebastien**
Refactored changes:
- apply bugfix in mblsensor.cpp in mblhandlers.cpp

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Commit 10b6e25 :
7.0-ized change:
    MCStack::setfilename not longer takes ownership of the filename, so the crash does not occur in 7.0
    but a memory leak exists, as File::filename was never released

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 10b6e25

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 10b6e255e6db9e250e5178caa044187c5c5a193a

**Comment by livecode-vulcan** [comment]
😎 test success 10b6e255e6db9e250e5178caa044187c5c5a193a
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/460)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/519)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/406)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/471)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/406)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/397)

**Pull request merged**
