### PR TITLE
[[ Java FFI ]] Fix a few issues

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok d8ff2a6

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d8ff2a6bbf2d329b419951925740fcc64b3953bf

**Comment by livecode-vulcan** [comment]
😞 test failure d8ff2a6bbf2d329b419951925740fcc64b3953bf

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1009)
* try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1015)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1007)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1008)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1015)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1029)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1006)

**Comment by livecodeali** [comment]
@livecode-vulcan retry d8ff2a6

**Comment by livecode-vulcan** [comment]
😞 test failure d8ff2a6bbf2d329b419951925740fcc64b3953bf

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1010)
* try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1016)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1008)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1009)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1016)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1030)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1007)

**Comment by peter-b** [comment]
@livecode-vulcan review ok c720c47

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c720c47d883819052962868d4c22e28753a83e02

**Comment by livecode-vulcan** [comment]
😎 test success c720c47d883819052962868d4c22e28753a83e02

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1015)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1021)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1013)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1014)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1021)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1035)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1012)

**Pull request merged**
