### PR TITLE
[Bug 15969] Playing a video on iOS crashes when touching the screen

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodepanos: Why does adding an exec-ctxt to the stack solve the crash?

**Comment by livecodepanos** [comment]
When the movie screen is touched, then

```
- (void)movieWindowTouched: (UIControl*) p_sender
{
    extern MCExecContext *MCECptr;
    MCEventQueuePostCustom(new MCMovieTouchedEvent(MCECptr -> GetObject()));
}
```

is called with `MCECptr == NULL`, thus the crash occurs. Adding an exec-ctxt matches the LC 6.7.x behaviour, where an `MCEPptr` was used instead.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 4cf83af

**Comment by runrevmark** [comment]
@livecode-vulcan review ok aaa0a2b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok aaa0a2b0284b7ff3cbe085f0331117cf828e607e

**Comment by livecode-vulcan** [comment]
😎 test success aaa0a2b0284b7ff3cbe085f0331117cf828e607e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/523)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/527)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/522)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/522)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/531)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/525)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/533)

**Pull request merged**
