### PR TITLE
[[ Bug 15411 ]] Fix implementation of GetRevAvailableVariables.

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok f0105c8

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f0105c8c831c002a237ec98b1aff6a165d8ba747

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 18a5000

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 18a50008ff817e8405679e272ea207aef10b00ee

**Pull request merged**
