### PR TITLE
[[ WidgetUtils ]] Use icon library for placeholder icons where possible

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by montegoulding** [comment]
not ok - standalone with com.livecode.widget.native.mac.textfield startup
not ok - standalone with com.livecode.widget.linegraph startup
not ok - standalone with com.livecode.widget.native.ios.button startup
not ok - standalone with com.livecode.widget.headerbar startup
not ok - standalone with com.livecode.widget.native.android.field startup
not ok - standalone with com.livecode.widget.treeview startup
not ok - standalone with com.livecode.widget.native.android.button startup
not ok - standalone with com.livecode.widget.switchbutton startup
not ok - standalone with com.livecode.widget.browser startup
not ok - standalone with com.livecode.widget.native.mac.button startup
not ok - standalone with com.livecode.widget.segmented startup
not ok - standalone with com.livecode.widget.navbar startup
not ok - standalone with com.livecode.widget.svgpath startup
FAIL:    /home/travis/build/livecode/livecode/tests/ide-support/standalonebuilder/extensions: TestStandaloneInclusions [33/46]

Seems unrelated to this patch

**Comment by livecodeali** [comment]
Hmm! These all use the widget utils module, so it seems to be not auto-including the icon svg library or at least not loading it.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok e68c037

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok e68c037f4879989ba30652096c7820a8eafc37ce

**Comment by livecode-vulcan** [comment]
😎 test success e68c037f4879989ba30652096c7820a8eafc37ce

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/480)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/472)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/472)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/472)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/472)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1994)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/222)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/221)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2025)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2016)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2014)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2048)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1985)

**Pull request merged**
