### PR TITLE
[Docs] Minor tweaks to LCB-related release notes since 8.0.0-dp-2

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodeali** [comment]
What's your problem with the word provided? :stuck_out_tongue: :smile: 

@livecode-vulcan review ok 97b858b

**Comment by peter-b** [comment]
I just felt that it flowed better the way it was. :octopus:

**Comment by peter-b** [comment]
Or rather, flowed better with the change! Oops. :)

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 97b858bf385d26877151b0640df391734b6f0e4a

**Comment by livecode-vulcan** [comment]
😎 test success 97b858bf385d26877151b0640df391734b6f0e4a
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/737)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/797)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/687)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/751)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/682)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/674)

**Pull request merged**
