### PR TITLE
[[ Bug 15873 ]] Set the iconic state of the stack if the stack window has opened iconified

### PR DESCRIPTION
**Pull request by techstrategies**

### CODE REVIEW

**Comment by runrevmark** [comment]
@techstrategies: Thanks for your contribution :)

I wonder whether it does actually fix the reported problem. I can see that this will correct the case of opening stack, minimizing it, closing the stack, then re-opening it in the sense that the 'iconic' property is correct (i.e. minimized)... However, I can't quite see how it would solve the issue with the stack rect changing.

I wonder if that is best solved by making it so that the engine ignores the window rect changes if the window is iconified - thus preserving the value it was before the iconification.

**Comment by techstrategies** [comment]
@runrevmark The actual rect of the stack doesn't change as such, the position is reported differently because it is iconified but the size of the stack remains the same.  When it is uniconified, the stack position is restored correctly from my test builds under Windows.

**Comment by techstrategies** [comment]
@runrevmark To clarify that, Windows is correctly maintaining the size and position of the stack as it is minimised and restored even if it is closed while it is minimised, there is no preservation issues there.  When the window is iconified, the top left corner is reported by the OS as -32000,-32000 which is not actually a problem.  The bug report can be confusing because the rect only appears to not be restored because the window is still iconified by the system despite LiveCode reporting it as not being iconified (because the flag was never re-set correctly).

**Comment by techstrategies** [comment]
Having said that, I just realised what the confusion might have been.  This fix is written based on the assumption that you would want to let the system to open the window in a minimised state, and not adjust its behaviour (Linux does it this way, though Mac opens it in its restored state).

If the preferred behavior on opening a stack that was closed in the minimised state is to automatically restore it back to its position before it was minimised, then I can adjust it quite easily for that purpose.

**Comment by runrevmark** [comment]
@techstrategies: This will also be affected by the 'destroyWindow' property I think - this causes the system window to be destroyed on close. Actually - that might be a workaround for the Researchware bug at the moment until this patch can be applied.

I'm not sure what the 'correct' behavior should be here to be honest - if script closes a stack, then opens it, does it imply the window is just being reopened and as such should reflect the user's last choice? Or should it be treated as if the window is being re-presented?

Looking at 'openrect' it appears that if you open a stack, then call open on it again it should uniconify it if it is already iconified. Thus doing open stack, then minimize by hand, then open stack _should_ cause the window to be unminimized. This means that minimize, close, then open stack should probably result in an unminimized window.

Indeed, I do think this is the more expected approach - as if you want to save the minimized state on closing a stack, you can do so by checking the iconic property, and opening it in a different way.

So, yes, I wonder if rather than checking the IsIconic property of the system window, it would be better to ensure the system window is uniconified after it is closed (assuming it is not being destroyed due to destroyWindow, that is).

Apologies for rambling a bit there - this seems to be a bit of subtle issue in regards what 'correctness' looks like!

**Comment by techstrategies** [comment]
If the window is destroyed, then yes, the OS would no longer store the system state and it would re-open in the right spot...  

An alternative way to handle this would be to call ShowWindow with SW_RESTORE instead of SW_SHOW in openwindow().  That way, regardless of the window having been closed minimised or not, it will be restored to its proper position.

That would have the added affect that if the window happened to have been maximised before it was closed, that it too would be restored to its normal size.  This would reflect the same behavior that is seen on OS X.

**Comment by techstrategies** [comment]
I think I just got what you were aiming for though... which is that after a window is closed, the user can set or unset the iconic property to determine what state they want the re-opened stack to be in...

Maybe we should just check the state of CS_ICONIC and if it is unset, call ShowWindow with SW_RESTORE instead?

Though that does beg the question of what should be done if the stack was closed maximised.  I don't believe there is a stack property for that?

(I'm rambling here too, it is definitely a question of correctness!)

**Comment by runrevmark** [comment]
@techstrategies: If the stack is closed maximized, at least the rect reflects that. (Of course, it does potentially mean there is a separate bug there if the window is destroyed after being maximized and then re-opened - I'd imagine the rect of the stack will be the maximized size, but the window will not be maximized when open and just fill the screen).

In regards to the current issue - it does sound sensible that if the stack attached to the window does not have CS_ICONIC set when it is opened, it should not open iconified... Which should fix the reported bug and make things a little more sensible. (i.e. you only have to worry about iconification if you want to preserve that for windows you close and then re-open, which seems to me to be a somewhat rare use-case so the scripting balance requires seems about right).

**Comment by techstrategies** [comment]
@runrevmark Apologies for the second commit there, I pushed up before I had double checked the behaviour on OS X (which I had got wrong!).

**Comment by runrevmark** [comment]
@livecode-vulcan review ok b5e6a4b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok b5e6a4bef0ba7a0a95431c8daedd449185f4abdc

**Comment by runrevmark** [comment]
Thanks for the update @techstrategies - this should be good to go for inclusion in 6.7.8 / 7.1.1 :)

**Comment by livecode-vulcan** [comment]
😎 test success b5e6a4bef0ba7a0a95431c8daedd449185f4abdc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/519)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/523)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/518)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/518)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/527)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/521)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/529)

**Pull request merged**
