### PR TITLE
Merge release-8.1.3 into develop-8.1

### PR DESCRIPTION
**Pull request by peter-b**
Various build related tweaks required for Windows-native builds.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review by @peter-b ok a151257

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a151257527d445c30aaf14c1c6293c49a65e4840

**Comment by livecode-vulcan** [comment]
😞 test failure a151257527d445c30aaf14c1c6293c49a65e4840

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/949)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/955)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/947)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/948)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/955)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/953)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/946)

**Comment by peter-b** [comment]
Still a clean merge!

@livecode-vulcan review ok cf956a9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok cf956a98d79bc36ddc517d27099534c582442aa4

**Comment by livecode-vulcan** [comment]
😎 test success cf956a98d79bc36ddc517d27099534c582442aa4

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/958)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/964)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/956)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/957)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/964)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/973)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/955)

**Pull request merged**
