### PR TITLE
[[ LCB Android ]] Allow modules to declare android app requirements in metadata

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali This relates to [bug 18850](http://quality.livecode.com/show_bug.cgi?id=18850), so please could you rename the release note so it appears in the list of resolved bugs?

Do you think it would be worthwhile to file some bug reports/feature requests about the broadcast issue and perhaps making this capability available to externals...?

**Comment by livecodeali** [comment]
@peter-b Sure, totally forgot there was a bug report! I do think it would be worthwhile to file a feature request about broadcast receivers - I will do so.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 7257d6d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 7257d6dbc73a9439b2ebac33e5e720a6f6a1db93

**Comment by livecode-vulcan** [comment]
😞 test failure 7257d6dbc73a9439b2ebac33e5e720a6f6a1db93

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/784)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/789)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/782)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/783)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/789)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/781)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/781)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 7257d6d

**Comment by livecode-vulcan** [comment]
😎 test success 7257d6dbc73a9439b2ebac33e5e720a6f6a1db93

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/800)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/805)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/798)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/799)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/805)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/797)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/797)

**Pull request merged**
