### PR TITLE
Replace references to quality.runrev.com (6.7)

### PR DESCRIPTION
**Pull request by peter-b**
BugZilla is now at http://quality.livecode.com/.

### CODE REVIEW

**Comment by peter-b** [comment]
This also addresses all of the non-IDE references to quality.runrev.com in the develop-7.0 branch.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok cf497ee

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok cf497eeebed7e71911f39791673130ad153da6c1

**Comment by livecode-vulcan** [comment]
😎 test success cf497eeebed7e71911f39791673130ad153da6c1
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1065)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1074)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1062)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1067)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1078)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1083)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1083)

**Pull request merged**
