### PR TITLE
[[ Bug 15432 ]] Opening a stack should resolved its filename before s…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…etting it, like it resolves it to open the file

### CODE REVIEW

**Comment by peter-b** [comment]
I like commits that result in deleting code. :+1: 

I think that it might have been clearer to _keep_ the `{ ... }` in the `if` block though!

@livecode-vulcan review ok 107b5cf

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 107b5cfa8460e12ea67965364e16c747858e79b5

**Comment by livecodepanos** [comment]
This commit causes problems when building Windows engines. The IDE window freezes just before loading the startcenter screen (and it is grey instead of green). If I revert the changes, it works as expected.

**Comment by runrevmark** [comment]
That suggests that there is something subtly different about MCS_resolvepath() on Windows perhaps?

Can you find out what loadfile is using as a final openpath with the patch and without? That way we can see what is tripping up the IDE loading process.

**Comment by livecodesebastien** [comment]
OK, the issue is obvious once I had a look at the code for MCS_resolvepath in w32spec.cpp: it simply turns the path in Windows native format (with backslashes), and does not resolve anything

**Comment by livecodesebastien** [comment]
Issue fixed in the pull request https://github.com/runrev/livecode/pull/2365

**Pull request merged**
