### PR TITLE
[[ Bug 20898 ]] Ensure malloc'd pointer is not incremented before free

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 582d086

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 582d0863e59bf4ca729ec5730ea551ed1deaf59d

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 582d086

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 582d086

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 582d086

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 582d086

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 582d086

**Comment by livecodeali** [comment]
@livecode-vulcan retry 582d086

**Comment by livecode-vulcan** [comment]
😎 test success 582d0863e59bf4ca729ec5730ea551ed1deaf59d

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1226)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1242)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1216)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/169)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/168)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1220)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1246)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1226)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1242)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1225)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1235)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1276)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1218)

**Pull request merged**
