### PR TITLE
[[ Bug 15654 ]] Make AVFoundation a weak-linked (optional) Framework.

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay a443837

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok a4438377306cc7a90a33e1d7563cfcdb6116ffa1

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry a443837

**Comment by livecode-vulcan** [comment]
😎 test success a4438377306cc7a90a33e1d7563cfcdb6116ffa1
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/702)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/762)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/652)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/716)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/647)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/639)

**Pull request merged**
