### PR TITLE
[[ FilterArray ]] Implement filter keys|elements of <array>

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by runrevmark** [comment]
@montegoulding: This looks most useful :) My only comment I think is that it appears 'filter tArray' implicitly chooses the keys to filter... I'd suggest not allowing the implicit form, and instead require:

```
    filter the keys of ...
```

The rationale here is that currently 'filter tArray' will work (the array gets converted to the empty string), and there is no real reason to choose keys over elements for the default, so it is better to be explicit.

**Comment by montegoulding** [comment]
Hmm... Would it be better to throw an error if filtering the lines or items of an array. It seems like something you would want to be told about...

**Comment by montegoulding** [comment]
Just to clarify I agree on the explicit form thing but I'm not so sure that we need to maintain a legacy silent failure of the command on an array

**Comment by runrevmark** [comment]
@montegoulding: I'd argue consistency - at the moment LCS silently converts between strings and arrays (empty either way) in all places.. i.e. Either strings should auto-convert to the empty array and arrays should auto-convert to the empty string everywhere, or nowhere - not piecemeal.

**Comment by montegoulding** [comment]
Ok... It gives me the hebegeebes but oh well. I wonder if one day we could have a strict execution mode where empty isn't 0 and calling an array op on a string throws an error instead of silently failing.

**Comment by montegoulding** [comment]
@runrevmark I've made the changes you wanted and added some tests for filtering arrays including implicit/explicit source conversion. I based my tests on the string filter test and noticed a few issues with it which I'll fix in a separate PR.

**Comment by runrevmark** [comment]
@montegoulding: Just in regard to the 'strict execution' mode - this has long been something we want to do... It would mean Data/String conversions would be an error as would Array/String conversions. There are probably other things we could tighten up as well - like requiring init of vars before use. The strict execution mode could be implemented as extra checks in the MCExecContext type conversion methods - which is why I'm generally against adding it explicitly to specific commands (it should be general, not piecemeal).

**Comment by montegoulding** [comment]
Thanks @runrevmark I agree. Is there anything remaining to do on this PR? Down the track I wouldn't mind adding support for supplying pattern strings as array paths to filter keys or elements multi-dimensionally but I couldn't get my head around that on the plane flight ;-)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok c195032

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok c19503285aaf80f4d7c574d50498b45914dea30b

**Comment by livecode-vulcan** [comment]
😎 test success c19503285aaf80f4d7c574d50498b45914dea30b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/56)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/56)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/56)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/56)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/56)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/56)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/56)

**Pull request merged**
