### PR TITLE
[Bug 16478] Link together mobile launch-related dict entries

### PR DESCRIPTION
**Pull request by peter-b**
Add some cross-references to dictionary.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 463ff21

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 463ff213875295b90da76c1f70186856c751084a

**Comment by livecode-vulcan** [comment]
😞 test failure 463ff213875295b90da76c1f70186856c751084a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1599)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1618)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1595)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1606)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1619)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1620)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1622)

**Comment by peter-b** [comment]
@livecode-vulcan retry 463ff21

**Comment by livecode-vulcan** [comment]
😎 test success 463ff213875295b90da76c1f70186856c751084a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1615)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1634)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1611)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1622)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1635)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1636)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1638)

**Pull request merged**
