### PR TITLE
[[ Merge 6.7.8 ]] 07-10-15 2

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodeali** [comment]
I'm slightly confused - why is the path relative if it has a `/` in it?

**Comment by livecodesebastien** [comment]
Usually, only the name of the stack is given to that function, but there has been an enhancement request to accept names with slashes inside - which are relative.
See the enhancement request http://quality.runrev.com/show_bug.cgi?id=13096

**Comment by livecodeali** [comment]
Ah I see. Thanks.
@livecode-vulcan review ok 651eff7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 651eff744b3cafef668b7c0423588f3cc639fb02

**Comment by livecode-vulcan** [comment]
😎 test success 651eff744b3cafef668b7c0423588f3cc639fb02
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/681)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/694)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/682)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/684)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/694)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/705)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/696)

**Pull request merged**
