### PR TITLE
[[ Bug 22192 ]] Mention using textEncode/textDecode with the dragData["private"]

### PR DESCRIPTION
**Pull request by researchware**

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @researchware, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by livecodepanos** [comment]
Hello @researchware, thank you for the PR.

Since there is a bug report for this issue, could you also add a bugfix note? This means you have to create a file `docs/notes/bugfix-22192.md`, which will contain a short description of the fix (and it will appear in the release notes of the next LC release).

The contents of this file must be a line starting with `#` followed by a space, followed by the description, something like:

`# Mention using textEncode/textDecode with the dragData["private"]`

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 1cba6bd

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 1cba6bd5691c70df4b15ad78ede13a793d7e9558

**Comment by livecode-vulcan** [comment]
😎 test success 1cba6bd5691c70df4b15ad78ede13a793d7e9558

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/598)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/7)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/7)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/7)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/7)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2124)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/349)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/345)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2153)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2140)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2139)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2173)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2113)

**Pull request merged**
