### PR TITLE
Add a document describing C++ language policies

### PR DESCRIPTION
**Pull request by livecodefraser**
A not-so-short document describing the features of the C++ language that are permitted or forbidden from use in the LiveCode codebase.

Not yet complete, but I'm posting the PR so people can look at it and comment.

[Rendered version](https://github.com/livecodefraser/livecode/blob/cxx-features/docs/C%2B%2B.md)

### CODE REVIEW

**Comment by livecodefraser** [comment]
I don't believe there were any strenuous objections to anything in this... as we don't have any existing documentation on this topic, I think we should probably go ahead and merge it. If there is anything that needs to be changed, then we can change it when we come across it.

**Comment by peter-b** [comment]
@livecode-vulcan review ok d9cb9dd

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d9cb9dd2af729a151afa104be31a1b75a2e83471

**Comment by livecode-vulcan** [comment]
😎 test success d9cb9dd2af729a151afa104be31a1b75a2e83471
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/574)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/579)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/574)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/578)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/583)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/575)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/575)

**Pull request merged**
