### PR TITLE
[[ Header Bar ]] General rework

### PR DESCRIPTION
**Pull request by livecodeali**
- The header bar colors are now controlled by the standard LiveCode
  **foregroundColor**, **backgroundColor**, **hiliteColor** and **borderColor**
  properties.  They can be edited in the property inspector.
- The visibility of the border at the bottom edge of the header bar is now
  controlled by the standard LiveCode **showBorder** property, which can be
  edited in the property inspector.
- The header bar now uses the **theme** property to control its appearance.
  Currently, the **theme** property is _not_ saved, and is reset to "native"
  whenever the widget is loaded.
- The **widgetTheme** property has been removed.
- The **colorScheme** property has been removed.
- The **actionColor** property has been removed.
- The **leftLabel** and **showBackIcon** properties have been removed.
- The **headerSubtitle** property has been removed.
- The **distinctTitle** property has been removed.
- The **headerTitle** property has been renamed to **label**.
- The **titleVisibility** property has been renamed to **showLabel**.
- The **backgroundOpacity** property has been renamed to **opaque**.
- The **showDivide** property has been renamed to **showBorder**.
- The **actionData** property has been renamed to **itemArray**.
- The **actionNames** property has been renamed to **itemNames**.
- The **actionIcons** property has been renamed to **itemIcons**.
- The **actionSelectedIcons** property has been renamed to **hilitedItemIcons**.
- The **actionLabels** property has been renamed to **itemLabels**.
- The **actionStyle** property has been renamed to **itemStyle**.
- A new property **firstItemLeft** has been added. If true, the first
  action in the **itemArray** is displayed on the left hand side of the
  header bar. On iOS, the icon and label of a left action are both drawn.
  On Android, only the left action icon is drawn.
- A new read-only **mouseAction** property has been added.  It contains
  the name of the action item that the mouse is currently over, or empty
  if there is no such action.
- The **headerAction**, **leftAction** and **backAction** signals have
  been removed.
- The header bar tests have been updated to use the new property names.
- Bugfixes:
  - [17006] Header widget throws error if leftLabel is empty
  - [16979] Header Widget loses header actions if show back icon unchecked

### CODE REVIEW

**Comment by peter-b** [comment]
A few comments:
- Please use `/** ... */` format for documentation comments
- It would be helpful to flesh out some of the doc comments (e.g. explaining what's meant by an "icon name")
- The `theme` property's doc comments mention the switchbutton, which probably isn't intentional
- Although the `mouseAction` property probably shouldn't be in the property inspector, it might be a good idea to document it
- You seem to have left some debugging `log` statements in there

Other than that all seems good. :+1:

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1e5f5cf

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1e5f5cf6ba47508ffc6917917b241bad51d39a37

**Comment by livecode-vulcan** [comment]
😎 test success 1e5f5cf6ba47508ffc6917917b241bad51d39a37
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2076)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2087)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2070)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2084)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2090)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2098)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2104)

**Pull request merged**
