### PR TITLE
Fix assert exec method definition

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 584c4c5

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 584c4c569e88724286244f5ceda8cd352e5efb36

**Comment by livecode-vulcan** [comment]
😞 test failure 584c4c569e88724286244f5ceda8cd352e5efb36

* try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/921)
* try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/927)
* try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/919)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/920)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/927)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/919)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/918)

**Comment by montegoulding** [comment]
@livecode-vulcan retry 584c4c5

**Comment by livecode-vulcan** [comment]
😞 test failure 584c4c569e88724286244f5ceda8cd352e5efb36

* try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/928)
* try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/934)
* try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/926)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/927)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/934)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/926)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/925)

**Comment by montegoulding** [comment]
@livecode-vulcan retry 584c4c5

**Comment by livecode-vulcan** [comment]
😎 test success 584c4c569e88724286244f5ceda8cd352e5efb36

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/937)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/943)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/935)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/936)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/943)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/935)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/934)

**Pull request merged**
