### PR TITLE
Fix integer points

### PR DESCRIPTION
**Pull request by mwieder**
Allows for the parsing and setting of non-integer points for graphic objects.
Changes MCU_strtol to round nonintegral values to the nearest integer and allows parsepoint and parsepoints to accept nonintegral values as arguments.

### CODE REVIEW

**Comment by runrevmark** [comment]
Hi Mark - thanks for this - I'll review and merge it in after the weekend before we do the next dp.

**Comment by runrevmark** [comment]
Hi Mark - I started having a look at this yesterday and I'm happy with MCU_parsepoints() accepting reals (and then rounding)... However, I'm still not 100% sure about the rounding mode in MCU_strtol - the latter is quite subtle and I want to make sure we make the right decision as it will have a subtle effect on existing code. I'm probably being a bit anally retentive about it, but I just want to make sure 'round to nearest away from zero' is the right way to go for everything. I just need to do a bit more experimenting to convince myself :)

**Comment by mwieder** [comment]
Mark - take your time. I did it both ways, then decided this was both the easiest and (I think) the most correct. But do note that without the rounding in MCU_strtol the MCU_parsepoints change will have no effect, as the decimal point will end the numeric parsing, and the non-integer part of the real number will start a new line in "the points".

**Comment by runrevmark** [comment]
Hi Mark,

Finally had some time to ponder this some more - especially in line with the type-mapping stuff we're firming up for the refactored branch. Anyway, I'll pull this in tomorrow morning (my next slot to integrate things) to develop as is as a fix to both the graphic points problem and inconsistent rounding (which I filed as a separate bug). After a little more thought I was perhaps being a little overly cautious and in the end it is better to round consistently than not-at-all, or inconsistently. If anyone notices any subtle issues with the change during the dev-cycle we can reconsider it then - it should be long enough to ensure we haven't subtle broken anyones code ;)

Thanks for your work,

Mark.

**Comment by runrevmark** [comment]
I've pulled these into develop as two separate branches - bugfix-11041 and bugfix-10964 - the former is for the change to point parsing (i.e. the points property of graphics) and the latter is the change to rounding in MCU_strotol.

Thanks again,

Mark.

**Pull request closed without merging**
