### PR TITLE
Added support for building with Xcode 11.1 / iOS 13.1 SDK

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodepanos** [comment]
The iOS 13.1 prebuilts are now ready, so this PR is ready for review

**Review by livecodeali — APPROVED** [review]

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 0305030

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 0305030da78f5b99a16bcaf1691640592e5b215a

**Comment by livecode-vulcan** [comment]
😎 test success 0305030da78f5b99a16bcaf1691640592e5b215a

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/640)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/49)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/49)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/49)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/49)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2166)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/0)
* try-community-universal-ios-iphonesimulator13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/0)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2195)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2182)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2181)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2215)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2155)

**Pull request merged**
