### PR TITLE
[[ Big 20216 ]] Fix incorrect item delimiter in httpd callback example

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 15e6c82

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 15e6c82260b345324848e873a87e712d01234a8c

**Comment by livecode-vulcan** [comment]
😭 test error 15e6c82260b345324848e873a87e712d01234a8c

* try-community-armv6-android-api8: [error](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/555)
* try-community-armv6-android-api9: [error](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/570)
* try-community-js-emscripten-sdk1.35: [error](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/544)
* try-community-universal-ios-iphoneos10.3: [error](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/487)
* try-community-universal-ios-iphonesimulator10.3: [error](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/490)
* try-community-universal-mac-macosx10.6: [error](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/550)
* try-community-universal-mac-macosx10.9: [error](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/558)
* try-community-x86-linux-debian7: [error](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/553)
* try-community-x86-linux-debian8: [error](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/570)
* try-community-x86_64-linux-debian7: [error](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/553)
* try-community-x86_64-linux-debian8: [error](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/563)
* try-community-x86-win32: [error](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/585)
* try-community-x86_64-win32: [error](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/549)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 15e6c82

**Comment by livecode-vulcan** [comment]
😭 test error 15e6c82260b345324848e873a87e712d01234a8c

* try-community-armv6-android-api8: [error](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/556)
* try-community-armv6-android-api9: [error](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/571)
* try-community-js-emscripten-sdk1.35: [error](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/545)
* try-community-universal-ios-iphoneos10.3: [error](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/488)
* try-community-universal-ios-iphonesimulator10.3: [error](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/491)
* try-community-universal-mac-macosx10.6: [error](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/551)
* try-community-universal-mac-macosx10.9: [error](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/569)
* try-community-x86-linux-debian7: [error](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/554)
* try-community-x86-linux-debian8: [error](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/571)
* try-community-x86_64-linux-debian7: [error](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/554)
* try-community-x86_64-linux-debian8: [error](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/564)
* try-community-x86-win32: [error](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/586)
* try-community-x86_64-win32: [error](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/550)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 15e6c82

**Comment by livecode-vulcan** [comment]
😎 test success 15e6c82260b345324848e873a87e712d01234a8c

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/558)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/573)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/547)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/490)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/493)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/553)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/571)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/557)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/573)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/556)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/566)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/588)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/552)

**Pull request merged**
