### PR TITLE
[Bug 16921] Rename "is really" to "is strictly".

### PR DESCRIPTION
**Pull request by peter-b**
Making the syntax `is strictly` better reflects the fact that it
operates on a "strict" typing model.
- Remove the "may be revised in LC8 cycle" caveat from dictionary
  entries
- Add some basic tests

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 569b018

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 569b018cf035ed4ca67ad6932f37c1e050eaf2ef

**Comment by livecode-vulcan** [comment]
😎 test success 569b018cf035ed4ca67ad6932f37c1e050eaf2ef
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1796)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1809)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1790)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1802)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1811)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1815)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1821)

**Pull request merged**
