### PR TITLE
Update mergExt Pointer

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
Still uploading so Travis will fail.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok bf0aede

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok bf0aedef0925bc10e26275b979c23bb4179479e6

**Comment by livecode-vulcan** [comment]
😎 test success bf0aedef0925bc10e26275b979c23bb4179479e6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2758)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2767)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2753)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2769)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2775)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2779)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2797)

**Pull request merged**
