### PR TITLE
[[ Bug 16335 ]] Fix slow resizing of browser widget when hidden

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 1438ead

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 1438eadcab432a3fc58185b80dfd638fac7e1218

**Comment by livecode-vulcan** [comment]
😎 test success 1438eadcab432a3fc58185b80dfd638fac7e1218
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1038)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1046)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1035)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1039)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1049)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1056)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1054)

**Comment by peter-b** [comment]
Hi @livecodeian, please don't forget to set a suitable milestone on each pull request as you submit it.  It helps make sure that pull requests don't fall through the cracks!

**Pull request merged**
