### PR TITLE
[[ Bug 17700 ]] Remove UTF8 BOM from release note

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1026ce6

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1026ce65047f7ed08e2b81a9dd7c5f64d8148595

**Comment by peter-b** [comment]
Merged this pre-test since the tests don't currently cover the release notes.

**Comment by livecode-vulcan** [comment]
⁉ merge unchanged 1026ce65047f7ed08e2b81a9dd7c5f64d8148595 → 423e26748e35d66bde32fd52f769556246fdadcd

Pull request is already fully merged!

**Pull request merged**
