### PR TITLE
Bugfix/coverity issues

### PR DESCRIPTION
**Pull request by montegoulding**
These are fixes to some covert scan issues related to lcidlc that @peter-b sent me. As far as I can tell there's no way for me to initiate a scan to test if they are resolved correctly. It's a first for me trying to interpret what Coverity doesn't like and what the issues meant etc so hopefully I'm not too far wrong...

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[lcidlc/src/Scanner.cpp, line 430 [r6]](https://reviewable.io:443/reviews/livecode/livecode/3049#-K0VbDFjbWMrOXGWZ-eG)** ([raw file](https://github.com/livecode/livecode/blob/ccc41c187c7e7f0671320e2c4af4639f78704ca1/lcidlc/src/Scanner.cpp#L430)):</sup>
Hi @montegoulding, I think this fix doesn't address the underlying problem.  You need to store the return value of ftell(3) into a `long`, and check its sign.  ftell(3) returns a negative result and sets `errno` on failure (e.g. if the fd is bad, or if the file offset is too large to fit into a `long`!)  Once you've checked the sign, you can then cast to `size_t` (because IIRC `size_t` is larger than `long` on all our supported platforms) and Coverity won't whinge.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3049)

**Comment by peter-b** [comment]
@livecode-vulcan review not ok ccc41c1



---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3049)

**Comment by peter-b** [comment]
Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[lcidlc/src/Scanner.cpp, line 430 [r6]](https://reviewable.io:443/reviews/livecode/livecode/3049#-K0VbDFjbWMrOXGWZ-eG)** ([raw file](https://github.com/livecode/livecode/blob/ccc41c187c7e7f0671320e2c4af4639f78704ca1/lcidlc/src/Scanner.cpp#L430)):</sup>
@montegoulding Thanks, this looks good. :+1: 



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3049)

**Comment by peter-b** [comment]
@livecode-vulcan review ok f7aee22



---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3049)

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f7aee228a5f6a7a828eecd372c397b052f9f432a

**Comment by livecode-vulcan** [comment]
😎 test success f7aee228a5f6a7a828eecd372c397b052f9f432a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/724)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/737)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/725)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/727)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/737)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/748)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/739)

**Pull request merged**
