### PR TITLE
[[ Bugfix 18495 ]] Fix errors in libURL forms

### PR DESCRIPTION
**Pull request by trevordevore**
In libURLMultipartFormData and libURLMultipartFormAddPart libURL tries to accommodate multiple files being passed in. The issue is that it uses comma as the itemDelimiter which is very brittle. Any filename with a comma in it breaks the code. 

This behavior isn't currently documented so this PR removes the code that looks for multiple file attachments. I can create a test for this if you can tell me the proper way to create a test with an external file.

Also, another alternative is to update the code to use some other character as a delimiter. If that is the preferred fix I can modify this PR. I'm waiting to create a release note until I hear back.

### CODE REVIEW

**Comment by peter-b** [comment]
@trevordevore I assume that the simple workaround for the removal of multiple file names separated with "," is to just call `libURLMultipartFormAddPart` multiple times.  Is that correct?

**Comment by trevordevore** [comment]
@peter-b Yes.

**Comment by peter-b** [comment]
@trevordevore In that case I think that this PR is a really good idea.  Thank you!  Can I suggest including a release note that explains that "the undocumented behaviour has been removed, you can use `libURLMultipartFormAddPart` multiple times instead" or words to that effect?

**Comment by trevordevore** [comment]
I've aded the release note. For tests can I include external files or create files on the fly? I can add a test that shows the handler breaking if I can reference an external file somehow.

**Comment by trevordevore** [comment]
@peter-b ^

**Comment by peter-b** [comment]
@trevordevore It's fine to add minimal files as part of the test infrastructure.  Look at the [clipboard tests](https://github.com/livecode/livecode/blob/develop/tests/lcs/core/engine/clipboard.livecodescript), for example.

**Comment by trevordevore** [comment]
@peter-b Ready for review.

**Comment by peter-b** [comment]
@livecode-vulcan review ok b2683af

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b2683afefd09d7b9fa4ed66f62774cc1ca93885b

**Comment by livecode-vulcan** [comment]
😎 test success b2683afefd09d7b9fa4ed66f62774cc1ca93885b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/472)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/477)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/472)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/472)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/478)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/472)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/472)

**Comment by peter-b** [comment]
@trevordevore It looks like the form tests are failing on Travis CI.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 82a8981

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 82a898122ff1e6ca261290156d1036fc3e71b83b

**Comment by livecode-vulcan** [comment]
😎 test success 82a898122ff1e6ca261290156d1036fc3e71b83b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/477)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/482)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/477)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/477)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/483)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/477)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/477)

**Comment by peter-b** [comment]
@trevordevore Thanks for persevering with this :-)

**Comment by trevordevore** [comment]
@peter-b NP. With each PR the process becomes more familiar and gets easier.

**Pull request merged**
