### PR TITLE
[[ Bug 17510 ]] Prevent hang when parsing invalid SVG data after 'z'

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodeali: I think the problem here is that we have 'Close' and 'RelativeClose' path commands. According to the SVG spec there is only 'Close' which is 'z' - there is no such thing as 'RelativeClose'. So, the correct fix is probably to make 'z' => Close and eliminate RelativeClose entirely.

**Comment by runrevmark** [comment]
Correction - 'z' and 'Z' should map to Close - there is no need for RelativeClose at all.

**Comment by livecodeali** [comment]
Yep, makes sense!

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 50bba66

**Comment by runrevmark** [comment]
@livecode-vulcan review no ok 50bba66

**Comment by runrevmark** [comment]
@livecode-vulcan review not ok 50bba66

**Comment by livecode-vulcan** [comment]
💔 review by @runrevmark not ok 50bba6678c7948ecf0be8ebe949ba27feb4c2c95

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 6765eb6

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 6765eb60aa9a43d9ba0f3d02b7d75b8b5399f165

**Comment by livecode-vulcan** [comment]
😞 test failure 6765eb60aa9a43d9ba0f3d02b7d75b8b5399f165
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2461)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2471)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2454)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2472)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2478)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2482)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2494)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 6765eb6

**Comment by livecode-vulcan** [comment]
😎 test success 6765eb60aa9a43d9ba0f3d02b7d75b8b5399f165
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2462)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2472)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2455)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2473)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2479)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2483)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2495)

**Pull request merged**
