### PR TITLE
The <metadata> of image property wasn't documented. There were two .x…

### PR DESCRIPTION
**Pull request by trevordevore**
…ml files in the repository (metadata_of_field/image.xml) which I've removed. I renamed metadata.lcdoc to metadata_of_field.lcdoc and added metadata_of_image.lcdoc. I used the information from metadata_of_image.xml but changed the version from 6.7 to 8.0 as it was introduced in 8.0 dp-3.

### CODE REVIEW

**Comment by peter-b** [comment]
@trevordevore Thanks for this patch -- improvements to the documentation are always very welcome!

In order to make it easier for us to review and manage your changes in the future, could you please write your commit messages (and pull requests!) following [these guidelines](http://chris.beams.io/posts/git-commit/)?  In particular, please use format:

> One line summary, less than 79 chars
> 
> More detailed description, possibly with multiple paragraphs

Thanks! :+1:

**Comment by trevordevore** [comment]
Sure @peter-b. Would you like me to redo this message?

**Comment by peter-b** [comment]
@trevordevore Let's put this one in as is.  Since it's a documentation patch rather than a code patch it's not so critical to have a very clean history!

@livecode-vulcan review ok 5ccdd0b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 5ccdd0bd3ad295f40b5921e3c459972fb24f7dca

**Comment by livecode-vulcan** [comment]
😎 test success 5ccdd0bd3ad295f40b5921e3c459972fb24f7dca
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/695)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/708)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/696)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/698)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/708)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/719)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/710)

**Pull request merged**
