### PR TITLE
Make sure QT is (weak) linked when setting player's dontuseqt to false

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
I think this should be calling MCQTInit() rather than weak linking directly

**Comment by livecodeali** [comment]
Ah, actually, I see why not.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok a0cd477

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a0cd47738ce97e1c9d77e63dd8fcb414ca0960be

**Comment by livecode-vulcan** [comment]
😎 test success a0cd47738ce97e1c9d77e63dd8fcb414ca0960be
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/514)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/518)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/513)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/513)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/522)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/516)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/524)

**Pull request merged**
