### PR TITLE
[[ Bug 18247 ]] For external libUrl drivers, call the external function lvExtIsBlocked() to check for existing blocking connections

### PR DESCRIPTION
**Pull request by techstrategies**
This PR relies on the tsNet external version 1.2.2

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 381f76e

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 381f76e6556654804fccf3cea7133395933d7993

**Comment by livecode-vulcan** [comment]
😎 test success 381f76e6556654804fccf3cea7133395933d7993
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/108)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/108)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/108)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/108)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/108)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/108)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/108)

**Comment by livecodepanos** [comment]
@livecode-vulcan review okay by @montegoulding 381f76e

**Comment by montegoulding** [comment]
I think vulcan doesn't care when you change the base branch

**Pull request merged**
