### PR TITLE
[[ Bug 15263 ]] Make sure file sizes use off_t in Open.

### PR DESCRIPTION
**Pull request by runrevmark**
…izes in MCS_open.

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevmark: it might be worth adding a comment explaining why the check against `UINT32_MAX` is necessary (i.e. that if `mmap()` is successful, we have to be able to store the file size in a `uint32_t`-sized variable).

Otherwise: what a simple fix! :+1:

**Comment by peter-b** [comment]
@livecode-vulcan review ok 125f2dc

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 125f2dc30871d46a4966f83967ce3531988fc931

**Comment by livecode-vulcan** [comment]
😎 test success 125f2dc30871d46a4966f83967ce3531988fc931
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/327)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/390)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/272)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/338)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/273)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/263)

**Comment by livecodesebastien** [comment]
Should this pull request have the same mmap fixes as https://github.com/runrev/livecode/pull/2508/files has?

**Comment by runrevmark** [comment]
@livecodesebastien: No - the system implementations between 6.7 and 7.0 have changed. So only that one use of mmap on linux in 6.7 needed patching.

**Pull request merged**
