### PR TITLE
[[Cleanup]] More type conversion warnings in graphics headers.

### PR DESCRIPTION
**Pull request by peter-b**
Fixes some possible issues with truncation rather than saturation.

### CODE REVIEW

**Comment by livecodeian** [comment]
@livecode-vulcan review ok cc5f87b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevian ok cc5f87bde277d7e7ec3affcf3df065fff8ea825b

**Comment by livecode-vulcan** [comment]
😎 test success cc5f87bde277d7e7ec3affcf3df065fff8ea825b
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/627)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/687)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/576)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/640)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/572)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/565)

**Comment by trevordevore** [comment]
I think this commit may have introduced some drawing issues in the engine. On OS X the IDE UI no longer renders correctly after applying this commit.
c87f624c-2bc5-4906-90aa-f5ba1991e754

**Comment by peter-b** [comment]
...I'll just go fix that... now... :fearful:

**Comment by peter-b** [comment]
#2640 should sort this. My bad. :-(

**Comment by livecodeali** [comment]
Nice sneak preview of @trevordevore 's personal widget collection there :smile:

**Comment by trevordevore** [comment]
All your widgets are belong to me @livecodeali

**Comment by trevordevore** [comment]
Thanks @peter-b. Looks much better now!

**Pull request merged**
