### PR TITLE
[Bug 7344] Correct gray RGB values in "GrayX" colors

### PR DESCRIPTION
**Pull request by meiradarocha**
"GrayX" series (where X is a number from 0 to 100) returned by the colorNames function has wrong values.

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @meiradarocha, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by montegoulding** [comment]
@meiradarocha thanks for the contribution! If you want to sort out the contributor agreement I'll check with the team whether we can include it from a backwards compatibility standpoint as these colors have been incorrect for a loooong time and I guess there could be people depending on their incorrect value.

**Comment by montegoulding** [comment]
This is the bug report for this issue http://quality.livecode.com/show_bug.cgi?id=7344

This patch will therefore need a bugfix note in the docs/notes directory.

**Comment by montegoulding** [comment]
@meiradarocha While there is some concern that projects may look different in the version that this patch is applied to that it would be beneficial to fix these values and move forward as long as the change is well documented. On that note we will need you to add a bugfix-7344.md file to the docs/notes directory explaining the change. This will appear in the release notes for the version this patch is merged into. I think we also will need `the colorNames` dictionary entry updated noting the change in version 8.1.

**Comment by meiradarocha** [comment]
Thank you, @montegoulding I will do that.

**Comment by montegoulding** [comment]
@meiradarocha We really need all the changes for this patch to be included in the one pull request. This means any further changes you make related to the GrayX colors needs to be on this branch https://github.com/meiradarocha/livecode/tree/patch-1

Just for clarity the lcdoc change will need to add a `Changes:` element. Something like this:

```
Changes:
In LiveCode 8.1 the Gray1-100 colors were corrected to match the shades of gray from the [X11 color names](https://en.wikipedia.org/wiki/X11_color_names).
```

We also need a `docs/notes/bugfix-7344.md` file containing something like:

```
# Correct named shades of gray (Gray1-100) to match the X11 color names
```

**Comment by mwieder** [comment]
Just a question here, since the new values seem correct (and thank you for fixing this - they've been wrong forever)...

Would it make sense to eliminate the magic numbers and just use round((NN / 100) \* 255) for all the GrayNN values? I mean, as long as this is compile-time assignment and not runtime function calling.

**Comment by montegoulding** [comment]
@meiradarocha Thanks for the updates to the PR. The merge conflicts will be on the lcdoc file due to the hard wrapping PR we merged the other day. Unfortunately there isn't really an easy way to resolve this without using git locally rather than via the github web interface. Let me know if you need talking through that. If you want to use a git gui I recommend sourcetree.

**Comment by meiradarocha** [comment]
OK, I will do that.
Thank you.

**Comment by meiradarocha** [comment]
@mwieder, it would probably make more sense to not use magic numbers, but I have no skills in C ++ to do this.

**Comment by mwieder** [comment]
@meiradarocha no worries. I was just suggesting something like
instead of 
{"Gray11", 28, 28, 28},
using the form
{"Gray11", round((11 / 100) \* 255), round((11 / 100) \* 255), round((11 / 100) \* 255)},

**Comment by montegoulding** [comment]
@meiradarocha we would like to include this in LiveCode 8.1 but need to resolve the conflict first. Do you need help doing that?

**Comment by meiradarocha** [comment]
Yes, @montegoulding. Currently,  I have no spare time to learn local git to resolve this. If you could make this patch would be fine.

**Comment by montegoulding** [comment]
@livecode-vulcan review ok be92d8e

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok be92d8e0d34963ba8517ab23a8a5622131e1eb9c

**Comment by livecode-vulcan** [comment]
😎 test success be92d8e0d34963ba8517ab23a8a5622131e1eb9c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/66)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/66)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/66)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/66)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/66)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/66)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/66)

**Pull request merged**
