### PR TITLE
[[ Installer ]] Add 'installer command line' environment and use in installer stack

### PR DESCRIPTION
**Pull request by livecodeali**
The installer stack was explicitly handing the 'noui' command line option.
This patch adds an 'installer command line' environment value which is true
if -ui is passed as an argument to the executable, so that faceless install
depends on the environment, for consistency with development mode.

### CODE REVIEW

**Comment by livecodeali** [comment]
installer.rev diff: https://gist.github.com/livecodeali/1d3ef019c24eee76a311a1f30467d521

**Comment by seaniepie** [comment]
@livecodeali , I've been developing/updating an App Package Signing standalone for the MacOS AppStore. Would this be of any use to you for integrating into the LiveCode application? I'm putting it out there for free. It basically creates a pkg file from the standalone after signing the various components within and now also creates a dmg and signs that as well (as recommended now by Apple). Here's the link to the current version stack:
https://www.dropbox.com/s/f00ji8tf24gwhz1/OSX_Packager2017.livecode?dl=0

**Comment by livecodeali** [comment]
@seaniepie Thanks! I'll put it on the backlog to have a look at.

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok e6d195e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok e6d195ebb9790586c2e42ebae1d2afe5d7da7bfb

**Comment by livecode-vulcan** [comment]
😎 test success e6d195ebb9790586c2e42ebae1d2afe5d7da7bfb

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/838)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/844)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/836)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/837)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/844)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/835)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/835)

**Pull request merged**
