### PR TITLE
libfoundation: Check for bad MCValueRef casts (part 2)

### PR DESCRIPTION
**Pull request by peter-b**
Add assertions to every public libfoundation function that accepts arguments of MCValueRef type, ensuring that the values are of the expected type.  This extends #3032 to add checks to all the new things in LiveCode 8's extended & improved libfoundation.

[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode/3035)

### CODE REVIEW

**Comment by runrevmark** [comment]
Reviewed 16 of 17 files at r3.
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[libfoundation/src/foundation-stream.cpp, line 148 [r3]](https://reviewable.io:443/reviews/livecode/livecode/3035#-K0QnWHPD-PJOF_ExxLY)** ([raw file](https://github.com/livecode/livecode/blob/20fee492e91456a506fead5966aae7591498e6bd/libfoundation/src/foundation-stream.cpp#L148)):</sup>
Given that we are allowing 'nil' for 0 length buffers elsewhere, isn't this inconsistent?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3035)

**Comment by peter-b** [comment]
Review status: 16 of 17 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

<sup>**[libfoundation/src/foundation-stream.cpp, line 148 [r3]](https://reviewable.io:443/reviews/livecode/livecode/3035#-K0QnWHPD-PJOF_ExxLY)** ([raw file](https://github.com/livecode/livecode/blob/20fee492e91456a506fead5966aae7591498e6bd/libfoundation/src/foundation-stream.cpp#L148)):</sup>
Fixed!



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3035)

**Comment by runrevmark** [comment]
Reviewed 1 of 2 files at r4.
Review status: 16 of 17 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3035)

**Comment by runrevmark** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode/3035)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok faa8e2e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok faa8e2e914d74768652b4f0ed864688d0ef73693

**Comment by livecode-vulcan** [comment]
😞 test failure faa8e2e914d74768652b4f0ed864688d0ef73693
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/705)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/718)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/706)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/708)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/718)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/729)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/720)

**Comment by peter-b** [comment]
@livecode-vulcan retry faa8e2e

**Comment by livecode-vulcan** [comment]
😞 test failure faa8e2e914d74768652b4f0ed864688d0ef73693
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/706)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/719)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/707)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/709)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/719)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/730)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/721)

**Comment by peter-b** [comment]
@runrevmark Pull request updated to address Windows build error.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok d5253c5

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d5253c556210ef0ccdef68deb8383a3c691e57d3

**Comment by livecode-vulcan** [comment]
😎 test success d5253c556210ef0ccdef68deb8383a3c691e57d3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/715)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/728)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/716)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/718)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/728)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/739)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/730)

**Comment by peter-b** [comment]
Failed tests locally. @livecodeali added a bunch of new tests to the engine, which this PR breaks. :sob: 

@livecode-vulcan review not ok d5253c5

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok d5253c556210ef0ccdef68deb8383a3c691e57d3

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 7ae3fa8

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 7ae3fa822c46583c100bc0c6be3dae4e1b800f74

**Comment by livecode-vulcan** [comment]
😎 test success 7ae3fa822c46583c100bc0c6be3dae4e1b800f74
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/736)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/750)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/737)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/739)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/750)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/760)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/752)

**Pull request merged**
