### PR TITLE
[[ Bug 14645 ]] Include tabAlign in htmlText and styledText field properties

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian Are you happy to merge this using `intenum_t` in the API rather than switching to a named `enum`?  If so you can mark this as reviewed by me.

**Comment by livecodeian** [comment]
I think leave it for now - there's more involved in updating several structs which use bitfields for the field textalign as well. Perhaps add cleaning up the field / paragraph style enums as a backlog item?

**Comment by peter-b** [comment]
@livecodeian It's probably not worth it at the moment.  Maybe if we come back to this code at some point in the future.

@livecode-vulcan review ok 41e696b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 41e696b6cfebee5c3b19edd01c8b25d240a68fc3

**Comment by livecode-vulcan** [comment]
😎 test success 41e696b6cfebee5c3b19edd01c8b25d240a68fc3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/267)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/271)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/267)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/267)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/271)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/267)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/267)

**Comment by peter-b** [comment]
This is a new feature and shouldn't go into the stable branch.  I think #4543 was actually fine...
Sorry for the mix-up 😭 
@livecode-vulcan review not ok 41e696b

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 41e696b6cfebee5c3b19edd01c8b25d240a68fc3

**Pull request closed without merging**
