### PR TITLE
Complete tokenOffset implementation

### PR DESCRIPTION
**Pull request by montegoulding**
It looks like I found a half implemented feature here. It's documented and as you can see from the limited amount I needed to do was mostly implemented. I'll rebase on whatever seems appropriate once I get some feedback on which version it should go into.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b49362f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b49362f8e877d1af0ca45d8bd925f541a27389e2

**Comment by peter-b** [comment]
@livecode-vulcan retry b49362f

**Comment by livecode-vulcan** [comment]
😞 test failure b49362f8e877d1af0ca45d8bd925f541a27389e2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/3)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/3)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/3)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/3)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/3)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/3)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/3)

**Comment by montegoulding** [comment]
Can I? @livecode-vulcan retry b49362f

**Comment by peter-b** [comment]
@montegoulding Don't forget that @livecode-vulcan only pays attention when its name appears at the start of a line!

@livecode-vulcan retry b49362f

**Comment by livecode-vulcan** [comment]
😎 test success b49362f8e877d1af0ca45d8bd925f541a27389e2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/9)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/9)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/9)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/9)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/9)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/9)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/9)

**Comment by montegoulding** [comment]
Aha... I knew there was a rule but I forgot what it was... thanks @peter-b

**Pull request merged**
