### PR TITLE
[[ Bug 18380 ]] Add bugfix note

### PR DESCRIPTION
**Pull request by techstrategies**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok b76cf9a

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok b76cf9a28f275ee2aad62d1d3636cf29aa502254

**Comment by livecode-vulcan** [comment]
😞 test failure b76cf9a28f275ee2aad62d1d3636cf29aa502254
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/197)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/201)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/197)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/197)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/201)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/197)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/197)

**Comment by peter-b** [comment]
@livecode-vulcan retry b76cf9a

**Comment by livecode-vulcan** [comment]
😎 test success b76cf9a28f275ee2aad62d1d3636cf29aa502254
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/208)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/212)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/208)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/208)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/212)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/208)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/208)

**Pull request merged**
