### PR TITLE
Merge develop 9.0 21.06.18

### PR DESCRIPTION
**Pull request by livecodeali**
Conflicts:
       config.py
       docs/development/build-android.md
       ide
       ide-support/revdeploylibraryandroid.livecodescript
       prebuilt/scripts/android.inc

### CODE REVIEW

**Comment by livecodeali** [comment]
Conflicts: https://gist.github.com/livecodeali/bfd8913d426cb752975649af5171a6f4

Note something slightly odd there with a change in the drawing library - I'm not sure how that got in there but it doesn't seem to have been changed in my patch

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 83f2f0c

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 83f2f0c0c4277f886e8939c05032fff84e591997

**Comment by livecode-vulcan** [comment]
😎 test success 83f2f0c0c4277f886e8939c05032fff84e591997

* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1543)
* try-community-armv6-android-api26: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api26/builds/28)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1517)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/44)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/44)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1547)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1541)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1536)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1575)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1515)

**Pull request merged**
