### PR TITLE
[[ Bug ]] Ensure you don't get 'random' number parsing failures due t…

### PR DESCRIPTION
**Pull request by runrevmark**
…o un-reset errno.

### CODE REVIEW

**Comment by runrevmark** [comment]
This is the 8.0 version of #2381 they conflict due to changes in MCNumberParse.

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok c29b164

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok c29b164c9d0e292d69b0a754ae6b925383b99ff6

**Comment by livecode-vulcan** [comment]
😞 test failure c29b164c9d0e292d69b0a754ae6b925383b99ff6
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/157)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/221)
- try-ios: [pending](https://vulcan.livecode.com/builders/try-ios/builds/110)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/167)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/103)
- try-mac: unknown

**Comment by runrevmark** [comment]
Superseded by #2409

**Pull request closed without merging**
