### PR TITLE
lc-compile: Fix namespace-related crash in some compilation modes

### PR DESCRIPTION
**Pull request by peter-b**
This PR fixes a crash bug in `lc-compile` relating to namespace handling.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 561b3b9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 561b3b9efa0496c540a8af855ef92fefb4b8b895

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3ac2c8b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 3ac2c8b7496e8847ee5d63979c30a62d10581129

**Comment by livecode-vulcan** [comment]
😎 test success 3ac2c8b7496e8847ee5d63979c30a62d10581129

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/683)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/683)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/681)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/682)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/687)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/679)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/679)

**Pull request merged**
