### PR TITLE
Replace references to quality.runrev.com

### PR DESCRIPTION
**Pull request by peter-b**
BugZilla is now at http://quality.livecode.com/.

### CODE REVIEW

**Comment by peter-b** [comment]
See also #3210.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 497f4fc

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 497f4fc877858c861ee27146af05f91972d1cf36

**Comment by livecode-vulcan** [comment]
😎 test success 497f4fc877858c861ee27146af05f91972d1cf36
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1064)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1073)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1061)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1066)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1077)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1082)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1082)

**Pull request merged**
