### PR TITLE
[[Docs]] this - use variable convention

### PR DESCRIPTION
**Pull request by seaniepie**
- variable currentName changed to tCurrentName to follow naming conventions

### CODE REVIEW

**Comment by livecodeali** [comment]
@seaniepie Could you also declare the variable please?

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 06dbcf2

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 06dbcf211e6d84dae4e64b30193ef2c7f591d895

**Comment by livecode-vulcan** [comment]
😎 test success 06dbcf211e6d84dae4e64b30193ef2c7f591d895
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/428)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/433)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/428)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/428)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/434)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/428)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/428)

**Pull request merged**
