### PR TITLE
[[ Bug 18273 ]] Prevent crash when rendering card with invalid objptr

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 0a86654

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 0a86654535b7257d2eb7ba3675c4935f449931ac

**Comment by livecode-vulcan** [comment]
😞 test failure 0a86654535b7257d2eb7ba3675c4935f449931ac

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1128)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1130)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1123)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1129)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1133)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1143)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1124)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 0a86654

**Comment by livecode-vulcan** [comment]
😎 test success 0a86654535b7257d2eb7ba3675c4935f449931ac

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1129)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1131)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1124)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1130)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1134)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1144)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1125)

**Pull request merged**
