### PR TITLE
json: Massively expanded test suite, fixes, and bump to 2.0.0

### PR DESCRIPTION
**Pull request by peter-b**
This pull request:
- corrects several incorrect behaviours in `JsonImport()`
- vendors a JSON test suite from nst/JSONTestSuite
- bumps the JSON library version to 2.0.0

See commit messages for (much) more detailed explanations.

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok a910eea

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok a910eea68dd12252142a4ac3032c5ee4eb4b1ac7

**Comment by livecode-vulcan** [comment]
😞 test failure a910eea68dd12252142a4ac3032c5ee4eb4b1ac7
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/506)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/511)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/506)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/508)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/513)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/506)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/507)

**Comment by peter-b** [comment]
@livecode-vulcan retry a910eea

**Comment by livecode-vulcan** [comment]
😞 test failure a910eea68dd12252142a4ac3032c5ee4eb4b1ac7
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/520)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/525)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/520)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/524)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/529)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/521)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/521)

**Comment by peter-b** [comment]
@montegoulding I added an extra couple of bugfixes to this PR -- do you mind re-reviewing, please?

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 1c8e5cd

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 1c8e5cdb1b66704437829338b38b9887135c911d

**Comment by livecode-vulcan** [comment]
😎 test success 1c8e5cdb1b66704437829338b38b9887135c911d
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/556)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/561)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/556)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/560)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/565)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/557)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/557)

**Pull request merged**
