### PR TITLE
[Bug 19469] Pad the 'hour' with 0 in 24-hour time format

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodepanos : I suggest using dateItems for the test.
```
put ... into tDateItems
convert tDateItems to the long time
... check that the string is precisely as expected ...
```
Then construct the string to test against against something derived from the dateItmes explicitly.

(Apart from anything else, there's a local time issue here - using dateItems means there are no DST related shifts)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 923ba3b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 923ba3b37ec3be5f84e708a76de611b1cf07d9f8

**Comment by livecode-vulcan** [comment]
😎 test success 923ba3b37ec3be5f84e708a76de611b1cf07d9f8

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/16)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/15)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2)
* try-community-universal-ios-iphoneos10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.2/builds/20)
* try-community-universal-ios-iphonesimulator10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.2/builds/20)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/14)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/16)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/18)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/20)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/18)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/20)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/20)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/19)

**Pull request merged**
