### PR TITLE
[[ Bug 15433 ]] MCEngineExecLog should print directly to stderr on server

### PR DESCRIPTION
**Pull request by livecodestephen**

### CODE REVIEW

**Comment by peter-b** [comment]
Hi Stephen,

Please explicitly encode to an appropriate encoding (e.g. `native`) rather than using `MCStringGetCString()`.  This is because `MCStringGetCString()` changes the representation of the string it is called for, which can cause data loss. The function will be removed soon because of this misfeature -- using it is (almost) never correct!

@livecode-vulcan review not ok 8f8654c

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 8f8654cebd4d417e43d7fc08629b2f56836c97a2

**Comment by runrevmark** [comment]
For reference - https://github.com/runrev/livecode/pull/2322 - it uses an UTF8String lock to convert before doing MCS_write.

**Comment by livecodestephen** [comment]
Should this be UTF8 encoded or something else?  (Was #2322 correct to use utf8 rather than native?)

**Comment by runrevmark** [comment]
UTF-8 seemed to be the best option as you are outputting to the console error stream... Which is distinct from stdout in terms of configuration.

**Comment by runrevmark** [comment]
On reflection - I wonder if SysString is actually the correct abstraction here (and in my PR for IO_printf)...

Although I'm not sure whether SysString is defined on Windows?

**Comment by runrevmark** [comment]
Right - so - after a brief chat with @peter-b offline - we _think_ the following is correct...

AsSysString should be used when generating strings which are being written to a stream defined by outside the LC environment - so stderr seems to be a good example of where.

I'll take a look at the SysString imp on Windows to make sure it 'does the right thing' with regards encoding to the CodePage of the output stream (it seems you can ask the console handles for this!).

**Comment by livecodestephen** [comment]
I've rebased on develop now that #2327 has been merged and switched to using MCAutoStringRefAsSysString

**Comment by runrevmark** [comment]
@livecode-vulcan review ok fcd5336

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok fcd53364f64e2f48162b19f31fc0d8a8c88f0c1b

**Pull request merged**
