### PR TITLE
Merge 7.0.6 rc 1

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Only one merge conflict here, and it was in whitespace.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3fd5d60

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3fd5d60ccf04abcc30bc527cfe4b7953a3063e41

**Comment by livecode-vulcan** [comment]
😞 test failure 3fd5d60ccf04abcc30bc527cfe4b7953a3063e41
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/138)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/203)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/91)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/148)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/84)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/88)

**Pull request merged**
