### PR TITLE
Update version for 8.1.0-gm-1

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 2511555

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 2511555c49eccb81242fd2ccb5cc4cb25785e188

**Comment by livecode-vulcan** [comment]
😞 test failure 2511555c49eccb81242fd2ccb5cc4cb25785e188
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/151)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/155)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/151)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/151)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/151)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/151)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/151)

**Comment by peter-b** [comment]
@livecode-vulcan retry 2511555

**Comment by peter-b** [comment]
@livecode-vulcan retry 2511555

**Comment by livecode-vulcan** [comment]
😎 test success 2511555c49eccb81242fd2ccb5cc4cb25785e188
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/155)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/159)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/155)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/155)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/159)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/155)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/155)

**Pull request merged**
