### PR TITLE
[Bug 17194] docs: Improve "file:" URL documentation and RFC xrefs

### PR DESCRIPTION
**Pull request by peter-b**
- Clarify the usage of `file:` scheme URLs/URIs somewhat
- Improve references to IETF RFC documents

### CODE REVIEW

**Comment by peter-b** [comment]
This also coincidentally fixes [bug 17119](http://quality.livecode.com/show_bug.cgi?id=17119).

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8e8e4b9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8e8e4b9f252cb25e5c43735ec0b90317e2544538

**Comment by livecode-vulcan** [comment]
😞 test failure 8e8e4b9f252cb25e5c43735ec0b90317e2544538
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2237)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2245)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2230)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2246)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/2252)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2257)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2268)

**Comment by peter-b** [comment]
Merging despite build failures because changes are unrelated to build failures.

**Pull request merged**
