### PR TITLE
[[ Bug 19036 ]] Fix incorrect local file path when setting url of browser widget on Android

### PR DESCRIPTION
**Pull request by HedgeHao**
Bug says local asset files cannot loaded into browser widget on Android. This is due to wrong file path pass to browser and this patch fix it.

### CODE REVIEW

**Comment by livecodefraser** [comment]
Hi,

Thanks for the contribution. Looks good to me except the naming of the bugfix note - it should have a .md extension so that the release notes builder can find it.

**Comment by HedgeHao** [comment]
@livecodefraser Just changed release note file name.

**Comment by livecodefraser** [comment]
Thanks!

@livecode-vulcan review okay 85e76bd

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 85e76bd73f620e12fdc2f2ae3ecc6e1e1b253211

**Comment by livecode-vulcan** [comment]
😎 test success 85e76bd73f620e12fdc2f2ae3ecc6e1e1b253211

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/791)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/796)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/789)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/790)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/796)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/788)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/788)

**Pull request merged**
