### PR TITLE
[[ Bug 14706 ]] Add beta testing entitlements for iOS applications

### PR DESCRIPTION
**Pull request by livecodesebastien**
The iOS standalone settings "ios,beta version" have been added

### CODE REVIEW

**Comment by livecodesebastien** [comment]
This comes as an answer to the bug 14706

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 4420fda

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 4420fda6fc98fa1c8bb990c374f350a860bad567

**Comment by livecode-vulcan** [comment]
😎 test success 4420fda6fc98fa1c8bb990c374f350a860bad567
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/327)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/327)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/326)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/325)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/330)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/322)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/333)

**Comment by livecodepanos** [comment]
I created an iOS standalone from this branch to test AppStore submission and use of TestFlight. Unfortunately, TestFlight is still not available, since "To use TestFlight Beta Testing, build 1.0.1 must contain the correct beta entitlement"

I think the problem here is that `<key>beta-reports-active</key>`etc should be placed in rsrc/template-store-entitlements.xcent instead of rsrc/mobile-(device-)template.plist

**Comment by livecodepanos** [comment]
Ok, I moved `<key>beta-reports-active</key>` etc in rsrc/template-(store-)entitlements.xcent and modified stack revsaveasiosstandalone to comply with this change.Then I built two standalones:
- one _with_ the beta-testing checkbox checked
- one _without_ the beta-testing checkbox checked

I successfully uploaded the first one to iTunes Connect using Application Loader. The binary appears in the correct place under the "Prerelease" section, and I no longer see the previous error (_"To use TestFlight Beta Testing, build 1.0.1 must contain the correct beta entitlement"_). Moreover, I enabled 'TestFlight Beta Testing' in the store pane, and immediately received an email in my tester's account inviting me to test the current app (as an internal tester). 

Then I tried to upload the second one. Application Loader throws the following error:

_ERROR ITMS-90046: “Invalid Code Signing Entitlements: Your application bundle’s signature contains code signing entitlements that are not supported on iOS. Specifically, value ‘false’ for key ‘beta-reports-active’ in Payload/sheepHerderVector.app/sheepHerderVector’ is not supported._

So I think we should just add `<key>beta-reports-active</key> <true/>` in rsrc/template-(store-)entitlements.xcent, and discard the changes in the IDE (i.e no beta-testing checkbox is needed), since this key cannot be 'false'.

**Comment by livecodesebastien** [comment]
Hey Panos, thanks for testing all of this - you more or less spotted the issues where I suppose they could come. I'll update the pull request.
@livecode-vulcan review not ok 959afd1

**Comment by livecodesebastien** [comment]
Pull request updated.
@livecodepanos: Can you check again this PR and review it accordingly? Thanks

**Comment by livecodepanos** [comment]
@livecodesebastien: Sure, I'll do it now :)

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok  dbd7966

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok dbd79669b3508705ddc77e4d5d63cf86b902ecda

**Comment by peter-b** [comment]
@livecode-vulcan review by @livecodepanos ok dbd7966

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok dbd79669b3508705ddc77e4d5d63cf86b902ecda

**Comment by livecode-vulcan** [comment]
😎 test success dbd79669b3508705ddc77e4d5d63cf86b902ecda
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/404)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/404)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/403)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/402)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/408)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/399)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/410)

**Pull request merged**
