### PR TITLE
[Tests] Add basic overview of test system

### PR DESCRIPTION
**Pull request by peter-b**
Give info on the test suites available, how to run them, and how to
write new tests.

### CODE REVIEW

**Comment by runrevmark** [comment]
@mwieder: Regarding splitting up tests into separate files - then perhaps - interface-<object>-props would be a good name for the tests on properties of each object? Ideally we want to keep tests related to each object type together, rather than cross-cut. e.g.

interface-field-props.livecodescript
interface-button-props.livecodescript

**Comment by livecodeali** [comment]
Plus those correspond to exec-interface-field.cpp and exec-interface-button.cpp in the engine.

**Comment by livecodeali** [comment]
Haha, so that's why the sentence was incomplete

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 35b212c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 35b212ccf6e870e9519440eeefa30680e9a02ba7

**Comment by livecode-vulcan** [comment]
😎 test success 35b212ccf6e870e9519440eeefa30680e9a02ba7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/923)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/931)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/920)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/924)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/933)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/942)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/937)

**Comment by stephentawn** [comment]
@peter-b: Did you miss the Google Test docs, there's plenty! https://github.com/google/googletest/blob/master/googletest/docs/

There's a list available [assertions](https://github.com/google/googletest/blob/master/googletest/docs/Primer.md#assertions), a description of how to write [simple tests](https://github.com/google/googletest/blob/master/googletest/docs/Primer.md#simple-tests), and if you've got common data, or setup and tear down functions, for several tests you can put the common code into a class and use a [fixture test](https://github.com/google/googletest/blob/master/googletest/docs/Primer.md#test-fixtures-using-the-same-data-configuration-for-multiple-tests).  There's also an [advanced guide](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md).

**Pull request merged**
