### PR TITLE
iOS 9.2 support (for develop-7.0)

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodepanos Please update `docs/notes/platforms.md`.

Also, do we need to continue to provide Xcode 7.1 / iPhoneOs 9.1 support?

**Comment by livecodepanos** [comment]
I guess that we will stop supporting Xcode 7.1 / iPhoneOs 9.1 once support for Xcode 7.2 / iPhoneOs 9.2 is released

**Comment by peter-b** [comment]
@livecode-vulcan review ok ca34a44

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ca34a44ef49914df834bbb1e96cd95561c490ef0

**Comment by livecode-vulcan** [comment]
😞 test failure ca34a44ef49914df834bbb1e96cd95561c490ef0
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1586)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1605)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1582)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1593)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1605)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1607)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1609)

**Comment by peter-b** [comment]
@livecode-vulcan retry ca34a44

**Comment by livecode-vulcan** [comment]
😞 test failure ca34a44ef49914df834bbb1e96cd95561c490ef0
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1587)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1606)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1583)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1594)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1606)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1608)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1610)

**Comment by peter-b** [comment]
@livecode-vulcan retry ca34a44

**Comment by livecode-vulcan** [comment]
😎 test success ca34a44ef49914df834bbb1e96cd95561c490ef0
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1588)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1607)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1584)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1595)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1608)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1609)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1611)

**Pull request merged**
