### PR TITLE
[Bug 15560]  'crop' fails when image reference is relative

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok a70d11d

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok a70d11d33b3c4c1d304ec1d4e5dabb0b859a5543

**Comment by livecode-vulcan** [comment]
😎 test success a70d11d33b3c4c1d304ec1d4e5dabb0b859a5543
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/4)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/4)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/4)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/4)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/4)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/4)

**Comment by livecodeali** [comment]
While you're doing these @runrevpanos, http://quality.runrev.com/show_bug.cgi?id=1751 is the same but for the flip command.
:+1: for more sensible parsing :smile:

**Comment by livecodepanos** [comment]
Thanks @livecodeali for discovering this :)

**Comment by runrevmark** [comment]
This command suffers the same problem as 'rotate'. The syntax is 'crop IMG [to] EXPR' or 'crop [to] EXPR'.

**Comment by peter-b** [comment]
@livecode-vulcan review by @runrevmark not ok a70d11d

**Comment by livecode-vulcan** [comment]
💔 review by @runrevmark not ok a70d11d33b3c4c1d304ec1d4e5dabb0b859a5543

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevpanos, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodefraser** [comment]
Closing as this fix causes parsing ambiguities.

**Pull request closed without merging**
