### PR TITLE
[emscripten] Log undefined symbols during whitelist generation

### PR DESCRIPTION
**Pull request by peter-b**
Since we call **emcc** with `-sLINKABLE=1`, it doesn't warn when
symbols are undefined.  However, we can do it ourselves by examining
the symbols in the LLVM bitcode file -- which we do anyway while
generating the Emterpreter whitelist and blacklist.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok b8d9317

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok b8d9317bbc72cf88905d70cb63a938546982fe96

**Comment by livecode-vulcan** [comment]
😞 test failure b8d9317bbc72cf88905d70cb63a938546982fe96
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1678)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1694)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1673)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1684)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1695)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1697)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1702)

**Comment by peter-b** [comment]
@runrevmark Pull request updated

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 90cdfa8

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 90cdfa8126ad25f058a9d20f952e9a26e8697a52

**Comment by livecode-vulcan** [comment]
😎 test success 90cdfa8126ad25f058a9d20f952e9a26e8697a52
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1701)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1717)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1696)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1707)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1718)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1720)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1725)

**Pull request merged**
