### PR TITLE
[[ Bugfix 18231 ]]  Fixed doc formatting issues for binaryEncode and …

### PR DESCRIPTION
**Pull request by PaulMcClernan**
Fixed doc formatting issues for binaryEncode and binaryDecode:
https://github.com/livecode/livecode/pull/4647

### CODE REVIEW

**Comment by livecodeali** [comment]
@PaulMcClernan Didn't see this before I commented on the other pull request!

I think the easiest thing here to get all the changes in one pull request would be if you copied the full modified text of the two encode files from https://github.com/PaulMcClernan/livecode/blob/f32c2a9029fa827893f6d5e096e178f74185e733/docs/dictionary/function/binaryDecode.lcdoc and https://github.com/PaulMcClernan/livecode/blob/f32c2a9029fa827893f6d5e096e178f74185e733/docs/dictionary/function/binaryEncode.lcdoc

and modify the versions of those files on this branch (patch-4) https://github.com/PaulMcClernan/livecode/blob/patch-4/docs/dictionary/function/binaryDecode.lcdoc
and 
https://github.com/PaulMcClernan/livecode/blob/patch-4/docs/dictionary/function/binaryEncode.lcdoc

by pasting the new versions in. Does that make sense?

**Comment by PaulMcClernan** [comment]
OK, I did that, but Peter B. Marked the other pull request to merge with 9.0dp1, does that matter?

**Comment by livecodeali** [comment]
@PaulMcClernan No that's fine. Sorry to be a pain but could you rename the bugfix note file so that it has a lower case b at the beginning? I just noticed. I have a feeling it will cause problems that way...

**Comment by PaulMcClernan** [comment]
No apologies necessary, just want to help if I can so you guys have more time to work on the really good stuff!

**Comment by livecodeali** [comment]
@PaulMcClernan We need to get rid of that last commit from this pull request somehow...

**Comment by PaulMcClernan** [comment]
@livecodeali You mean the commit for "undo" that I meant to go with "redo" patch-5?
I can't figure out how to do that with the web GUI (though revert was supposedly added in 2014). I just downloaded the GitHub Desktop app but don't have time to set it up and figure it out right now, I sent a request to add you as a collaborator. Why does it need to be removed?

**Comment by livecodeali** [comment]
@PaulMcClernan Because it's not relevant to this pull request and will cause a merge conflict between this and the actual PR that it should be in.

Revert exists in the GitHub web UI for entire pull requests only, not individual commits.

One way we could achieve this actually is if you add another commit to this PR that restores the undo file to its former state, and then we could squash the commits on merge and then there shouldn't be a conflict.

I can do it fairly easily though, if the collaborator thing works!

**Comment by livecodeali** [comment]
@PaulMcClernan There we go... I've removed that commit and combined all the others into the original one (not strictly necessary but it's nice and neat this way!)

**Comment by peter-b** [comment]
Thanks for sorting out that mess, @PaulMcClernan & @livecodeali!

@livecode-vulcan review ok 669db81

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 669db8198279338ee8837f6b2d2c64774874a4b7

**Comment by livecode-vulcan** [comment]
😎 test success 669db8198279338ee8837f6b2d2c64774874a4b7
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/441)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/446)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/441)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/441)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/447)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/441)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/441)

**Pull request merged**
