### PR TITLE
[[ Bug 9820 ]] Discard additional, erroneous parameters added for the…

### PR DESCRIPTION
**Pull request by livecodesebastien**
… content-type application/x-www-form-urlencoded

### CODE REVIEW

**Comment by peter-b** [comment]
I'm not sure it's sufficient to check that the content type starts with `application/x-www-form-urlencoded`, because it will also match `application/x-www-form-urlencoded-myspecialsuffix`.

I think that you need to check that `application/x-www-form-urlencoded` is followed either by end-of-line or a separator.

**Comment by livecodesebastien** [comment]
PR updated.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 64f4fa3

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 64f4fa3c7eceb880eac6271f0bf7d834f12bd432

**Pull request merged**
