### PR TITLE
[[ Bug 18010 ]] Add optional 'kind' parameter to files/folders

### PR DESCRIPTION
**Pull request by runrevmark**
This patch unifies the implementation of files() and folders()
and adds an optional second parameter 'kind'. The kind parameter
can be empty or "detailed". If it is detailed then the 'detailed'
variant of the request is made, otherwise the normal variant
is made.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok a2273b3

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a2273b3cd4a9a5840965f575a9f2b0cee91a1e78

**Comment by livecode-vulcan** [comment]
😞 test failure a2273b3cd4a9a5840965f575a9f2b0cee91a1e78

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1041)
* try-community-armv6-android-api9: [error](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1057)
* try-community-js-emscripten-sdk1.35: [error](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1031)
* try-community-universal-ios-iphoneos11.1: [error](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.1/builds/104)
* try-community-universal-ios-iphonesimulator11.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.1/builds/104)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1036)
* try-community-universal-mac-macosx10.9: [error](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1058)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1041)
* try-community-x86-linux-debian8: [error](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1057)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1040)
* try-community-x86_64-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1050)
* try-community-x86-win32: [error](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1073)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1036)

**Comment by livecodeali** [comment]
@livecode-vulcan retry a2273b3

**Comment by livecode-vulcan** [comment]
😎 test success a2273b3cd4a9a5840965f575a9f2b0cee91a1e78

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1044)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1060)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1034)
* try-community-universal-ios-iphoneos11.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.1/builds/107)
* try-community-universal-ios-iphonesimulator11.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.1/builds/107)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1039)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1061)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1044)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1060)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1043)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1053)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1076)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1039)

**Pull request merged**
