### PR TITLE
[Bugfix-22596] Include Android in playLoudness docs

### PR DESCRIPTION
**Pull request by livecodealice**
Included Android as a supported platform in the playLoudness dictionary entry

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 62cbb32

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 62cbb322833ea499e9acc0dace20689f40b822c9

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 62cbb32

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 62cbb32

**Comment by livecode-vulcan** [comment]
😎 test success 62cbb322833ea499e9acc0dace20689f40b822c9

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/752)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/161)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/161)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/161)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/161)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2278)
* try-community-universal-ios-iphoneos13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.4/builds/12)
* try-community-universal-ios-iphonesimulator13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.4/builds/12)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2307)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2294)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2293)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2328)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2268)

**Pull request merged**
