### PR TITLE
[[ Bug 17698 ]] Fix windows player frame seeking

### PR DESCRIPTION
**Pull request by livecodeian**
Depends on PR https://github.com/livecode/livecode/pull/4064

### CODE REVIEW

**Comment by livecodefraser** [comment]
This looks reasonable, but I'll wait until the dependency is merged before reviewing properly - too many changes going on simultaneously before then.

**Comment by livecodefraser** [comment]
Hmm, GitHub seems a little confused... the dependent PR has been merged, but the dependent commits are still shown in the history. I'm also a little concerned about it reporting that the PR removes 3,000 lines (while only adding 350 or so)... could you maybe merge develop into your branch and re-push?

**Comment by livecodeian** [comment]
@livecodefraser that seems to have fixed it :)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 64f4349

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 64f43494132f897991eaaee7c8791ff8c419622c

**Comment by livecode-vulcan** [comment]
😎 test success 64f43494132f897991eaaee7c8791ff8c419622c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2608)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2618)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2603)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2619)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2625)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2631)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2643)

**Pull request merged**
