### PR TITLE
[Bug 14809] LCB: Remove deprecated type names.

### PR DESCRIPTION
**Pull request by peter-b**

### CODE REVIEW

**Comment by peter-b** [comment]
Requires a release note.

**Comment by peter-b** [comment]
@livecode-vulcan review ok dfccf10

**Comment by livecodefraser** [comment]
@livecode-vulcan review ok dfccf10

**Comment by livecodefraser** [comment]
@livecode-vulcan review ok abcdef0

**Comment by peter-b** [comment]
@livecode-vulcan assign reviewer @runrevmark

**Comment by peter-b** [comment]
@livecode-vulcan review by @runrevmark ok 4f7c978

**Comment by livecode-vulcan** [comment]
:sparkling_heart: review by @runrevmark ok 4f7c978751d937d70f5fc1b44acce834c00e62da

**Comment by livecode-vulcan** [comment]
:sparkling_heart: review by @runrevmark ok 4f7c978751d937d70f5fc1b44acce834c00e62da

**Comment by peter-b** [comment]
Delaying to 8.0.0-dp-4 as discussed with @runrevmark

**Comment by livecode-vulcan** [comment]
😞 test failure 4f7c978751d937d70f5fc1b44acce834c00e62da
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/136)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/201)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/89)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/146)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/82)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/86)

**Comment by peter-b** [comment]
@livecode-vulcan try 4f7c978

**Comment by livecode-vulcan** [comment]
😎 test success 4f7c978751d937d70f5fc1b44acce834c00e62da
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/236)
- try-win-x86: unknown\* try-ios: unknown\* try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/247)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/182)
- try-mac: unknown

**Comment by peter-b** [comment]
@livecode-vulcan try 4f7c978

**Comment by livecode-vulcan** [comment]
😎 test success 4f7c978751d937d70f5fc1b44acce834c00e62da
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/238)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/301)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/190)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/249)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/184)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/183)

**Comment by peter-b** [comment]
@livecode-vulcan retry 4f7c978

**Comment by livecode-vulcan** [comment]
😞 test failure 4f7c978751d937d70f5fc1b44acce834c00e62da
- try-linux-x86: [failure](https://vulcan.livecode.com/builders/try-linux-x86/builds/281)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/344)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/227)
- try-android-armv6: [failure](https://vulcan.livecode.com/builders/try-android-armv6/builds/292)
- try-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/227)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/219)

**Comment by livecodefraser** [comment]
The most interesting thing about this is that MSBuild didn't interpret the failure to build the extensions as a compilation error...

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 962e72c

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 4f7c978

It helps when I use the correct commit hash...

**Comment by livecode-vulcan** [comment]
😎 test success 4f7c978751d937d70f5fc1b44acce834c00e62da
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/276)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/274)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/275)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/274)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/279)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/271)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/282)

**Pull request merged**
