### PR TITLE
[[ Bug 22279 ]] Fix browser widget showing blank page after set htmltext

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecodeian Could you please rebase this against `develop-9.5` branch?

**Comment by runrevmark** [comment]
@livecodeian Could you rebase this against develop, please :D

**Comment by runrevmark** [comment]
Ping ^^^ @livecodeian :)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok fa3e90e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok fa3e90e517a274619e81ca156d8f975234dd4dce

**Comment by livecode-vulcan** [comment]
😎 test success fa3e90e517a274619e81ca156d8f975234dd4dce

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/692)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/101)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/101)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/101)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/101)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2218)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/52)
* try-community-universal-ios-iphonesimulator13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/52)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2247)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2234)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2233)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2267)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2207)

**Pull request merged**
