### PR TITLE
[[ Bug 18364 ]] Only send standalone saving messages once

### PR DESCRIPTION
**Pull request by livecodeali**
Move the code that sends these messages outside the platform repeat loop.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok a84c907

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok a84c907044eda3eb0cb1aa0387be1af55135faf2

**Comment by montegoulding** [comment]
@livecodeali are the mobile messages impacted by this issue also?

**Comment by livecodeali** [comment]
@montegoulding That's a good point... when are they meant to be sent?

**Comment by livecodeali** [comment]
They shouldn't really be separate messages anymore should they. Maybe we want to deprecate the mobile version and make it 
`savingStandalone pPlatformList`
and 
`standaloneSaved pFolder, pPlatformList`

**Comment by livecode-vulcan** [comment]
😎 test success a84c907044eda3eb0cb1aa0387be1af55135faf2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/167)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/171)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/167)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/167)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/171)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/167)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/167)

**Comment by montegoulding** [comment]
Nice if savingStandalone could also have a mutable settings parameter too

**Comment by peter-b** [comment]
@livecode-vulcan review ok 8313d82

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 8313d825f3cc886c7a20b1576fdefa08c737bf06

**Comment by livecode-vulcan** [comment]
😎 test success 8313d825f3cc886c7a20b1576fdefa08c737bf06
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/168)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/172)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/168)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/168)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/172)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/168)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/168)

**Pull request merged**
