### PR TITLE
Improvements to Linux installation location.

### PR DESCRIPTION
**Pull request by peter-b**
We are not called RunRev any more.

This changes the installer stack to install to /opt/livecode by default, and updates the release notes' setup instructions accordingly.  It also removes shell special characters from the default installation path.

### CODE REVIEW

**Comment by livecodeian** [comment]
This PR doesn't seem to have any changes removing special chars - have these commits been merged elsewhere?

**Comment by peter-b** [comment]
@livecodeian The removal of special characters is in the changes to the binary `Installer.rev` stack in 912de8e.

**Comment by livecodeian** [comment]
Ah, those pesky binary blobs!

**Comment by livecodeian** [comment]
@livecode-vulcan review ok 912de8e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeian ok 912de8e002533899c243a984ab8493d1321c0d68

**Comment by livecode-vulcan** [comment]
😎 test success 912de8e002533899c243a984ab8493d1321c0d68
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1156)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1167)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1153)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1159)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1171)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1173)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1175)

**Pull request merged**
