### PR TITLE
[[ iOS SDK Version ]] Place all the iOS SDK versions to change for an Xc...

### PR DESCRIPTION
**Pull request by livecodesebastien**
...ode update in one place: revdeploylibraryios.rev

### CODE REVIEW

**Comment by runrevmark** [comment]
Reviewed-by: @runrevmark.

**Comment by peter-b** [comment]
@livecode-vulcan review by @runrevmark ok 4ce1427

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 4ce14273a746330baeea2015370b2bc31303282d

**Comment by livecodesebastien** [comment]
Both Android and iOS SDK update were modifying revstandalonesettings.rev - the former has been merged in the latter, so that we can merge the Android update before Xcode 6.4 goes out (without merge conflicts for revstandalonesettings).
See https://github.com/runrev/livecode-ide/pull/199

**Comment by runrevmark** [comment]
@livecode-vulcan review ok ae58191

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok ae5819192283119ae48cbb0be61a012bb9d337a3

**Pull request merged**
