### PR TITLE
[[ Bug 15302 ]] Fix "occured"

### PR DESCRIPTION
**Pull request by bwmilby**
Correct the spelling error of "occured" to "occurred".  Most of the corrections were in comments.  A few were in strings.  6 changes were to actual code, but were self contained within each function (engine\src\mac-menu.mm and engine\src\opensslsocket.cpp).

7 changes to stack script of engine\src\Environment.rev - all were comments or strings.

2 changes in toolchain/gentle/gentle (int ErrorOccured / extern int ErrorOccured)

Did not fix error in revcapture.h since ErrorOccured(void) is part of a struct (MCCaptureSessionDelegate) and could not be certain it wasn't referenced somewhere else.

### CODE REVIEW

**Comment by montegoulding** [comment]
Hi @bwmilby thanks for this. `engine/src/Environment.rev` has recently been scriptified and most of the code is in script only behavior stacks now. I suggest dropping `29bd050` from this patch and then rebasing on the current upstream head of develop and those changes can then be made to the stack behavior script. I'm not sure how comfortable you are with git so I can talk you through it if you like. 

Essentially you need to do the following assuming you have develop setup to track upstream rather than your fork. If you haven't got that setup I can give you instructions for that too.

```
git checkout develop
git pull
git checkout bugfix-15302
git rebase -i develop
git push -f
```
When you rebase -i you will get a file pop up in your command line editor with with a list of your commits and you need to change `pick 29bd050` to `drop 29bd050`

**Comment by bwmilby** [comment]
I'm using SourceTree on Mac & PC, but both are set up to pull my fork's origin.  I was able to update the develop on my Mac and then rebase.  Will need to work on my local setup to keep it in sync.

**Comment by bwmilby** [comment]
Build is failing due to spelling error in /livecode/ide/tests/core/idelibrary/errors.livecodescript
https://github.com/livecode/livecode-ide/pull/1692

**Comment by runrevmark** [comment]
@montegoulding @livecodeali : Is this likely to cause conflicts in future when merging up develop-8.1? If so, would it be better to rebase back to develop-8.1?

**Comment by bwmilby** [comment]
Did a little digging trying to understand the build error.
_testlib.livecodescript builds the error mapping from the header file, so:
/livecode/ide/tests/core/idelibrary/errors.livecodescript and
/livecode/engine/src/executionerrors.h
must match EE-0863's description for the engine tests to pass.
One option is to change the test to use EE-0867.  That would allow the IDE change to take place and not interfere with any builds on the engine since 0867 isn't being changed.

**Comment by montegoulding** [comment]
@runrevmark it probably would be good to rebase it yes

@bwmilby Sourcetree is a handy git gui but it can be a little hard to use for more complicated things like interactive rebase. You should be able to add `https://github.com/livecode/livecode.git` as an `upstream` remote and then set `develop` and `develop-8.1` to track it instead of `origin`. I'm pretty sure there's a good UI for doing that in sourcetree but I can give you command line instructions if you like. As far as rebasing this patch onto `develop-8.1` that may well be impossible in Sourcetree (I'm not sure). The command line is:
```
git checkout bugfix-15302
git rebase --onto=develop-8.1 develop
git push -f
```
PS it could be that this patch touches files that have changed significantly between 8.1 and 9 in which case the above will leave you in a mess and you may need to `git rebase --abort`

**Comment by bwmilby** [comment]
Rebase completed.  3 files do not exist in develop-8.1 branch and will need to be fixed in develop:
- extensions/script-libraries/semver/semver.livecodescript
- extensions/script-libraries/oauth2/oauth2.livecodescript
- docs/dictionary/property/scriptExecutionErrors.lcdoc

One of the additions to executionerrors.h in develop contains the error as well (EE-0897).  Build still fails due to change to the EE-0863 comment.

Added a new branch to my fork with these changes (bugfix-15302.1) that does not include any of the the ones in this PR.

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 2e5fc54

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 2e5fc544079c01649c7572b87f8e875a82c12dcd

**Comment by livecode-vulcan** [comment]
😎 test success 2e5fc544079c01649c7572b87f8e875a82c12dcd

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/523)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/538)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/512)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/455)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/458)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/518)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/526)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/521)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/538)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/521)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/531)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/553)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/516)

**Pull request merged**
