### PR TITLE
Modify "open elevated process" to use "pkexec" on Linux.

### PR DESCRIPTION
**Pull request by peter-b**
Most modern Linux distributions no longer install "gksu" by default.
Instead, running commands with root privileges is performed via polkit
[1].  The recommended way to communicate with polkit is over DBus, but
we don't currently have any access to DBus, so instead the `pkexec`
tool can be used.

This patch simplifies Linux elevated process creation to simply
prepending `pkexec --disable-internal-agent` to the command to be run,
and removes all of the previous Linux elevated process infrastructure.

[1] https://www.freedesktop.org/wiki/Software/polkit/

### CODE REVIEW

**Comment by peter-b** [comment]
This patch is currently marked as "WIP" because I need @runrevmark to explain why removing all the existing infrastructure surrounding `gksu` is a horrible idea which will break everything.

**Comment by mwieder** [comment]
Thanks so much for this! I await further discussion on this topic with bated breath.

**Comment by runrevmark** [comment]
@peter-b: The infrastructure for 'elevated process' was needed because gksu did not pass on the stdin/stdout/stderr file descriptors so a separate mechanism needed to be used to connect them to the (elevated) child process. As long as the replacement works on all the linux distros we support then there's no problem updating it - pkexec is a lot newer than gksu. A good test is the installer - if that can install for 'everyone' on linux and you get appropriate status feedback whilst installation is happening - then the feature is working :)

**Comment by angerangel** [comment]
Hi, 
this patch now is mandatory, because Ubuntu removed gksu for security reason and there is no way to use or install it anymore.
You HAVE TO use pkexec instead of gksu.

**Pull request closed without merging**
