### PR TITLE
Spelling Fixes

### PR DESCRIPTION
**Pull request by PaulMcClernan**

### CODE REVIEW

**Comment by livecodepanos** [comment]
Hello @PaulMcClernan, thank you for the contribution. 

The PR should be submitted against `develop-9.6` branch. I tried to rebase it using github's web interface but this was not possible, since this branch was branched off `develop` in the first place.

So I think in this case the easiest way forward would be to submit a new PR against `develop-9.6` (remember to branch off `develop-9.6`), and ideally you can put all your changes in one commit.

**Comment by PaulMcClernan** [comment]
> The PR should be submitted against `develop-9.6` branch. I tried to rebase it using github's web interface but this was not possible, since this branch was branched off `develop` in the first place.

It seems that I was able to change the base, so hopefully that's good enough, if not then I'll make new PRs for these.

**Comment by PaulMcClernan** [comment]
Hmm, something looks weird about this now, it now lists a bunch of commits from back in June along with mine.

**Comment by PaulMcClernan** [comment]
OK, I'm just going to close this and redo it later tonight

**Comment by mwieder** [comment]
@PaulMcClernan I had the same problem with one of my PRs. I'm not sure what happened with the git commit tree, but I eventually stashed my changes, reset the head back to before the problem point, pulled from the livecode repo again, and popped the stash. It's mostly fixed in my repo except for an IDE submodule commit that I can't seem to rebase away. Good luck with the redo.

**Pull request closed without merging**
