### PR TITLE
[[ Bug 18344 ]] Support iOS 10 in lclink.sh

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 8d8f4ca

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 8d8f4ca3ab41518cdb13a0f4f8308fa74b5ba627

**Comment by livecode-vulcan** [comment]
😎 test success 8d8f4ca3ab41518cdb13a0f4f8308fa74b5ba627
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/150)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/154)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/150)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/150)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/150)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/150)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/150)

**Comment by peter-b** [comment]
@livecode-vulcan review ok ae8e177

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ae8e177a62abf3b3a047e282ed13b26f632df639

**Comment by livecode-vulcan** [comment]
😞 test failure ae8e177a62abf3b3a047e282ed13b26f632df639
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/157)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/161)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/157)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/157)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/161)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/157)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/157)

**Comment by peter-b** [comment]
@livecode-vulcan retry ae8e177

**Comment by livecode-vulcan** [comment]
😎 test success ae8e177a62abf3b3a047e282ed13b26f632df639
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/160)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/164)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/160)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/160)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/164)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/160)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/160)

**Pull request merged**
