### PR TITLE
[[ Bug 15592 ]] Do not leave the buffer allocated for MCMacDesktop::S…

### PR DESCRIPTION
**Pull request by livecodesebastien**
…hell unfree'd

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Note that this pull request fixes a rather critical issue - and might be worth to merge it for 7.1.0 RC 1 (as it is a pretty safe fix).

**Comment by livecodeali** [comment]
@livecode-vulcan review ok edef7bf

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok edef7bf5a0af365851a18f08960ac8a914fd3004

**Comment by livecode-vulcan** [comment]
😎 test success edef7bf5a0af365851a18f08960ac8a914fd3004
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/540)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/599)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/489)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/553)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/485)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/478)

**Pull request merged**
