### PR TITLE
Feature: Add launchData param to "resume" message on Android

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecodeian** [comment]
Depends on #3040

**Comment by runrevmark** [comment]
@livecodeian: I've been pondering this... I wonder if a new parameter is actually needed to resume.

The key thing someone needs to know is if the intent has changed on resume - since an app needs explicit additions on the manifest for this to occur (I believe anyway?) could we just get away with leaving resume as it is - merging the other PR and then saying 'on resume on Android, the intent may have changed - you can refetch with the same syntax'.

If an app knows this, then it can store the 'current intent' (it is just an array after all), and then compare in resume to see if it has changed?

**Comment by livecodeian** [comment]
@runrevmark I don't believe that would work. If the app is brought to the foreground (without a request) that would also trigger a resume message, and if the app is launched twice in a row to handle the same intent (url share from a browser for instance) there would be no way of knowing as the Intent data wont' necessarily be unique.

**Comment by runrevmark** [comment]
Summary of discussion with @livecodeian, off-list:

It would be better to keep suspend / resume as they are (no extra parameter). Instead if a new intent is delivered just before resumption, the engine will send a 'launchDataChanged' message after resumption. This means there's no need for special code in 'resume' on android, an android app handling intents can do so by hooking into the launchDataChanged message instead, and then rechecking mobileGetLaunchData.

**Comment by livecodeian** [comment]
Closing this pull request to reimplement as #3046

**Pull request closed without merging**
