### PR TITLE
[[ Bug 18349 ]] Fix MCStringFindAndReplace used on non-mutable string

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeian Looks good.  Do you mind adding a regression test for this bug, please?

I wonder if it would make sense to add a new `MCStringFindAndReplaceCodepoint()` function, and deprecate (or preferably remove) the codepoint version of `MCStringFindAndReplaceChar()`.  What do you think?

**Comment by livecodeian** [comment]
The differentiation between char and codepoint isn't something i have a strong opinion on, but if you're saying the function name should more accurately reflect the type of input parameters then i can agree with that :)

**Comment by peter-b** [comment]
@livecode-vulcan review ok e76c96f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e76c96f743ee80725ddc57b199343b4138aa922b

**Comment by livecode-vulcan** [comment]
😎 test success e76c96f743ee80725ddc57b199343b4138aa922b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/304)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/309)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/304)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/304)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/310)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/304)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/304)

**Pull request merged**
