### PR TITLE
[[ Bug 19154  ]] Widget browser stuck on handling javascript

### PR DESCRIPTION
**Pull request by HedgeHao**

### CODE REVIEW

**Comment by HedgeHao** [comment]
From [Android WebView documentation](https://developer.android.com/guide/webapps/webview.html)

>  If you've set your targetSdkVersion to 17 or higher, you must add the @JavascriptInterface annotation to any method that you want available to your JavaScript (the method must also be public). If you do not provide the annotation, the method is not accessible by your web page when running on Android 4.2 or higher.

This bug caused by Android 4.2 (or higher) webview cannot execute Java method without @JavascriptInterface annotation. It just skip without exceptions and no result return to LC engine. But the engine will wait the execute result from browser for 30 seconds. The browser then hang for 30 seconds and cannot execute other JS commands.

**Comment by livecodeian** [comment]
@livecode-vulcan review ok 4613eaa

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeian ok 4613eaa3f37107defa37ee71d10d1471358fe1e0

**Comment by livecode-vulcan** [comment]
😎 test success 4613eaa3f37107defa37ee71d10d1471358fe1e0

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/912)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/918)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/910)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/911)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/918)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/909)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/909)

**Review by livecodeian — APPROVED** [review]
Looks good! I couldn't add the @JavascriptInterface tags at the time this was written as we were still using an older version of the Android SDK. Now we're using API 17 the tag is required to make the methods visible from JavaScript.

Thanks Josh!

**Comment by livecodeian** [comment]
@livecode-vulcan review ok 47078ef

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeian ok 47078efd44edcffe536fc21dbec67ca631ca7b3b

**Comment by livecode-vulcan** [comment]
😞 test failure 47078efd44edcffe536fc21dbec67ca631ca7b3b

* try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/919)
* try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/925)
* try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/917)
* try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/918)
* try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/925)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/917)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/916)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 47078ef

**Comment by livecode-vulcan** [comment]
😎 test success 47078efd44edcffe536fc21dbec67ca631ca7b3b

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/962)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/968)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/960)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/961)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/968)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/977)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/959)

**Pull request merged**
