### PR TITLE
[[ Bugfix 16306 ]] Fix font issues with PDF printing on Linux

### PR DESCRIPTION
**Pull request by livecodefraser**
We were using a Pango FontMap that was configured differently to
the one used by Cairo, which caused problems when laying out and
drawing text for the Cairo PDF surface.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok d71eff3

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d71eff34fe236e45bf9e87510353bf0e18e08cef

**Comment by livecode-vulcan** [comment]
💥 merge conflict d71eff34fe236e45bf9e87510353bf0e18e08cef → 605cb9b64a72074771bb0dfe0e5b287b0211eb9f

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 1ed6152

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 1ed6152e8b04e2af396d6af3b8b64113a5c7d85c

**Comment by livecode-vulcan** [comment]
😎 test success 1ed6152e8b04e2af396d6af3b8b64113a5c7d85c
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/915)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/923)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/912)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/916)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/925)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/934)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/929)

**Pull request merged**
