### PR TITLE
[[ BrowserWidget ]] Allow compilation with iOS SDK < v7.0

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok f73a183

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok f73a1836ba2e6b95cd5763f25708c97fbd15e0cd

**Comment by livecodeali** [comment]
I think you'll need to ifdef out the 

`#import <JavaScriptCore/JavaScriptCore.h>` 

for < 7.0 too

**Comment by livecode-vulcan** [comment]
😎 test success f73a1836ba2e6b95cd5763f25708c97fbd15e0cd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/901)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/910)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/899)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/902)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/911)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/921)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/915)

**Comment by livecodeian** [comment]
@livecodeali Yup, I've sorted that now. Thanks!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 0770486

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 077048673ce66bf0f5ca47afe44af1e2266e83a2

**Comment by livecode-vulcan** [comment]
😎 test success 077048673ce66bf0f5ca47afe44af1e2266e83a2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/902)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/911)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/900)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/903)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/912)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/922)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/916)

**Pull request merged**
