### PR TITLE
[Bug 11569] Scrolling a group crashes LiveCode when hiding scrollbar

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by runrevmark** [comment]
@runrevpanos: I don't think the problem here is with checking for whether hsb/vsb are nil. What's happening is that a mouseLeave handler is turning off the scrollbars when the CS_HSCROLL or CS_VSCROLL state is set on the control. The latter mean that 'the mouse is currently grabbed to one or other of the scrollbars' - which cannot be true if the scrollbars have been turned off. Thus I _think_ the bug is that CS_HSCROLL is not being unset when the hscrollBar of the group is set to false, and CS_VSCROLL is not being unset when the vscrollbar of the group is set to false.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 16770ed

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 16770edd678cf1dd352331f6db9f28b27024e8bf

**Comment by livecode-vulcan** [comment]
😎 test success 16770edd678cf1dd352331f6db9f28b27024e8bf
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/672)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/733)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/621)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/685)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/617)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/610)

**Pull request merged**
