### PR TITLE
Merge develop 8.0 18.05.16

### PR DESCRIPTION
**Pull request by livecodeali**
Conflicts:
        ide-support/revsaveasiosstandalone.livecodescript
        version

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 7c72596

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 7c725960168c089b0b641986d192444563392ad9

**Comment by livecode-vulcan** [comment]
😞 test failure 7c725960168c089b0b641986d192444563392ad9
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2505)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/2515)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2498)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2516)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2522)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2526)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2538)

**Comment by peter-b** [comment]
@livecode-vulcan retry 7c72596

**Comment by livecode-vulcan** [comment]
😎 test success 7c725960168c089b0b641986d192444563392ad9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2506)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2516)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2501)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2517)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2523)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2527)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2539)

**Pull request merged**
