### PR TITLE
Feature: new statistical functions as described on the engine forum

### PR DESCRIPTION
**Pull request by quartamsoftware**
Added new statistical functions:
- averageDeviation (aka: avgDev)
- geometcirMean
- harmonicMean
- populationStandardDeviation (aka: pStdDev)
- populationVariance (aka: pVariance)
- sampleVariance (aka: sVariance, variance)
  Added synonyms to existing functions:
- arithmeticMean, mean -> average
- sampleStandardDeviation, sStdDev -> stdDev

### CODE REVIEW

**Comment by runrevmark** [comment]
Hi Jan, thanks for these. A couple of things before I can pull it in...

We can't really have synonyms like 'pStdDev' or 'sVariance' or 'sStdDev' since they are the same as potential variable names (we've always said to avoid giving variable names english-like names, and thus we need to avoid giving tokens variable-like names). Maybe popStdDev, popVariance, sampVariance, and sampStdDev? (Assuming we really need the synonyms ;)).

Also, could you add a 'note' to the docs/notes folder describing the functions and what they do? This is part of our new 'automated release notes' generation system which we added last week. The files are in markdown. I'm going to pull this in as a branch 'feature-stats_functions', so the file should be 'docs/notes/feature-stats_functions.md'.

I can't see anything wrong with the code at first review, so with the above alterations I should be able to merge into 'develop'.

Thanks in advance,

Mark.

**Comment by quartamsoftware** [comment]
I revised the shorthand synonyms as requested; and caught some gremlins hiding in the cupboard; hopefully the release notes live up to the standards...

**Comment by runrevmark** [comment]
Hi Jan - thanks for this - now merged into 'develop'.

**Comment by runrevmark** [comment]
Hi Jan,

Could you add some dictionary entries for the new features?

They can be based on the stdDev one that already exists.

Both release notes and dictionary entries should really be part of the pull-request acceptance process for features, but I forgot about them initially (and when we first went open source, we hadn't integrated the dictionary!).

There are notes on writing dictionary entries here:

http://livecode.com/community/contribute-to-livecode/

Thanks!

Mark.

P.S. Add them to your branch and reopen this pull-request, I can then re-merge them in.

**Comment by quartamsoftware** [comment]
Hi Mark,
I added them to my branch, but I don't see a way to reopen the pull request.
Can you do anything at your end to reopen it, or do we need a separate pull request?
Jan.

**Comment by runrevmark** [comment]
Hi Jan,

That's fine, I can just pull in from your branch easily enough. Pull requests are just a notification system for the most part :)

Mark.

**Pull request merged**
