### PR TITLE
[[ Bug 14423 ]] Ensure that the codec names can be converted to MacRoman...

### PR DESCRIPTION
**Pull request by livecodesebastien**
... before duplicating the converted result

### CODE REVIEW

**Comment by runrevmark** [comment]
It might be worth noting _which_ of all the API calls are actually affected by the change in the release note - those which previously took/returned only ASCII won't be affected.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay ccc8d4b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok ccc8d4bd748fbeb69b8c407cc16fb88483695989

**Comment by livecode-vulcan** [comment]
😎 test success ccc8d4bd748fbeb69b8c407cc16fb88483695989
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/201)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/200)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/201)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/196)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/203)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/201)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/204)

**Pull request merged**
