### PR TITLE
Possible fix for 10863. The fix is in line with other error conditions i...

### PR DESCRIPTION
**Pull request by montegoulding**
...n this method however if implemented this way you can get an error thrown if you list the controls to group and an error in the result if you group the selected controls. So there needs to be some design changes here but perhaps this can resolve the issue in the short term.

### CODE REVIEW

**Comment by runrevmark** [comment]
Hmmm - I'm concerned about having the same error condition being signalled in two different ways.

A better way to handle this would be to have MCSellist::group() return Exec_stat, and then have it push the EE_GROUP_NOBG error onto MCeerror rather than setting the result.

Of course, one could argue that the 'not having the same parent' case should also throw an error...

**Comment by montegoulding** [comment]
> Of course, one could argue that the 'not having the same parent' case should also throw an error..
> 
> Yes, I implemented it that way specifically because of the other error condition being implemented that way. I presume also that the IDE checks the result so throwing an error would break the IDE. I really don't like the multiple ways of handling errors in the language so I'm happy to make the change and throw errors for both conditions if that's what you want. Of course it was the sharedGroup property that motivated this so it may all end up fairly low on the todo list ;-)

**Comment by runrevmark** [comment]
I'm not sure the IDE does do much error checking in that regard so cleaning it up probably won't change the IDE's behavior :)

In regards to consistency, then this problem goes way back. We've always tried to rationalize the behavior as this: errors that occur which could be prevented by scripting should throw, errors that script cannot necessarily prevent should set the result. (I'm not saying this is necessarily the best rationalization, just the one which seems to fit with the engine's existing code-base).

A good example is opening a file. You cannot ever guarantee that opening a file will succeed however you code it (it comes down to the OS) thus 'open file' sets the result. You can guarantee (in script) that a property that needs an integer is only given an integer, thus when you pass a string an exception is thrown.

The case of 'MCSellist::group()' is a little less clear which is why, at the very least, making the shared group error throw (from MCSellist::group()) would at least be consistent with it throwing that if you do the same thing with a list...

Although, in actual fact, I'm not sure MCMakeGroup is doing enough checking when it is given a list of objects - I suspect grouping two controls on two different stacks might cause problems as it is written at the moment...

**Comment by montegoulding** [comment]
> I'm not sure the IDE does do much error checking in that regard so cleaning it up probably won't change the IDE's behavior :)

OK

> In regards to consistency, then this problem goes way back. We've always tried to rationalize the behavior as this: errors that occur which could be prevented by scripting should throw, errors that script cannot necessarily prevent should set the result. (I'm not saying this is necessarily the best rationalization, just the one which seems to fit with the engine's existing code-base).

Hmm... I guess you could check to see if one of the groups is shared and if all controls have the same parent by script... probably simpler to try/catch though ;-)

> The case of 'MCSellist::group()' is a little less clear which is why, at the very least, making the shared group error throw (from MCSellist::group()) would at least be consistent with it throwing that if you do the same thing with a list...

OK... I'll look at this when I have a chance. Should it throw an error for the parents not being the same? The IDE should at least catch the error and present a dialog though... at the moment it doesn't appear to do anything if the result says that the parent's are not the same.

> Although, in actual fact, I'm not sure MCMakeGroup is doing enough checking when it is given a list of objects - I suspect grouping two controls on two different stacks might cause problems as it is written at the moment...

Hmm.. wonder if there's way I can unify the code so it's only maintained in one place... maybe just parse the list of selected objects in MCMakeGroup

**Comment by runrevmark** [comment]
Hi Monte,

I've pulled this in as branch bugfix-10863 and merged into 'develop'.

Thanks,

Mark.

**Pull request closed without merging**
