### PR TITLE
[[ Bug 11039 ]] Throw error when changing behavior in behavior

### PR DESCRIPTION
**Pull request by livecodeali**
This patch prevents behavior scripts from changing their child's
behavior.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 24e482a

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 24e482a1c75add479362a3501a1df4180d85e1a9

**Comment by peter-b** [comment]
@livecode-vulcan review ok 762f616

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 762f616937875033ef0fb2753ceca5b653f099f8

**Comment by livecode-vulcan** [comment]
😎 test success 762f616937875033ef0fb2753ceca5b653f099f8

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/685)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/686)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/683)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/684)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/690)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/681)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/682)

**Comment by livecodeali** [comment]
Hmm, I wonder if something in the IDE does this!

**Comment by peter-b** [comment]
@livecode-vulcan review ok 438af97

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 438af978b713d26ea3eb949faf6af6090282151f

**Comment by livecode-vulcan** [comment]
😎 test success 438af978b713d26ea3eb949faf6af6090282151f

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/708)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/709)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/706)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/707)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/713)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/704)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/705)

**Pull request merged**
