### PR TITLE
Final clean-ups required to get the engine building for OSX 64-bit

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 2d7f176

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2d7f1765206f836f259adfcddd2a9642f5835a1b

**Comment by livecode-vulcan** [comment]
💥 merge conflict 2d7f1765206f836f259adfcddd2a9642f5835a1b → ecc2b4647a5381688939ef70c8de6c4da26fca34

**Comment by peter-b** [comment]
@livecode-vulcan review ok 9c535b3

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9c535b36052772d7dcacf3d0feaf81b69b8463e8

**Comment by livecode-vulcan** [comment]
😞 test failure 9c535b36052772d7dcacf3d0feaf81b69b8463e8
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1193)
- try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/1204)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1190)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1197)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1208)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1210)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1212)

**Comment by peter-b** [comment]
@livecode-vulcan review ok d7c4bee

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d7c4beee8e901266b19fbfa3b5fb54fd2e134d94

**Comment by livecode-vulcan** [comment]
😎 test success d7c4beee8e901266b19fbfa3b5fb54fd2e134d94
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1374)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1385)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1370)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1380)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1391)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1390)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1395)

**Pull request merged**
