### PR TITLE
[Tests] Remove lc-test program and legacy LCB testsuite.

### PR DESCRIPTION
**Pull request by peter-b**
This isn't needed any more (now that we have the **lc-run**-based unit tests).

Also clean-up the bitrotten and probably misleading example widget from the toolchain directory, too.  The widgets in the `extensions` tree are probably much better examples anyway.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali Look okay to you?

**Comment by livecodeali** [comment]
Sure
@livecode-vulcan review ok 7f754a4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7f754a4b9b44e5857b4bc471c5afd2ad158b5dc6

**Comment by livecode-vulcan** [comment]
😎 test success 7f754a4b9b44e5857b4bc471c5afd2ad158b5dc6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1570)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1589)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1566)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1577)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1589)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1591)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1593)

**Pull request merged**
