### PR TITLE
[[ Bug 17391 ]] Evaluate mark as empty string when start is greater than end

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali It probably makes no practical difference whether the check is `>` or `>=`...

@livecode-vulcan review ok ccb17b9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ccb17b973a0bbb1ded32a8631c501c8c1f492f58

**Comment by livecodeali** [comment]
@peter-b Oh well, I've fixed it anyway, and added a bonus check in the EvalBytes version as well

**Comment by peter-b** [comment]
@livecode-vulcan review ok 774930d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 774930d2f707b37f436ae0de72ab8431cf369ce2

**Comment by livecode-vulcan** [comment]
😎 test success 774930d2f707b37f436ae0de72ab8431cf369ce2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2412)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2422)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2405)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2423)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2429)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2433)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2445)

**Pull request merged**
