### PR TITLE
[[ Buildbot ]] Upload the release notes alongside the installers

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by peter-b** [comment]
Does it cause problems to just add `-o -name 'LiveCodeNotes*.pdf'` to the original `find`?

Edit: English.

**Comment by livecodesebastien** [comment]
Yes: `find`'s depth is 1, and the release notes are not in `.`, but in `_build/notes`.
Can update `find`'s depth though, but not sure it's the best to do

**Comment by peter-b** [comment]
I agree, I think your patch is the right one.

@livecode-vulcan review ok 759b7cc

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 759b7cc0b9422f316d76f9008384bd7c01a57731

**Comment by livecode-vulcan** [comment]
😎 test success 759b7cc0b9422f316d76f9008384bd7c01a57731
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1135)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1145)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1132)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1138)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1149)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1153)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1154)

**Pull request merged**
