### PR TITLE
[[ Merge release 6.7.8 ]] 21-10-15

### PR DESCRIPTION
**Pull request by livecodesebastien**
Clean merge.

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Auto-review as clean merge of `release-6.7.8` into `develop-6.7`
@livecode-vulcan review ok 2f3a26e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 2f3a26ee1aa534c109ce2f8eac14a36726af8c7e

**Comment by livecode-vulcan** [comment]
😞 test failure 2f3a26ee1aa534c109ce2f8eac14a36726af8c7e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/802)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/816)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/803)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/806)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/816)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/826)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/819)

**Comment by livecodesebastien** [comment]
@livecode-vulcan retry 2f3a26e

**Comment by livecode-vulcan** [comment]
😎 test success 2f3a26ee1aa534c109ce2f8eac14a36726af8c7e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/807)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/821)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/808)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/811)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/821)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/831)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/824)

**Pull request merged**
