### PR TITLE
Add Gyp rules for building the library and widget extensions used by the IDE

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @livecodefraser, the shell script could really do with some explanatory comments for the benefit of everyone else if you get hit by a bus on the way home.  As could the batch file. :sob:

**Comment by livecodestephen** [comment]
Closes #2335

**Comment by peter-b** [comment]
Fine whatever. :wink: 

@livecode-vulcan review ok 9bdbb5a

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9bdbb5ac6e5cb456903394f41dfd7ce25d62a96c

**Comment by livecode-vulcan** [comment]
😎 test success 9bdbb5ac6e5cb456903394f41dfd7ce25d62a96c
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/260)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/323)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/210)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/271)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/206)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/202)

**Pull request merged**
