### PR TITLE
Merge develop 8.1 14.02.17

### PR DESCRIPTION
**Pull request by livecodeali**
@livecode-vulcan review ok 35e273a

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 35e273ae82dc5e605d94d411d2edf7b9ba09d89a

**Comment by livecode-vulcan** [comment]
😞 test failure 35e273ae82dc5e605d94d411d2edf7b9ba09d89a

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/948)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/954)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/946)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/947)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/954)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/952)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/945)

**Comment by peter-b** [comment]
Failed due to `mspdbsrv` squatting on the build directory 😢 

@livecode-vulcan retry 35e273a

**Comment by livecode-vulcan** [comment]
😞 test failure 35e273ae82dc5e605d94d411d2edf7b9ba09d89a

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/950)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/956)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/948)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/949)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/956)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/957)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/947)

**Comment by peter-b** [comment]
Superseded by #5193.

**Pull request closed without merging**
