### PR TITLE
[[ Gyp ]] Update the iOS standalone engine name in mapFilePath

### PR DESCRIPTION
**Pull request by livecodesebastien**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
That is only breaking iOS deployment when the IDE is built, not on the installed version - that can be merged in after 6.7.7 RC 1 release.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 888b4a9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 888b4a9ca05019d8f824877577d27f2eaf5a2350

**Comment by livecode-vulcan** [comment]
😎 test success 888b4a9ca05019d8f824877577d27f2eaf5a2350
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/646)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/706)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/595)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/659)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/591)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/584)

**Pull request merged**
