### PR TITLE
[Bug 17466] Standalone-Community app name should be 'LiveCode'

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodepanos Can we keep the bundle identifier the same (`com.runrev.revolution`) and just change the bundle name?

**Comment by peter-b** [comment]
@livecode-vulcan review ok 51872d0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 51872d03f165644ff574783ad53b0b849c399f5f

**Comment by livecode-vulcan** [comment]
😎 test success 51872d03f165644ff574783ad53b0b849c399f5f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2439)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2449)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2432)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2450)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2456)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2460)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2472)

**Pull request merged**
