### PR TITLE
Update zlib to version 1.2.8

### PR DESCRIPTION
**Pull request by livecodefraser**
This eliminates a number of Valgrind warnings in the deflate
implementation. These may have caused memory corruption when
using revZip.

Corresponding PR for third-party repo is https://github.com/runrev/livecode-thirdparty/pull/27

### CODE REVIEW

**Comment by peter-b** [comment]
This seems like a good idea.

@livecode-vulcan review ok 415ac4b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 415ac4bb19613326fc9f0988c397ee087511ac29

**Comment by livecode-vulcan** [comment]
😞 test failure 415ac4bb19613326fc9f0988c397ee087511ac29
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/52)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/52)
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/52)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/52)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/54)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/52)

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay ea91265

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok ea91265c0073d74b9643b1c758978b526ed80e71

**Comment by livecode-vulcan** [comment]
😎 test success ea91265c0073d74b9643b1c758978b526ed80e71
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/53)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/53)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/53)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/53)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/55)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/53)

**Pull request merged**
