### PR TITLE
Merge develop 7.0 29.03.2016

### PR DESCRIPTION
**Pull request by livecodepanos**
Conflicts:

```
Makefile
docs/notes/platforms.md
ide-support/revdeploylibraryios.livecodescript
prebuilt/fetch-libraries.sh
thirdparty
```

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 75d293e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 75d293ec9296282f9381537c2b4dd80de615bbba

**Comment by livecode-vulcan** [comment]
😞 test failure 75d293ec9296282f9381537c2b4dd80de615bbba
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2232)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2240)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2225)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2241)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2247)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2252)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2263)

**Comment by livecodepanos** [comment]
I just updated the thirdparty submodule pointer in develop branch, so

@livecode-vulcan retry 75d293e

**Comment by livecode-vulcan** [comment]
😞 test failure 75d293ec9296282f9381537c2b4dd80de615bbba
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2235)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2243)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2228)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2244)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2250)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2255)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2266)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 75d293e

**Comment by livecode-vulcan** [comment]
😞 test failure 75d293ec9296282f9381537c2b4dd80de615bbba
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2236)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2244)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2229)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2245)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2251)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2256)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2267)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 75d293e

**Comment by livecode-vulcan** [comment]
😞 test failure 75d293ec9296282f9381537c2b4dd80de615bbba
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2238)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2246)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2231)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2247)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2253)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2258)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2269)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 75d293e

**Comment by livecode-vulcan** [comment]
😎 test success 75d293ec9296282f9381537c2b4dd80de615bbba
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2239)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2247)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2232)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2248)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2254)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2260)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2270)

**Pull request merged**
