### PR TITLE
Parse $OTHER_LDFLAGS to include custom flags in call to g++

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
I'm surprised that `for` doesn't split `OTHER_LDFLAGS` correctly without the `tr` invocation.

When does `for f in $OTHER_LDFLAGS; do … ; done` work incorrectly?

**Comment by montegoulding** [comment]
;-)

I didn't check I just copied from what you guys did for archs which should be the same.

**Comment by peter-b** [comment]
Hah, touché. I assume you've signed the CLA at some point?

**Comment by montegoulding** [comment]
Yes a few years ago now

**Comment by peter-b** [comment]
@livecode-vulcan review ok ea7e982

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ea7e9823ebc72a79ab6b1054ce2721a99b578522

**Comment by livecode-vulcan** [comment]
😎 test success ea7e9823ebc72a79ab6b1054ce2721a99b578522
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/9)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/9)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/9)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/9)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/9)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/9)

**Pull request merged**
