### PR TITLE
[Bug 14930] libsystem: Fix some issues with lc-run on Windows

### PR DESCRIPTION
**Pull request by peter-b**
This pull request fixes the crash that was making lc-run fail to work on Windows systems.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 5f62fd2

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 5f62fd2358a461fe37e6c6f38e1a99944bd278bc

**Comment by livecode-vulcan** [comment]
😎 test success 5f62fd2358a461fe37e6c6f38e1a99944bd278bc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1255)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1267)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1252)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1261)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1272)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1272)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1276)

**Comment by peter-b** [comment]
@livecodeali Could you please re-review this? I've added a change to make lc-run's command line argument processing a bit more useful on Windows.

**Comment by livecodeali** [comment]
Fixes a memory leak as well :+1: 
@livecode-vulcan review ok e393920

**Comment by peter-b** [comment]
@livecodeali So it does! Hadn't even spotted that. :grinning:

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok e393920d11c8264d09bd306389dfb6d7d6ccaff6

**Comment by livecode-vulcan** [comment]
😎 test success e393920d11c8264d09bd306389dfb6d7d6ccaff6
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1269)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1281)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1266)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1275)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1286)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1286)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1290)

**Pull request merged**
