### PR TITLE
[[ Documentation ]] Fixes to mouseDown.lcdoc

### PR DESCRIPTION
**Pull request by asayd**
- Clarified the param description to reflect modern OSs and mouses.
- Added html5 as OS.
- Added messages tag.
- Clarified example comments.
- Standardizing on "_Note:_" for block quoted notes.
- Added example.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok b54f73f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b54f73f899973e2015b6be317b9318a306964c27

**Comment by livecode-vulcan** [comment]
😎 test success b54f73f899973e2015b6be317b9318a306964c27
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/273)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/277)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/273)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/273)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/277)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/273)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/273)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 3314923

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 33149238f743bc9d2f22f9786ac5b31bbaa0fccd

**Comment by livecode-vulcan** [comment]
😎 test success 33149238f743bc9d2f22f9786ac5b31bbaa0fccd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/279)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/283)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/279)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/279)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/283)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/279)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/279)

**Pull request merged**
