### PR TITLE
Merge develop-8.0 into develop

### PR DESCRIPTION
**Pull request by peter-b**
Trivial merge conflicts in mergExt version and the `version` file.

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 30b706a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 30b706a4d5668c2a14a6770539240cb21e10b350

**Comment by livecode-vulcan** [comment]
😎 test success 30b706a4d5668c2a14a6770539240cb21e10b350
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2784)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2793)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2779)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2795)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2801)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2805)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2823)

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 1126319

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 11263194e04c96ffff1f9d8b5f2aced88eacc1d5

**Comment by livecode-vulcan** [comment]
😎 test success 11263194e04c96ffff1f9d8b5f2aced88eacc1d5
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2788)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2797)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2783)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2799)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2805)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2809)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2827)

**Pull request merged**
