### PR TITLE
[[ Oracle ]] Remove from community repo (it has never been built as p…

### PR DESCRIPTION
**Pull request by runrevmark**
…art of community)

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 118198e

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 5c106e8

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 5c106e8829eee1360c37e1d1319f4ad192ad32c8

**Comment by livecode-vulcan** [comment]
😎 test success 5c106e8829eee1360c37e1d1319f4ad192ad32c8
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/701)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/761)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/651)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/715)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/646)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/638)

**Pull request merged**
