### PR TITLE
Merge develop 8.2 03.11.17

### PR DESCRIPTION
**Pull request by livecodeali**
https://gist.github.com/909434f5d6f9aaa2de21b66094db4b09

Conflicts:
	both modified:   Makefile
	both modified:   buildbot.py
	both modified:   docs/dictionary/command/create-card.lcdoc
	both modified:   docs/dictionary/command/do.lcdoc
	both modified:   engine/src/exec-engine.cpp
	both modified:   engine/src/exec.h
	both modified:   ide
	both modified:   ide-support/revdeploylibraryios.livecodescript
	both modified:   prebuilt/fetch-libraries.sh
	both modified:   prebuilt/scripts/ios.inc
	both modified:   tools/setup_xcode_sdks.py

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 99b06b1

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 99b06b17a066a0b1c7680ced6194926a4daab535

**Comment by livecode-vulcan** [comment]
😞 test failure 99b06b17a066a0b1c7680ced6194926a4daab535

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/951)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/967)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/941)
* try-community-universal-ios-iphoneos11.1: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.1/builds/14)
* try-community-universal-ios-iphonesimulator11.1: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.1/builds/14)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/945)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/968)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/951)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/967)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/950)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/960)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/982)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/946)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 99b06b1

**Comment by livecode-vulcan** [comment]
😞 test failure 99b06b17a066a0b1c7680ced6194926a4daab535

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/952)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/968)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/942)
* try-community-universal-ios-iphoneos11.1: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.1/builds/15)
* try-community-universal-ios-iphonesimulator11.1: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.1/builds/15)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/946)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/969)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/952)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/968)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/951)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/961)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/983)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/947)

**Comment by livecodepanos** [comment]
The openssl and ICU prebuilts for iOS 11.1 are now uploaded.

@livecode-vulcan retry 99b06b1

**Comment by livecode-vulcan** [comment]
😎 test success 99b06b17a066a0b1c7680ced6194926a4daab535

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/955)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/971)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/945)
* try-community-universal-ios-iphoneos11.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.1/builds/18)
* try-community-universal-ios-iphonesimulator11.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.1/builds/18)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/949)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/972)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/955)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/971)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/954)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/964)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/986)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/950)

**Pull request merged**
