### PR TITLE
[[ Bug 16644 ]] Ensure 'CanBeNative'-ness is preserved by concatenation where appropriate

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 772f5ea

Sorry for breaking it...

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 772f5eaa6da165c8bcbac25ed51293110c4b39b4

**Comment by livecode-vulcan** [comment]
😎 test success 772f5eaa6da165c8bcbac25ed51293110c4b39b4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1508)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1527)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1504)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1515)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1527)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1528)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1530)

**Comment by livecodeali** [comment]
@peter-b You didn't, I don't think? Unless you also wrote the implementation of `__MCStringCreateWithStrings` ;-)

**Pull request merged**
