### PR TITLE
Error returned by hostnametoaddress was not being reported to the user

### PR DESCRIPTION
**Pull request by trevordevore**
ulHostNameToAddressCallback needs to report a detailed error rather thant "invalid host address". This fix reports the actual error.

### CODE REVIEW

**Comment by peter-b** [comment]
@trevordevore Thanks for this bugfix! I think we should probably include it in the next round of 8.1.x releases.  In order to for us to do this, I would really appreciate it if you could:
- Rebase this PR on the `develop-8.1` branch
- File a bug report describing the problem and how to reproduce it
- Add a release note to this PR
- Ideally, write a unit test to make sure that this bug never happens again

Please let me know if you run into any problems -- I would be delighted to help you backport the bug fix if necessary.

**Comment by trevordevore** [comment]
@peter-b No need to back port. I'm finally moving to 8.1 (I had to modify a lot of code that used the executionContexts) and I want to switch to using the tsNet version of libURL. I'm going to go through and submit some PRs with fixes and additions from my own custom libURL.

**Comment by peter-b** [comment]
@trevordevore Okay, as long as you're happy with them only going into LiveCode 9 ;-)

**Comment by trevordevore** [comment]
@peter-b sorry,  I thought you were referring to backporting to 8.0. I'm with you now. I'm going to move this over to 8.1.

**Pull request closed without merging**
