### PR TITLE
Bug 18231 & more [Docs] binaryEncode/binaryDecode Fix list line break dataTypes

### PR DESCRIPTION
**Pull request by PaulMcClernan**
Inserted line breaks and made dataTypes an unordered list -

### CODE REVIEW

**Comment by livecodeali** [comment]
@PaulMcClernan Thanks for this! It's fine as it is, but would it be ok to get you to make a couple of other minor adjustments please? 

One is that the Summary of this doc seems to start with `<Decodesbinary data>` which should just be `Decodes binary data`, and `Decodesbinary data (glossary)` should be removed from the references. 

Also could you add an empty line before the beginning of the `>*Important` section please?

Finally there are several occurrences of `variablesList`, `formatsList` and `binaryDecode` which should have angle brackets round them just so they are displayed correctly in the entry.

**Comment by PaulMcClernan** [comment]
Have to figure out this whole git/branch/fork/pull/merge thing some more. Sorry, If I do annoying newb things.

**Comment by PaulMcClernan** [comment]
This is fixes to bug report #18231
http://quality.livecode.com/show_bug.cgi?id=18231

**Comment by livecodeali** [comment]
@PaulMcClernan Since this fixes a bug report, I'm afraid you'll have to add a bugfix note as well! Sorry. Otherwise this is good to go!

**Comment by PaulMcClernan** [comment]
@seaniepie 
sure I'll try to do some of those when I get a chance (later today?)

**Comment by livecodeali** [comment]
Superseded by https://github.com/livecode/livecode/pull/4727

**Pull request closed without merging**
