### PR TITLE
[Bug 16524] Make sure empty lines reset color props..

### PR DESCRIPTION
**Pull request by livecodepanos**
when setting the colors of an object

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-panos review ok 3a8cffb

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 3a8cffb

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 3a8cffbb24a7cd8efb90b6a8a15eb744ae30e4ee

**Comment by livecode-vulcan** [comment]
😎 test success 3a8cffbb24a7cd8efb90b6a8a15eb744ae30e4ee
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1360)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1371)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1356)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1366)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1377)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1376)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1381)

**Pull request merged**
