### PR TITLE
[[ Bug 16357 ]] Update libffi for iOS, fixing browser widget crash on 64bit devices

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecodeian** [comment]
livecode-thirdparty update PR: https://github.com/livecode/livecode-thirdparty/pull/50

**Comment by peter-b** [comment]
@livecodeian Could you please change this PR to just add the release note without updating the submodule? The submodule update should happen reasonably automatically after the corresponding thirdparty PR is merged.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1ff377e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1ff377e189d1b2d58050cc9e38e8a2563d6ef62f

**Comment by livecode-vulcan** [comment]
😎 test success 1ff377e189d1b2d58050cc9e38e8a2563d6ef62f
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2043)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2055)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2037)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2051)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2058)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2064)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2071)

**Pull request merged**
