### PR TITLE
[[ Docs API ]] Add database of docs data

### PR DESCRIPTION
**Pull request by livecodeali**
There is no easy way of creating a docs api in the IDE using the
JSON data, so we include an sqlite database with each entry's docs
data array arrayEncoded for easy retrieval.

The database includes a table of libraries (currently livecode script
and livecode builder) and a table for each library containing its
docs data.

### CODE REVIEW

**Comment by livecodeali** [comment]
Ah thanks, yes was planning to do that but it slipped my mind.

**Comment by peter-b** [comment]
Out of interest, why use a table for each library, rather than one table of libraries and one table of docs data with a "libraryId" column?  Using one big table could potentially make it easier to perform full-documentation searches.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3d96be2

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3d96be2111c8b4add827aa71a263901d30b22b60

**Comment by livecode-vulcan** [comment]
😎 test success 3d96be2111c8b4add827aa71a263901d30b22b60
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1273)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1284)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1269)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1279)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1290)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1289)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1294)

**Pull request merged**
