### PR TITLE
[Bug 16737] Send playstopped msg on time

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 72503c8

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 72503c8419cf1de164eb1ad325c94c159650f904

**Comment by livecode-vulcan** [comment]
😎 test success 72503c8419cf1de164eb1ad325c94c159650f904
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1596)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1615)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1592)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1603)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1616)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1617)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1619)

**Comment by livecodepanos** [comment]
Just a bugfix note added, so self review:

@livecode-vulcan review ok 12faeb9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 12faeb920f30804b41ea51f749a38014e8abcf9e

**Comment by livecode-vulcan** [comment]
😎 test success 12faeb920f30804b41ea51f749a38014e8abcf9e
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1597)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1616)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1593)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1604)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1617)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1618)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1620)

**Pull request merged**
