### PR TITLE
[[ Bug 19840 ]] Allow 'delete me' from message box

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevmark** [comment]
This is certainly a start - but we need to vet all places which use GetObject() on the exec-context I think, otherwise it is no better than not using a PartHandle. Also I'm trying to think if there are any other side-effects here.

As I said on slack, this case is an easier one to get working than others because the handlerlist/handler object is owned by the MCObject::domess() frame, and not by the object. So deleting the object won't cause that to get destructed (thus causing a problem whilst executing multiple statements).

I think 'the target' and 'me' (and places which call GetObject() directly) are the only ones which could cause SEGV type crashes / undefined behavior if the object has been deleted.

**Comment by runrevmark** [comment]
As per discussion offline - for 8.1.5 we should just remove the exec lock from domess() - the engine will be as stable as it was *before* this was put in; and we can make the exec-lock finer / less intrusive properly in 8.1.6 after some time to work out the best pattern follow when using MCExecContext::GetObject() (which we *think* is the only point of entry which could cause any instability).

**Comment by runrevmark** [comment]
@livecode-vulcan review ok c131f40

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok c131f400a17f39b74c0c8b846be601b2723d55e0

**Comment by livecode-vulcan** [comment]
😎 test success c131f400a17f39b74c0c8b846be601b2723d55e0

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/366)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/372)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/352)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/295)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/295)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/361)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/366)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/364)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/370)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/364)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/370)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/389)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/360)

**Pull request merged**
