### PR TITLE
[Bug 13754] Changing the scalefactor might hide the stack off screen

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @runrevpanos, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 753995f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 753995f645f9c8b6c5294a0c98c898a36c317be2

**Comment by livecode-vulcan** [comment]
😎 test success 753995f645f9c8b6c5294a0c98c898a36c317be2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/209)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/208)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/209)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/204)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/211)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/209)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/212)

**Comment by livecodeali** [comment]
This forces stacks onto the primary screen.

Perhaps something like the following will work:

```
    // PM-2015-07-17: [[ Bug 13754 ]] Make sure stack does not disappear off screen when changing the scalefactor
    MCRectangle t_bounded_rect, t_screen_rect;

    t_screen_rect = MCscreen -> getnearestdisplay(t_view_rect) -> viewport;

    t_bounded_rect = MCU_bound_rect(t_view_rect, t_screen_rect . x, t_screen_rect . y, t_screen_rect . width, t_screen_rect . height);

    // IM-2014-01-16: [[ StackScale ]] Update view rect if needed
    view_setrect(t_bounded_rect);
```

**Comment by livecodepanos** [comment]
Good catch. Created new PR for this:

https://github.com/livecode/livecode/pull/2965

**Pull request merged**
