### PR TITLE
Fix a couple of issues with the standalone builder

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok fc0c1f4

I missed that incorrect setting/resetting of `the itemdelimiter` when I reviewed the original PR! Sorry!

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok fc0c1f42a6e50316711be6207846426eb2931837

**Comment by livecode-vulcan** [comment]
😎 test success fc0c1f42a6e50316711be6207846426eb2931837
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2628)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2638)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2623)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2639)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2645)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2651)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2663)

**Comment by livecodeali** [comment]
@peter-b It's a particularly hard case to spot - in fact it took me a while to work out what the bug actually was!

**Pull request merged**
