### PR TITLE
Tweaks to get the 8.0 installers complete

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 5edcdc2

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 9054175

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 9054175d3fc700c693f93ed0142fb33c2a72fc2e

**Comment by livecode-vulcan** [comment]
😞 test failure 9054175d3fc700c693f93ed0142fb33c2a72fc2e
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/330)
- try-win-x86: [failure](https://vulcan.livecode.com/builders/try-win-x86/builds/393)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/275)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/341)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/276)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/266)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 9054175

**Comment by livecode-vulcan** [comment]
😎 test success 9054175d3fc700c693f93ed0142fb33c2a72fc2e
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/332)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/395)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/277)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/343)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/278)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/268)

**Pull request merged**
