### PR TITLE
Merge develop 7.0 24.09.15

### PR DESCRIPTION
**Pull request by livecodeali**
All trivial conflicts 
- whitespace in lnxstack.cpp
- standard conflicts in version and ide

The Installer package conflict was still relatively trivial (coming from the fact that all the 5.1s here https://github.com/livecode/livecode/pull/2919/files were 6.1s in develop. Therefore I just accepted the develop-7.0 version of that section.

### CODE REVIEW

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok  50bd363

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 50bd363bff4701920bbae6af3392e43ca2ae66fe

**Comment by livecode-vulcan** [comment]
⁉ merge unchanged 50bd363bff4701920bbae6af3392e43ca2ae66fe → 83fb108e334217cd35e50e5346abb9a84a5691a0

Pull request is already fully merged!

**Comment by livecodeali** [comment]
Argh, whoops - sorry @livecode-vulcan, I jumped the gun there.

**Pull request merged**
