### PR TITLE
[Bug 15925] Implemented "playableDuration" for android player

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeian** [comment]
@livecodepanos are there any changes to be committed for mobileControlGet.xml? I don't see any content changes for that file here.

**Comment by livecodepanos** [comment]
Hi @livecodeian. I thought I had removed the "iOS only" from the "playableDuration" property, but it seems that I reverted this change because was having merge conflicts in mobileControlGet.xml (not sure why!) If you think this PR is correct, I suggest merging it into develop-6.7, and then I can submit a new PR which will include only the update of mobileControlGet.xml.

**Comment by livecodeian** [comment]
@livecodepanos you should be able to pull develop-6.7 into your bugfix-15925 branch without any conflicts, make the necessary changes to the docs, then push it out to github. Send me a PM if you need any assistance with this.

**Comment by livecodeian** [comment]
Not sure what's going on with the github "Files changed" view as it's not showing the changes to MobileControlGet.xml, but viewing the full files shows that the playableDuration entry has been updated so I'll go ahead and mark this as reviewed.

**Comment by livecodeian** [comment]
@livecode-vulcan review ok 3971398

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeian ok 3971398790ef3876105c71b79a54442685678353

**Comment by livecode-vulcan** [comment]
😎 test success 3971398790ef3876105c71b79a54442685678353
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/515)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/519)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/514)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/514)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/523)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/517)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/525)

**Pull request merged**
