### PR TITLE
[[ Bug 16813 ]] Use multithreaded messageloop on Windows

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodeian: Could you resolve conflicts in this branch so I can review? Thanks!

**Comment by livecodeian** [comment]
@runrevmark conflicts resolved :)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 455f79f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 455f79fae6c23ee6ff072ea93fb97d03b1e352cc

**Comment by livecode-vulcan** [comment]
😎 test success 455f79fae6c23ee6ff072ea93fb97d03b1e352cc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1799)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1812)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1793)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1805)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1814)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1818)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1824)

**Pull request merged**
