### PR TITLE
[[ Builder ]] Docs should error if the script dictionary folder doesn't exist or data is empty

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
This won't fix the issue but might at least give us a clue as to what's breaking.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 55e3e49

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 55e3e495eb12da7682e89f9d1f450be8ddff312b

**Comment by livecode-vulcan** [comment]
😞 test failure 55e3e495eb12da7682e89f9d1f450be8ddff312b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1828)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1841)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1822)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1834)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1844)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1847)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1853)

**Comment by peter-b** [comment]
@livecode-vulcan retry 55e3e49

**Comment by livecode-vulcan** [comment]
😞 test failure 55e3e495eb12da7682e89f9d1f450be8ddff312b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1830)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1843)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1824)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1836)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1846)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1849)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1855)

**Comment by peter-b** [comment]
@livecode-vulcan retry 55e3e49

**Comment by livecode-vulcan** [comment]
😞 test failure 55e3e495eb12da7682e89f9d1f450be8ddff312b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1832)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1845)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1826)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1838)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1848)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1851)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1857)

**Comment by peter-b** [comment]
One more try...

@livecode-vulcan retry 55e3e49

**Comment by livecode-vulcan** [comment]
😞 test failure 55e3e495eb12da7682e89f9d1f450be8ddff312b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1836)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1849)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1830)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1842)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/1852)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1855)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1861)

**Comment by peter-b** [comment]
Merging this untested -- the test failures are not at all related to the change.

**Pull request merged**
