### PR TITLE
[[ Bug 14910 ]] Add .livecodescript to valid file associations for LC

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodefraser** [comment]
Given that you so recently fixed the revFileAssociations stack for Windows, do you think you could add this change there too? :innocent:

**Comment by livecodeali** [comment]
Good plan.

**Comment by livecodeali** [comment]
There you go :smile: 
https://github.com/runrev/livecode-ide/pull/123
https://github.com/runrev/livecode-ide/pull/122

**Comment by livecodesebastien** [comment]
Reviewed-by: Sébastien Nouat

**Pull request merged**
