### PR TITLE
[[ Xcode&Prebuilt update ]] Updates both Xcode and the prebuilt libraries

### PR DESCRIPTION
**Pull request by livecodesebastien**
Merge of https://github.com/runrev/livecode/pull/2518 and https://github.com/runrev/livecode/pull/2522

### CODE REVIEW

**Comment by livecodesebastien** [comment]
@livecode-vulcan review ok 1cd552c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 1cd552cf93b7adb602d06e1d9000b4c8f935d999

**Comment by livecode-vulcan** [comment]
😎 test success 1cd552cf93b7adb602d06e1d9000b4c8f935d999
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/377)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/440)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/323)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/388)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/323)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/314)

**Comment by peter-b** [comment]
Yay, finally! 😄

**Pull request merged**
