### PR TITLE
Accelerated rendering issues

### PR DESCRIPTION
**Pull request by montegoulding**
This can/will be split into separate PRs and is mainly here at the moment for @livecodepanos to pull and test.

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 7926c45

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 7926c45a81a9a501875a88984a451aeecd54ff1e

**Comment by livecode-vulcan** [comment]
😞 test failure 7926c45a81a9a501875a88984a451aeecd54ff1e

* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1544)
* try-community-armv6-android-api26: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api26/builds/29)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1518)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/45)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/45)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1548)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1542)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1537)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1576)
* try-community-x86_64-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1516)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 7926c45

**Comment by livecode-vulcan** [comment]
😎 test success 7926c45a81a9a501875a88984a451aeecd54ff1e

* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1545)
* try-community-armv6-android-api26: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api26/builds/30)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1519)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/46)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/46)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1549)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1543)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1538)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1577)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1517)

**Pull request merged**
