### PR TITLE
Xslt

### PR DESCRIPTION
**Pull request by mwieder**
Addition of xml stylesheet transformation functions (relies on the libxml 2.9.1 branch and the thirdparty xslt branch for the xslt library).
Functions supplied here are:

xsltApplyStylesheet()
xsltApplyStylesheetFile()
xsltLoadStylesheet()
xsltLoadStylesheetFromFile()
xsltFreeStylesheet

### CODE REVIEW

**Comment by runrevmark** [comment]
Hi Mark,

Thanks for this, a couple of initial comments...

Could you resubmit the pull-request against develop? As this builds on changes there, it will clean up the diff a bit and make it easier to see the ones pertaining exclusively to the XSLT functions.

Also, at the moment the way the XSLT 'pointers' are being handled is too unsafe - as you are returning an id which is just a the pointer cast to an int (from what I can see), it would be all too easy to crash the engine by passing in an invalid id. An id system similar to the one revXML uses for XML documents is needed here - that way you can be sure that the user isn't giving you integers that aren't actually pointers.

Warmest Regards,

Mark.

**Comment by runrevmark** [comment]
Addendum: By the way, I'm not suggesting you rebase your branch onto develop or anything like that, just change the target branch of the pull-request when you submit.

**Comment by mwieder** [comment]
OK - I'll resubmit it against develop. I just did a build and the develop branch built ok over here, so I don't think there should be a problem. But I'll think about the pointers thing first. That worried me a bit as well. I'd rather not have to go through all the overhead of building an entire xml tree document just to get an id. It seems that the important thing here would be to insulate the user from the actual free() call so that an id can reference a valid pointer.

**Comment by runrevmark** [comment]
Resubmitting against develop just means the diff reduces in size which makes it easier for me to peruse :) It's annoying github doesn't allow you to change the target branch of a pull-request after its been sent...

In regards to the pointer thing xmlStylesheetPtr's are distinct from the XML document ptrs as far as I can see. So all you need is a simple map from integers to pointers - revXML currently does this by keeping a 'vector' of XMLDocs which are essentially a pair (integer, xml doc ptr). It then looks up (when needing to find one) and prunes (when freeing one) this as appropriate. A simple linked-list would actually do:

```
struct XSLTStyleSheet
{
  XSLTStyleSheet *next;
  unsigned int id;
  xsltStylesheetPtr stylesheet;
};
```

This would save having to create a wrapper around xsltStylesheetPtr which contains the id - which I think is what the revXML functions do.

**Comment by runrevmark** [comment]
Hi Mark - I'll close this request since it has been superseded,

**Pull request closed without merging**
