### PR TITLE
Update OpenSSL version to 1.0.1s

### PR DESCRIPTION
**Pull request by livecodefraser**
Prebuilt packages have been uploaded for 7.x+ for all platforms **except iOS**; these will need to be done before merging. Back-porting to the 6.7 prebuilt repo will also be required.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok cdd58f8

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok cdd58f8a348e3297ae1694f7da8264128a3636cd

**Comment by livecode-vulcan** [comment]
😞 test failure cdd58f8a348e3297ae1694f7da8264128a3636cd
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2194)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/2201)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2187)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2203)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2208)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2214)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2225)

**Comment by livecodefraser** [comment]
Re-trying to see if merging libCurl fixed the Linux issues

@livecode-vulcan retry cdd58f8

**Comment by livecode-vulcan** [comment]
😞 test failure cdd58f8a348e3297ae1694f7da8264128a3636cd
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2200)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2207)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2193)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2209)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/2214)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2220)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2231)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry cdd58f8

**Comment by livecode-vulcan** [comment]
😞 test failure cdd58f8a348e3297ae1694f7da8264128a3636cd
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2224)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2232)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2217)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2233)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/2239)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2244)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2255)

**Comment by livecodefraser** [comment]
All builds except iOS (broken for other reasons) have passed.

**Pull request merged**
