### PR TITLE
[19918] [[ JavaFFI ]] Allow jar file inclusions in desktop standalones

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Requires https://github.com/livecode/livecode-ide/pull/1803

**Comment by livecodeali** [comment]
Hmm, I'm not sure the extension tests are being run yet.

**Comment by livecodeali** [comment]
Check branch https://github.com/livecode/livecode/pull/6068

**Comment by montegoulding** [comment]
@livecode-vulcan review ok fadbd95

@livecodeali reviewing ok but the need for `TestEnsureJVM` indicates the IDE isn't setting `$JAVA_HOME` like it's meant to isn't it? Either way couldn't this ensuring just be done by default?

**Comment by livecodeali** [comment]
@montegoulding It doesn't need to be there in the S/B test it's in, but is there for the skip behavior. I should probably tweak it slightly so that it starts with a `TestSkipIf "jvm"` or something.

 But the reason it needs to set $JAVA_HOME is that I have a standalone engine test as well (tests/lcs/extensions/libraries/javatest/tests/java.livecodescript) that needs it.

My plan is to move `revcommonlibrary` into a `com.livecode.library.utils` or something, and put the java_home setter in there (as well as a bunch of other things that are needed in multiple of build/test/run from source/run from install environments)

**Comment by montegoulding** [comment]
@livecode-vulcan review ok fe04d45

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok fe04d45a0795c2c5b76c8d6fcf5bd4f864548b33

**Comment by livecode-vulcan** [comment]
😎 test success fe04d45a0795c2c5b76c8d6fcf5bd4f864548b33

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/916)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/932)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/906)
* try-community-universal-ios-iphoneos11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.0/builds/81)
* try-community-universal-ios-iphonesimulator11.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.0/builds/82)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/910)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/932)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/916)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/932)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/915)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/925)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/947)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/911)

**Pull request merged**
