### PR TITLE
Installer builder changes required for Indy/Business licensing

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by livecodefraser** [comment]
There is a corresponding PR in the IDE repo that removes the installer manifest from it:

https://github.com/runrev/livecode-ide/pull/414

**Comment by livecodeali** [comment]
This looks sound to me assuming the relevant stuff is in the correct place in the private repo. Will have a look at that one. Probably the best thing here is to get it merged and tested asap.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok c97bb5a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok c97bb5a309e16f38abda36a2e7baa0f974e6a4a4

**Comment by livecode-vulcan** [comment]
😎 test success c97bb5a309e16f38abda36a2e7baa0f974e6a4a4
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/728)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/788)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/678)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/742)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/673)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/665)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok b097168

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok b097168fdacfad0a15846e75e9822725fb7c8074

**Comment by livecode-vulcan** [comment]
😞 test failure b097168fdacfad0a15846e75e9822725fb7c8074
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/25)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/25)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/25)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/25)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/27)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/25)

**Pull request merged**
