### PR TITLE
[[ Community Docs ]] MobileControlGet - fix formatting

### PR DESCRIPTION
**Pull request by asayd**
- Unscrambled Parameter listing;
- Added Tag: properties;
- Beefed up examples;
- Other minor fixes.

### CODE REVIEW

**Comment by asayd** [comment]
Suspect errors in Global properties for all native mobile controls vs. Global properties for all native iOS controls.
In the LC 7 dictionary, **mobileControlGet** lists them this way:
Global properties (All native mobile controls)
- id - Returns the id of the control where the name is passed.
- name - Returns the name of the control where the id is passed.
- rect - Returns the bounds of the control, relative to the top-left of the card. For example "0,0,100,100".
- visible - Returns true if the control is visible.
- ignoreVoiceOverSensitivity - Returns true if the control is accessible through Voice Over. Default value is false.

Global properties (All native iOS controls)
- opaque - Returns true if the control is opaque.
- alpha - Returns the blendlevel of the control as an integer between 0 and 255.
- backgroundColor - Returns the background color of the control as an integer between 0 to 255.

In LC 7 Dictionary, those same two categories in **mobileControlSet** are listed this way:
Global properties (All native mobile controls)
- rect - the bounds of the control, relative to the top-left of the card. For example "0,0,100,100".
- visible - set to true or false to determine whether the control should be displayed.
- alpha - set to a property between 0 and 255 to blend the control with any controls underneath it.
- backgroundColor - Set to either a standard color name, or a string of the form red,green,blue or red,green,blue,alpha. Where the components are integers in the range 0 to 255.

Global properties (All native iOS controls)
- opaque - set to false if the control should be rendered with transparency. In particular, set this control to true if you set a backgroundColor that is not fully opaque.
- ignoreVoiceOverSensitivity - set to true or false to determine whether the control should be accessible through Voice Over.

Suspect `ignoreVoiceOverSensitivity` is iOS only, but **mobileControlGet** lists as "All mobile".

`alpha` and `backgruondColor` are listed as iOS only in the latter, but "all mobile" in the former.

Do you know where they all belong?

**Comment by livecodeali** [comment]
@asayd Yes `ignoreVoiceOverSensitivity` should indeed be iOS only in both, and `alpha` and `backgroundColor` should be all mobile in both!

**Comment by livecodeali** [comment]
@asayd I think it might be best to move all of the description of the `property` parameter (which I think should be called `propertyName` to avoid conflict with the property entry) to the Description section. There is probably just too much data there to be worth keeping in the table. What do you think? I believe @peter-b has already done this with some other long parameter descriptions.

**Comment by asayd** [comment]
@livecodeali Okay, will move `ignoreVoiceOverSensitivity` to iOS only, along with opaque, and move the others to all mobile.

**Comment by asayd** [comment]
@livecodeali Agreed re property parameter. That's the way HTMLText entry is. All of the supported tags are listed in the Description.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok c6e1b05

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok c6e1b05cdb30137d345f2dbbe1d9970e0d2eae84

**Comment by livecode-vulcan** [comment]
😎 test success c6e1b05cdb30137d345f2dbbe1d9970e0d2eae84
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2453)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2463)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2446)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2464)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2470)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2474)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2486)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok ed03c86

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok ed03c8614bef54c7337249e904aac656b7bd4e86

**Comment by livecode-vulcan** [comment]
😎 test success ed03c8614bef54c7337249e904aac656b7bd4e86
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2459)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2469)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2452)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2470)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2476)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2480)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2492)

**Pull request merged**
