### PR TITLE
[[Dictionary]] adMin references

### PR DESCRIPTION
**Pull request by seaniepie**
Add all transfer modes to the references

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok ba11e66

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok ba11e66826d62ec7574e766028a3ff54026cbd8c

**Comment by peter-b** [comment]
@seaniepie Thinking about this further, would it make more sense to have a `transfer mode` entry in the glossary, which lists all the transfer modes with brief explanations and links to the full descriptions?  That way if a transfer mode was added or removed in the future it wouldn't be necessary to update every single dictionary entry for each of them.

**Comment by peter-b** [comment]
@seaniepie I'm going to temporarily remove the "review" flag from this while we discuss, just so this doesn't get merged yet.

@livecode-vulcan review not ok ba11e66

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok ba11e66826d62ec7574e766028a3ff54026cbd8c

**Comment by seaniepie** [comment]
Sounds good.

**Pull request closed without merging**
