### PR TITLE
[Bugfix 15439] Make sure you can set the enabledTracks in LC 7.0

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @runrevpanos, was this previously fixed in develop-6.7?

**Comment by livecodepanos** [comment]
Hi @peter-b, yes this issue was fixed in develop-6.7 (reported as bug 15052)

**Comment by peter-b** [comment]
That was #2113. @runrevmark, could you please review this PR since you also reviewed #2113?

**Comment by runrevmark** [comment]
Is there not a suitable list getter / setter which does the int-array <-> appropriate-type-of-string-list conversion?

**Comment by runrevmark** [comment]
Indeed - there is a property type 'LinesOfUInt' which would be more appropriate than putting the MCList accumulation in the player code itself.

**Comment by livecodepanos** [comment]
Superseded by https://github.com/runrev/livecode/pull/2369

**Pull request closed without merging**
