### PR TITLE
widgets: Install into correctly-named directory.

### PR DESCRIPTION
**Pull request by peter-b**
Ensures that the directory that widgets are installed into
matches their actual module name.

### CODE REVIEW

**Comment by livecodeali** [comment]
The installer manifest will need to be changed in this pull request too.

**Comment by peter-b** [comment]
@livecodeali Pull request updated!

**Comment by livecodeali** [comment]
Nice one :+1: 
@livecode-vulcan review ok a3ae1b9

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a3ae1b992a59fde7e28423b8d74aad38715fdb4b

**Comment by livecode-vulcan** [comment]
😎 test success a3ae1b992a59fde7e28423b8d74aad38715fdb4b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1521)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1540)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1517)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1528)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1540)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1541)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1543)

**Pull request merged**
