### PR TITLE
[[ Documentation ]] Changes to joinStyle.lcdoc

### PR DESCRIPTION
**Pull request by asayd**
- Fixed formatting problem in Value element.
- Added references and links.
- Minor wording fixes.

### CODE REVIEW

**Comment by livecodeali** [comment]
@asayd The reason this wasn't formatting correctly for the enum type was that there were line breaks in the items... I'll file a bug report for not being able to wrap these lists.

I'm fine either way with keeping what you've done or formatting it correctly for an enum, but I think if you keep what you've done we should remove the `(enum)` from the parameter. Does having it there not affect the display of the entry? I'm surprised if it doesn't!

**Comment by asayd** [comment]
@livecodeali The presence of `(enum)` doesn't seem to affect the display. But I'll take it out.

**Comment by peter-b** [comment]
@livecode-vulcan review ok d288229

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok d2882293bee6290ff63d4bd9be19c305c2009c9a

**Comment by livecode-vulcan** [comment]
😎 test success d2882293bee6290ff63d4bd9be19c305c2009c9a

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/641)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/646)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/641)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/645)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/650)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/642)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/642)

**Pull request merged**
