### PR TITLE
Merge develop 7.0 181115

### PR DESCRIPTION
**Pull request by livecodesebastien**
Unreviewed changes:
- `config/linux.gypi`: changes ported to `config/linux-settings.gypi`
- docs/dictionary/operator/bitNot.xml: changes ported to `bitNot.lcdoc`
- engine/src/osxprinter.cpp
- engine/src/stackcache.cpp
- engine/src/sysspec.cpp
- libfoundation/src/foundation-value.cpp

Changes to be committed:
    modified:   config/ios.gypi
    modified:   config/linux-settings.gypi
    modified:   docs/dictionary/operator/bitNot.lcdoc

The following files had to be modified to cope with `-Werror=tautological-compare` flag on iOS and Mac
- libbrowser/src/libbrowser.cpp
- libbrowser/src/libbrowser_android.cpp
- libbrowser/src/libbrowser_desktop_factories.cpp
- libbrowser/src/libbrowser_internal.h
- libbrowser/src/libbrowser_ios_factories.cpp

### CODE REVIEW

**Comment by peter-b** [comment]
I can duplicate the unit test failures on my home Linux machine.  Unfortunately the test suite log file isn't any more informative than the console output.  Maybe the RTF code changed between LC7 and LC8 in ways that didn't conflict with @livecodesebastien's changes to fix bug 16308?

**Comment by peter-b** [comment]
Is it actually possible to deploy from LiveCode 8 using Xcode 4.6?

**Comment by livecodesebastien** [comment]
@peter-b > for LiveCode 8 on with Xcode 4.6, that's a @runrevmark question.
As for a potential non-conflicting change, I'm not sure: nothing is found by `git diff develop-7.0 sebastien/merge-develop-7.0_181115 -- engine/src/fieldrtf.cpp`

**Comment by livecodeali** [comment]
Strange that it's fine on Mac - there doesn't seem to be anything platform-specific in the rtf code.

**Comment by livecodeali** [comment]
Could it be the upper case T in the rtfText.livecodescript somehow? IIRC all the other test filenames are lower case. 

Scratch that, just checked and they aren't.

**Comment by livecodesebastien** [comment]
3fbf599 is a clean merge so
@livecode-vulcan review ok 3fbf599

**Comment by livecode-vulcan** [comment]
💙 review by @livecodesebastien ok 3fbf599821f217d2dfd44cd474aeb4abeffa673a

**Comment by livecode-vulcan** [comment]
😞 test failure 3fbf599821f217d2dfd44cd474aeb4abeffa673a
- try-community-linux-x86: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1239)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1251)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1236)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1244)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1255)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1255)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1259)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 04ba384

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 04ba384fe4dad8379e22222e8a39fdd5a698d60b

**Comment by livecode-vulcan** [comment]
😎 test success 04ba384fe4dad8379e22222e8a39fdd5a698d60b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1242)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1254)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1239)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1247)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1258)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1258)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1262)

**Pull request merged**
