### PR TITLE
[[ External selection handles ]] Make selection handles circular and sit outside the rect of the control

### PR DESCRIPTION
**Pull request by livecodeali**
- This also allows controls to be resized to zero-width or height.
- Fixes bug 16117

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 25c6aaf

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 25c6aaf11adb28c004c3412661459af6e58f6d25

**Comment by livecode-vulcan** [comment]
😎 test success 25c6aaf11adb28c004c3412661459af6e58f6d25
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/680)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/693)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/681)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/683)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/693)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/704)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/695)

**Comment by mwieder** [comment]
Ali- this is an awesome addition. Thanks so much.

**Comment by runrevmark** [comment]
@mwieder: Thanks! I was concerned people might find it disconcerting!

Originally @livecodeali put in a patch to adjust the minimum object size - I must confess neither of us liked that patch at all.

Then in discussion about it we realized we had all the pieces in the engine to do it 'properly' just waiting to be used (as a result of various other things over the years). I think we were both slightly surprised when it did just work (of course, famous last words, I'm sure there's some gremlins lurking somewhere we haven't forseen!).

**Comment by montegoulding** [comment]
I like it but aesthetically it would be nice if the tabs were antialiased. Their pixelated edges jumped out at me

**Comment by montegoulding** [comment]
@peter-b sent me some covert scan issues related to lcidlc because I guess I'm the only one interested in lcidlc ;-) Anyway mixed in was one that's as a result of this change I think:

```
*** CID 117571:  Incorrect expression  (DIVIDE_BY_ZERO)
/engine/src/control.cpp: 1359 in MCControl::continuesize(short, short)()
1353                else
1354                    newrect.height = ly - newrect.y;
1355            }
1356        if (MCmodifierstate & MS_SHIFT)
1357        {
1358            double newaspect;
   CID 117571:  Incorrect expression  (DIVIDE_BY_ZERO)
   In expression "newrect.height / (double)newrect.width", division by expression "newrect.width" which may be zero has undefined behavior.
1359            newaspect = newrect.height / (double)newrect.width;
1360
1361            if (aspect < newaspect)
1362            {
1363                int2 newheight;
1364                newheight = (int2)(newrect.width * aspect);
```

The problem is now that the control width can be zero we get divide by zero issues here when shift is down and it's trying to maintain aspect ratio. Possibly resolve by setting a minimum aspect ratio when shift is down to height : 1? Anyway @livecodeali I'll leave this one for you to work out how you want it to behave. Also while you are fixing I'm not sure why the new height and width are declared as int2 when the rect wants a uint2. You could kill a couple of warnings there...

**Comment by runrevmark** [comment]
@montegoulding: Thanks for the heads-up on the coverity warning :) Also, it is easy enough to make the handles anti-aliased - we'll make sure that is done.

**Comment by runrevmark** [comment]
I've filed these two things as:

http://quality.runrev.com/show_bug.cgi?id=16201

and

http://quality.runrev.com/show_bug.cgi?id=16202

**Pull request merged**
