### PR TITLE
[[ Bug 14441 ]] Reinstate server-specific waiting loop for pipe readi...

### PR DESCRIPTION
**Pull request by livecodesebastien**
...ng in MCLinuxDesktop::Shell

### CODE REVIEW

**Comment by runrevmark** [comment]
How does the code which calls the low-level shell() function differ between server and desktop?

As written the server variant of the low-level shell() does an implicit way... But then surely that is repeated in the caller (since desktop does a ::wait()). That's the only question I have with regard this specific patch.

On a more general note (that won't necessarily stop me from being happy for this to be merged now)...

I wonder if there would be some means to make it so that wait() when running on server is a little more sensible - so that the same code could be used everywhere (except at the SystemInterface level - where some difference might be needed).

Indeed, further thought suggests this - the difference between server and desktop from the point of view of 'wait' is that on Desktop you have event stream + fd stream; on server you just have the latter - so I wonder if that is the way to play things.

**Comment by peter-b** [comment]
We really need to rework the main loop so that events on file descriptors (e.g. pipes to subprocesses) get picked up as system events... (i.e. they get plumbed into the poll call at `lnxdce.cpp:415`).

**Comment by livecodesebastien** [comment]
That bug fix brings the server `shell` back to what it was in 6.7 - the addition of the 'better' handling of `poll()` return value is simply that when `read()` was returning `EGAIN`, sometimes `poll()` was returning `EINTR` in 7.0 (something that wasn't happening in 6.7).
As for wait on server... I think most of our server slowdown problems come from the fact `MCS_poll` on server simply sleeps for the given time - and that Linux server and Linux desktop are (more or less) the same in 7.0, including calls to `MCscreen::wait` (in which `MCS_poll` is called). Implementing a proper MCS_poll for server might be what we need, in a further step.

**Comment by runrevmark** [comment]
@peter-b: Yes - same on Mac - you can plumb FDs into the CFRunLoop logic.

@runrevsebastien: That's cool - cleaning up waiting is something which can wait until later :)

**Comment by runrevmark** [comment]
Reviewed-by: @runrevmark.

**Pull request merged**
