### PR TITLE
Example C++ unit test framework

### PR DESCRIPTION
**Pull request by livecodestephen**
This is a quick example of a C++ unit test that I hacked together using google test.  This is a test that could go with #2833.

### CODE REVIEW

**Comment by runrevmark** [comment]
This certainly seems quite simple... Can you explain how google test works in this scenario? I notice you've put a target which wraps server (engine-ctest)... Does googletest hijack main when compiled into a project?

**Comment by livecodestephen** [comment]
Google test provides a `main()` that you can use, or you can provide your own.  The one provided by googletest is really simple:

```
GTEST_API_ int main(int argc, char **argv) {
  printf("Running main() from gtest_main.cc\n");
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```

I'd envisage one test executable for each library, so you'd have `libfoundation-ctest`, `libgraphics-ctest`, etc.  `engine` is probably the hardest as there is already a `main()`.  As a quick hack I set a linker flag to ignore multiple definitions so the `main()` that comes first wins, which happens to be the one from googletest.  I don't fully understand the gyp build system, so I just hack something together that seemed to work, I'm sure someone who understands this better could do a better job.

This probably doesn't build on anything other than linux -- I suppose Mac might work -- it creates the test runner at `./build-linux-x86_64/livecode/out/Debug/engine-ctest`.  There are various options for running the tests and different output formats, just add `--help` for more info.

**Comment by runrevmark** [comment]
Okay - that's starting make sense :)

So - we'd have a 'test' exe for each library, and then each engine type (server, dev, standalone, installer) which we would build and then run after?

I wonder if there's anything we can do about the muldefs thing for main. Perhaps factor out the 'main' functions in all our exe targets somehow so the test ones use a different implementation?

**Comment by livecodestephen** [comment]
It is just the `main` symbol that causes problems.  You could create a library from all the object files that don't contain a `main` and then just link against that. That would mean that you couldn't test any function defined in the same compilation unit as a `main()`, but that might not be too much of a compromise.

**Comment by runrevmark** [comment]
Another googletest related question... Can it collect timing info?

**Comment by livecodestephen** [comment]
This is the output I get from running the test:

```
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from lextable
[ RUN      ] lextable.factor_table
../../engine/ctest/test_lextable.cpp:23: Failure
Expected: (strcmp(factor_table[i].token, factor_table[i+1].token)) < (0), actual: 2 vs 0
"cmdname" comes before "codeunits"
[  FAILED  ] lextable.factor_table (0 ms)
[----------] 1 test from lextable (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] lextable.factor_table

 1 FAILED TEST
```

It seems to include a time, so I guess the answer is yes.

**Comment by livecodestephen** [comment]
From https://code.google.com/p/googletest/wiki/AdvancedGuide#Suppressing_the_Elapsed_Time:

> By default, Google Test prints the time it takes to run each test. To suppress that, run the test program with the --gtest_print_time=0 command line flag. Setting the GTEST_PRINT_TIME environment variable to 0 has the same effect.

**Comment by runrevmark** [comment]
Well this certainly satisfies the 'super-simple' requirement :)

I guess the only two things I have a little concern over are:
- TAP output: our LCB unittest stuff outputs TAP which @peter-b suggested was the most useful thing to output... Can we make google-test do the same so we can unify the testing stuff at least in terms of results (assuming that is desirable and/or makes sense)?
- the addition of a dreaded submodule

Now, to be fair, the submodule thing is probably something we are going to want to do a lot more with extensions in 8 when we start separating things out so it is perhaps not too much of a concern. However, given the mess people seem to get into with submodules, before we add another one it's probably worth exploring what we can do to make them easier to manage / more robust in terms of usage.

**Comment by livecodestephen** [comment]
For TAP there is https://github.com/kinow/gtest-tap-listener but I have no idea how that works.

I went for a submodule here as it was the quickest way to get the code and keep it's origin clear.  I'm undecided whether submodules are either really neat, or a hideous maintenance nightmare :smile:.   In this case it's thirdparty code that we are unlikely to want to modify, so submodules probably make sense.

**Comment by livecodestephen** [comment]
Just added TAP output using code from https://github.com/kinow/gtest-tap-listener.  This now creates `.tap` files when the test is run.

The API (https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#extending-google-test-by-handling-test-events) is fairly straight forward, so it might be better to do our own implementation.

**Comment by livecodestephen** [comment]
Replaced by a proper implementation  in #2924

**Pull request closed without merging**
