### PR TITLE
[[ Docs ]] Fix mangled references

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok  53004c5

**Comment by montegoulding** [comment]
IDE tests crashed here too.

**Comment by asayd** [comment]
@livecodeali So this cleanup was done by a script that automatically fixes these mangled references in the _source_ documents, correct? It's not just post-processing to display them properly?

**Comment by livecodeali** [comment]
@montegoulding I think @livecode-vulcan doesn't like not being the first thing in the comment

**Comment by livecodeali** [comment]
@asayd Yes, that's correct!

**Comment by asayd** [comment]
@livecodeali Brilliant! That will cut down on a lot of manual editing. Now we just need to get you or @montegoulding to write a script to add html5 as an OS wherever appropriate.

**Comment by montegoulding** [comment]
@asayd the difficulty there is it would be hard for a script to know what works and what doesn't in HTML5. One thing I have proposed is that we change the way the OS and platform elements work. I think we could do the following which should be backwards compatible:
- no element means it functions on all
- `<element> (excluding): <item delimited list>` - supported on any platform/OS but those listed
- `<element>: <item delimited list>` = supported only on the platform/OS listed

We often either know which platform/OS something is supported on or we know which it is unsupported on so I think the above would match our development workflow better than always having to list every platform/OS something is supported on. Given the large proportion of the language supported everywhere I think it will also reduce maintenance.

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 53004c5

Let's try this again

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 53004c5ada7d4cffe382cbdc2ce64f64a18622bc

**Comment by livecode-vulcan** [comment]
😎 test success 53004c5ada7d4cffe382cbdc2ce64f64a18622bc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/485)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/490)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/485)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/485)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/491)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/485)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/485)

**Pull request merged**
