### PR TITLE
Update of the OSX printing code for 64-bit compatibility

### PR DESCRIPTION
**Pull request by livecodefraser**
This should also resolve some of the issues that occur when trying to build 32-bit OSX engines with recent SDK versions.

### CODE REVIEW

**Comment by livecodefraser** [comment]
Printing is not generally amenable to automated testing (unless your printer's output feeds directly into a scanner :wink:) but this has been tested manually to ensure that printing still works as it did before.

**Comment by runrevmark** [comment]
So - two questions...

1) What happens if you use a printer settings blob from an old version in the new?

2) Is there a way to provide a dialog similar to what you would see in non-debug mode in a standalone?

**Comment by livecodefraser** [comment]
1) I don't know! They're binary blobs containing embedded XML. The XML bit is the same, the binary bit is not and I can't tell if that is normal variation or a different format. The docs make no mention of compatibility (in fact, they tell you that they don't recommend saving and restoring settings blobs between print runs and would prefer it to be configured manually each time). I'd guess that the formats are compatible but I can't guarantee it.

2) Apple have removed all the CorePrinting APIs that show a 'Printing...' dialogue in 64-bit and I've not been able to find a replacement. A quick survey of other apps is that some don't show anything at all and others create a sheet. The NS printing API includes a runOperationModalForWindow:delegate:didRunSelector:contextInfo: message in NSPrintOperation that looks like a candidate but using it would require us to use an NSView for printing and I don't know how feasible that is.

**Comment by runrevmark** [comment]
Fair enough :)

We'll need to do something about the dialog thing on 64-bit at some point - we should be able to provide our own easily enough (it is just a progress bar with a cancel button).

In regards to the format stuff - as long as it doesn't crash if you use the old settings with the new code there isn't a problem. After all, the settings tend to be printer specific in any case, so you lose them as soon as you switch printer.

We aren't producing a 64-bit build _yet_ so as long as we document these things before we do, it should be fine.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 59c2d8a

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 59c2d8aaa4481493e24329dd045fffb1735f03b8

**Comment by livecode-vulcan** [comment]
😎 test success 59c2d8aaa4481493e24329dd045fffb1735f03b8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/954)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/962)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/951)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/955)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/964)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/973)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/968)

**Pull request merged**
