### PR TITLE
[[ Docs ]] Fix formatting error in repeat.lcdoc

### PR DESCRIPTION
**Pull request by asayd**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 02b37bf

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 02b37bf903394b76c9bbec44e6d28dd08bba85c9

**Comment by asayd** [comment]
@montegoulding I of course noticed that you had back-ported a bunch of docs fixes to the develop-X.X branch. Should I re-base this one on that? I looked at it, but saw that the previous fixes weren't yet incorporated into that branch.

**Comment by livecode-vulcan** [comment]
😎 test success 02b37bf903394b76c9bbec44e6d28dd08bba85c9

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/637)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/653)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/627)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/570)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/573)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/631)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/651)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/636)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/653)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/635)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/646)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/668)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/632)

**Comment by montegoulding** [comment]
@asayd the backport is merged now. Keep contributing on develop until I backport the docs tests. I will do another backport that includes the tests and then we can recommend contributions be made to develop-8.2.

**Pull request merged**
