### PR TITLE
[[ Bug 22097 ]]  Docs: effective rect of stack docs should mention need for the stack to have been opened

### PR DESCRIPTION
**Pull request by researchware**

### CODE REVIEW

**Comment by livecodepanos** [comment]
Thanks @researchware for the PR.

Could you also add a bugfix note, as described in the first comment in https://github.com/livecode/livecode/pull/7109?

Also, this is fine for this PR, but for future reference, the base for community PRs that include dictionary updates should be branch `develop-9.0`. This means the change will appear in LC 9.0.x, and then we will merge `develop-9.0` into `develop`, so as the change appears in LC 9.5.x as well.

So in the future, you have to create your branch (that will include the change) from `develop-9.0`, and submit the PR against `develop-9.0` - as you did with this PR: https://github.com/livecode/livecode/pull/7109

**Comment by livecodepanos** [comment]
@researchware I have edited the release note  -for future reference the first letter should be uppercase.

Thank you for the PR

@livecode-vulcan review ok fb788a4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok fb788a4342578f0dcc017f3acf054fb44a70f059

**Comment by livecode-vulcan** [comment]
😎 test success fb788a4342578f0dcc017f3acf054fb44a70f059

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/599)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/8)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/8)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/8)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/8)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2125)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/350)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/346)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2154)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2141)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2140)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2174)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2114)

**Pull request merged**
