### PR TITLE
Turn on -Werror=unknown-pragmas

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 58dbb35

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 58dbb356261222d9221833f70503fc5d4af50fc8

**Comment by livecode-vulcan** [comment]
😎 test success 58dbb356261222d9221833f70503fc5d4af50fc8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/186)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/190)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/186)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/186)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/190)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/186)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/186)

**Comment by montegoulding** [comment]
@livecode-vulcan review by @peter-b ok dae05cd

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok dae05cdcf4820b481313b2164ff487087ec76425

**Comment by livecode-vulcan** [comment]
😎 test success dae05cdcf4820b481313b2164ff487087ec76425
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/189)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/193)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/189)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/189)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/193)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/189)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/189)

**Comment by montegoulding** [comment]
@livecode-vulcan review by @peter-b ok 070e99d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 070e99d70316dc8458b8a0afc627064774e8ebdc

**Comment by livecode-vulcan** [comment]
😞 test failure 070e99d70316dc8458b8a0afc627064774e8ebdc
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/204)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/208)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/204)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/204)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/208)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/204)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/204)

**Comment by montegoulding** [comment]
```
ld: warning: directory not found for option '-L../prebuilt/lib/ios/iphoneos10.0'
ld: library not found for -licui18n
```

**Comment by montegoulding** [comment]
@livecode-vulcan review by @peter-b ok 587917b

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 587917b1486afaafba12a9171b98dd81017f676b

**Comment by livecode-vulcan** [comment]
😎 test success 587917b1486afaafba12a9171b98dd81017f676b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/214)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/218)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/214)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/214)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/218)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/214)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/214)

**Pull request merged**
