### PR TITLE
[[ Bug 15684 ]] Add bundle conversion method so we can include extras bundle in launch data.

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by peter-b** [comment]
Hi @runrevian, could you please update the title/description of this PR with a summary of the changes? Thanks! :smile:

**Comment by livecodeian** [comment]
The description was originally ok until I added a second commit. Have copy/pasted the description from the 1st commit.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 29f32e9

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 29f32e9898eb6620aee1c0b43ec3516affd5f7ac

**Comment by livecode-vulcan** [comment]
😎 test success 29f32e9898eb6620aee1c0b43ec3516affd5f7ac
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/3)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/3)
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/3)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/3)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/3)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/3)

**Comment by livecodesebastien** [comment]
Hi Ian, can you rebase this pull request against release-7.1.0? That's a fix for a regression in the end, so it should be merged in for 7.1.0 RC 2. Thanks

**Comment by livecodesebastien** [comment]
This pull request is superseded by https://github.com/runrev/livecode/pull/2739

**Pull request closed without merging**
