### PR TITLE
Gyp rejig warnings 8.0

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok b425753

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b4257537f8f808db3af7976e937c0b04ffadabb4

**Comment by peter-b** [comment]
Looks like you didn't push your `thirdparty` changes. :disappointed:

**Comment by peter-b** [comment]
@livecode-vulcan retry b425753

**Comment by livecode-vulcan** [comment]
😞 test failure b4257537f8f808db3af7976e937c0b04ffadabb4
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/275)
- try-win-x86: [pending](https://vulcan.livecode.com/builders/try-win-x86/builds/338)
- try-ios: [failure](https://vulcan.livecode.com/builders/try-ios/builds/221)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/286)
- try-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/221)
- try-mac: [pending](https://vulcan.livecode.com/builders/try-mac/builds/213)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 59695ed

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 59695ed8a195fa1833fb0f1432b383fa2b219f48

**Comment by livecode-vulcan** [comment]
😞 test failure 59695ed8a195fa1833fb0f1432b383fa2b219f48
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/278)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/341)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/224)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/289)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/224)
- try-mac: [failure](https://vulcan.livecode.com/builders/try-mac/builds/216)

**Comment by livecodefraser** [comment]
@livecode-vulcan retry 59695ed

**Comment by livecode-vulcan** [comment]
😎 test success 59695ed8a195fa1833fb0f1432b383fa2b219f48
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/289)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/352)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/235)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/300)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/235)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/227)

**Pull request merged**
