### PR TITLE
[[ iOS 9.1 ]] update

### PR DESCRIPTION
**Pull request by livecodesebastien**
Clean merge, plus 2 refactored changes:
- brings what was changed in ide/Installer/package.txt in `develop-6.7` in Installer/package.txt
- update `prebuilt/scripts/ios.inc` to build prebuilts for iOS 9.1

Conflicts:
    prebuilt

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok b192dc0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b192dc088df07ff9b3886eeaf8f7836fee5834fa

**Comment by livecode-vulcan** [comment]
😞 test failure b192dc088df07ff9b3886eeaf8f7836fee5834fa
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/833)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/847)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/834)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/837)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/847)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/857)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/850)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 31f9582

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 31f958224fb88d7bc7b36319acbf501fb7c9c157

**Comment by livecode-vulcan** [comment]
😎 test success 31f958224fb88d7bc7b36319acbf501fb7c9c157
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/836)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/850)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/837)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/840)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/850)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/860)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/853)

**Pull request merged**
