### PR TITLE
[[ LinuxUninstaller ]] Fix two bugs with Linux uninstaller

### PR DESCRIPTION
**Pull request by livecodesebastien**
- 16411: change the name to match the architecture (like the executable) and remove the `.`
- 16410: make the uninstaller executable

### CODE REVIEW

**Comment by peter-b** [comment]
I think the installer stack looks for `.setup.x86` in order to decide if a directory is a LiveCode installation directory.  Might be worth checking if that code needs updating too!

**Comment by livecodesebastien** [comment]
The stack Installer.rev has been updated to deal with the different editions, when checking that a location is not a LiveCode install.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 183cc2d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 183cc2de0d3eb1dd2f2d6b9387603dd6e45f5119

**Comment by livecode-vulcan** [comment]
😎 test success 183cc2de0d3eb1dd2f2d6b9387603dd6e45f5119
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1277)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1288)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1273)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1283)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1294)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1293)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1298)

**Pull request merged**
