### PR TITLE
system: Add support for accessing system error information.

### PR DESCRIPTION
**Pull request by peter-b**
Add the following LCB syntax:
- `reset system error`: Reset system code to "none" (i.e. 0)
- `the system error code`: The current numerical error code
- `the system error message`: A string describing the current
  error code.

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 8971469

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 8971469271c4d0dbd8d5de3b8113b3b11ef47dd9

**Comment by livecode-vulcan** [comment]
😞 test failure 8971469271c4d0dbd8d5de3b8113b3b11ef47dd9
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/48)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/48)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/48)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/48)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/48)
- try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/48)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/48)

**Comment by peter-b** [comment]
@livecode-vulcan retry 8971469271c4d0dbd8d5de3b8113b3b11ef47dd9

**Comment by livecode-vulcan** [comment]
😞 test failure 8971469271c4d0dbd8d5de3b8113b3b11ef47dd9

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/66)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/65)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/52)
* try-community-universal-ios-iphoneos10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.2/builds/70)
* try-community-universal-ios-iphonesimulator10.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.2/builds/70)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/64)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/66)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/68)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/70)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/68)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/70)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/70)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/66)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 73106d6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 73106d63a35f24e75ea7bb2e9e9eb38ea14335f3

**Comment by livecode-vulcan** [comment]
😎 test success 73106d63a35f24e75ea7bb2e9e9eb38ea14335f3

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1111)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1127)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1101)
* try-community-universal-ios-iphoneos11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.2/builds/54)
* try-community-universal-ios-iphonesimulator11.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.2/builds/54)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1106)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1128)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1111)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1127)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1110)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1120)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1143)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1106)

**Pull request merged**
