### PR TITLE
Bugfix/license check compile issues

### PR DESCRIPTION
**Pull request by montegoulding**
Some issues identified while implementing the license checks

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 50ffd04

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 50ffd04e8b4dcd4a6d4e753563a22873ac63f1cb

**Comment by livecode-vulcan** [comment]
😞 test failure 50ffd04e8b4dcd4a6d4e753563a22873ac63f1cb
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1854)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1867)
- try-community-linux-x86_64: [failure](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1848)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1860)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1870)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1873)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1879)

**Comment by montegoulding** [comment]
Any idea why this failed?

**Comment by peter-b** [comment]
@livecode-vulcan retry 50ffd04

**Comment by livecode-vulcan** [comment]
😎 test success 50ffd04e8b4dcd4a6d4e753563a22873ac63f1cb
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1855)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1868)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1849)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1861)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1871)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1874)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1880)

**Pull request merged**
