### PR TITLE
Do not split up .framework folders between MacOS and Resources/_MacOS…

### PR DESCRIPTION
**Pull request by trevordevore**
… folder

### CODE REVIEW

**Comment by trevordevore** [comment]
@montegoulding I was struggling to get the rebase to work properly so I just created a new PR.

**Comment by montegoulding** [comment]
Ah... sorry @trevordevore rebase is often very confusing in GUI tools... I found the sourcetree rebase nearly impossible to use. On command line it's easy:
```
git rebase --onto=develop-9.0 develop
```

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 378b319

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 378b3193acc70c34da26b317bd28f5f99b5265bd

**Comment by trevordevore** [comment]
@montegoulding thanks for the tip. I only use the command line for rebasing but I didn’t realize I needed to use ‘onto’. I haven’t had to use that in my work before. I’ll use that next time.

**Comment by montegoulding** [comment]
You use `onto` when you are rebasing from one branch to another.

**Pull request merged**
