### PR TITLE
lc-compile: Add short options (-o and -I)

### PR DESCRIPTION
**Pull request by peter-b**
Add `-o` (same as `--output`) and `-I` (same as `--modulepath`).

Other minor updates to lc-run and lc-compile usage messages.

### CODE REVIEW

**Comment by livecodestephen** [comment]
Am I correct in thinking that lc-compile actually creates a file in the module path?  If so then perhaps `-I` is not the best choice as the behaviour is subtly different to, say, `gcc`.

**Comment by peter-b** [comment]
It does.  However, this morning @runrevmark was discussing changing that behaviour.

**Comment by runrevmark** [comment]
Yes - the idea is that the compiler will be able to infer interfaces directly from the lcm files (rather than having to use lci files -- the latter are generated from the lcm content anyway).

This would mean that there would be no interface generation and it would be up to the user of lc-compile to ensure that any modules they might want to 'use' get put into a suitable module search path.

That being said, this does still need a fair bit of refinement - particular in terms of working out what the IDE should do when a package is installed!

**Comment by runrevmark** [comment]
I think this is fine - @livecodestephen is correct that -I behavior is different from C compilers at the moment but it is almost the same thing now and will entirely be the same thing in a subsequent revision.

On balance, having the contractions is probably better than not having them as it simplifies build scripts.

Reviewed-by: @runrevmark.

**Comment by peter-b** [comment]
On further discussion with @runrevmark,the semantics of the command-line options to **lc-compile** -- and, to some extent, **lc-run** are still in need of some revision, so we'll live with verbose command-lines until that's done.

**Pull request closed without merging**
