### PR TITLE
[[ Bug 20917 ]] Fix display of <> in markdown

### PR DESCRIPTION
**Pull request by trevordevore**
I chose to escape the instances of <> with code.

### CODE REVIEW

**Comment by livecodepanos** [comment]
Thanks for the PR @trevordevore. Could you also please add a bugfix note?

**Comment by trevordevore** [comment]
@livecodepanos - this was really just a docs change, not a bug fix. Does it need a bugfix note? I don’t know the exact cause, but I think that <> is used for referencing other items in the docs so the parser tried to resolve those links and can’t. I just wrapped the text in tick marks so they aren’t treated as normal text.

**Comment by livecodepanos** [comment]
@trevordevore Yes, every issue (either in docs, engine or IDE) needs a bugfix note if there is a corresponding report in BugZilla. In this case you just have to create a file `docs/notes/bugfix-20917.md` which will contain a short description, which will appear in the release notes. In this case you can just put:

`# Fixed broken links in "URL scheme" entry` 

Now, regarding the change, yes <> is used for referencing other items in the docs. I think it would be better if instead of escaping the <>, you change `HTTP` and `FTP` to `http` and `ftp`. It seems the parser is case sensitive, so if you do that the links will work.

**Comment by livecodepanos** [comment]
Off-topic, I edited your comment to reference @livecodepanos, as @panos is a different existing GitHub user :)

**Comment by trevordevore** [comment]
@livecodepanos I've made changes. Take a look.

**Comment by livecodepanos** [comment]
Thanks @trevordevore 

@livecode-vulcan review ok 4151d03

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 4151d033dca9d4de73e1c07455d5dc099d02fdfd

**Comment by livecode-vulcan** [comment]
😎 test success 4151d033dca9d4de73e1c07455d5dc099d02fdfd

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/151)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/143)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/143)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/143)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/143)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1665)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/47)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/47)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1695)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1688)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1685)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1721)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1662)

**Pull request merged**
