### PR TITLE
Don't link with standard libraries when pre-linking iOS standalone

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 1690d0f

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 1690d0f

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 1690d0f7443a8033b6f9e5d3184601c8d4531146

**Comment by livecode-vulcan** [comment]
😎 test success 1690d0f7443a8033b6f9e5d3184601c8d4531146
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/180)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/179)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/180)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/175)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/182)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/179)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/183)

**Pull request merged**
