### PR TITLE
build: Compile for deployment on Mac OS X 10.9 with libc++

### PR DESCRIPTION
**Pull request by peter-b**
In the future, we would like to make more use of C++11 standard library features, such as `std::unique_ptr`.  This requires the use of a newer C++ standard library on Macs, which in turn requires deploying with a minimum deployment target of Mac OS X 10.9.

In LiveCode 9, we are already planning to end support for Mac OS X 10.8 and lower, in accordance with our current platform support policy.

### CODE REVIEW

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 317452d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 317452d4caeec64e782356437b5a2c1982b1a91c

**Comment by peter-b** [comment]
N.b. the LiveCode 9 release notes already announce EOL for Mac OS X 10.6/10.7/10.8 support.

**Comment by livecode-vulcan** [comment]
😞 test failure 317452d4caeec64e782356437b5a2c1982b1a91c

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/730)
* try-community-mac: [failure](https://vulcan.livecode.com/builders/try-community-mac/builds/731)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/728)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/729)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/735)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/726)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/727)

**Comment by peter-b** [comment]
@livecode-vulcan review by @livecodefraser ok 6fb2070

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 6fb2070949698360f37d01135c37dc487a58799e

**Comment by livecode-vulcan** [comment]
😎 test success 6fb2070949698360f37d01135c37dc487a58799e

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/738)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/743)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/736)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/737)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/743)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/734)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/735)

**Pull request merged**
