### PR TITLE
[[ IDE ]] Fix remaining uses of revSetEdited

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by livecodeali** [comment]
I'm not sure why this backport is necessary... `revSetEdited` was deleted in develop, not develop-8.1 (https://github.com/livecode/livecode-ide/pull/1434/files)

**Comment by livecodeian** [comment]
@livecodeali the ide submodule in develop-8.1 points to a branch that has your revIDESetEdited changes in it. Do you think that was in error?

**Comment by livecodeali** [comment]
@livecodeian No it looks right, it's just that the _removal_ of `revSetEdited` was only done in develop - in develop 8.1 `revSetEdited` just calls `revIDESetEdited`. I mean, there's no harm in merging this anyway.

**Comment by livecodeian** [comment]
So looks like this was due to a problem with my checkout folder. Closing as this isn't needed.

**Pull request closed without merging**
