### PR TITLE
[[ Browser Widget ]] Change kind to com.livecode.widget.browser

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 40d6fef

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 40d6fef31e89dad3aab25a2e250f665da04e2ad3

**Comment by livecodeali** [comment]
This needs to wait until the other browser things are merged, so that they can be updated to use the new 'kind'.

**Comment by livecode-vulcan** [comment]
😎 test success 40d6fef31e89dad3aab25a2e250f665da04e2ad3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1109)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1118)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1106)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1111)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1122)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1127)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1127)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 423bd58

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 423bd586ff3f99c9ffe7ee02f4a03d6bfadfda2a

**Comment by livecode-vulcan** [comment]
😎 test success 423bd586ff3f99c9ffe7ee02f4a03d6bfadfda2a
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1116)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1126)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1113)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1119)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1130)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1134)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1135)

**Pull request merged**
