### PR TITLE
[[ Bug 15822 ]] Restore watchedVariables and breakpoints slightly more lax parsing

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
Replaces https://github.com/runrev/livecode/pull/2796

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay 09f0e85

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 09f0e853dca9e9cf2b1cdcf97d668626897ea9d8

**Comment by livecodeali** [comment]
@livecode-vulcan retry 09f0e85

**Comment by peter-b** [comment]
@livecode-vulcan retry 09f0e85

**Comment by livecode-vulcan** [comment]
😎 test success 09f0e853dca9e9cf2b1cdcf97d668626897ea9d8
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/230)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/229)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/230)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/225)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/232)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/228)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/233)

**Pull request merged**
