### PR TITLE
[[ Cleanup ]] Cleanup MCName API

### PR DESCRIPTION
**Pull request by runrevmark**
This patch cleans up the MCName API. It removes all MCName APIs in foundation-legacy.h - in particular MCAutoNameRef.

Additionally, it reworks the way MCN_ and MCM_ constants are created - making it table-based so hopefully reducing code footprint a bit.

Whilst a large patch, each individual cleanup is split up into separate commits - so I suggest looking at each individually.

Note: Marked as WIP as it will need a patch merged in commercial before this.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 505371a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 505371a65cf9bdbb232bbfb47ae2438091bb373d

**Comment by livecode-vulcan** [comment]
😞 test failure 505371a65cf9bdbb232bbfb47ae2438091bb373d

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/726)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/742)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/716)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/659)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/661)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/720)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/740)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/725)
* try-community-x86-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/742)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/724)
* try-community-x86_64-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/735)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/756)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/720)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 6ce7603

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 6ce76039f127441179e2c85361eb23a5b86613b1

**Comment by runrevmark** [comment]
This depends on https://github.com/livecode/livecode-private/pull/207 being merged first.

**Comment by livecode-vulcan** [comment]
😎 test success 6ce76039f127441179e2c85361eb23a5b86613b1

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/727)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/743)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/717)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/660)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/662)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/721)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/741)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/726)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/743)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/725)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/736)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/757)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/721)

**Comment by livecodeali** [comment]
I think we will have to merge this, update submodules and review the private repo PR won't we? Otherwise `MCNameIsEqualToCaseless` won't exist for the private one to pass

**Comment by montegoulding** [comment]
@runrevmark if `MCAutoNameRef` is gone can we just change `MCNewAutoNameRef` to `MCAutoNameRef`? Also the lookup APIs appear to be a bit out of style. Shouldn't they be `bool lookup(in, out)`

**Comment by runrevmark** [comment]
@livecodeali : I'll do a test by updating the submodule in the private PR and getting it to run through CI - if that works, then we can merge both.

**Comment by runrevmark** [comment]
@montegoulding Yeah - we can now change MCNewAutoNameRef to MCAutoNameRef - might be best done as a separate PR after this one is merged though. I'll take a look at the uses of MCNameLookupCaseless and see if the code is simpler if its in the more standard form.

**Pull request merged**
