### PR TITLE
[[ Merge 7.1.1 ]] 05-10-15 

### PR DESCRIPTION
**Pull request by livecodesebastien**
Changes on libgraphics/src/mblandroidtext.cpp applied to libgraphics/src/harfbuzztext.cpp
Changes on docs/dictionary/function/revOpenDatabase.xml applied to docs/dictionary/function/revOpenDatabase.lcdoc

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 13e0f96

**Comment by peter-b** [comment]
@livecode-vulcan review ok c91da8d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c91da8d52a1df049c7de71770e8ecef50fa27ef2

**Comment by livecode-vulcan** [comment]
😎 test success c91da8d52a1df049c7de71770e8ecef50fa27ef2
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/608)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/620)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/609)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/610)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/619)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/630)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/621)

**Pull request merged**
