### PR TITLE
[[ Community Docs ]] Tweak my incorrect Markdown for the Command Line…

### PR DESCRIPTION
**Pull request by alextweedly**
… instructions

### CODE REVIEW

**Comment by peter-b** [comment]
@alextweedly What do you think about putting that URL as an inline code block?  That way there's no chance of any of it being automatically hyperlinkified.

**Comment by alextweedly** [comment]
Good idea. I shied away from doing that because the other examples 
within the "command line" section were all command lines to be typed to 
a shell - but I do see that the earlier sections of the doc used code 
blocks for URLs, so I should do the same.

Thanks
Alex.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b77220b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b77220b99344db8dd2bc125d0f52761dbb42b375

**Comment by livecode-vulcan** [comment]
😎 test success b77220b99344db8dd2bc125d0f52761dbb42b375
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2351)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2361)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2344)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2362)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2368)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2372)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2384)

**Pull request merged**
