### PR TITLE
[[ LCB ]] Ensure Names maps to Strings when returning to lcb

### PR DESCRIPTION
**Pull request by runrevmark**
This patch ensures that the 'send' and 'execute script' engine LCB
commands both return values compatible with the builder type world.

In particular, they ensure that names (and recursive appearances
of names) are mapped to strings.

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevmark Is it possible to add a test for this at the moment, or do we need test system improvements?

**Comment by runrevmark** [comment]
@peter-b: It would be possible to write a test (e.g. execute script "return the version"; the result is a string is true) - however I'm not sure where to put it. This is LCB engine syntax - do we have a test module / place / mechanism for testing that?

**Comment by peter-b** [comment]
@runrevmark I think you can add a LCB library with a basename beginning with `_` somewhere under the LCS tests.  It _should_ be compiled before the LCS tests run (but that can easily be put in place if necessary).  The you could use `load extension` to load it during a `.livecodescript` test's `TestSetup` handler.  You could add a handler to the LCB file like:

```
public handler IsLCBHandlerArgumentString(in pValue)
   return pValue is a string
end handler
```

and then call it from the LCS test with a name.

**Comment by peter-b** [comment]
@runrevmark How did you verify that this works for `send`?  I can't find a good way of getting a valid `Object` from an LCB library.  `resolve script object "stack LoadedStackName"` appears to fail.

**Comment by peter-b** [comment]
Fixed differently in #4571.

**Pull request closed without merging**
