### PR TITLE
[[ LCB ]] Add --deps option to lc-compile

### PR DESCRIPTION
**Pull request by runrevmark**

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevmark I'm not sure it's worth doing the time-of-modification handling in lc-compile itself — it can be handled really easily in a wrapper script, and it would be nice to always get the same dependency list for the same input files no matter the build state!

**Comment by peter-b** [comment]
Also, I initially misread the title as "[[ LCB ]] WTF"…

**Comment by runrevmark** [comment]
@peter-b: There are now '--order' and '--changed-order' arguments which output the compile order for the input source files. If '--changed-order' is used then it only emits the input source files which need recompiling. Still to add '--deps'.

**Comment by peter-b** [comment]
What about:

``` bash
--deps make
--deps order
--deps changed-order
--deps         # same as --deps make
```

I can fix up the option parsing and `--help` output later, if that sounds good…

**Comment by runrevmark** [comment]
Sure - I'll tweak it... I've just implemented the '--deps' logic... It doesn't do any sorting, just lists the .lci file dependencies. e.g.:

```
com.foo.mymodule.lci: com.foo.othermodule.lci mymodule.lcb
```

Does that sound sufficient?

**Comment by peter-b** [comment]
Is there any way to add the .lci to .lcb dependencies to the output? If so I'd use it **immediately** for compiling vulcanbot :-D

**Pull request closed without merging**
