### PR TITLE
[CI] Use Travis CI containerised builders.

### PR DESCRIPTION
**Pull request by peter-b**
Move LiveCode to using the new Travis CI build infrastructure.

### CODE REVIEW

**Comment by peter-b** [comment]
Waiting for Travis CI to whitelist some of the Ubuntu packages that we need for building.

@livecode-vulcan review not ok 2b499d3

**Comment by livecode-vulcan** [comment]
💔 review by @peter-b not ok 2b499d3dbf4b3cb0b58783c5f75bccf5b66316f2

**Comment by peter-b** [comment]
- [x] liblcms1-dev ~~travis-ci/apt-package-whitelist#329~~ travis-ci/apt-package-whitelist#349
- [x] libesd0-dev travis-ci/apt-package-whitelist#328
- [x] libxv-dev travis-ci/apt-package-whitelist#330

**Comment by peter-b** [comment]
This patch doesn't affect anything other than Travis builds, so merging unreviewed.

**Pull request merged**
