### PR TITLE
Turn on -Werror=mismatched-new-delete

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 984e549

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 984e5497503f1174cbbb30fd4dcff8879b487141

**Comment by montegoulding** [comment]
@livecode-vulcan review by @peter-b ok b9802f0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok b9802f06af76aea07004e8fec64fd615d0688ca3

**Comment by livecode-vulcan** [comment]
😎 test success b9802f06af76aea07004e8fec64fd615d0688ca3
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/188)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/192)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/188)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/188)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/192)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/188)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/188)

**Pull request merged**
