### PR TITLE
[ Skia update ] Re-implement CoreText text rendering on top of Skia

### PR DESCRIPTION
**Pull request by livecodeian**

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecodeian I presume this doesn't suffer the same problem as on Win32 with regards LCD text type rendering not working against buffers with transparency?

**Comment by livecodeian** [comment]
@runrevmark Panos had filed a bug - http://quality.livecode.com/show_bug.cgi?id=19432 however I was unable to reproduce it. I've just yesterday managed to reproduce in a stack I created to test emoji support. I'll attach it to the bug report.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok d359761

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok d359761f623e132bf20d7eaf6679b953c0cd3104

**Comment by livecode-vulcan** [comment]
😎 test success d359761f623e132bf20d7eaf6679b953c0cd3104

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/281)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/291)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/270)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/213)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/214)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/280)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/284)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/283)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/289)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/283)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/289)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/308)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/279)

**Pull request merged**
