### PR TITLE
Changed <before> and <after> to <front> and <back> for the "to" syntax.

### PR DESCRIPTION
**Pull request by trevordevore**

### CODE REVIEW

**Comment by livecodeali** [comment]
Hi Trevor, the angle brackets shouldn't be round before, after, front or back either - it appears these were incorrectly specified as parameters in the xml, when they are actually just the strings.

Would you mind removing those and then moving the descriptions of the before/after/front/back variants to the Description section?

**Comment by trevordevore** [comment]
Done.

**Comment by livecodeali** [comment]
Awesome, thanks!
@livecode-vulcan review ok 0fa2aa6

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 0fa2aa6f423af7e540f545a46b36a7c8ed224efc

**Comment by livecode-vulcan** [comment]
😎 test success 0fa2aa6f423af7e540f545a46b36a7c8ed224efc
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/584)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/596)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/585)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/585)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/594)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/605)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/596)

**Pull request merged**
