### PR TITLE
[[ LCB ]] Improve builtin module emission and loading

### PR DESCRIPTION
**Pull request by runrevmark**
This patch reworks the way builtin modules are handled.

When lc-compile is run in --outputc mode, it will now emit a C
byte array for each module which is passed on the command line
along with a unique global class instance which calls
MCScriptRegisterBuiltinModule in its constructor. This function takes
a fixed format static record which contains the module data and its
(C) initializer and finalizer. When called, the function will link
the static record into a singly-linked list of builtin modules.

When MCScriptInitialize is called, it will now iterate through this
list loading each module, and setting each one's initializer and
finalizer. It will then ensure each builtin module is usable.

The initializer and finalizer are now called by libscript itself -
the initializer when the module is made usable, and the finalizer
when the module is (finally) destroyed.

This new mechanism means that builtin modules do not all have to be
compiled together into one C file, but compiled and linked into the
engine separately.

### CODE REVIEW

**Comment by runrevmark** [comment]
After much wrangling with static libs and linking options, I think this patch now finally works correctly on all platforms!

@livecodefraser : I'd appreciate you looking over the changes to the gyp files at least - in particular the engine_lcb_modules target. I've had to make it dependent on specific paths within PRODUCT_DIR on linux/android/win since the output of that target doesn't seem to go in PRODUCT_DIR directly. Perhaps this is just the way it is, but if there is a more appropriate var to use then please let me know!

**Comment by livecodefraser** [comment]
@livecode-vulcan review okay ec3981a

**Review by livecodefraser — APPROVED** [review]

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok ec3981aed2c1e56aec84d697461adc87b197e993

**Comment by livecode-vulcan** [comment]
😞 test failure ec3981aed2c1e56aec84d697461adc87b197e993

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/901)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/907)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/899)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/900)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/907)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/898)
* try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/898)

**Comment by runrevmark** [comment]
This PR requires VS2015 to be merged to build on Windows (as VS2015 introduced the /WHOLEARCHIVE option which we need to preserve our static constructors 😒 )

**Comment by runrevmark** [comment]
This should now work on Mac/iOS again and on Win (in VS2015).

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 93a6432

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 93a6432eada00ab3ef66b6bd98de26b190365fe7

**Comment by livecode-vulcan** [comment]
😞 test failure 93a6432eada00ab3ef66b6bd98de26b190365fe7

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/980)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/986)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/978)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/979)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/986)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1000)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/977)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 7318c98

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 7318c98d239b7d7a640ffebecccf2e9d9e34b08c

**Comment by livecode-vulcan** [comment]
😞 test failure 7318c98d239b7d7a640ffebecccf2e9d9e34b08c

* try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1130)
* try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/1132)
* try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1125)
* try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1131)
* try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/1135)
* try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1145)
* try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1126)

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 99b1611

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 99b1611c8b2e1ac09f3ccd5a0756517c31ac4bcd

**Comment by livecode-vulcan** [comment]
😎 test success 99b1611c8b2e1ac09f3ccd5a0756517c31ac4bcd

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1131)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1133)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1126)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1132)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1136)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1146)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1127)

**Pull request merged**
