### PR TITLE
Added support for building with Xcode10 / iOS 12 SDK

### PR DESCRIPTION
**Pull request by livecodepanos**
WIP for now, as Xcode10 is still in beta

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecodepanos it would be good to drop armv7 builds from 11+

**Comment by livecodepanos** [comment]
New OpenSSL and ICU prebuilts for iOS 12 are uploaded, so removing WIP

**Comment by livecodepanos** [comment]
@montegoulding It seems we do need the 32 bit slice for OpenSSL and ICU prebuilts even for iOS >= 11, at least for *device*, so as to support deployment to iOS min version < 11 in the standalone settings.

If we don't build the 32 bit slice we get some errors about undefined symbols for arch armv7.

I will add a new commit.

**Comment by montegoulding** [comment]
Hmm... @livecodepanos ok perhaps something to do later... maybe involves removing it from other places

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 1d9a0e5

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 1d9a0e5cca9e66fa286bc41c5816f18d9448564b

**Comment by livecode-vulcan** [comment]
😎 test success 1d9a0e5cca9e66fa286bc41c5816f18d9448564b

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/104)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/96)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/96)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/96)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/96)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1618)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/0)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/0)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1648)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1641)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1638)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1674)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1615)

**Pull request merged**
