### PR TITLE
[[ Documentation ]] Formatting fix to capStyle.lcdc

### PR DESCRIPTION
**Pull request by asayd**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 032b981

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 032b981276df309eec747b35085155dbab993d07

**Comment by livecode-vulcan** [comment]
😞 test failure 032b981276df309eec747b35085155dbab993d07
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/529)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/534)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/529)
- try-community-emscripten: [failure](https://vulcan.livecode.com/builders/try-community-emscripten/builds/533)
- try-community-ios: [pending](https://vulcan.livecode.com/builders/try-community-ios/builds/538)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/530)
- try-community-android-armv6: [failure](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/530)

**Comment by montegoulding** [comment]
@livecode-vulcan try 032b981

**Comment by livecode-vulcan** [comment]
😎 test success 032b981276df309eec747b35085155dbab993d07
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/546)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/551)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/546)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/550)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/555)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/547)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/547)

**Pull request merged**
