### PR TITLE
Merge develop 9.0 25.09.2018

### PR DESCRIPTION
**Pull request by livecodepanos**
Conflicts in `treeview.lcb`, because of PRs https://github.com/livecode/livecode/pull/6675/files (`develop-9.0`) and https://github.com/livecode/livecode/pull/6676/files (`develop`):

screen shot 2018-09-25 at 12 39 24

screen shot 2018-09-25 at 12 38 59

### CODE REVIEW

**Comment by livecodepanos** [comment]
@bwmilby Did I miss anything while resolving conflicts in file `extensions/widgets/treeview/treeview.lcb`?  :)

**Comment by bwmilby** [comment]
> @bwmilby Did I miss anything while resolving conflicts in file `extensions/widgets/treeview/treeview.lcb`? :)

There is some extra code (1707-1709, 1722 doesn't need the second part after the and)
The `redraw all` is actually not going to fire properly if mScrollHilitedElementIntoView is true.

Here is a proposed merge of the logic that is used in the 2 branches:

```
if mSelectedElement is nothing or tPathNotAlreadySelected or \
      mScrollHilitedElementIntoView then
   if pPath is not the empty list and \
         not applyToNode(selectKey, pPath, 0, 1, mDataList, mData) then
      put nothing into mSelectedElement
   end if
   if tPathNotAlreadySelected then
      post "hiliteChanged"
   end if
   redraw all
end if
```

I'm working on an update that will expand the tree to display the selected element which is going to modify this further (actually make it simpler in this section of code, validation will take place before calling this handler).

**Comment by livecodepanos** [comment]
Thank you @bwmilby

**Comment by bwmilby** [comment]
Glad to assist.  I'll wait for this to merge before submitting anything else on the widget.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 9adf98c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 9adf98cccef7eb8950cee3a9c5b2e1197ebf6fac

**Comment by livecode-vulcan** [comment]
😞 test failure 9adf98cccef7eb8950cee3a9c5b2e1197ebf6fac

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/123)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/115)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/115)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/115)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/115)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1637)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/19)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/19)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1667)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1660)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1657)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1693)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1634)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 9adf98c

**Comment by livecode-vulcan** [comment]
😞 test failure 9adf98cccef7eb8950cee3a9c5b2e1197ebf6fac

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/125)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/117)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/117)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/117)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/117)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1639)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/21)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/21)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1669)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1662)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1659)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1695)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1636)

**Comment by livecodepanos** [comment]
@livecode-vulcan retry 9adf98c

**Comment by livecode-vulcan** [comment]
😎 test success 9adf98cccef7eb8950cee3a9c5b2e1197ebf6fac

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/126)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/118)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/118)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/118)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/118)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1640)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/22)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/22)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1670)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1663)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1660)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1696)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1637)

**Pull request merged**
