### PR TITLE
Merge 7.0 into 8.0

### PR DESCRIPTION
**Pull request by livecodefraser**

### CODE REVIEW

**Comment by peter-b** [comment]
Could you please summarise the conflicts?

**Comment by peter-b** [comment]
Unfortunately the Github user interface makes it really difficult to review merges...

**Comment by livecodefraser** [comment]
Both branches:
- changed the version number
- added new methods to the end of MScreenDC in lnxdc.h
- added new functions to the end of uidc.h

Additionally, changes were made to the Linux and Android build settings to change -Og to -O0 in 6.7 but these have been refactored in 8.0 (to aid cross-compiling).

**Comment by peter-b** [comment]
@livecode-vulcan review ok 591af70

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 591af70587dbc3e061a4a4a7c386452e6f432e1b

**Comment by livecode-vulcan** [comment]
😎 test success 591af70587dbc3e061a4a4a7c386452e6f432e1b
- try-linux-x86: [success](https://vulcan.livecode.com/builders/try-linux-x86/builds/313)
- try-win-x86: [success](https://vulcan.livecode.com/builders/try-win-x86/builds/376)
- try-ios: [success](https://vulcan.livecode.com/builders/try-ios/builds/258)
- try-android-armv6: [success](https://vulcan.livecode.com/builders/try-android-armv6/builds/324)
- try-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-linux-x86_64/builds/259)
- try-mac: [success](https://vulcan.livecode.com/builders/try-mac/builds/249)

**Pull request merged**
