### PR TITLE
[[ Bug 17247 ]] Include dirty rect of children in dirty rect of group

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4d94321

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4d94321e7a97ffd1d8dae4392696271f50d2df6b

**Comment by livecode-vulcan** [comment]
😞 test failure 4d94321e7a97ffd1d8dae4392696271f50d2df6b
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2222)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2230)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2215)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2231)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/2237)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2242)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2253)

**Comment by livecodeali** [comment]
@livecode-vulcan retry 4d94321

**Comment by livecode-vulcan** [comment]
😞 test failure 4d94321e7a97ffd1d8dae4392696271f50d2df6b
- try-community-linux-x86: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2233)
- try-community-mac: [pending](https://vulcan.livecode.com/builders/try-community-mac/builds/2241)
- try-community-linux-x86_64: [pending](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2226)
- try-community-emscripten: [pending](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2242)
- try-community-ios: [failure](https://vulcan.livecode.com/builders/try-community-ios/builds/2248)
- try-community-win-x86: [pending](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2253)
- try-community-android-armv6: [pending](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2264)

**Comment by peter-b** [comment]
@livecode-vulcan retry 4d94321

**Comment by livecode-vulcan** [comment]
😎 test success 4d94321e7a97ffd1d8dae4392696271f50d2df6b
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2250)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2259)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2243)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2260)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2266)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2271)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2282)

**Pull request merged**
