### PR TITLE
[[ Resolve File ]] Implement resolve file relative to object

### PR DESCRIPTION
**Pull request by montegoulding**
This patch implements a new LCB statement to resolve a file path relative to a
script object in the same way that relative file paths are resolved in LiveCode
script.

### CODE REVIEW

**Comment by runrevmark** [comment]
@montegoulding I wonder if (when in a widget) if there is no 'relative to' then it should use the widget's script object. Obviously for libraries, there is no current widget to use, so defaultStack makes sense. There's actually an issue in 'image from path' in the canvas library which assumes there is a current widget - perhaps we need a general handler in the engine to get 'current object context'?

**Comment by livecodeali** [comment]
That would fit with the send/post behavior which does exactly the same thing.

**Comment by montegoulding** [comment]
Ok

**Comment by montegoulding** [comment]
@runrevmark I have resolved [anomaly 19137](https://quality.livecode.com/show_bug.cgi?id=19137) here for the sake of consistency/sanity.

**Comment by montegoulding** [comment]
Hmm... I just noticed the mentioned issue for `image from file`... will look into it.

**Comment by montegoulding** [comment]
rebased and fixed some missing intents in the syntax declaration

**Comment by runrevmark** [comment]
This needs tests for all the cases touched:
  - image file resolution in widgets and in libraries
  - execute script/send/post in widgets and in libraries
  - resolve file in widgets and in libraries

**Comment by montegoulding** [comment]
We already have tests covering send & post in widgets and libraries and execute script in libraries.

I've just noticed another anomaly here. `the contents of file` is relative to the current directory (which there is no access to except via execute script BTW) while `image from file` is relative to the the current object context. I guess we have the same anomaly in LCS image fileName property v file paths so it makes sense.

**Comment by montegoulding** [comment]
I have now added the extra tests and think I have covered all the cases that need to be covered here

**Comment by runrevmark** [comment]
@montegoulding I don't think its quite right to lump all the context tests into a 'ContextObject' test as that is an internal abstraction - it would be better if the tests were split up by the features. In particular, we have a TestExtensionExecuteScript test (which still references anomaly 19137) - that should be made to ensure it covers the cases which this touches; and add the widget cases.

There seems to be a duplicate test for resolve file in both the EngineContextTest and the ResolveFileTest (maybe it is slightly different - but if so they should all be in the ResolveFileTest).

Similarly, the image from file tests should go in a TestExtensionImageFromFile test handler.

**Comment by runrevmark** [comment]
Also can you clarify how anomaly 19137 has been resolved? The widget case is obviously clear - it should be the widget's script object.... However, the suggestion made in the bug report for libraries was that it should be the script object which called the library handler - the rationale there is that execute script is do... If you called do from within an engine method it would use the script object which called the engine method; just as using do from LCS does. Maybe that is too big a change though...

**Comment by montegoulding** [comment]
OK I will reorganise the tests. Regarding 19137 I can't recall if I discussed it with you... was a while back. Anyway, my thoughts were:

- it's possible to execute script at the moment when there's no caller (in a foreign callback for example). At least script object access does not appear to be disabled for that (perhaps it should be?).
- if you want to execute in the context of the caller it's easy enough to do explicitly

I can change it to the caller if you like or change the note to saying it is resolved only for widgets, however, I think it would be good if the implicit object follows consistent rules for all syntax.

**Comment by runrevmark** [comment]
@montegoulding Okay - that's fine :) The key thing is that libraries can have foreign callbacks and so (as you point out) there is no consistent script object context, so using default card of default stack universally for libraries in this case is fine. As you point out, libraries can always use 'the caller' to explicitly specify they want to execute script in the calling script object :)

Perhaps add a note to the anomaly about the resolution (and reason why default card ... makes sense for libraries) - we can consider that anomaly resolved then :)

**Comment by runrevmark** [comment]
@montegoulding The tests look much better - thanks :) Last thing here can you add a section to the 'breaking changes' doc as there is a non-backwards-compatible change here.

**Comment by runrevmark** [comment]
@montegoulding I'm reviewing this as is for the moment as we need it in before we can merge the macstatusmenu feature... If you could submit a seperate PR with the breaking changes update that would be great.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 857a2fb

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 857a2fb4d9422a32abd494da5bada35140c223f5

**Comment by livecode-vulcan** [comment]
😎 test success 857a2fb4d9422a32abd494da5bada35140c223f5

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/518)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/510)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/510)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/510)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/510)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2032)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/260)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/259)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2064)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2054)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2052)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2087)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2024)

**Pull request merged**
