### PR TITLE
[Bug 16937] paletteactions: Improved appearance and configurability

### PR DESCRIPTION
**Pull request by peter-b**
Various changes and improvements to the paletteactions widget.
- Correctly clear hover status when the mouse leaves the widget
- Make appearance configurable via properties
- Improved theming abstraction

### CODE REVIEW

**Comment by peter-b** [comment]
Must merge with livecode/livecode-ide#999.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok bbf2ea3

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok bbf2ea3e3b45ef8a01e7622b97374065ba959cd4

**Comment by livecode-vulcan** [comment]
😎 test success bbf2ea3e3b45ef8a01e7622b97374065ba959cd4
- try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/2082)
- try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/2093)
- try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/2076)
- try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/2090)
- try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/2096)
- try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/2104)
- try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/2110)

**Pull request merged**
