### PR TITLE
[[ Bug 21955 ]] Fix diamond menu item mark on macOS

### PR DESCRIPTION
**Pull request by runrevmark**
This patch corrects an error in the builtin diamond TIFF image data
used for diamond (!r) menu item marks on macOS and makes the data size
constant implicit rather than explicit.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 74411d2

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 74411d26e6bc80e9661caef2b8715cc024e41724

**Comment by livecode-vulcan** [comment]
😞 test failure 74411d26e6bc80e9661caef2b8715cc024e41724

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/372)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/364)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/364)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/364)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/364)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1886)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/114)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/114)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1917)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1907)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1906)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1938)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1880)

**Comment by runrevmark** [comment]
This patch only affects mac, the win64 build succeeded fine and the win32 build failed due to a copy directory problem - so merging.

**Pull request merged**
